### ISSUE TITLE
User of deprecated preg_replace /e modifier

### ISSUE THREAD

**Issue by radekzak** [modxbot/migrate#10056]
radekzak created Redmine issue ID 10056

The xPDO class is using a deprecated /e modifier, triggering a deprecated warning messages.  Please refactor to use preg_replace_callback instead.

<pre>
Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in /var/www/devlin.local/theex/web/core/xpdo/xpdo.class.php on line 2643
</pre>

**Comment by oori** [comment]
oori submitted:

Fix:  https://github.com/modxcms/xpdo/commit/edbe094

**Comment by opengeek** [comment]
opengeek submitted:

Resolved for 2.3 via https://github.com/modxcms/revolution/commit/6e3325ed11d69c7cb2c94cd44ab47b0885a7e31e
