### ISSUE TITLE
add an @see getTree to the phpdoc of modX::getChildIds

### ISSUE THREAD

**Issue by jak** [modxbot/migrate#1013]
jak created Redmine issue ID 1013

When I was looking for a function to get the children of a node I found getChildIds but overlooked getTree. Both functions perform a similar purpose but have completely different names, so if you find one it is not obvious that the other exists.
I would suggest to add an "@see getTree" tag to the function getChildIds (and maybe also vice versa).

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6125
