### ISSUE TITLE
Chunk parsing bug (2.2.9)

### ISSUE THREAD

**Issue by andchir** [modxbot/migrate#10154]
andchir created Redmine issue ID 10154
1. [[Wayfinder@options]] - work
2. [[MySnippet@options]] - not work! (empty output)

MySnippet code:

<pre>
return $modx->runSnippet('Wayfinder', $scriptProperties);
</pre>

Problem appeared after this commit: https://github.com/modxcms/revolution/commit/779ef0581e403b8fc6e4c80f132e85174acc10f1#core/model/modx/modchunk.class.php
([#10007] Fix parser logic when processing elements via API)

Wayfinder 2.3.3.

&displayStart=`1`

wayfinder.class.php (327)

<pre>
$placeholders['wf.wrapper'] = $useSub;//[[+wf.wrapper.4]]
</pre>

wayfinder.class.php (358)

<pre>
$output .= $chunk->process($placeholders, $useChunk);
</pre>

Placeholder [[+wf.wrapper.4]] it is not (empty).

**Comment by andchir** [comment]
andchir submitted:

<pre>
1. [[Wayfinder@options]] - work
</pre>

<pre>
2. [[MySnippet@options]] - not work! (empty output)
</pre>

**Comment by opengeek** [comment]
opengeek submitted:

Please provide the contents of a your Chunk tpl's being used with Wayfinder.

**Comment by exside** [comment]
exside submitted:

This is related to: http://tracker.modx.com/issues/10211 and here is a temporary solution + details how to reproduce, ie reverting the change...https://github.com/roryg/ElementHelper/pull/16

**Comment by opengeek** [comment]
opengeek submitted:

See patch at https://github.com/modxcms/revolution/commit/5cd13cba13e52e888cff5a5209b4d88bb976daf5
