### ISSUE TITLE
Uncached snippet call in chunk is being cached anyway

### ISSUE THREAD

**Issue by bertoost** [modxbot/migrate#10202]
bertoost created Redmine issue ID 10202

I have a static template and I use a static header chunk. Inside my header chunk I call a snippet uncached (which is a static file too). This snippet should generate a unique number for the current session. But because the output is cached this way, the number isn't unique.

I had to reset all static elements back to normal elements to let this work. It was fixed already when I reverted the header chunk only as normal element (instead of static).

**Comment by opengeek** [comment]
opengeek submitted:

Can you confirm if this is only a problem if the static elements are using a Media Source?

**Comment by bertoost** [comment]
bertoost submitted:

This only occurs (just discoverd) when there is a Media Source linked to the static file. When having <none> selected, it's just fine. (discovered by Menno Pietersen)

[edit]
Sorry Jason.. just saw your comment.. and you're right

**Comment by opengeek** [comment]
opengeek submitted:

See patch at https://github.com/modxcms/revolution/commit/5cd13cba13e52e888cff5a5209b4d88bb976daf5
