### ISSUE TITLE
Checking "Is Static" without specifying Static File deletes the content

### ISSUE THREAD

**Issue by mhenry07** [modxbot/migrate#10219]
mhenry07 created Redmine issue ID 10219

I was attempting to save a non-static element (template/tv/chunk/snippet/etc) as a static element by checking the Is Static checkbox. I didn't choose a static file to write it to, figuring MODX would choose a sensible default and write it there. But when I clicked Save in the manager, it cleared the template/chunk/snippet code without warning.

Even if a Static File is required to be specified, it should check for one and warn before allowing the element to be saved in MODX.

**Comment by opengeek** [comment]
opengeek submitted:

Can you confirm this really occurs or provide very specific steps to reproduce it? I cannot reproduce this affect at all. If I do not specify a path, I get a validation error, which though not entirely accurate, is definitely not deleting the content I entered.

**Comment by opengeek** [comment]
opengeek submitted:

Regardless, this should be addressed for 2.3 via https://github.com/modxcms/revolution/pull/650
