### ISSUE TITLE
Set User Role to 'None' makes the access permission disappear from Grid

### ISSUE THREAD

**Issue by garryn** [modxbot/migrate#1023]
garryn created Redmine issue ID 1023

When adding Access Permissions to a user via the grid - create a user in the Administrator Group with a role of SuperUser. Save, and then edit the permission, change the role to 'None' and save. The access permission disappears from the grid, but the record remains in the database making it impossible to change back to a different role.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6032
