### ISSUE TITLE
updating user role not working?

### ISSUE THREAD

**Issue by zxie** [modxbot/migrate#1024]
zxie created Redmine issue ID 1024

After installing MODx Revolution 2.0.0-beta-4 I can log in with the admin user and password. Then I wanted to create another admin user. I did so by creating a user then added it to the Adminnistrator user group. It's role remained member though so I went to "Security" -> "Manager Users" -> Right click on the user then "Update User" -> "Access Permission" -> Right click on the User Role then "Update User Role" -> Select "Superuser" instead of "Memeber", then save. I check the db table, the role wasn't changed: mysql> select \* from modx_member_groups;
 --- ---------- ------ -----+ id user_group member role --- ---------- ------ -----+ 1 1 1 2 2 1 2 1 3 1 3 1 --- ---------- ------ -----+
3 rows in set (0.00 sec) If I tried to log in as the newly created user I got a permission denied error. Only when I manually changed the role to 2 in mysql I was able to log in.

**Comment by splittingred** [comment]
splittingred submitted:

Already fixed in a prior revision.
