### ISSUE TITLE
Creating/Updating Users - Password min length bug and server-side validation not returning errors to browser

### ISSUE THREAD

**Issue by garryn** [modxbot/migrate#1032]
garryn created Redmine issue ID 1032

When creating or updating a user via the GUI, there is a bug in the current beta that causes a mismatch between the client-side allowed minimum password length (JS validation) and the server-side minimum password length (specified in System Settings) when the 'Let me specify a password' option is selected. For example, currently the minimum password length allowed in the JS is hardcoded to 6 but the System Setting value is set at 8 on a default install. This means that the JS validation can be passed but the server-side will produce an error. Simple fix is to ensure the JS uses the system setting value (in modx.panel.user.js) This brings to light another (in my opinion critical) bug, in that the server-side validation doesn't correctly return a failure if errors were encountered during the validation. This is due to the return value from the _validation.php include not being checked or utilized. This creates the loophole where the user is created, with no errors and also no password!

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6025
