### ISSUE TITLE
When you create 2 folders with the same attribute keys in them you cannot edit the first value in the user's "Extended Fields"

### ISSUE THREAD

**Issue by dimmy** [modxbot/migrate#10371]
dimmy created Redmine issue ID 10371

When you create 2 folders with the same attribute keys in them you cannot edit the first value in the user's "Extended Fields" Steps to reproduce: Go to a user Create 2 folders in the Extended Fields In each folder create an attribute with the same key, "color" for instance Try to edit both values, the grid will always select the second color so the
first is out of reach.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/97ac6ee076d449b86d2a592a252054cdc06d09ed

**Comment by splittingred** [comment]
splittingred submitted:

Reopening, still broken if:

extended.subkey1.key
extended.subkey2.key

The DOM id's are the same for the 2nd-level "key", preventing editing, even though they are different.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/e3faad9ce66f301d8a9952fc87d934047b2aedfd
