### ISSUE TITLE
Site | Search Order by description appears to not work when fields are empty

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#10376]
wshawn created Redmine issue ID 10376

In one of my test sites I have only a few resources with descriptions. The vast majority have empty descriptions. In this situation, the ascending and descending option appear to be grayed out. The rest of the columns work as expected, as those columns all have complete data sets.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/55c133a546d096afc62276eaceec6135fe2ae884
