### ISSUE TITLE
RTL display of resource ID broken

### ISSUE THREAD

**Issue by ghost** [modxbot/migrate#10373]
sottwell created Redmine issue ID 10373

The resource ID in the Tree is broken if the pagetitle is RTL: 4)string) http://modxcms.com/forums/index.php/topic,55444.msg319208.html#msg319208

**Comment by splittingred** [comment]
splittingred submitted:

Deferring to 2.1.0, since this seems to be a rendering issue with ExtJS.

**Comment by j16sdiz** [comment]
j16sdiz submitted:

This is not a ExtJS specific-issue. This is the unicode RTL algorithm. You have to ovrride the extjs render and wrap the id with @<span dir="ltr">@ like this:

<pre>
   <span> rtl-text-string   <span dir="ltr">(10)</span> </span>
</pre>

from firebug I can see you are sending the whole text as a string. I guess you can hack around this using regex matching the @(\d+)@.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/4a122219a763f6c872dc14391b2ac8f07d0635a4
