### ISSUE TITLE
Context name converted to HTML entities in context management

### ISSUE THREAD

**Issue by ghost** [modxbot/migrate#10374]
sottwell created Redmine issue ID 10374

The context name is in Hebrew (?????), and in trying to edit the context to add the cultureKey in its settings, the name is converted to HTML entities and the context cannot be found. The name shows up fine in the Tree, and appears to be just plain text in the database as well. http://modxcms.com/forums/index.php/topic,52869.msg319053.html#msg319053

**Comment by splittingred** [comment]
splittingred submitted:

What charset is that language string in? Mine shows up as ?????.

**Comment by ghost** [comment]
sottwell submitted:

utf8

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/01c5648629e8f51197f4f004b9fdf9cb2a0dd9e1
