### ISSUE TITLE
Menu Index auto increment over multiple contexts bug

### ISSUE THREAD

**Issue by multimedia** [modxbot/migrate#10380]
multimedia created Redmine issue ID 10380

i noticed a small bug with automatic menuindex increment over multiple contexts. lets say i have 10 contexts with each 1 resource "home" and all have menuindex 0 when i add a new resource anywhere the menuindex that is generated will be 10 instead of 1

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/7e799357615ed3d4310eceb14426f7dba3886fcd
