### ISSUE TITLE
Ability to condense Form Customization rules with comma-separated lists of values (or similar)

### ISSUE THREAD

**Issue by kenquad** [modxbot/migrate#10386]
kenquad created Redmine issue ID 10386

It would be more efficient if multiple values could be put into "constraint field", and "value", possibly with a comma-separated list. You could then, for instance, hide multiple TV's on certain templates with just one rule - where several would currently be required to accomplish the same thing.

**Comment by adamwintle** [comment]
adamwintle submitted:

I thought this was already possible? 

I've been able to group multiple values (e.g. pagetitle, menutitle, alias) for _some_ Form Customisation rules, but it has seemed buggy

**Comment by splittingred** [comment]
splittingred submitted:

No longer valid with new FC UI.
