### ISSUE TITLE
Search or filtering on forms customization rules

### ISSUE THREAD

**Issue by kenquad** [modxbot/migrate#10387]
kenquad created Redmine issue ID 10387

It would be very helpful to have some kind of filtering or search for FC rules - similar to the way System Settings works. Once you get past 2 or 3 pages of rules, it gets hard to find the one you want.

**Comment by splittingred** [comment]
splittingred submitted:

Added in http://github.com/modxcms/revolution/commit/4574274526d3fa3f4ef295fac72f621180e7d64a
