### ISSUE TITLE
Turn Most Popular/Recently Added list of packages into hotlinks for those items

### ISSUE THREAD

**Issue by mconsidine** [modxbot/migrate#10382]
mconsidine created Redmine issue ID 10382

The existing lists are useful but would be more so if one could click on a package title and be taken to that item, rather than having to figure out where in the tree it might be or having to search for it.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/ce4cc8f36da1cfa92c364b629849fe3874021814
