### ISSUE TITLE
system preferences overwritten after core upgrade

### ISSUE THREAD

**Issue by gerritvanaaken** [modxbot/migrate#10388]
gerritvanaaken created Redmine issue ID 10388

After upgrading from 2.0.0 to 2.0.2, and from 2.0.2 to 2.0.3, I had to manually define the "filemanager_path" preference once again. It was overwritten by the update. No drama, but this should be fixed.

**Comment by splittingred** [comment]
splittingred submitted:

Duplicate of http://bugs.modx.com/browse/MODX-2380 which is already fixed.
