### ISSUE TITLE
Allow Symlinks metadata to override target Resource metadata

### ISSUE THREAD

**Issue by jgestiot** [modxbot/migrate#10389]
jgestiot created Redmine issue ID 10389

The page title, summary, template variables (etc...) of the symlinks do not override the page title, summary and template variables of the resource pointed to by the symlink. My understanding of symlinks is that they borrow the content of a static resource while maintaining their own published state, page title and other such resource fields. This does not appear to work. At the moment, a symlink appears to work as a redirection and all its fields are ignored.

**Comment by mikrobi** [comment]
mikrobi submitted:

Maybe it would be helpful if the values of these fields (page title, summary,etc...) are inherited from the symlink target page when they are not set in symlink resource?

**Comment by opengeek** [comment]
opengeek submitted:

See resolution commit details at https://github.com/modxcms/revolution/commit/d508c023d6f5537ac9555523e3bfb78abce62f83 and https://github.com/modxcms/revolution/commit/3ba0710882c765e6269a595b6d1f8faefe694ee7
