### ISSUE TITLE
Alert if we try to exit from an unsaved element/resource

### ISSUE THREAD

**Issue by maxpiepenbrink** [modxbot/migrate#10393]
mido created Redmine issue ID 10393

If we start editing an element or resource and we click anywhere else ( other element/resource, other link, etc. ), MODx redirects to the link. It will be so usefull to warn user about he is exiting the page without saving changes and all the data will be lost if continue.

**Comment by splittingred** [comment]
splittingred submitted:

Duplicate of http://bugs.modx.com/browse/MODX-2182 (edited)

**Comment by maxpiepenbrink** [comment]
mido submitted:

I think both are different issues...

**Comment by maxpiepenbrink** [comment]
mido submitted:

Different issues

**Comment by splittingred** [comment]
splittingred submitted:

Oops, was wrong link: http://bugs.modx.com/browse/MODX-2182
