### ISSUE TITLE
Minimum role problem for Resource Policy

### ISSUE THREAD

**Issue by kirkhuyser** [modxbot/migrate#10390]
kirkhuyser created Redmine issue ID 10390

The minimum role of Super User-0 for Resource Access Policy, context Mgr, is not sufficient to allow admin user to add children to a resource. The admin user is a member of Administrator group and admin's role is Super User. A minimum role lower than 0 must be selected to allow this permission.

**Comment by splittingred** [comment]
splittingred submitted:

Did you flush the permissions? Try logging out/logging in after adding the ACL? I have no problem adding children Resources, with a Super User role. This seems like a problem with your ACLs.
