### ISSUE TITLE
Form Customisation resource/create not applying some rules when using a Constraint

### ISSUE THREAD

**Issue by adamwintle** [modxbot/migrate#10392]
adamwintle created Redmine issue ID 10392

See this forum post:
 http://modxcms.com/forums/index.php/topic,55241.msg318018.html#msg318018 When applying a contraint to a new document, e.g. forcing a different template onto a newly created Resource, some of the other rules are not applied. Maybe this is due to the order which the rules are fired in? Hope that makes sense. Maybe it would be useful to have a resource/create/update Action for people wanting to make rules which apply to both?

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/a00398819b79447eed3a377cee77de2ae4c57115
