### ISSUE TITLE
Autoassign default template when create new TV

### ISSUE THREAD

**Issue by maxpiepenbrink** [modxbot/migrate#10397]
mido created Redmine issue ID 10397

When creating a new TV no template is assigned. Is to easy to forget to assign a TPL to a TV ( and it is in other tab ). In this case I think MODx can: Check by the default the default template
or Warn user about it, giving the option to assign the tpl.

**Comment by splittingred** [comment]
splittingred submitted:

This would be best done with a Plugin, and won't be in the core. It would cause more issues than solve.
