### ISSUE TITLE
Creating of user specific settings not possible

### ISSUE THREAD

**Issue by bentrax** [modxbot/migrate#10396]
bentrax created Redmine issue ID 10396

When creating a new user specific setting and hitting save in the creation dialog the saving progress bar comes up and does some progress but infinte. If you reload the manager nothing is saved.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/274f687625e72653241835b502366d4dd9ad3e2d
