### ISSUE TITLE
Installing multiple packages in one session does not reset the license agreement selection nor other pre-install forms

### ISSUE THREAD

**Issue by bentrax** [modxbot/migrate#10394]
bentrax created Redmine issue ID 10394

When you install one package and another afterwards the license agreement selection is the same a before.
This might be ok since you can only proceed if you accept and then you don't have to accept the next one too and can "proceed" right after the form is displayed. I don't know if thats intention. But when a package brings up another form to set special install requirements, I think Quip and some others do this, then the package you install afterwards brings up the same dialog even it is not needed for that package.
This can't be intended.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/ce0984d9476c4aa46c50f23cae1649d317316883
