### ISSUE TITLE
core/cache/smarty not cleared!

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1039]
bobray created Redmine issue ID 1039

I finally figured out why fixed issues are still appearing on my site for a few days after an upgrade install. The /core/cache/smarty directory isn't cleared for me when the cache is cleared. Immediatly after a cache clear, it still had two files in it that were over a week week old. Those files had survived several upgrade installs and dozens of cache clear events. When I deleted them, I saw the bug fixes in the Manager.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6034

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed
