### ISSUE TITLE
Move resource (with additional child resources) from one context to another fails to move child resources

### ISSUE THREAD

**Issue by gavro** [modxbot/migrate#10409]
gavro created Redmine issue ID 10409

When I try to move a resource (drag & drop) to another context the resource gets moved properly. The thing is: if this resource has child resources, you can't expand the moved resource to reach the child resource and edit them. You have to move it back, pull out every resource, move all resources, then pull them back in again. Could this be a caching thing, a background worker? I've tried emptying modx cache, browser cache, refresh in other browser, wait a while. No success.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/0a5f3e8bda1128408adcbeea15b712961263baab
