### ISSUE TITLE
Permissions required for resource Delete and Undelete seem transposed

### ISSUE THREAD

**Issue by martinf55** [modxbot/migrate#10404]
martinf55 created Redmine issue ID 10404

Noticed on an upgraded installation with custom policies lacking undelete_document. It seems like managers need undelete_document for the Delete Resource menu to appear, and delete_document for the Undelete Resource menu to appear. See modx.tree.resource.js: if (ui.hasClass('pdelete') && ui.hasClass('deleted')) {
m.push({ text: _('resource_undelete') ,handler: this.undeleteDocument });
} else if (ui.hasClass('pundelete')) {
m.push({ text: _('resource_delete') ,handler: this.deleteDocument });
}

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/491afc7bd88fdc536889b50837c881d85382c4fe
