### ISSUE TITLE
Change resource type

### ISSUE THREAD

**Issue by maxpiepenbrink** [modxbot/migrate#10408]
mido created Redmine issue ID 10408

Now to change the resource type of a document we have to change the classKey field from modDocument/modResource to modWebLink ( not documented: http://modxcms.com/forums/index.php/topic,54989.0.html ). It would be better to change it using a dropdown or simmilar.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/52325e6fde4479cfab9944c09dc2f0169b05b491 (rebuild/upgrade required)
