### ISSUE TITLE
Certain settings erased on upgrade

### ISSUE THREAD

**Issue by deribas** [modxbot/migrate#10403]
deribas created Redmine issue ID 10403

At updating variables are cleared filemanager_path
filemanager_url
rb_base_dir
rb_base_url MySQL client Version: 5.1.49
MySQL client Server: 5.1.49-1
Apache Version Apache/2.2.16
PHP Version 5.3.2-2 Browser : IE 8.9.7600.16385

**Comment by onepack** [comment]
onepack submitted:

I have the same issue also discussed at: http://modxcms.com/forums/index.php/topic,55123.0.html The next values were not filled at install 2.0.0 and again cleared after every upgrade like 2.0.2 and 2.0.3. filemanager_path
filemanager_url
rb_base_dir
rb_base_url Setup:
MODx: 2.0.3-pl
Apache/2
mysql Client API version: 5.1.42
php:5.2.12
Database version:5.1.42-log (Zend Engine:v2.2.0)
(PDO Driver for MySQL, client library version: 5.1.42) Modzilla Firefox: 3.6.10

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/020f49691d2c1d34df7ac9d7e6727b56589ca508
