### ISSUE TITLE
Changes to rank on template variable screen of template editor do not save

### ISSUE THREAD

**Issue by kenquad** [modxbot/migrate#10400]
kenquad created Redmine issue ID 10400

Since upgrading to 2.0.2-pl, changes made to 'rank' in the template variable section of the template editor simply do not save. I have had to change these values manually in the db table modx_site_tmplvar_templates

**Comment by splittingred** [comment]
splittingred submitted:

Related to http://bugs.modx.com/browse/XPDO-74

**Comment by opengeek** [comment]
opengeek submitted:

Fixed for 2.0.4
