### ISSUE TITLE
Toolbar with action buttons not displayed correctly in IE 7

### ISSUE THREAD

**Issue by mikrobi** [modxbot/migrate#10405]
mikrobi created Redmine issue ID 10405

In my IE 7 Browser the toolbar with action buttons "Save", "Cancel", etc. is not displayed on the right hand side. It's displayed on the left directly on top of the resource-browser.

**Comment by mikrobi** [comment]
mikrobi submitted:

Toolbar with action buttons on the left in IE7

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/dacd383b2b5df4b7eb0a5cb57e7863073084703c
