### ISSUE TITLE
Updating Context Settings broken on GIT

### ISSUE THREAD

**Issue by xpix** [modxbot/migrate#10407]
xpix created Redmine issue ID 10407

Updating Context Settings doesn't work.
If you double click the value of an existing setting, click outside and save and later return to the Context Settings tab the value is not avalable Same for using Right Click/Update menu More here: http://modxcms.com/forums/index.php/topic,55008.0/topicseen.html

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/6ae47b1e78e136afbef63a85356f9979944ef96d

**Comment by xpix** [comment]
xpix submitted:

I can't get the latest changes using git clone http://github.com/modxcms/revolution.git Can you pls advise me on the process of getting the latest changes. Thanks

**Comment by splittingred** [comment]
splittingred submitted:

See: http://rtfm.modx.com/display/revolution20/Git+Installation GitHub might have been down when you were trying to get to it.

**Comment by xpix** [comment]
xpix submitted:

It seems that the master branch is still the old one. I can see that core/docs/changelog.txt was not updated. If I change the brach to 2.0 I can see the 2.0.3 changes. Hopefully I make sense. I will try to force a download for the 2.0 branch As you can see my GIT is not that good
