### ISSUE TITLE
Publishedon always reset on save for resources with Edit or Quick Update

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1040]
bobray created Redmine issue ID 1040

For resources, publishedon seems to always equal editedon. It appears to be updated on every save, rather than when pub status changes from 0 to 1. resource/update.php uses time() for the publishedon date if $_POST &#91;&#39;publishedon&#39;&#93; is empty. So either update should check for a change in published status before messing with publishedon, or we should make sure $_POST &#91;&#39;publishedon&#39;&#93; is not empty.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6018

**Comment by BobRay** [comment]
bobray submitted:

publishedon still always equals editedon for me and is updated on every save.

**Comment by BobRay** [comment]
bobray submitted:

No longer happening.
