### ISSUE TITLE
Package manager update logic incorrectly identifies updates. 

### ISSUE THREAD

**Issue by pulse-xx** [modxbot/migrate#1041]
pulse created Redmine issue ID 1041

When right clicking a package and clicking update, the updater seems to only check the suffix of the package to verify it is indeed an update. To reproduce this, install tinymce-3.2.7.0-beta1 and then attempt to update it. The package manager will present tinymce-3.2.0.1-beta3 as an update, when it is clearly a lower version.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed.
