### ISSUE TITLE
Fora new version of MODx Revo every user of the MODx Manager has to clear the browser cache - because of javascript caching

### ISSUE THREAD

**Issue by blackraven** [modxbot/migrate#10415]
blackraven created Redmine issue ID 10415

Currently, the browsers do not see a difference between javascript code for MODx Revolution 2.0.0 and version 2.0.2, which means that the 2.0.0 cache is used while running 2.0.2 (and the other way around).
This causes problems for the users. Those problems are solved after the browser-cache is cleared - but they probaly come back when a user works with the manager for an older version again. It is possible to make sure that these problems do not occur for future versions of the MODx-Manager. See the links below for some suggestions: http://www.spiderstrategies.com/blog/index.php/2007/02/smart-javascript-caching/ http://verens.com/2008/04/09/javascript-cache-problem-solved/

**Comment by splittingred** [comment]
splittingred submitted:

This has already been addressed in a prior commit: http://github.com/modxcms/revolution/commit/38dd28d9ee38e301b11009a1e159b8626d86028f
