### ISSUE TITLE
Image TV thumbnails don't get cleared after setting emptying the TV value

### ISSUE THREAD

**Issue by nomark** [modxbot/migrate#10410]
nomark created Redmine issue ID 10410

Steps to reproduce:
1. Edit a page
2. Use the MODx Browser to select an image to set the Template Variable value
3. Save the page
4. Clear the TV value, by selecting all the text and hitting delete/backspace
5. Save again
6. The TV value is empty (as expected), but the thumbnail remains there If I reload this page the thumbnail is gone...

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/9db28b8fffaeff6c91bee21cd2d4495ab047bbc8
