### ISSUE TITLE
Cannot set Property set to Event for Plugin

### ISSUE THREAD

**Issue by juro** [modxbot/migrate#10412]
juro created Redmine issue ID 10412

When trying to set Property set to Plugin event, after saving all changes are lost. Sometimes even another, not related event is set. AFAIK this is the only way how to set Plugin properties (TinyMCE) other than changing the default set.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/37d47dab5020333438c44fcd7a768ba12323c8cf

**Comment by juro** [comment]
juro submitted:

It's probably more complicated. Now I can set Property set (PS), but cannot unset it. In Events data grid when editing event's PS, drop-down menu has two bugs: it shows all defined PSs, not only those associated with that Plugin it doesn't show "Default" option, so once set, you can't revert back do Default One can try to click "Update Plugin Event" on the event. In pop-up dialog drop-down menu is OK (Default+associated PSs), but saving in this window does nothing. Event worse is that it seem that assigning PS in this way to plugin doesn't work. When set, plugin probably doesn't receive ANY properties (or at least doesn't receive default props). Not sure whether to create another bug about this.

**Comment by juro** [comment]
juro submitted:

As of my previous comment, property sets for plugins unusable

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/6dd6852534ca42acb8293661bd9c1bb417bebb4b
