### ISSUE TITLE
OnResourceTVFormRender

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10420]
bobray created Redmine issue ID 10420

This may be unavoidable, but it looks like this event fires before the form is rendered and there is no Prerender event for the TV tab that I can find. If this can't be moved, maybe it should be called OnResourceTVFormPrerender?

**Comment by splittingred** [comment]
splittingred submitted:

It's definitely fired after the form data is collected (no OnFormRender events really fire before the form is rendered, but after the data is collected. BeforeRender events fire before data is collected.)

**Comment by BobRay** [comment]
bobray submitted:

Got it. Shouldn't there be an OnResourceTVFormPrerender event?

**Comment by splittingred** [comment]
splittingred submitted:

Yep. Fixed: http://github.com/modxcms/revolution/commit/9b0021b412831e598b64622267328c5016e006e4 Will need to rebuild/upgrade to see it.
