### ISSUE TITLE
Check box TV type encodes HTML tags

### ISSUE THREAD

**Issue by juro** [modxbot/migrate#10428]
juro created Redmine issue ID 10428

String in TV Input Option Values for check box TV type gets HTML encoded (gt, lt, amp, quot etc.), thus unable to use it as part of page's source code. Probably was working fine in 2.0.0 but I'm not sure.
Workaround for this is to use Drop-down list TV type with values Yes/No.

**Comment by splittingred** [comment]
splittingred submitted:

This is actually complex (and definitely would have happened in 2.0.0). Putting straight HTML into forms like that isn't easy, as it has to encode it so it can go in the value="" attribute on the input field. That said, if we just decode it before saving, then we prohibit people from putting entities into default values.

**Comment by juro** [comment]
juro submitted:

Certainly one must be careful with HTML entities and encode/decode them properly. But it seems strange to me, that filing the same values in TV's Input Option Values produces different results (encoded/not encoded) with different TV types.
Try this: say you have TV named "tv_title" with label "Show page title" which allows user to choose if he wants to see page title. So page template looks like this (simplified): <body>
[ &#91;_tv_title&#93; ]
[ &#91;_content&#93; ]
</body> Situation 1: tv_title is of type "Check Box" with Input Option Value: "show==<h1>[ &#91;_pagetitle&#93; ]</h1>". When checked page source code renders using &lt, &gt instead of <>. Situation 2: tv_title is of type "DropDown List Menu" with Input Option Value: "show==<h1>[ &#91;_pagetitle&#93; ]</h1>||hide== " and Default Value "<h1>[ &#91;*pagetitle&#93; ]</h1>". When set to "show" page source code code renders as expected "<h1>MY TITLE</h1>". What comes to my mind is that maybe Input Option Values is treated differently from Default Value. Because in situation 2 when tv is set to "show" it directly uses content of field Default Value (in fact, there is no record in the database).

**Comment by splittingred** [comment]
splittingred submitted:

Hm, interesting. I'll take a look from there.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/2fb307fd66be4ca21d710edf6d1ad7661ff07334 Can you confirm?

**Comment by juro** [comment]
juro submitted:

Seems ok now, thank you.
