### ISSUE TITLE
warning before set usergroup to context access (disappears in administrator-context-access)

### ISSUE THREAD

**Issue by ghost** [modxbot/migrate#10421]
stetus created Redmine issue ID 10421

When you give a usergroup access to a new created context, the context disappears in the System->Context-Menu in the menubar, when you're logged in as an administrator. You can't give the administrator-group context-access to that new context, as it doesn't appear in the „add context access"-dialogue. To fix that up, you have to give the new created usergroup administrator-policies, log in with that account and then you're able to assign the administrator-group to that new created context.
After that you have to re-login as an admistrator and remove the administrator-policy from the new-created usergroup. Maybe a litte warning if context access isn't set for Administrators would be appropriate?

**Comment by splittingred** [comment]
splittingred submitted:

Instead just ensured the Administrator user group always has Administrator/Resource Policies Access added to the Context when you try and add Context Access with another, lesser User Group. Basically prevents this from ever occurring. You will still, of course, have to Security -> Flush Sessions after adjusting access controls like this to get it to refresh your session with the new access permissions, but the Context will show back up after you do. http://github.com/modxcms/revolution/commit/ff21927ca421008bf1b9915e8f52eb2c2c1369c8
