### ISSUE TITLE
Resource tree doessn;t remember it's state in Chrome

### ISSUE THREAD

**Issue by juro** [modxbot/migrate#10423]
juro created Redmine issue ID 10423

After reloading page (e.g. after clicking on resource) the resource tree doesn't remember it's last state (although it's remember some older state). It's annoying again and again opening the same tree branches. Works fine in IE and FF. Seems to be related to 2.0.1 update (not sure), where more branches can be open at a time, but now not updating properly.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/d6e9a1f8849b5733515db6f535a63fe64fa7b9ef
