### ISSUE TITLE
Inconsistency in Resource delete and undelete events

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10425]
bobray created Redmine issue ID 10425

In the processors/resource/undelete.php processor, the delete and undelete events fire after the modified resource is saved. In the processors/resource/update.php processor for both resources and static resources, however, the same events fire before the resource is saved. There are no "before" events for delete and undelete that I can find.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed. They should come after save; logic adjusted in the update processors. http://github.com/modxcms/revolution/commit/d9b19a3e36c40ef7611a2880ddb834adfc2d3184
