### ISSUE TITLE
Failed Validator in Transport Package doesn't abort install

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10434]
bobray created Redmine issue ID 10434

When a validator returns false, the abort error message is printed, but the install continues. The element is not installed, but system settings are and the Console reports success. Package Manager also considers the package installed. Here is the Console output: /\* MODx Console Output
- @date 2010-09-20 14:05:36
  _/
  Attempting to install package with signature: captcha-3.2.0-beta1 Package found...now preparing to install. Grabbing package workspace... Workspace environment initiated, now installing package... Running PHP Validator. Checking for GD and FreeType: GD lib not found &#8211; install canceled xPDOVehicle validator failed: type php (C:/xampp/htdocs/gitfork/core/packages/captcha-3.2.0-beta1/modPlugin/74b704722914629ed180fda3a6af1526.preinstall-script.validator) Could not validate vehicle object of class modPlugin; criteria: Array
  (
  &#91;name&#93; => Captcha
  ) Successfully installed package captcha-3.2.0-beta1 /_ EOF _/
  *_***********************************
  Here is the Validator code (note the "x" before things it is looking for so they won't be found). <?php
  /*\* @package captcha Validator &#8211; checks for GD and FreeType
  _/
  /_ $oldLogLevel = $object->xpdo->setLogLevel(xPDO::LOG_LEVEL_INFO);
  $oldLogTarget = $object->xpdo->setLogTarget(XPDO_CLI_MODE ? 'ECHO' : 'HTML'); _/ $object->xpdo->log(xPDO::LOG_LEVEL_INFO,'Running PHP Validator.');
  switch($options &#91;xPDOTransport::PACKAGE_ACTION&#93; ) {
  case xPDOTransport::ACTION_INSTALL: $object->xpdo->log(xPDO::LOG_LEVEL_INFO,'Checking for GD and FreeType: ');
  $success = true;
  /_ Check for GD library _/
  if (function_exists('ximagegd2')) { $object->xpdo->log(xPDO::LOG_LEVEL_INFO,'GD lib found'); } else { $object->xpdo->log(xPDO::LOG_LEVEL_ERROR,'GD lib not found -- install canceled'); return false; }
  /_ GD is ok, check for necessary functions _/ $fs = array('imagettfbbox', 'ximagecreate', 'imagecolorallocate', 'imagettftext',
  'imagecolortransparent', 'imagedestroy', 'imagecreatefromjpeg', 'imagesx',
  'imagesy', 'imagecreatetruecolor', 'imagecopyresampled', 'imagecopymerge'
  );
  $object->xpdo->log(xPDO::LOG_LEVEL_INFO,'Checking for necessary functions'); foreach($fs as $f) {
  $object->xpdo->log(xPDO::LOG_LEVEL_INFO,'Checking for ' . $f . ' function: ');
  if (function_exists($f)) { $object->xpdo->log(xPDO::LOG_LEVEL_INFO,'OK'); } else { $object->xpdo->log(xPDO::LOG_LEVEL_ERROR,'Not found'); $success = false; }
  }
  if ($success == false) { $object->xpdo->log(xPDO::LOG_LEVEL_ERROR,'Configuration problem - install canceled'); return false; } else { $object->xpdo->log(xPDO::LOG_LEVEL_INFO,'No Problems -- installing CAPTCHA plugin'); } break;
  case xPDOTransport::ACTION_UPGRADE:
  $success = true;
  break; case xPDOTransport::ACTION_UNINSTALL:
  $success = true;
  break;
  } /_$object->xpdo->setLogLevel($oldLogLevel);
  $object->xpdo->setLogTarget($oldLogTarget); */ return $success;

**Comment by splittingred** [comment]
splittingred submitted:

Vehicle validators only validate a vehicle, so technically it works as expected. That said, we do need Package-level resolvers and validators. An xPDO ticket has been added here: XPDO-73 (now improvement #2404)

**Comment by BobRay** [comment]
bobray submitted:

Is there currently a way to completely abort the package install when a validator fails?

**Comment by splittingred** [comment]
splittingred submitted:

Not at this time. We're working on it.

**Comment by splittingred** [comment]
splittingred submitted:

Pushing the fix to this - which would be adding package-wide Validators and Resolvers - to 2.1, since adding that would be a new feature, and would not be compatible with the 2.0.x branch. IOW, if we added this and an Extra came out saying it was supported in 2.0 but used a Package-wide resolver, the resolver would not get executed in installs prior to this fix - ie, 2.0.3 and before. This would mean we'd have to say the Extra was 2.0.4+ compatible, but we have decided to make compatibility in Revo "minor release specific" to prevent compatibility bloat and keep new features out of patch releases. All that said, this will be a top priority for Revo 2.1.x.

**Comment by opengeek** [comment]
opengeek submitted:

**Comment by opengeek** [comment]
opengeek submitted:

Actually, I'm not sold on adding validators and resolvers to the transport after attempting some implementations. I did however introduce an xPDOVehicle attribute in the xPDO layer that will tell the xPDOTransport to abort installation if a vehicle with that attribute set to true fails to install.

This does not need to wait for 2.1 to be merged into Revolution IMO.

**Comment by opengeek** [comment]
opengeek submitted:

Ok, new features are in develop via commit http://github.com/modxcms/revolution/commit/aad50c3e62a7960c5728b60aec9b7a94b66678d1
