### ISSUE TITLE
Category field in template showing wrong value

### ISSUE THREAD

**Issue by juro** [modxbot/migrate#10436]
juro created Redmine issue ID 10436

When template is assigned to a category, on next opening the template Category field is showing the first available category (ID=1), not selected one. Thus after resaving the template it is assigned to wrong category. Other elements are working fine.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/0669184a2aa3e6322c0df5b80df7c2fda6932c71
