### ISSUE TITLE
can't close dialog window after clear cache done 

### ISSUE THREAD

**Issue by adhiarta** [modxbot/migrate#10433]
adhiarta created Redmine issue ID 10433

after clear cache i can't close dialog box

**Comment by BobRay** [comment]
bobray submitted:

I can confirm that the Console sometimes won't close (I think I saw it in uninstalling a component, but I can't remember for sure). The OK button is live but has no effect (FF 3.6.8).

**Comment by juro** [comment]
juro submitted:

I can confirm the issue, sometimes Console won't close, pressing OK button only refreshes underlaying resource panel (Chrome 6)

**Comment by splittingred** [comment]
splittingred submitted:

Added sanity check here: http://github.com/modxcms/revolution/commit/25b7e5c08dfa3c4ee317eb0408465a50c1e51cff
