### ISSUE TITLE
File Manager system settings ignored, imposing security risk

### ISSUE THREAD

**Issue by juro** [modxbot/migrate#10438]
juro created Redmine issue ID 10438

Uploadable file/image/media types system setting is ignored. Any user with file_upload permission can upload any type of file. So he can upload and execute any PHP script. Even if these settings work correctly, default value for upload_files includes php.
As a workaround .htaccess in "filemanager_path" physical directory and subdirectories can be used to prevent script execution of user uploaded files.
Also diferentiating uploaded files to file/image/media/flash seems to be obsolete (maybe MODx Evo legacy?), as you can upload any file anywhere within "filemanager_path". TinyMCE always open file browser at "filemanager_path", regardles if you are inserting image or link to a document.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/b5f252f1398e433c4090d9215ca23073878df7f6
