### ISSUE TITLE
Tables missing from some distros (access_category, categories_closure)

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10449]
bobray created Redmine issue ID 10449

The two tables modx_access_category and modx_categories_closure are missing from the DB in my installs of the Advanced and SVN versions. Several other users report the tables missing, one believes he installed the Traditional distro, but could be mistaken.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/8c0ca486b1671eb3dcf8775fe956abac045f29b6
