### ISSUE TITLE
Users override each other language setting for top menu

### ISSUE THREAD

**Issue by juro** [modxbot/migrate#10442]
juro created Redmine issue ID 10442

Top menu items (excluding "Home" item) are cached without respect to manager_language system or user setting. E.g. after clearing cache, user1 loads top menu with say manager_language="EN", user2 will also see menu in EN even if his own manager_language is different and vice versa.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/915c1ebb384cf1685677c52a4969c03054e2e66e
