### ISSUE TITLE
No way to tell Distro from inside Manager

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10448]
bobray created Redmine issue ID 10448

I can't find any way to tell the Traditional from the Advanced distribution from inside the Manager. Both show the same rev. numbers. Users may not know which one they downloaded so it would be good if there were a way to tell. Possibly something in Reports -> System Info if not on the main screen.

**Comment by opengeek** [comment]
opengeek submitted:

See https://github.com/modxcms/revolution/commit/8604310571ab3e75b05dc6c9b7312539a20de26b for commit details on the fix.
