### ISSUE TITLE
Login to Manager problem on some systems

### ISSUE THREAD

**Issue by kszyniu** [modxbot/migrate#10440]
kszyniu created Redmine issue ID 10440

When trying to login to manager or as a web user with Login package I have to refresh browser window after logging in for login correnctly.
I discovered the solution for the Manager is to change manager/controllers/default/security/login.php I have had fixed this problem by changing from:
$modx->sendRedirect($url,'','','full'); to:
$modx->sendRedirect(rtrim($url), "/"),'','','full'); so I had to remove the last "/" char from $url String. I does the same with web user login (front end user login), but I never tried to modify the Package.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/3c0b0f3ca65d517a7c1f86509be0a7cc980f9498
