### ISSUE TITLE
Resource Tree hides Child resource from owner if owner does not have permissions to parent resource.

### ISSUE THREAD

**Issue by timharris777** [modxbot/migrate#10445]
timharris777 created Redmine issue ID 10445

A user group that has permission to access a child resource but not the parent resource will not have the child resource show in the resource tree in the manager. To expound, I have the following resources: Parent 1
Parent 2
++ Child 1
++ Child 2
Parent 3 Parent and child resource permissions are given to superusers (0).
Child resource permissions under parent 2 are given to managers (5). Logging into mgr as a manager will not show the child resource. The child resources will only show in the resource tree to edit if permissions to Parent 2 have also been given to managers. It seems that there is a bug in the resource tree itself in the way it displays resources parent-child. I don't think it can physically display the child if their is no permission to display the parent. I say this because if I enter the direct link (URL/manager/?a=30&id=4) with the id of the child resource I can edit the child resource. However, it will not show in the resource tree because the parent is not visible. Is there any way to fix this issue with the way the resource tree displays?

**Comment by splittingred** [comment]
splittingred submitted:

Actually not a bug; you'll need to add `list` and `load` Permissions (or use the "Load, List and View" Policy) to those Resources in that Context to enable them to be 'seen' in the manager. Giving them list/load permissions for that user will enable the user to see them in the tree, but not edit the Resource.
