### ISSUE TITLE
MODx behind reverse-proxy

### ISSUE THREAD

**Issue by gour** [modxbot/migrate#10450]
gour created Redmine issue ID 10450

Recently I exprienced very stange problem when attempting to run MODx under Cherokee which is serving behind nginx serving as reverse-proxy. My Cherokee runs under local port xxxxx, and when using front-end, every URL was generated as http://domain:port/ . In the beginning I thought the problem is with Cherokee not supporting X-Forwared-For header, but after installing CMS Made Simple 1.8.2, Wordpress-3.0.1 and Joomla-1.5.20 and seeing that none of the packages has such problem and that the same problem is if I replace Cherokee with Lighttpd, I was convinced the problem is the with following code in ../core/config/config.inc.php: if (!defined('MODX_HTTP_HOST')) { if(defined('PHP_SAPI') && (PHP_SAPI == "cli" || PHP_SAPI == "embed" )) { $http_host='gour-nitai.com:62845'; define('MODX_HTTP_HOST', $http_host); } else { $http_host= $_SERVER['HTTP_HOST']; if ($_SERVER['SERVER_PORT'] != 80) { $http_host= str_replace(':' . $_SERVER['SERVER_PORT'], '', $http_host); // remove port from HTTP_HOST } $http_host .= ($_SERVER['SERVER_PORT'] == 80 || $isSecureRequest) ? '' : ':' . $_SERVER['SERVER_PORT']; define('MODX_HTTP_HOST', $http_host); } } I wrote about the problem in Forums . OpenGeek suggested some workarounds , but suggested to create ticket so that some better solution can be written in the future version of Revo. Sincerely,
Gour

**Comment by krisj** [comment]
krisj submitted:

I have a very similar problem.
I run MODx Revo 2.0.4-pl2 with Nginx reverse proxy in front of Apache.

First the installation process:

-i type in the http://site.com/setup/
-it times out with a rewritten url to http://site.com:8080/setup/index.php?action=welcome
-i had to add define('MODX_SETUP_URL', "http://site.com/setup/index.php"); to the setup/index.php file on line 60
-after this is done the setup went smooth

After that everything seems to be fine apart from the logging into the manager. Every time I am trying to log in:

-it times out with a url rewritten to http://site.com:8080/manager/
-when i delete the ":8080" part of the url and resubmit it logs into manager and I can continue without any further problems.

So it seems that only the login procedure is the falling point here.

I also notice that setup writes this to the core/config/config.inc.php

line 57:        $http_host='site.com:8080';

which should be         $http_host='site.com';

And investigating log files it seems that the login procedure uses a 301 redirect at some point which nginx seems to be having a problem with.

Hope this helps

Thanks,
Kris

**Comment by opengeek** [comment]
opengeek submitted:

I believe we just need to fix the login issue and provide a way to override the auto-detected $_SERVER['http_host'] setting which seems to be including port 8080 when reported by these web servers behind a proxy.

**Comment by krisj** [comment]
krisj submitted:

I would like to add that this issue (in my case) was just down to the server configuration. most likely nginx. I am on a different server now, running nginx in front of apache without any issues related to proxying that I can tell so far from install to use.

**Comment by opengeek** [comment]
opengeek submitted:

Does this still need to be implemented? I don't think it does if everyone agrees that the server should always report the front-end port used by the proxy.
