### ISSUE TITLE
MODx Revolution SEO Strict URL support

### ISSUE THREAD

**Issue by pixelchutes** [modxbot/migrate#10454]
pixelchutes created Redmine issue ID 10454

Please see this forum thread for more URL handling concerns in Revo: http://modxcms.com/forums/index.php/topic,53826.msg311119.html#msg311119 Excerpt: &#91;...&#93; Unfortunately Revolution still serves many possible URL variations for the exact same content: /alias.html - (Canonical)
/?id=1
/?id=1.
/?id=1.0
/?id=1.0000
/?id=1.000000000
/1
/1.
/1.0
/1.0000
/1.000000000 Unfortunately, the current handling is not very SEO "Strict" - Ideally all scenarios above would 301 Redirect to the Canonical URL: "/1" OR "/alias-name-here.ext" with FURLs enabled.

**Comment by opengeek** [comment]
opengeek submitted:

I'm heavily refactoring this to be more properly strict, but don't you think that ?id=1. ?id=1.0 etc. should return a 404 rather than 301 redirecting to whatever id is passed? And I'm also of the opinion that numerics and all ?id= parameters should be ignored when friendly_urls is enabled, IOW only look for ?q= when using FURLs and only look for ?id= when not using FURLs. Thoughts?

**Comment by pixelchutes** [comment]
pixelchutes submitted:

I definitely agree: 1., 1.0, etc should definitely 404 vs 301. As for extending the "strict" behavior, you bring up valid points regarding ?id= usage when FURLs are enabled. In my personal experience, I almost exclusively use FURLs, however there have been a few times that having "?id=x" support has really been helpful, not to mention convenient, during testing, etc. My personal preference would be having the option to enable/disable this functionality in Site Configuration, just in case a particular use case may require it...

**Comment by opengeek** [comment]
opengeek submitted:

Still trying to solve a few corner cases and work out how to make the id method configurable when friendly_urls is enabled. This is also going to be a significant enough functional change to warrant not including this in a patch release, i.e. 2.0.4.

**Comment by krisj** [comment]
krisj submitted:

really hoping this will make it into rc2 or pl. i have xed all my fingers and toes right now...
the priority I thought should have been higher. to me it is very important.

**Comment by opengeek** [comment]
opengeek submitted:

This is now fixed in develop for 2.2.0-rc1 — I introduced request_method_strict to ignore ?id= routing when enabled with FURLs (or ?q= routing when FURLs not enabled); this is not enabled by default, but the numeric requests making it through without the query string params are now always returning 404.

I also added the 301 response code to redirects for containers without the container_suffix and for the site_start uri.

**Comment by pixelchutes** [comment]
pixelchutes submitted:

Thanks for the update, Jason. This approach does accomplish the "strict" routing.

As I mentioned in the original post, "having ?id=x support has really been helpful, not to mention convenient, during testing, etc."

For example, when developing, it's nice to be able to pass ?id=X and go straight to a page, or place /index.php?id=x in a rewrite rule (vs. hard-coding the alias path).

Is it possible to make the HTTP status response code optional? (301 vs 404?)

The way the Evo plugin works today is it simply 301's to the canonical URL... I may just need to switch my way of looking at it, because I do think the 404 makes the most sense. However, I will admittedly miss the ?id=x "shortcut" -- FURLs or not.

**Comment by opengeek** [comment]
opengeek submitted:

The ?id=ID still works unless you enable request_method_strict, in which case only the q=URI is considered when routing. Making the ?id=ID requests 301 redirect is easy enough when request_method_strict is not enabled. See commit details for these additional adjustments at https://github.com/modxcms/revolution/commit/db08fb3c349fb783b2bea96203d88e4131165c02

**Comment by pixelchutes** [comment]
pixelchutes submitted:

That's it! This is exactly what I was thinking :)

I love the new strict option, or optionally having any valid URI correctly 301 redirected to the canonical URL (with FURLs enabled).

THANK YOU!

**Comment by opengeek** [comment]
opengeek submitted:

Cherry-picked for inclusion in 2.1.4-pl
