### ISSUE TITLE
SEO related -> sendRedirect() is missing parameter that was in EVO > 0.9.5

### ISSUE THREAD

**Issue by multimedia** [modxbot/migrate#10462]
multimedia created Redmine issue ID 10462

In MODx evolution > 0.9.5 the function sendRedirect() had 4 parameters. manager/includes/document.parser.class.inc.php
line: 63 -> function sendRedirect($url, $count_attempts= 0, $type= '', $responseCode= '') It seems that MODx revolution 2.0.0 only makes use of 3 parameters core/model/modx/modresponse.class.php
line: 194 -> public function sendRedirect($url, $count_attempts= 0, $type= '') core/model/modx/modx.class.php
line: 765 -> public function sendRedirect($url, $count_attempts= 0, $type= '') The request is bring back the responseCode parameter to the sendRedirect() function. Reason: Default php redirect is a 302 redirect = temporary redirect, search engines (like google) are not happy with those and might workout negative on the search result ranking. Instead 301 redirects = permanent redirect, are much better to use. This should be also able to be defined as parameter in FirstChildRedirect snippet.

**Comment by multimedia** [comment]
multimedia submitted:

For better SEO support the parameters to optional send with the redirect can be: HTTP/1.1 301 Moved Permanently HTTP/1.1 302 Found HTTP/1.1 303 See Other HTTP/1.1 307 Temporary Redirect without setting the parameter, a normal 'clean' redirect is automaticly handled as 302 redirect. also see: http://www.mattcutts.com/blog/seo-advice-discussing-302-redirects/

**Comment by opengeek** [comment]
opengeek submitted:

Added for 2.0.1-pl
