### ISSUE TITLE
@INHERIT value doesn't work for radio options, checkboxes, and DD lists

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1046]
bobray created Redmine issue ID 1046

With @INHERIT value: For radio options and checkboxes, the default value isn't set to begin with and Set to Default doesn't work at all. For DD-lists, Set to Default works but it sets the value to "@INHERIT value," instead of "value" and no default value is set initially. To reproduce: Set Input Option Values to red||blue||green
or
1==red||2==blue||3==green Set default value to: @INHERIT blue Set type to radio options, checkbox, or dd-List.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6146
