### ISSUE TITLE
Simplified Chinese lexicon

### ISSUE THREAD

**Issue by greentea** [modxbot/migrate#10460]
greentea created Redmine issue ID 10460

I have translated revolution-2.0.0-pl to Simplified Chinese. How to send it to you.

**Comment by jdearmas** [comment]
> greentea created Redmine issue ID 10460
> 
> I have translated revolution-2.0.0-pl to Simplified Chinese. How to send it to you.

I'm hoping you get an email alert on this and then we can talk about your username
