### ISSUE TITLE
Template variables do not reorder on resource editing page regardless of "sort order" or "rank" settings associated with them

### ISSUE THREAD

**Issue by kenquad** [modxbot/migrate#10461]
kenquad created Redmine issue ID 10461

Filing as a bug per this forum thread: http://modxcms.com/forums/index.php/topic,53906.0.html - exact details can be found there.

**Comment by splittingred** [comment]
splittingred submitted:

http://github.com/modxcms/revolution/commit/70a53040759611c616618758517d77fea0c07253
