### ISSUE TITLE
Option to turn off parsing for some elements

### ISSUE THREAD

**Issue by rickj** [modxbot/migrate#10464]
rickj created Redmine issue ID 10464

The parser will attempt to parse a tag anytime it finds [[. I'd like to turn off parsing when displaying modx code samples within chunks for example. Currently I'd have to use html entities. Could this also be a performance increase?

**Comment by splittingred** [comment]
splittingred submitted:

This can be done via a plugin. See: http://modx360.com/blog/2010/02/prevent-rendering-modx-tags-revo.html
