### ISSUE TITLE
Modx doesn't set default_template when creating resource in other contexts

### ISSUE THREAD

**Issue by Paprikas** [modxbot/migrate#10474]
paprikas created Redmine issue ID 10474

Modx doesn't select my default template when creating resource in other contexts in regular way. (quick way works well) To reproduce:
Create new template (id 2)
Create new context.
Add key default_template and set value 2
Try to create resource in new context.

**Comment by Paprikas** [comment]
paprikas submitted:

Not tested on 2.0 GA. But I think there will be same behavior.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/61d69c46c1184cb568e62c739ae0c787793dab31
