### ISSUE TITLE
Template Variable 'Input Option Values' aren't being displayed in manager panel

### ISSUE THREAD

**Issue by SiNNuT** [modxbot/migrate#10475]
sinnut created Redmine issue ID 10475

Running the latest 2.0 branch from Git in encounter the following problem:
I create a TV with input type check-box and Input Option Values, for example: blue||yellow||red After i save the new TV i can see that the option values are correctly stored in the modx_site_tmplvars table in the elements column.
When i create a resource i can set/choose the correct TV options but when i revisit the TV itself, the Input Option Values aren't being displayed/ the textbox is empty. Making a change to blue||yellow and saving does update the database so i guess it's purely a retrieve issue. Maybe related to http://github.com/modxcms/revolution/commit/3af196c396e7b13e7d7d58e59c8d05d0052465b2 ?

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/d4ae4ac6a2dd7b23c975bb2264bb9ba72c161855
