### ISSUE TITLE
Failed validator in Transport Package craps up Console

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10476]
bobray created Redmine issue ID 10476

If a PHP validator returns false, the GPL, the readme, and a bunch of other stuff is appended to the Console output. If a LOG_LEVEL_FATAL message is logged, this doesn't happen, but the OK button is dead and there's no way to close the Console. A close button on the Console might be a quick fix, but I think this problem also occurs when there is any error in the uninstall. Steps to reproduce: Get the Captcha package from the SVN components directory.
Edit the preinstall-script.php validator in the _build directory and change the name of one of the functions it's looking for.
Build and install it. To see the other problem, change the appropriate LOG_LEVEL_ERROR message to LOG_LEVEL_FATAL.

**Comment by splittingred** [comment]
splittingred submitted:

FATAL will always kill the process and should never be used in a validator. The ERROR issue needs to be fixed by regressing the error message in xPDOTransport to a DEBUG log call.

**Comment by splittingred** [comment]
splittingred submitted:

Debug message needs to be adjusted before 2.0.1; escalating to Blocker to prioritize.

**Comment by opengeek** [comment]
opengeek submitted:

Log messages are now greatly condensed in install and uninstall operations

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed. But package is still considered "installed" will report a separate bug.
