### ISSUE TITLE
Checking chunk option 'Clear Cache on Save' doesn't work

### ISSUE THREAD

**Issue by SiNNuT** [modxbot/migrate#10478]
sinnut created Redmine issue ID 10478

When creating a chunk with 'Clear Cache on Save' option checked this doesn't seem to get saved. On first save it seems fine, option is checked, but when revisiting the chunk from the tree menu the option is unchecked. This behavior only occurs on chunks.
Running on 2.0.1-pl from GIT, updated until 2010-08-20.

**Comment by SiNNuT** [comment]
sinnut submitted:

forgot to mention:
tested on FF 3.6.8 and Chrome 5.0.375.127

**Comment by splittingred** [comment]
splittingred submitted:

It's not supposed to be stateful; never was in Evo, wont be in Revo. It allows for you to one-time save a resource without clearing the cache.
