### ISSUE TITLE
Quirky url handling

### ISSUE THREAD

**Issue by rfoster** [modxbot/migrate#10471]
rfoster created Redmine issue ID 10471

Revolution handles friendly urls in a funny way. You can type in crazy urls, and it will serve a "random" page rather than a 404 IF the first few characters are a number that is a valid, published resource id. Example:
 http://www.mysite.com/4I-can-typeANYTHING_IwantTO ^afterthenumber.whatever Will load the resource with id 4. My initial thought is that if the "q" url parameter does not contain a valid alias a 404 should be returned (requests for a specific resource by id should use the id url param).

**Comment by rfoster** [comment]
rfoster submitted:

At minimum should change 'GetResource' (in modrequest) to check
if (intval($resourceId)!==$resourceId || !intval($resourceId)) { $this->modx->sendErrorPage(); }

**Comment by BobRay** [comment]
bobray submitted:

Nice catch. Try modxcms.com/25-IReallyHateGnu

**Comment by BobRay** [comment]
bobray submitted:

I think if (!is_numeric($resourceId)) will do it. I've issued a Git pull request for that fix.

**Comment by pixelchutes** [comment]
pixelchutes submitted:

Please see this forum thread for more URL handling concerns in Revo: http://modxcms.com/forums/index.php/topic,53826.msg311119.html#msg311119 Excerpt: &#91;...&#93; Unfortunately Revolution still serves many possible URL variations for the exact same content: /alias.html - (Canonical)
/?id=1
/?id=1.
/?id=1.0
/?id=1.0000
/?id=1.000000000
/1
/1.
/1.0
/1.0000
/1.000000000 Unfortunately, the current handling is not very SEO "Strict" &#8211; Ideally all scenarios above would 301 Redirect to the Canonical URL: "/1" OR "/alias-name-here.ext" with FURLs enabled.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/78bdd1882c66a1c9078a064bd842ce6ed9b04e82 Mike, can you open a separate issue for the Strict URLs? That will have to be a feature request.

**Comment by pixelchutes** [comment]
pixelchutes submitted:

All set! http://bugs.modx.com/browse/MODX-2326
