### ISSUE TITLE
User Settings filemanager_path wont let upload files

### ISSUE THREAD

**Issue by eerne** [modxbot/migrate#10485]
eerne created Redmine issue ID 10485

Setting filemanager_path to assets/files under System Setting:
does display the correct files and upload to the specified directory works. Setting the same under User Settings:
does display the correct files BUT uploading gives following error:
"the specified directory is not a directory"

**Comment by eerne** [comment]
eerne submitted:

Hi I just ran into an other possible related bug, where phpthumb not created preview thumbnails in the file browser (the one that opens from tinymce). It was my fault and I could fix it with changing "assets/files" to "assets/files/" (with slash at the end) now I tried to reproduce the issue that I reported at first and found out that it is not related to User Settings filemanager_path directly. the issue should be reproducable with admin user and following conditions and steps: system settings filemanager_path = "assets/files/" NO filemanager_path user settings go to Files tab add/upload a file note: OK close upload panel right-click remove the just uploaded file add/upload a different file note: "the specified directory is not a directory" At this point I belive that after removing a file it wont let me upload again, until I logout and log back in .

**Comment by splittingred** [comment]
splittingred submitted:

This seems to have been fixed in the commit related to MODX-2309 .
