### ISSUE TITLE
New resource doesn't hold custom index setting upon first save

### ISSUE THREAD

**Issue by pixelstuff** [modxbot/migrate#10482]
pixelstuff created Redmine issue ID 10482

When creating a new resource and changing the index value from the default (example: 7 to 15), it will not keep the value upon initial save. However upon editing the existing resource and changing the index value, any new value will be retained.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/020709436a4e70ad140081569a52f0589c29c4e7
