### ISSUE TITLE
Ignore "continue editing" setting for user form

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1048]
bobray created Redmine issue ID 1048

If the Continue Editing" icon is set when editing a user or creating a new user, Save takes you back to the user form rather than the user grid. You have to click "Cancel" (or use the main menu) to get back to the grid. This would be annoying when editing a bunch of users and could confuse new users who couldn't figure out how to get back to the grid. IMO, it would be better if this were ignored there.

**Comment by splittingred** [comment]
splittingred submitted:

Done in r6011

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
