### ISSUE TITLE
RegClientCss does not work when called in a page that is cached and snippet is cached

### ISSUE THREAD

**Issue by kjaebker** [modxbot/migrate#10481]
kjaebker created Redmine issue ID 10481

If a snippet calls regClientCss on a page that is cached and the snippet is cached... the css gets loaded on the first request. Once the document goes into the cache the css file is no longer included. If you change the snippet to be uncached the css then gets included correctly on all requests. Wayfinder uses this method and I was able to reproduce it with that snippet.

**Comment by opengeek** [comment]
opengeek submitted:

Duplicate of # MODX-364
