### ISSUE TITLE
Deleting a TV should trigger clear-cache to remove TV values from resources

### ISSUE THREAD

**Issue by jrotering** [modxbot/migrate#10488]
jrotering created Redmine issue ID 10488

http://modxcms.com/forums/index.php?topic=53158 When deleting a TV, the values for that TV in resources that used it will persist until cache is cleared. It seems like cache should automatically be cleared - if you don't want the TV element in your site anymore, you don't want the old values showing up anymore either.

**Comment by opengeek** [comment]
opengeek submitted:

I want to consider options here a little more before committing to a solution on this; I think there are times you might want to make various such changes before having the cached cleared, and other times you want it done immediately. Others who might have input on this, please chime in.

**Comment by opengeek** [comment]
opengeek submitted:

This is resolved for 2.0.4-pl in http://github.com/modxcms/revolution/commit/3452e50bf9145d7548558050bcc24040f2c8dc8b
