### ISSUE TITLE
Use property sets in form customization rules

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#10484]
gadamiak created Redmine issue ID 10484

It would be very handy to be able to use property sets to provide names and values for form customization rules. That would allow to operate on groups of similar customizations, which is quicker, more efficient and easier to manage than multiple rules. Say, I want to hide a few fields. In current implementation I have to create as many "Field Visible" rules as there are fields I want to hide. With PS support I would create one "Field Visible" rule and select a PS to provide name/value pairs for every field I want to hide.

**Comment by splittingred** [comment]
splittingred submitted:

We'll be taking a look at Form Customization in 2.1.0; we'll be introducing Form Customization Profiles, that let you store information. We won't use Property Sets, though, as those are Element-specific. We'll have other solutions for this problem, though.

**Comment by gadamiak** [comment]
gadamiak submitted:

I proposed using property sets because they are already available and don't require additional development. However, there may be better solutions to achieve this kind of functionality.
