### ISSUE TITLE
Image preview in file manager

### ISSUE THREAD

**Issue by devtrench** [modxbot/migrate#10487]
devtrench created Redmine issue ID 10487

Can we get an image preview in the file manager? When you select an image you still get the text area as if the file is text based. If it is a png, gif or jpg the image should be displayed.

**Comment by splittingred** [comment]
splittingred submitted:

Since you can't edit binary file types in 2.0.1 anymore, added an image preview on hover over in the file tree in http://github.com/modxcms/revolution/commit/739c8dcd709643731d22e3e366f67e851efb1aec
