### ISSUE TITLE
bug? modX::getChildIds()

### ISSUE THREAD

**Issue by goldsky** [modxbot/migrate#10493]
goldsky created Redmine issue ID 10493

http://modxcms.com/forums/index.php/topic,52337.msg307365.html#msg307365 public function getChildIds($id= null, $depth= 10) { $children= array (); if ($id !== null && intval($depth) >= 1) { $id= intval($id); if (isset ($this->resourceMap["{$id}"])) { if ($children= $this->resourceMap["{$id}"]) { foreach ($children as $child) { $processDepth = $depth - 1; if ($c= $this->getChildIds($child, $processDepth)) { $children= array_merge($children, $c); } } } } } return $children; } $id= intval($id);
this makes $id to 0 (zero, in MODx's tree case= ROOT). Is this a bug or on purpose?

**Comment by goldsky** [comment]
goldsky submitted:

I propose to tweak it like this: public function getChildIds($id= null, $depth= 10) { $children= array (); if ($id !== null || $id === '' && (int)$depth >= 1) { if (isset ($this->resourceMap["{$id}"])) { $children= $this->resourceMap["{$id}"]; foreach ($children as $child) { $processDepth = $depth - 1; if ($c= $this->getChildIds($child, $processDepth)) { $children= array_merge($children, $c); } } } } return $children; }

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/61b0deafeceab9daf55a23ef87d6a46b2c8175c8
