### ISSUE TITLE
Reload Lexicon entries during upgrade install

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1049]
bobray created Redmine issue ID 1049

This doesn't seem to be happening now.

**Comment by splittingred** [comment]
splittingred submitted:

This is working normally on my install. I don't understand how it wouldn't be on yours - the code hasn't changed.

**Comment by BobRay** [comment]
bobray submitted:

It's probably Vista I had deleted /core/packages/core and the .zip file. I did a build and an install, but the string wasn't updated until I manually reloaded the Lexicon. The Lexicon reload reported loading the new string in the console, even though it should have been loaded during the install. I've noticed in the past that fixes you post and commit (even ones that have nothing to do with the Lexicon) sometimes don't show up on my site until after several builds and installs. I know it's not a browser cache/cookies issue and I always flush the permissions/sessions before upgrading. Let me know if there's any diagnostic testing I can do.
