### ISSUE TITLE
Hover popup should be "New Document" not "Create Resource"

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10499]
bobray created Redmine issue ID 10499

The first resource-creation icon at the top of the Resource Tree has "Create Resource" as a hover popup. It actually creates a Document and should say so since the others create Weblinks, Symlinks, and Static Resources &#8211; all of which are also resources.

**Comment by gadamiak** [comment]
gadamiak submitted:

See MODX-2175 .

**Comment by splittingred** [comment]
splittingred submitted:

Resolved in http://github.com/modxcms/revolution/commit/69818f7952ce9a8692213c92f884bfe7e7166245
