### ISSUE TITLE
add a single white space to empty files

### ISSUE THREAD

**Issue by eerne** [modxbot/migrate#10498]
eerne created Redmine issue ID 10498

cyberduck gives an error for each file that contains 0 bytes. /manager/assets/modext/build/workspace/builder/combos-min.js
/manager/assets/modext/workspace/builder/combos.js
/manager/templates/default/element/tv/renders/properties/default.tpl is it possible to add at least 1 white space to these files?

**Comment by splittingred** [comment]
splittingred submitted:

http://github.com/modxcms/revolution/commit/9a3ff132b4f2143cc8b27ab6cb5624b3d9664f7a
