### ISSUE TITLE
Changing Content-Type to "text" and then saving -> "Saving..." Popup doesn`t disappear

### ISSUE THREAD

**Issue by MadeMyDay** [modxbot/migrate#10490]
mademyday created Redmine issue ID 10490

Like in http://bugs.modx.com/browse/MODX-2205 the changing of a static resource to content-type "text" produces the neverending "saving..." message while saving. Saving is okay, but the message won`t disappear. http://github.com/modxcms/revolution/commit/336b4868b2cdc031e105de2ae3b3cb576b686b8a is already applied.

**Comment by splittingred** [comment]
splittingred submitted:

Can't replicate at all. Please state: Version of MODx, Traditional or Advanced distribution (for Revo), Server OS, Server Version, PHP Version, MySQL Version (client and server), is pdo_mysql installed, your Browser type and version, if you are using any opcode caching such as eAccelerator, APC, winCache, xCache, etc; any relevant errors in core/cache/logs/error.log, and any other relevant environment data.
