### ISSUE TITLE
[Irreproducable] Unclean $_GET link on the Browser Tree

### ISSUE THREAD

**Issue by goldsky** [modxbot/migrate#10494]
goldsky created Redmine issue ID 10494

If we select any resources or elements, then click any file from the File Tree, the 'Edit File' field goes blank.
The link (if we hover the filename) seems awkward. Well, sometimes it works, sometimes it does not.

**Comment by splittingred** [comment]
splittingred submitted:

Huh? I can't replicate anything like this at all. Can you describe more in detail exactly what you're doing here?
