### ISSUE TITLE
drag & drop tree doesn't change the container's value

### ISSUE THREAD

**Issue by goldsky** [modxbot/migrate#10501]
goldsky created Redmine issue ID 10501

MODx Revolution 2.0.0-pl rev7212
Running on my FF 3.6.8, when I played with drag & drop child, the Container's checkbox didn't play well, the db-value didn't change.
And of course, it made the Wayfinder picked the false parentClass.

**Comment by splittingred** [comment]
splittingred submitted:

Yeah, Wayfinder is incorrect there - it should check for children, not the container checkbox. Dragging should never change the container field, as 'container' status is not necessarily equal to 'has children'.
