### ISSUE TITLE
file manager is showing broken thumbnail images when filemanager_path is outside of the base path

### ISSUE THREAD

**Issue by scotto** [modxbot/migrate#10502]
scotto created Redmine issue ID 10502

filemanager is showing broken thumbnails for images in the vhost directory which holds my context's assets

**Comment by splittingred** [comment]
splittingred submitted:

What have you set filemanager_path to? And what's the URL it is rendering, and then what is the URL it should be rendering?

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/ab01b989b3aa08624491fa3070424f8a26850ec1 Added a filemanager_url setting to get around this.
