### ISSUE TITLE
Directory browser does not respect filemanager_path setting

### ISSUE THREAD

**Issue by chucktrukk** [modxbot/migrate#10504]
chucktrukk created Redmine issue ID 10504

Update filemanager_path setting
 http://skitch.com/prowebscape/dtq3p/file-manager-path-1 Browse to http://www.site.com/manager/?a=3
 http://skitch.com/prowebscape/dtq35/modx-modx-resources-browser I think the problem is in /core/model/modx/modfilehandler.class.php
line 55
public function getBasePath($prependBasePath = false) {
$root = $this->modx->getOption('filemanager_path'); The ->getBasePath() is returning null here. In the frontend, I tested:
$root = $modx->getOption('filemanager_path',null,''); and it did work

**Comment by splittingred** [comment]
splittingred submitted:

Strange, my line 55 says: $root = $this->modx->getOption('filemanager_path',null,''); Does changing that line fix it for you?

**Comment by chucktrukk** [comment]
chucktrukk submitted:

My line 55 has that too now. I think i cut-and-pasted wrong? It is working this morning- replacing {assets_path} and everything
