### ISSUE TITLE
Add Option to SortBy pulishedon in the combobox generated for the resource tree

### ISSUE THREAD

**Issue by scotto** [modxbot/migrate#10506]
scotto created Redmine issue ID 10506

I'm guessing this: , &#91;_(&#39;published_on&#39;),&#39;publishedon&#39;&#93; would go into: http://github.com/modxcms/revolution/blob/master/manager/assets/modext/widgets/resource/modx.tree.resource.js#L262

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: http://github.com/modxcms/revolution/commit/ab5cfdec072a471b1042cddb9463522d146b6bfe
