### ISSUE TITLE
Drag files to TV's (for multiple-files/gallery TV)

### ISSUE THREAD

**Issue by Gigha** [modxbot/migrate#10508]
gigha created Redmine issue ID 10508

Hello, I want to create a Webshop in MODx.
Now I have a Product-template for products. But the problem is, I want to let the user add preview images or video's of the product.
After they created preview-files into the TV, I want to make a gallery of it (with a snippet), to show on the page of the product. But I can only add 1 file/image with the TV's per field.
Now I thought a solution would be, to let the user drag the files from the left panel into a textfield/textarea, separate them with a comma, and then explode that string with the gallery-snippet.
Like this: [ 1.png,2.jpg,3.avi,etc ] This is why I thought it would be cool to drag files into TV's, or make a multiple-files TV-type This is not a very crucial bug or something, but it would be cool to add in MODx.

**Comment by Gigha** [comment]
gigha submitted:

I wanted to create a webshop, just to get more experienced with MODx, and see what's possible.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/35dc2ea06eaf22855353b810f11f6745bad6a7c7
