### ISSUE TITLE
Highlighting, dragging and dropping text while editing chunks does not activate the save button

### ISSUE THREAD

**Issue by graviteski** [modxbot/migrate#10507]
graviteski created Redmine issue ID 10507

When editing a chunk in the manager, prior to using the keyboard, it is possible to click and drag to select a block of text, then move it to a new location within the editable textarea yet the change is not recognised and the save button remains disabled. I guess that the save object is waiting for a keyUp callback from the textarea?

**Comment by MarkH** [comment]
markh submitted:

Added trigger on "change" event next to the keydown: https://github.com/modxcms/revolution/pull/495

This makes sure the save button is enabled as soon as the field loses focus after dragging things around within one or another field. I couldn't find an event that does it right when you do the dragging, but I think change comes closest to what we need.

**Comment by opengeek** [comment]
opengeek submitted:

Fixed for 2.2.9

https://github.com/modxcms/revolution/commit/077740e39b054a3cf5721cc6218d4b08f03ff8eb
