### ISSUE TITLE
Save button not enabled after changing a drop-down TV

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1051]
bobray created Redmine issue ID 1051

Changing a drop-down TV's value doesn't enable the save button even if you click somewhere else. You have to alter something else to save. The TV I saw this for wasn't the first TV on the page, if that matters.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6010

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed - FF 3.5.4.
