### ISSUE TITLE
Quirk in User Extended Fields

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10519]
bobray created Redmine issue ID 10519

If you create a new extended field without giving it a value, the entry form on the right won't respond to clicking on it. Steps to reproduce: Create a "Field1" with "Value1"
Create "Field2" with no value
Click on "Field1" at the left
Click on "Field2" at the left &#8211; Field 1 is still in the editing form at the right.

**Comment by splittingred** [comment]
splittingred submitted:

This has been fixed already in 2.0.1.
