### ISSUE TITLE
Better handling of multiple form customization rules

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10510]
bobray created Redmine issue ID 10510

If you create a form customization rule that hides a tab (with no user group specified), then create another rule that makes the tab visible for the Administrator user group, the tab is still hidden from the Administrators. This violates the general security strategy of having the most permissive rule apply. One solution would be to let rules with a user group override rules without one. Another would be to follow the general security strategy and let the most permissive rule that fits the current situation apply.

**Comment by splittingred** [comment]
splittingred submitted:

Done in new FC UI.
