### ISSUE TITLE
Can't change the key of an extended user field

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10516]
bobray created Redmine issue ID 10516

You can change the key name of an extended user field, but the new key isn't saved. The only way to change the key is to remove and recreate it.

**Comment by splittingred** [comment]
splittingred submitted:

Really? I have no problems with changing the name of a key. Changing a container value, though, I can't do - that's correct.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/141de6ac88178d90b4b6f253d3880a9ef183bbd8
