### ISSUE TITLE
TV Radio Options still not rendering correctly

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10515]
bobray created Redmine issue ID 10515

A radio option TV with this input option values setting shows the third option on a different line than its radio button: red==assets/css/red.css||blue==assets/css/blue.css||green==assets/css/green.css

**Comment by SiNNuT** [comment]
sinnut submitted:

This also applies to checkbox tv's (on Rev 2.0.1 rc-1 from Git)
In FF and Chrome. It looks as if the longest value doesn't fit

**Comment by splittingred** [comment]
splittingred submitted:

Definitely cannot replicate this, across any environment. Tried: FF 3.\* OSX/Win/Linux Chrome OSX/Win/Linux Safari OSX IE8 Win

**Comment by SiNNuT** [comment]
sinnut submitted:

That's weird. Anyways, it's a pretty minor issue and atm it seems only Bob Ray and i are affected by it .
I'll try and figure out what's causing this.
