### ISSUE TITLE
Buttons have 'hot spots'

### ISSUE THREAD

**Issue by anablepo** [modxbot/migrate#10512]
anablepo created Redmine issue ID 10512

While I believe it to be a simple CSS issue, it appears that buttons (Save, Cancel Preview, etc. - Textual buttons) have a hotspot wherein clicking on the visual button does not necessarily execute the task assigned to it. Sometimes if the text is not clicked - rather the outer rim of the button - the button graphic seems to register a click but does nothing. Clicking on text however always seems to cause the button to behave properly. Not a huge thing... but instructionally - it's tough to say to end-users "Ok, be sure to click on the button text - not just the button - because if you click it the wrong way it won't work." - you know?

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/1dc4b519fe339f48e23708105d700a623c4097bd
