### ISSUE TITLE
Empty user extended field causes odd array

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10517]
bobray created Redmine issue ID 10517

Bug or feature? If you create an extended user field and leave the value blank, fields beyond it are misplaced in the array retrieved with getObjectGraph(). I'm not sure if that's a feature, a bug in xPDO or a bug in JSON_decode. Here is are the extended fields (in order of creation): full_name: "Bob Ray"
Location: "Oregon"
Extra Field: (no value)
Another Extra Field: "red,blue,green" Here is the JSON string in the DB: {"full_name":"Bob Ray","Location":"Oregon","Extra Field":{"Another Extra Field":"red,blue,green"}} Here is the print_r of that part of the array returned from getObjectGraph() and toArray(): &#91;extended&#93; => Array
(
 &#91;full_name&#93; => Bob Ray
 &#91;Location&#93; => Oregon
 &#91;Extra Field&#93; => Array
(
 &#91;Another Extra Field&#93; => red,blue,green
) )

**Comment by BobRay** [comment]
bobray submitted:

This is a little more serious than I thought, because the field with the empty value can't be removed without destroying the fields below it and it can't be edited to fill in the value. It becomes a container for the field (fields?) below it, so it can't be edited and, if you remove it the other fields are lost.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/1dddb103227a7227e5274cb561ccefde1d63687d
