### ISSUE TITLE
modTemplateVar->get('name') adds trailing space to tv named 'keywords' (& possibly others)

### ISSUE THREAD

**Issue by putamare** [modxbot/migrate#10526]
putamare created Redmine issue ID 10526

Any template variable named 'keywords' (& potentially others) attaches a trailing space from $tv->get('name') so 'keywords' becomes 'keywords '. Thus the call $modx->getTemplateVarOutput(array('keywords')) returns the array: &#91;keywords &#93; => tv contents and not &#91;keywords&#93; => *tv contents I fixed my issue by changing $output &#91;$tv->get(&#39;name&#39;)&#93; = $tv->renderOutput($resourceId);
to
$output &#91;trim($tv->get(&#39;name&#39;))&#93; = $tv->renderOutput($resourceId); in modx.class.php, but the real source of the problem lies further down the rabbit hole.

**Comment by splittingred** [comment]
splittingred submitted:

Cannot duplicate this in any way, environment or test. I think you just might have a trailing space.
