### ISSUE TITLE
Password blank after modifying password of existing user

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1052]
bobray created Redmine issue ID 1052

The new password is shown as blank when you modify the password of an existing user, set the password yourself, and choose "show me the password" (in FF3.5 anyway). I think the password is set (not sure), it just doesn't show in the final popup.

**Comment by splittingred** [comment]
splittingred submitted:

Did you reload your lexicon? I think I forgot to put that in the commit message. Sorry bout that!

**Comment by BobRay** [comment]
bobray submitted:

My bad. I should have thought of that. Shouldn't the lexicon be reloaded during an upgrade install (it wasn't)?
