### ISSUE TITLE
Manager blank page when moving everything to subdomain

### ISSUE THREAD

**Issue by eerne** [modxbot/migrate#10527]
eerne created Redmine issue ID 10527

moved all files to a subdomain and ran setup "advanced upgrade"
/manager gave me blank page. then removed all files from /core/cache/ , but manager still blank. found that there are some missing path in core/config/config.inc.php . the first one (MODX_CORE_PATH) was updated correctly but the others (MODX_PROCESSORS_PATH - MODX_ASSETS_PATH) were not updated at all (as far as i can see). after adjusting these path the manager seems to work again old (and not updated) path was
/home/httpd/vhosts/mydomain.ch/httpdocs/core/ correct path would be
/home/httpd/vhosts/mydomain.ch/subdomains/revolution/httpdocs/core/
(only first one MODX_CORE_PATH had the correct path)

**Comment by splittingred** [comment]
splittingred submitted:

Duplicate of MODX-2201 .
