### ISSUE TITLE
TV File Binding dont work correct

### ISSUE THREAD

**Issue by man-oi** [modxbot/migrate#10523]
wumble created Redmine issue ID 10523

I have create a TV, input type file, default value @FILE html/header.html, output default, template access to the right templates when i edit a ressource it makes @FILE html/header.html to Could not retrieve document &amp;#039;html/header.html&amp;#039;.
then i reedit it to @FILE html/header.html, click save, all works! File is included correctly But the i edit the ressource again and again there are &amp;#039;html/header.html&amp;#039; instead of @FILE html/header.html

**Comment by splittingred** [comment]
splittingred submitted:

Why are you using a File input type there? Why not a textbox??

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/6bdf1d37e66257194b8429c5825aef15d70899fa Was a bigger issue with all bindings, rather than just @FILE
