### ISSUE TITLE
[server-specific] When editing a document in Google Chrome, TV list often fails to load

### ISSUE THREAD

**Issue by Roobarb** [modxbot/migrate#10529]
roobarb created Redmine issue ID 10529

When editing a document, clicking the Template Variables tab causes a 'Loading...' message to be displayed. Sometimes this goes on indefinitely and the TVs are never displayed. When this happens, I have to click the resource again in the tree and wait for it to reload (sometimes the TVs aren't displayed the second time around either). I have 18 TVs assigned to the template being used by my document.

**Comment by opengeek** [comment]
opengeek submitted:

Is this still occurring for you in the latest releases?
