### ISSUE TITLE
Manager Login DNS dependant?

### ISSUE THREAD

**Issue by anablepo** [modxbot/migrate#10522]
anablepo created Redmine issue ID 10522

Revo Manager will not adapt to a DNS change when logging into manager. In my case - I installed Revo on a webserver before the domain name I intended to use was resolving properly. When 'example.com' did resolve properly - accessing the manager (example.com/manager) would allow me to enter & validate login information, but would not leave the login screen (i.e. it would tell me in red text if the login was incorrect - but if it was correct - it just reloaded the login page and cleared the form) Same thing happens with each domain / subdomain from which the manager is accessed. Flushed all sessions, permissions and toilets. Residual config from the install?

**Comment by opengeek** [comment]
opengeek submitted:

You really should use the manager using a single URL you configured it with and that is reported by the webserver as HTTP_HOST. However it should work regardless, depending on your session cookies configuration. It could be that accessing it from various domains is causing session conflicts. For instance, make sure you do not have a session_cookie_domain setting hardcoded to a specific domain if you plan on accessing it from different domains.

**Comment by opengeek** [comment]
opengeek submitted:

Unable to reproduce with the information given. Will wait a few days for additional feedback and then close.

**Comment by opengeek** [comment]
opengeek submitted:

No feedback, closing.
