### ISSUE TITLE
Misleading comment in tv->getValue()

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10525]
bobray created Redmine issue ID 10525

The comment (as I read it) suggests that if the ID argument is zero or missing, it defaults to the current document. That implies that the TVs raw value for the current document would be returned. Instead, the function returns the default value of the TV. I'm not sure if that's a problem with the comment or the code.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: http://github.com/modxcms/revolution/commit/8484df1cfdd20ec782d180984ef120913f2ef8ce
