### ISSUE TITLE
Manager menu item descriptions

### ISSUE THREAD

**Issue by charliez** [modxbot/migrate#10528]
charliez created Redmine issue ID 10528

It would be a good idea to have a system setting that controls the display form of
the menu items in the main menu of the manager. The option could be: text, text+descriptions, small icon, big icon, icon+text, etc.

**Comment by splittingred** [comment]
splittingred submitted:

Added in http://github.com/modxcms/revolution/commit/3a90677e5832550685e09805fafcf77337c4b7eb
