### ISSUE TITLE
Checkbox TVs with default value dont allow all checkboxes unchecked

### ISSUE THREAD

**Issue by man-oi** [modxbot/migrate#10524]
wumble created Redmine issue ID 10524

I created a Template Variable with Type Checkbox, give Permissions to one Template.
Then editing a Ressource, uncheck the checkbox, click save. modx called save successfully, the editing the ressource again and the checkbox is still checked.
Then i looked in the Database and theres no entry in table "modx_site_tmplvar_contentvalues" for this TV

**Comment by splittingred** [comment]
splittingred submitted:

Revised title to be more correct. This only happens if there's a default value for the TV.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/849abd1ead9f42acce540d07e1b3d856632afa16
