### ISSUE TITLE
Create New User - missing error message for "username in use"

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1053]
bobray created Redmine issue ID 1053

Steps to reproduce: 1. Create a new user with the same username and email as an existing user. Save. (get the "email in use" error message). 2. Correct the email address to an unused one. Save. (get the error box, but no description of the error &#8211; should be "username in use" ?) No way to save the user and no info on what's wrong. Correcting the username let's you save, so the mechanics are OK, just the error message needs fixing. You also get the generic error message if just the username is a duplicate - The username error should probably have priority over the duplicate email error (and maybe it will if the error message is set).

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6078

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
