### ISSUE TITLE
ZipArchive not extracting transport zip

### ISSUE THREAD

**Issue by multimedia** [modxbot/migrate#10530]
multimedia created Redmine issue ID 10530

Clean install of MODx Revolution 2.0.0-pl,
Package Management clicked download for TinyMCE 4.0.1-rc2, it seems to download because the Download button is greyed out, but it stays greyed out, i have to press the finish button to go back to the package management screen which still says No data to display
Reselected the page System > Package Management, there it is now... In core/packages the zip file and folder are there
tinymce-4.0.1-rc2.transport.zip
tinymce-4.0.1-rc2 (1.543 files, 140 folders) In database in modx_transport_packages the field attributes is NULL Back on the Package Management page, pressing the Install button gives the following:
An empty License Agreement, selected I Agree and clicking Next;
An empty Readme, clicking Next;
Also nothing in Setup Options (this might be OK), clicking Finish;
Console window opens, takes a while...shows Console running... still waiting... then the following in the console apears:
Error 42S02 executing statement: UPDATE `modx_session` SET `access` = '1280490887' WHERE `id` = 'u90u9uqvt2mhj1al99aqidqcn7' LIMIT 1 Array ( &#91;0&#93; => 42S02 &#91;1&#93; => 1146 &#91;2&#93; => Table 'modx_project.modx_session' doesn't exist )
Created table`modx_session` SQL: CREATE TABLE `modx_session` (`id` VARCHAR(40) NOT NULL DEFAULT '',`access` INT(20) unsigned NULL,`data` TEXT NULL, PRIMARY KEY (`id`)) TYPE=MyISAM
Attempting to install package with signature: tinymce-4.0.1-rc2
Package found...now preparing to install. Then after that nothing else happens, the OK buttons stays greyed out. Reloading the manager page results in a timeout...
Fatal error: Maximum execution time of 60 seconds exceeded in E:\MODx\modx\core\model\modx\modsession.class.php on line 28 restarting Apache service Reloading the manager page, System > Package Management, it shows that TinyMCE is not installed

**Comment by splittingred** [comment]
splittingred submitted:

Changing description, since this while this is actually 2 issues, a big part of it is that TinyMCE's not extracting the zip, as shown by the 'attributes' field being NULL.

**Comment by splittingred** [comment]
splittingred submitted:

Seems to be related to a bad version of ZipArchive. This version doesn't unzip: Zip version 1.8.11 Libzip version 0.8.0-compatible This version DOES unzip: Zip version 1.8.11 Libzip version 0.9.0

**Comment by splittingred** [comment]
splittingred submitted:

Other debugging: http://modxcms.com/forums/index.php/topic,53252.msg308478.html#msg308478

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/ac952979bb2c93babb49c1d8e160bc84300ee272 If you're having problems with ZipArchive, set the "Force PCLZip Archives" (archive_with) setting to "Yes". This will force MODx to use PCLZip instead of ZipArchive.
