### ISSUE TITLE
more methods of modx classes (modResource, modResourceGroup)

### ISSUE THREAD

**Issue by norblenn** [modxbot/migrate#10534]
norblenn created Redmine issue ID 10534

The principle: Most functions in the MODx manager menu should have ready classes with their methodes in the MODx object model. Otherwise it is nearly impossible for most programmers to develop applications on the MODx layer. They would have to completely understand the database model and xPDO model, of course. For example, what I miss today is this: I have 'authors' who may fetch 'reviewers' for their article. What I need as codeable modx functions in PHP snippets is the same what an admin would have to do by hand.
The interesting issue is that all those functions must already be coded; otherwise it wouldn't be possible that the Revo manager could work. The task is "only" to spend them a useful modx layer. I have this: See Revo Manager menu:
Access Controls -> Update User Group -> Resource Group Access -> Add User Group The modx-php equivalent could be something like
(modResourceGroup) $resourcegroup->joinGroup($usergroup, $minimum_role, $context); Then your resource itself needs an connection to the user group.
(modResource) $resource->joinGroup($resource_group); And the other way arround by leaveGroup. That should be enough here. I am sure that I will find more missing methods. Then I will come back within further keys.

**Comment by splittingred** [comment]
splittingred submitted:

Scheduling for next feature release, 2.1

**Comment by splittingred** [comment]
splittingred submitted:

Done in https://github.com/modxcms/revolution/commit/4741e9c941d65761c565773d46368d4ddaabbb66
