### ISSUE TITLE
No description tooltip on elements when in category

### ISSUE THREAD

**Issue by SiNNuT** [modxbot/migrate#10538]
sinnut created Redmine issue ID 10538

When elements are put in a category the onmouseover 'description tooltip' doesn't work anymore. Refreshing the tree doesn't help.
Tested on:
Revolution 2.0.0-pl and 2.0.1-rc-1
PHP 5.3.1, MySQL client: 5.0.5-dev, server: 5.1.36, Apache/2.2.11,
browsers: IE8, FF 3.6.8, Chrome 5.0.3
WinXP

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/23b1a4473eea8192dda1bab60a3aa0cd4483de9c
