### ISSUE TITLE
Error with drag-and-drop for parent field

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10537]
bobray created Redmine issue ID 10537

Setting the parent field of a resource works fine the old Evo way, but users who only know Revo may try dragging the desired parent resource onto the field. That drops a link tag on the field.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/aa49668c426108e5fc71e61f5787696c517a21af
