### ISSUE TITLE
Create an additional faster way of accessing files/resources/elements within the mgr

### ISSUE THREAD

**Issue by niklas177** [modxbot/migrate#10546]
nklsf created Redmine issue ID 10546

Since Entities (resources, chunks, snippets etc) in the MODx-Manager tend to be intertwined, the AJAX-reloading tree slows down the workflow quite often when working across several files. Especially when entities have categories assigned. I would love to see a view, which supports this "currently working on"-mode. That could be through a tabbed behaviour of the edit-pages, where i could have 1 resource, 2 chunks and 1 snippet open - switching them through tabs. Or it could be implemented by a view in the resource tree, that shows the last edited entities in descending order, disregarding its category or type. Icons help to identify the kind of entity. Thanks.

**Comment by splittingred** [comment]
splittingred submitted:

See "Quick Update" and "Quick Create" for Resources/Elements.

**Comment by niklas177** [comment]
nklsf submitted:

yes, that would do the trick, if my chunk tree would not collapse automatically now and then (when creating entities of another kind). if it always kept the state of opened types and categories i could work with quick update/create. should i file this as a bug?
