### ISSUE TITLE
Character encoding issue

### ISSUE THREAD

**Issue by atype** [modxbot/migrate#10547]
atype created Redmine issue ID 10547

There seems to be a basic character encoding issue in the admin area. Although this doesn't have any noticible impact on performance at all, it makes the interface look 'less than professional', as for example it shows the 'black diamond with question mark inside' instead of an apostrophe. Its a tiny, tiny matter in the scheme of things but IMHO these things could have an impact on how the package is recieved by end users. Example: What?s New and we think you?ll love

**Comment by splittingred** [comment]
splittingred submitted:

Is due to the forum post's RSS feed, rather than the Revo manager. Closing.
