### ISSUE TITLE
Security Hole - change_profile does not work unless user has view_user and edit_user rights - 2.0.0pl

### ISSUE THREAD

**Issue by jgulledge19** [modxbot/migrate#10549]
jgulledge19 created Redmine issue ID 10549

I think this is a major security hole. The change_profile permissions does not allow the user to edit their profile. The solution is to give them the edit_user, view_user and save_user rights. And if you give them those rights, any smart user can then edit the admins account change the password and take it over. I have 2 possible suggestions:
1. just make it work as it is stated
2. create the edit_profile, view_profile and save_profile permissions. If you want to quickly test this, download the script here: http://modxcms.com/forums/index.php/topic,52248.msg303533.html#msg303533 and it divides the Access Policy up into different groups where you can load them easily.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/4673eef8a9cf05d89f9dc572aa59c01a8d04908b
