### ISSUE TITLE
Improve Usability, Expected Behavior and Efficiency

### ISSUE THREAD

**Issue by jgulledge19** [modxbot/migrate#10543]
jgulledge19 created Redmine issue ID 10543

I have started to get into Modx Revolution 2.0.0 and here are some desired improvements that would make the manager from good to awesome. I also posted here: http://modxcms.com/forums/index.php/topic,52430.0.html with a few pics. First A wanted feature
For the Resources, I would like a review date option. How it would be used is like this, imagine a large information website and pages needed reviewed and updated periodically. Currently you have to just read page by page, but if you could assign a review date and the review date could be a sort/filter option in site schedule. An advanced optional option to this could be to set a resource owner/manager that would get emailed on the day the page needs to be reviewed. Usability and Expected Behavior
The right click option is helpful in some situations when referencing advanced options, but I think it breaks expected behavior for basic things like Edit and Delete/Remove. My suggestion, I think it would be helpful and make the manager more user friendly, would be to reduce the amount of a right clicks and only use right clicks for advanced options. If the original intent was to keep a clean interface without 30 million buttons everywhere on the page, I get that. I have started using Feng Office CE: http://www.fengoffice.com/web/community/downloads.php in recent months and it offers a visual approach to this problem that is very clean. Take for example Feng Tasks tab, few buttons are shown, until you hover over a row and then all of its basic options are visible and you can then left click on them as expected. This is so much faster than right clicks and it feels simple but has a ton of features. See image attachment I find check boxes to be in a very odd location in the Manager, to me this is confusing and I would argue it also breaks Expected Behavior. Could check boxes be to the left of the label with all only a little space in between as normally expected? Efficiency, Search & Sort functionality
Could there be a way to set the table grids to have more than just 10 rows? It would be much quicker if the user can select how many rows they want to view or via the System Settings. How about filter options on table grids? Again I point to Feng Office as an example of this. See image attachment Could there be a search option be directly under the resources tab, just an input field and submit button? There could then be an advanced option/link like the current search option. Modx permissions
Could the access policies be listed as rows of three or four with a check boxes next to each item and when you hover over a label it would give the description? And all permission would always would show so you just click on/off. There could still be the Add permission option for customizations, and once a new perm is added it should also show up on all access policies even though inactive. Also what about grouping the access policy permissions, maybe by a resource, category or tag? See here how I grouped some: http://modxcms.com/forums/index.php/topic,52248.msg303533.html#msg303533 , this at least gives you an idea. Customizing Modx Manager pages
Can the manager forms be built with standard HTML and the JavaScript simply load values from the form and save them with Ajax? And still allow one to be saved with a post form? On that thought, I am trying to figure out(although I have not spent a ton of time) on how to build custom manager pages that would fit into the Modx Manager framework. Other
Just one thing that I don't get, you cannot select/highlight basically any text from in the Manager. This is annoying, for example if I would like to copy a permission, I can't I have to type it. Thanks,

**Comment by splittingred** [comment]
splittingred submitted:

Good points, but please split these up as separate issues; it's too hard to manage and address an issue-cluster like this. Closing as Invalid until then.
