### ISSUE TITLE
MODx could not create your database

### ISSUE THREAD

**Issue by wilecoyte78** [modxbot/migrate#10544]
wilecoyte78 created Redmine issue ID 10544

I added the database manaually and I tried letting MODx add the database for me but I keep getting this error: Connecting to mysql server: Success! Checking database:MODx could not create your database. Please manually create your database and then try again. The database when I created it is MySQL charset: UTF-8 Unicode (utf8) MySQL connection collation: UTF-8 Unicode

**Comment by splittingred** [comment]
splittingred submitted:

Can you please state the exact versions of both your MySQL client and server.
