### ISSUE TITLE
New install: database tables get latin1_swedish_ci collation

### ISSUE THREAD

**Issue by ludri** [modxbot/migrate#10541]
ludri created Redmine issue ID 10541

When doing New Installation and setting values under "Test database server connection and view collations." like this:
Connection character set: utf8
Collation: utf8_general_ci All tables are still created with latin1_swedish_ci collation. Database is pre-created and database collation is set utf8_general_ci, tested under mysql root user.

**Comment by opengeek** [comment]
opengeek submitted:

I cannot reproduce this on any environment; if I pre-create the database with the proper collation and charset, the tables are created properly with the database specified charset/collation. Are you sure you set the database charset/collation properly before the installation was executed?

**Comment by ludri** [comment]
ludri submitted:

Really you are right. I did some more tests and if database collation is set like so:
CREATE DATABASE `modx-test` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci; Then all tables are created with right collation (utf8_general_ci). But if database is created like so:
CREATE DATABASE `modx-test`; And on ModX installation settings are set like this:
Connection character set: utf8
Collation: utf8_general_ci then ModX tables will have latin1_swedish_ci collations. Shouldn't tables be created with "utf8_general_ci" collation?
If not, please mark this as invalid.

**Comment by opengeek** [comment]
opengeek submitted:

IMO, MODx should create tables using collation of the database container they are created in. Thus this is invalid.
