### ISSUE TITLE
Date TV output filter generates 01.01.1970 if TV is not set 

### ISSUE THREAD

**Issue by MadeMyDay** [modxbot/migrate#10545]
mademyday created Redmine issue ID 10545

In Revo, if you set a TV to input type "date" and output filter "date" it returns 01/01/1970 even if TV is not set. Default behaviour should be returning nothing (like in empty image TVs).

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/2420c4bde4be075aecb850550a3b1e40a63d353a
