### ISSUE TITLE
Dragging elements into TinyMCE in Chrome

### ISSUE THREAD

**Issue by Gigha** [modxbot/migrate#10554]
gigha created Redmine issue ID 10554

Hello,
When I drag elements into text fields it works, but when i try to drag them into TinyMCE, rich text editor, it wont work! I would really like to have this good because when I try to go to the manager on IE7 (my only other browser), the whole manager is crappy (sorry)!
Now in IE7 and Chrome the manager doesn't work perfect. In which browser does it? Only Firefox? Or also IE8/Opera/Safari? Maybe if the bug ain't fixable I will switch to one of those browsers. PS. MODx is the best open-source CMS though!

**Comment by splittingred** [comment]
splittingred submitted:

This is due to the security settings in those browsers; there's no way to get around it, to be honest.
