### ISSUE TITLE
names of non-core items in Top Menu tree not shown correctly

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#10550]
netprophet created Redmine issue ID 10550

The Top Menu is only giving names (via the Lexicon) to items in the core namespace.

**Comment by mkschell** [comment]
netprophet submitted:

Initial fix committed: http://github.com/netProphET/revolution/commit/af720b8a32cbddaa334f4e093286054b94838f6e Potential remaining issues: The namespace used to load the Lexicon topic is taken from the menu item's modAction. Therefore, if a menu item does not specify a modAction, it's possible that it's Lexicon topic won't be loaded. If the menu item's name (i.e. Lexicon key) is not in the default topic, then it may still not be available.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/276495f371328729a3f0d573c389de8f5a0e2225
