### ISSUE TITLE
Maintain Sort order in resource tree after save a resource

### ISSUE THREAD

**Issue by An-tonio** [modxbot/migrate#10551]
an-tonio created Redmine issue ID 10551

When you sort the resorce tree with a different criteria than default and then you edit and save a resource, you lost your sort option in the tree and it change to default.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/c2764c7cd53e88cfce72886741b93a03d78a37c5
