### ISSUE TITLE
Inconsistent behaviour of MODx browser

### ISSUE THREAD

**Issue by gerritvanaaken** [modxbot/migrate#10559]
gerritvanaaken created Redmine issue ID 10559

In my defaut "images" directory, I have stored some images and some folders. When I open the MODx browser through the button in the "files" tab, I can see them both. When I open the MODx browser via TV image, it only shows the folders, not the images. See attached screenshots to clarify.

**Comment by gerritvanaaken** [comment]
gerritvanaaken submitted:

even more strange: Clicking on the "MODx browser" button within the MODx browser opens the correct one with the files on "root" level.

**Comment by splittingred** [comment]
splittingred submitted:

Not a bug; files arent shown in left-hand in TVs so you choose them through the view to execute the proper JS.

**Comment by vitalized** [comment]
vitalized submitted:

I get the same issue with the image TV and file browser.  I'm using multiple contexts.
If I click on the image TV it just shows the folders not the images inside them. I then click on the "MODX Browser" button which will then show the images but selecting an image and clicking 'OK' doesn't do anything except go back the the original view with no images in folders.

Gerrit van Aaken wrote:

> In my defaut "images" directory, I have stored some images and some folders. When I open the MODx browser through the button in the "files" tab, I can see them both. When I open the MODx browser via TV image, it only shows the folders, not the images. See attached screenshots to clarify.
