### ISSUE TITLE
Undelete for permissions in policy

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10556]
bobray created Redmine issue ID 10556

Just a thought &#8211; maybe for 2.1 or beyond: It would be great if permissions in a policy worked like resources in the Resource tree where you can delete and undelete them and they show in overstrike until you purge them. The way it is now, a new user would probably have to write down all the deleted ones on paper in case they have to be restored. Second choice: revert to default, like TVs.

**Comment by splittingred** [comment]
splittingred submitted:

This is no longer an issue due to Access Policy Templates.
