### ISSUE TITLE
Placing a colon in the title of a page breaks inline linking [[~24]] (server-specific)

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#10555]
wshawn created Redmine issue ID 10555

By simply placing a colon in the title of a web page, then referring to that page with a hard link [ &#91;~docID&#93; ] the site returns only the document alias, no path, and no extension. I would have to assume it is being interpreted as a filter reference.

**Comment by splittingred** [comment]
splittingred submitted:

I can't replicate this at all...I have tons of pages with a : in the pagetitle. How are you implementing this?

**Comment by wshawn** [comment]
wshawn submitted:

You can close this. The use alias path was disabled and I did not catch it and I was expecting the path to be showing up.
