### ISSUE TITLE
Add a way to delete multiple permissions from a policy in one step

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10557]
bobray created Redmine issue ID 10557

You can highlight multiple permissions in a policy with ctrl-click, but only one is deleted when you select it by right-clicking and choosing "Remove Permission." The others remain highlighted and are not removed. It's a a royal pain to slog through a policy deleting many permissions.

**Comment by splittingred** [comment]
splittingred submitted:

This is no longer applicable due to the changes in 2.0.5.
