### ISSUE TITLE
adding <em>test</em> in Summary (introtext) results in hangup when saving

### ISSUE THREAD

**Issue by SiNNuT** [modxbot/migrate#10563]
sinnut created Redmine issue ID 10563

Adding content like <em>test</em> in the Summary (introtext) field results in a hangup when saving.
The popup save message: "Please Wait...
Saving... " just keeps on going and going. I don't know if this is expected behavior and that you're just not allowed to put some html in the Summary field. If so, then maybe a description like (only plain text) would be nice.

**Comment by splittingred** [comment]
splittingred submitted:

Confirmed.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/336b4868b2cdc031e105de2ae3b3cb576b686b8a
