### ISSUE TITLE
changing a Menu's Lexicon Key orphans any child Menus

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#10562]
netprophet created Redmine issue ID 10562

Lexicon Key (name) is the primary key for modMenu. Referential integrity should be maintained when it's changed.

**Comment by mkschell** [comment]
netprophet submitted:

Attached patch resolves issue

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/668fcada24ccfe87bac4f1fbaf9096b1fa5b9245
