### ISSUE TITLE
MODX_PROCESSORS_PATH not set properly on upgrade install

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10567]
bobray created Redmine issue ID 10567

This relates to moving the core directory after installation with the Traditional distribution. Steps to reproduce. Install traditional distro normally
Move the core
Edit the four config.core.php files to set the full new core path path. (e.g. c:/xampp/htdocs/modx/newcore/)
Run Setup in upgrade mode. Everything else is set properly, but the MODX_PROCESSORS_PATH in core/config/config.inc.php is unchanged. I haven't tried this except on localhost/xampp, but I suspect it would be the same anywhere.

**Comment by BobRay** [comment]
bobray submitted:

The only incorrect part of the setting is the "core" part of the processors path. I'm not sure, but I think the problem is in setup/controllers/database.php, lines 98 and 113. The processors setting is the only one that uses MODX_CORE_PATH, which I suspect hasn't been set properly yet if the config.core.php files have been changed. Maybe the MODX_CORE_PATH should be read from setup/includes/config.core.php just above this code.

**Comment by BobRay** [comment]
bobray submitted:

Bad guess. It looks like that code isn't executing since die() statements in that file have no effect.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/c8215167b6864cab3f95cc1711f8199a261eb1f3
