### ISSUE TITLE
Root of user-specific filebrowser not reachable

### ISSUE THREAD

**Issue by StevenLangbroek** [modxbot/migrate#10565]
stevenlangbroek created Redmine issue ID 10565

A client has his own login to my (his?) Revo install. I've set the filebrowser-path to www.domain.com/images. All is wonderful, when he launches the filebrowser to edit an Image-TV he can only see the subfolders of images, and to his right he can see the images directly in the folder "images". However, when he clicks on one of the folders, it's impossible for him to get back to the "images" folder, as it's (quite logically) omitted from the browser by me setting it as his path. Maybe I'm misunderstanding the way you meant it to work, but is it possible to show the folder "images" in the overview on the left?

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/ef1da73866d800e09a323d9307ea298c11df4332
