### ISSUE TITLE
New Static Resource, Web Link & Symlink menu & icon links in manager interface are incorrect.

### ISSUE THREAD

**Issue by boombana** [modxbot/migrate#10566]
boombana created Redmine issue ID 10566

When creating a New Static Resource the action is set to 51 by default rather then 48. Web Link & Symlink actions are also set to 51 rather than 44 & 46 respectively. The flow on effect is for Form Customisation action settings, such as resource/staticresource/create, not to work.

**Comment by splittingred** [comment]
splittingred submitted:

Hrm, actually, what needs to happen is the derivative actions ( resource/staticresource/create et al) need to be removed, as those are deprecated and don't apply anymore. Best way to apply FC rules to derivative types is through a constraint.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/6bfbb9b8363f08da7b0887e3963f4bbe43e112ba
