### ISSUE TITLE
error in modLexicon->fetch() related to passing prefix

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#10573]
netprophet created Redmine issue ID 10573

calling $modx->lexicon->fetch('aprefix') will not return anything

**Comment by mkschell** [comment]
netprophet submitted:

patch fixes issue, could be modified further for slight speed or memory improvement, not sure which to optimize for

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: http://github.com/modxcms/revolution/commit/5c3d55358701a6d3e9209f1da9f0edddd57c4059
