### ISSUE TITLE
Can't change Name of a custom setting

### ISSUE THREAD

**Issue by eerne** [modxbot/migrate#10575]
eerne created Redmine issue ID 10575

I have some custom settings, but can't alter the Name. Trying: right-click Update Settings trying to change the Name in a custom setting (and custom Namespace) save
Remains with the original name. Changing the value works fine.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/3fca406a8ac409e2ee2eac57103f6e838029470f
