### ISSUE TITLE
TV options UI bug

### ISSUE THREAD

**Issue by maximbell** [modxbot/migrate#10577]
maximbell created Redmine issue ID 10577

TV Image -> Rendering options -> Input Type: Image -> Output Type: Image -> Align: HERES THE BUG drop down option list appears not under arrow but in the left top corner of the screen

**Comment by splittingred** [comment]
splittingred submitted:

I can't replicate this at all, in Fx/Safari/Chrome. What OS are you on?

**Comment by maximbell** [comment]
maximbell submitted:

Windows 7

**Comment by splittingred** [comment]
splittingred submitted:

This seems to have been fixed in the ExtJS 3.3 upgrade.
