### ISSUE TITLE
manager buttons ons the left

### ISSUE THREAD

**Issue by Senne** [modxbot/migrate#10574]
senne created Redmine issue ID 10574

Since upgrade from revolution RC2 to RC3, the buttons for saving, previewing (when editing a resource) are on the left..
I tought it would be fixed in the final release, but it's still on the left! Please help me Problem is only with ie8, in firefox buttons are on his place.
Flushed the cache also... screen:
 http://j.imagehost.org/0420/screen.jpg

**Comment by splittingred** [comment]
splittingred submitted:

This only seems to happen with IE8 in compatibility mode.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/1dc4b519fe339f48e23708105d700a623c4097bd
