### ISSUE TITLE
FURL settings not in Friendly URL area in System Settings

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10576]
bobray created Redmine issue ID 10576

friendly_urls and friendly_alias_urls are not categorized in the Friendly URL area (they're uncategorized) and don't show up when you select the Friendly URL area in System Settings.

**Comment by splittingred** [comment]
splittingred submitted:

Actually, they are - just Settings don't "update" on upgrades, and you're probably using an old old checkout of Revo, which didnt have them there. So technically this is 'already fixed.'
