### ISSUE TITLE
View Unpublished Resource when logged in displaying 404 for any context other that 'www'

### ISSUE THREAD

**Issue by scotto** [modxbot/migrate#10572]
scotto created Redmine issue ID 10572

as user with view_unpublished permission as part of the policy used on the Context ACL Can view unpublished 'www' context resources when same acl policy is applied to the 'www' Context

**Comment by splittingred** [comment]
splittingred submitted:

Can't reproduce. Can you reproduce this in the latest?

**Comment by opengeek** [comment]
opengeek submitted:

I think this is likely across different domains (or subdomains without the .domain.tld session_cookie_domain Setting properly set) that have separate sessions.

**Comment by scotto** [comment]
scotto submitted:

There was very little documentation about that system setting at the time this bug was filed. Thanks for following up. I will keep you posted on how well this works.
