### ISSUE TITLE
Simply can't download!!  Always trashes out about half way through.  Getting frustrated

### ISSUE THREAD

**Issue by hupe** [modxbot/migrate#10579]
hupe created Redmine issue ID 10579

Attempting to download to PC to use locally before setting up on servers. Cant download - trashes out halfway through Dave

**Comment by dschubert** [comment]
dschubert submitted:

JS enabled? Which Browser? Tried the direct-link http://modxcms.com/download/pl/modx-2.0.0-pl.zip?
