### ISSUE TITLE
Some lexicon entries are depended on language.

### ISSUE THREAD

**Issue by enogu** [modxbot/migrate#10588]
enogu created Redmine issue ID 10588

Some messages are using %s for replace words. But I think that these are having dependency on word order of the language.
I'm joining jp translation team and found that some messages aren't able to translate. For instance: Changed default value for column `%s` to %s on table `%s`. (from setup/lang/en/upgrade.inc.php) Basic japanese syntax is SOV. And modifier is oftenly placed forward noun (=SCOV). In this case, a table name (is modifier of the column) is force placed after its column.
I think that this message is expected to translate like such order in japanese : <third %s> table on <first %s> column for default value <second %s> to Changed. This is a sample text replaced word by word from Japanese message I expected. I think that most of you may be not able to understand this word order. In this way, there is much difference between some east asian languages(e.g. japanese, korian) and english. Then, I propose that replace %s to placeholder in the messages (at least two or more %s existing).

**Comment by splittingred** [comment]
splittingred submitted:

We can definitely find another way of getting rid of the %s, in a way similar to how we do lexicons. We'll definitely fix that in the first patch release.

**Comment by gadamiak** [comment]
gadamiak submitted:

It might be worth to consider using %n , where n is index of variable used in the string (if at all possible without gettext). With this approach the message: <third %s> table on <first %s> column for default value <second %s> to Changed. would be %3 table on %1 column for default value %2 to Changed. The working example is BBPress localization based on gettext. IMO, switching to gettext based localization should be the way to go, as this is "the right tool for the job" approach, which offers tools to facilitate translation and simplifies the whole thing.

**Comment by enogu** [comment]
enogu submitted:

gadamiak,
I used it <third %s> to specify which %s is placed. it isn't actual syntax. I only hope to use the placeholders(or another way to replace specified words via its id or index).
I found lexicon already supports the placeholder. But it seems %s isn't removed yet.

**Comment by splittingred** [comment]
splittingred submitted:

Setup wasn't using the placeholder method; we'll move setup to placeholders for 2.0.1.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/4202560fb8c14572d535d25fad23d98f2c416666 Translations will need to be adjusted to take advantage of new placeholder syntax.
