### ISSUE TITLE
Resource tree expand all only expands 1 level

### ISSUE THREAD

**Issue by scotto** [modxbot/migrate#10582]
scotto created Redmine issue ID 10582

Resource tree expand all only expands 1 level. expands all top level nodes to reveal second level nodes. I believe this used to expand all the way instead of just 1 level.

**Comment by scotto** [comment]
scotto submitted:

Just want to say that the feature fully works on the Elements tab, but works as described above for the Resources tab

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/3f4955e60f725dc30bd1d7f25e41756c19fa6260
