### ISSUE TITLE
browser opened up from tinyMCE to add images does not respect the filemanager_path Context setting

### ISSUE THREAD

**Issue by scotto** [modxbot/migrate#10583]
scotto created Redmine issue ID 10583

i would assume that if the browser was opened up when creating a resource in the blog context to adhere to the filemanager_path setting in the 'blog' Context

**Comment by scotto** [comment]
scotto submitted:

http://svn.modxcms.com/docs/display/revolution/filemanager_path states that i should have that as the root of the modx install dir. What if i need to have a separate assets folder for each context? or a separate directory to use for each user? using filemanager_path in the User settings and/or Context Settings does not affect anything. additionally if i specify a directory in the filemanager_path System setting other than the root of the modx install, it wont display anything in the file manager. (i would like to specify the assets directory of another virtualhost folder which my blog context lays under)

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in Revolution in http://github.com/modxcms/revolution/commit/21fb8097a18327eabd2dea551132771c53852ece However, a TinyMCE patch will need to be made to ensure it works with TinyMCE. This will be done post 2.0.1 release.

**Comment by scotto** [comment]
scotto submitted:

where would those of us that cant wait until 2.0.1 get the TinyMCE patch to get this to work?
