### ISSUE TITLE
Element names cannot have less than 3 characters

### ISSUE THREAD

**Issue by splittingred** [modxbot/migrate#10597]
splittingred created Redmine issue ID 10597

Due to regexp: /(?=^ &#91;a-zA-Z0-9\x2d-\x2f\x7f-\xff_-&#93; &#91;a-zA-Z0-9\x2d-\x2f\x7f-\xff_-\s&#93; + &#91;a-zA-Z0-9\x2d-\x2f\x7f-\xff_-&#93; $)/

**Comment by opengeek** [comment]
opengeek submitted:

New regex: /^(?!\s) &#91;a-zA-Z0-9_-\x7f-\xff\s&#93; +(?!\s)$/ This may not handle all corner cases, because \s can match certain Unicode characters, for instance, non-printing characters...but should cover most.
