### ISSUE TITLE
Binding are not processed for default TV values

### ISSUE THREAD

**Issue by josht** [modxbot/migrate#10598]
josht created Redmine issue ID 10598

When setting a TV's default value to @INHERIT somevalue it does not hold the processed value in the manager when editing the TV attached to a resource. When you click "Set to Default" it would load @INHERIT somevalue instead of just somevalue or the inherited value. Also, this causes lists to not select the default value at all. Only tested it with DropDown, Single Select and Multi-Select lists

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r7188

**Comment by josht** [comment]
josht submitted:

This is for DropDown lists (possibly other lists, haven't check though). Now, if a TV does not have an value set, and the default is @INHERIT somevalue it doesn't select the default value from the list. Also, when you select 'Set to Default' it still puts @INHERIT somevalue instead of just the value that it should be. If you remove 'false' from the call at line 280 in modtemplatevar.class.php The default values for TV's (ones that don't have a saved value) load correctly. But, when you click 'Set to Default' it still puts the whole binding and parameter back into the field.

**Comment by splittingred** [comment]
splittingred submitted:

Whew. Fixed in r7190. That should clear it up; inherited values now show their inherited value in the inputs (including in non-linear inputs, such as dropdowns/checkboxes). Also, added some text to below the description should a TV's value be inherited.
