### ISSUE TITLE
IE8 Package Installer - various not being shown

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#10594]
netprophet created Redmine issue ID 10594

License is not being shown in appropriate field.
 package-installer-IE8-1.jpg

**Comment by mkschell** [comment]
netprophet submitted:

Readme not being shown in appropriate field.
 package-installer-IE8-2.jpg

**Comment by mkschell** [comment]
netprophet submitted:

Behavior is different on Setup Options step in IE8 than in FF 3.6.6.
In FF, once the Setup Options step appears, the install console is triggered and the installation begins.
In IE8, the (blank) Setup Options step appears but the user must click "Finish" for the console to appear and the install to begin.
 package-installer-IE8-3.jpg

**Comment by mkschell** [comment]
netprophet submitted:

may be related to http://svn.modxcms.com/jira/browse/MODX-2158

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r7202
