### ISSUE TITLE
Resource menu uses "document" instead of "resource"

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#10592]
gadamiak created Redmine issue ID 10592

Resource actions in Create and Quick Create menus use "document" instead of "resource".

**Comment by splittingred** [comment]
splittingred submitted:

Not a bug; a Document is a type of Resource. (The default type, in fact.)

**Comment by gadamiak** [comment]
gadamiak submitted:

The button in resource tree says "Create resource" but creates a document. This is inconsistent. I agree it's not a bug, however
