### ISSUE TITLE
Configuration Check dialog box appears for users who don't have permission to some resources

### ISSUE THREAD

**Issue by leaase** [modxbot/migrate#10607]
leaase created Redmine issue ID 10607

I created a RESOURCE GROUP who only the admin could access and edit. In this group where the 404 page, startpage and the unauthorized page. When I logged in as an EDITOR who doesn't have access to the RESOURCE GROUP, the CONFIGURATION CHECK dialog box appeared in the welcome screen telling me that the error page and unauthorized page was either missing or not published, even though they both exists.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r7177
