### ISSUE TITLE
Loading set values for TV's broken

### ISSUE THREAD

**Issue by josht** [modxbot/migrate#10605]
josht created Redmine issue ID 10605

The fixes for issue MODX-1354 were broken in revision 7133. Many TV's input rendering now depend on calling $this->get('processedValue') to load the default values. It was removed in the mentioned revision.

**Comment by josht** [comment]
josht submitted:

The patch just adds back in the removed lines of code that are needed. Don't see where it causes the issues they were removed to fix. ?

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r7179
