### ISSUE TITLE
richtext_default system setting not effective

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#10608]
gadamiak created Redmine issue ID 10608

Setting richtext_default to no in system settings is ignored. New resources have the "Rich Text" check box checked.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r7175

**Comment by gadamiak** [comment]
gadamiak submitted:

"Rich text" checkbox is still checked in Quick Create Resource modal.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r7210
