### ISSUE TITLE
Stuck in Loop when Changin User Password

### ISSUE THREAD

**Issue by mattcdavis1** [modxbot/migrate#1060]
mattcdavis1 created Redmine issue ID 1060

When I try to change a user password (Security > Manage Users > Update User) or create a user with a password that I define, Modx gets stuck in a loop. It does ok if I allow Modx to generate password, but get's stuck otherwise. Screencast here: http://screenr.com/lfN

**Comment by splittingred** [comment]
splittingred submitted:

Duplicate of MODX-1327 .
