### ISSUE TITLE
publish_document and unpublish_document permissions not obeyed when using the checkbox on saving a resource

### ISSUE THREAD

**Issue by rubenk** [modxbot/migrate#10613]
rubenk created Redmine issue ID 10613

publish_document and unpublish_document permissions are not obeyed when saving a resource after checking or unchecking the checkbox 'Published'. I want some users to have be able to only access and edit unpublished resources. The bug above let's them publish their resources. There are also a few permissions missing called something like 'view_own_document' and 'save_own_document'.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r7167. view_own_document and such will not be added in 2.0.0. The best way to do that is through Resource Groups, though feel free to add a separate feature request for those.
