### ISSUE TITLE
Minify CSS/JS on-the-fly in Manager

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#10614]
gadamiak created Redmine issue ID 10614

Right now minified versions of CSS/JS files have to be prepared in build
process and are inaccessible in SVN deployments. Minify (PHP 5) allows JS and CSS files to be
combined, minified and then served in a single request with caching,
compression and appropriate HTTP headers. That would speed up loading and simplify build process getting rid of
duplicate files. Plus it would make manager in SVN deployments use minified
CSS/JS while not changing the source.

**Comment by gadamiak** [comment]
gadamiak submitted:

Minify can be used as a "proxy" serving CSS/JS through a modified URI or serve the content from a PHP script. I think the former is the way to go in Manager as it requires minimum work.

**Comment by splittingred** [comment]
splittingred submitted:

We'll definitely look into this for 2.0.1; however, this wont be in 2.0.0; too late to add this in.

**Comment by gadamiak** [comment]
gadamiak submitted:

I see this one won't make it into 2.1 :(

**Comment by gadamiak** [comment]
gadamiak submitted:

Shaun McCormick wrote:

> We'll definitely look into this for 2.0.1; however, this wont be in 2.0.0; too late to add this in.

Will you look at it again, please?

**Comment by Martijn1981** [comment]
Martijn1981 submitted:

I was just thinking about this yesterday! Google Minify is perfect for speeding up the Manager even more. Check out http://code.google.com/p/minify/. It is _very_ easy to configure.

**Comment by gadamiak** [comment]
gadamiak submitted:

That's exactly, what I was talking about :) This issue was transferred from Jira (yes, it's that old) and original link has been lost. Thanks for bringing it back.

**Comment by splittingred** [comment]
splittingred submitted:

This has been done in the 'refactor-mgr-controllers' branch in Git; however, probably will not make it until 2.2, unless we can confirm it (and the other related changes to mgr controllers) don't break existing Extras implementations.

**Comment by gadamiak** [comment]
gadamiak submitted:

I upgraded from c2ed118 to 897c80b. Manager now works fast, it's incomparable to what it was. That's a great improvement! Thank you.

However, there are issues:
- In Opera 11 (yes, that's my browser of choice) Package Management and Users pages don't show up. Error log is empty. Welcome boxes on home page don't display correctly (see attachment). I've taken look into Opera's Dragonfly and found 2 JS errrors when displaying the manager home page:
  
  In @http://.../manager/min/?f=/manager/assets/modext/widgets/modx.panel.welcome.js,/manager/assets/modext/widgets/security/modx.grid.user.recent.resource.js,/manager/assets/modext/sections/welcome.js@
  
  <pre>Syntax error at line 1 while loading:
  ?unexpected character: U+001F</pre>
  
  In @http://.../manager?a=1@
  
  <pre>Uncaught exception: TypeError: 'b[d.xtype||e]' is not a constructor

Error thrown at line 3, column 315572 in <anonymous function: create>(d, e) in http://.../manager/min/?f=/manager/assets/ext3/adapter/ext/ext-base.js,/manager/assets/ext3/ext-all.js,/manager/assets/modext/core/modx.js:
    return d.render?d:new b[d.xtype||e](d)
called from line 7, column 0 in <anonymous function: load>() in http://.../manager/min/?f=/manager/assets/ext3/adapter/ext/ext-base.js,/manager/assets/ext3/ext-all.js,/manager/assets/modext/core/modx.js:
    os.push(Ext.ComponentMgr.create(a[i]));
called from line 6, column 12 in <anonymous function>() in http://.../manager?a=1:
    MODx.load({
called from line 3, column 57123 in <anonymous function>() in http://.../manager/min/?f=/manager/assets/ext3/adapter/ext/ext-base.js,/manager/assets/ext3/ext-all.js,/manager/assets/modext/core/modx.js:
    p.apply(n,o)
called via Function.prototype.apply() from line 3, column 91513 in <anonymous function: Ext.util.DelayedTask>() in http://.../manager/min/?f=/manager/assets/ext3/adapter/ext/ext-base.js,/manager/assets/ext3/ext-all.js,/manager/assets/modext/core/modx.js:
    d.apply(c,a||[])</pre>
- After upgrade TinyMCE 4.3.0-rc1 switched from advanced to simple in content field. What's more, custom styles are not respected. I checked this in Opera 11 and Firefox 5. No settings for TinyMCE have been changed.

**Comment by gadamiak** [comment]
gadamiak submitted:

I wanted to do some Package Management and used Firefox 5, in which _no manager page displays_.

**Comment by gadamiak** [comment]
gadamiak submitted:

I reported separate issues for the above:
- #5053
- https://github.com/splittingred/TinyMCE/issues/66
