### ISSUE TITLE
Spurious stuff in console when updating packages

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10616]
bobray created Redmine issue ID 10616

The entire GPL and some other stuff shows up in the Console when I update a package to a new version using right-click in PM. I wonder if we're missing some sanity checking in PM. I've often seen the readme.txt file and sometimes PHP code show up in the Console when installing my own packages during development.

**Comment by splittingred** [comment]
splittingred submitted:

This was fixed a while back.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
