### ISSUE TITLE
Edit Multi Line at System Setting

### ISSUE THREAD

**Issue by gusdecool** [modxbot/migrate#10629]
gusdecool created Redmine issue ID 10629

i try to edit "sign-up email" at "system setting" (which it contain multi line text), but it only show 1 line text (like input in HTML form) which make me cannot see all the multi line.

**Comment by gusdecool** [comment]
gusdecool submitted:

Please see when i try to edit the "Sign-up email"

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r7141
