### ISSUE TITLE
Setup timeout error message on first entry

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#10623]
shamblett created Redmine issue ID 10623

On Revo r7153 I'm getting this message up on entry the first setup page :- 'MODx had to restart the setup process as a security precaution because setup was idle for over 15 minutes. Please re-attempt running setup at this time.' Noticed it after I did a rebuild.

**Comment by splittingred** [comment]
splittingred submitted:

Does this happen on an upgrade, or new install? Whats your URL when this happens? Can you replicate this?

**Comment by shamblett** [comment]
shamblett submitted:

It was when I executed setup after a rebuild of transport.core.php, itself after an svn up The URL is http://localhost/revolution/revolutiontest/2.0/setup/index.php?s=set Can't replicate it on the original site or another test site doing the above

**Comment by splittingred** [comment]
splittingred submitted:

I'm willing to bet then you still had a settings cache file somewhere from a prior setup. Closing the issue from here on out.
