### ISSUE TITLE
Actions page improvement

### ISSUE THREAD

**Issue by frenchfries** [modxbot/migrate#10626]
frenchfries created Redmine issue ID 10626

For less confusion, should there not be a warning message ( something like "please clear the cache and reload this page after moving a menu item") in the navigation panel on the "Actions" page ? When not doing theses steps, it looks like a bug because the parent or menuindex value are not saved.

**Comment by splittingred** [comment]
splittingred submitted:

Duplicate of MODX-2064 , it clears the cache now and will reload it when you reload the page. It is assumed you'll need to reload the page.
