### ISSUE TITLE
Issues in tooltips and menus

### ISSUE THREAD

**Issue by Pont** [modxbot/migrate#10622]
pont created Redmine issue ID 10622

In some places in the manager phrases are assembled from different strings. This sometimes leads to ungrammatical phrases. This happens in the Element tab in the left hand menu. The tooltips for all the create buttons (Template etc) are assembled from two strings: "New" and "Template" creating the combined string "New Template". This works in some languages but not in others. As an example - in swedish there is two words for "New": "Ny" and "Nytt". Witch one you use depends on the new object. You would say "Ny mall" for "New Template". "Nytt mall" would be grammatically wrong. The same thing happens in the right-click menus in the tree under the Element tab. If you right-click on "Templates" you get a menu where the first item is assembled in the same way leading to the same issue. My suggestion is to use the existing language strings for "New Template", "New TV" etc to eliminate this issue. Just like "New Category" is a defined string and not assembled from "New" and "Category".

**Comment by splittingred** [comment]
splittingred submitted:

Will have to wait until 2.0.1, the first Revo patch release, since lexicon strings are currently frozen.

**Comment by Pont** [comment]
pont submitted:

This doesn't require new strings. They are already in default.inc.php or the respective topic files.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r7162; required adding one lexicon string.
