### ISSUE TITLE
Revision 7101 is introducing mayor problems with TVs in other contexts

### ISSUE THREAD

**Issue by rubenk** [modxbot/migrate#10635]
rubenk created Redmine issue ID 10635

Revision 7101 is introducing mayor problems with TVs in other contexts. Template variables are not visible. Reverting the old file ( modtemplatevar.class.php ) solved the problem, but breaks the fix made in rev7101.

**Comment by opengeek** [comment]
opengeek submitted:

Can you describe the "major problems with TVs in other context"? Some kind of reference to a specific issue is necessary when making a bug report.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r7128
