### ISSUE TITLE
Show a message if cURL extension is not found in package management grid's

### ISSUE THREAD

**Issue by lossendae** [modxbot/migrate#10639]
lossendae created Redmine issue ID 10639

Add an error message in the package management grids if cURL is not present or not activated in PHP configuration. One possible track is to write a message in the grid body with the JSON response. Example: Extjs code: //Listener
this.store.on('load', this.onStoreLoad, this); /\* ...code... */
,onStoreLoad: function(store, rec){
if(store.reader.jsonData.msg){ msg = store.reader.jsonData.msg; this.getView().emptyText = msg; this.getView().refresh(false); }
} PHP code: if (!in_array ('curl', get_loaded_extensions())) {
$response &#91;&#39;results&#39;&#93; = array();
$response &#91;&#39;msg&#39;&#93; = '<p><b>cURL extension is not activated in your PHP configuration.</b></p>
<p>Package managment need this extension in order to work properly.<br/> Please activate cURL and try again.</p>';
$response &#91;&#39;success&#39;&#93; = true;
return $this->modx->toJSON($response);
} And the following CSS rules: .x-grid-empty{
padding-top: 2em;
text-align: center;
font-size:14px;
}

**Comment by splittingred** [comment]
splittingred submitted:

Done in r7115
