### ISSUE TITLE
When updating/saving a resource by drag-and-drop in the tree (changing parent), no Event is invoked

### ISSUE THREAD

**Issue by rubenk** [modxbot/migrate#10637]
rubenk created Redmine issue ID 10637

When updating/saving a resource by drag-and-drop in the tree (changing parent), their should be an Event invoked like OnDocFormSave (I know strictly it is not by 'Form' save, but the resource changes, and plugins should know that) An example plugin can be the Redirector-plugin, monitoring the location of all Resources and saving existing URLs to Resources that has been moved by drag and drop in the tree on the left.
:
The following example-code can be added to /core/model/modx/processors/resource/sort.php (because 'sort' is the action being triggered) after:
$node->set('menuindex',$ar_node &#91;&#39;order&#39;&#93; );
$node->save(); /\* invoke OnDocFormSave event */
$modx->invokeEvent('OnDocFormSave', array(
'mode' => 'sort',
'id' => $node->get('id'),
'resource' => &$node,
));

**Comment by splittingred** [comment]
splittingred submitted:

Added OnResourceSort and OnResourceBeforeSort events in r7122. (Also added OnResourceDelete, OnResourceUndelete, OnResourceDuplicate and OnResourceToolbarLoad)
