### ISSUE TITLE
friendly_url_prefix still exists in revolution code, throwing a php warning message in modcontext.class.php (line 171)

### ISSUE THREAD

**Issue by rubenk** [modxbot/migrate#10634]
rubenk created Redmine issue ID 10634

friendly_url_prefix still exists in revolution code, throwing a php warning message in modcontext.class.php (line 171)

**Comment by splittingred** [comment]
splittingred submitted:

The patch in 7125 causes a side issue: $ph = array('file' => 123); $output = $modx->makeUrl(571,'',$ph); always generates: download/downloading.html&file=123 Note the & first, which should be ?. Reverting 7125's commit on modcontext.class.php fixes this side issue, but reopens the issue above. r7125 has been reverted in r7151.

**Comment by opengeek** [comment]
opengeek submitted:

And fixed properly in r7153
