### ISSUE TITLE
PHP errors: There was an error retrieving or creating session id: ruvek0nkfn9a9e0pi11bs3gt41 (server-specific)

### ISSUE THREAD

**Issue by rubenk** [modxbot/migrate#10631]
rubenk created Redmine issue ID 10631

I retreive an error on each pageview, like this one:
 &#91;2010-07-12 12:23:32&#93; (INFO @ /index.php) There was an error retrieving or creating session id: ruvek0nkfn9a9e0pi11bs3gt41

**Comment by splittingred** [comment]
splittingred submitted:

This seems to be an issue with your server environment. Are you sure you have sessions configured correctly in PHP?

**Comment by rubenk** [comment]
rubenk submitted:

From my PHPinfo(): session Session Support enabled
Registered save handlers files user
Registered serializer handlers php php_binary wddx Directive Local Value Master Value
session.auto_start Off Off
session.bug_compat_42 Off Off
session.bug_compat_warn On On
session.cache_expire 180 180
session.cache_limiter nocache nocache
session.cookie_domain no value no value
session.cookie_httponly Off Off
session.cookie_lifetime 604800 0
session.cookie_path / /
session.cookie_secure Off Off
session.entropy_file no value no value
session.entropy_length 0 0
session.gc_divisor 1000 1000
session.gc_maxlifetime 604800 1440
session.gc_probability 1 1
session.hash_bits_per_character 5 5
session.hash_function 0 0
session.name PHPSESSID PHPSESSID
session.referer_check no value no value
session.save_handler user files
session.save_path /var/lib/php/session /var/lib/php/session
session.serialize_handler php php
session.use_cookies On On
session.use_only_cookies Off Off
session.use_trans_sid 0 0

**Comment by opengeek** [comment]
opengeek submitted:

In addition to PHP version, please provide as much information about your environment as possible (i.e. mysql version, mysql client API version, web server, OS at least). Also, do you have any Snippets running on the Resources being accessed? Or plugins running on every request?
