### ISSUE TITLE
New Context Access Denied

### ISSUE THREAD

**Issue by chryan** [modxbot/migrate#10646]
chryan created Redmine issue ID 10646

Creating new context and giving users admin access to it will cause the context to be inaccessible until admin user relogs. Steps to reproduce:
1) Create a new context.
2) Assign admin permissions to user for new context (User Group: Administrator, Authority: 0, Access Policy: 0)
3) Attempts to access the new context will give a "Access denied!" error. Relogging seems to solve the problem and the bug doesn't seem to be reproducible afterwards.
I am unsure if this is a bug related to the upgrade from RC2 to RC3 that I performed.

**Comment by chryan** [comment]
chryan submitted:

Just found out that the problem is not reproducible with a context of the same name. Creating a new context, however, will give the same problem until the user relogs.

**Comment by splittingred** [comment]
splittingred submitted:

You need to "Flush All Sessions" (under Security menu) after adding Context permissions, as permissions are stored in the session and will need to be reloaded.
