### ISSUE TITLE
Method sanitize may not work as expected

### ISSUE THREAD

**Issue by rfoster** [modxbot/migrate#10649]
rfoster created Redmine issue ID 10649

I was looking at the sanitize method in core/model/modx/modx.php, and I think that the way it is coded the depth argument will not function as expected. As it loops through the items in $target, $depth is decremented in a function call. I believe this should be changed to $depth - 1 so that the value does not change. &#91;code&#93;
public static function sanitize(array &$target, array $patterns= array(), $depth= 3, $nesting= 10) {
while (list($key, $value)= each($target)) {
if (is_array($value) && $depth > 0) {
modX :: sanitize($value, $patterns, $depth--);
 &#91;/code&#93;

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r7094
