### ISSUE TITLE
onunload firing incorrectly in IE

### ISSUE THREAD

**Issue by splittingred** [modxbot/migrate#10647]
splittingred created Redmine issue ID 10647

onunload firing incorrectly in IE

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r7089. Can be temporarily fixed by removing the code: Ext.EventManager.on(window, 'beforeunload',function(e) {
MODx.releaseLock(this.config.resource);
MODx.sleep(400);
e.browserEvent.returnValue = '';
},this); call in manager/assets/modext/sections/resource/update.js, around line 41.

**Comment by StevenLangbroek** [comment]
stevenlangbroek submitted:

The temporary fix didn't work (flushed entire IE cache, still get the message...) Any other workaround available?

**Comment by StevenLangbroek** [comment]
stevenlangbroek submitted:

Sorry, didn't mean to reopen it, just wanted to comment (new to JIRA)

**Comment by splittingred** [comment]
splittingred submitted:

Hm, if it's not fixed, lets definitely keep it open. Will look again. Not sure why its firing.

**Comment by StevenLangbroek** [comment]
stevenlangbroek submitted:

Well I'm running RC2 (rev6923), i'm not saying it's not fixed in the upcoming release, just that the hotfix stated above doesn't fix the issue. If you'd like to keep it open, please do.

**Comment by splittingred** [comment]
splittingred submitted:

Okay, definitely cannot replicate on IE after SVN update. Betting your install has a browser cache issue, or the function wasnt fully removed. Closing ticket.
