### ISSUE TITLE
Quick Update doesn't work in IE 8

### ISSUE THREAD

**Issue by devtrench** [modxbot/migrate#10643]
devtrench created Redmine issue ID 10643

I click on Quick Update Resource in the context menu and I get the JS error below. This only happens in IE 8 (haven't tested other IE versions), and works fine for me on the same site with Firefox. Webpage error details User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0; WOW64; Trident/4.0; SLCC1; .NET CLR 2.0.50727; Media Center PC 5.0; .NET CLR 3.5.21022; .NET CLR 3.5.30729; .NET CLR 1.1.4322; .NET CLR 3.0.30729; .NET4.0C)
Timestamp: Thu, 8 Jul 2010 19:21:45 UTC Message: Invalid argument.
Line: 7
Char: 60073
Code: 0
URI: http://localhost/example.com/web/manager/assets/ext3/ext-all.js Message: Invalid argument.
Line: 7
Char: 60073
Code: 0
URI: http://localhost/example.com/web/manager/assets/ext3/ext-all.js

**Comment by splittingred** [comment]
splittingred submitted:

Is it just Quick Update, or Quick Create as well?

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r7106

**Comment by devtrench** [comment]
devtrench submitted:

Yeah, it was just Quick Update You're too quick for me. Thanks for the fix.
