### ISSUE TITLE
phpthumb does not create proper thumbnails in MODx Browser

### ISSUE THREAD

**Issue by gerritvanaaken** [modxbot/migrate#10650]
gerritvanaaken created Redmine issue ID 10650

I tried several file paths and ressource URLs options, but the MODx browser does not generate thumbnails of my images. In RC-2, the MODx browser just showed the raw image and let the browser scale. Now in RC-3 phpthumb is being used in the ressource browser, but it doesn't work here.

**Comment by gerritvanaaken** [comment]
gerritvanaaken submitted:

Screenshots and phpinfo

**Comment by splittingred** [comment]
splittingred submitted:

Gah, was a capitalization issue. Fixed in r7099 - to fix, go to: core/model/modx/processors/system/phpthumb.php and on line 20, change 'phpThumb' to 'phpthumb' in the include.

**Comment by splittingred** [comment]
splittingred submitted:

Bah, also the fix in r7100. You can see the changes here: http://svn.modxcms.com/crucible/changelog/modx/?cs=7100
