### ISSUE TITLE
mod_rewrite - International URLS not parsed

### ISSUE THREAD

**Issue by grinko** [modxbot/migrate#10657]
grinko created Redmine issue ID 10657

Hello, I have enabled SEO friendy urls and they work fine for latin character. When I want to SEO a Greek URL to say this:
www.mywebsite.gr/???? ?????? It doesnt seem to work and it returns the ID number. I have added the AddDefaultCharset UTF-8 to the .conf file. Any suggestions? OpenGeek - Reply
It seems to be a couple of issues. First, by default the alias transliteration doesn't seem to work with these characters and I'm not sure why. Second, even when that does work, the request handler doesn't seem to be allowing those characters either. Can you enter a ticket for this in JIRA?

**Comment by mkschell** [comment]
netprophet submitted:

What's an example Greek URL that isn't working?
I've tried a couple of Greek UTF-8 characters in FURLs and they work.
I'm a little confused by OpenGeek's comment about transliteration not seeming to work, but I think it's a bit out of context.
If I can get some more clarity on this problem, I'll try to take it further.

**Comment by opengeek** [comment]
opengeek submitted:

I mean the option friendly_alias_translit which applies transliteration rules to the alias provided (or automatically generated from the pagetitle). Until I specified 'none' as the value in a system setting, I was not able to save that Greek string. And then the URL was rewritten automatically to the id of the resource plus the .html extension. Of course now, for some unknown reason, it works as expected. :/ Am continuing research into this.

**Comment by opengeek** [comment]
opengeek submitted:

Some issues were addressed that should reduce the number of problems with international URL generation out of the box. In particular, the PCRE u modifier was used to avoid an error which was mangling the particular Greek string that was being tested here. For some reason /\s+/ was matching a letter as if it were a space and mutilating the string; /\s+/u as the pattern works fine, though this needs to be more thoroughly tested across various environments, as it is possible it could cause errors in some environments.
