### ISSUE TITLE
Advanced/Upgrade install is the same as Upgrade/Existing

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#10656]
shamblett created Redmine issue ID 10656

From this forum thread :- http://modxcms.com/forums/index.php/topic,51297.msg298074/topicseen.html#msg298074 On page 3 selecting the Advanced upgrade install option seems to follow the same installation path as the Upgrade existing install option, should these be different? There seems to be no difference between these two install methods.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r7136
