### ISSUE TITLE
Placeholders for Query-Time and Query-Count aren't working

### ISSUE THREAD

**Issue by dschubert** [modxbot/migrate#10659]
dschubert created Redmine issue ID 10659

The placeholders &#91;^q^&#93; and &#91;^qt^&#93; for query-count and query-time are not working. &#91;^p^&#93; , &#91;^t^&#93; and &#91;^s^&#93; are working. Seems like /core/model/modx/modresponse.class.php , lines 94 and 96 are returning empty values.

**Comment by splittingred** [comment]
splittingred submitted:

Duplicate of MODX-1693
