### ISSUE TITLE
Download of Static Resource with application/pdf ContentType not working

### ISSUE THREAD

**Issue by opengeek** [modxbot/migrate#10660]
opengeek created Redmine issue ID 10660

Download of PDF files as static resources is apparently not working. See http://modxcms.com/forums/index.php/topic,44920.0.html for discussion of the problem.

**Comment by opengeek** [comment]
opengeek submitted:

See additional discussion at http://modxcms.com/forums/index.php/topic,54807.0.html It appears there may be an error in the tertiary logic in line 150, though it only seems to affect some environments. Still a very odd issue.

**Comment by opengeek** [comment]
opengeek submitted:

I cannot confirm any problem with the tertiary logic. Only problem I can reproduce is when friendly_urls are disabled and you try to serve a pdf inline with gzip compression enabled on your site. I currently do not know how to solve this, but will research for future improvement.

**Comment by mjeni** [comment]
mjeni submitted:

I have the same problem: (static resource, friendly urls turned off, custom pdf content type, content disposition attachment --> internal server error).
So I spent some time in further investigation of this problem and found out, that the modx script returns these bad headers for the pdf request:

<pre>
Set-Cookie: PHPSESSID=bb4d986e515ac4bba8d8b4b31db978ba; expires=Thu, 02 Dec 2010 22:35:45 GMT; path=/modx_rev/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Pragma: no-cache
Content-Disposition: attachment; filename=20
Content-Type: application/pdf
Content-Transfer-Encoding: binary
Content-Length: 292421
Cache-Control: public
inline
Vary: User-Agent
</pre>

Which leads me to this line in core/model/modx/modstaticresource.class.php:

<pre>
$header= 'Content-Disposition: ' . $this->get('content_dispo') ? 'inline' : 'attachment' . '; filename=' . $name;
</pre>

which should be:

<pre>
$header= 'Content-Disposition: ' . ($this->get('content_dispo') ? 'inline' : 'attachment' . '; filename=' . $name);
</pre>

Note the missing parentheses. So the string concatenation is performed before the conditional check what is not intended here.

**Comment by opengeek** [comment]
opengeek submitted:

Fixed for 2.0.5-pl. Commit details at https://github.com/modxcms/revolution/commit/844625cf0fedd2d87760f763cde6672561106427
