### ISSUE TITLE
Manager initializes "Content Type" field to "HTML" unexpectedly.

### ISSUE THREAD

**Issue by enogu** [modxbot/migrate#10663]
enogu created Redmine issue ID 10663

When an existing XML document is opened, the manager often sets Content Type to "HTML" automatically.

**Comment by enogu** [comment]
enogu submitted:

I guess there is a possibility too that MODx failed to save the document's Content Type field.

**Comment by splittingred** [comment]
splittingred submitted:

Cant reproduce this under any browser circumstances.
