### ISSUE TITLE
Allow Package Provider to be changed on already loaded Packages in Package Management

### ISSUE THREAD

**Issue by opengeek** [modxbot/migrate#10665]
opengeek created Redmine issue ID 10665

Allow the provider to be changed on packages that are already loaded in package management. This will allow, for instance, a package that was loaded manually to be tied to an online provider to check for updates at a later time, or for users to switch providers for certain components that might have been forked.

**Comment by splittingred** [comment]
splittingred submitted:

Done in r7053
