### ISSUE TITLE
MODx doesn't show lexicon topics other then "default" in custom components due to wrong path

### ISSUE THREAD

**Issue by b03tz** [modxbot/migrate#10671]
b03tz created Redmine issue ID 10671

I've just did some testing and when i open up "modlexicon.class.php" there's
a function called "getTopicList" which iterates over the topic directory like so: Code: $corePath = $this->getNamespacePath($namespace);
$lexPath = str_replace('//','/',$corePath.'/lexicon/'.$language.'/'); $topics = array(); if (!is_dir($lexPath)) return $topics; If i echo $lexPath it shows an unprocessed: {core_path} in the string...shouldn't
this be the actual corepath?

A hotfix for this would be:
Code:

public function getNamespacePath($namespace = 'core') {
$corePath = $this->modx->getOption('core_path',null,MODX_CORE_PATH);
if ($namespace != 'core') {
$namespaceObj = $this->modx->getObject('modNamespace',$namespace);
if ($namespaceObj) {
// Changed this line:
// $corePath = $namespaceObj->get('path');

// To this
$corePath = str_replace('{core_path}', $corePath, $namespaceObj->get('path'));
}
}
return $corePath;
}

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r7007
