### ISSUE TITLE
When a setting has never been modified, the "Last Modified" column states 1 Jan of 1970

### ISSUE THREAD

**Issue by dae** [modxbot/migrate#10673]
dae created Redmine issue ID 10673

In "System Settings" (?a=70), when a setting has never been modified, in the "Last Modified" column it shows the start of unixtime, 1 Jan of 1970. I believe it should be set to either "Never" or the date of the installation.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r7009
