### ISSUE TITLE
Right click menu doesn't appear under the cursor

### ISSUE THREAD

**Issue by dae** [modxbot/migrate#10677]
dae created Redmine issue ID 10677

The right click menu doesn't appear under the cursor on some Manager pages. See the screenshot:
 http://www.imagocentre.com/images/61/Right-click-menu_101.png (The screenshot is from "Access Controls" page, ?a=53) However, on other pages, such as "Manage Users" (?a=52), it works as expected.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r7010
