### ISSUE TITLE
Erroneous lexikon string?

### ISSUE THREAD

**Issue by Pont** [modxbot/migrate#10687]
pont created Redmine issue ID 10687

The following is found in setting.inc.php. The second sentence in setting_cache_handler_desc is a duplicate of setting_cache_lang_js_desc and confuses the description. It should be removed? $_lang &#91;&#39;setting_cache_handler&#39;&#93; = 'Caching Handler Class';
$_lang &#91;&#39;setting_cache_handler_desc&#39;&#93; = 'The class name of the type handler to use for caching. If set to true, this will use server headers to cache the lexicon strings loaded into JavaScript for the manager interface.'; $_lang &#91;&#39;setting_cache_lang_js&#39;&#93; = 'Cache Lexicon JS Strings';
$_lang &#91;&#39;setting_cache_lang_js_desc&#39;&#93; = 'If set to true, this will use server headers to cache the lexicon strings loaded into JavaScript for the manager interface.';

**Comment by splittingred** [comment]
splittingred submitted:

Yes, it should be.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r7008
