### ISSUE TITLE
(WARN @ /index.php) Language string not found: "and" - in method cleanAlias()

### ISSUE THREAD

**Issue by blackraven** [modxbot/migrate#10682]
blackraven created Redmine issue ID 10682

When using the method cleanAlias(), the following warning appears in the errorlog: (WARN @ /index.php) Language string not found: "and" This warning seams to be caused by the following part of the modResource::cleanAlias() code: if ($this->xpdo instanceof modX && $this->xpdo->getService('lexicon','modLexicon')) { $alias = str_replace('&', $this->xpdo->lexicon('and') ? ' ' . $this->xpdo->lexicon('and') . ' ' : ' and ', $alias); }

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r7013
