### ISSUE TITLE
Can't get form customization set TV default to work

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10685]
bobray created Redmine issue ID 10685

I'm getting no default value on any type of TV. Not sure if this is a bug, or if the docs are out of date. The "Set to Default" button works if the the Action is set to core - resource/tvs, but the "reload" button clears it again.

**Comment by BobRay** [comment]
bobray submitted:

The docs are here: http://svn.modxcms.com/docs/display/revolution/tvDefault

**Comment by splittingred** [comment]
splittingred submitted:

No longer valid since RELOAD btn is nuked.
