### ISSUE TITLE
Unable to open second Image Template Variable on a resource due to javascript error.

### ISSUE THREAD

**Issue by rubenk** [modxbot/migrate#10693]
rubenk created Redmine issue ID 10693

When having more than one Template Variable with input and output type "Image" on a page in the manager, after opening one Image selectionbox, any other won't open anymore. Reload of the page is needed. Javascript error when closing the first Image selectionbox:
Uncaught TypeError: undefined is not a function
native_runtime.js:392 Javascript error when opening an other than the first Image selectionbox:
Uncaught TypeError: Cannot call method 'show' of undefined
/manager/assets/modext/core/modx.view.js:140 Opening the first opened Image selectionbox again ain't a problem.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r7104
