### ISSUE TITLE
System settings : refresh button never stops loading

### ISSUE THREAD

**Issue by frenchfries** [modxbot/migrate#10699]
frenchfries created Redmine issue ID 10699

When loading system settings page in the manager, the refresh buttons keeps loading. All the buttons of the bottom pagination system remain grey. When clicking on "next page" the following settings are displayed but the current page number is not updated. Clearing cache resolves the problem.

**Comment by splittingred** [comment]
splittingred submitted:

I can't reproduce this at all; probably a file that didnt get uploaded, a cache error with APC/eAccelerator/xCache, or an ubuntu error (ubuntu is known for faulty PDO drivers)
