### ISSUE TITLE
Slash appended to image TV urls

### ISSUE THREAD

**Issue by leaase** [modxbot/migrate#10698]
leaase created Redmine issue ID 10698

After upgradeing to Revolution RC2 when I add an image to an image TV there is a slash appended to the image URL. Before upgrade: image/workers/2010/a-worker.jpg
After upgrade: /image/workers/2010/a-worker.jpg This results in the browser looking for the image in the root folder. So when I have a modx installation in http://localhost:8888/knms/modx the browser looks for the image in http://localhost:8888/ and the image is not found. It would be great if this is fixed

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6985
