### ISSUE TITLE
HTML tags in TV description field should be filtered

### ISSUE THREAD

**Issue by jrotering** [modxbot/migrate#10694]
jrotering created Redmine issue ID 10694

When HTML tags are entered in to the description field for a TV, they are not being filtered when displayed in a template that uses the TV. This is causing an HTML parsing error at some level, leading to unpredictable results. I entered a <script> tag in a TV description - only intended for descriptive purposes. When I went to edit a page that used a template with that TV, my TV category tabs didn't appear. I saw all my TVs from all categories in a single long list rather than tabs. In the problematic TV description, the text ended abruptly at the first appearance of <script>. Not sure if it would have made a difference if I had added a close tag </script>. But that's beside the point - this is a case where user input can cause unpredictable results in the manager display. Probably the appropriate path forward is to strip HTML tags out of element descriptions, either before they go in to the database or by filtering them before displaying in Manager.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r7024
