### ISSUE TITLE
The "Manage Users" Page (under Security) does not display properly in Google Chrome

### ISSUE THREAD

**Issue by Ineffable** [modxbot/migrate#10695]
ineffable created Redmine issue ID 10695

The "Manage Users" Page (under Security) does not display properly in Google Chrome

**Comment by splittingred** [comment]
splittingred submitted:

Looks fine to me...what version of Chrome? What's wrong with it?

**Comment by Ineffable** [comment]
ineffable submitted:

Sorry about this, the problem resolved by itself the next time I logged in. Initially when I upgraded to RC-2 there was no menu bar on the left but now everything appears normal. Thanks
