### ISSUE TITLE
Problems with Manager Interface

### ISSUE THREAD

**Issue by Nacnud** [modxbot/migrate#10696]
nacnud created Redmine issue ID 10696

1) Toolbar is wrapping over the navigator.
2) Navigator Expand All not working.
3) Navigator minimum width is too wide.
4) Resource title hidden under floating buttons. 1) Toolbar is wrapping over the navigator.
I have a Components tab as well as the usual toolbar entries. This wraps once it bumps into the 'Logged in as' block. Unfortunately it wraps on top of the Navigator tabs making it exceeding difficult to select the Resources tab. If the user has a long login name then all the navigator tabs become really hard to select as they are all underneath toolbar buttons.
This is reproducible with FF and IE8. 2) Navigator Expand All not working.
The navigator Expand All button seems inoperative in FF and IE8. 3) Navigator minimum width is too wide.
On a low resolution screen (vanity spec laptop belonging to pointy haired boss) the navigator takes about a third of the available window width. The navigator could be resized and made bigger - but not smaller. The remaining 2/3 of the width is rather small for editing page content. A smaller minimum size would be much appreciated. This was seen in IE8. 4) Resource title hidden under floating buttons.
When viewing a resource on a low resolution screen the Save, Duplicate, Preview, etc buttons overlay the Document name. This is confusing as it's not clear which page is currently being displayed. I guess it won't be too long before we see some alternative Manager templates - but it would be great if these could be addressed in the core template.

**Comment by splittingred** [comment]
splittingred submitted:

What resolution are you using?

**Comment by Nacnud** [comment]
nacnud submitted:

Sean - the content author's screen is 1024x768.
It's a manager spec laptop and all they have access to! This screenshot demonstrates their challenge when using IE8 full-screen.
The blank space reserved by the navigator is as small as possible but it's still a significant part of the page considering they are authoring content that will be viewed on a much wider web-page (even on their screen).
I've also highlighted the problem they have using the editor toolbars. It is usable by getting them to juggle the page up and down till they can see the toolbar button they want to use. The easiest fix would be to allow the navigator to be reduced in width.
Even better would be a navigator collapse/expand button. As soon as the navigator can free us some width then two of the editor toolbars will stop wrapping and the overlapping buttons are no longer such a problem.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed, mostly, in r7016. The tree works fine for me in FF. It's not meant to expand the tree fully - just the root nodes. As for the floating bar - well, we dont plan to change the styling of it currently.
