### ISSUE TITLE
Make large file manager available in an easier way

### ISSUE THREAD

**Issue by gerritvanaaken** [modxbot/migrate#10709]
gerritvanaaken created Redmine issue ID 10709

The small "files" tab on the left-hand side is fine, but it would be nice to just start the large file resource manager with a simple click. Today, you have to go to an article and abuse the TinyMCE-image button to start this file manager, which is not very elegeant. I provide you with a simple mockup.

**Comment by gerritvanaaken** [comment]
gerritvanaaken submitted:

That's how it could look like

**Comment by splittingred** [comment]
splittingred submitted:

Done in r6952
