### ISSUE TITLE
setProperties() not honoring merge argument

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10700]
bobray created Redmine issue ID 10700

When you call element->setProperties($props, true), all existing properties are deleted and replaced with the ones in $props. I think this is true of propertySet->setProperties() as well. I think line 519 of core/model/modx/modelement.class.php should change from this: $set = $this->set('properties', $propertiesArray); to this: $set = $this->set('properties', $propertyArray); The bug is also present in line 121 of core/model/modx/modpropertyset.class.php I'm assuming that the version in core/model/modx/modparser.class/php is the correct one.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r7076
