### ISSUE TITLE
Upgrade to RC2 fails on database with utf8 character set.

### ISSUE THREAD

**Issue by martinf55** [modxbot/migrate#10706]
martinf55 created Redmine issue ID 10706

The setup failed quietly at this point: ALTER TABLE modx_lexicon_entries CHANGE `topic` `topic` VARCHAR(255) NOT NULL DEFAULT 'default' with
Error code 1071, SQL state 42000: Specified key was too long; max key length is 1000 bytes due to the combined length of the columns in index "uniqentry" adding to more than 1000 bytes when accounting for the 3 byte characters in UTF8. The maximum length for topic that would work is VARCHAR(18), which probably isn't long enough...
Changing the collation on the columns in that index to latin1_swedish_ci allowed a length of VARCHAR(228), which is plenty long enough for existing topics. Although it is a peculiar number (the original modx_lexicon_topics.name was varchar 100). What should be the proper way around this for an installation that wants the ability to use unicode character sets? I guess for now I can change the rc2 upgrade file to use varchar(228) to get the setup finished.

**Comment by martinf55** [comment]
martinf55 submitted:

Please downgrade to Minor since the database entries are only required for overrides, and there is a workaround for the index length issue.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r7030
