### ISSUE TITLE
doc vanishes from tree after drag-n-drop at bottom of opened context 

### ISSUE THREAD

**Issue by frenchfries** [modxbot/migrate#10719]
frenchfries created Redmine issue ID 10719

After a drag'n drop very close from the next context, the whole moved container disappeared form the tree with all its children. When searching the document form the menu I can edit it but it cannot be saved

**Comment by frenchfries** [comment]
frenchfries submitted:

Forum entry about this :
 http://modxcms.com/forums/index.php/topic,49903.msg290901.html#msg290901

**Comment by frenchfries** [comment]
frenchfries submitted:

This makes documents visible again :
UPDATE modx_site_content SET context_key='web' WHERE context_key='0'

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6937
