### ISSUE TITLE
Creating subfolders within "images", "media", "flash or "files" not possible.

### ISSUE THREAD

**Issue by gerritvanaaken** [modxbot/migrate#10710]
gerritvanaaken created Redmine issue ID 10710

The recommended method for managing upload files always seemed to be: root
&#8211; assets
---- images
---- files
---- flash
---- media (As known from Evo) In Evo, the editor was able to create subfolders within the "images", "files" ... directories. In Revo RC-2 this seems not possible anymore. Why is that?

**Comment by splittingred** [comment]
splittingred submitted:

It's definitely possible, what do you mean?

**Comment by gerritvanaaken** [comment]
gerritvanaaken submitted:

I'm so sorry, I just have to use the right-click!! Did not see that. How embarrasing.
