### ISSUE TITLE
time formatting PHP Warning "Invalid CRT parameters" appearing in multiple locations on Windows install

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#10712]
netprophet created Redmine issue ID 10712

PHP on Windows does not support all strftime formatters, and %s seems to be causing some troubles on my Windows install. Today I have seen this warning during Revo install, and during install of Packages
 http://msdn.microsoft.com/en-us/library/az4se3k1%28VS.71%29.aspx

**Comment by mkschell** [comment]
netprophet submitted:

In addition to the use of the "%s" formatter, I'm seeing some weird behavior in that each time %s is attempted on my system, the error log is written to 5 times.
I will try to isolate this and perhaps file another ticket if I can replicate it in another way.

**Comment by opengeek** [comment]
opengeek submitted:

This is happening because of code in the modSessionHandler I believe. If I am correct, this is now fixed. Re-open if not. That was the only instance of %s I could see used as a strftime modifier (via xPDOObject::get() format parameter).
