### ISSUE TITLE
PHP doesn't have permission to delete test file in modInstall :: is_writable2

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#10714]
netprophet created Redmine issue ID 10714

Getting 'permission denied' error trying to unlink test file during install's is_writable2 check.
Seems PHP at least in my configuration can't delete a file while the file pointer is still open.
Closing the file pointer first, then unlinking the file solves for me: /\* attempt to delete test file */ fclose($fp); $written = @unlink($filePath);

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6943
