### ISSUE TITLE
modInstallTest directory checks fail on first pass (server-specific)

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#10713]
netprophet created Redmine issue ID 10713

Installation Summary screen shows, on first attempt, 3 "Failed!" for directory exists, and 3 for directory is writable.. and messages do not contain the paths that they should be checking.
Will upload screenshot shortly.
These "Failed!" notices correct themselves after clicking "Retry".

**Comment by mkschell** [comment]
netprophet submitted:

Also, may be related to this (installer, Windows, SVN version...) is that when I ran the installer again in "upgrade" mode, the database connection screen behaved as if it were a new install (asking for Admin username, email etc). To resolve, I simply pressed Back, then Next again and the database connection screen then behaved as expected.

**Comment by mkschell** [comment]
netprophet submitted:

I am not able to replicate this while debugging, but the described behavior is still happening. It may be specific to my environment, I know that ZendServer is not a common environment for people on Windows. If anyone developing on Windows is able to look at this, and post whether you can or cannot replicate, it would be helpful.

**Comment by opengeek** [comment]
opengeek submitted:

Is this still an issue?

**Comment by mkschell** [comment]
netprophet submitted:

Just ran setup in both install and upgrade mode from SVN.. issue seems to be gone.
