### ISSUE TITLE
Right Click on System Settings Grid

### ISSUE THREAD

**Issue by gluethegiant** [modxbot/migrate#10715]
paulmerchant created Redmine issue ID 10715

Right clicking no longer works on System Settings Grid. Bug introduced with RC-2. Without right click, there's no way to fully edit the namespace, field type, description, or to delete keys. One workaround is to edit the modx_system_settings table directly.

**Comment by splittingred** [comment]
splittingred submitted:

Already fixed in r6935. Thanks!
