### ISSUE TITLE
Strange upload and browser behaviour (file manager)

### ISSUE THREAD

**Issue by gerritvanaaken** [modxbot/migrate#10724]
gerritvanaaken created Redmine issue ID 10724

The file manager does not behave as it should. I have a folder in my root directory called "assets". Here I manually inserted those four subfolders "images", "files", "flash" and "media", as told by the help text in the file systems settings. All those folders are on chmod 777. By default the file manager (both, the small version in the left sidebar as well as the large one I can call through TinyMCE) show my root direcory, which is not what I want. When I play with the "file system" settings, I can tell the file manager to "begin" within the assets folder, which is fine. Now the real problems: When I upload a jpg or a png image (or any other kind), it is placed within the assets folder, but not within the correct "images" subfolder. I cannot drag the images into the subfolders, there is always this red icon. Renaming the image's path name sort of helps, but this is not very elegant and breaks the permissions somehow... In the large file manager, the thumbnails are not displayed correctly, because the path is wrong If I set the file settings to default values, I can make the thumbs visible in the large file manager, but now the file manager will start at the root level once again. Could you make it possible to... start at the "assets" level in both file managers automatically put files in the correct subfolders provide a link to the large file manager somewhere in the navigation. Having to use TinyMCE for that is uncool drag and drop files in the asstes file tree.

**Comment by gerritvanaaken** [comment]
gerritvanaaken submitted:

Forget about the wrong path for the thumbnails, I forgot to set the Resource URL. Now I only have the problems with the subfolders.

**Comment by splittingred** [comment]
splittingred submitted:

The folders are always red, as you cannot drag/drop with files You can do upload/file browsing via the Files tab in the left tree I'm not sure what's the bug here. Could you please either:
A) Repost this bug as a single issue with the problem?
B) Clarify in this issue what is the problem?

**Comment by gerritvanaaken** [comment]
gerritvanaaken submitted:

Sorry for the confusion! I'll open two new topics with clear description!
