### ISSUE TITLE
Duplicate context option

### ISSUE THREAD

**Issue by chucktrukk** [modxbot/migrate#10728]
chucktrukk created Redmine issue ID 10728

An option to 'Duplicate Context' very similar to 'Duplicate Resource' Use case:
1. I have a default context named 'example.com' with certain context settings.
2. I click duplicate context so all of 'example.com' settings are the default
3. I update the different settings for this context and rename it.

**Comment by splittingred** [comment]
splittingred submitted:

Duplicating a context was done prior, but added code to duplicate the settings as well in r6915.
