### ISSUE TITLE
Completely blank screen response following installation and manager login (server-specific)

### ISSUE THREAD

**Issue by gemstone-zz** [modxbot/migrate#10720]
gemstone created Redmine issue ID 10720

Following on from MODX-1919 a clean installation of 2.0.0-rc-2 proceeds without error but a blank screen is returned after manager login. This is a completely empty zero length response. The code of manager/index.php is executed and the call is made to, but no return from $modx->request->handleRequest(); just the blank screen response. The contents of core/cache/logs/error.log with LOG_LEVEL_DEBUG after one access attempt &#91;2010-05-30 00:31:12&#93; (DEBUG @ /manager/index.php) System event OnInitCulture was executed but does not exist.
 &#91;2010-05-30 00:31:12&#93; (DEBUG @ /manager/index.php) System event OnHandleRequest was executed but does not exist.
 &#91;2010-05-30 00:31:12&#93; (DEBUG @ /manager/index.php) System event OnManagerPageInit was executed but does not exist.
 &#91;2010-05-30 00:31:12&#93; (DEBUG @ /manager/index.php) System event OnBeforeManagerPageInit was executed but does not exist.
 &#91;2010-05-30 00:31:12&#93; (WARN @ /www/html/modx2.xxxxxxxx.co.uk/core/model/modx/processors/system/config_check.inc.php : 105) PHP notice: Undefined index: mgrRole
 &#91;2010-05-30 00:31:12&#93; (ERROR @ /manager/index.php) Error preparing statement for query: SELECT `modActionDom`.`id` AS `modActionDom_id`, `modActionDom`.`action` AS `modActionDom_action`, `modActionDom`.`name` AS `modActionDom_name`, `modActionDom`.`description` AS `modActionDom_description`, `modActionDom`.`xtype` AS `modActionDom_xtype`, `modActionDom`.`container` AS `modActionDom_container`, `modActionDom`.`rule` AS `modActionDom_rule`, `modActionDom`.`value` AS `modActionDom_value`, `modActionDom`.`constraint` AS `modActionDom_constraint`, `modActionDom`.`constraint_field` AS `modActionDom_constraint_field`, `modActionDom`.`constraint_class` AS `modActionDom_constraint_class`, `modActionDom`.`active` AS `modActionDom_active` FROM `modx2_actiondom` AS `modActionDom` LEFT JOIN `modx2_access_actiondom` `Access` ON `modActionDom`.`id` = `Access`.`target` WHERE ( `modActionDom`.`action` = ? AND `modActionDom`.`active` = ? AND ( ( `Access`.`principal_class` = ? AND `Access`.`principal` IN (1) ) OR `Access`.`principal` IS ? ) ) Array
(
 &#91;0&#93; => 42000
 &#91;1&#93; => 1064
 &#91;2&#93; => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '? ) )' at line 1
) &#91;2010-05-30 00:31:12&#93; (WARN @ /www/html/modx2.xxxxxxxx.co.uk/core/cache/mgr/smarty/default/%%F7^F7F^F7F34188%%header.tpl.php : 36) PHP notice: Undefined index: a
 &#91;2010-05-30 00:31:12&#93; (WARN @ /www/html/modx2.xxxxxxxx.co.uk/core/cache/mgr/smarty/default/%%F7^F7F^F7F34188%%header.tpl.php : 39) PHP notice: Undefined index: a
 &#91;2010-05-30 00:31:12&#93; (DEBUG @ /manager/index.php) System event OnInitCulture was executed but does not exist.
 &#91;2010-05-30 00:31:12&#93; (DEBUG @ /manager/index.php) System event OnHandleRequest was executed but does not exist.
 &#91;2010-05-30 00:31:12&#93; (DEBUG @ /manager/index.php) System event OnManagerPageInit was executed but does not exist.
 &#91;2010-05-30 00:31:12&#93; (DEBUG @ /manager/index.php) System event OnBeforeManagerPageInit was executed but does not exist.
 &#91;2010-05-30 00:31:12&#93; (WARN @ /www/html/modx2.xxxxxxxx.co.uk/core/model/modx/processors/system/config_check.inc.php : 105) PHP notice: Undefined index: mgrRole
 &#91;2010-05-30 00:31:12&#93; (ERROR @ /manager/index.php) Error preparing statement for query: SELECT `modActionDom`.`id` AS `modActionDom_id`, `modActionDom`.`action` AS `modActionDom_action`, `modActionDom`.`name` AS `modActionDom_name`, `modActionDom`.`description` AS `modActionDom_description`, `modActionDom`.`xtype` AS `modActionDom_xtype`, `modActionDom`.`container` AS `modActionDom_container`, `modActionDom`.`rule` AS `modActionDom_rule`, `modActionDom`.`value` AS `modActionDom_value`, `modActionDom`.`constraint` AS `modActionDom_constraint`, `modActionDom`.`constraint_field` AS `modActionDom_constraint_field`, `modActionDom`.`constraint_class` AS `modActionDom_constraint_class`, `modActionDom`.`active` AS `modActionDom_active` FROM `modx2_actiondom` AS `modActionDom` LEFT JOIN `modx2_access_actiondom` `Access` ON `modActionDom`.`id` = `Access`.`target` WHERE ( `modActionDom`.`action` = ? AND `modActionDom`.`active` = ? AND ( ( `Access`.`principal_class` = ? AND `Access`.`principal` IN (1) ) OR `Access`.`principal` IS ? ) ) Array
(
 &#91;0&#93; => 42000
 &#91;1&#93; => 1064
 &#91;2&#93; => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '? ) )' at line 1
) &#91;2010-05-30 00:31:12&#93; (WARN @ /www/html/modx2.xxxxxxxx.co.uk/core/cache/mgr/smarty/default/%%F7^F7F^F7F34188%%header.tpl.php : 36) PHP notice: Undefined index: a
 &#91;2010-05-30 00:31:12&#93; (WARN @ /www/html/modx2.xxxxxxxx.co.uk/core/cache/mgr/smarty/default/%%F7^F7F^F7F34188%%header.tpl.php : 39) PHP notice: Undefined index: a
 &#91;2010-05-30 00:31:12&#93; (DEBUG @ /manager/index.php) System event OnInitCulture was executed but does not exist.
 &#91;2010-05-30 00:31:12&#93; (DEBUG @ /manager/index.php) System event OnHandleRequest was executed but does not exist.
 &#91;2010-05-30 00:31:12&#93; (DEBUG @ /manager/index.php) System event OnManagerPageInit was executed but does not exist.
 &#91;2010-05-30 00:31:12&#93; (DEBUG @ /manager/index.php) System event OnBeforeManagerPageInit was executed but does not exist.
 &#91;2010-05-30 00:31:12&#93; (WARN @ /www/html/modx2.xxxxxxxx.co.uk/core/model/modx/processors/system/config_check.inc.php : 105) PHP notice: Undefined index: mgrRole
 &#91;2010-05-30 00:31:12&#93; (ERROR @ /manager/index.php) Error preparing statement for query: SELECT `modActionDom`.`id` AS `modActionDom_id`, `modActionDom`.`action` AS `modActionDom_action`, `modActionDom`.`name` AS `modActionDom_name`, `modActionDom`.`description` AS `modActionDom_description`, `modActionDom`.`xtype` AS `modActionDom_xtype`, `modActionDom`.`container` AS `modActionDom_container`, `modActionDom`.`rule` AS `modActionDom_rule`, `modActionDom`.`value` AS `modActionDom_value`, `modActionDom`.`constraint` AS `modActionDom_constraint`, `modActionDom`.`constraint_field` AS `modActionDom_constraint_field`, `modActionDom`.`constraint_class` AS `modActionDom_constraint_class`, `modActionDom`.`active` AS `modActionDom_active` FROM `modx2_actiondom` AS `modActionDom` LEFT JOIN `modx2_access_actiondom` `Access` ON `modActionDom`.`id` = `Access`.`target` WHERE ( `modActionDom`.`action` = ? AND `modActionDom`.`active` = ? AND ( ( `Access`.`principal_class` = ? AND `Access`.`principal` IN (1) ) OR `Access`.`principal` IS ? ) ) Array
(
 &#91;0&#93; => 42000
 &#91;1&#93; => 1064
 &#91;2&#93; => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '? ) )' at line 1
) &#91;2010-05-30 00:31:12&#93; (WARN @ /www/html/modx2.xxxxxxxx.co.uk/core/cache/mgr/smarty/default/%%F7^F7F^F7F34188%%header.tpl.php : 36) PHP notice: Undefined index: a
 &#91;2010-05-30 00:31:12&#93; (WARN @ /www/html/modx2.xxxxxxxx.co.uk/core/cache/mgr/smarty/default/%%F7^F7F^F7F34188%%header.tpl.php : 39) PHP notice: Undefined index: a

**Comment by splittingred** [comment]
splittingred submitted:

Were there any install error logs in the core/cache/logs/ directory? Was this advanced or traditional distro? Were you running eAccelerator, APC, etc?

**Comment by gemstone-zz** [comment]
gemstone submitted:
1. I have re-run the install from scratch and included the error log below which does show some install errors. The distro was unpacked to the site root and both chmod 777 and chown www-data:www-data were applied to the whole site tree before running setup. No post setup warning messages were shown.
2. The traditional distro was used.
3. To my knowledge eAccelerator, APC, etc are not being used. core/cache/logs/error.log &#91;2010-06-01 19:39:44&#93; (ERROR @ /setup/index.php) Could not copy /www/modx2/core/packages/core/modContext/cb6735d74324be818cbc168c34fee488/0/ to index.php
   &#91;2010-06-01 19:39:44&#93; (ERROR @ /setup/index.php) Could not copy /www/modx2/core/packages/core/modContext/cb6735d74324be818cbc168c34fee488/1/ to ht.access
   &#91;2010-06-01 19:39:44&#93; (ERROR @ /setup/index.php) Could not copy /www/modx2/core/packages/core/modContext/416c2e5105292945e37fc3fdd8099215/0/ to assets
   &#91;2010-06-01 19:39:44&#93; (ERROR @ /setup/index.php) Could not copy /www/modx2/core/packages/core/modContext/416c2e5105292945e37fc3fdd8099215/1/ to controllers
   &#91;2010-06-01 19:39:44&#93; (ERROR @ /setup/index.php) Could not copy /www/modx2/core/packages/core/modContext/416c2e5105292945e37fc3fdd8099215/2/ to templates
   &#91;2010-06-01 19:39:44&#93; (ERROR @ /setup/index.php) Could not copy /www/modx2/core/packages/core/modContext/416c2e5105292945e37fc3fdd8099215/3/ to ht.access
   &#91;2010-06-01 19:39:44&#93; (ERROR @ /setup/index.php) Could not copy /www/modx2/core/packages/core/modContext/416c2e5105292945e37fc3fdd8099215/4/ to index.php
   &#91;2010-06-01 19:39:44&#93; (ERROR @ /setup/index.php) Could not install files from /www/modx2/core/packages/core/xPDOFileVehicle/e1a99604dbe3574c67514fb6ee00a822/ to
   &#91;2010-06-01 19:39:44&#93; (ERROR @ /setup/index.php) Could not install files from /www/modx2/core/packages/core/xPDOFileVehicle/37716d61897c4e3b27eeeea6228fc421/ to
   &#91;2010-06-01 19:39:44&#93; (ERROR @ /setup/index.php) Could not install files from /www/modx2/core/packages/core/xPDOFileVehicle/20d024f77c7a330017db87ec029a7400/ to
   &#91;2010-06-01 19:39:44&#93; (ERROR @ /setup/index.php) Could not install files from /www/modx2/core/packages/core/xPDOFileVehicle/db5fe1e0bcf62416c0be9a49e5dc6d81/ to
   &#91;2010-06-01 19:39:44&#93; (ERROR @ /setup/index.php) Could not install files from /www/modx2/core/packages/core/xPDOFileVehicle/d9ca0463ea831c92ede1051ab7cfc625/ to
   &#91;2010-06-01 19:39:44&#93; (ERROR @ /setup/index.php) Could not install files from /www/modx2/core/packages/core/xPDOFileVehicle/67fca7fc2fd1d41b99372850903de700/ to
   &#91;2010-06-01 19:39:44&#93; (ERROR @ /setup/index.php) Could not install files from /www/modx2/core/packages/core/xPDOFileVehicle/87a2082dd4ea568d58eae1fcd1bb88ec/ to
   &#91;2010-06-01 19:39:44&#93; (ERROR @ /setup/index.php) Could not install files from /www/modx2/core/packages/core/xPDOFileVehicle/874c323e74f2fa87efba0b8407b290bf/ to
   &#91;2010-06-01 19:39:44&#93; (ERROR @ /setup/index.php) Could not install files from /www/modx2/core/packages/core/xPDOFileVehicle/6236add07797340510d138abafa998ff/ to
   &#91;2010-06-01 19:39:44&#93; (ERROR @ /setup/index.php) Could not install files from /www/modx2/core/packages/core/xPDOFileVehicle/269f4f43c713ad772b36298bb6af3e9f/ to
   &#91;2010-06-01 19:44:05&#93; (ERROR @ /manager/index.php) Error preparing statement for query: SELECT `modActionDom`.`id` AS `modActionDom_id`, `modActionDom`.`action` AS `modActionDom_action`, `modActionDom`.`name` AS `modActionDom_name`, `modActionDom`.`description` AS `modActionDom_description`, `modActionDom`.`xtype` AS `modActionDom_xtype`, `modActionDom`.`container` AS `modActionDom_container`, `modActionDom`.`rule` AS `modActionDom_rule`, `modActionDom`.`value` AS `modActionDom_value`, `modActionDom`.`constraint` AS `modActionDom_constraint`, `modActionDom`.`constraint_field` AS `modActionDom_constraint_field`, `modActionDom`.`constraint_class` AS `modActionDom_constraint_class`, `modActionDom`.`active` AS `modActionDom_active` FROM `modx2_actiondom` AS `modActionDom` LEFT JOIN `modx2_access_actiondom` `Access` ON `modActionDom`.`id` = `Access`.`target` WHERE ( `modActionDom`.`action` = ? AND `modActionDom`.`active` = ? AND ( ( `Access`.`principal_class` = ? AND `Access`.`principal` IN (1) ) OR `Access`.`principal` IS ? ) ) Array
   (
   &#91;0&#93; => 42000
   &#91;1&#93; => 1064
   &#91;2&#93; => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '? ) )' at line 1
   ) &#91;2010-06-01 19:44:05&#93; (ERROR @ /manager/index.php) Error preparing statement for query: SELECT `modActionDom`.`id` AS `modActionDom_id`, `modActionDom`.`action` AS `modActionDom_action`, `modActionDom`.`name` AS `modActionDom_name`, `modActionDom`.`description` AS `modActionDom_description`, `modActionDom`.`xtype` AS `modActionDom_xtype`, `modActionDom`.`container` AS `modActionDom_container`, `modActionDom`.`rule` AS `modActionDom_rule`, `modActionDom`.`value` AS `modActionDom_value`, `modActionDom`.`constraint` AS `modActionDom_constraint`, `modActionDom`.`constraint_field` AS `modActionDom_constraint_field`, `modActionDom`.`constraint_class` AS `modActionDom_constraint_class`, `modActionDom`.`active` AS `modActionDom_active` FROM `modx2_actiondom` AS `modActionDom` LEFT JOIN `modx2_access_actiondom` `Access` ON `modActionDom`.`id` = `Access`.`target` WHERE ( `modActionDom`.`action` = ? AND `modActionDom`.`active` = ? AND ( ( `Access`.`principal_class` = ? AND `Access`.`principal` IN (1) ) OR `Access`.`principal` IS ? ) ) Array
   (
   &#91;0&#93; => 42000
   &#91;1&#93; => 1064
   &#91;2&#93; => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '? ) )' at line 1
   ) &#91;2010-06-01 19:44:05&#93; (ERROR @ /manager/index.php) Error preparing statement for query: SELECT `modActionDom`.`id` AS `modActionDom_id`, `modActionDom`.`action` AS `modActionDom_action`, `modActionDom`.`name` AS `modActionDom_name`, `modActionDom`.`description` AS `modActionDom_description`, `modActionDom`.`xtype` AS `modActionDom_xtype`, `modActionDom`.`container` AS `modActionDom_container`, `modActionDom`.`rule` AS `modActionDom_rule`, `modActionDom`.`value` AS `modActionDom_value`, `modActionDom`.`constraint` AS `modActionDom_constraint`, `modActionDom`.`constraint_field` AS `modActionDom_constraint_field`, `modActionDom`.`constraint_class` AS `modActionDom_constraint_class`, `modActionDom`.`active` AS `modActionDom_active` FROM `modx2_actiondom` AS `modActionDom` LEFT JOIN `modx2_access_actiondom` `Access` ON `modActionDom`.`id` = `Access`.`target` WHERE ( `modActionDom`.`action` = ? AND `modActionDom`.`active` = ? AND ( ( `Access`.`principal_class` = ? AND `Access`.`principal` IN (1) ) OR `Access`.`principal` IS ? ) ) Array
   (
   &#91;0&#93; => 42000
   &#91;1&#93; => 1064
   &#91;2&#93; => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '? ) )' at line 1
   )

**Comment by opengeek** [comment]
opengeek submitted:

I suggest you start with a clean installation (perhaps when RC3 is out this week) and see if this still occurs. These errors indicate that your PDO_mysql configuration may be invalid or that you may have experienced an error related to timeouts in setup that cause the settings to be emptied. Otherwise, we cannot reproduce this problem.

**Comment by opengeek** [comment]
opengeek submitted:

Moving to 2.0.0-pl to allow time for additional feedback.

**Comment by opengeek** [comment]
opengeek submitted:

removing from 2.0.0-pl release list until additional feedback received
