### ISSUE TITLE
Form Rules can't set a specific template based on rules

### ISSUE THREAD

**Issue by xpix** [modxbot/migrate#10732]
xpix created Redmine issue ID 10732

HI, It seems you can't target the default template when using Form Rules. Sorry if this doesn't make sense. Here's the post for more details:
 http://modxcms.com/forums/index.php/topic,49784.0/topicseen.html

**Comment by opengeek** [comment]
opengeek submitted:

You also couldn't do it via a plugin, but I have now added that ability by allowing $_REQUEST &#91;&#39;template&#39;&#93; to be specified for the controller (and this can be set via OnDocFormPrerender event).

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6917
