### ISSUE TITLE
Can't run transport.core.php (possible server-specific ZipArchive issue)

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10738]
bobray created Redmine issue ID 10738

I haven't upgraded for a while, so it's a big jump. When I run transport.core.php, I get this: Beginning to zip up transport package... &#91;2010-05-25 13:49:03&#93; (ERROR @ /modx097/_build/transport.core.php) Error packing \xampp\htdocs\MODx097/core/packages/core to \xampp\htdocs\MODx097/core/packages/core.transport.zip: Array
(
 &#91;0&#93; => Error packing core/modContext/572c8e106e8aee96f3e30a6263f8f59a/0/assets/ext3/resources/images/default/tabs/tab-close.gif from \xampp\htdocs\MODx097/core/packages/core/modContext/572c8e106e8aee96f3e30a6263f8f59a/0/assets/ext3/resources/images/default/tabs/tab-close.gif Followed by ~1200 similar lines. Tried running it various ways &#8211; always the same result.
Tried to upgrade two different installs &#8211; same thing. Both sites are now trashed (new files, but no new install). I need to see the current version for the book, so it's critical for me (and might bite others who make a big version jump).

**Comment by splittingred** [comment]
splittingred submitted:

Is your core/packages directory writable?

**Comment by BobRay** [comment]
bobray submitted:

Hmmm... This is bizarre. All my MODx directories are set to read-only (XAMPP Vista). When I uncheck read-only, and click on OK, I can see it resetting all of them in the progress bar, but once I quit the dialog and return, it's read-only again. I've never seen anything like this and I haven't upgraded anything but MODx.

**Comment by splittingred** [comment]
splittingred submitted:

Since I definitely cannot reproduce this, closing it for now. As for your situation...I have no clue. Sounds like a Vista bug.

**Comment by BobRay** [comment]
bobray submitted:

On further examination, I don't think this is a permissions issue. The Vista read-only symbol for folders is ambiguous and I checked them at the CLI with attrib. They are not read only. Also, I can create zip files myself in any of the directories. It's starting to look more like a MODx issue.

**Comment by BobRay** [comment]
bobray submitted:

Oho. When I modified the code in xpdotransport.class.php to switch it from using ZipArchive to PclZip, the build works fine, so there may be a problem with ZipArchive (At least on my platform).

**Comment by opengeek** [comment]
opengeek submitted:

Can you provide details of the Zip extension on your platform. I cannot reproduce.

**Comment by BobRay** [comment]
bobray submitted:

I'm not sure where to look. I found this in the Apache config file: AddType application/x-compress .Z
AddType application/x-gzip .gz .tgz I found php_zip.dll in the php ext dir &#8211; Version 5.2.6
I also found it in the extras dir, but it reports no version number 7Zip and WinZip are also around somewhere, but I don't know if either is being used. I'm on Windows Vista Ultimate.

**Comment by opengeek** [comment]
opengeek submitted:

When you look at phpinfo, what information is there for zip? Mine looks like this: Zip enabled
Extension Version $Id: php_zip.c 276389 2009-02-24 23:55:14Z iliaa $
Zip version 1.9.1
Libzip version 0.9.0

**Comment by BobRay** [comment]
bobray submitted:

Zip enabled
Extension Version $Id: php_zip.c,v 1.1.2.43 2008/01/18 00:51:38 pajoye Exp $
Zip version 1.8.11
Libzip version 0.8.0-compatible

**Comment by opengeek** [comment]
opengeek submitted:

I'm going to have to consider this an environment specific problem for now. If anyone can provide further evidence that this is a problem in the MODx code and not in this version of the Zip extension on Vista, we can reopen.

**Comment by opengeek** [comment]
opengeek submitted:

Looks like we have another report with the same libzip version as the original report. Re-opening to investigate further. For reference: http://modxcms.com/forums/index.php/topic,51592.0/topicseen.html

**Comment by BobRay** [comment]
bobray submitted:

No longer happening.

**Comment by opengeek** [comment]
opengeek submitted:

BobRay, I just re-opened this yesterday because of a similar issue with the version of libzip you reported. Is it no longer happening on the same environment or did you upgrade XAMPP?

**Comment by BobRay** [comment]
bobray submitted:

Jason, Nothing is different here, it just went away. When I experienced it before, I hadn't upgraded in a long time and was making a big jump in versions, so maybe that's a factor. PhpInfo() is still reporting the same libzip version.

**Comment by StevenLangbroek** [comment]
stevenlangbroek submitted:

Still experiencing it here, and it's on shared hosting so I have no options concerning upgrading. If you want to snoop around my installation please send me a message on the forums, I'll email you login-data...

**Comment by BobRay** [comment]
bobray submitted:

As a workaround when I had the problem, I changed this line (300) in core/xpdo/transport/xpdotransport.class.php: if (class_exists('ZipArchive', true) && $xpdo->loadClass('compression.xPDOZip', XPDO_CORE_PATH, true, true)) { to if (!class_exists('ZipArchive', true) && $xpdo->loadClass('compression.xPDOZip', XPDO_CORE_PATH, true, true)) { That forced the use of PclZip, which worked for me. It might be a good idea to reverse the two cases so PclZip is the default?

**Comment by BobRay** [comment]
bobray submitted:

Since the problem has gone away for me without any changes in my environment, I suspect that the problem may only strike users making a big jump in versions.

**Comment by StevenLangbroek** [comment]
stevenlangbroek submitted:

I didn't make a jump in version at all, I just moved the installation around on the same server. I checked all paths but I still get this...

**Comment by opengeek** [comment]
opengeek submitted:

Steven, if you move the install on the server, you have to run setup again in upgrade mode at the current time. There are paths specifically related to package management that get affected depending on the physical location of things.

**Comment by StevenLangbroek** [comment]
stevenlangbroek submitted:

Jason: I have (several times), I've even went into config.inc.php and all database entries that had a path of any sort and changed them all manually. After that tried running setup again (3-4 times), still no luck.

**Comment by opengeek** [comment]
opengeek submitted:

Did it not update the path field in {table_prefix}workspaces to be accurate?

**Comment by StevenLangbroek** [comment]
stevenlangbroek submitted:

Jason: Yes I did. I also ran a search through the entire database for all paths (they all end with /web/), and checked them all. And no: it did not automatically update the record in modx_workspaces properly, had to do this by hand. After the initial problems i tried removing the zip-file, the corresponding record from the table modx_transport_packes, then redownloading it and installing it form the new download, but that didn't work either. I also can't uninstall the older version, and considering that the site is due to go live in about a week I'm a little scared of manually poking around.

**Comment by opengeek** [comment]
opengeek submitted:

So it worked on this server before, but now it doesn't; is that right?

**Comment by StevenLangbroek** [comment]
stevenlangbroek submitted:

I installed TinyMCE 4.0.0-rc3 before I moved the install. I downloaded the update 4.0.1-rc1, but due to some issues I decided to move it from domain.com/dev/ to domain.com. After that was over I decided to install 4.0.1-rc1, which didn't work.

**Comment by opengeek** [comment]
opengeek submitted:

Sure sounds like a permissions problem; I'm at a loss to know what else it could be. When you moved the files could the permissions have been affected?

**Comment by StevenLangbroek** [comment]
stevenlangbroek submitted:

Well doesn't sound very logical, and I've tried to set chmod to several folder to 777. What folder should I look at? Shaun: if it wasn't I wouldn't be able to install other packages either right? Because TinyMCE is the only one I'm having trouble with...

**Comment by opengeek** [comment]
opengeek submitted:

The option to switch to PclZip is now available.

**Comment by BobRay** [comment]
bobray submitted:

IIRC, when the build fails because of the archiving, you can no longer log in to the Manager, so you'd have to set the option with PhpMyAdmin.
