### ISSUE TITLE
Disallow reserved TV names

### ISSUE THREAD

**Issue by MadeMyDay** [modxbot/migrate#10734]
mademyday created Redmine issue ID 10734

A german user had a strange bug with Ditto (Summary not working). After long discussion I looked in the manager and saw that he created TVs with names "longtitle", "id", "link" and so on. Don`t know why he did that, but I realized that this shouldn`t even be possible.

**Comment by opengeek** [comment]
opengeek submitted:

Cloned for Evolution as MODX-2034

**Comment by opengeek** [comment]
opengeek submitted:

This is implemented as a validation rule in the model now.
