### ISSUE TITLE
Form Rules should accept queries or snippets

### ISSUE THREAD

**Issue by xpix** [modxbot/migrate#10731]
xpix created Redmine issue ID 10731

HI, It would be nice if instead using values for the "Value" and "Constraint" we could run code snippets/queries. Example: Constraint Class: modCustom
Constraint Field/Value: [ &#91;UltimateParent&#93; ]
Constraint: 6 The rule would only apply if the value returned by [ &#91;UltimateParent&#93; ] is 6 Also something like this might work:
Constraint Class: modCustom
Constraint Field/Value: [ &#91;UltimateParent&#93; ]
Constraint: [ &#91;AnotherSnippet&#93; ] The rule would only apply if the value returned by [ &#91;UltimateParent&#93; ] is [ &#91;AnotherSnippet&#93; ] I'm sure you guys will come up with the best solution.

**Comment by splittingred** [comment]
splittingred submitted:

New FC UI should resolve all criteria, and we'll be adding the ability to do multiple constraints per Set later.
