### ISSUE TITLE
Quirks in File Upload on Windows XAMPP

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10730]
bobray created Redmine issue ID 10730

I selected the assets dir and uploaded a file, but the file went to the site root and I couldn't find any way to move it. Drag and drop doesn't seem to work for anything. My next try (again selecting the assets dir) got the error message: "The specified directory is not a dir." Third try at the same thing, the file appeared to upload, but never showed in the tree, even after refreshing it or clearing the cache and reloading the page. I found the "Waiting . . . " message distracting.

**Comment by splittingred** [comment]
splittingred submitted:

Seems to be Windows related.

**Comment by splittingred** [comment]
splittingred submitted:

Does this still happen with RC-3? (You'll need to try with a fresh new uploaded file.) Drag/drop doesn't work on the files tree.

**Comment by splittingred** [comment]
splittingred submitted:

Couldn't replicate on my Windows environment, so assuming environment-specific. Postponing to future release until a diagnosis can be determined.

**Comment by BobRay** [comment]
bobray submitted:

This isn't happening any more.
