### ISSUE TITLE
Duplicate and Active/Inactive Form Rules Option

### ISSUE THREAD

**Issue by xpix** [modxbot/migrate#10735]
xpix created Redmine issue ID 10735

Please add a Duplicate option for the Form Customization Rules.
Currently there are only Edit and Remove Also Active/Inactive might be a good addition as sometimes you might want to disable one and enable another one for testing purposes. Thank you

**Comment by splittingred** [comment]
splittingred submitted:

Added, along with batch options, in r6899.
