### ISSUE TITLE
When creating a new user the message box doesn't close

### ISSUE THREAD

**Issue by xpix** [modxbot/migrate#10737]
xpix created Redmine issue ID 10737

I created a new user but the loading box did not closed. See the 2 attached images, one with a js error

**Comment by splittingred** [comment]
splittingred submitted:

I can't replicate this at all - and the error seems to show you're doing something wierd with the User class...do you have any plugins or custom user extensions?

**Comment by xpix** [comment]
xpix submitted:

Try with the "Send new password by email" and "Let modx generate the password" Also, when I use the "Show password on screen" the password is shown for a few seconds than the page redirects. I thought this was fixed. I remember opening a bug. Let me know if you want it reopend Thanks

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6906
