### ISSUE TITLE
move config.inc.tpl somewhere else and create empty config.inc.tpl

### ISSUE THREAD

**Issue by eerne** [modxbot/migrate#10739]
eerne created Redmine issue ID 10739

Please move core/config/config.inc.tpl to somewhere else and create an empty core/config/config.inc.tpl
(or better a file with 1 space since some ftp clients do not handle empty files well) MODx Evolution users are somewhat used to rename the config.inc.tpl to config.inc.php. In Revolution this will lead to the "blank page on setup" issue that a few people reported. This is follow up to http://svn.modxcms.com/jira/browse/MODX-1080 Thanks a lot

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6883
