### ISSUE TITLE
Logout does not work on 'Permission denied!' error

### ISSUE THREAD

**Issue by Drei** [modxbot/migrate#1074]
drei created Redmine issue ID 1074

When login is attempted with a user with unsufficient permissions, the error 'Permission denied!' is shown.
Clicking the offered Logout link (pointing to http://<host>/connectors/security/logout.php) brings the user to an empty page. Subsequently calling http://<host>/manager immediately redirects to the above mentioned 'Permisson denied!' error page. Apparently the session is not correctly flushed on the logout function.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6081
