### ISSUE TITLE
Plugin to set $renderdir got getinputs.php and getoutputs.php

### ISSUE THREAD

**Issue by chucktrukk** [modxbot/migrate#10747]
chucktrukk created Redmine issue ID 10747

I plan on having many contexts in some installations. I would like to keep some of my custom TVs in one folder. Can there be a plugin to set the location of the of the following files for custom inputs and outputs: core/model/modx/processors/element/tv/renders/getinputs.php
core/model/modx/processors/element/tv/renders/getoutputs.php
core/model/modx/processors/element/tv/renders/getproperties.php I propose: $renderPath (in getproperties.php) and $renderdir ( in getinputs.php and getoutputs.php) are arrays a plugin event can be fired where we can filter and return a new array the above files look through each path and continues when it finds the first one

**Comment by splittingred** [comment]
splittingred submitted:

Revision: 6827
Author: splittingred
Date: 2010-05-17 15:16
Message: - MODX-1972 Plugin to set $renderdir got getinputs.php and getoutputs.php
 &#91;REBUILD/UPGRADE REQUIRED&#93; MODX-1972 Added OnTVInputRenderList, OnTVOutputRenderList, and OnTVOutputRenderPropertiesList System Events to allow you to return a path to specify where to look for custom TV files
