### ISSUE TITLE
Confusing Options in Package Management

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10742]
bobray created Redmine issue ID 10742

The uninstall/remove options in Package Manager are still very confusing. The word "remove" is ambiguous and there could easily be confusion about whether it refers to removing the package from the site, the PM grid, and/or core/packages. The remove package option in the right-click menu removes the package from the grid and from /core/packages (even without "force removal"). The remove option from the uninstall button does not remove the package from the grid or from the disk, so the phrase "completely uninstall" is potentially misleading . The fact that one is "remove" under uninstall and the other is "remove package" should be a tipoff, but I just finally noticed the difference today after using these options for a long time and I don't think it will be clear to new users at all. Many users won't notice the difference between "remove" and "remove package" (since we're in Package Management) and will not know what will happen when they select "remove." The easiest solution would be to 1. modify the message in the right-click menu to make it clear that it will uninstall the package from the site, and remove it from the grid, and the disk. and 2. Change the name of the uninstall button option to "uninstall" rather than "remove" and change the message from: "This will completely uninstall the package and any prior versions." to: "This will uninstall all versions of the package. They will remain in the grid for possible re-installation." Another, more granular, solution would be to add checkboxes under remove in the right-click menu: "uninstall from site," "remove from grid," "remove from disk." That would make it really clear what will happen and give the user more flexibility.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6875

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
