### ISSUE TITLE
Only alpha-numeric characters are allowed for a context name

### ISSUE THREAD

**Issue by chucktrukk** [modxbot/migrate#10748]
chucktrukk created Redmine issue ID 10748

Example docs shows a context named 'domain2.tld'. http://svn.modxcms.com/docs/display/revolution/Using+One+Gateway+Plugin+to+Manage+Multiple+Domains Having dots, dashes, and slashes in the context name would be helpful so contexts could be named either: domain.com domain/user domain-one The main characters needed would be - and . so a context could be a real domain or subdomain name.

**Comment by splittingred** [comment]
splittingred submitted:

Done in r6900, but only for the characters . / - as other characters will cause internal problems, and will not allow those characters or numerals in the 1st character for the context name.

**Comment by theuros** [comment]
theuros submitted:

I have a lot of problems with context .. i use context for multisite with different languages so i nammed my context
AKP-English  
AKP-Italian
...
if i want to duplicate some context and use name AKP-xxx i can't do it ..but is possible if i use name without "-".
Another problem is when i tryed to switch context using a plugin .. with context names "xxx" works fine .. with names AKP-xxx doesn't work
