### ISSUE TITLE
Errors when using Package Manager

### ISSUE THREAD

**Issue by jusmeig** [modxbot/migrate#10744]
jusmeig created Redmine issue ID 10744

Hi guys, Not sure if this is the right place to post this!
Firstly I have been getting this problem with the Package System on all RC's.
When installing any Package, I get errors relating to : Could not create target directory /home/radical/domains/revolution.radical.ie/public_html/core/components I usually get a blue msg in the console telling me that the install was successful, however none of the Packages work. (Example Tiny MCE installing with the following) /\* MODx Console Output
- @date 2010-05-19 14:09:57
  _/
  Workspace environment initiated, now installing package... Grabbing package workspace... Could not create target directory /home/radical/domains/revolution.radical.ie/public_html/core/components Successfully installed package tinymce-3.2.7.0-rc2 Attempting to install package with signature: tinymce-3.2.7.0-rc2 Package found...now preparing to install. Could not create target directory /home/radical/domains/revolution.radical.ie/public_html/assets/components Could not copy /home/radical/domains/revolution.radical.ie/public_html/core/packages/tinymce-3.2.7.0-rc2/modPlugin/ed68f32553b0ca010987b74e57be7ebb/2/ to /home/radical/domains/revolution.radical.ie/public_html/core/components/tinymce Could not copy /home/radical/domains/revolution.radical.ie/public_html/core/packages/tinymce-3.2.7.0-rc2/modPlugin/ed68f32553b0ca010987b74e57be7ebb/1/ to /home/radical/domains/revolution.radical.ie/public_html/assets/components/tinymce /_ EOF */ Does not work however, even though I install it.
  Hope this is indeed a bug and helps in some way! Cheers, Justin

**Comment by splittingred** [comment]
splittingred submitted:

You need to make the core/components/ and assets/components/ directories writable. There's already a check implemented in RC-2 to ask you to do this, so closing this ticket.
