### ISSUE TITLE
Add way to output canonical URL for resources from tags

### ISSUE THREAD

**Issue by pixelchutes** [modxbot/migrate#10749]
pixelchutes created Redmine issue ID 10749

I think it would be great to have a new system setting that identifies the current Page/Resource URL without having to combine other settings/conditions to achieve it: Something like [ &#91;++page_url&#93; ] OR [ &#91;++resource_url&#93; ] to output the entire URL (minus query string) In RC-1 today, this can be accomplished using: [ &#91;++site_url&#93; ][[_id:isnot=`[ &#91;++site_start&#93; ]`:then=`[[~[ &#91;_id&#93; ]]]`]] See following post for more detail: http://modxcms.com/forums/index.php/topic,49361.msg288111.html#msg288111

**Comment by opengeek** [comment]
opengeek submitted:

I much prefer we add a simple property to the link tags: [ &#91;~12? &scheme=`full`&#93; ] would always produce canonical URLs without trickery.

**Comment by pixelchutes** [comment]
pixelchutes submitted:

I really like this suggestion. It would still allow for the desired output, while also providing enhanced functionality across the site for any Resource ID, not just the current request.

**Comment by opengeek** [comment]
opengeek submitted:

And committed.
