### ISSUE TITLE
Output Filters not working with iterated Elements

### ISSUE THREAD

**Issue by splittingred** [modxbot/migrate#10740]
splittingred created Redmine issue ID 10740

Due to caching changes, output filters are not working. To reproduce, use this as Resource content: [ &#91;!$testOutputFilterTpl? &pagetitle=`dummy1`&#93; ]
[ &#91;!$testOutputFilterTpl? &pagetitle=`dummy2`&#93; ]
[ &#91;!$testOutputFilterTpl? &pagetitle=`dummy3`&#93; ] And then this as the chunk 'testOutputFilterTpl': <li>[ &#91;+pagetitle:testOutputFilter&#93; ]</li> And then this as the snippet 'testOutputFilter': <?php
return $input.' - '.uniqid(); This will always return (or something similar): dummy1 - 4bfbf96e32401
dummy2
dummy3 Note how the last 2 calls dont show the output filter output.

**Comment by opengeek** [comment]
opengeek submitted:

This was affecting all Snippets executed using modX::runSnippet() multiple times in a single request.
