### ISSUE TITLE
Date timezone setting warning on installation

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#10751]
shamblett created Redmine issue ID 10751

I'm getting this warning on all the install pages :- Warning: strftime() &#91;function.strftime&#93; : It is not safe to rely on the system's timezone settings........... This is clattering the installation with headers being sent stopping progress etc. From PHP this is because :- Note: Since PHP 5.1.0 (when the date/time functions were rewritten), every call to a date/time function will generate a E_NOTICE if the timezone isn't valid, and/or a E_WARNING message if using the system settings or the TZ environment variable.
Instead of using this function to set the default timezone in your script, you can also use the INI setting date.timezone to set the default timezone. Screenshot with trace attached. This seems to emanate from Smarty and the modinstaller code

**Comment by shamblett** [comment]
shamblett submitted:

Screenshots, first shows Smarty in error, second modinstall

**Comment by splittingred** [comment]
splittingred submitted:

We'll add an error message, but to be honest, this is more of a server misconfiguration issue than a MODx one - you'll have all kinds of webapp errors if you don't set this in your php.ini, as PHP 5.3.0+ requires it to be set.

**Comment by shamblett** [comment]
shamblett submitted:

Ah! I misread the error, I thought it was implying we couldn't use strftime the way we were and we had to change the code, I'll look at my php.ini. An error message sounds OK for this then.

**Comment by shamblett** [comment]
shamblett submitted:

OK, updated php.ini, all fine now.

**Comment by splittingred** [comment]
splittingred submitted:

Added in r6846.
