### ISSUE TITLE
Manager cache is overriding manager_theme setting

### ISSUE THREAD

**Issue by devtrench** [modxbot/migrate#10755]
devtrench created Redmine issue ID 10755

Default manager_theme config parameter is set to 'default' by default. Changing the manager_theme at the user level, does not change the theme as expected. Seems to be a smarty cache issue. Here are the steps to recreate: 1) create another manager user (username 'manager') and change their manager_theme setting to 'simple_manager',
2) create the corresponding 'simple_manager' folders in manager/templates and manager/controllers by copying and pasting the default folders and renaming them
3) make a change in the 'simple_manager' theme that is easy to see (ex. change the manager title to 'Simple Manager' and remove the MODx logo)
4) then log into the manager with the 'manager' user. Expected Result: Manager theme would change to simple_manager theme Actual Result: Manager theme stays the same unless the /core/cache/mgr/smarty files are cleared. If they are, and the simple_manager theme is loaded, then logging out and logging back in as admin does not change the theme back to default (unless the smarty cache is cleared). Not sure if I set up the theme right since I can't find docs on it, but it seems to work except for this cache issue.

**Comment by splittingred** [comment]
splittingred submitted:

Revision: 6825
Author: splittingred
Date: 2010-05-17 12:33
Message: - MODX-1951 Manager cache is overriding manager_theme setting MODX-1951 Ensure smarty cache is cleared on site cache clearing and settings

**Comment by devtrench** [comment]
devtrench submitted:

Just wanted to comment that I tested this fix and it does appear to be resolved. Right on, now I can do some Manager Theme development
