### ISSUE TITLE
Console 'Download Output To File' button

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1075]
shamblett created Redmine issue ID 1075

The 'Download Output To File' button on the console seems to generate the file 'output.cache.php' in the directory core/cache/export/console. Also, on invocation the browser loads a blank page, meaning you have to 'back' the browser to get back to the manager, where you find the console window has vanished. This behaviour is not intuitive, log files should not be saved with php extensions and the window behaviour is odd to say the least. Suggest we just dump the contents of the console window to a file under logs, with an extension of log say, without leaving the current browser page.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6005
