### ISSUE TITLE
Save Button behaviour

### ISSUE THREAD

**Issue by aceman3000** [modxbot/migrate#10766]
aceman3000 created Redmine issue ID 10766

The save button is not fully clickable. There seems to be a padding around the clickable area, but when the mouse is in this padding, the cursor indicates that you can click (hand cursor). Also sometimes the save button is disabled and stays disabled, then i have to change a textfield, to get it enabled.
Why can´t the button be always disabled, as it was in Evo? Let the user decide if to save or not.

**Comment by aceman3000** [comment]
aceman3000 submitted:

Ehm, i ment "enabled" in the second last sentence.
I have an example for this bad behaviour. I have a TV that has an input type "Image". When i enter text in this field (without using the filemanager dialog) the save button stays disabled.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6951
