### ISSUE TITLE
Can't install in XAMPP 1.7.3a

### ISSUE THREAD

**Issue by fthieme** [modxbot/migrate#10767]
fthieme created Redmine issue ID 10767

I donwloaded the ga package, run the setup, put in my database information and pressed "Test database server connection and view collations." Error message: "Connecting to mysql server: Could not connect to the database server. Check the connection properties and try again.". I tried to find something in the log files, but I can't see a reason why that shouldn't work. I have an Evolution installation on that server running, installed just a couple of hours ago.

**Comment by splittingred** [comment]
splittingred submitted:

Can you verify that PDO is enabled in your system? Have you read: http://svn.modxcms.com/docs/display/revolution/Troubleshooting+Installation

**Comment by fthieme** [comment]
fthieme submitted:

phpinfo() says it is enabled. I have gone through php.ini and filled in the default sockets, but no change...

**Comment by splittingred** [comment]
splittingred submitted:

Duplicate of MODX-1942
