### ISSUE TITLE
When saving page (or elements like chunks) the saving dialog make a rollover and an infinite recursion is raised in log

### ISSUE THREAD

**Issue by Whisky** [modxbot/migrate#10763]
whisky created Redmine issue ID 10763

&#91;2010-05-05 18:58:06&#93; (ERROR @ /revolution/manager/index.php) Error 42S22 executing statement:
Array
(
 &#91;0&#93; => 42S22
 &#91;1&#93; => 1054
 &#91;2&#93; => Unknown column 'modManagerLog.
occurred' in 'where clause'
) &#91;2010-05-05 19:29:11&#93; (ERROR @ /home/telnowedge/public_html/revolution/core/xpdo/xpdo.class.php : 1610) PHP warning: json_encode() &#91;<a href=&#39;function.json-encode&#39;>function.json-encode</a>&#93; : recursion detected
 &#91;2010-05-05 19:29:11&#93; (ERROR @ /home/telnowedge/public_html/revolution/core/xpdo/xpdo.class.php : 1610) PHP warning: json_encode() &#91;<a href=&#39;function.json-encode&#39;>function.json-encode</a>&#93; : recursion detected which is the line : $encoded= json_encode($array); in function public function toJSON($array) {
$encoded= '';
if (is_array ($array)) {
if (!function_exists('json_encode')) {
if (@ include_once (XPDO_CORE_PATH . 'json/JSON.php')) { $json = new Services_JSON(); $encoded= $json->encode($array); }
} else { $encoded= json_encode($array); }
}
return $encoded;
}

**Comment by Whisky** [comment]
whisky submitted:

Verified probable cause around the fact that a ressource element was a container with an affected template. Removing the template, made the part looking like a folder and this problem disappear, so it may be a duplicate or a corrected bug in rc2. btw : it is not clear that the RC2 is pushed on the web site or on the svn stable. Does this mean, that you advice to pull from the trunk branch ?

**Comment by splittingred** [comment]
splittingred submitted:

To get RC-2 before it's official release, you need to pull from: http://svn.modxcms.com/svn/tattoo/tattoo/branches/2.0/
