### ISSUE TITLE
No header.tpl loaded by Smarty for 3PC's

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#10774]
shamblett created Redmine issue ID 10774

From this Forum thread :- http://modxcms.com/forums/index.php/topic,48746.msg285195.html#msg285195 , basically when the Provisioner 3PC is activated from the component menu a blank page appears, this seems to be because Smarty can't find the header.tpl located in manager/templates/default. It looks in the Smarty cache but doesn't seem to load it for some reason.

**Comment by splittingred** [comment]
splittingred submitted:

Revision: 6732
Author: splittingred
Date: 2010-04-28 15:14
Message: - MODX-1908 No header.tpl loaded by Smarty for 3PC's
Corrected logic flaw in modManagerResponse that prevented smarty templatePath from being set for CMPs

**Comment by splittingred** [comment]
splittingred submitted:

Should work as expected - MODx will now assign the template path to the Namespace path. return $modx->smarty->fetch('index.tpl') will fetch the index.tpl file in your namespace's path.

**Comment by shamblett** [comment]
shamblett submitted:

Looks OK now, ta
