### ISSUE TITLE
Tracking changes to static Files in the Manager Actions log

### ISSUE THREAD

**Issue by jrotering** [modxbot/migrate#10772]
jrotering created Redmine issue ID 10772

It would be really sweet if there were permissions for new_file, edit_file, save_file & delete_file, for static files in the Files tree, and if those actions were recorded in the Manager Actions log.

**Comment by splittingred** [comment]
splittingred submitted:

Permissions have been added as of r6828. Manager logging to come.

**Comment by splittingred** [comment]
splittingred submitted:

Manager logging added in r6829. Ticket fixed.
