### ISSUE TITLE
Improvement for adding template variables

### ISSUE THREAD

**Issue by aceman3000** [modxbot/migrate#10778]
aceman3000 created Redmine issue ID 10778

It would be nice if you could integrate the tab "Template access" into the "General information" tab, because assigning the variable to a template is a common task and often needed.
Then someone could only use keyboard navigation to add a new TV without having to grab the mouse to switch the tab.

**Comment by splittingred** [comment]
splittingred submitted:

UI design is like that for a purpose: to scale properly with large numbers of Templates/TVs.
