### ISSUE TITLE
Wording needs to be changed during installation

### ISSUE THREAD

**Issue by Defsolutions** [modxbot/migrate#10771]
defsolutions created Redmine issue ID 10771

On the last page of the installation it says click Continue to proceed - but actually the button says Next. Just a minor change in wording.

**Comment by splittingred** [comment]
splittingred submitted:

Revision: 6750
Author: splittingred
Date: 2010-05-03 11:29
Message: - MODX-1913 Wording needs to be changed during installation
Fixed incorrect wording on setup complete page
