### ISSUE TITLE
Issue with theme switch in the manager

### ISSUE THREAD

**Issue by lossendae** [modxbot/migrate#10777]
lossendae created Redmine issue ID 10777

Impossible to change default theme. 1 - If i change the theme of the manager to a custom one and try to access to the manager from another browser it gives a blank page.
Same things happen if i log out of the manager (blank landing page and impossible to go back in). 2 - The only solution is to run again the setup process (update) which reset the theme to default, which is not normal too (for an upgrade procedure) 3 - Once the theme reset is done, if i try to change the theme again, the setting is registred but the theme stay on the default one (even with browser cache reset). The setting is saved correctly in the database, and like point 1 , other browser can't access manager anymore and if i log out, same thing happen.

**Comment by splittingred** [comment]
splittingred submitted:

I had no problems copying a theme... Did you copy both the templates/default/ and controllers/default/ folders? Themes need to have their own controllers directory as well...

**Comment by lossendae** [comment]
lossendae submitted:

My mistake, i did not know about the controllers.
Next time, i'll ask on the forum before file anything in Jira. Thank you!

**Comment by splittingred** [comment]
splittingred submitted:

No problem. It's a change from Evo, mainly b/c the default controllers probably wouldn't be good for someone who wants to make a non-ExtJS theme.
