### ISSUE TITLE
problems with translate095 and nested placeholder-tags in phx

### ISSUE THREAD

**Issue by bruno** [modxbot/migrate#10776]
bruno created Redmine issue ID 10776

made a snippet and now a CMP for converting tags in files and tables.
Found following bug. inner tags are not translated in nested phx - calls for example: [+xett.row.groupeventscount:is=`0`:then=`<li class= "[+xett.row.status+]" title= "[+xett.row.room_title+]: frei" > [+xett.config.canedit:is=`1`:then=` <a class= "newicon" title= "[+xett.row.room_title+] ab [+xett.row.tsday:date_ger=`%d.%m.%Y`+] belegen" href= "[~[+xett.config.docids.maketime+]~]&newday=[+xett.row.tsday:date_ger=`%d`+]&newmonth=[+xett.row.tsday:date_mod=`month`+]&newyear=[+xett.row.tsday:date_mod=`year`+]&callID=[*id*]&callmonth=[+xett.row.tsday:date_mod=`month`+]&callyear=[+xett.row.tsday:date_mod=`year`+]&room_ID=[+xett.row.room_ID+]&room_title=[+xett.row.room_title+]" style= "display:block;height:100%;" > </a> `+] </li>`+] this mods in /core/model/modx/modparser095.class.php seems to fix this: <?php /\* \* MODx Revolution \* \* Copyright 2006-2010 by the MODx Team. \* All rights reserved. \* \* This program is free software; you can redistribute it and/or modify it under \* the terms of the GNU General Public License as published by the Free Software \* Foundation; either version 2 of the License, or (at your option) any later \* version. \* \* This program is distributed in the hope that it will be useful, but WITHOUT \* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS \* FOR A PARTICULAR PURPOSE. See the GNU General Public License for more \* details. \* \* You should have received a copy of the GNU General Public License along with \* this program; if not, write to the Free Software Foundation, Inc., 59 Temple \* Place, Suite 330, Boston, MA 02111-1307 USA _/ /_\* \* Utility class for assisting in migrating content from older MODx releases. \* \* @ package modx _/ class modTranslate095 { var $modx= null ; var $parser= null ; function modTranslate095(& $modx) { $ this ->__construct($modx); } function __construct(& $modx) { $ this ->modx= & $modx; //mod by Bruno $ this ->preTranslationSearch= array('[_','[~','[+','[!'); $ this ->preTranslationReplace= array('#trans->[_','#trans->[~','#trans->[+','#trans->[!'); $ this ->tagTranslation= array ( '[[++' => array ('[(', ')]', '++'), '[[$' => array ('{{', '}}', '$'), '[[_' => array ('#trans->[_', '_]', '*'), '[[~' => array ('#trans->[~', '~]', '~'), '[[+' => array ('#trans->[+', '+]', '+'), '[[!' => array ('#trans->[!', '!]', '!'), ); //end mod } function getParser() { if (!is_object($ this ->parser) || !($ this ->parser instanceof modParser095)) { $ this ->parser= & $ this ->modx->getService('parser095', 'modParser095'); } return $ this ->parser; } function translateSite($save= false , $classes= null , $files= array (), $toFile= false ) { $parser = $ this ->getParser(); //mod by Bruno $parser->tagTranslation = $ this ->tagTranslation; //end mod if ($classes === null ) { $classes= array ( 'modResource' => array ('content', 'pagetitle', 'longtitle', 'description', 'menutitle', 'introtext'), 'modTemplate' => array ('content'), 'modChunk' => array ('snippet'), 'modSnippet' => array ('snippet'), 'modPlugin' => array ('plugincode'), 'modTemplateVar' => array ('default_text'), 'modTemplateVarResource' => array ('value'), 'modSystemSetting' => array ('value') ); } ob_start(); echo "Processing classes: " . print_r($classes, true ) . "\n\n\n" ; foreach ($classes as $className => $fields) { $resources= $ this ->modx->getCollection($className); if ($resources) { foreach ($resources as $resource) { foreach ($fields as $field) { if ($content= $resource->get($field)) { echo "[BEGIN TRANSLATING FIELD] {$field}\n" ; //mod by Bruno $content = str_replace($ this ->preTranslationSearch, $ this ->preTranslationReplace, $content); //end mod while ($parser->translate($content, array(), true )) { $resource->set($field, $content); } echo "[END TRANSLATING FIELD] {$field}\n\n" ; } } if ($save) { $resource->save(); } } } } if (!empty ($files)) { echo $ this ->translateFiles($save, $files); } $log= ob_get_contents(); ob_end_clean(); if ($toFile) { $cacheManager= $ this ->modx->getCacheManager(); $cacheManager->writeFile($toFile, $log); } else { echo $log; } } function translateFiles($save= false , $files= array()) { $output= ''; if (is_array($files) && !empty ($files)) { $parser= $ this ->getParser(); //mod by Bruno $parser->tagTranslation=$ this ->tagTranslation; //end mod $cacheManager= $ this ->modx->getCacheManager(); $output.= "Processing files: " . print_r($files, true ) . "\n\n\n" ; ob_start(); foreach ($files as $file) { if (file_exists($file)) { echo "[BEGIN TRANSLATING FILE] {$file}\n" ; $content= file_get_contents($file); if ($content !== false ) { //mod by Bruno $content=str_replace($ this ->preTranslationSearch,$ this ->preTranslationReplace,$content); //end mod while ($parser->translate($content, array(), true )) {} if ($save) $cacheManager->writeFile($file, $content); } echo "[END TRANSLATING FILE] {$file}\n" ; } } $output.= ob_get_contents(); ob_end_clean(); } return $output; } }

**Comment by mkschell** [comment]
netprophet submitted:

Note: Bruno's code must mod /core/model/modx/modtranslate095.class.php, not modparser095.php as referenced above.

**Comment by splittingred** [comment]
splittingred submitted:

Can't accept this mod without a CLA: http://modxcms.com/develop/contribute/cla.html Bruno, can you fill one out and send it in?

**Comment by bruno** [comment]
bruno submitted:

Bruno, can you fill one out and send it in? done

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6948

**Comment by bruno** [comment]
bruno submitted:

thanks for fixing that. Sorry for duplicating that issue per accident.
seems you have copied this code to modparser095.php. I wrote the wrong filename above.
It was for modtranslate095.class.php as Mike Shell commented. thanks!

**Comment by bruno** [comment]
bruno submitted:

thanks for fixing that. Sorry for duplicating that issue per accident.
seems you have copied this code to modparser095.php. I wrote the wrong filename above.
It was for modtranslate095.class.php as Mike Shell commented. thanks!

**Comment by splittingred** [comment]
splittingred submitted:

Ack. Ok, fixed.
