### ISSUE TITLE
changing a category's parent

### ISSUE THREAD

**Issue by jrotering** [modxbot/migrate#10773]
jrotering created Redmine issue ID 10773

Currently when you create a new category you can choose an existing category to be its parent category - but that is the only point where you can ever (through Manager) set or edit the category hierarchy. It would be ideal if you could change a category's parent category both via an "edit category" form and through the drag-drop interface.

**Comment by splittingred** [comment]
splittingred submitted:

Revision: 6739
Author: splittingred
Date: 2010-04-29 16:45
Message: - MODX-1911 changing a category's parent
Allow for drag/drop reorganizing of categories in the Element tree.

**Comment by splittingred** [comment]
splittingred submitted:

No need to add another form; drag/drop should be sufficient.
