### ISSUE TITLE
Missing resource folders

### ISSUE THREAD

**Issue by aceman3000** [modxbot/migrate#10785]
aceman3000 created Redmine issue ID 10785

the folders images, media, flash and files are missing in the assets folder. Also the setting rb_base_dir is empty on a fresh installation.

**Comment by splittingred** [comment]
splittingred submitted:

This is expected. assets/ does not come with the core install. Those directories, also, are deprecated and do not apply in Revo - they are Evo legacy and no longer apply. You can configure filemanager_path to go to whatever dir you want now.
