### ISSUE TITLE
Too much refreshes on save action

### ISSUE THREAD

**Issue by aceman3000** [modxbot/migrate#10786]
aceman3000 created Redmine issue ID 10786

There are too much refreshes when i try to save.
First the resources tree refreshes and slides out.
Next the whole page refreshes and the resources tree slides out again.
Why does the whole page need to be refreshed?

**Comment by aceman3000** [comment]
aceman3000 submitted:

This only happens when i add a new document. Everthing works fine when i save a template or chunk.

**Comment by splittingred** [comment]
splittingred submitted:

Because you're changing from 'create' to 'update' status. This is necessary as behavior may (and often does) change between such methods.
