### ISSUE TITLE
Sort in Template Access section by Rank(or others) is not working

### ISSUE THREAD

**Issue by xpix** [modxbot/migrate#10783]
xpix created Redmine issue ID 10783

Hi, The sort Sort Ascending and Sort Descending is not working in the Template Access section. For example I'm trying to sort the TVs by Rank so I can easily see the order in which they will appear in a document but it's not possible because the Sort Ascending and Sort Descending options are not working. Thx

**Comment by splittingred** [comment]
splittingred submitted:

Revision: 6735
Author: splittingred
Date: 2010-04-28 16:46
Message: - MODX-1892 Sort in Template Access section by Rank(or others) is not working
Various fixes to TV-Template relationship grids

**Comment by splittingred** [comment]
splittingred submitted:

Now you can sort by rank, and this will auto-filter to only rows that are actively assigned to templates. You can revert back by sorting by name.
