### ISSUE TITLE
Thumbnails are not displayed

### ISSUE THREAD

**Issue by xpix** [modxbot/migrate#10781]
xpix created Redmine issue ID 10781

Hi, Thumbnails are not displayed in the manager
This the generate html shown by firebug. <img width="90" height="90" title="riders.jpg" src="//assets/images/articles-top/riders.jpg"> Image attached

**Comment by splittingred** [comment]
splittingred submitted:

Revision: 6733
Author: splittingred
Date: 2010-04-28 15:24
Message: - MODX-1895 Thumbnails are not displayed
Added sanity check for windows systems with file names in file browser

**Comment by splittingred** [comment]
splittingred submitted:

Added a commit to strip double slashes...does it work now?

**Comment by xpix** [comment]
xpix submitted:

Works, thank you
