### ISSUE TITLE
Change the width of the left tree to fixed value

### ISSUE THREAD

**Issue by lossendae** [modxbot/migrate#10787]
lossendae created Redmine issue ID 10787

Currently, the left tree use a % value. It break with all Extjs theme (default, blue, custom...) and it's not so well managed by the MODx custom theme.
It should have a fixed width, and let the principal content adjust it's size accordingly.

**Comment by splittingred** [comment]
splittingred submitted:

Revision: 6690
Author: splittingred
Date: 2010-04-22 16:48
Message: - MODX-1887 Change the width of the left tree to fixed value
Adjusted default widths for main layout to render panels more consistently
