### ISSUE TITLE
Call to undefined function parseTpl()

### ISSUE THREAD

**Issue by codedeep** [modxbot/migrate#10798]
codedeep created Redmine issue ID 10798

Fatal error: Call to undefined function parseTpl() in /var/www/vhosts/dinlabs.com/httpdocs/core/cache/elements/modsnippet/4.include.cache.php on line 193

**Comment by splittingred** [comment]
splittingred submitted:

Reinstall getResources. Make sure core/components/ and assets/components/ is writable by your web server.
