### ISSUE TITLE
Make the tree_root_id accept comma separated values

### ISSUE THREAD

**Issue by xpix** [modxbot/migrate#10796]
xpix created Redmine issue ID 10796

Hi, It would be nice make tree_root_id accept comma separated values. Imagine having 3 sections on your website each at the different levels in a tree. home section 1 - section 101 - section 4 - section 102 section 2 - section 3 - -section 301 It would be nice to make the tree root id to accept 100,101,102 as values and only show what's inside section 101, 102 and section 301
If the sections are not containers show them in a tree as regular documents For this particular case section 1 - section 101 - section 4 - section 102 tree root id can be 1 and you can hide section 4 using group permissions

**Comment by xpix** [comment]
xpix submitted:

the tree root id to accept 100,101,102
should be
the tree root id to accept 100,101,301

**Comment by splittingred** [comment]
splittingred submitted:

Revision: 6682
Author: splittingred
Date: 2010-04-19 17:31
Message: - MODX-1868 Make the tree_root_id accept comma separated values
The setting tree_root_id now accepts a comma-delimited list of Resource IDs to restrict by. Works across contexts as well.
