### ISSUE TITLE
Delimiter not working

### ISSUE THREAD

**Issue by xpix** [modxbot/migrate#10794]
xpix created Redmine issue ID 10794

Hi, I can't seem to make the Delimiter work I attached a screen shot of the TV. I changed the delimiter to "," but I still get "||" as an output delimiter.
Thank you

**Comment by splittingred** [comment]
splittingred submitted:

Revision: 6681
Author: splittingred
Date: 2010-04-19 17:15
Message: - MODX-1871 Delimiter not working Fixed bug with delimiter TV output render
