### ISSUE TITLE
New setting for number of elements displayed in the "Assigned Template Variable" or show all

### ISSUE THREAD

**Issue by xpix** [modxbot/migrate#10791]
xpix created Redmine issue ID 10791

There should be an option to show all the TVs on one page in the Assigned Template Variable, Reason: When you go on 2 pages(more than 20 TVs for 1 template) it is hard to edit the Rank. I think it should show all the TVs by default so you can properly rank them

**Comment by splittingred** [comment]
splittingred submitted:

On a site with 200+ TVs showing all would not scale well at all. A setting is an idea, however, it's definitely not a 'major' issue - so setting to Trivial.

**Comment by xpix** [comment]
xpix submitted:

I agree, this one can be closed as I think the sorting option will be enough. The problem is that it's not working properly. I already opened a new issue
 http://svn.modxcms.com/jira/browse/MODX-1892
