### ISSUE TITLE
Activate Save when a TV changes

### ISSUE THREAD

**Issue by xpix** [modxbot/migrate#10799]
xpix created Redmine issue ID 10799

HI, I have a template with 2 date TVs and 2 checkbox TVs. When I modify the fields(pick a date or check a box) the Save button is not activated. I have to switch to "Create/Edit" Tab, modify one of the default fields and only then the Save button will be activated and I can save the document. Thank you

**Comment by splittingred** [comment]
splittingred submitted:

I'm definitely not able to duplicate this. Do you have an RTE installed?

**Comment by splittingred** [comment]
splittingred submitted:

Duplicate of MODX-1859 .
