### ISSUE TITLE
tree start ID(s) seeting for users

### ISSUE THREAD

**Issue by xpix** [modxbot/migrate#10797]
xpix created Redmine issue ID 10797

Please set up a "tree start ID(s)" option for users section. The field will accept a comma separated list of IDs. Probably this ca be set up in the "Login Option" Area The user will only see what is inside that Container. If the document is not a container the user will only see 1 document in the tree and the tree can be hidden.

**Comment by splittingred** [comment]
splittingred submitted:

Implemented it in SVN earlier today.

**Comment by splittingred** [comment]
splittingred submitted:

Although, it only accepts one ID number, and only does children of the ID. If you'd like other features related to this, can you file as separate tickets? Thanks!
