### ISSUE TITLE
"logged in as USERNAME" is not a valid link

### ISSUE THREAD

**Issue by xpix** [modxbot/migrate#10809]
xpix created Redmine issue ID 10809

"logged in as USERNAME" is not a valid link. When you click it it goes to the correct page but the mouse pointer does not change on hover. <a onclick="MODx.loadPage(71);" id="modx-login-user">cipa</a> should have the href property or just add cursor:pointer somewhere in the css

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6661
