### ISSUE TITLE
cultureKey setting is not using in modLexicon

### ISSUE THREAD

**Issue by Bounz** [modxbot/migrate#10803]
bounz created Redmine issue ID 10803

First. Changing system setting "cultureKey" from manager doesn't change anything in fron-end of the site.
Second. I found out that in modLexicon.class.php line 156 is:
$language = $this->modx->cultureKey;
It's using to detect language of topic to load when no language was specified (ex. 'formit:default').
But this cultureKey field of the modx object is set only once in modx.class,php line 130 to 'en':
public $cultureKey= 'en';
So, after loading settings the value of the $this->modx->cultureKey is still 'en', while value of $this->modx->config &#91;&#39;cultureKey&#39;&#93; is that, that was set in manager ('ru' in my case). Also, when I changed lexicon loading request in component from $this->modx->lexicon->load('formit:default') to $this->modx->lexicon->load('ru:formit:default') everything became right. So, translation of fron-end coundn't be perfomed.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6660
