### ISSUE TITLE
Editing a TV will not activate save button in Weblinks

### ISSUE THREAD

**Issue by opengeek** [modxbot/migrate#10802]
opengeek created Redmine issue ID 10802

Editing a TV will not activate save button in Weblinks. This may affect Symlinks or other Resource types other than modDocument as well, but I did not test the others.

**Comment by splittingred** [comment]
splittingred submitted:

Revision: 6673
Author: splittingred
Date: 2010-04-15 12:33
Message: - MODX-1859 Editing a TV will not activate save button in Weblinks
Standardized IDs on derivative resource panels to work with Form Customization, TV changes, save button enabling, 3rd party integrations, etc
