### ISSUE TITLE
Strange display issues

### ISSUE THREAD

**Issue by xpix** [modxbot/migrate#10805]
xpix created Redmine issue ID 10805

See attachment
1. Set to default for Rider Image section is not displayed correctly in firefox and safari
2. The Rider Details TV should expand under the Reload button(is it possible that the reload button messes up the layout?)
3. Rider Image should not look like a dropdown. I prefer more the an input text field that I can edit with a select button next to it.

**Comment by splittingred** [comment]
splittingred submitted:

I don't see an attachment in this ticket...?
