### ISSUE TITLE
Reload button on top of the image picker

### ISSUE THREAD

**Issue by xpix** [modxbot/migrate#10804]
xpix created Redmine issue ID 10804

The Reload button is on top of the image picker See pic

**Comment by splittingred** [comment]
splittingred submitted:

I don't see the attachment..?

**Comment by xpix** [comment]
xpix submitted:

I used that Java tool before without success. Probably I was doing something rong. See top right corner for the display issue. Thank you

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6882
