### ISSUE TITLE
modRegister read() delay in picking up messages

### ISSUE THREAD

**Issue by oori** [modxbot/migrate#10806]
oori created Redmine issue ID 10806

Reference forum thread:
 http://modxcms.com/forums/index.php/topic,47847.0.html Messages in the queue are not picked up by ->read(), only after a short delay (random 5-30 sec??) db_cache is not enabled. I have various pieces of code using modRegister (db) and this issue apears in all. modx core is also affected by it, resource->removeLock() sometimes misses reading lock messages (and therefor resources remain locked). the messages are 100% in the queue on time. running the same read() function again, after a couple of seconds (or half-minute) - and the message will be picked up and processed normally. thanks in advance.

**Comment by opengeek** [comment]
opengeek submitted:

Is it possible you are running APC, eAccelerator or some other accelerator when experiencing this? Since modFileRegister uses include on files that end in .msg.php, I imagine the accelerators would try to cache this stuff by default and that could cause some odd results, I imagine. I'm going to run some tests in this regard, but let me know if that is a possibility in your environment or not...

**Comment by oori** [comment]
oori submitted:

Thanks for your reply.
No, I am not using any accelerator.
Note - I always use modDbRegister , actually I have not tried this with modFileRegister.

**Comment by opengeek** [comment]
opengeek submitted:

https://gist.github.com/141719e9916a31b2dff7 This script works flawlessly at 100 iterations, 10 messages per iteration being written and immediately read, with absolutely no delay whatsoever. I'm afraid something else is the problem here.

**Comment by opengeek** [comment]
opengeek submitted:

Marking this resolved since I cannot reproduce this behavior.

**Comment by oori** [comment]
oori submitted:

Jason, thanks for your efforts and test.
I ran your test script and saw:
a. it runs well on two different linux hosted servers (one with revo rc1 and second with rc2)
b. it completely fails on my dev machine (windows, tested with rc1 and rc2):
1. on first run all return: Expected message count of 10 not read; actual count = 0
2. in modx_register_messages - I see messages, but never 100 as expects (around 20-60)
3. on next test-script run (with some delay), they are picked up (Expected message count of 10 not read; actual count = 30)
*. if I run the script without delay between runs - the messages are not picked up and build up in the db hundreds...) This is exactly the issue as i originally described it...
but now we know this is a platform related issue. so - the good news is that my production servers do NOT suffer from this issue.
the bad news is that this issue undoubtedly exists on my dev platform (xampp), and therefor other people might also be affected by it. Info:
OS: Windows
MySQL: 5.1.37
PHP: 5.3.0
Client API / PDO driver: mysqlnd 5.0.5-dev - 081106 - $Revision: 1.3.2.27 $
eAccelerator: Disabled Any idea on what to check next? Thanks again for your assitance.
