### ISSUE TITLE
change password popup dissapears too fast

### ISSUE THREAD

**Issue by xpix** [modxbot/migrate#10801]
xpix created Redmine issue ID 10801

Hi When changing the pass of an user( with Show the new password on screen.) the popup that shows the password disappears in 2 seconds or less. There is no time to copy the password so you have to manually set up the password. THx

**Comment by splittingred** [comment]
splittingred submitted:

Revision: 6671
Author: splittingred
Date: 2010-04-15 10:14
Message: - MODX-1860 change password popup dissapears too fast
Fixed bug where new password was being hidden too fast when changing user password by removing unnecessary message hiding Removed no longer needed formhandler.js file
