### ISSUE TITLE
changing manager folder name gives 'Could not find action file' error

### ISSUE THREAD

**Issue by mouton** [modxbot/migrate#10814]
mouton created Redmine issue ID 10814

After installation, changing manager folder name (the folder itself, then the settings $modx_manager_path & $modx_manager_url in core/config/config.inc.php) gives me 'Could not find action file' errors in the manager. Reverting back the settings to default 'manager' resolves the problem.

**Comment by splittingred** [comment]
splittingred submitted:

Did you run setup/ and upgrade after changing the folder name?

**Comment by mouton** [comment]
mouton submitted:

No I didn't try this. Will do the test tomorrow,
Thanks,

**Comment by mouton** [comment]
mouton submitted:

sorry for the delay,
After running setup wiht upgrade option evrything is working ok, thank you,
