### ISSUE TITLE
"To Default" Buttons Squished when Using RTE as a TV

### ISSUE THREAD

**Issue by mattcdavis1** [modxbot/migrate#10818]
mattcdavis1 created Redmine issue ID 10818

Here's a screenshot: <a href="http://ratiochristi.org/assets/images/squishedDefaultButton.PNG">Squished Button Screenshot</a>

**Comment by mattcdavis1** [comment]
mattcdavis1 submitted:

Screenshot

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6999
