### ISSUE TITLE
Allow drag-and-drop organizing of elements

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1081]
bobray created Redmine issue ID 1081

Drag-and-drop appears to work for elements but it is ignored and they are always organized alphabetically. It would be nice if you could drag one you are working on to the top of its section to make it easier to find. Another icon (ABC?) next to the refresh icon could put them back in alphabetical order. Until that's implemented, drag-and-drop should probably be disabled for the elements tree.

**Comment by splittingred** [comment]
splittingred submitted:

Drag/drop ordering has been disabled as of r6124. You can still drag/drop elements into categories within the element type, though.

**Comment by splittingred** [comment]
splittingred submitted:

Was implemented a bit ago; forgot about this issue.

**Comment by BobRay** [comment]
bobray submitted:

This should really be classed as "will not fix" (assuming that's the case). Drag-and-drop is disabled, but the feature request was to allow drag-and-drop organizing of elements.
