### ISSUE TITLE
Add menuitle to Quick Create Resource panel

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1083]
bobray created Redmine issue ID 1083

I almost always need this when creating a new resource. Not having it makes Quick Create much less useful, especially for prototyping a site.

**Comment by splittingred** [comment]
splittingred submitted:

Added in r6007

**Comment by BobRay** [comment]
bobray submitted:

I've cleared all caches but I'm not seeing Menu Title in either Quick Update or Quick Create for resources in r6009.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed (had to clear core/cache/smarty).
