### ISSUE TITLE
config.inc.tpl error/notice patch

### ISSUE THREAD

**Issue by feamsr00** [modxbot/migrate#10849]
feamsr00 created Redmine issue ID 10849

When using the MODx API in an non-http SAPI, the config.inc.php with emit upwards of 6 notices complaining of non existent values (such as SERVER_PORT and HTTP_HOST). A patch is attached that simply checks for the lack of these values and sets the related variables accordingly.

**Comment by feamsr00** [comment]
feamsr00 submitted:

a patch for \core\config\config.inc.tpl made against r6578

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6579
