### ISSUE TITLE
Trash system events don't set $id

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10847]
bobray created Redmine issue ID 10847

I'm pretty sure that the OnBeforeEmptyTrash and OnEmptyTrash events used to set $id, an array of the deleted resources' IDs, but in Revo, they only set $num_deleted.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6601

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
