### ISSUE TITLE
OnContextFormPrerender fires on update but not create

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10846]
bobray created Redmine issue ID 10846

Unless create calls update?

**Comment by BobRay** [comment]
bobray submitted:

Also true for OnContextFormRender

**Comment by splittingred** [comment]
splittingred submitted:

Since New Context is now done in a window...I'm not sure of OnContextFormRender is applicable anymore on Create.

**Comment by BobRay** [comment]
bobray submitted:

Good point.
