### ISSUE TITLE
Installation Script Error

### ISSUE THREAD

**Issue by MadeMyDay** [modxbot/migrate#10842]
mademyday created Redmine issue ID 10842

I get an Error at the first page of the installation: > Notice: Undefined index: HTTPS in /Users***/Sites/modx20rc1/setup/index.php on line 44 Line 44: $installBaseUrl .= ($_SERVER &#91;&#39;SERVER_PORT&#39;&#93; == 80 || isset ($_SERVER &#91;&#39;HTTPS&#39;&#93; ) || strtolower($_SERVER &#91;&#39;HTTPS&#39;&#93; ) == 'on') ? '' : ':' . $_SERVER &#91;&#39;SERVER_PORT&#39;&#93; ; Seems like this part isn`t correct because the index is not set: > strtolower($_SERVER &#91;&#39;HTTPS&#39;&#93; ) == 'on') If I delete this (no HTTPS anyway), setup begins correctly and continues without errors. If I continue with that error I get a "Headers already send"-Message on page 2.

**Comment by splittingred** [comment]
splittingred submitted:

For one, you shouldn't be running a server with E_NOTICE set to on. Secondly, this will only occur on servers that dont properly set the SERVER global var.

**Comment by splittingred** [comment]
splittingred submitted:

Temporary fix for RC-1 users: Either do steps in description of this issue OR, turn E_NOTICE off in your server environment (preferred) Reference: http://modxcms.com/forums/index.php/topic,47312.0.html

**Comment by MadeMyDay** [comment]
mademyday submitted:

Hi Shaun, this is just the standard MAMP config, I think other users will also run into this issue. So a hint here: http://svn.modxcms.com/docs/display/revolution/Fresh+Installation#FreshInstallation-MAMPonMacOSX would be helpful. Problem is, the settings of MAMP are so user friendly, there is no setting for the SERVER global vars BTW: It is not only a E_NOTICE problem, the setup breaks on the next page, if you continue with that error.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6617
