### ISSUE TITLE
Manager Action log doesn't show object for Top Menu updates.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10851]
bobray created Redmine issue ID 10851

I actually need this because I couldn't remember which Top Menu item I'd just edited.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6580. Unfortunately, Bob, menus were not storing the correct PK value, so I can't help ya there. :/

**Comment by BobRay** [comment]
bobray submitted:

Still not showing an object after deleting a Top Menu item. Not sure if this is a won't fix or not.

**Comment by splittingred** [comment]
splittingred submitted:

Nope, just an oversight. Fixed in r6602.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
