### ISSUE TITLE
Quirk in exporting a Lexicon topic

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10856]
bobray created Redmine issue ID 10856

When you export and non-core lexicon topic, the topic ("default" in this case) shows up as a number. If you select "default" from the drop-down list, the export fails with "Topic not Found." If you leave the number alone, the export is successful. The drop-down list is showing the core topics (which it shouldn't be), which allows the user to pick the wrong "default" topic. In fact, once the drop-down arrow for Topic is selected, it's impossible to save the file because there's no way to pick the correct "Default" topic.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6537

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
