### ISSUE TITLE
Fatal error: Class 'PDO' not found in *site_root*/core/model/modx/modx.class.php on line 314

### ISSUE THREAD

**Issue by hanneman** [modxbot/migrate#10859]
hanneman created Redmine issue ID 10859

After performing a fresh install of Revolution-2.0.0-beta5 the manager console works just fine, however when trying to preview the site, I get the error "Fatal error: Class 'PDO' not found in site_root /core/model/modx/modx.class.php on line 314". It doesn't seem to matter if I'm logged into the manager or not. The same server configuration is running two, separate, Revolution-2.0.0-beta4 and Revolution-2.0.0-beta1 sites just fine.

**Comment by splittingred** [comment]
splittingred submitted:

What are your client and server versions of MySQL? Are you running eAccelerator or APC?

**Comment by hanneman** [comment]
hanneman submitted:

MySQL 5.0.89 and the only optimization software on the server is Zend.

**Comment by splittingred** [comment]
splittingred submitted:

I'm pretty sure we fixed this a while back in SVN. You'll have to either a) update to latest SVN or b) wait for RC1.

**Comment by splittingred** [comment]
splittingred submitted:

Closing - this seems to be a local environment misconfiguration.
