### ISSUE TITLE
Top Menu items with no children don't show in menu

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10854]
bobray created Redmine issue ID 10854

I imagine this was done to hide the Components item when it's empty. The problem is that Top Menu items can have actions themselves now (which is really handy for common tasks when you're working on something &#8211; e.g. System Settings). Ideally, they would show if they have an action attached or have children. Second choice, show them always.

**Comment by splittingred** [comment]
splittingred submitted:

Ah, yes - the logic should be changed to accomodate menus that have an action.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6505

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
