### ISSUE TITLE
Can't assign TV to resource group

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10869]
bobray created Redmine issue ID 10869

You can assign a TV to a resource group on the Access Permissions tab of the Create/Edit TV panel and the save appears successful, but if you edit another element and come back, it's no longer assigned.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6451

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
