### ISSUE TITLE
TV Set to default not working with radio buttons (again)

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10867]
bobray created Redmine issue ID 10867

I was working for a while, but isn't now. Input Type: Radio Options
Input Option Values: red||blue||green
Output Type: Default The default value is set to blue
A Form Customization rule sets the value to green Set to Default sets it to red. If I delete the FC rule, it still sets it to red.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6449

**Comment by BobRay** [comment]
bobray submitted:

OK, I think I see what's happening here. If you set the radio option to a non-default value and save, when you come back, Set To Default sets it to the saved value rather than the default. IOW, it reverts the value to its previous setting rather than setting it to the default. Text TVs don't do this. Set to Default actually sets them to the default value.

**Comment by splittingred** [comment]
splittingred submitted:

Set to Default should only apply to 'create', ie New, actions. Update actions wont work, since they already have stored values. So what's the problem here?

**Comment by BobRay** [comment]
bobray submitted:

Well, one problem is a big honking "Set To Default" button visible when Updating a resource that does what is says, but not all the time. Actually, with text TVs, "Set to Default" acts exactly as expected (almost). If the TV has a default value, "Set to Default" sets it to that value no matter how many times it has been saved with different values. The "almost" is that "Set to Default" ignores FC rules on Update (but honors them on Create), so new TV's get the FC default value but "Set to Default" on Update gives them the default value of the TV. For radio options, "Set to Default" has a completely different behavior on Update and reverts the TV to the previously saved value. At a minimum, it should behave as it does for text TVs. All these are useful functions but no user is going to be able to guess what will happen when they click on the "Set to Default" button, which is bad, IMO. Remember that regular users don't know how this is supposed to work or how it was intended. They just see a "Set to Default" button and assume that it will always do what it says. I'd suggest we pick just one of the following: &#8211; 1. Have "Set to Default" set any TV to the value in the TV's default value field &#8211; always (that info should certainly be available) &#8211; on either Create or Update. (This is the current behavior for text TVs on Update but not on Create.) &#8211; 2. Same as 1 but honor any FC TV default value rules on both Create and Update. (This is the current behavior for TVs on Create but not Update.) &#8211; 3. Change the name of the button to "Revert" and have it use the default value (+ FC rules) on Create and the previously saved value on Update (this is the current behavior for radio options, but not for text TVs). &#8211; 4. Keep the current behavior, but remove the "Set to Default" buttons on Update. Number 2 would be my first choice &#8211; it would be great to always be able to take a TV back to the "factory default" value. Number 1 would be confusing for users since it would appear that the FC rules aren't working (that's what I thought was happening). Number 3 is also confusing (witness my confusion about the radio options) &#8211; it makes it appear like both the TV default value and the FC rules aren't working. Number 4 is the easiest to implement, but it takes away a really useful function where you need it most &#8211; after a TV (maybe containing a complex @EVAL) has gotten fubared and saved and you just want to set it back to its original default value.

**Comment by splittingred** [comment]
splittingred submitted:

Crossing fingers, #2 should be implemented as expected. My tests showed a-ok.

**Comment by BobRay** [comment]
bobray submitted:

I'm still getting this: 1. Radio Option TV with Options red||blue||green
2. Default is blue (no FC rule).
3. Save with it set to red. Set to default does but change it back to red if you alter it. It looks like it's still using the previously saved value as the default rather than the default field.

**Comment by BobRay** [comment]
bobray submitted:

Isn't it possible to just call the code that sets the TV in a new document?

**Comment by BobRay** [comment]
bobray submitted:

See last two comments.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6589. Was an issue specific to radio TVs - the code was setting the value as default rather than the default_text as default.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
