### ISSUE TITLE
Check for memory_limit fails

### ISSUE THREAD

**Issue by Stefan** [modxbot/migrate#1086]
stefan created Redmine issue ID 1086

hello, not sure if already known or not. The revo installation fails at memory_limit check modistalltest.class.php : return_bytes the substr statment for catching the last letter is not right. input is '512M' function return_bytes($val) { $val = trim($val); $num = intval(substr($val,0,strlen($val)-1)); // current $last = strtolower(substr($val,strlen($val),1)); var_dump( $last ); // string(0) "" // looks better $last = strtolower(substr($val,-1)); var_dump($last) // string(1) "m" adios, Stefan

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5978 (in branches/revolutionphp5, which will be merged to 2.0/ after finished). Thanks!
