### ISSUE TITLE
TV Set to Default buttons don't appear until you click on "Reload"

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10866]
bobray created Redmine issue ID 10866

Doesn't happen all the time. Usually happens the first time the TV tab is accessed but occasionally reappears later.

**Comment by splittingred** [comment]
splittingred submitted:

I cannot for the life of me replicate this in latest SVN. Does this still happen?

**Comment by BobRay** [comment]
bobray submitted:

Just checked. No longer happening.
