### ISSUE TITLE
Radio Option TVs not rendered properly

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10864]
bobray created Redmine issue ID 10864

This just started and doesn't happen all the time. Input Option Values: red||blue||green The word "green" is rendered on the second line (with the "g" directly under its radio button).

**Comment by splittingred** [comment]
splittingred submitted:

Confirm fixed in r6454?

**Comment by BobRay** [comment]
bobray submitted:

Now I'm getting the following for a red||blue||green radio option (even though there's plenty of room for all three on one line): . Red . Green
. Blue And another of the same further down the screen shows: . Red . Green
. Blue Does this in both FF and Chrome.

**Comment by BobRay** [comment]
bobray submitted:

Now I'm getting this consistently .Red .Green
.Blue

**Comment by BobRay** [comment]
bobray submitted:

See comment. I'm also getting this on the same TV, but with @INHERIT for a default value in FF 3.5.6 Vista: .red .green
.blue

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6588

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
