### ISSUE TITLE
Can't log in to r6438 Revo 2.0 branch

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#10874]
shamblett created Redmine issue ID 10874

Updated to revo 2.0 branch r6438, did a rebuild/upgrade, on trying to log in with existing known good accounts I'm getting :- 'That account could not be located. Check the username and re-type the password to try again.'

**Comment by shamblett** [comment]
shamblett submitted:

Running the login under debug shows that the lines :- $username = $scriptProperties &#91;&#39;username&#39;&#93; ;
$givenPassword = $scriptProperties &#91;&#39;password&#39;&#93; ; in the login.php processor do not set the username or the password, hence the failure to find the account.

**Comment by splittingred** [comment]
splittingred submitted:

Oops. Fixed in r6439.
