### ISSUE TITLE
Editing TV does not activate Save button

### ISSUE THREAD

**Issue by ebuster** [modxbot/migrate#10879]
ebuster created Redmine issue ID 10879

When editing template variable and make changes in the Name, Caption or Description fields the Save button automaticaly activate.
But this does not happen if the change of the Output Type dependent fields. For example if TV Output Type is URL, typing in the DisplayText, Title, Class, and other fields do nothing, but must activate the save button.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6440
