### ISSUE TITLE
Output filters: change isinrole to ismember

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10875]
bobray created Redmine issue ID 10875

isinrole appears to be an alias of memberof, which is misleading. The name implies that it's checking for a role rather than user group membership. It should either be a true role test or be removed/renamed, IMO. ismemberof and isingroup might be another good alias to add in addition to ismember

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6442

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
