### ISSUE TITLE
Formit, SPForm, and other packages give spurious lexicon error messages on uninstall

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10884]
bobray created Redmine issue ID 10884

These are from Formit 1.0 RC2 uninstall (remove all previous versions option): &#91;snip&#93;
Removed modLexiconEntry instance with primary key 10926
Removed modLexiconEntry instance with primary key 10927
Removed modLexiconEntry instance with primary key 10928
Removed modLexiconTopic instance with primary key 60
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.contains &#91;topic&#93; => 66 &#91;language&#93; => nl )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.email_invalid &#91;topic&#93; => 66 &#91;language&#93; => nl )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.email_invalid_domain &#91;topic&#93; => 66 &#91;language&#93; => nl )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.email_no_recipient &#91;topic&#93; => 66 &#91;language&#93; => nl )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.email_not_sent &#91;topic&#93; => 66 &#91;language&#93; => nl )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.email_tpl_nf &#91;topic&#93; => 66 &#91;language&#93; => nl )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.field_not_empty &#91;topic&#93; => 66 &#91;language&#93; => nl )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.field_required &#91;topic&#93; => 66 &#91;language&#93; => nl )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.max_length &#91;topic&#93; => 66 &#91;language&#93; => nl )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.max_value &#91;topic&#93; => 66 &#91;language&#93; => nl )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.min_length &#91;topic&#93; => 66 &#91;language&#93; => nl )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.min_value &#91;topic&#93; => 66 &#91;language&#93; => nl )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.not_number &#91;topic&#93; => 66 &#91;language&#93; => nl )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.password_dont_match &#91;topic&#93; => 66 &#91;language&#93; => nl )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.password_not_confirmed &#91;topic&#93; => 66 &#91;language&#93; => nl )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.range_invalid &#91;topic&#93; => 66 &#91;language&#93; => nl )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.range &#91;topic&#93; => 66 &#91;language&#93; => nl )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.username_taken &#91;topic&#93; => 66 &#91;language&#93; => nl )
Skipping modLexiconTopic object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => default &#91;namespace&#93; => formit )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.contains &#91;topic&#93; => 66 &#91;language&#93; => en )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.email_invalid &#91;topic&#93; => 66 &#91;language&#93; => en )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.email_invalid_domain &#91;topic&#93; => 66 &#91;language&#93; => en )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.email_no_recipient &#91;topic&#93; => 66 &#91;language&#93; => en )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.email_not_sent &#91;topic&#93; => 66 &#91;language&#93; => en )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.email_tpl_nf &#91;topic&#93; => 66 &#91;language&#93; => en )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.field_not_empty &#91;topic&#93; => 66 &#91;language&#93; => en )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.field_required &#91;topic&#93; => 66 &#91;language&#93; => en )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.max_length &#91;topic&#93; => 66 &#91;language&#93; => en )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.max_value &#91;topic&#93; => 66 &#91;language&#93; => en )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.min_length &#91;topic&#93; => 66 &#91;language&#93; => en )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.min_value &#91;topic&#93; => 66 &#91;language&#93; => en )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.not_number &#91;topic&#93; => 66 &#91;language&#93; => en )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.password_dont_match &#91;topic&#93; => 66 &#91;language&#93; => en )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.password_not_confirmed &#91;topic&#93; => 66 &#91;language&#93; => en )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.range_invalid &#91;topic&#93; => 66 &#91;language&#93; => en )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.range &#91;topic&#93; => 66 &#91;language&#93; => en )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.spam_blocked &#91;topic&#93; => 66 &#91;language&#93; => en )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.spam_marked &#91;topic&#93; => 66 &#91;language&#93; => en )
Skipping modLexiconEntry object (data object does not exist and cannot be removed): Array ( &#91;name&#93; => formit.username_taken &#91;topic&#93; => 66 &#91;language&#93; => en )
Removed modCategory instance with primary key 12
Removed modSnippet instance with primary key 38
Removing files in file resolver: C:/xampp/htdocs/revo/core/components/formit
Removed modNamespace instance with primary key formit
Package successfully uninstalled with signature: formit-1.0-rc2

**Comment by splittingred** [comment]
splittingred submitted:

Should be fixed with lexicon changes in rc-2.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
