### ISSUE TITLE
Keyboard shortcut bug

### ISSUE THREAD

**Issue by kszyniu** [modxbot/migrate#10886]
kszyniu created Redmine issue ID 10886

Using Modx Revo with polish system settings and pressing RITGHT ALT+S should input character "?" in input textfield.
Now it can't be done because RITGHT ALT+S fires "save" command, this is big issue for polish modx revo users.
I think "save" command should be fired when pressing only LEFT ALT+S only.
cheers!

**Comment by kszyniu** [comment]
kszyniu submitted:

I don't know if JIRA system put correct character - it should be this one - http://i90.twenga.com/hobby-i-rozrywka/szablon-malarski/wielka-litera-s-czcionka-tp_2524785844873575566.png instead "?"

**Comment by gadamiak** [comment]
gadamiak submitted:

The Polish language contains more characters with diactrics (eg. Za&#380;ó&#322;&#263; g&#281;&#347;l&#261; ja&#378;&#324;), which are obtained with use of AltGr key (right Alt) and corresponding Latin alphabet letter on the standard 102-key keybord ( &#378; is exception as it's obtained with x letter). All of those are potential candidates for conflicts with any shortcuts. Both AltGr+S and Ctrl+Alt+S produce a letter &#347; and trigger "save" action. This makes a choice of non-conficting shortcuts quite difficult. The possibilities might be: Use HTML way accesskey property. Use Alt combinations, which may conflict with some browsers. Use Esc, X shortcuts (press Esc , release and press X key). Make shortcuts customizable like any other system/context setting. Remove all or a part of shortcuts. It's definitely not a trivial issue as it makes authoring content in Polish painful and prone to errors.

**Comment by splittingred** [comment]
splittingred submitted:

Wait a minute here; the hotkey in question is not ALT+S; Revo does not in any way override that key combination. Revolution overrides the following: CTRL+ALT+S - For saving
CTRL+ALT+H - For hide/show left tree
CTRL+ALT+N - Quick Create Resource\ So this issue seems moot.

**Comment by gadamiak** [comment]
gadamiak submitted:

The hotkey is Ctrl+Alt+S , which is equivalent to AltGr+S . AltGr (alternate graphic) is mapped to right Alt key on the US international keyboard (which is a standard in Poland) and is distinguished from Ctrl+Alt combination by the operating system. You may check it using the "Polish programmers' layout". Applications not aware of AltGr read it as Ctrl+Alt, which it seems to be at the low level. Thus the JS script handling shortcuts reads AltGr+S as Ctrl+Alt+S.

**Comment by gadamiak** [comment]
gadamiak submitted:

Any update on this issue? Can you, please, remap Ctrl+Alt+S to Alt+S temporarily in wait for a final solution? Or use the HTML accesskey property instead? To illustrate how ugly it is to edit a document with this issue I'll give some numbers: my doc has 505 words of 3674 chars of which 18 are the letter &#347; . That means I trigger the save action every 1.5 sentence, assuming I don't do any corrections. It's really ugly and really important!

**Comment by splittingred** [comment]
splittingred submitted:

Added reference to setting 'keymap_save' to allow for overriding of save shortcut key. This setting is not in the default build (since we are on lexicon lockdown), so you'll need to add a setting with the 'keymap_save' key and the letter of the key you want to change the save action to. We'll add a descriptor and text for the setting in 2.0.1.

**Comment by gadamiak** [comment]
gadamiak submitted:

Thanks! That works OK. However, a more fine grained control would be useful. I mean having control over modifier keys too: Alt, Ctrl, Shift.
