### ISSUE TITLE
Pagination on plugin System Events table not works

### ISSUE THREAD

**Issue by ebuster** [modxbot/migrate#10880]
ebuster created Redmine issue ID 10880

When open tab System Events, on editing plugin, events table pagination state is
"Page 1 of 5, Displaying 1 - 100 of 100"
on the next page state is
"Page 2 of 5, Displaying 21 - 120 of 100"
on the next
"Page 3 of 5, Displaying 41 - 140 of 100"
on the last
"Page 4 of 5, Displaying 81 - 180 of 100" But all events always are shown.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6428
