### ISSUE TITLE
Regex in filter method of modOutputFilter class erroneously replaces pipe char '|' with space

### ISSUE THREAD

**Issue by ridgerunner** [modxbot/migrate#10889]
ridgerunner created Redmine issue ID 10889

MODx: 2.0.0-beta-5
File: core/model/modx/filters/modoutputfilter.class.php
Line: ~203 BEFORE:
$output= preg_replace("~( &#91;\n|\r|\t|\s&#93; +)~", " ", $output); AFTER:
$output= preg_replace("/\s+/", " ", $output);

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6436
