### ISSUE TITLE
Any field of modResource processes via plugin on OnDocFormSave will erase when use Quick Update

### ISSUE THREAD

**Issue by ebuster** [modxbot/migrate#10881]
ebuster created Redmine issue ID 10881

Have a plugin like this: if ($modx->event->name == 'OnDocFormSave') { $resource =& $scriptProperties['resource']; $resource->set('longtitle', str_replace('.', ':', $_POST['longtitle'])); $resource->set('link_attributes', str_replace('-', '-', $_POST['link_attributes'])); $resource->set('introtext', str_replace('-', '-', $_POST['introtext'])); /\* ... and any other field */ $resource->save(); } When normally editing document - all works fine. But when editing document via Quck Update - all processed via plugin fields are deleted.
Plugin example form here .

**Comment by splittingred** [comment]
splittingred submitted:

Definitely wont fix this one - that's up to the plugin writer to properly check to make sure those vars (such as $_POST &#91;&#39;introtext&#39;&#93; ) are set with isset() before trying to save or set them. This will become especially important as we move forward later on, with REST-based connectors (slated for 2.1-on), as partial updates to Resources - updating only certain fields - will become more and more of a common thing.
