### ISSUE TITLE
Condition to display "Clear" button on Error Log is transposed.

### ISSUE THREAD

**Issue by martinf55** [modxbot/migrate#10895]
martinf55 created Redmine issue ID 10895

In the recent update to add a specific permission for erasing the error log, the conditions for displaying the clear button are transposed:
modx.panel.error.log.js line 40 reads:
,hidden: MODx.hasEraseErrorLog ? true : false should probably read:
,hidden: MODx.hasEraseErrorLog ? false : true ?

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6404
