### ISSUE TITLE
Pagetitle not sanitized before rendering in manager tree and various other locations

### ISSUE THREAD

**Issue by opengeek** [modxbot/migrate#10893]
opengeek created Redmine issue ID 10893

The pagetitle needs to be sanitized before being rendered in the HTML of the manager interface. For instance, using this as a pagetitle: foo <a href="foo/bar">____[ &#91;!Iñtërnâtiônàlizætiøn&#93; ]</a> --- &Prime; " &ldquo;" &Ograve;--- A link is generated in the Resource tree item for the Resource with this pagetitle. This also occurs when displaying the pagetitle on the Resource edit panel, and may be occurring in other locations as well.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6406
