### ISSUE TITLE
CKEditor Changes in "Source" view won't update

### ISSUE THREAD

**Issue by mattcdavis1** [modxbot/migrate#10909]
mattcdavis1 created Redmine issue ID 10909

When using CKEditor as an RTE changes made in source view won't update. When you go back to regular view, the changes will still show up in the editor, but the database is not updated.

**Comment by splittingred** [comment]
splittingred submitted:

Revolution will no longer as of RC1 support multiple RTEs. We will be building an in-house one based off of ExtJS's HtmlEditor widget. Therefore, this ticket is moot.
