### ISSUE TITLE
CK Editor Resource Browser Shows Blank Screen

### ISSUE THREAD

**Issue by mattcdavis1** [modxbot/migrate#10908]
mattcdavis1 created Redmine issue ID 10908

When I click on the "Browse Server" button, I get a blank screen. The resource browser works fine in other contexts (i.e. when adding static resources).

**Comment by splittingred** [comment]
splittingred submitted:

Revolution will no longer as of RC1 support multiple RTEs. We will be building an in-house one based off of ExtJS's HtmlEditor widget. Therefore, this ticket is moot.
