### ISSUE TITLE
Remove opacity in Manager menu dropdowns

### ISSUE THREAD

**Issue by swytch** [modxbot/migrate#10927]
michaelm@swaytech.co.nz created Redmine issue ID 10927

index.css (line 614) The opacity:0.97 in the dropdown menus should probably be removed as it causes text rendering problems in a few browsers. As far as I can see, this is the only declaration. Should slightly improve responsiveness on some older browsers and slower environments.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6375
