### ISSUE TITLE
Uninstalling packages trashes lexicon

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10937]
bobray created Redmine issue ID 10937

I uninstalled SPForm, Formit, Login, Wayfinder and Ditto &#8211; don't know which one did it, but the lexicon is completely empty and the reload lexicon entries button is missing. Running setup fixed things. Note: the SPForm package was built with an up-to-date SVN version. I assume the others were too. May be related to: http://svn.modxcms.com/jira/browse/MODX-1652

**Comment by BobRay** [comment]
bobray submitted:

SPForm doesn't hurt the lexicon on uninstall. Ditto 3.0 alpha2 does.

**Comment by splittingred** [comment]
splittingred submitted:

I actually had no problems installing and uninstalling Ditto...

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6372

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.

**Comment by BobRay** [comment]
bobray submitted:

Ditto just did it to me again. Then I reinstalled and uninstalled it twice and it didn't do it.

**Comment by splittingred** [comment]
splittingred submitted:

This seems to only happen with older packages (eg, Ditto). I've tried it multiple times with FormIt, Quip, oEmbed, and others, and cant reproduce. We'll make sure and do a rebuild of Ditto for RC1 so that people dont download it and use the old package.
