### ISSUE TITLE
Field mismatch in System Actions

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10931]
bobray created Redmine issue ID 10931

When creating or editing a top menu item or subitem in System | Actions, the first field is captioned "Lexicon Key" when creating a new action, but "Text" for updating an action. They should match (assuming that both are used as lexicon keys). Lexicon Key seems the more accurate caption. "Lexicon Key (Caption)" might make sense.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6397

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
