### ISSUE TITLE
"Create Action Here" always puts new menu item at the top level in System | Actions

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10933]
bobray created Redmine issue ID 10933

The new item should go below the item you right-clicked on but it's created as a Top Menu item instead. It can then be dragged to make it a subitem.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6355

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed (though I still think it would be nice if you could right-click on the Top Menu folder).
