### ISSUE TITLE
Add an error level variable for transport packages

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1094]
bobray created Redmine issue ID 1094

Many packages are still showing red errors in the console on installation even thought they install fully. They appear to be errors in the installer rather than the packages and, if so, they should probably be cleared up. In the meantime, It would be nice to have an error level setting in the package so that developers could see all the messages during development, but hide them from users in the finished package.

**Comment by splittingred** [comment]
splittingred submitted:

Nah; we'll want a way to show low level errors as well, say if a file doesnt copy over, or a permission isnt set right. The PCLERR message is a known bug, and we'll fix that before rc1.
