### ISSUE TITLE
Editor without access_permissions cannot save resource

### ISSUE THREAD

**Issue by martinf55** [modxbot/migrate#10949]
martinf55 created Redmine issue ID 10949

Editors without access_permissions cannot save resources due to a 'g is undefined' javascript error in modx.panel.resource.js beforeSubmit(), which expects modx-grid-resource-security to be present (at line 451). But modx-grid-resource-security isn't rendered if the user doesn't have access_permissions.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6330
