### ISSUE TITLE
Create system settings for SMTP

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10946]
bobray created Redmine issue ID 10946

If we had a mail_use_smtp system setting and system settings for the SMTP variables so the MODx mail service would use SMTP instead of mail(), people wouldn't have to configure all the different third-party components to use SMTP (and components like Register, that don't have that option would work for people without mail() service). I've never been able to get mail() to work on localhost so it would help a lot in testing the components that involve email. mail_use_smtp
mail_smtp_auth
mail_smtp_host
mail_smtp_username
mail_smtp_password
mail_smtp_port
main_smtp_prefix

**Comment by splittingred** [comment]
splittingred submitted:

Implemented into r6342. Rebuild/upgrade required to get functionality.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed working. Thank you!!!! I must have spend 40 hours over the last year trying to implement mail() on localhost (why didn't I think of this sooner?).
