### ISSUE TITLE
Logging out doesn't unlock resources

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10947]
bobray created Redmine issue ID 10947

If you go to the Edit panel for a resource and log out, even without doing any editing or selecting any tabs, the resource is locked for other users. This happens whether you are an admin user or a low-level user.

**Comment by opengeek** [comment]
opengeek submitted:

added modUser::removeLocks() and modified modUser::endSession() to call this method

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
