### ISSUE TITLE
TV hidden with Form Customization flashes on screen

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10948]
bobray created Redmine issue ID 10948

Hidden TVs show on the screen briefly before being hidden the first time you go to the TV tab. This happens every time you edit the resource. May occur with other hidden fields?

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6356 by moving the hiding logic to PHP and optmizing the JS

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
