### ISSUE TITLE
Allow Top Menu items to have actions

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10956]
bobray created Redmine issue ID 10956

I'm not sure if this is feasible, but it would be nice to be able to create Top Menu items for frequently used actions (e.g. System Settings) that performed the action directly. At present, Top Menu items can be created with actions, but the actions don't occur when you click on them.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6345

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
