### ISSUE TITLE
Can't assign role when adding a user to a user group

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10951]
bobray created Redmine issue ID 10951

In Access Controls, User Groups tab, right-clicking on a group and selecting "Add User to Group" lets you pick a user, but not a role. The user gets the role of "member," which might not be what you want. Adding a user in "Update User Group" - "Users" tab does let you assign a role.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6332

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
