### ISSUE TITLE
Wrong right-click menu in resource group tree for new items

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10955]
bobray created Redmine issue ID 10955

If you drag items into a resource group and then immediately right-click on them to remove them, you get the full resource right-click menu (create, quick create, etc.) rather than just the "remove" option. If you reload the page, you then get the correct right-click "remove" option.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6350

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
