### ISSUE TITLE
Installation error: attempting to preserve files

### ISSUE THREAD

**Issue by fmilitao** [modxbot/migrate#10959]
unknown created Redmine issue ID 10959

Installing tinymce on revo beta 5 gives 2 errors about preserving files. (Installation finished successfully and tinymce seems to be working fine.)
I think this is because the installer is looking for an older installation of tinymce and tries to make a backup. This fails in this case because there is no older installation. Installation log: Console running...
Package found...now preparing to install.
Workspace environment initiated, now installing package...
Attempting to install package with signature: tinymce-3.2.7.0-beta3
Grabbing package workspace...
Attempting to preserve files at /var/www/localhost/htdocs/modx/assets/components/ into archive /var/www/localhost/htdocs/modx/core/packages/tinymce-3.2.7.0-beta3/modPlugin/5470ea23e7cf120d68775725f7232a72.1.preserved.zip
Error packing /var/www/localhost/htdocs/modx/assets/components/tinymce to /var/www/localhost/htdocs/modx/core/packages/tinymce-3.2.7.0-beta3/modPlugin/5470ea23e7cf120d68775725f7232a72.1.preserved.zipPCLZIP_ERR_MISSING_FILE (-4) : File '/var/www/localhost/htdocs/modx/assets/components/tinymce' does not exists
Attempting to preserve files at /var/www/localhost/htdocs/modx/core/components/ into archive /var/www/localhost/htdocs/modx/core/packages/tinymce-3.2.7.0-beta3/modPlugin/5470ea23e7cf120d68775725f7232a72.2.preserved.zip
Error packing /var/www/localhost/htdocs/modx/core/components/tinymce to /var/www/localhost/htdocs/modx/core/packages/tinymce-3.2.7.0-beta3/modPlugin/5470ea23e7cf120d68775725f7232a72.2.preserved.zipPCLZIP_ERR_MISSING_FILE (-4) : File '/var/www/localhost/htdocs/modx/core/components/tinymce' does not exists

**Comment by opengeek** [comment]
opengeek submitted:

Moved this to MODx as this was an issue with the package management in core, not with the TinyMCE package specifically.

**Comment by opengeek** [comment]
opengeek submitted:

Resolved for rc-1 release @ revision 6316
