### ISSUE TITLE
Can't change name of top menu item or subitem

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10958]
bobray created Redmine issue ID 10958

You can edit the name of a standard or custom Top menu item or submenu item in "Update Menu" under "Actions", but when you save, you get a "Menu not Found" error. The only way to change the name of an item is to delete it and recreate it.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6354

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
