### ISSUE TITLE
Build transport script fails on creating transport zip file

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#10950]
shamblett created Redmine issue ID 10950

Updating to latest 2.0 branch, r6328, XPDO r406 getting this when running the transport.core.php :- All OK until :- &#91;2010-02-08 10:13:33&#93; (INFO @ /rev20/_build/transport.core.php) Beginning to zip up transport package... &#91;2010-02-08 10:13:43&#93; (ERROR @ /rev20/_build/transport.core.php) Error packing \Program Files\xampp\htdocs\rev20/core/packages/core to \Program Files\xampp\htdocs\rev20/core/packages/core.transport.zip: Array
(
 &#91;0&#93; => Error packing core/modContext/5d0ca1cfa20fed2c5a7327093058b3a1/0/assets/ext3/resources/images/modx/window/icon-info.gif from \Program Files\xampp\htdocs\rev20/core/packages/core/modContext/5d0ca1cfa20fed2c5a7327093058b3a1/0/assets/ext3/resources/images/modx/window/icon-info.gif
 &#91;1&#93; => Error packing core/modContext/5d0ca1cfa20fed2c5a7327093058b3a1/0/assets/ext3/resources/images/modx/window/icon-question.gif from \Program Files\xampp\htdocs\rev20/core/packages/core/modContext/5d0ca1cfa20fed2c5a7327093058b3a1/0/assets/ext3/resources/images/modx/window/icon-question.gif
 &#91;2&#93; => Error packing core/modContext/5d0ca1cfa20fed2c5a7327093058b3a1/0/assets/ext3/resources/images/modx/window/icon-warning.gif from \Program Files\xampp\htdocs\rev20/core/packages/core/modContext/5d0ca1cfa20fed2c5a7327093058b3a1/0/assets/ext3/resources/images/modx/window/icon-warning.gif
 &#91;3&#93; => Error packing core/modContext/5d0ca1cfa20fed2c5a7327093058b3a1/0/assets/ext3/resources/images/modx/window/left-corners.png from \Program Files\xampp\htdocs\rev20/core/packages/core/modContext/5d0ca1cfa20fed2c5a7327093058b3a1/0/assets/ext3/resources/images/modx/window/left-corners.png
 &#91;4&#93; => Error packing core/modContext/5d0ca1cfa20fed2c5a7327093058b3a1/0/assets/ext3/resources/images/modx/window/left-right.png from \Program Files\xampp\htdocs\rev20/core/packages/core/modContext/5d0ca1cfa20fed2c5a7327093058b3a1/0/assets/ext3/resources/images/modx/window/left-right.png
 &#91;5&#93; => Error packing core/modContext/5d0ca1cfa20fed2c5a7327093058b3a1/0/assets/ext3/resources/images/modx/window/right-corners.png from \Program Files\xampp\htdocs\rev20/core/packages/core/modContext/5d0ca1cfa20fed2c5a7327093058b3a1/0/assets/ext3/resources/images/modx/window/right-corners.png
 &#91;6&#93; => Error packing core/modContext/5d0ca1cfa20fed2c5a7327093058b3a1/0/assets/ext3/resources/images/modx/window/top-bottom.png from \Program Files\xampp\htdocs\rev20/core/packages/core/modContext/5d0ca1cfa20fed2c5a7327093058b3a1/0/assets/ext3/resources/images/modx/window/top-bottom.png
 &#91;7&#93; => Error packing core/modContext/5d0ca1cfa20fed2c5a7327093058b3a1/0/assets/modext/core/modx.actionbuttons.js from \Program Files\xampp\htdocs\rev20/core/packages/core/modContext/5d0ca1cfa20fed2c5a7327093058b3a1/0/assets/modext/core/modx.actionbuttons.js
.
.
.
This continues down through events, system settings, menus etc. culminating in :- &#91;2010-02-08 10:13:43&#93; (INFO @ /rev20/_build/transport.core.php) Error creating transport zip!

**Comment by splittingred** [comment]
splittingred submitted:

Are you sure those files exist and are readable by the webserver?

**Comment by shamblett** [comment]
shamblett submitted:

Ok Shaun, The files do seem to exist and to get rid of the web server I've run this from the command line and get the same error list, OK let me try this on linux.

**Comment by shamblett** [comment]
shamblett submitted:

Ok Shaun, Linux has the same prob but gives me much more info, specifically I'm getting this :- Warning: opendir(/var/www/html/local/revorawhide/2.0/core/packages/core/modContext/7e1f731df378c2e4158d38e5635fa347/2/templates/default/images/tree/filetree/) &#91;function.opendir&#93; : failed to open dir: Too many open files in /var/www/html/local/revorawhide/2.0/core/xpdo/compression/xpdozip.class.php on line 96 Ok, so it looks as though it may be a PHP setting somewhere for open file count or something to do with opendir, I'll have look.

**Comment by shamblett** [comment]
shamblett submitted:

OK, looking at this further under a debug session has revealed that when we are about 10 levels of recursion down in function pack of the xpdozip class we suddenly fail on the call to addFile on line 104. We have had plenty of succesful add's before this, so why the sudden fail I don't know. However, going to xpdotransport class line 290, ie where we look for a ZipArchive class and negating the if statement forces us to use the PclZip class instead. This works, the core.transport.zip is created OK. So I can only conclude that ZipArchive either doesn't like lots of depth or has some other bug on addFile. This was on windows, I'll confirm the fix on linux.

**Comment by shamblett** [comment]
shamblett submitted:

OK, works on linux now, also the 'Too many open files' warnings are gone, weird.

**Comment by splittingred** [comment]
splittingred submitted:

So would you say this issue is fixed, or is there a specific bug we should look into?

**Comment by shamblett** [comment]
shamblett submitted:

As far as I can see its not a MODx prob, its something to do with the ZipArchive PHP extension in the fact that when this is selected by revo I can't build the transport package, if I force the code to use the PclZip class all is well, so I have in fact got a one liner code change at the mo on both my windows and linux boxes. I suppose it depends on what the future of the PclZip package is, if it is going to be deprecated then we can't rely on it being there, the code at the mo uses it as a fallback if the ZipArchive extension is not available, maybe we could reverse this in the code ie chose PclZip first. If not I think we can close this ticket anyway, if anybody else hits this we can point them here for a resolution. If it becomes more of a prob we can look at it again.

**Comment by shamblett** [comment]
shamblett submitted:

A link about the ZipArchive class :- http://blog.code-head.com/the-annoying-php-ziparchive-class Other people seem to have seen things like this, good job revo caught the error in the first place

**Comment by shamblett** [comment]
shamblett submitted:

An even better link :- http://jnotes.jonasfischer.net/2009/11/phps-ziparchive-class-has-problems-with-too-many-1012-files/ Seems to be a bit broken.
