### ISSUE TITLE
No way to create menu subitems

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10957]
bobray created Redmine issue ID 10957

You can create a new top menu item now, but there's no way to put anything under it. Right-clicking and selecting "place action here" either results in a generic error or saves the item in the root of the menu tree. This happens with existing items also. When you do create a new item it is not a folder and there's no way to drag anything under it.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6318

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
