### ISSUE TITLE
Change "Field" to "Name" in Form Customization Add rule dialog

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10965]
bobray created Redmine issue ID 10965

Name might be more appropriate since it can be a field, a tab, or a TV name. It's referred to as "Name" in some of the documentation and "Field" is used to refer to specific form fields in the docs.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6310

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
