### ISSUE TITLE
Form Customization: Setting TV default value doesn't work

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10964]
bobray created Redmine issue ID 10964

I can hide TVs with FC, but can't get any default value to show up. I tried text and radio option TVs.

**Comment by BobRay** [comment]
bobray submitted:

Does this require a containing panel? I tried modx-panel-resource-tv, but maybe it should be something else.

**Comment by splittingred** [comment]
splittingred submitted:

Was a bug in the JS code. Fixed in r6313. It should not need a containing panel reference.

**Comment by BobRay** [comment]
bobray submitted:

Now works for text TVs.
