### ISSUE TITLE
unauthorized resource not in cache - sent to error page. (bug in modrequest:178?)

### ISSUE THREAD

**Issue by oori** [modxbot/migrate#10967]
oori created Redmine issue ID 10967

Scenario: Source resource document with access permissions set to a resource group. when anonymous client tries to view - we expect he'll be forwarded to unauthorized page.
This works but ONLY when the source resource is in the cache.
Otherwise (just clear you cache and see) - he is sent to error page and not unauthorized. note:
a. doesn't matter if source resource is set to cacheable or not. the issue is if the document is in the cache.
b. if the source document is in the cache - everything functions correct I seem to track this issue down to here:
\core\model\modx\modrequest.class.php
Line: 178
This call: $this->modx->getObject('modResource', $criteria) returns empty. The criteria is correct, but getObject returns empty for some reason.

**Comment by oori** [comment]
oori submitted:

To be clear:
if the source page is not cacheable - the issue is persistant!
you'll ONLY get the unauthorized page if:
a. the source page is cahceable
b. it is in the cache

**Comment by oori** [comment]
oori submitted:

More testings revealed: a. The issue is 100% as i described (tested on multiple scenarios).
b. It has more negative affects, not only the unauthorized pages. redirect to requested url after login is also affected. if the source doc is in cache - all is well. if not - after login, it redirect to the "page not found" resource instead of the source document. it is clear why.. the same issue in modrequest. (line 178 return empty)

**Comment by opengeek** [comment]
opengeek submitted:

Actually, the proper behavior is to send to the error_page (which it always will now as of revision 6322) unless you have an ACL defined for the (anonymous) User Group for the Resource Group protecting the page with a single permission: load. IOW, by default, secured pages are treated as 404's (i.e. error_page) by Revolution unless you give anonymous viewers permission to see that it exists at all. Only in the case where anonymous viewers have the load permission for the Resource Group will they know that the URL exists but that they have been forbidden access to view it (i.e. unauthorized_page). Just create a policy with that single permission, load, and assign it to your Resource Group in the anonymous User Group's ACL. Then anonymous viewers will get the unauthorized_page with a 401 response header.
