### ISSUE TITLE
Manager Unusable after FC operations

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10962]
bobray created Redmine issue ID 10962

I created some Form Customization rules and then created a new resource in the root. When I select almost any subitem on the Top Menu, I get this error: Fatal error: Call to a member function get() on a non-object in C:\xampp\htdocs\revo\core\model\modx\modactiondom.class.php on line 23 I can clear the cache and preview and a few other things, but most menu selections give this error.

**Comment by BobRay** [comment]
bobray submitted:

This is on a fresh checkout of the current 2.0 SVN. The FC rules I create hide a specific TV and set a TV default value, and hide the entire Template Variable tab. The last thing I did was to create a constraint to to the rule hiding the TV tab so that it only applied to the home page: Class: modResource
Field: id
Constraint: 1

**Comment by BobRay** [comment]
bobray submitted:

Deleting the constraint in the modx_actiondom table fixed things.

**Comment by splittingred** [comment]
splittingred submitted:

Added sanity check to r6312; cant seem to duplicate your issue now.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
