### ISSUE TITLE
Editing and saving an existing Access Policy leaves you at the same edit panel

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10975]
bobray created Redmine issue ID 10975

It should return you to the Access Controls panel. You have to click on "Cancel" after saving to go back to the Access Controls panel. (Not sure if this depends on "continue editing" or not.)

**Comment by splittingred** [comment]
splittingred submitted:

Most all of the panels behave this way; the AJAX editing allows you to do multiple saves and only go back when you're ready.

**Comment by BobRay** [comment]
bobray submitted:

OK, but I'm "ready" when I click on "Save" when it comes to editing policies.
