### ISSUE TITLE
New Install unsuccessful when core/config/config.inc.php still present

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10970]
bobray created Redmine issue ID 10970

Deleted all files except build config file and core/config/config.inc.php (including all svn files).
Dropped all tables in DB.
Did a fresh checkout of 2.0 SVN.
Upgrade install is checked by default &#8211; switched it to New install (both files in place and upacked radio options were checked)..
Install went fine, but Manager login sends you back to the Manager login page. Starting over and deleting config.inc.php fixed it, but maybe a New install should overwrite the config file? One note: The modx directory had a space in the name (Vista) &#8211; renamed it before starting over. The previous install in that directory worked fine, though.

**Comment by opengeek** [comment]
opengeek submitted:

I cannot reproduce this, at least not in the most recent revisions.

**Comment by BobRay** [comment]
bobray submitted:

Assumed fixed.
