### ISSUE TITLE
Problem with add_children permission

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10973]
bobray created Redmine issue ID 10973

When users have permissions for a container document (in a Resource Group Access ACL entry) based on the resource policy but with only load, list, and add_children permissions in the mgr context, they can right-click on the container and select "Create Document Here." They get a new document form, but when they save it, they get an "Access Denied" message (briefly). The document is still saved.

**Comment by opengeek** [comment]
opengeek submitted:

This has already been resolved in RC-1

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
