### ISSUE TITLE
FC - Can't hide resource tabs

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10979]
bobray created Redmine issue ID 10979

Can't seem to hide any of the resource tabs for either create or update, e.g.: Action: core - resource/update/index.php
User Group: None (or admin)
Field: modx-panel-resource-tv
Containing Panel: modx-resource-tabs
Rule: Tab Visible
Value: 0 Tab is still visible (and usable) after manually clearing cache, flushing permissions, and clearing browser cache.

**Comment by splittingred** [comment]
splittingred submitted:

Works fine for me. Did the rules exactly as you said. Tested in all browsers. (Revo SVN)

**Comment by BobRay** [comment]
bobray submitted:

I hate when that happens.
Maybe it's time for a new checkout.

**Comment by BobRay** [comment]
bobray submitted:

Doesn't happen in fresh checkout.
