### ISSUE TITLE
Selecting "New User Group" should take you to the "General Information Tab"

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10985]
bobray created Redmine issue ID 10985

When clicking on the "New User Group" button or selecting "New user Group" by right clicking in the grid, it's confusing to end up on one of the other tabs (which can happen now) for a group that doesn't exist yet.

**Comment by BobRay** [comment]
bobray submitted:

Hmmm... Maybe not so trivial. The other tabs don't work until you give the group a name (e.g. you can't add a user on the Users tab until a name has been assigned on the General Information tab and the group has been saved).

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6295 by this: MODX-1592 Fixed bug with usergroup create by moving it to a window

**Comment by BobRay** [comment]
bobray submitted:

No longer an issue.
