### ISSUE TITLE
Creating new user group leads to new blank form on Save

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10984]
bobray created Redmine issue ID 10984

When you create a new user group, give it a name, and save it, you end up at another (blank) new user group form rather than editing the one you just created. You have to cancel and select your newly created group to add users.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6295

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
