### ISSUE TITLE
When adding a new user, you can select "none" for the role but then can't save the user

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10983]
bobray created Redmine issue ID 10983

I'm not sure whether "none" should be allowed or removed, but it shouldn't be there if you can't use it.

**Comment by splittingred** [comment]
splittingred submitted:

Must have already been fixed; I can't dupe this anymore.

**Comment by BobRay** [comment]
bobray submitted:

This doesn't happen in Security | Manager Users (there you can save a user with "none" as the role). It does happen in Security | Access Controls | User Groups tab when you right-click on a group and add a user to is (Saving with "none" gives an error).

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6453

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
