### ISSUE TITLE
Processor not found error in updating user group context grid.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10986]
bobray created Redmine issue ID 10986

In Update User Group | Context Access | Update Changing the policy (probably changing anything) in the popup and saving gives this error: Processor not found.C:/xampp/htdocs/test2/core/model/modx/processors/security/access/usergroup/context/update.php

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6294

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
