### ISSUE TITLE
Can't create new Top Menu item

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10980]
bobray created Redmine issue ID 10980

I can't find any way to create a new Top Menu item in the Top Menu tree. The "Create Menu" button will only create subitems and right-clicking on the "Top Menu" folder does nothing. Clicking on the "Create Menu" button with "Top Menu" selected either locks up the Manager or gives a "parent not found" error.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6305

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
