### ISSUE TITLE
Backslash character in admin password is handled inconsistently.

### ISSUE THREAD

**Issue by fmilitao** [modxbot/migrate#10991]
unknown created Redmine issue ID 10991

Using the web setup I created a new admin user with a randomly generated password which happened to contain a backslash. This was accepted but when I tried to log in to the newly configured system my password was rejected. It was accepted when I added a second backslash beside the first. User input not properly sanitised? I'm sorry my PHP isn't all that great or I'd offer a patch.

**Comment by splittingred** [comment]
splittingred submitted:

Added code to prevent certain invalid chars from being used in admin username/password in r6273.
