### ISSUE TITLE
Sort not working in Reports | System Info | Recent Docs tab

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10997]
bobray created Redmine issue ID 10997

The sort options are grayed-out in the drop down so there's no way to sort the grid. Ideally, left-clicking on a column heading would sort by that column in the default sort order (descending for date fields, ascending for all others) and right-clicking would let you alter the sort order.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6261

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
