### ISSUE TITLE
Setting new user password hangs the Manager

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1099]
bobray created Redmine issue ID 1099

Giving an existing user a new password leads to endless "Saving" progress bar. X Show new password on the screen
X Let me specify the password

**Comment by BobRay** [comment]
bobray submitted:

May be related to http://svn.modxcms.com/jira/browse/MODX-1300

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in related issue.

**Comment by BobRay** [comment]
bobray submitted:

Almost fixed &#8211; the password is blank in the final popup.

**Comment by BobRay** [comment]
bobray submitted:

Filed the blank password as a separate issue.
