### ISSUE TITLE
getlist.php - bug with last svn update

### ISSUE THREAD

**Issue by oori** [modxbot/migrate#10993]
oori created Redmine issue ID 10993

core/model/modx/processors/resource/resourcegroup/getlist.php you changes $sort to $mode. i am not sure where $mode is used but here's two missed spots:
the first one prevents you from setting resourge groups to resources (ajax request returns only "total", the "results" is empty because the sql query is missing the order by field)
a. (solution) LINE 40: $sort should be changed to should be $c->sortby(\* $mode *,$dir);
b. when you open a resource to edit in the manager, the ajax request still sends the "old" POST &#91;sort&#93; , this is not so important, but still... thanks

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6272
