### ISSUE TITLE
phpmailer + SMTP + php 5.3

### ISSUE THREAD

**Issue by oori** [modxbot/migrate#10995]
oori created Redmine issue ID 10995

ERROR @ .....\core\model\modx\mail\phpmailer\class.phpmailer.php : 592) Un-recoverable error 8192: Function eregi() is deprecated Suggested resolution:
LINE 592:
change: _eregi('^(.+) &#91;0-9&#93; +)$'_
to: _preg_match('/^(.+) &#91;0-9&#93; +)$/'_ (only changed eregi --> pref_match, and wrapped match in / ...... / )

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6278
