### ISSUE TITLE
Add button problem in Files Tree right-click menu

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#11008]
bobray created Redmine issue ID 11008

The Add button is active in the right-click menu for individual files and the upload button is active after you select one but the upload always fails because you can only upload to a directory. Both buttons should be inactive (or better &#8211; hidden) when right-clicking on files unless we're going to give the option to replace a file or just allow the file to be uploaded to the parent directory.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6420

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
