### ISSUE TITLE
Object not shown for deleted resources or elements in Manager Action Log

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#11006]
bobray created Redmine issue ID 11006

Objects are shown for other actions, but deleted resources are shown as () and deleted elements are blank.

**Comment by opengeek** [comment]
opengeek submitted:

Now showing "Class (ID)" for deleted objects in Manager Action log; other data can not be shown since the data is deleted and purged from the system.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed (although elements are listed by ID rather than by name, which might be better).
