### ISSUE TITLE
Site Schedule shows only upcoming publications, not unpublications

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#11000]
bobray created Redmine issue ID 11000

The toggle button doesn't seem to do anything, only upcoming pubs are shown. A published doc with an upcoming unpub date doesn't show.

**Comment by BobRay** [comment]
bobray submitted:

fixed typo

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6270

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
