### ISSUE TITLE
memory exhausted while upgrading from beta3 to beta4

### ISSUE THREAD

**Issue by relonger** [modxbot/migrate#1100]
relonger created Redmine issue ID 1100

on the last stage of installation, got the following error: Fatal error: Allowed memory size of 25165824 bytes exhausted (tried to allocate 45 bytes) in /var/www/SITENAME/core/xpdo/xpdo.class.php on line 1078

**Comment by splittingred** [comment]
splittingred submitted:

Redownload beta4 - this was addressed last night, up your memory_limit to more than 24M (recommend 64M).
