### ISSUE TITLE
The new manager layout has several incompatibilities with IE7 ( menú problems, overflow, round corners on tabs... )

### ISSUE THREAD

**Issue by maxpiepenbrink** [modxbot/migrate#11015]
mido created Redmine issue ID 11015

The new manager layout has several incompatibilities with IE7 ( menú problems, overflow, round corners on tabs... )

**Comment by splittingred** [comment]
splittingred submitted:

Please file a ticket for each incompatability. Generic, undetailed tickets will be ignored. Thanks!

**Comment by maxpiepenbrink** [comment]
mido submitted:

Attach screenshot....

**Comment by splittingred** [comment]
splittingred submitted:

Please file a ticket for each incompatability. Generic, undetailed tickets will be ignored. Thanks!
