### ISSUE TITLE
Limited Admin user can use Quick Update and can edit resources but can't Save them.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#11017]
bobray created Redmine issue ID 11017

My user seems to have all the necessary permissions and can load resources in the editor. The Save button is active but clicking it doesn't produce the progress bar and the resource isn't saved. The user can save fine in Quick Update resource. My install has been quirky on saves (the main admin doesn't have an active Save button ever until a TV value is changed), so it may be part of that problem.

**Comment by opengeek** [comment]
opengeek submitted:

Is this still an issue?
