### ISSUE TITLE
Package Browser IE8 JS errors

### ISSUE THREAD

**Issue by maxpiepenbrink** [modxbot/migrate#11011]
mido created Redmine issue ID 11011

Package management returns a lot of JS errors ( IE8 ) when I try to expand the tree to see the avalaible packages. Once I close the window, a semitransparent layer is still there.

**Comment by splittingred** [comment]
splittingred submitted:

Confirmed, but pushing to post-rc1, since for the most part, it works.

**Comment by splittingred** [comment]
splittingred submitted:

Can you confirm if this happens on Revo RC-2?

**Comment by maxpiepenbrink** [comment]
mido submitted:

IE8 results:
Windows appear a little bit down.
Templates are shown, but no content is displayed from MODX ADDONS category.
Sometimes, the area where packages list must be shown, is displayed under the tree, and not in the right.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r7033
