### ISSUE TITLE
Create New element Here shows for root elements but not those in categories

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#11010]
bobray created Redmine issue ID 11010

I'm not sure what the expected behavior is here. Right clicking on a category in the Elements Tree shows "Create New element here" (as it should). Right clicking on an element type (e.g. "chunk" or "snippet") does not (as it shouldn't). But, Right clicking on an element in a category shows no creation options at all (seems like it should show "create element here"). Right clicking on an uncategorized element shows "Create element Here" (seems like it should show "New element").

**Comment by opengeek** [comment]
opengeek submitted:

Added Create New element Here to elements within categories. Changeset 6319.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
