### ISSUE TITLE
Downloaded zip file should install into its own modx_versionnum directory, 

### ISSUE THREAD

**Issue by fmilitao** [modxbot/migrate#11016]
unknown created Redmine issue ID 11016

When unzipping the beta file, MODx files and folders are placed in the current working directory. I think it's preferrable when files are unzipped into its own directory, eg modx_versionnum. That way, when I want to remove it or move it, I only have to move one folder. So I guess either add a high level directory to the distribution, or make it explicitly clear in the instructions that users should create a new directory for modx.

**Comment by splittingred** [comment]
splittingred submitted:

Current builds are exporting to a directory with the name of the zip file, eg: modx-2.0.0-rc-1.zip -> modx-2.0.0-rc-1/ So closing this ticket.
