### ISSUE TITLE
package download problem [server-specific]

### ISSUE THREAD

**Issue by maxpiepenbrink** [modxbot/migrate#11013]
mido created Redmine issue ID 11013

Package downloads does not works in any enviroment ( tried tinymce and discuss ). I click on "download" button but nothing happens.

**Comment by splittingred** [comment]
splittingred submitted:

Make sure you have cURL or sockets available in your PHP install.

**Comment by maxpiepenbrink** [comment]
mido submitted:

Sockets and cURL are enabled....

**Comment by splittingred** [comment]
splittingred submitted:

Any relevant errors in core/cache/logs/error.log? Is your core/components/ directory created and writable? MODx should be able to create this directory, unless you've prevented it from doing so permissions-wise on your server.

**Comment by maxpiepenbrink** [comment]
mido submitted:

nothing relevant on modx error.log
The directory was not created. I created it and set permissions to 0777 but the problem persists.
I think the server has phpsuexec installed.

**Comment by splittingred** [comment]
splittingred submitted:

What's your server environment? (PHP/MySQL/apache versions) What distro of Revo did you download? Traditional or Advanced? What is the URL for the provider that shows in the Providers table?

**Comment by maxpiepenbrink** [comment]
mido submitted:

Enviroment: http://www.netfactory.es/info.php
Revo traditional
provider url: modxcms.com

**Comment by splittingred** [comment]
splittingred submitted:

The provider "name" should be modxcms.com, but the provider "service_url" should be http://rest.modxcms.com/extras/ You'll need to look at the Providers tab in Package Management to verify this. Please respond on whether or not this is correct. Secondly, turn magic_quotes_gpc off. This is probably your problem.

**Comment by maxpiepenbrink** [comment]
mido submitted:

Provider is OK.
Turning magic_quotes_gpc = off results in a fatal error:
Fatal error: Class 'PDO' not found in /home/betanf/public_html/modxRevo/core/model/modx/modx.class.php on line 314

**Comment by splittingred** [comment]
splittingred submitted:

This sounds like your PDO drivers werent compiled correctly.
