### ISSUE TITLE
Custom property sets don't show in drop-down on snippet's properties tab

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#11025]
bobray created Redmine issue ID 11025

I can't see anything but the default properties.

**Comment by splittingred** [comment]
splittingred submitted:

You must be assigning them wrong, or something; this works fine for me in SVN. If this is beta5 specifically, that's been fixed.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
