### ISSUE TITLE
Quirks in File Editing

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#11024]
bobray created Redmine issue ID 11024
1. Tree collapses on file save &#8211; makes it inconvenient to edit multiple files in deep subdirectories. 2. No save progress bar &#8211; hard to know if save occurred. 3. Can scroll way past bottom of edit window (outer scroll bar). Save button is above the top of the screen.

**Comment by splittingred** [comment]
splittingred submitted:

#1 is duplicate of MODX-1549 #2 fixed in r6254. #3 shouldn't occur anymore because of fix for #2

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed FF 3.5.6
