### ISSUE TITLE
Quirks in User Group ACL UI

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#11027]
bobray created Redmine issue ID 11027

Roles are sometimes shown with and sometimes without authority numbers. On the Role tab, the numbers never show in the grid or the drop-down. On the Context and Resource Group tabs, they usually show without the numbers when the grid is first loades, but the grid will reformat and show the numbers after a save and the numbers will persist. On the Context tab, the numbers will be truncated if the Role name is long and the number is 4 digits.

**Comment by splittingred** [comment]
splittingred submitted:

Should be fixed now.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
