### ISSUE TITLE
Incorrect Install Permission

### ISSUE THREAD

**Issue by amdbuilder** [modxbot/migrate#11030]
amdbuilder created Redmine issue ID 11030

The files extracted during/after install process are chmod 664 instead of detecting server default 644. Evolution detects (or defaults) to 644 correctly. It would be nice if the files came out 644 without the need for me to change them. The folders seam to detect the 755 default without any problem.

**Comment by opengeek** [comment]
opengeek submitted:

This should be resolved if I understand the issue properly.
