### ISSUE TITLE
manager template, JS, package management...

### ISSUE THREAD

**Issue by maxpiepenbrink** [modxbot/migrate#11034]
mido created Redmine issue ID 11034

The new manager layout has several incompatibilities with IE7 ( menú problems, overflow, round corners on tabs... )
Calendar icon ( editing/creating document ) appears repeated ( all navigators )
Package downloads does not works in any enviroment ( tried tinymce and discuss ). I click on "download" button but nothing happens.
When we choose "Edit file" from "files tab", the tree gets collapsed inseat of keeping expanded in the selected file/folder.
Package management returns a lot of JS errors ( IE8 ) when I try to expand the tree to see the avalaible packages. Once I close the window, a semitransparent layer is still there.

**Comment by splittingred** [comment]
splittingred submitted:

Please file these as separate issues, a separate issue for each problem.
