### ISSUE TITLE
Incorrect user password during setup resets all fields vs showing error

### ISSUE THREAD

**Issue by amdbuilder** [modxbot/migrate#11031]
amdbuilder created Redmine issue ID 11031

Install Revo 5 I entered mismatched passwords for the manager login. On hitting next it just shows the first DB entry fields at which point I can test through to get back to creating the manager login. Once showing the create login fields the error message shows password mismatch.

**Comment by amdbuilder** [comment]
amdbuilder submitted:

This should be trivial priority, Sorry I missed the dropdown to set that and can't find place to edit

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r7034
