### ISSUE TITLE
Create a way to hide the Resources, Elements, and Files tabs

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#11032]
bobray created Redmine issue ID 11032

Not sure if this would best be done through Form Customization or ACLs. FC would be easier for the user, IMO. It would definitely help make the Manager simpler for naive users.

**Comment by splittingred** [comment]
splittingred submitted:

Done via Access Permissions in r6293: resource_tree element_tree file_tree These are by default in the Administrator policy. You can omit them in your policies to restrict access to the respective leftside tabs.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed (very nice).
