### ISSUE TITLE
Non-core namespaces empty in Lexicon Management

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#11038]
bobray created Redmine issue ID 11038

If you go to Lex. Management and select a 3PC namespace and topic, the grid is empty. If you then go back to the core namespace, it's empty too.

**Comment by splittingred** [comment]
splittingred submitted:

Cant reproduce this at all. You haven't been installing DocManager, have you?

**Comment by BobRay** [comment]
bobray submitted:

I did just install DocManager Reinstalling the 3PCs one-by-one seems to restore their lexicon entries. Should I remove DocManager?
