### ISSUE TITLE
User needs access_permissions to edit own profile

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#11035]
bobray created Redmine issue ID 11035

User can't edit his or her own profile unless access_permissions is set to true in policy (unless I've got something else set wrong). Having access_permissions set lets the user edit the profiles and permissions of other users as well.

**Comment by splittingred** [comment]
splittingred submitted:

Limited to just save_user in r6260

**Comment by BobRay** [comment]
bobray submitted:

User has save_user, view_user, database, and change_profile permissions. 1. Gets a "denied" error box before the user form appears. 2. User form is blank.

**Comment by BobRay** [comment]
bobray submitted:

Still seeing this in a fresh checkout of r6308.
