### ISSUE TITLE
modx.class.php : line 1909  (function getUserInfo) - marked as deprecated is false

### ISSUE THREAD

**Issue by oori** [modxbot/migrate#11037]
oori created Redmine issue ID 11037

getUserInfo is used by :userinfo filter, therefor it should not be removed in 2.1
(modOutputFilter:360) i guess you know that... but i see it still marked as deprecated in the core code.

**Comment by opengeek** [comment]
opengeek submitted:

Actually, it will remain deprecated and removed in 2.1; modOutputFilter's :userinfo filter will be modified.

**Comment by oori** [comment]
oori submitted:

http://svn.modxcms.com/docs/display/revolution/Input+and+Output+Filters
Must be updated to remove the whole :userinfo example chunk, so people will not use this..
