### ISSUE TITLE
Add infrastructure to hide Top Menu items & subitems using ACLs.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#11033]
bobray created Redmine issue ID 11033

This would be handy in creating policies for low-level users so they wouldn't see options but get "Permission denied" messages when they try to use them.

**Comment by opengeek** [comment]
opengeek submitted:

You can now specify a comma-delimited list of policy permissions (from Policies applied to Context ACLs for the mgr) for each top menu item. If the user does not have the policy permission( s ) specified, the menu item will not be rendered.
