### ISSUE TITLE
Elements tree updating gives strange results after assigning a category to a snippet

### ISSUE THREAD

**Issue by fmilitao** [modxbot/migrate#11043]
unknown created Redmine issue ID 11043

First defined a new category.
Then selected an existing snipped and assigned it to the category.
Then selected a second existing snipped and assigned it to the category Elements tree now looks like:

> Snippets
> 
> > Category (2)
> > 
> > > Snippet 1 (2)
> > > Snippet 2 (3)
> > > Snippet 1 (2)
> > > Snippet 2 (3)
> > > Snippet 2 (3) Both snippets display 2 times in the Category and the second snippet is also still visible in the snippet roots. Tested with snippets, but maybe also applies while assigning categories to chunks or TV?

**Comment by Quick-Nic** [comment]
quick-nic submitted:

Screenshot of the elements tree

**Comment by Quick-Nic** [comment]
quick-nic submitted:

A refresh of the tree will provide the correct display.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6277
