### ISSUE TITLE
No Packages available in Package Manager

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#11045]
bobray created Redmine issue ID 11045

"Download Extras" takes you to the repository, but no packages show up in the right panel.

**Comment by splittingred** [comment]
splittingred submitted:

Not really a bug; no packages yet said they supported "Revolution 2.0.0-rc-1". I've updated the packages to reflect this.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
