### ISSUE TITLE
core/model/modx/processors/resource/create.php, LINE 197

### ISSUE THREAD

**Issue by oori** [modxbot/migrate#11056]
oori created Redmine issue ID 11056

core/model/modx/processors/resource/create.php
LINE 197: $tmplvar = implode('||',$featureInsert); $tmplvar is wrong, should be: "$value" I am not sure where exactly it affects the manager. I use the create.php as reference for my own processor, so - found this bug in my code and traced it back to line 197. thanks

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6171
