### ISSUE TITLE
Access Policy grid context menu Quirk

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#11050]
bobray created Redmine issue ID 11050

This is truly odd. If you duplicate the Manager Access Policy, then immediately edit the duplicate, there will usually be one permission that can't be removed. As you move down the list, right-clicking on each permission, there will be one (usually in the "delete_ " section) that shows what looks like a tiny double scroll bar instead of the delete message. This doesn't happen with duplicating the Resource policy and, looking in the DB, there's nothing at all odd about the anomalous entry (and it's not always the same one).

**Comment by pulse-xx** [comment]
pulse submitted:

Confirmed. I was easily able to reproduce this. It affects current SVN as well. For me, it seems to always be delete_plugin.

**Comment by BobRay** [comment]
bobray submitted:

It's usually delete_plugin, but I did have it once on delete_chunk.

**Comment by splittingred** [comment]
splittingred submitted:

Actually, you can just edit the Administrator policy to get this bug; try right-clicking on database_truncate. Seems to be an ExtJS issue with the context menu incorrectly calculating height and forcing scrollbars.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6219
