### ISSUE TITLE
Need to Clear Site Cache for newly downloaded packages to show up (specific to environment)

### ISSUE THREAD

**Issue by tvachon** [modxbot/migrate#11051]
tvachon created Redmine issue ID 11051

When downloading a new package, you have to clear the entire site's cache for the package to show up in the list. However, the list wil indicate the following at the bottom (while not displaying the package) Displaying 1-n of n+1

**Comment by pulse-xx** [comment]
pulse submitted:

Any more information on this issue? I cannot reproduce this under any circumstances.
