### ISSUE TITLE
Users get an empty tree

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#11055]
bobray created Redmine issue ID 11055

For the life of me, I can't create a user who can see any resources in the tree. I'm probably doing something wrong, but I've tried everything I can think of. Even if I assign the user to a user group with a role of super user (with or without any resource groups), the user can log in but can't see any resources. The user group has access to the Mgr context with the standard administrator policy and I've tried a variety of minimum roles. I've been working on this for over a week with no success and it's holding up the book.

**Comment by splittingred** [comment]
splittingred submitted:
1. I have no problems creating users who can see the tree.
2. Did you give the user a Super User role with a Policy of Administrator for both mgr and web?
3. Did you flush the sessions after doing so?

**Comment by BobRay** [comment]
bobray submitted:

Access to the Web context did it (could have sworn I had tried that). I had assumed that access to the the "Web" context would only affect access in the front end and that a super user with Mgr access would automatically have access to all contexts. A little more depth and some examples in the Security docs would sure help.
