### ISSUE TITLE
Allow space for category & template name

### ISSUE THREAD

**Issue by lossendae** [modxbot/migrate#11053]
lossendae created Redmine issue ID 11053

When we create a category or a template with the transport builder, all space in the name are removed. It's not user friendly.

**Comment by splittingred** [comment]
splittingred submitted:

"Transport Builder"? Can you be more specific as to the problem you're having? i.e., 1. What code you're using
2. Your server environment (PHP,MySQL,Apache versions)
3. What it is you're trying to do

**Comment by lossendae** [comment]
lossendae submitted:

Sorry for the unprecise report. I'm talking about a build.transport.php If i try to create a category like this: /\* create category */
$category= $modx->newObject('modCategory');
$category->set('id',1);
$category->set('category','Device Management'); The category is saved without space (DeviceManagement) The same goes for template name: $category->set('category','My company blue - technical services'); It's saved as "Mycompanyblue-technicalservices" This issue is partially adressed by using underscore but it's not really what i wanted to do. Is it possible to allow spaces for those? I've added my server environment on the description.

**Comment by splittingred** [comment]
splittingred submitted:

Oh, sure. Fixed in r6192.
