### ISSUE TITLE
TV default values issue

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#11058]
bobray created Redmine issue ID 11058

All the default TV values now work for me and "Set to Default" works. But . . . They don't work for every document (I've only tested in the Manager &#8211; not sure what's happening in the front end). I have a couple of pages where checkbox TVs are not set to the right default or have no default value and "Set to Default" doesn't work. I can't see anything different about those pages (same template, same page settings, etc.). Looking in site_tmplvar_contentvalues, I see that there is sometimes no entry for those TV/document combinations. When the TV value is set to the default, sometimes there's an entry, sometimes not. It looks like the problems may occur when there's no entry in that table. If I save the document several times with various values for the problem TVs, things seem to straighten out. Maybe I just have a corrupted install (or a cache problem--will be filing a separate issue on cache quirks), but I thought I should report this. Should there always be an entry in that table for every usable TV/document combination once the doc has been saved? That's definitely not happening for me.

**Comment by splittingred** [comment]
splittingred submitted:

Is this still working? If so, can you create a new page and test it (so you have a clean slate with the TV values).

**Comment by BobRay** [comment]
bobray submitted:

I can't seem to make this happen. Will reopen if I see it again.
