### ISSUE TITLE
Can't log into latest 2.0 branch installation

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#11054]
shamblett created Redmine issue ID 11054

After rebuild/upgrade on both my Windows and Linux boxes I can't log into the latest 2.0 branch build, r6170. After pressing the login button a small loading box appears, followed by a clear screen effect then the login page is represented in the browser. There's nothing in the revo logs or the apache error logs, the apache access log shows this for a login attempt. :- 127.0.0.1 - - &#91;07/Dec/2009:09:27:01 +0000&#93; "GET /revorawhide/2.0/manager/assets/ext3/resources/css/ext-all-notheme.css HTTP/1.1" 200 98379
127.0.0.1 - - &#91;07/Dec/2009:09:27:01 +0000&#93; "GET /revorawhide/2.0/manager/assets/ext3/resources/css/xtheme-modx.css HTTP/1.1" 200 45111
127.0.0.1 - - &#91;07/Dec/2009:09:27:01 +0000&#93; "GET /revorawhide/2.0/manager/templates/default/css/index.css HTTP/1.1" 200 40737
127.0.0.1 - - &#91;07/Dec/2009:09:27:01 +0000&#93; "GET /revorawhide/2.0/manager/templates/default/css/login.css HTTP/1.1" 200 2188
127.0.0.1 - - &#91;07/Dec/2009:09:27:01 +0000&#93; "GET /revorawhide/2.0/manager/assets/ext3/adapter/ext/ext-base.js HTTP/1.1" 200 32677
127.0.0.1 - - &#91;07/Dec/2009:09:27:01 +0000&#93; "GET /revorawhide/2.0/manager/assets/modext/core/modx.js HTTP/1.1" 200 10837
127.0.0.1 - - &#91;07/Dec/2009:09:27:01 +0000&#93; "GET /revorawhide/2.0/manager/assets/modext/core/modx.component.js HTTP/1.1" 200 11914
127.0.0.1 - - &#91;07/Dec/2009:09:27:01 +0000&#93; "GET /revorawhide/2.0/manager/assets/modext/util/utilities.js HTTP/1.1" 200 31951
127.0.0.1 - - &#91;07/Dec/2009:09:27:01 +0000&#93; "GET /revorawhide/2.0/manager/assets/modext/widgets/core/modx.panel.js HTTP/1.1" 200 10239
127.0.0.1 - - &#91;07/Dec/2009:09:27:01 +0000&#93; "GET /revorawhide/2.0/manager/assets/modext/widgets/core/modx.msg.js HTTP/1.1" 200 202
127.0.0.1 - - &#91;07/Dec/2009:09:27:01 +0000&#93; "GET /revorawhide/2.0/manager/assets/modext/widgets/core/modx.window.js HTTP/1.1" 200 4598
127.0.0.1 - - &#91;07/Dec/2009:09:27:01 +0000&#93; "GET /revorawhide/2.0/manager/assets/modext/sections/login.js HTTP/1.1" 200 3168
127.0.0.1 - - &#91;07/Dec/2009:09:27:01 +0000&#93; "GET /revorawhide/2.0/connectors/lang.js.php?topic=login HTTP/1.1" 200 15792
127.0.0.1 - - &#91;07/Dec/2009:09:27:01 +0000&#93; "GET /revorawhide/2.0/manager/assets/ext3/ext-all.js HTTP/1.1" 200 634460
127.0.0.1 - - &#91;07/Dec/2009:09:27:01 +0000&#93; "GET /revorawhide/2.0/manager/assets/ext3/resources/images/modx/qtip/tip-sprite.gif HTTP/1.1" 200 4271
127.0.0.1 - - &#91;07/Dec/2009:09:27:01 +0000&#93; "GET /revorawhide/2.0/manager/assets/ext3/resources/images/modx/qtip/tip-anchor-sprite.gif HTTP/1.1" 200 951
127.0.0.1 - - &#91;07/Dec/2009:09:27:01 +0000&#93; "GET /revorawhide/2.0/manager/assets/ext3/resources/images/modx/panel/top-bottom.gif HTTP/1.1" 200 875
127.0.0.1 - - &#91;07/Dec/2009:09:27:01 +0000&#93; "GET /revorawhide/2.0/manager/assets/ext3/resources/images/modx/form/button-bg.png HTTP/1.1" 200 135 I've tried clearing the sessions table, clearing the browser cache to no avail. If I login with an accounr that doesn't exist I get a 'That account could not be located. Check the username and re-type the password to try again.' message.

**Comment by shamblett** [comment]
shamblett submitted:

Well, just tried this in Opera 10.10 on my Centos box and I can in fact log in, looks Ok, created a site start page in the web context but I'm not seeing any context menus on resources etc. Just tried FF again, still no login. Ok, swapping back to windows, just tried IE6, no luck can't get in with this either.

**Comment by splittingred** [comment]
splittingred submitted:

A few things: 1. On the box that the user cant be located - does the user exist in modx_users?
2. Remove your session_name, session_cookie_path, and session_cookie_domain system settings.
3. Dont use IE6. Revo does not support it yet.

**Comment by shamblett** [comment]
shamblett submitted:

OK Shaun, 1. The user doesn't exist, so I was expecting the 'doesn't exist' message, which did appear.
2. Hoorah! clearing these worked, I cleared them all together so I don't know which one it was.
3. Yes, It's the only other browser I have on my windows box, just thought I'd see what it made of the world. I don't use it for anything as a rule. OK, I've got context menu's now as expected , the layout looks better I think, especially on my 2 screen box here where I can side by side this branch and the revolution branch. Don't know what the Opera prob was with the context menu's but I don't really use this either that much, are we supporting Opera as such? It seems to have a good presence on mobile devices.

**Comment by splittingred** [comment]
splittingred submitted:

No, we're not supporting Opera, since Opera's design policy is the epitome of retarded. They disable Javascript right-click events by default, unless you go into a buried setting somewhere and check to allow it. Any reputable, modern browser that supports that as a policy doesnt deserve rich application support, imo.
