### ISSUE TITLE
Quirks with TV values in Manager

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#11063]
bobray created Redmine issue ID 11063

Now that @INHERIT is working, two new quirks have shown up: Set type to: checkbox
Input option values to: red||blue||green
Default value to: red or red||Green Default value doesn't show in Mgr but Set to Default shows it. Now to reverse the behavior: Change the type of that TV to Radio Options. Now the default value shows but Set to Default blanks all choices. BTW, Clear Cache isn't clearing core/cache/mgr/smarty for me (though I cleared it manually for testing the above).

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in 6156

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
