### ISSUE TITLE
Error updating User via Manager, when modUser.id and modUserProfile.id are NOT equal.

### ISSUE THREAD

**Issue by oori** [modxbot/migrate#11066]
oori created Redmine issue ID 11066

For example:
modUser.id = 119
has modUserProfile.id = 118
(simply because one use on the way was created without a Profile, just the base class) in Manager --> I edit some param for that user --> Save
## Using Firebug I can see the issue, in the POST it calls "action=update" with "id=118" (i.e. the id of the profile and not the modUser).

groups &#91;{"usergroup":2,"name":"Members","member":119,"role":1,"rolename":"Member","menu":null}&#93;
## id 118

(notice, id=118 and in group, member=119) This situation will never happen when all users have Profile (then the id will always be the same).
## but in general - it is "legal" to have users without Profile - this shouldn't break the manager's ability to manage common-users.

Priority: LOW
It affects only people who make their own user creation code, normally these people can resolve the issue somehow....
But - in the long run, this should be corrected as it is wrong.

**Comment by oori** [comment]
oori submitted:

NOTE: this is LOW priority.
I can't seem to change the Priority in jira....

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6134
