### ISSUE TITLE
Can't save changes to access policies

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#11069]
bobray created Redmine issue ID 11069

When changing an access policy on the User Group panel, the policy is marked as dirty and the save button is active but on save, the value reverts to its previous value. The only way to change the value is to delete the entry and create a new one. This happens in both Context Access and Resource Group Access.

**Comment by splittingred** [comment]
splittingred submitted:

I'm assuming you mean editing an ACL, not an Access Policy (very different things). I really cant duplicate this at all. Tried in Safari 4.0.4, Webkit (latest), and FF 3.5.5. All worked fine.

**Comment by BobRay** [comment]
bobray submitted:

I think one of the most confusing things about Revo permissions is that I can find nothing in the Manager that is referred to or labelled as an ACL. I mean where you go when you do this: Access Controls | User Groups | Update User Group The screen you reach has the heading
User Group: groupname I suspect this is an ACL but if an ACL is an object, it's not at all evident. And I wouldn't think to look under User Groups | Update User Group to find it. I wonder if my "bug" is caused by trying to assign inappropriate APs? Perhaps only administrative APs can be assigned to mgr and only resource APs can be assigned to "web" ?? If so, there should be an error popup on save. It would make it clear what was happening and help people learn about permissions. A message with a little explanation at the top of the ACL screen (if that's what it is) couldn't hurt.

**Comment by splittingred** [comment]
splittingred submitted:

You can assign admin policies to web; but assigning a Resource policy to 'mgr' wont get you all the needed permissions. I agree this needs much more documentation; but a popup restricting wont work, either, since there's no way to tell what constitutes a "bad" Policy. We'll have to figure out a better way of presenting this.

**Comment by splittingred** [comment]
splittingred submitted:

I'm going to close this for now.
