### ISSUE TITLE
Problems with TV Set to Default

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#11065]
bobray created Redmine issue ID 11065

Set to default doesn't seem to work in a lot of common cases. As far as I can tell, it doesn't work for: Radio buttons
Multi-Select lists
Any TVs with @ bindings, including the very common @INHERIT and @INHERIT value In most of those cases Set to Default removes all values so nothing is set. For a new user, Set to Default will appear to be very unreliable and experienced users who can't remember how TV value is originally set won't know what it will do. Since Reload restores the default values if a Save hasn't occurred, IMO it might make sense to remove the Set to Default feature.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6157. If you're still getting bugs, go ahead and file tickets for each specific TV type and we'll iron those out.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
