### ISSUE TITLE
@INHERIT not working for TVs

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#11064]
bobray created Redmine issue ID 11064

I can't get @INHERIT or @INHERIT value to work properly for any kind of TV.

**Comment by splittingred** [comment]
splittingred submitted:

Works fine for me....are you setting them right?

**Comment by splittingred** [comment]
splittingred submitted:

Bah, found it. Fixed in r6146

**Comment by BobRay** [comment]
bobray submitted:

At least one interesting quirk remains: Set type to: checkbox
Input option values to: red||blue||green
Default value to: red or red||Green Default value doesn't show in Mgr but Set to Default shows it. Now to reverse the behavior: Change the type to Radio Options. Now the default value shows but Set to Default blanks all choices. BTW, Clear Cache isn't clearing core/cache/mgr/smarty (though I cleared it manually for testing the above).

**Comment by BobRay** [comment]
bobray submitted:

Closing. Will open new issue on the new problem.
