### ISSUE TITLE
Add a setting property to modxgrid.js to hide the overflow column

### ISSUE THREAD

**Issue by lossendae** [modxbot/migrate#11067]
lossendae created Redmine issue ID 11067

Add the property "scrollOffset: 0" in viewConfig settings in modx.grid.js in viewConfig:{} and view: new Ext.grid.GroupingView({}) so that the overflow column can be hidden on render. Since all grids are in autoHeight, the reserved place is not necessary.

**Comment by lossendae** [comment]
lossendae submitted:

Modifications on line 33 and 50.

**Comment by splittingred** [comment]
splittingred submitted:

Added in r6128
