### ISSUE TITLE
Add a message in the grid when there is no data to display 

### ISSUE THREAD

**Issue by lossendae** [modxbot/migrate#11062]
lossendae created Redmine issue ID 11062

Add a parameter 'emptyText' in the viewConfig to show 'no data to display' with a corresponding entry in lexicon.
Ideallly, on server response, we could grab what was serached and add it to the emptyText :'There is no data to display for ' +searched_value;

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6153
