### ISSUE TITLE
TV @Select binding returns empty rows

### ISSUE THREAD

**Issue by oori** [modxbot/migrate#11061]
oori created Redmine issue ID 11061

Tv config:
Template variable: TV1
Input option values: @SELECT name,id FROM mytableName
## Default Value: (empty)

Then, in a document --> Template variables
TV1 "structure" is there, but without any values.
i.e. say the above sql-select returns 20 rows, in tv1 I see 20 empty rows. Using firebug , I "Reload" (document-->template variables --> reload) and look at the Response., and as expected - i see this:
<option value="" selected="selected"></option>
<option value="" selected="selected"></option>
etc.... a. I tried other 'Input Type', just to be sure.. same issue.
b. all return "selected" - no clue why, but i guess it's a by-product of the first issue. info:
a. the above sql-select works as expected (directly with mysql)
b. manual input-type (i.e. Tv config:
Template variable: TV1
Input option values: @SELECT id,name FROM mytableName
## Default Value: (empty)

Then, in a document --> Template variables
TV1 "structure" is there, but without any values.
i.e. say the above sql-select returns 20 rows, in tv1 I see 20 empty rows. Using firebug , I "Reload" (document-->template variables --> reload) and look at the Response., and as expected - i see this:
<option value="" selected="selected"></option>
<option value="" selected="selected"></option>
(twenty times) INFO:
a. I tried other 'Input Type', just to be sure.. same issue.
b. all return "selected" - no clue why, but i guess it's a "by-product" of the main issue.
c. I'm running MODx Revolution 2.0.0-beta-5 rev6103, PHP 5.3, Apache Thanks!

**Comment by oori** [comment]
oori submitted:

returns rows, but empty
the above example uses checkbox as input type

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6158
