### ISSUE TITLE
Upon downloading packages or attempting to refresh the packages page, the spinner spins endlessly and never reloads.

### ISSUE THREAD

**Issue by pulse-xx** [modxbot/migrate#11073]
pulse created Redmine issue ID 11073

Upon downloading packages or attempting to refresh the packages page, the spinner spins endlessly and never reloads.
This affects revision 6102, and possibly previous revisions.

**Comment by pulse-xx** [comment]
pulse submitted:

This issue only affects beta versions of Firefox 3.6. My apologies.

**Comment by splittingred** [comment]
splittingred submitted:

Closing due to it being about an invalid browser.
