### ISSUE TITLE
Right click on icon in left menu box Elements tab does not work with Epiphany web browser

### ISSUE THREAD

**Issue by mregan** [modxbot/migrate#11077]
mregan created Redmine issue ID 11077

Right clicking on the icons in the Elements tab of the manager left menu box is not working. I just get the standard right menu - not the Modx custom menu. This function works in Evolution and previous Modx versions.

**Comment by splittingred** [comment]
splittingred submitted:

Revolution 2.0.0 will not at this time support Epiphany.
