### ISSUE TITLE
Attempting to reorganize the menus or their items via the new interface leads to menus disappearing.

### ISSUE THREAD

**Issue by pulse-xx** [modxbot/migrate#11079]
pulse created Redmine issue ID 11079

Steps to hopefully reproduce: Go to the new menu configuration interface. Attempt to move "Package Management" to Tools. This, for me, lead to the entire System menu disappearing.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6098. However, MODX-735 will still be an issue.
