### ISSUE TITLE
Problem with duplicating Access Policies

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#11071]
bobray created Redmine issue ID 11071

Related to #1437 (marked fixed). When you duplicate an Access Policy, the permissions don't show in the grid (although they are there in the DB). If you then edit the name of the policy and save, the permissions are lost. Even though the permissions are in the data field in the DB, I couldn't find any way of making them show in the grid (clearing caches, navigating away and back, etc.). This makes it pretty much impossible to create new policies.

**Comment by splittingred** [comment]
splittingred submitted:

This was already fixed; I just tested it and it works fine.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
