### ISSUE TITLE
Clicking cancel from Access Policy Edit panel takes you back to the Mgr home page

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#11070]
bobray created Redmine issue ID 11070

Clicking the Cancel button from the Edit panel for an Access Policy should take you back to the Access Policies tab of the Access Controls screen.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6129

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
