### ISSUE TITLE
Problems logging Firefox into manager on site upgraded to rev6125

### ISSUE THREAD

**Issue by martinf55** [modxbot/migrate#11072]
martinf55 created Redmine issue ID 11072

The quick fix: remove the site settings 'session_name', 'session_cookie_path' and 'session_cookie_domain' from the upgraded site. After upgrading a rev6046 site to rev6125, I discovered I couldn't log into the manager using Firefox, even though Safari was working OK.
The login process was succeeding but MODx was seeing an empty _SESSION on the subsequent request, and hence no session contexts, so modManagerRequest sees the user as not authenticated and returns the login template. Everything works fine on a clean rev6125 site, the problem was only on an upgraded site. Tracked it down to these three system settings, whose defaults were removed at rev6102:
('session_cookie_domain', 'localhost', 'textfield', 'core', 'session', '0000-00-00 00:00:00'),
('session_cookie_path', '/', 'textfield', 'core', 'session', '0000-00-00 00:00:00'),
('session_name', 'modxcmssession', 'textfield', 'core', 'session', '0000-00-00 00:00:00'), But of course they still exist in an upgraded site - removing them caused the site to work in Firefox and Safari. Before removing them they had the default values. Between any changes, did a Site->Clear cache, Security->Flush all sessions, and deleted any localhost cookies in the browser. Other observations:
re-adding the 'session_name' default caused Firefox to start working, but broke Safari.
then re-adding the 'session_cookie_domain' default caused Safari to resume working, but broke Firefox (the initial problem condition).

**Comment by splittingred** [comment]
splittingred submitted:

Just remove those 3 settings; their defaults are deprecated out of post-beta5 installs.

**Comment by wshawn** [comment]
wshawn submitted:

Running Firefox 3.5.5 on Fedora Core 12. I had to go into the database and add my domain name directly to the session_cookie_domain in the modx_system_settings table. In the future you may want to have the installer simply push the DOMAIN.TLD to this position automatically. If people are installing on a local host they could have a failure notice if only a "localhost" is found. According to http://us2.php.net/function.setcookie Firefox requires two dots to accept a cookie. The backend is correctly sending .shawnwilkerson.com once I added shawnwilkerson.com to the table. Simply clearing the values did not work, as Firefox was refusing the cookies as being malformed.
