### ISSUE TITLE
Installing local transport package removes previous version from grid

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#11089]
bobray created Redmine issue ID 11089

If you download a .zip file for package from the forums (tried Wayfinder and Breadcrumbs), installing it removes any older versions from the grid. They are still in core/packages, but Search Locally for Packages doesn't put them back. This may be by design, but it makes it difficult to revert to an earlier version.

**Comment by splittingred** [comment]
splittingred submitted:

This is by design - if you want to revert, just Uninstall -> Restore.
