### ISSUE TITLE
MYSQL Version check in Revolution 2.0 branch

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#11084]
shamblett created Redmine issue ID 11084

On the installation summary page I'm getting :- "# OK!
Could not detect MySQL server version!
MODx could not detect your MySQL server version via mysql_get_server_info(). Please manually make sure that your MySQL server version is at least 4.1.20 before proceeding." Followed by :- "Checking MySQL server version: OK! Running: 5.0.77" The first statement is misleading as we can get the server version Ok.

**Comment by shamblett** [comment]
shamblett submitted:

OK, having a quick look I think that the first error is here :- Line 70 of modinstalltest.class.php where we call mysql_get_server_info(). This either needs a mysql link parameter or it will either try and use the last one opened or open one itself with default parameters. It may be that this is failing, hence $mysqlVersion is empty, I don't think we have a last opened connection at this point if not we need to open one to do this check. The next error is just a typo, the mysql_get_client_info() call on line 101 doesn't need a link so it always works, it should say 'client version' not 'server version'. Also, should we really be doing this here, if the user has pressed the 'test connection' button on the DB page shouldn't this tes be done there, we don't want to say 'your connections OK' on one page than further one say 'but you can't use it' do we?

**Comment by splittingred** [comment]
splittingred submitted:

Added a fix to 6096, can you test?

**Comment by shamblett** [comment]
shamblett submitted:

OK Shaun, still getting this :-
#
Could not detect MySQL server version! MODx could not detect your MySQL server version via mysql_get_server_info(). Please manually make sure that your MySQL server version is at least 4.1.20 before proceeding.

# Checking MySQL server version: Failed! Haven't debugged yet but I still suspect that $mysqlVersion is empty because mysql_get_server_info() has no myswql link parameter, will verify ASAP.

**Comment by splittingred** [comment]
splittingred submitted:

Steve, I can't duplicate that. Can you tell me exactly what mysql_get_server_info(); prints out? If it is empty, it should still allow you to proceed.

**Comment by shamblett** [comment]
shamblett submitted:

OK Shaun, run this under a debugger now :- What I'm seeing is that when line 79 executes '$mysqlVersion = mysql_get_server_info();' the var $mysqlVersion remains empty, no version string is returned, so we fall into the 'if (empty($mysqlVersion)) ' clause and fail. I think its something to do with this from the PHP manual for mysql_get_server_info() :- Parameters
link_identifier
The MySQL connection. If the link identifier is not specified, the last link opened by mysql_connect() is assumed. If no such link is found, it will try to create one as if mysql_connect() was called with no arguments. If by chance no connection is found or established, an E_WARNING level warning is generated. Return Values
Returns the MySQL server version on success, or FALSE on failure. I suppose if you just happen to be testing this on a machine with an open DB connection, or one that you can log in with using default creds it will work OK.

**Comment by splittingred** [comment]
splittingred submitted:

Steve, right - it should fall into the "if (empty($mysqlVersion))" clause - but that clause doesn't return an error - just a warning. (testWarn as the class.) You should still be able to go through the install process. This is why I need you to var_dump what your mysql_get_server_info(); I've tested it with a blank return value and you can still proceed with setup (albeit you get a nice warning saying that MODx can't detect your MySQL version and you should verify it manually.)

**Comment by shamblett** [comment]
shamblett submitted:

Yes OK, I'm confusing myself here as I'm trying this on a machine where the MYSQL client version does actually fail!. On a machine where the versions are OK we get what you say above, ie this :- 'Could not detect MySQL server version! MODx could not detect your MySQL server version via mysql_get_server_info(). Please manually make sure that your MySQL server version is at least 4.1.20 before proceeding.
' but the client check passes and I am allowed to continue with the install. OK, good. I suppose the only thing here is that the server check will probably fail all the time, do we want this?

**Comment by splittingred** [comment]
splittingred submitted:

No, it shouldn't fail all the time - in fact, most servers will say it's OK and report the right version most of the time.

**Comment by shamblett** [comment]
shamblett submitted:

getting this now on r6125 of the 2.0 branch at the top of the Installation Summary page :-
Warning: mysql_get_server_info() &#91;function.mysql-get-server-info&#93; : Access denied for user 'ODBC'@'localhost' (using password: NO) in C:\Program Files\xampp\htdocs\rev20\setup\includes\modinstalltest.class.php on line 79
Call Stack Time Memory Function Location
1 0.0035 91424 {main}( ) ..\index.php:0
2 0.0501 934408 modInstallRequest->handle( ) ..\index.php:75
3 0.0641 987536 include( 'C:\Program Files\xampp\htdocs\rev20\setup\controllers\summary.php' ) ..\modinstallrequest.class.php:71
4 0.0642 988600 modInstall->test( ) ..\summary.php:13
5 0.0764 1267760 modInstallTestSvn->run( ) ..\modinstall.class.php:240
6 0.0764 1267960 modInstallTest->run( ) ..\modinstalltestsvn.class.php:10
7 0.0765 1269544 modInstallTest->_checkMySQLServerVersion( ) ..\modinstalltest.class.php:28
8 0.0765 1272096 mysql_get_server_info ( ) ..\modinstalltest.class.php:79

( ! ) Warning: mysql_get_server_info() &#91;function.mysql-get-server-info&#93; : A link to the server could not be established in C:\Program Files\xampp\htdocs\rev20\setup\includes\modinstalltest.class.php on line 79
Call Stack

# Time Memory Function Location

1 0.0035 91424 {main}( ) ..\index.php:0
2 0.0501 934408 modInstallRequest->handle( ) ..\index.php:75
3 0.0641 987536 include( 'C:\Program Files\xampp\htdocs\rev20\setup\controllers\summary.php' ) ..\modinstallrequest.class.php:71
4 0.0642 988600 modInstall->test( ) ..\summary.php:13
5 0.0764 1267760 modInstallTestSvn->run( ) ..\modinstall.class.php:240
6 0.0764 1267960 modInstallTest->run( ) ..\modinstalltestsvn.class.php:10
7 0.0765 1269544 modInstallTest->_checkMySQLServerVersion( ) ..\modinstalltest.class.php:28
8 0.0765 1272096 mysql_get_server_info ( ) Not sure where these params are coming from but this definitely won't work on any of my systems.

**Comment by lossendae** [comment]
lossendae submitted:

I've got the same error on 3 differents system. Warning: mysql_get_server_info() &#91;function.mysql-get-server-info&#93; : Access denied for user 'ODBC'@'localhost' (using password: NO) in C:\Program Files\xampp\htdocs\rev20\setup\includes\modinstalltest.class.php on line 79 The only way to get past it is to add mysql_connect statement before checking.

**Comment by splittingred** [comment]
splittingred submitted:

I've added another connect, in r6184, to assist with the check. Let me know if that works.

**Comment by shamblett** [comment]
shamblett submitted:

Yep, looks fine now.
