### ISSUE TITLE
Pressing Enter after setting filter in System Settings doesn't work

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#11088]
bobray created Redmine issue ID 11088

Clicking in the grid after setting the filter works fine. Hitting Enter after typing the filter entry reloads the grid without changing it and then clicking on "Clear Filter" actually shows you the filtered results.

**Comment by splittingred** [comment]
splittingred submitted:

I cant duplicate this. Does this still happen?

**Comment by BobRay** [comment]
bobray submitted:

No longer happening.
