### ISSUE TITLE
Cant buil transport package for revolution 2.0 branch 

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#11086]
shamblett created Redmine issue ID 11086

On updating the latest 2.0 branch( tattoo/tattoo/branches/2.0) to r5984 the transport.core.php script fails to build the transport packages, the error is :- Fatal error: Undefined class constant 'OPT_TABLE_PREFIX' in C:\Program Files\xampp\htdocs\rev20&#95;build\transport.core.php on line 54
Call Stack Time Memory Function Location
1 0.1508 263904 {main}( ) ..\transport.core.php:0

**Comment by splittingred** [comment]
splittingred submitted:

Judging by your error: Fatal error: Undefined class constant 'OPT_TABLE_PREFIX' in C:\Program Files\xampp\htdocs\rev20_build\transport.core.php on line 54 It looks like your build.config.php is set wrong: rev20_build

**Comment by shamblett** [comment]
shamblett submitted:

Fair enough, must admit I just updated my 2.0 area and tried the re-build, its the same area I've had for a while and builds have worked before but I didn't really look at this, just faster to file the JIRA so it can be looked at. I'll look at this in more detail ASAP.

**Comment by shamblett** [comment]
shamblett submitted:

OK fixed, for some reason the update didn't get the latest XPDO directory in core, which is an external svn link to the XPDO repo. I re-checked this out manually and all is OK now, I don't know why this happened but I'll keep an eye out for any re-occurence. Can close this.
