### ISSUE TITLE
For multiple checkbox values renderOutput leaves out the comma

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#11091]
bobray created Redmine issue ID 11091

For a set of checkboxes with the input value: red||blue||green If the user checks red and green, the rendered output is redgreen instead of red,green Also true for multi-select DD lists and for input option values in the form: red==1||blue==2||green==3 rendered output is 13 rather than 1,3

**Comment by splittingred** [comment]
splittingred submitted:

Not a bug; this should happen by default. We dont want TVs inserting markup or characters unless the user explicitly says to. To get the comma, you have to select the output type for the TV to "delimiter", and set it to a comma.

**Comment by BobRay** [comment]
bobray submitted:

Invalid.
