### ISSUE TITLE
Output filters on Element tags have no effect

### ISSUE THREAD

**Issue by martinf55** [modxbot/migrate#11094]
martinf55 created Redmine issue ID 11094

After upgrade to rev 6046 output filters do not seem to work on template variable tags, either for built-in or "snippet" filters. E.g.
[ &#91;_myContentTV:reverse&#93; ]
[ &#91;_myContentTV:mySnippet&#93; ] have no effect on the output, whereas on a built-in field: [ &#91;_content:reverse&#93; ]
[ &#91;_content:mySnippet&#93; ] they modify the output as expected.

**Comment by splittingred** [comment]
splittingred submitted:

Updating; seems to not be working on any Element type

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6079
