### ISSUE TITLE
Multiple checkbox TV default values not set properly

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#11090]
bobray created Redmine issue ID 11090

For a checkbox with the input option value set to red||blue||green both red and blue are checked no matter which is the default If the default is red||green, red and blue are still checked. For the form: red==1||blue==1||green==3 no checkboxes are checked no matter what the default it set to More or less the same problems exist with Multi-select lists.

**Comment by splittingred** [comment]
splittingred submitted:

I can't duplicate this at all in any browser. My values work fine, the checkboxes show as expected, etc.

**Comment by BobRay** [comment]
bobray submitted:

I can't duplicate it in a fresh checkout. Closing.
