### ISSUE TITLE
user unicity test crahes when creating a new user

### ISSUE THREAD

**Issue by ale-xx** [modxbot/migrate#11093]
ale created Redmine issue ID 11093

&#91;49&#93; core/model/modx/processors/security/user/_validation.php /\* check if the email address already exists */
$emailExists = $modx->getObject('modUserProfile',array('email' => $_POST &#91;&#39;email&#39;&#93; ));
if ($emailExists) {
if ($user_email->get('internalKey') != $_POST &#91;&#39;id&#39;&#93; ) { $modx->error->addField('email',$modx->lexicon('user_err_already_exists_email')); }
} $user_email should probably be $emailExists... on the other hand, i wonder why modx is trying to enforce email unicity (and why even when fixing the name of the object it wont enforce it)

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in an earlier version, and in r6076
