### ISSUE TITLE
strftime('%s', $value) generates an "a non well formed numeric value encountered" error in xpdoobject.class.php

### ISSUE THREAD

**Issue by Thalion** [modxbot/migrate#1114]
thalion created Redmine issue ID 1114

In core/xpdo/om/xpdoobject.class.php, line 932 : "a non well formed numeric value encountered"
$value= strftime($format, $value);
with $format = '%s' does not seem to work here, and it generates a warning.
With a little search, I found that this line is only called with $format = '%s', so it could be replaced with
$value=strtotime($value);
which should give the same result.

**Comment by opengeek** [comment]
opengeek submitted:

Can you tell me either where this is happening or what $value is when you get this WARN notice?
