### ISSUE TITLE
System Event Cleanup

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1124]
bobray created Redmine issue ID 1124

System Events Cleanup (some of these may be deprecated in Evo as well) I assume that the references in core/packages/core/preserved.php will go away on their own. Line references are to _build/data/transport.core.events.php These events are registered or exist in the file but are never invoked in Revo: OnWebSaveUser (47)
OnWebDeleteUser (54)
OnManagerCreateGroup (117)
OnLoadWebPageCache (138) (should be invoked in Revo?)
OnBeforeManagerPageInit (628)
OnBeforeEmptyTrash (635) (should be invoked in Revo?)
OnEmptyTrash (642) (should be invoked in Revo?)
OnCreateDocGroup (656)
OnUserFormRender (411) (should be invoked in Revo?)
OnWUsrFormPrerender (446)
OnWUsrFormRender (453)
OnBeforeWUsrFormSave (460)
OnWUsrFormSave (467)
OnBeforeWUsrFormDelete (474)
OnWUsrFormDelete (481)
OnFileManagerUpload (495) (should be invoked in Revo?)
OnSiteSettingsRender (530)
OnFriendlyURLSettingsRender (537)
OnUserSettingsRender (544)
OnMiscSettingsRender (558)
OnLogPageHit (621)
OnContextCreate (677) (should be invoked in Revo?)
OnContextUpdate (684) (should be invoked in Revo?)
OnContextDelete (691) (should be invoked in Revo?) Other issues: Category Events? OnContextFormPrerender and OnContextFormRender are invoked for update but not for create OnWebChangePassword (61) still invoked in Revo, but shouldn't be? (moduser.class.php 262) OnBeforePluginFormDelete (264) (should be invoked in Revo?) OnPluginEventRemove is in Revo but there's no corresponding Before event so maybe OnBeforePluginEventRemove should be added and/or OnPluginEventRemove should be renamed to the old-style name to match the other event names OnBeforeUserFormSave and OnUserFormSave events set the user object as a parameter in update.php, while other FormSave events don't send the object as a parameter. Should they all? OnSiteRefresh in controllers/system/refresh_site.php (33) looks redundant because it's invoked just after $modx->cacheManager->clearCache($paths, $options); and clearCache() invokes the same event These events are still in the database (modx_system_eventnames) but not in the code (not sure how that's happening): OnModFormPrerender
OnModFormRender
OnBeforeModFormDelete
OnModFormDelete
OnBeforeModFormSave
OnModFormSave It took several days to compile this list. It would be a HUGE favor to me if all changes (other than removing the deprecated functions from the _build) and a list of things that won't change were documented in one place (here?)

**Comment by splittingred** [comment]
splittingred submitted:

Bob, Thanks much for compiling this list. I'll get right on it. I'll also let you know how I resolve each one. As for the module-specific related plugin events (*Mod), they're still in your DB because we removed them from the build code a while back and didn't add a script to the setup/ scripts to remove them. (No real need to, really, since we're still in beta, and most users wont have them in their DB.) You can feel free to remove them.

**Comment by splittingred** [comment]
splittingred submitted:

Details (in parenthesis is file - line number) of committed fix in r5844: Removed
OnWebSaveUser?
OnWebDeleteUser
OnFriendlyURLSettingsRender (no longer applicable)?OnUserSettingsRender (no longer applicable)?
OnMiscSettingsRender (no longer applicable)
OnLogPageHit
OnWUsrFormPrerender
OnWUsrFormRender
OnBeforeWUsrFormSave
OnWUsrFormSave
OnBeforeWUsrFormDelete
OnWUsrFormDelete Already Invoked
OnManagerCreateGroup (processors/security/group/create - 82)
OnUserFormRender (processors/security/user/update - 38, create - 31) Added Event
OnBeforeDocGroupRemove (processors/security/documentgroup/remove - 18)
OnDocGroupRemove (processors/security/documentgroup/remove - 27) Added Invoke Calls
OnBeforeManagerPageInit (model/modx/modmanagerresponse.class.php - 79)
OnBeforeEmptyTrash (processors/resource/emptyrecyclebin - 13)
OnEmptyTrash (642) (processors/resource/emptyrecyclebin - 46)
OnCreateDocGroup (processors/security/documentgroup/create - 27)
OnFileManagerUpload (processors/browser/directory/upload - 40)
OnSiteSettingsRender (controllers/system/settings/index - 11) - should not be used, however, to render custom settings; just create packages for this and use modSystemSetting objects
OnContextCreate (processors/context/create - 39)
OnContextUpdate (processors/context/update - 60, updatefromgrid - 28)
OnContextDelete (processors/context/remove - 33) Leaving In - Can be fired in the front-end
OnWebSaveUser
OnWebDeleteUser?

**Comment by BobRay** [comment]
bobray submitted:

Thanks a million for the great record of changes! Still to do (and some questions) &#8211; I could do all but the first two and #7 if you prefer: 1. OnWebSaveUser &#8211; can't find
2. OnWebDeleteUser &#8211; can't find 3. This can't be right, can it (it's still there)? Should be 'resource' => &$resource and it has an extra comma at the end of the array. /\* invoke OnDocPublished event */
$modx->invokeEvent('OnDocPublished',array(
'docid' => $resource->get('id'),
'resource' => $resource->get('id'),
)); 4. In Evo, the two trash invoke events both just send $ids as a parameter, an array containing ids of deleted (or to-be-deleted) resources, which would be necessary for most uses of them. The user could get the count from the array. Revo should send $ids or the &$resource array of objects, imo. If that's not possible, 'num_deleted' should be renamed to 'numdeleted' or 'count' to match the style of all the other sent variables and OnBeforeEmptyTrash should probably send some parameter. OnBeforeEmptyTrash (processors/resource/emptyrecyclebin - 13)
OnEmptyTrash (642) (processors/resource/emptyrecyclebin - 46) 5. OnBeforePluginFormSave has the wrong comment in update and should send the plugin object as a parameter: 'plugin' => &$plugin 6. Should OnBeforePluginEventRemove be changed to OnBeforePluginFormDelete to match Evo? 7. Category events? 8. To be consistent with all the other events (unless they're all changing in 2.1), these should really change from this: OnContextCreate (processors/context/create - 39)
OnContextUpdate (processors/context/update - 60, updatefromgrid - 28)
OnContextDelete (processors/context/remove - 33) to this: OnContextFormSave (with mode set to 'new' or 'upd')
OnContextFormDelete 9. and there should maybe be matching OnBefore events.
