### ISSUE TITLE
'mode' is missing from OnUserFormPrerender

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1125]
bobray created Redmine issue ID 1125

When OnUserFormprerender is invoked, 'mode' is set to 'upd' in update.php, but no mode is set in create.php &#8211; only 'id' is set. Mode should be set to 'new'. Also, OnUserFormRender is not invoked in either file (or anywhere else).

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5842

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed (including OnUSerFormRender)
