### ISSUE TITLE
OnManagerCreateGroup is never invoked

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1128]
bobray created Redmine issue ID 1128

Is this deprecated?

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5829. A lot of the plugin events may be deprecated, or missing. Would definitely be worth a cleanup look.

**Comment by BobRay** [comment]
bobray submitted:

A number of them are still registered, but never invoked. I'm going through them for the book. I'll try to keep a list.
