### ISSUE TITLE
php file permissions must be 644, not 664

### ISSUE THREAD

**Issue by mikerott** [modxbot/migrate#1139]
mikerott created Redmine issue ID 1139

After successfully executing setup, file permissions on some files are set to 664. There may be more files that this, but these are the ones I saw: manager/index.php
manager/ht.access
index.php
ht.access Some configurations of php do not allow 664 on php files. The server will return a 500 internal server error if the permissions are anything other than 644. Thanks.
mike

**Comment by splittingred** [comment]
splittingred submitted:

Can you please list your server info, including, but not limited to: 1. PHP version
2. MySQL version
3. Apache version

**Comment by mikerott** [comment]
mikerott submitted:

Sure, please see comment in MODX-1257 : http://svn.modxcms.com/jira/browse/MODX-1257?focusedCommentId=12741&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#action_12741

**Comment by mikerott** [comment]
mikerott submitted:

Just found a forum post in the MODX forums regarding my host (site5) and their file permissions policy: http://modxcms.com/forums/index.php?topic=31326.0 I like my host, but it doesn't look like it's playing nice with MODX, or vice versa?

**Comment by mikerott** [comment]
mikerott submitted:

I'll be glad to set you up with a test database and ftp area where you can test if you'd like. Let me know.

**Comment by opengeek** [comment]
opengeek submitted:

It's not clear to me what the problem is here. You should have full control over file permissions on your server and nothing in MODx dictates that files should have 664 permissions. What package was this, traditional or advanced?

**Comment by splittingred** [comment]
splittingred submitted:

Could not reproduce this; nor does any code cause this.
