### ISSUE TITLE
cannot login due to bug in login.js

### ISSUE THREAD

**Issue by mikerott** [modxbot/migrate#1140]
mikerott created Redmine issue ID 1140

Manager login panel was not allowing me to login (I got no feedback or indicators that my login creds were even accepted from the form), so I fired up Firebug and saw this during the page load of the Manager Login page: 1 Error _ is not defined
title: _('login')\n login.js (line 47)

**Comment by splittingred** [comment]
splittingred submitted:

Looks like your install failed, most likely due to a server misconfiguration. Can you please list your server info, including, but not limited to:
1. PHP version
2. MySQL version
3. Apache version
4. pdo_mysql installed?
5. Any errors in core/cache/logs/error.log or the setup logs in that directory?
6. Any relevant apache error log entries?

**Comment by mikerott** [comment]
mikerott submitted:

Sure, thanks for taking such a quick look! Here's the phpinfo(): http://experiencefellowship.ohmyhead.com/info.php Apache version is reported as 2.2.11 (Unix)
MySQL version is reported as 5.0.81-community-log I followed these instructions from Jason to get xPDO working: http://modxcms.com/forums/index.php/topic,31032.msg202742.html#msg202742 Output from the only file in core/cache/logs/:
ohmyhead@ohmyhead.com &#91;~/www/experiencefellowship&#93; # cat core/cache/logs/install.config.2009-10-05T13:52:23
 &#91;2009-10-05 13:52:26&#93; (ERROR @ /setup/index.php) Error packing /home/ohmyhead/public_html/experiencefellowship/index.php to /home/ohmyhead/public_html/experiencefellowship/core/packages/core/modContext/515674d74fb65d3459617987b6ea7f0f.0.preserved.zipPCLZIP_ERR_MISSING_FILE (-4) : File '/home/ohmyhead/public_html/experiencefellowship/index.php' does not exists
 &#91;2009-10-05 13:52:26&#93; (ERROR @ /setup/index.php) Error packing /home/ohmyhead/public_html/experiencefellowship/ht.access to /home/ohmyhead/public_html/experiencefellowship/core/packages/core/modContext/515674d74fb65d3459617987b6ea7f0f.1.preserved.zipPCLZIP_ERR_MISSING_FILE (-4) : File '/home/ohmyhead/public_html/experiencefellowship/ht.access' does not exists
 &#91;2009-10-05 13:52:27&#93; (ERROR @ /setup/index.php) Error packing /home/ohmyhead/public_html/experiencefellowship/manager/controllers to /home/ohmyhead/public_html/experiencefellowship/core/packages/core/modContext/1642954be5370caa3c12fffb831fbccd.1.preserved.zipPCLZIP_ERR_MISSING_FILE (-4) : File '/home/ohmyhead/public_html/experiencefellowship/manager/controllers' does not exists
 &#91;2009-10-05 13:52:27&#93; (ERROR @ /setup/index.php) Error packing /home/ohmyhead/public_html/experiencefellowship/manager/templates to /home/ohmyhead/public_html/experiencefellowship/core/packages/core/modContext/1642954be5370caa3c12fffb831fbccd.2.preserved.zipPCLZIP_ERR_MISSING_FILE (-4) : File '/home/ohmyhead/public_html/experiencefellowship/manager/templates' does not exists
 &#91;2009-10-05 13:52:27&#93; (ERROR @ /setup/index.php) Error packing /home/ohmyhead/public_html/experiencefellowship/manager/ht.access to /home/ohmyhead/public_html/experiencefellowship/core/packages/core/modContext/1642954be5370caa3c12fffb831fbccd.3.preserved.zipPCLZIP_ERR_MISSING_FILE (-4) : File '/home/ohmyhead/public_html/experiencefellowship/manager/ht.access' does not exists
 &#91;2009-10-05 13:52:27&#93; (ERROR @ /setup/index.php) Error packing /home/ohmyhead/public_html/experiencefellowship/manager/index.php to /home/ohmyhead/public_html/experiencefellowship/core/packages/core/modContext/1642954be5370caa3c12fffb831fbccd.4.preserved.zipPCLZIP_ERR_MISSING_FILE (-4) : File '/home/ohmyhead/public_html/experiencefellowship/manager/index.php' does not exists No apache files that I can see. Also, now that I see the core/cache/logs/error.log file, I think this might be related to: MODX-1258

**Comment by splittingred** [comment]
splittingred submitted:

Cannot reproduce, but might be related to issue posted earlier in comments. Closing this one to prevent duplicate issues.
