### ISSUE TITLE
Resource Groups page: 2nd resource tree not visible

### ISSUE THREAD

**Issue by martinf55** [modxbot/migrate#1141]
martinf55 created Redmine issue ID 1141

On the Security / Resource Groups page, the right-hand tree (containing the resources to be dragged into the groups) isn't appearing.
The collapse arrow for the containing panel is there, but no content (see attached screenshot). This is with the latest SVN 2.0 branch rev5782.
I've tried it with a clean install in case my upgraded install was the cause, same issue.
Also tried it in Safari and Firefox. Possibly related: the Tools / Import Resources page is not showing the document tree either.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5785
