### ISSUE TITLE
Server Offset Time entered in "hours" in System Settings, treated as "seconds" in System Info

### ISSUE THREAD

**Issue by fmilitao** [modxbot/migrate#1146]
unknown created Redmine issue ID 1146

The description of Server Offset Time in System Settings requires the offset to be entered in hours, but System Info takes the value as seconds. The following shows a fragment of System Info when Server Offset Time is set to 1 hour: Server Time 09:05:47 AM
Local Time 09:05:48 AM
Server Offset 0.000277777777778 h

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5862
