### ISSUE TITLE
Components not being added to menus table

### ISSUE THREAD

**Issue by neilness** [modxbot/migrate#1158]
neilness created Redmine issue ID 1158

since at least r5765, after packages are installed, entries are added to the actions table and they can be accessed by manually entering the url: /manager/?a=#, but they are not being added to the menus table, and therefore not showing up in the components menu.

**Comment by splittingred** [comment]
splittingred submitted:

New releases will need to be made for all those components, since the method they were adding menus is no longer valid. This will be done before beta4.

**Comment by splittingred** [comment]
splittingred submitted:

Will be resolved at the beta4 release.
