### ISSUE TITLE
Modparser class generates warning : undefined variable $qs

### ISSUE THREAD

**Issue by Thalion** [modxbot/migrate#1159]
thalion created Redmine issue ID 1159

In file xore/model/modx/modparser.class.php, line 921, variable $qs is defined inside a loop ($qs = array() , but used on line 934 outside the loop : .
$this->_output= $this->modx->makeUrl($this->_output, $context, $qs); If condition on line 920 is not met, there is a warning "undefined variable". A simple fix would be to declare this variable before the loop condition, ie put it one line up.

**Comment by Thalion** [comment]
thalion submitted:

After more search, the fix should simply be to add before line 920 the following declaration :
$qs='';

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5828. Thanks!
