### ISSUE TITLE
"Save and Add Another" button is not working correctly.

### ISSUE THREAD

**Issue by zaigham** [modxbot/migrate#1160]
zaigham created Redmine issue ID 1160

When we save a Resources and select "Save and Add Another" icon from the static action bar, the newly created Resource doesnt appear in the Resources Tree. But ID # advances OK. You can try by creating a new resource via "Add Another" option and then creating other by choosing "Continue Editing" option. The later will show up but former will not.

**Comment by splittingred** [comment]
splittingred submitted:

Can't replicate this at all in SVN; must have been fixed since then.
