### ISSUE TITLE
MODx browser without upload button

### ISSUE THREAD

**Issue by tkapet** [modxbot/migrate#1161]
tkapet created Redmine issue ID 1161

I can't find an upload button in modx browser &#91;.....manager/controllers/browser/index.php&#93; so that i can upload an image from the local drive becouse
there is no right-click appearing when you click the left menu with the folders:assets, images, files, flash etc.
The right click that show a costum ext - javascript menu works only in files on the right with one option("Remove file") Looking at Net tab of firebug there some 404 not found http requests. Example the following files where not found:
 http://localhost/modxbeta/manager/assets/modext/util/modhext.js
 http://localhost/modxbeta/manager/templates/default/images/icons/sort.png

**Comment by splittingred** [comment]
splittingred submitted:

This has been addressed in svn.
