### ISSUE TITLE
Categories Delete Issue When Contains Elements

### ISSUE THREAD

**Issue by mattcdavis1** [modxbot/migrate#1165]
mattcdavis1 created Redmine issue ID 1165

I deleted a category in the Content Elements Tree that had elements in it. Now, the elements aren't showing up but when I try to make a new element with the same name as the old one ModX tells me the name already exists. Also, I'm still able to use the snippets / chunks I just can't see them in the tree to modify or delete them. From another user: "I noticed this as well. It also happens when resetting a category that has sub-elements back to a non-category page. The other items just vanish."

**Comment by splittingred** [comment]
splittingred submitted:

This should be fixed in SVN; confirm?
