### ISSUE TITLE
Click and drag from Resource Treee to Symlink field inserts a web link instead of just the number as it should

### ISSUE THREAD

**Issue by mattcdavis1** [modxbot/migrate#1166]
mattcdavis1 created Redmine issue ID 1166

Click and drag from Resource Treee to Symlink field (when creating a new symlink) inserts a web link instead of just the number as it should

**Comment by splittingred** [comment]
splittingred submitted:

"should" is subjective here...I'm not sure this is completely a bug, but we can look into it. I'm not sure we want to prevent [[ ]] tags in the field.

**Comment by splittingred** [comment]
splittingred submitted:

Implemented in r5846
