### ISSUE TITLE
When creating a new static resource, "Hide from Menus" gets checked automatically when save button is pressed even if it wasn't selected.

### ISSUE THREAD

**Issue by mattcdavis1** [modxbot/migrate#1167]
mattcdavis1 created Redmine issue ID 1167

When creating a new static resource, "Hide from Menus" gets checked automatically when save button is pressed even if it wasn't selected. <a href= http://screenr.com/rZ7 >Link to screencast illustrating issue</a>

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5755
