### ISSUE TITLE
Deprecate and/or disable checkChildren()?

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1170]
bobray created Redmine issue ID 1170

checkChildren() sets isFolder based on whether the resource has children. Since we've separated isFolder and hasChildren(), I don't think we want this happening any more. checkChildren() is still called several times in the code.

**Comment by opengeek** [comment]
opengeek submitted:

I just went ahead and removed this function so it will not be abused.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed: checkChildren() and all references to it removed.
