### ISSUE TITLE
Call to member function get() on non-object when creating new weblink with continue editing selected

### ISSUE THREAD

**Issue by opengeek** [modxbot/migrate#1183]
opengeek created Redmine issue ID 1183

When I add a weblink with the "continue editing" option selected I get the following error (Note: Weblink is succesfully created even with error): Fatal error: Call to a member function get() on a non-object in /homepages/43/d248200557/htdocs/modx-2.0.0-beta/manager/controllers/resource/weblink/update.php on line 17 The error does not occur when the "close" or "add another" option is selected. Fatal error: Call to a member function get() on a non-object in /webroot/htdocs/www.revosvn.local/manager/controllers/resource/weblink/update.php on line 17 Call Stack: 0.0008 668408
1. {main}() /webroot/htdocs/www.revosvn.local/manager/index.php:0 0.1719 10405680
2. modManagerRequest->handleRequest() /webroot/htdocs/www.revosvn.local/manager/index.php:77 0.1735 10510944
3. modManagerRequest->prepareResponse() /webroot/htdocs/www.revosvn.local/core/model/modx/modmanagerrequest.class.php:153 0.1825 10746480
4. modManagerResponse->outputContent() /webroot/htdocs/www.revosvn.local/core/model/modx/modmanagerrequest.class.php:198 0.2145 11185864
5. include('/webroot/htdocs/www.revosvn.local/manager/controllers/resource/weblink/update.php') /webroot/htdocs/www.revosvn.local/core/model/modx/modmanagerresponse.class.php:89

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5749
