### ISSUE TITLE
modUser->isMember() performs an AND rather than the documented OR operation on multiple groups

### ISSUE THREAD

**Issue by martinf55** [modxbot/migrate#1192]
martinf55 created Redmine issue ID 1192

The documentation for modUser->isMember() states that expected functionality is that the method returns true if the user is a member of ANY of the supplied groups.
e.g. in the online documentation Examples: "See if the User is a member of either the 'Staff' or 'Investors' groups."
e.g. in the API documentation: "return: True if the user is a member of any of the groups specified." Actually though, the implementation only returns true if the user is a member of ALL of the supplied groups. The documented and commented behaviour would ideally match the implementation.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5747 by adding $matchAll 2nd parameter. If set to true, will require user to be a member of all groups specified.
If set to false, will require user to be a member of at least one of the groups specified. Defaults to false.
