### ISSUE TITLE
Stay on current tab in tree when Main Menu item is executed

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1193]
bobray created Redmine issue ID 1193

When you execute a Main Menu action, the tree reverts to the Resources tab. I'm not sure if it's possible, but it would be nice if it would stay on the tab it was on, since you're often still working there.

**Comment by splittingred** [comment]
splittingred submitted:

Implemented in r5722

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
