### ISSUE TITLE
Escaped quotes in TV href checbox rendering

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1197]
bobray created Redmine issue ID 1197

This bug doesn't exist in Evo, but in Revo, if you put an href into a TV and render it as a checkbox, the URL has escaped quotes in it. Steps to reproduce: 1. Create a TV with input type Checkbox and Input Option Values: <a href="Hello">Hello</a> 2. Edit a doc with the TV attached and check the checkbox. 3. Display the TV with a tag in the doc. The doc will show: Hello (correctly) but when you hover over it, the link will be: http://yoursite.com/\ "Hello\" The URL will be normal if you use a radio button input type.

**Comment by splittingred** [comment]
splittingred submitted:

This doesnt seem to happen to me at all, Bob. Mine renders it properly: http://localhost/modx/Hello

**Comment by BobRay** [comment]
bobray submitted:

Are you sure you followed the steps above and used double quotes? I just tried it again and it's still there.

**Comment by splittingred** [comment]
splittingred submitted:

Yep, I did. What browser are you doing this in? Also, what PHP version? In the DB for the TV, does the "elements" column show <a href="Hello">Hello</a> ?

**Comment by BobRay** [comment]
bobray submitted:

PHP 5.2.6
MySQL 5.0.56 It happens in FF 3.5.2 and Chrome: FF URL: (cut and pasted) http://localhost/test/%5C%22Hello%5C%22
Displayed: http://localhost/test/\ "Hello\" In IE7: http://localhost/%22Hello/%22 In the DB: <a href="Hello">Hello</a> I wonder about this code in the MODx class, which appears to depend on the accuracy of get_magic_quotes_gpc(): if (get_magic_quotes_gpc()) { $target[$key]= stripslashes($value); } else { $target[$key]= $value; }

**Comment by splittingred** [comment]
splittingred submitted:

Well, I tried in FF, and it still renders fine for me. That GPC reference is in modX::sanitize(), which doesn't get called for TV output rendering... I've looked all through it, and cant duplicate this at all on my environment. The code is pretty much identical to Evo's, too, which leaves me even more confused.
