### ISSUE TITLE
none of the loaders work

### ISSUE THREAD

**Issue by tomj** [modxbot/migrate#1203]
tomj created Redmine issue ID 1203

When I log into my installation, the loader will just keep loading and loading (the modx onscreen loader), so I have to re-fresh the page and then it's already logged on. Also when I go to the Package Management, there are no providers in the list, and when I try to add the official modx one it just won't save. Also when I upload a Package to the right server directory and try and add it from the Package Management screen I get this message:
MODx will now search your core/packages directory for any valid packages, and then add them in. Please note that it will NOT install them, but simply add them into your workspace. Please make sure before proceeding that you have uploaded the packages into the core/packages directory."
And I can't go any further...
That's all for now..
Cheers

**Comment by splittingred** [comment]
splittingred submitted:

Can you provide more information on your server environment? (ie, PHP version, Apache Version, MySQL version, server OS) Also, what versions of FF and SafarI? And, Loaders have pretty much been removed in SVN. I can't duplicate this error, so I'm going to assume its related to your environment.

**Comment by splittingred** [comment]
splittingred submitted:

Closing this since this is not a problem in SVN, and must be an environment issue.
