### ISSUE TITLE
Change name of "Import Lexicon" and "Export Lexicon"

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1204]
bobray created Redmine issue ID 1204

I suggest changing "Import Lexicon" to "Import Topic File" since that's what you're actually doing and "Export Lexicion" to "Export to Topic File" or "Export Topic."

**Comment by splittingred** [comment]
splittingred submitted:

Done in r5699

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
