### ISSUE TITLE
$tv->setValue('id','newvalue') doesn't works !

### ISSUE THREAD

**Issue by phron** [modxbot/migrate#1207]
anso created Redmine issue ID 1207

A simple TV called 'color'
A snippet to change the value of the TV in a specific document.
Snippet code :
 &#91;code&#93;
$id=4;
$resource = $modx->getObject('modResource',$id);
$tv = $modx->getObject('modTemplateVar', array('name' => 'color')); // change the value for a resource
if($tv){ $changed = $tv->setValue($resource->get('id'), 'yellow'); $tv->save(); $resource->save(); }
return;
 &#91;/code&#93; doesn't have any effect.
If TV is empty, doesn't create the record, if the TV has a value (i.e. 'red') it's still 'red' and not changed for 'yellow'. No update (nor creation) in the 'site_templvar_contentvalues' table. I get the correct TV (I made an output to control this, extract the correct values when the TV is not empty) I just cannot update TVs or set TV values...

**Comment by BobRay** [comment]
bobray submitted:

That parallels my experience exactly. I also verified in the DB that the TV value for that resource did not change. XAMPP 1.7.1
Apache 2.2.11
PHP 5.2.9
MySQL client 5.0.51a (WTF? &#8211; I upgraded from that a long time ago and 1.7.1 has a much newer version).

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5702
