### ISSUE TITLE
[Revo-Beta3] - Problem with TVs : can not reset checkboxes 

### ISSUE THREAD

**Issue by phron** [modxbot/migrate#1218]
anso created Redmine issue ID 1218

I have a TV called 'color' : input type : checkbox input type values : Blue||Red||Yellow output type : Delimiter, delimiter : , If I do NOT check any value at all => all is OK
If I check one or two or three values => all is OK
If I change my choices (i.e, 'Blue,Yellow' for 'Blue,Red') => all is OK
Now if I change my choice and want to UNCHECK all option (so 'reset' the tv to his initial state which is no value) it doesn't work at all !
The last value saved still present, the corresponding line in the "site_tmplvar_contentvalues" is not removed, and seems no accept empty value in 'value' column...

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5748
