### ISSUE TITLE
Change "Lexicon" to "Topic File" in "Import Lexicon" popup

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1219]
bobray created Redmine issue ID 1219

The term Lexicon should be reserved for the MODx service into which you load language strings, IMO. I think what you're actually specifying in the field is a "Topic file."

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5699

**Comment by BobRay** [comment]
bobray submitted:

This is fixed on the grid, but still needs to be change in the popup that appears when you click on "Import Topic."

**Comment by BobRay** [comment]
bobray submitted:

Closing. Will create new issue for remaining problem.
