### ISSUE TITLE
Add hasChildren() convenience method

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1223]
bobray created Redmine issue ID 1223

Now that in Revo isFolder and hasChildren are two independent concepts, it would be nice to have a hasChildren method for developers to use to determine the latter. hasChildren($id) should do it &#8211; I don't think we need hasChildren('resouceName'). This might do it (untested): function hasChildren( $id) {
return (count($this->getChildIds($id) > 0);
}

**Comment by splittingred** [comment]
splittingred submitted:

What about on the Resource class itself; ie, $modx->resource->hasChildren() // returns boolean true/false Or should it return the # of children?

**Comment by BobRay** [comment]
bobray submitted:

Putting it in the resource class would make it parallel to isFolder and be more correct OOP. haschildren($id) OTOH, might be faster in some cases since you wouldn't have to actually get the resource and it would let you perform the test from anywhere. I'm not sure it's worth the extra time and code to return the number of children since most times you would want that, you'd actually be getting the children and could use count() on the array. It might be faster just to return true on the first child found. That said, either way is fine with me on both issues.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
