### ISSUE TITLE
Give new namespaces a "default" topic

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1225]
bobray created Redmine issue ID 1225

When you create a new namespace, its grid comes up with a red outline around the "Topic" field, but there's no way to enter anything in that field. It's not clear what to do about it (currently, Create New | Topic). Since virtually all user-created namespaces will have a "default" topic, it makes sense to create it automatically when the namespace is created.

**Comment by splittingred** [comment]
splittingred submitted:

Dont want to do this, because Namespace doesnt necessarily imply Lexicon Topic.
