### ISSUE TITLE
Improve ifFolder checkbox tooltip

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1229]
bobray created Redmine issue ID 1229

The tooltip from Evo is better, IMO, because it makes it clear that a container can also have content. This is what I'm suggesting (in core/lexicon/en.resource.inc.php): $_lang &#91;"resource_folder_help"&#93; = 'Check this to make the Resource also act as a Container for other Resources. A \'Container\' is like a folder, only it can also have content.'; It currently says: 'When enabled this will make the resource also act as a container for other resources. A \'container\' is like a folder, only it can also have children resources.'; (which is less clear and a little redundant)

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5709

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
