### ISSUE TITLE
Convert weblink to document (and vice versa Revo) 

### ISSUE THREAD

**Issue by ncrossland** [modxbot/migrate#1246]
ncrossland created Redmine issue ID 1246

There's no facility to change a weblink into a document (and vice versa) without deleting it and starting again. Would be nice to have a convert to document option on weblinks, and a convert to weblink option on documents.

**Comment by splittingred** [comment]
splittingred submitted:

Just needs to reload the page if the class_key changes. Should be an easy fix. Assigning to pl.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r7093
