### ISSUE TITLE
Properties lost on save

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1270]
bobray created Redmine issue ID 1270

Steps to reproduce (not sure if all are necessary): On the properties tab of a chunk: Create two default properties. Create a new property set. Override the value of the second default property. Click on Done but don't save.
Add a third property not in the default set.
Click on Done
Click on Save Property Set. The new property is lost. This doesn't happen every time. I got it to occur three times in a row, then it didn't occur several times in a row following the exact steps above each time.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5712

**Comment by BobRay** [comment]
bobray submitted:

Testing this, I did the following: Create a new chunk
Add name and content
Go to Properties tab
Add two default properties
Click on Add property set.
Add a new property set. The default properties are gone.
Revert all to default has no effect. There's no way to get back to the default properties grid without navigating away and coming back, and then it's empty.
