### ISSUE TITLE
Take Templates off the list of attachable elements in Tools | Property Sets

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1271]
bobray created Redmine issue ID 1271

Until there's a way to tell a template which property set to use, there shouldn't be a way to attach a property set to a template in Tools | Property Sets. Should just involve taking it off the drop-down list. If possible, "Add Property Set" should be removed from the grid of the Properties tab for templates as well.

**Comment by splittingred** [comment]
splittingred submitted:

Fixing issue to be more accurate ("Tools | System Settings" should be "Tools | Property Sets").

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5633

**Comment by BobRay** [comment]
bobray submitted:

Confirmed Fixed.
