### ISSUE TITLE
Default properties not saved for new element

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1272]
bobray created Redmine issue ID 1272

Steps to reproduce: Right click on chunks and create a new chunk. Give the chunk a name and some content Switch to the Properties tab Unlock default properties and add a couple
Save the Chunk (or switch to the main tab and save the chunk &#8211; doesn't matter) Navigate to another chunk and come back &#8211; the default properties are gone. Doesn't happen with existing chunks. Happens with chunks and templates so probably true for all elements.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5664

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
