### ISSUE TITLE
Show TV names on Template Variable tab 

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1275]
bobray created Redmine issue ID 1275

Unless the user uses the same term for the Name and Caption of a TV, there's no way to know what to put in the TV's content tag without actually loading up the TV in Quick Update and looking. I'm suggesting putting the name of the TV in parentheses under or after the Caption on the TV tab of the Create/Edit Resource panel. Making It available when you hover over the caption would be an alternative that wouldn't mess with the formatting of the panel.

**Comment by BobRay** [comment]
bobray submitted:

I see that the description shows when you hover over the Caption. That probably shouldn't change. I still think it would be good if the name showed in parentheses after or under the caption. Most users won't think to put it in the description.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5759

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed (nice)
