### ISSUE TITLE
Checking Template Access box doesn't make a TV dirty

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1283]
bobray created Redmine issue ID 1283

If you create a new template variable, save it, then go to the Template Access tab and mark a check box, the save button is dead until you go to the General tab and change something. I don't think this happens with existing TVs, just new ones.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5756

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed (FF 3.5)
