### ISSUE TITLE
Add Rename File to right-click menu

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1305]
bobray created Redmine issue ID 1305

I've wanted this for a really long time. On a shared server, it's a royal pain to have to go through cPanel to rename a file.

**Comment by splittingred** [comment]
splittingred submitted:

Added in r6114 to branches/2.0-setup, will be merged in to branches/2.0 soon.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
