### ISSUE TITLE
Wrong Class Names in Schema

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1307]
bobray created Redmine issue ID 1307

Some of the classes below aren't correct. I think all the 'modResource' ones should be 'modUser' (not sure about 'Sender' and 'Recipient'). <object class="modUser" table="users" extends="modPrincipal">
. . .
<aggregate alias="CreatedBy" class="modResource" key="createdby" local="id" foreign="createdby" cardinality="many" owner="local" />
<aggregate alias="EditedBy" class="modResource" key="editedby" local="id" foreign="editedby" cardinality="many" owner="local" />
<aggregate alias="DeletedBy" class="modResource" key="deletedby" local="id" foreign="deletedby" cardinality="many" owner="local" />
<aggregate alias="PublishedBy" class="modResource" key="publishedby" local="id" foreign="publishedby" cardinality="many" owner="local" />
<aggregate alias="Sender" class="modUserMessage" key="sender" local="id" foreign="sender" cardinality="many" owner="local" />
<aggregate alias="Recipient" class="modUserMessage" key="recipient" local="id" foreign="recipient" cardinality="many" owner="local" />
<composite alias="modUserProfile" class="modUserProfile" key="internalKey" local="id" foreign="internalKey" cardinality="one" owner="local" />
<composite alias="modUserSetting" class="modUserSetting" key="user" local="id" foreign="user" cardinality="many" owner="local" />
<composite alias="modUserGroupMember" class="modUserGroupMember" key="member" local="id" foreign="member" cardinality="many" owner="local" />
</object>

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5627

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
