### ISSUE TITLE
Ability of using Smarty syntax (i.e : {if...}html{/if}, {foreach} etc...) in tempaltes

### ISSUE THREAD

**Issue by phron** [modxbot/migrate#1310]
anso created Redmine issue ID 1310

It would be great to have ability of using Smarty syntax (instead of PHx) in templates.

**Comment by splittingred** [comment]
splittingred submitted:

Closing this issue, because it's not related to core and should be done in a Component. This can be done via a plugin that loads the Smarty service before the Resources are parsed. You could post this in the Wish List forum.
