### ISSUE TITLE
Add new package>Search Locally for package doesn't works.

### ISSUE THREAD

**Issue by phron** [modxbot/migrate#1325]
anso created Redmine issue ID 1325

Add new package -> Search Locally doesn't do anything. No message, no new window, no visibility of any package, just a quick flash and you still on the pakage management page ...

**Comment by splittingred** [comment]
splittingred submitted:

What is the package you uploaded?
What's it's filename?
Is your core/packages directory writeable?

**Comment by phron** [comment]
anso submitted:

a littel mystery there... but after a new install of Wamp and a new fresh install of Revolution 2.0-beta 3 all works fine...
