### ISSUE TITLE
The user creation form is unclear in two tabs

### ISSUE THREAD

**Issue by paz-zz** [modxbot/migrate#1333]
paz created Redmine issue ID 1333

This is just a thought, but since the access permissions are required, maybe it would be better to put the User Group and Role fields for that in the main screen?
I forgot it the first time, because I didn't look at the second tab.
A second tab usually only contains extras and not required fields.
This caused my manager to crash, as all I got was an error page.

**Comment by pulse-xx** [comment]
pulse submitted:

I personally think this is already clear enough. Adding too much to the add user screen would be very daunting to new users. Also, adding too much content to any single tab makes it seems as though the process is more work than its worth. The simpler the better. The Access Permissions Tab is clear enough, especially as it is now with the new theme. Changing to Will not fix.

**Comment by pulse-xx** [comment]
pulse submitted:

Current display structure is more than adequate.
