### ISSUE TITLE
Can't get error and unauthorized pages to work

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1349]
bobray created Redmine issue ID 1349

I've created the error and unauthorized pages and can access them directly with site/index.php?id=n. Both are published and the System Settings are set for them, but trying to access a nonexistent page in a different browser gives me a standard 404 page from the browser. Trying to access an unpublished document shows me the unpublished document. I've cleared all caches and cookies and tried with and without .htaccess and FURLS with the same result.

**Comment by BobRay** [comment]
bobray submitted:

The only remote install I have is a fairly old rev and it doesn't do this. It could be a problem with XAMPP 1.7.1. Let me know if you can duplicate this. If not, I'll close it.

**Comment by splittingred** [comment]
splittingred submitted:

I cannot duplicate this.

**Comment by BobRay** [comment]
bobray submitted:

Something in my setup apparently.
