### ISSUE TITLE
Login form doesnt trigger browser's "Remember Password" feature.

### ISSUE THREAD

**Issue by zaigham** [modxbot/migrate#1358]
zaigham created Redmine issue ID 1358

Login form doesnt trigger browser's "Remember Password" feature. However if the url has username and password already stored in the browser's password store, it populates fine. Checked in FF, Safari, IE, Chrome across the platforms.

**Comment by splittingred** [comment]
splittingred submitted:

The goal of this resolution will be to create a HTML-based form that will be styled properly, and use Ext to access the login processor.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6367
