### ISSUE TITLE
changing friendly_url_suffix has no affect on how friendly urls are being displayed .html is being used as a suffix at all times

### ISSUE THREAD

**Issue by jaz6ix** [modxbot/migrate#1363]
jaz6ix created Redmine issue ID 1363

changing friendly_url_suffix under system settings has no affect on how friendly urls are being displayed .html is being used as a suffix at all times. I tried to leave it blank, use .htm and htm. I also tried to empty the cache. Nothing seems to affect the .html appended to the end of document aliases in friendly urls.

**Comment by splittingred** [comment]
splittingred submitted:

Not a bug - suffixes are managed now by Content Types. Each Resource can change its suffix by changing its Content Type. See System -> Content Types.
