### ISSUE TITLE
Wrong includes of javascript files from ext2 where it should be ext3

### ISSUE THREAD

**Issue by HenrikNielsen** [modxbot/migrate#1366]
henriknielsen created Redmine issue ID 1366

When inserting a image with TinyMCE 3.2.0.1-beta3 in the content area - all I got are a blank window. But after that I've a look at the code at "/manager/controllers/browser/index.php" it seems that it is calling four javascript files in "/manager/assets/ext2/" but in Revolution beta3 (SVN 5537) it should be "/manager/assets/ext3/" - Note the "ext3".

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5545
