### ISSUE TITLE
site_unavailable_message description refers to nonexistent system setting?

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1376]
bobray created Redmine issue ID 1376

The description for the site_unavailable_message system setting includes this note: "Note: This message will be displayed only if the site unavailable page option is not set." I couldn't find any site unavailable page option. It's not in the "Site" area.

**Comment by opengeek** [comment]
opengeek submitted:

Added missing site_unavailable_page System Setting.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
