### ISSUE TITLE
To choose the target context, when duplicating a web document

### ISSUE THREAD

**Issue by paz-zz** [modxbot/migrate#1410]
paz created Redmine issue ID 1410

Currently you can only duplicate a document in its own context.
But it would be great if you'd also be able to choose the context you want to duplicate it to.
The larger one site gets, it'll make it easier to keep similair contexts exactly the same.

**Comment by splittingred** [comment]
splittingred submitted:

This has problems; if one chooses say, 'context2', and it's not a root-level Resource, it wont work - because the tree wont find the parent of the duplicated resource in the new context. You'd need some way to specify the new parent.

**Comment by splittingred** [comment]
splittingred submitted:

Should be able to just drag the resource, anyway. Closing for now.
