### ISSUE TITLE
Can't decode JSON string from directory getlist processor

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1413]
shamblett created Redmine issue ID 1413

I can no longer decode the JSON string returned by the /directory/getlist processor. MODX-903 was raised to change this encoding to use the string literals fix applied to the resources and elements processors. OK, this has not been done yet but I've been using my own copy that changes the 'return $this->toJSON' line to 'return $modx->toJSON', this has been working up till now. Neither of these methods now work hence I can't decode this string in PHP code. Version is Revo 2 beta 2, r5472 from the revolution branch

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5473

**Comment by shamblett** [comment]
shamblett submitted:

Yes, got this now in revolution branch, works OK ta
