### ISSUE TITLE
New PHPMailer

### ISSUE THREAD

**Issue by Paprikas** [modxbot/migrate#1417]
paprikas created Redmine issue ID 1417

Update phpmailer class.
 http://phpmailer.codeworxtech.com/index.php?pg=sf&p=dl
And remove phpmailer.lang-ru.php file. (english is already included to phpmailer).
Dunno how to properly include both versions of phpmailer (for 4 and later php versions).

**Comment by Paprikas** [comment]
paprikas submitted:

oops.
Not phpmailer.lang-RU.php file
phpmailer.lang-en.php

**Comment by splittingred** [comment]
splittingred submitted:

What is this for?

**Comment by Paprikas** [comment]
paprikas submitted:

Is it bad, to have the actual version?
 http://phpmailer.worxware.com/index.php?pg=changelog Version 5.0.2 (May 24, 2009) Fix for missing attachments when inline graphics are present Fix for missing Cc in header when using SMTP (mail was sent,
but not displayed in header &#8211; Cc receiver only saw email To:
line and no Cc line, but did get the email (To receiver
saw same) Version 5.0.1 (April 05, 2009) Temporary fix for missing attachments Version 5.0.0 (April 02, 2009) With the release of this version, we are initiating a new version numbering
system to differentiate from the PHP4 version of PHPMailer. Most notable in this release is fully object oriented code.
class.smtp.php: Refactored class.smtp.php to support new exception handling
code size reduced from 29.2 Kb to 25.6 Kb Removed unnecessary functions from class.smtp.php:
public function Expand($name) {
public function Help($keyword="") {
public function Noop() {
public function Send($from) {
public function SendOrMail($from) {
public function Verify($name) {
class.phpmailer.php: Refactored class.phpmailer.php with new exception handling Changed processing functionality of Sendmail and Qmail so they cannot be
inadvertently used removed getFile() function, just became a simple wrapper for
file_get_contents() added check for PHP version (will gracefully exit if not at least PHP 5.0)
class.phpmailer.php enhancements enhanced code to check if an attachment source is the same as an embedded or
inline graphic source to eliminate duplicate attachments
New /test_script We have written a test script you can use to test the script as part of your
installation. Once you press submit, the test script will send a multi-mime
email with either the message you type in or an HTML email with an inline
graphic. Two attachments are included in the email (one of the attachments
is also the inline graphic so you can see that only one copy of the graphic
is sent in the email). The test script will also display the functional
script that you can copy/paste to your editor to duplicate the functionality.
New examples All new examples in both basic and advanced modes. Advanced examples show
Exception handling.
PHPDocumentator (phpdocs) documentation for PHPMailer version 5.0.0 all new documentation

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5462

**Comment by Paprikas** [comment]
paprikas submitted:

what about evo?
