### ISSUE TITLE
User groups not removed on package uninstallation

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1419]
shamblett created Redmine issue ID 1419

If a usergroup is created in a packaging script, like :- $usergroup = $modx->newObject('modUserGroup');
$usergroup->fromArray(array(
'name' => 'Provisioner',
'parent' => 0
), '', true); $attr = array(
XPDO_TRANSPORT_PRESERVE_KEYS => false,
XPDO_TRANSPORT_UPDATE_OBJECT => true,
XPDO_TRANSPORT_UNIQUE_KEY => array ('name')); $vehicle = $builder->createVehicle($usergroup, $attr);
$vehicles[] = $vehicle; It is not removed when the package is uninstalled.

**Comment by splittingred** [comment]
splittingred submitted:

Can't duplicate. Should also be: <?php $usergroup= $xpdo->newObject('modUserGroup'); $usergroup->fromArray(array ( 'id' => 1, 'name' => 'Provisioner', 'parent' => 0, ), '', true , true );
