### ISSUE TITLE
Property description not updated in grid on save

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1423]
bobray created Redmine issue ID 1423

If you update the description of a property in a property set the dirty flag isn't set and after you save the set, the description doesn't change until you navigate away to another set, then come back. All the other fields update immediately and set the dirty flag. The changed description is saved, it just doesn't show until you go away and come back which could make users thing the change hasn't stuck.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6075

**Comment by BobRay** [comment]
bobray submitted:

Confirmed Fixed.
