### ISSUE TITLE
Proposed changes to Package Management/Retriever grid

### ISSUE THREAD

**Issue by kongondo** [modxbot/migrate#1429]
kongondo created Redmine issue ID 1429

Package Retriever 1. At the moment, it is a bit tedious looking for new packages to add/install. There is a lot of categories and folders to click through just to check for new packages. Is it possible to change the "Package Retriever" so that it is similar to the "Packages Management" grid? See link prototype PROTOTYPE: http://i414.photobucket.com/albums/pp228/kongondo/proposed_package_retriever_revo.png 2. In the "Package Retriever" window, when no packages are selected and you click Finish, before the error window pops up, you briefly get the "please wait downloading" window. Is it possible to detect that no package has been selected and hence pop-up the error window directly? Package Management 1. In the "Package Management" grid, the first column showing the name of the package is titled "signature". I am sure technically it means something but am thinking, would it be better to rename this to "package name" or something more descriptive? 2. Is it possible to have a universal "check for updates button" to simultaneously check for updated versions of installed packages (ala firefox addons' update checker)..and maybe highlight packages that have updates? This would save right-clicking each package when checking for updates. Many thanks
/k

**Comment by splittingred** [comment]
splittingred submitted:

PR:
1. This solution would be problematic when the Repository grows - there might be thousands of packages available for download. A grid simply isn't feasible there.
2. Yes. Will look into a sanity check. PM:
1. Yes, I'll look into it.
2. Maybe - this could get complex (queueing/order of updates, etc) and we may want to push that till 2.0.1, but I'll look into it.

**Comment by kongondo** [comment]
kongondo submitted:

Shaun, That's a good point (PR 1.). Thanks. /kongondo

**Comment by splittingred** [comment]
splittingred submitted:

Updates made in r5445. Please refile batch update proposal into separate ticket; probably wont be able to do that until 2.0.1.
