### ISSUE TITLE
Can disabling a plugin in "Package Management" be synchronised to disabling it in the plugin edit page?

### ISSUE THREAD

**Issue by kongondo** [modxbot/migrate#1430]
kongondo created Redmine issue ID 1430

If a plugin is disabled in "Package Management", and not disabled in the plugin edit page, the plugin still works - i.e. it is not disabled. Is there a way to synchronise the two? Otherwise, what does disabled in "Package Management" mean/do? Tested with "captcha" plugin Thanks
/kongondo

**Comment by splittingred** [comment]
splittingred submitted:

Gone ahead in r5446 to remove Disabled from Package grid since it's functionality is not currently worked out and is not really applicable at this time.
