### ISSUE TITLE
Clicking "collapse tree" icon in "Package Retriever" window makes the packages listing disappear

### ISSUE THREAD

**Issue by kongondo** [modxbot/migrate#1431]
kongondo created Redmine issue ID 1431
1. a) Clicking "collapse tree" icon in "Package Retriever" window makes the packages listing disappear and shifts the "more info window/pane" to the right (see screen). Clicking on Finish will pop up the error window "please select at least one package.....". Clicking the Back button and then Next doesn't help. One has to close the "Package Retriever" window, refresh the browser window and start all over again. b) Clicking on "expand tree" icon in "Package Retriever" window does nothing. Screen:
   http://i414.photobucket.com/albums/pp228/kongondo/bug_collapse_tree_pckg_retriever_re.png Thanks
   /kongondo

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5445
