### ISSUE TITLE
"Manage User Groups and Roles" page heading is "Access Permissions"

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1435]
bobray created Redmine issue ID 1435

It looks like the main menu choice goes to the right screen but the heading is wrong. Also - Clicking on "New User Group" leads to a completely blank right panel.

**Comment by BobRay** [comment]
bobray submitted:

The Heading is fixed, but clicking on "New User Group" still leads to a completely blank right panel in FF3.5 Vista.

**Comment by splittingred** [comment]
splittingred submitted:

Ack, missed that. Fixed in r5457.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed. FF 3.5.
