### ISSUE TITLE
ExtJS Error when trying to create template.

### ISSUE THREAD

**Issue by anasmughal** [modxbot/migrate#1438]
anasmughal created Redmine issue ID 1438

Got the following ExtJS error when tried to create my first template in Revolotion Beta1.
I got this error when I clicked on the save button. too much recursion
? in ext-all.js@52(Object success=false message=User not specified. total=0)ext-all.js (line 52)
? in ext-all.js@52(Object tId=4 status=200 statusText=OK)ext-all.js (line 52)
? in ext-all.js@50(Object params=Object request=Object reader=Object, true, Object tId=4 status=200 statusText=OK)ext-all.js (line 50)
? in ext-base.js@9(function(), Object events=Object conn=Object useAjax=true, &#91;Object params=Object request=Object reader=Object, true, Object tId=4 status=200 statusText=OK 0=Object 1=true 2=Object&#93; , undefined)ext-base.js (line 9)
? in ext-all.js@17(Object tId=4 status=200 statusText=OK)ext-all.js (line 17)
? in ext-base.js@10(Object tId=4, Object scope=Object argument=Object timeout=30000, undefined)ext-base.js (line 10)
? in ext-base.js@10()ext-base.js (line 10)
 &#91;Break on this error&#93; (no source for http://localhost/modx200b1a/manager/assets/ext2/ext-all.js ) And, below it, I also got the error: Ext.getCmp("template-header") is undefined
fn()()modx.pan...mplate.js (line 58)
EventManager()()ext-all.js (line 12)
EventManager()()ext-all.js (line 12)
onResize()(Object browserEvent=Event blur button=-1 type=blur)ext-all.js (line 124)
h()()eventfix.js (line 192)
getViewWidth()()ext-base.js (line 10)
 &#91;Break on this error&#93; Ext.getC...('template') ': '+f.getValue() '</h2>');

**Comment by splittingred** [comment]
splittingred submitted:

What browser + version? And is this beta-2 or beta-1?

**Comment by splittingred** [comment]
splittingred submitted:

Closing ticket until more details are provided; cannot reproduce this behavior at all.
