### ISSUE TITLE
Install ignores "next" button with no error message.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1455]
bobray created Redmine issue ID 1455

I'm not sure how this is possible, but I had this on more than one install. On the Connection Information screen, "Check database connection" reported success but the "Next" button didn't do anything. I believe the problem was related to upgrading XAMPP or and/or an issue in the cache directory &#8211; I no longer have the problem (I hope). It went away when I recreated the MODx DB user in phpmyadmin. I wonder if something in the cache directory led to the successful report even though the DB connection wasn't made. I believe that when this happened, the DB user that MODx used no longer existed, but setup reported a successful connection to the DB. Another possibility is that the connection test depends on the existence of the DB, but doesn't try a query.

**Comment by splittingred** [comment]
splittingred submitted:

This was due to a changing of the cache format. It has been resolved and wont happen again - we issued a notice in the forums about it a while back.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed
