### ISSUE TITLE
Misleading report in build

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1457]
bobray created Redmine issue ID 1457

transport.core.php reports: "Removed pre-existing core/ and core.transport.zip" whether they were removed or not. They're not removed on Vista (I usually remove them manually before the build) but the script doesn't check for success of the removal attempt.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5856

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
