### ISSUE TITLE
Streamline Package Manager

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1458]
bobray created Redmine issue ID 1458

Once a provider has been selected, it shouldn't take so many steps to get to the repository. Click on add a package
Click on Select a provider
Click on Next
Click on the down arrow
Click on the provider
Click on Next Let the user designate a default provider and add "Go to default provider" as the default option on the "Package Retriever" dialog (if one has been designated). Go directly to the repository from there if that option is selected. If having a default provider isn't feasible, add radio buttons for all the providers on the "Package Retriever" dialog and go directly to the one selected. I don't think "Add a new Provider" is necessary on the "Package Retriever" dialog or the one after that unless no providers have been registered since it's available on the main screen. Or how about a button on the main screen: Go to Main Repository that bypasses all the steps. BTW, http://modxcms.com/assets/provider.js no longer shows up in a new install for me as a provider and even after adding it, it doesn't show up in the "select a provider" dialog.

**Comment by splittingred** [comment]
splittingred submitted:

Bob, I don't know why you're not getting the default provider in install. I'm assuming it has something to do with the xPDOZip problems you're having in the other issue. With regards to this issue, I can definitely have either a 'Go to Default Provider' option or a 'Go to Main Repository' button. Which would you prefer?

**Comment by BobRay** [comment]
bobray submitted:

Could be. I'm also getting a login screen with no submit button now. >>'Go to Default Provider' option or a 'Go to Main Repository' button. Which would you prefer? That's a tough call. It kind of depends on how many repositories will be out there. I think 'Go to Main Repository' would probably be best and easiest, although if 'Go to Default Repository' sent them to the Main Repository if no default one were designated or no repositories were on the list, that might be better.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5396. Added a "Download Extras" button.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed and what a treat to use!
