### ISSUE TITLE
Error building transport core 

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1459]
shamblett created Redmine issue ID 1459

SVN r5388, XPDO r341 After todays(large) update am getting this error on building the transport.core.php :- &#91;2009-07-15 09:34:51&#93; (INFO @ /revolution/_build/transport.core.php) Beginning build script processes...
 &#91;2009-07-15 09:34:51&#93; (INFO @ /revolution/_build/transport.core.php) Removed pre-existing core/ and core.transport.zip.
 &#91;2009-07-15 09:34:52&#93; (INFO @ /revolution/_build/transport.core.php) Core transport package created.
 &#91;2009-07-15 09:34:52&#93; (INFO @ /revolution/_build/transport.core.php) Default workspace packaged.
 &#91;2009-07-15 09:34:52&#93; (INFO @ /revolution/_build/transport.core.php) Packaged in modxcms.com provisioner reference.
 &#91;2009-07-15 09:34:52&#93; (INFO @ /revolution/_build/transport.core.php) Packaged all modActions.
 &#91;2009-07-15 09:34:52&#93; (INFO @ /revolution/_build/transport.core.php) Packaged all modMenus.
 &#91;2009-07-15 09:34:52&#93; (INFO @ /revolution/_build/transport.core.php) Packaged all default modContentTypes.
 &#91;2009-07-15 09:34:52&#93; (INFO @ /revolution/_build/transport.core.php) Packaged in web context.
 &#91;2009-07-15 09:34:55&#93; (INFO @ /revolution/_build/transport.core.php) Packaged in mgr context.
 &#91;2009-07-15 09:34:55&#93; (INFO @ /revolution/_build/transport.core.php) Packaged in connectors.
 &#91;2009-07-15 09:34:56&#93; (INFO @ /revolution/_build/transport.core.php) Packaged all default events.
 &#91;2009-07-15 09:34:56&#93; (INFO @ /revolution/_build/transport.core.php) Packaged all default system settings.
 &#91;2009-07-15 09:34:56&#93; (INFO @ /revolution/_build/transport.core.php) Packaged all default context settings.
 &#91;2009-07-15 09:34:56&#93; (INFO @ /revolution/_build/transport.core.php) Packaged in default user groups.
 &#91;2009-07-15 09:34:56&#93; (INFO @ /revolution/_build/transport.core.php) Packaged in default roles Member and SuperUser.
 &#91;2009-07-15 09:34:56&#93; (INFO @ /revolution/_build/transport.core.php) Packaged in default access policies.
 &#91;2009-07-15 09:35:03&#93; (INFO @ /revolution/_build/transport.core.php) Packaged core lexicon entries and topics.
 &#91;2009-07-15 09:35:03&#93; (INFO @ /revolution/_build/transport.core.php) Packaged in default access context permissions.
 &#91;2009-07-15 09:35:03&#93; (INFO @ /revolution/_build/transport.core.php) Beginning to zip up transport package... ( ! ) Fatal error: Call to undefined method xPDOZip::errorInfo() in /var/www/html/local/revolution/core/xpdo/transport/xpdotransport.class.php on line 302
Call Stack Time Memory Function Location
1 0.0384 184248 {main}( ) ../transport.core.php:0
2 11.8208 6229316 xPDOTransport->pack( ) ../transport.core.php:472
3 11.8514 6229312 xPDOTransport->_pack( ) ../xpdotransport.class.php:284

**Comment by splittingred** [comment]
splittingred submitted:

Seems to be an issue with ZipArchive. Until Jason gets up and fixes it, you can add this function to the xPDOZip class: public function errorInfo() {
return print_r($this->_errors,true);
}

**Comment by shamblett** [comment]
shamblett submitted:

OK, ta, now getting this :- 2009-07-15 15:14:39] (ERROR @ /revolution/_build/transport.core.php) Error packing /var/www/html/local/revolution/core/packages/core to /var/www/html/local/revolution/core/packages/core.transport.zipArray
(
) with no transport core zip Seems to come from line 78 of xpdozip class

**Comment by splittingred** [comment]
splittingred submitted:

Try r5397.

**Comment by shamblett** [comment]
shamblett submitted:

Still the same, also same at my latest revision which is r5408

**Comment by splittingred** [comment]
splittingred submitted:

Steve, you're still getting xPDOZip errors? That's not even in the code anymore - you sure you did a full update? My skype is splittingred, if you're still having problems. Might need to live-time debug this.

**Comment by shamblett** [comment]
shamblett submitted:

Ok Shaun, If I do a full SVN revert local changes which gets rid of the little hack above I go back to this :- ( ! ) Fatal error: Call to undefined method xPDOZip::errorInfo() in /var/www/html/local/revolution/core/xpdo/transport/xpdotransport.class.php on line 302
Call Stack Time Memory Function Location
1 0.0432 184256 {main}( ) ../transport.core.php:0
2 13.1694 6229316 xPDOTransport->pack( ) ../transport.core.php:472
3 13.1774 6229312 xPDOTransport->_pack( ) ../xpdotransport.class.php:284 SVN swears blind I'm in sync with head at r5411. Let me try this on another machine just to rule out this one box, I'll get back to you

**Comment by splittingred** [comment]
splittingred submitted:

Try a svn cleanup on the branch. It seems your SVN externals reference to xPDO is not updating - that line that is erroring is commented out, and shouldn't be running at all. Once you've run cleanup, try svn update again, from the root. If that doesnt work, try going to the core/xpdo dir and svn updating from there.

**Comment by opengeek** [comment]
opengeek submitted:

Shamblett: is this from branches/revolution or branches/2.0 ? The fix to the xPDOZip problem is currently only in branches/2.0, but I'll be merging it down to branches/revolution this afternoon in preparation for beta2 release.

**Comment by shamblett** [comment]
shamblett submitted:

I use the branches/revolution repo not the branches/2.0. I keep an eye on the rss feeds coming out of fisheye but Its sometimes difficult to see what exactly has gone into a merge push from 2.0 to revolution. I think this is where some confusion is creeping in with Shaun on the get/getlist processors bugs I've raised. He's fixed the stuff I wanted doing but I think this is in in the 2.0 branch still, hence I cant see it. Its not a prob, I know it will emerge eventually.

**Comment by shamblett** [comment]
shamblett submitted:

Ok, updated to r5423, beta 2 now, all good on the rebuild/upgrade. Looks OK now.

**Comment by BobRay** [comment]
bobray submitted:

This is odd, but I thought I should report it. I got the errors on the latest build when running transport.core.php from inside NetBeans. I tried switching the System Setting, but still got errors. Then I tried from inside PhpEdit and the build went fine. I don't know what it means but this bug may still be around for some folks.
