### ISSUE TITLE
Changing a resource's parent leaves two copies in the Resource tree

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1467]
bobray created Redmine issue ID 1467

After changing the resource's parent on the Create/Edit Resource panel and saving the resource, the resource shows in both its old and new position in the tree. Refreshing the tree or clearing the cache corrects it.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5859

**Comment by BobRay** [comment]
bobray submitted:

Still seeing this in r5917 (FF 3.5.3).

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed r6009.
