### ISSUE TITLE
Using Duplicate with right click from tree, it's possible to create multiple resources with the same title

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1469]
bobray created Redmine issue ID 1469

If you enter a duplicate name in the name field, a new resource is created with the identical name.

**Comment by splittingred** [comment]
splittingred submitted:

This isn't really a bug - sometimes you might want to do this. (multiple resources with diff aliases, other fringe cases)

**Comment by BobRay** [comment]
bobray submitted:

won't fix
