### ISSUE TITLE
Can't enter name in Duplicate Resource

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1470]
bobray created Redmine issue ID 1470

When duping a resource by right-clicking in the tree, the field for entering the new name is dead.

**Comment by BobRay** [comment]
bobray submitted:

It appears that this is only true for resources that have children.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5356

**Comment by BobRay** [comment]
bobray submitted:

Still dead for me in FF3/Vista when duping any container document with right click.

**Comment by BobRay** [comment]
bobray submitted:

Only a problem for containers now. Will open new issue.
