### ISSUE TITLE
wordwrap filter doesn't work

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1475]
bobray created Redmine issue ID 1475

The third argument of wordwrap is the string to used terminate broken lines, not the character to break at (which, I think, is any whitespace &#8211; no choice on that). In core/model/modx/filters/modoutputfilter.class.php &#8211; instead of $output= wordwrap($output, $wrapat, " ", 1); The code should be either: $output= wordwrap($output, $wrapat, "<br />/n ", 1); or $output= wordwrap($output, $wrapat, "/n ", 1); If we used the former, nl2br wouldn't be necessary as an adjunct filter (though it would limit the use of wordwrap to web rendering). It might also be good to have two versions of wordwrap with the fourth argument 0 and 1 to give the option of not forcing the breaking of long words.
e.g.: wordwrap (cut = 0)
wordwrapcut (cut=1)

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5361.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
