### ISSUE TITLE
output filter isinrole and ismember of issue

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1483]
bobray created Redmine issue ID 1483

Not sure about this one, but in core/model/modx/filters/modinputfilter.class.php isinrole is an alias of memberof and mo and for all three there's a call to isMemberOfWebGroupByUserId(). Do we even have web groups any more? And what would being in a web group have to do with having a particular role?

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5864

**Comment by BobRay** [comment]
bobray submitted:

Taking Shaun's word for it &#8211; don't know how to test this.
