### ISSUE TITLE
Can't add resources to resource group

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1484]
bobray created Redmine issue ID 1484

I can't find any way of adding resources to a resource group. Dragging and dropping doesn't work.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5338

**Comment by BobRay** [comment]
bobray submitted:

I can add resources to groups now, but MODx hangs every time with the "please wait - saving" progress bar on the screen. The progress bar is complete, but won't go away. If I reload the page, the resource has been added.

**Comment by BobRay** [comment]
bobray submitted:

No longer happening with FF 3.5.1. Closing.
