### ISSUE TITLE
Changes to output filters

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1485]
bobray created Redmine issue ID 1485

There's some seemingly wrong processing in the lt, gt, el, eg, section. Lowerthan is processed as less than or equal to. isgt and isgreaterthan are processed as greater than or equal rather than is greater than etc. Even if this is legacy code, it should be corrected, IMO. I suggest the following for that section (I'm ambivalent about the longer aliases for lte and gte): case "gt:":
case "isgt" :
case "greaterthan":
case "isgreaterthan" :
$condition[]= intval(($output > $m_val));
break; case "lt":
case "islt":
case "lessthan":
case "lowerthan":
case "islessthan":
case "islowerthan": $condition[]= intval(($output < $m_val));
break; case "gte":
case "isgte":
case "eg" :
case "ge":
case "equalorgreaterthan":
case "greaterthanorequalto":
$condition[]= intval(($output >= $m_val));
break; case "lte":
case "islte":
case "el" :
case "le":
case "lesthanorequalto":
case "equaltoorlessthan":
$condition[]= intval(($output <= $m_val));
break;

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5361.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
