### ISSUE TITLE
Prevent user from returning $tag in a custom filter.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1488]
bobray created Redmine issue ID 1488

Putting the following code in a custom output filter will crash Apache: return $tag; It creates infinite recursion for obvious reasons. Someone creating a custom filter might try to use it for debugging like I did. It might be worth short-circuiting if there's an easy way to do it.

**Comment by splittingred** [comment]
splittingred submitted:

Changing to a feature request.
