### ISSUE TITLE
String Literal encoding need for file tree

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1492]
shamblett created Redmine issue ID 1492

r5266 of the file core\model\modx\processors\resource\getnodes.php added an extra parameter to encode the output as string literals, the same needs to be done in file core\model\modx\processors\browser\directory\getlist.php to allow the file tree to be decoded correctly.

**Comment by shamblett** [comment]
shamblett submitted:

There is another issue here as well with the 'prependPath' parameter. Line 32 does this :-
$modx->getOption('base_path').$modx->getOption('rb_base_dir'); ie the root path depends upon base_path and rb_base_dir, not just rb_base_dir as the header comment suggests. rb_base_dir is in the core system settings but base_path isn't. Also, can the $fullname variable be included in the outgoing data set. This would allow this variable to be passed straight to the /browswer/file/get processor which expects an absolute file path.

**Comment by splittingred** [comment]
splittingred submitted:

$fullname is accessible via the property 'pathname'. And stringLiterals isn't an issue here, since it uses $modx->toJSON, not $this->toJSON

**Comment by shamblett** [comment]
shamblett submitted:

Ok Shaun, Maybe we are looking at different things here but my version of \modx\processors\browser\directory\getlist.php on line 120 has this return $this->toJSON($ls); hence the need for string literals. This is r5337 in my installation, Ok, so is this fixed in branches/2.0 and I just have to wait for it to arrive? Also, what do you mean by 'property', is it a js property of a node such as var node = this.cm.activeNode;
pathname = node.pathname

**Comment by shamblett** [comment]
shamblett submitted:

'
And stringLiterals isn't an issue here, since it uses $modx->toJSON, not $this->toJSON
'
On my revision r5408 it still uses $this->toJSON, hence I can't decode it

**Comment by shamblett** [comment]
shamblett submitted:

Still seeing this om my r5423, beta 2 version, may have got lost somewhere.
