### ISSUE TITLE
Site Status system setting description doesn't match value

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1495]
bobray created Redmine issue ID 1495

The value of the site_status system setting displays as "yes" or "no" but the instructions in the description say to set it to "online" or "offline." Either the displayed value or the instructions need to change.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6149

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
