### ISSUE TITLE
"clear filter" has to be clicked twice in system settings grid

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1496]
bobray created Redmine issue ID 1496

If you search for a keyword (e.g. "user"). Then click on "Clear Filter" nothing happens until you click again. I also observed a condition where clearing the filter led to an empy grid (even thought the filter field was blank). I couldn't get the grid to repopulate, even after I reslected the core namespace. The only way to bring the grid entries back was to use System | System Settings on the main menu. Unfortunately, I haven't found a way to duplicate this, although it definitely happened.

**Comment by splittingred** [comment]
splittingred submitted:

Duplicate of MODX-1356

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
