### ISSUE TITLE
Funky error log scroll bar

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1500]
bobray created Redmine issue ID 1500

With many entries in the error log, the range of the scroll bar seems to be tied to the number of entries, but it doesn't scroll them. It scrolls the window containing the error log window. You can scroll for a long time after the log itself is no longer visible.. The only way to to see log entries that are off the screen initlially is to scroll manually with the keyboard or scroll wheel on the mouse. It would also be nice to have buttons to jump to the end or beginning.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6073

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
