### ISSUE TITLE
Provide loading of basic JS libraries via MODx API

### ISSUE THREAD

**Issue by atma** [modxbot/migrate#1505]
atma created Redmine issue ID 1505

Provide loading of basic JS libraries via MODx API such as http://code.google.com/apis/ajaxlibs/ ... $modx->regClientStartupScript('jquery', '1.3.2', 'min'); //or distribute JS collection with MODx core For example WP have some implementation of this - http://codex.wordpress.org/Function_Reference/wp_enqueue_script#Example

**Comment by splittingred** [comment]
splittingred submitted:

We've decided we dont want to have to maintain an unknown number of JS libraries, nor be liable for them. Someone could easily create a Plugin or Snippet to do this, so closing this ticket.
