### ISSUE TITLE
Element 'get' processors - parameter checks incorrect

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1508]
shamblett created Redmine issue ID 1508

The following element 'get' processors use 'if (!isset($_POST &#91;&#39;id&#39;&#93; ))' to check incoming parameters, chunk
plugin
tv others eg template use 'if (empty($_REQUEST &#91;&#39;id&#39;&#93; ))' I believe the $REQUEST method should be used across all these types of processors to check parameters, not $POST This means that remote callers need to encode a POST request for some processors but not for others.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5311. All get\* based processors use REQUEST. Any processor that explicitly modifies data, such as create/remove/update, must use POST.

**Comment by shamblett** [comment]
shamblett submitted:

OK, I have r5311, the file core\model\modx\processors\element\plugin\get.php still has this in it :- if (empty($_POST &#91;&#39;id&#39;&#93; ) on line 15 Its last 3 logs read :- Revision: 5153
Author: splittingred
Date: 18:33:33, 18 June 2009
Message:
 &#91;merge -r5117:5152 http://svn.modxcms.com/svn/tattoo/tattoo/branches/2.0&#93;
 &#91;REBUILD/UPGRADE REQUIRED&#93; Revision: 4553
Author: splittingred
Date: 18:11:38, 15 December 2008
Message:
 &#91;LEXICON RELOAD REQUIRED&#93; Added UI for managing property sets to each element page Added ability to assign property sets to an element Added 'Revert' option to property grid on properties that have been overridden in a set Revision: 4425
Author: splittingred
Date: 16:01:51, 14 November 2008
Message: LOTS of phpdoc additions to all processors, including parameter lists for each processor Revision: 4418
Author: splittingred
Date: 20:01:13, 13 November 2008
Message: Removed "require_once MODX_PROCESSORS_PATH.'index.php';" from all processors Moved code in that index.php to request layer, where it should be Revision: 4373
Author: opengeek
Date: 19:04:53, 28 October 2008
Message: Refactored modError completely, removing all derivative classes and introducing modManagerResponse and modConnectorResponse to handle formatting modError responses appropriately. NOTE that all calls to $modx->error->success() and $modx->error->failure() must now be returned explicitly from all processors and controllers and formatted/rendered by a modResponse derivative (defined in modRequest derivatives or in a setting for modResponse.class that can be provided by context).
 &#91;REBUILD AND UPGRADE RECOMMENDED&#93;
