### ISSUE TITLE
[[*createdon]] prints all zeros

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1509]
bobray created Redmine issue ID 1509

[ &#91;_createdon&#93; ] displays 0000-00-00 00:00:00
[ &#91;_createdon:date=`Y`&#93; ] displays nothing.

**Comment by splittingred** [comment]
splittingred submitted:

Createdon value setting was fixed priorly in SVN. For date filter, see MODX-885 .

**Comment by BobRay** [comment]
bobray submitted:

Sorry, different issue. The createdon field in the DB is blank for a number of resources. Doesn't seem to be happening any more.
