### ISSUE TITLE
Date output filter prints 1969

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1510]
bobray created Redmine issue ID 1510

[ &#91;_editedon:date=`%Y`&#93; ] displays 1969. [ &#91;_editedon&#93; ] prints the correct date.

**Comment by splittingred** [comment]
splittingred submitted:

That's because datetime values like [ &#91;_editedon&#93; ] return a formatted date rather than the unix timestamp - date takes in a timestamp. To use formatting, do: [ &#91;_editedon:strftime:date=`Y`&#93; ]

**Comment by BobRay** [comment]
bobray submitted:

In FF3 for me (r5310 branches/2.0): [ &#91;_editedon&#93; ] prints the correct full date
[ &#91;_editedon:strftime:date=`Y`&#93; ] prints Y
[ &#91;*editedon:strftime:date=`%Y`&#93; ] prints 1969

**Comment by adamcrown** [comment]
adamcrown submitted:

It should be [ &#91;*editedon:strtotime:date=`%Y`&#93; ]. That's strTOtime not strFtime

**Comment by BobRay** [comment]
bobray submitted:

Right. Closing this (nothing to fix).
