### ISSUE TITLE
ucfirst output filter doesn't work

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1511]
bobray created Redmine issue ID 1511

ucfirst() only takes one argument and is getting two so it produces no output.
Current code: if (empty($m_val))
$m_val = false;
$output= ucfirst($output, m_val);
break; Should be: $output=ucfirst($output);
break; While you're there, we should probably add ucwords(): case "ucwords": $output = ucwords($output);
break;

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5307

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
Tested ucwords - OK
