### ISSUE TITLE
Funky behavior of Create another/Keep editing/Close buttons

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1516]
bobray created Redmine issue ID 1516

If you click on "create another" while editing a template variable, it seems to be set for all other elements and has to be turned off for each one individually (either that or it's too sticky). Worse yet, when you get the new blank form for the new element, it looks like you can't turn it off (set it to "keep editing" without either creating an element and saving it, or cancelling and editing another element of that type and saving it. Molto annoying. I don't know if it's possible, but clicking on the one of the buttons should probably set the value immediately either just for that element type, or for all element types consistently.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6363; stay options now action-specific (page-specific) and done through ExtJS state management rather than the PHP sessions

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
