### ISSUE TITLE
Fix confusing TV permission message

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1517]
bobray created Redmine issue ID 1517

This message appears on the Create/Edit TV panel's Access Permissions tab. "Select the resource groups that are allowed to modify the content or value of this Template Variable." I don't understand the new permissions system but a "resource group" should be a group of resources and there's no way that a group of resources is going to be editing a TV. I'll take a wild guess and suggest that it should say something like this: Select the resource groups that this Template Variable belongs to. Only users with access to the groups selected will be able to modify this TV. If no groups are selected, all users with access to the Manager will be able to modify the TV.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6585

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
