### ISSUE TITLE
System settings grid search not working

### ISSUE THREAD

**Issue by doze** [modxbot/migrate#1526]
doze created Redmine issue ID 1526

Steps to reproduce: 1. Go to System settings grid
2. Write keyword to the search field and hit enter
3. The grid is reloaded, but without search
4. Click focus away from the search text field
5. Grid is reloaded with search term results So the search keyword is not POSTing on enter, but it is onBlur.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5293
