### ISSUE TITLE
Cannot set root as parent for the document

### ISSUE THREAD

**Issue by doze** [modxbot/migrate#1536]
doze created Redmine issue ID 1536

When creating the first document, I cannot set the parent for the document to be the root folder. Steps: 1. Right click on "web" and select Create > Create a Document Here
2. Open the select list for "Parent Resource"
3. Text appears "Please select a node in the tree to the left." and the Web Resources panel is expanded.
4. If you click to the root (context) folder i.e. "web", you get a popup message saying: "The resource cannot be its own parent" So issues with this: 1. I'm not setting the resource to be its own parent, eg. the error message is wrong
2. It should set the root folder as the parent

**Comment by splittingred** [comment]
splittingred submitted:

Seems to have been already fixed; works now.
