### ISSUE TITLE
The key is displayed from select lists items by default and not the item text when creating a new document

### ISSUE THREAD

**Issue by doze** [modxbot/migrate#1537]
doze created Redmine issue ID 1537

Some select list values are displayed by their key values by default in the "new document" view. Content type: 1 (although there are CSS, HTML, etc.. values in the select list and HTML is marked as selected)
Uses Template: 1 (I have only (empty) available for the values, because I have not added any templates) Should be: Content type: HTML
Uses Template: no value

**Comment by splittingred** [comment]
splittingred submitted:

Duplicate of # MODX-649
