### ISSUE TITLE
Installation problems with Revo SVN 5223

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1540]
shamblett created Redmine issue ID 1540

The build.transport.core script outputs the following :- &#91;2009-06-28 17:56:38&#93; (INFO @ /revdevremote/_build/transport.core.php) Beginning build script processes...
 &#91;2009-06-28 17:56:39&#93; (INFO @ /revdevremote/_build/transport.core.php) Removed pre-existing core/ and core.transport.zip.
 &#91;2009-06-28 17:56:39&#93; (INFO @ /revdevremote/_build/transport.core.php) Core transport package created.
 &#91;2009-06-28 17:56:39&#93; (INFO @ /revdevremote/_build/transport.core.php) Default workspace packaged.
 &#91;2009-06-28 17:56:39&#93; (ERROR @ /revdevremote/_build/transport.core.php) Error 42S02 executing statement:
Array
(
 &#91;0&#93; => 42S02
 &#91;1&#93; => 1146
 &#91;2&#93; => Table 'revdevremote.modx_transport_providers' doesn't exist
) &#91;2009-06-28 17:56:39&#93; (INFO @ /revdevremote/_build/transport.core.php) Created table`modx_transport_providers`
SQL: CREATE TABLE `modx_transport_providers` (`id` INTEGER unsigned NOT NULL AUTO_INCREMENT,`name` VARCHAR(255) NOT NULL,`description` MEDIUMTEXT NULL,`service_url` TINYTEXT NULL,`created` DATETIME NOT NULL,`updated` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`), UNIQUE INDEX `name` (name)) TYPE=MyISAM &#91;2009-06-28 17:56:39&#93; (INFO @ /revdevremote/_build/transport.core.php) Packaged in modxcms.com provisioner reference.
 &#91;2009-06-28 17:56:39&#93; (INFO @ /revdevremote/_build/transport.core.php) Packaged all modActions.
 &#91;2009-06-28 17:56:40&#93; (INFO @ /revdevremote/_build/transport.core.php) Packaged all modMenus.
 &#91;2009-06-28 17:56:40&#93; (INFO @ /revdevremote/_build/transport.core.php) Packaged all default modContentTypes.
 &#91;2009-06-28 17:56:40&#93; (INFO @ /revdevremote/_build/transport.core.php) Packaged in web context.
 &#91;2009-06-28 17:56:42&#93; (INFO @ /revdevremote/_build/transport.core.php) Packaged in mgr context.
 &#91;2009-06-28 17:56:43&#93; (INFO @ /revdevremote/_build/transport.core.php) Packaged in connectors.
 &#91;2009-06-28 17:56:43&#93; (INFO @ /revdevremote/_build/transport.core.php) Packaged all default events.
 &#91;2009-06-28 17:56:44&#93; (INFO @ /revdevremote/_build/transport.core.php) Packaged all default system settings.
 &#91;2009-06-28 17:56:44&#93; (INFO @ /revdevremote/_build/transport.core.php) Packaged all default context settings.
 &#91;2009-06-28 17:56:44&#93; (INFO @ /revdevremote/_build/transport.core.php) Packaged in default user groups.
 &#91;2009-06-28 17:56:44&#93; (INFO @ /revdevremote/_build/transport.core.php) Packaged in default roles Member and SuperUser.
 &#91;2009-06-28 17:56:44&#93; (INFO @ /revdevremote/_build/transport.core.php) Packaged in default access policies.
 &#91;2009-06-28 17:56:56&#93; (INFO @ /revdevremote/_build/transport.core.php) Packaged core lexicon entries and topics.
 &#91;2009-06-28 17:56:56&#93; (INFO @ /revdevremote/_build/transport.core.php) Packaged in default access context permissions.
 &#91;2009-06-28 17:56:56&#93; (INFO @ /revdevremote/_build/transport.core.php) Beginning to zip up transport package...
 &#91;2009-06-28 17:57:02&#93; (INFO @ /revdevremote/_build/transport.core.php) Transport zip created. Build script finished. The database contains the created table modx_transport_providers and no others. When pressing 'next' on the welcome screen I get a blank page, nothing in firebug, nothing in apache error log, apache access log shows a 200 response with nothing returned, nothing in the core/error directory

**Comment by shamblett** [comment]
shamblett submitted:

OK, commenting out line 5 of the options.php controller allows the install to continue, //$this->parser->assign('installmode',$install->getInstallMode()); getting this on the installation summary page :- ( ! ) Warning: PDO::query() &#91;pdo.query&#93; : SQLSTATE &#91;42S02&#93; : Base table or view not found: 1146 Table 'revdevremote.modx_system_settings' doesn't exist in /var/www/html/revdevremote/core/xpdo/xpdo.class.php on line 1873
Call Stack Time Memory Function Location
1 0.0006 83012 {main}( ) ../index.php:0
2 0.0214 808220 modInstallRequest->handle( ) ../index.php:75
3 0.0239 822820 include( '/var/www/html/revdevremote/setup/controllers/summary.php' ) ../modinstallrequest.class.php:72
4 0.0242 830720 modInstall->test( ) ../summary.php:15
5 0.0445 1003648 modInstallTest->run( ) ../modinstall.class.php:288
6 0.0452 1009380 modInstallTest->checkDatabase( ) ../modinstalltest.class.php:38
7 0.0814 2219884 xPDO->query( ) ../modinstalltest.class.php:367
8 0.0815 2220012 PDO->query( ) ../xpdo.class.php:1873 Lots of failures when 'instll' is pressed, no db tables seem to exist.

**Comment by splittingred** [comment]
splittingred submitted:

Fresh install or upgrade? Assuming on the revolution/ SVN branch?

**Comment by splittingred** [comment]
splittingred submitted:

I just ran a fresh checkout of the SVN revolution/ branch, and can confirm that modx_transport_packages is the only table existing after the build - but my install works just fine, with no errors.

**Comment by shamblett** [comment]
shamblett submitted:

Yes, this is odd indeed, I get something like this on nealry every installer page, yes it is a fresh install :- Warning: PDO::query() &#91;pdo.query&#93; : SQLSTATE &#91;42S02&#93; : Base table or view not found: 1146 Table 'revdevremote.modx_system_settings' doesn't exist in /var/www/html/revdevremote/core/xpdo/xpdo.class.php on line 1873
Call Stack Time Memory Function Location
1 0.0006 83012 {main}( ) ../index.php:0
2 0.0187 808220 modInstallRequest->handle( ) ../index.php:75
3 0.0208 822820 include( '/var/www/html/revdevremote/setup/controllers/summary.php' ) ../modinstallrequest.class.php:72
4 0.0211 830720 modInstall->test( ) ../summary.php:15
5 0.0463 1003648 modInstallTest->run( ) ../modinstall.class.php:288
6 0.0470 1009024 modInstallTest->checkDatabase( ) ../modinstalltest.class.php:38
7 0.0724 2219572 xPDO->query( ) ../modinstalltest.class.php:367
8 0.0724 2219700 PDO->query( ) ../xpdo.class.php:1873 Different tables are named, however on scrolloing down the page output the real installer page is OK, if I press 'next', 'install' etc. the installation completes OK, I have 54 tables, can log into the manager amd revo looks fine to me, created some docs etc, all looks well. I dont often do a fresh install on this machine, only upgrades so its possible its my machine somewhere here. I'll try a fresh install on my windows box, use the same db name etc and see what happens there. I'll post back, if it works OK this can be closed.

**Comment by shamblett** [comment]
shamblett submitted:

OK, r5273 checkout fresh install works Ok on windows, so whatever the above was I don't think we should worry about it, the table not found stuff are only warnings, that's probably why the install proceeded and worked OK, may have been perms somewhere I suppose.
