### ISSUE TITLE
Change caption of source section in View Resource panel in Revo

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1541]
bobray created Redmine issue ID 1541

The caption in View Source (in View Document from the tree) should be changed to "Cache Output", "Resource Cache", or "Cache Inspection" since that's what is showing. A note that nothing will appear unless the doc is cacheable, saved, and visited might be a good idea too.

**Comment by BobRay** [comment]
bobray submitted:

Revo, not Evo.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5262

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
