### ISSUE TITLE
Better handling of "can't create database"

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1545]
bobray created Redmine issue ID 1545

User's are frequently stumped when the install fails becuase of permission issues in creating the DB. Maybe a more verbose message could be delivered suggesting that they create an empty DB using PhpMyAdmin or the equivalent.

**Comment by aceman3000** [comment]
aceman3000 submitted:

I thought excactly the same

**Comment by splittingred** [comment]
splittingred submitted:

Is fixed in branches/2.0-setup, will be merged in soon.
