### ISSUE TITLE
Quick create and quick update don't work in Firefox 3.0.11 + missing fields labels in Quick create/update TV

### ISSUE THREAD

**Issue by kongondo** [modxbot/migrate#1576]
kongondo created Redmine issue ID 1576

Quick Create and Quick Update in different browsers: 1. Firefox 3.0.11 Web Resource (resource, symlink, etc) Quick Create - does nothing when clicked Quick Update - The "loading" box flashes and that's it; nothing happens Snippet/Template Quick Create/Update - Work fine 2. Chrome Web Resource (resource, symlink, etc)/Snippet/Template Everything works fine 3. Safari 4.0 Web Resource (resource, symlink, etc)/Snippet/Template Works fine except for Quick Create Web Resource - the edit window is flash up the top of the browser and cannot be dragged down. See image here - http://img512.imageshack.us/i/revoquickcreateupdate.png/ ALL above Browsers - Quick Create/Update TV Works fine except the labels for some of the fields are missing. See image here: http://img221.imageshack.us/i/revoquickcreateupdatetv.png/ Many thanks. cheers/k

**Comment by kongondo** [comment]
kongondo submitted:

Tested on the svn version. The video demos for these features (by Shaun) says these features are from Revo beta 2 but the install actually says Revo beta 1 cheers/k

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5173. Also, if referring to beta-2, SVN will apply. The video just says that so people don't look for it in beta-1.
