### ISSUE TITLE
Make View Resource panel formatting more consistent

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1585]
bobray created Redmine issue ID 1585
1. Add "none" in red for empty fields in the general section. 2. Add missing language string for resource_unpublished 3. Add "No" in red for "Hide from Menus," and "Menu Title." 4. Add Menu Index?

**Comment by BobRay** [comment]
bobray submitted:

Oops, forgot this one: 5. Make Publish Date and Un-publish Date show "none" in red if empty instead of all the zeros.

**Comment by BobRay** [comment]
bobray submitted:
1. Add Published On to the Changes section.

**Comment by BobRay** [comment]
bobray submitted:
1. Add Menu Index to Status section.

**Comment by BobRay** [comment]
bobray submitted:
1. Uses Template shows just a dash for (empty) and Auto templates. Should show (empty) and Auto.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5262. Red coloring will come later, hopefully.

**Comment by BobRay** [comment]
bobray submitted:

Resolved.
