### ISSUE TITLE
In View Resource, the tree drops down and a blank gray area appears above it

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1586]
bobray created Redmine issue ID 1586

The tree starts below the bottom of the right panel. Much of the tree is off the screen.

**Comment by splittingred** [comment]
splittingred submitted:

Bob, Can you duplicate this still? I can't seem to get this to happen.

**Comment by BobRay** [comment]
bobray submitted:

I'm not seeing this any more.
