### ISSUE TITLE
Huge Alternate Text input box in Image TVs

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1591]
bobray created Redmine issue ID 1591

Sometimes the entry field for an image TV's Alternate Text is quite large--a large rectangular text area. I think it happens after setting the TV Output Type to Rich Text, then back to Image (not likely to happen very often).

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5289

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
