### ISSUE TITLE
RTE doesn't show up for Rich Text TVs

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1594]
bobray created Redmine issue ID 1594

With both Input and Output type set to Rich Text for a TV, the RTE doesn't appear when editing the TV in the Create/Edit Resource panel. TinyMCE is installed and works for the Content field. This happens whether or not Rich Text is checked in the Page Settings panel.

**Comment by robocop** [comment]
robocop submitted:

I'm noticing this in every browser. I wonder if the reason it's not showing up Is because the TV include is being called in remotely? This is more than a minor bug...

**Comment by splittingred** [comment]
splittingred submitted:

It's actually more of a bug with TinyMCE specifically - not MODx, per se, which is why it's classified as minor. TinyMCE needs to use the correct JS event handling to fire when the TVs are loaded.

**Comment by robocop** [comment]
robocop submitted:

so should we be looking for a temporary workaround for this issue?

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in SVN, will be operational in beta4. SVN Users can download the latest TinyMCE via Package Management to make it work.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed (tested in FF)
