### ISSUE TITLE
Image TV gets default value rather than selected value

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1596]
bobray created Redmine issue ID 1596

Image TVs always seem to get the default value (or an empty value if there is no default value) instead of the image selected. The selected image path shows in the box after browsing to the image, but the content tag has the default value for the src. Also, it seems that if the default value is assets/images, the browser should start in that directory when the user clicks on the browse button.

**Comment by splittingred** [comment]
splittingred submitted:

This seems to have been fixed in a prior revision.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed Fixed
