### ISSUE TITLE
Revolution Beta 2 accepts two mis-matched administrator passwords on install 

### ISSUE THREAD

**Issue by kongondo** [modxbot/migrate#1598]
kongondo created Redmine issue ID 1598

On a new install today, to test the installation process, I noticed that Revo accepted two mis-matched administrator passwords (I am referring to the "Administrator password" and "confirm password"). I tested this four times and in all instances I did not get any warnings; the installation continued successfully. I was able to log in using the first admin password entered and not the one entered in the confirmation field. Secondly: I tested installing without entering any admin details. The installation still proceeded successfully without any warnings - I couldn't log in after that since I didn't create any user. Thanks.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5120
