### ISSUE TITLE
no way to go back to the root folder when trying to insert an image for a page

### ISSUE THREAD

**Issue by xpix** [modxbot/migrate#1604]
xpix created Redmine issue ID 1604

When using an Image TV in a document you are shown the list of files from the "root" folder. If you click on another folder you will see all the images in that folder.
But when you want to see al the images in the root folder there is no button that you can use to go back to the initial listing. Solution: Create some sort of navigation menu or clickable bred-crumbs.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5854
