### ISSUE TITLE
USE RTE not sticky for documents

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1607]
bobray created Redmine issue ID 1607

Once I select TinyMCE for a document's editor, when I then select "none" it will let me edit without the RTE, but when I save and reload, the RTE is always back.

**Comment by splittingred** [comment]
splittingred submitted:

Is 'Richtext' checked for the document?

**Comment by BobRay** [comment]
bobray submitted:

Yes &#8211; so I guess setting editor to "none" works only temporarily unless you also uncheck "Rich Text." (I see this is also true in 0.9.6 &#8211; don't know why I never noticed it). I thought about having it so that setting editor to "none" either issues a warning if "Rich Text" is checked or automatically unchecks it, but the more I think about it, the more I like the current setup (duh). BTW, If you uncheck 'RichText," then immediately set editor to "none," then save (or not) the Rich Text setting is reset to checked and your change to it is lost.

**Comment by splittingred** [comment]
splittingred submitted:

TBH, I'm debating just removing that "which_editor" dropdown box entirely - it causes far more problems than it's worth.

**Comment by BobRay** [comment]
bobray submitted:

I like the idea a lot, although I guess it's possible that some one would want to use a different editor on different docs.

**Comment by splittingred** [comment]
splittingred submitted:

Removed the dropdown. Good riddance.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed gone.
