### ISSUE TITLE
Chunk cache with TVs not cleared with @CHUNK binding -- chunk cached even when TV tag is uncached

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1609]
bobray created Redmine issue ID 1609

This is complicated and possibly expected or inevitable but . . . Steps to duplicate: 1.Create a chunk called Lines
2. Create a TV called Colors
3. Put @CHUNK Lines in the Input Option Values field of the Color TV
4. Put the following in the Lines chunk:
red==Red as a rose||blue==Blue as the sea||green==Green as the grass 5. Put [ &#91;!*Colors&#93; ] in the template. This all works fine, but when you edit the chunk (e.g. Red as an apple), the changes don't appear until you also edit a document with the TV and save it. Clearing the site cache/browser cache doesn't do it (and shouldn't be necessary anyway since the content tag is uncached). So possibly two separate problems: 1. Content is cached that shouldn't be.
2. Clearing the site cache doesn't clear it. Note that this problem doesn't occur with a straight @CHUNK binding in the default value field, only when the @CHUNK is in the Input Option Values field. Could also be a problem with other @ bindings like @DIRECTORY and @FILE. Changes in a directory, for example, might not be reflected in the output until the document is edited and saved.

**Comment by BobRay** [comment]
bobray submitted:

Not a problem with @DIRECTORY. @FILE doesn't seem to work for Input Option Values &#8211; not sure if it should.

**Comment by opengeek** [comment]
opengeek submitted:

Since input option values are only evaluated at edit time, and not during parsing, it simply is not possible to pick up the changed value unless you re-edit a Resource after the input options change.
