### ISSUE TITLE
Sertting TV to rich text has no effect

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1610]
bobray created Redmine issue ID 1610

I have TinyMCE installed and it shows for the content field or a document but not for TVs with their Input Type set to richtext.

**Comment by splittingred** [comment]
splittingred submitted:

Duplicate of MODX-800

**Comment by BobRay** [comment]
bobray submitted:

I'm still getting a plain text box in FF3 rather than the RTE for TVs with Input Type set to Rich Text.
