### ISSUE TITLE
Friendly URLs Prefix and Suffix values can be changed in the settings page, but are not honoured for the actual site pages

### ISSUE THREAD

**Issue by bossloper** [modxbot/migrate#1611]
uxello created Redmine issue ID 1611

Enabling friendly URLs works, but when I change the default 'Suffix for friendly URLs' then new value is not used on the pages I view. It keeps using .html
Similar with Suffix. Any value put in the settings is not used and it remains as no suffix when viewing the site.
Clearing cache does not help.

**Comment by splittingred** [comment]
splittingred submitted:

Not a bug - suffixes are now done with Content Types.
