### ISSUE TITLE
Accordioan panel stickiness

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1617]
shamblett created Redmine issue ID 1617

In the web resources pane of the accordion panel I currently have folder of resources with some children, this folder(name templates) initially shows as expanded when the web resource pane is drawn on login(don't know why this should be but no matter). When I close up the expansion the web resources pane re-draws it unexpanded as expected. If I then however invoke another action., say clear site cache or create new document from the top menu, on completion of the operation the web resources pane is drawn with the templates folder expanded again, i.e. it seems to forget my last selection. If I create a document from the pull down menu in the document tree however on completion it does seem to remember my last selection.

**Comment by splittingred** [comment]
splittingred submitted:

No longer valid as of tabs change.
