### ISSUE TITLE
Site search returns results without entering any criteria

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1618]
shamblett created Redmine issue ID 1618

On invoking the Site->Search menu option the search page is displayed with the search results already populated, the search results panel seems to display a list of all the resources. OK but is this wise? On very large sites invoking this page may take some time, also should we not allow the user to enter some search criteria before we show any results?

**Comment by splittingred** [comment]
splittingred submitted:

It wont display all of them; just 20. Not really worth trying to hack into ExtJS to prevent the load.
