### ISSUE TITLE
Enabled System Events appear Disabled after applying a filter when editing a Plugin

### ISSUE THREAD

**Issue by pixelchutes** [modxbot/migrate#1621]
pixelchutes created Redmine issue ID 1621

While editing a plugin, when applying a Filter in the "System Events" section, associated "Enabled" events aren't showing up as being Enabled. At first glance this appeared to be similar to # MODX-135 , but have confirmed this is not the case.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5249
