### ISSUE TITLE
Issues with Quick Create

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1622]
bobray created Redmine issue ID 1622

The language string for Quick Create Snippet says "Quick Create Chunk" When Quick Creating a chunk, the content field is labeled "Code:" (should probably be "content").

**Comment by splittingred** [comment]
splittingred submitted:

There is no 'Quick Create Snippet' yet. There will be by beta-2.

**Comment by BobRay** [comment]
bobray submitted:

Ah... BTW, is it expected that when you right-click on an existing snippet or chunk lower down in the tree there's no "create" option?

**Comment by splittingred** [comment]
splittingred submitted:

No, 'Create a new [ &#91;+type&#93; ] here' is that create option; but it seems the lexicon string wasn't parsed right. That's a bug. However clicking on it still does the desired action.

**Comment by BobRay** [comment]
bobray submitted:

I wasn't seeing that "Create new [ &#91;+type&#93; ]" in FF, just IE, although I see it now in FF on the latest build.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5125

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
