### ISSUE TITLE
Saving Symlink brings up a blank page

### ISSUE THREAD

**Issue by peterb** [modxbot/migrate#1623]
peterb created Redmine issue ID 1623

I installed 097 Beta 1 without a hitch. Set it to use friendly URLs. Created first resources, which was a Symlink. I saved it and it displayed a blank page. Browsed back one page and the link was saved and displayed in Web Resources as it should be. I created a document and saved it. No issues. changed the System so that doc 2 was the defaul site start doc. Created another Symlink resources. Saved and it too displayed a blank page. Browsed back one page and it too was saved where it should be. I ediated and saved it with no issues at all. That's why I assigned this priority as Trivial. Something to fix later.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5191
