### ISSUE TITLE
Can no longer log into the manager after update to r5083

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1626]
shamblett created Redmine issue ID 1626

On updating to SVN r5083 and performing a successful rebuild/upgrade I can no longer log into the manager. On login a page appears with this content :-
"
Error! Permission denied! [ Logout ]
" If I press the logout link I get :- {'"success":true,"message":"","total":0,"data":[],"object":[]}' displayed. Nothing much in firebug, the MODx error log or the apache error log. Apache access log shows :_
'
127.0.0.1 - - &#91;02/Jun/2009:09:08:13 +0100&#93; "GET /revdev/manager HTTP/1.1" 301 378
127.0.0.1 - - &#91;02/Jun/2009:09:08:14 +0100&#93; "GET /revdev/manager/ HTTP/1.1" 200 2648
127.0.0.1 - - &#91;02/Jun/2009:09:08:16 +0100&#93; "GET /revdev/manager/assets/modext/core/modx.js HTTP/1.1" 304 -
127.0.0.1 - - &#91;02/Jun/2009:09:08:16 +0100&#93; "GET /revdev/connectors/lang.js.php?topic=login HTTP/1.1" 200 33754
127.0.0.1 - - &#91;02/Jun/2009:09:08:16 +0100&#93; "GET /revdev/manager/assets/modext/core/modx.component.js HTTP/1.1" 304 -
127.0.0.1 - - &#91;02/Jun/2009:09:08:16 +0100&#93; "GET /revdev/manager/assets/modext/widgets/core/modx.panel.js HTTP/1.1" 304 -
127.0.0.1 - - &#91;02/Jun/2009:09:08:41 +0100&#93; "POST /revdev/connectors/security/login.php HTTP/1.1" 200 88
' I'll try and get some more info on this when I get some time.

**Comment by splittingred** [comment]
splittingred submitted:

Truncate your modx_sessions table.

**Comment by shamblett** [comment]
shamblett submitted:

Yep, fixed, just noticed it does say 'NOTE: truncate all user sessions before updating/upgrading]' in the SVN log, missed it originally.
