### ISSUE TITLE
A new system setting with a numeric key does not resolve in a template when using the system setting tag.

### ISSUE THREAD

**Issue by bossloper** [modxbot/migrate#1627]
uxello created Redmine issue ID 1627

Create a new setting in System Settings. enter the key as a numeric e.g. 123
Add a value e.g. 'test' Put the system setting tag in a template: [ &#91;++123&#93; ]
This does not resolve to 'test' as expected.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5218 by preventing settings starting with numbers.
