### ISSUE TITLE
Hardcoded language

### ISSUE THREAD

**Issue by Pont** [modxbot/migrate#1631]
pont created Redmine issue ID 1631

There is hardcoded language in the following files: manager/assets/modext/widgets/security/modx.panel.user.js
280 - Login Options manager/assets/ext2/ext-all.js
91 - Displaying {0} - {1} of {2}
91 - No data to display
91 - Page
91 - of {0}
91 - First Page
91 - Previous Page
91 - Next Page
91 - Last Page
91 - Refresh
94 - OK
94 - Cancel
94 - Yes
94 - No manager\assets\modext\widgets\element\modx.grid.element.properties.js
84 - Import Properties
88 - Export Properties

**Comment by splittingred** [comment]
splittingred submitted:

Oh there's a lot more strings missing than that, especially with regards to ExtJS ones...working on it.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5139
