### ISSUE TITLE
Running setup in other language than english results in missing language strings and errors

### ISSUE THREAD

**Issue by Pont** [modxbot/migrate#1632]
pont created Redmine issue ID 1632

Running the setup in Swedish works perfectly until I get to the login screen. There all language is gone (se attached image). Logging in works with no problem, but the left menu is broken, language strings are missing and several warning messages are displayed on the start page (se attached image). Manually changing language settings to Swedish and doing a refresh of the manager fixes the issue.

**Comment by Pont** [comment]
pont submitted:

Never mind the bit about warnings... Those are standard warnings after a new installation when nothing is yet created and MODx wants various errorpages and the like.

**Comment by splittingred** [comment]
splittingred submitted:

Could you provide us with your Swedish translation so we can specifically test your situation?

**Comment by Pont** [comment]
pont submitted:

Swedish translation for rev 6351 attached. Login-screen is still without language. After login the menu seems so be ok, but the manager is without language.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6371
