### ISSUE TITLE
File Permissions during install

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1633]
bobray created Redmine issue ID 1633

File permissions need to be settable during install for suPHP and suExec environments. Since supPHP is reputedly difficult to detect, how about checking the permissions of existing index.php and/or .htaccess files and existing connectors folder?

**Comment by opengeek** [comment]
opengeek submitted:

Need more information on this; permissions should be no issue at all in these environments since one user owns the files and PHP runs as that same user.

**Comment by BobRay** [comment]
bobray submitted:

At one time, directory/file permissions were not being set to 755/644 in those environments which caused errors. Many permissions had to be set manually before MODx would run. I haven't done a fresh install on a remote server in quite a while so I don't know if this is still true.

**Comment by BobRay** [comment]
bobray submitted:

Assumed fixed.
