### ISSUE TITLE
Menu items ( resources, files... )

### ISSUE THREAD

**Issue by maxpiepenbrink** [modxbot/migrate#1635]
mido created Redmine issue ID 1635

It will be great if, as in previous versions, you add the menú items: resources and files, on the top menu too. Now, only appears on the left and the user must right-click items to create a new chunk or simmilar.

**Comment by splittingred** [comment]
splittingred submitted:

New Document/Symlink/Weblink/StaticResource are all in the top menu. We will not be adding chunk/snippet/plugin/etc to the top menu. However, you can do that custom if you'd like, via the System -> Actions page.

**Comment by maxpiepenbrink** [comment]
mido submitted:

Yes, I saw the custom menu option ( great idea ). But i thought it will be usefull. thanks instead
