### ISSUE TITLE
Couldn't change role to a member from the Security->Manage users menu

### ISSUE THREAD

**Issue by roberto** [modxbot/migrate#1639]
roberto created Redmine issue ID 1639

I am the admin user created during installation.
As soon as installed, I created a new user for my colleague.
Then, I tried to change her role from the Security->Manage Users menu, by double clicking on her role. I changed, and when I clicked out it gave me this Processor not found./home/MODx_Revolution_Beta/core/model/modx/processors/security/user/updatefromgrid.php and didn't change the role.

**Comment by roberto** [comment]
roberto submitted:

I think I found the reason. /home/MODx_Revolution_Beta/core/model/modx/processors/security/user/updatefromgrid.php MODx search for this, but the filename was /home/MODx_Revolution_Beta/core/model/modx/processors/security/user/updateFromGrid.php so, I just renamed the file and now it works. but I think it's better to rename the call in the core code instead of renaming the file. Cheers, and great work

**Comment by splittingred** [comment]
splittingred submitted:

Ack - no, we'll need to rename the file to lowercase - some PHP environments dont like capitalized files. Good catch.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5140
