### ISSUE TITLE
Sometimes can't edit User Group Access

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1645]
bobray created Redmine issue ID 1645

Right clicking on an entry in either User Group Access to Contexts or Resource Groups grid and selecting "edit" gives a small dialog with: The title (User Group Access to Contexts or User Group Access to Recource Groups) and just the "save" and "cancel' buttons. Nothing to edit.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5290

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
