### ISSUE TITLE
Sometimes can't log out after flushing permissions

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1646]
bobray created Redmine issue ID 1646

Sometimes, logging out immediately after flushing permissions results in an empty "are you sure" box with no button and a grayed-out screen. Reloading the page and trying again usually works. You should be able to duplicate this by repeatedly clicking on "no" on the "are you sure you want to log out" dialog, flushing permissions and clicking on logout.

**Comment by splittingred** [comment]
splittingred submitted:

Cant reproduce this at all, so assuming fixed.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed (FF).
