### ISSUE TITLE
Can't download packages in IE7 extra download site shown in both IE7 and FF

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1650]
bobray created Redmine issue ID 1650

In both IE7 and FF, I get two choices for "select a provider" in Package Management: MODx Web Transport Facility
modxcms.com (on one install, I get a third choice: MODx WTF). Selecting modxcms.com leads to a completely blank download tree in both FF3 and IE7 Selecting MODx Web Transport Facility works in FF, but in IE7, the tree is there but the items won't expand so it's impossible to download a package. In addition, closing the window in IE7 leaves a ghost window.

**Comment by splittingred** [comment]
splittingred submitted:

You can go ahead and delete WTF from the list - that is no longer a viable provider. modxcms.com will be the only provider for beta. The blank download for modxcms.com should be fixed now.

**Comment by BobRay** [comment]
bobray submitted:

In IE7, the tree appears and shows the categories but no componenents show up.
Still shows the ghost window after closing using the X. Things work fine in FF3 (although it sometimes takes several clicks to close the window using the X &#8211; not always and I can't find a pattern for it).

**Comment by splittingred** [comment]
splittingred submitted:

See MODX-510
