### ISSUE TITLE
Top Menu Choices not showing properly

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1655]
bobray created Redmine issue ID 1655

In r4987 the last four top menu items show the keys rather than the lexicon entries in the drop-down menu. It's weird, the lexicon entries are there in lexicon management under core | topmenu but they're only displaying for the left side of the top menu. Once you get past the left panel, only the keys show in both FF and IE7.

**Comment by splittingred** [comment]
splittingred submitted:

Try completely clearing your cache - I think we fixed this bug yesterday, but it requires a complete cache clear to fix it.

**Comment by BobRay** [comment]
bobray submitted:

I've cleared everything but it won't go away. I even deleted the entire core, manager, and connector directories, updated, and did a build/install on today's SVN with no luck. The correct entries are in the DB and I can see them all in Lexicon Management. They just don't show up in the drop-down menus on the right side. The odd thing is that I don't see this problem in another install on the same machine.

**Comment by BobRay** [comment]
bobray submitted:

I'm getting lots of these in the MODx error log: &#91;2009-05-14 10:17:19&#93; (ERROR @ C:\xampp\htdocs\MODx097\core\model\modx\modlexicon.class.php : 131) PHP warning: array_merge() &#91;<a href=&#39;function.array-merge&#39;>function.array-merge</a>&#93; : Argument #1 is not an array

**Comment by splittingred** [comment]
splittingred submitted:

This should have been fixed in a recent commit. Can you confirm?

**Comment by BobRay** [comment]
bobray submitted:

I have one local install where I can't seem to make this go away &#8211; even after lots of rebuilds, reinstalls, and cache clearing. It does not appear in a fresh checkout in either FF or IE7 so I guess it should be considered fixed.

**Comment by BobRay** [comment]
bobray submitted:

Oops &#8211; spoke too soon. Now that I can access the remote site, it's doing this too. I've deleted the cache and done an upgrade install to the current version but can't seem to make this go away.

**Comment by BobRay** [comment]
bobray submitted:

This is now gone in FF3 as of the latest release. I'll reopen if it shows up again.
