### ISSUE TITLE
Foreign characters (UTF8 data) needlessly removed from alias

### ISSUE THREAD

**Issue by rfoster** [modxbot/migrate#1676]
rfoster created Redmine issue ID 1676

Right now utf8 data is removed from the alias when the page is saved. If I set the alias to a utf8 string directly in the db (for example, ), utf8 friendly URLs (mysite.com/ .html) work fine, but of course, they are wiped out the next time I save the page. There is no reason to remove utf8 data from the alias since it works fine, and it is useful to many of the international users (notice that Wikipedia uses utf8 data in its aliases). Of course spaces should still be replaced with dashes, etc. If for some reason a user wanted to disable utf8 aliases or transliterate them, that functionality would properly belong in a plugin. (Or, you could add a site setting "Remove UTF-8 characters in alias.")

**Comment by rfoster** [comment]
rfoster submitted:

I gave more thought to this and created a quick fix. The function that does most of this is cleanAlias in modResource. This is how I believe it should work: Remove html entities and tags. (It would be nice to convert '&' and '&' to 'and' like in 9.6.x--better yet to convert to 'and' in the default language.) Remove characters that are reserved or could otherwise cause problems (& = + % # < > ~ `" ' @ ? [ ] { } | ^ &#41; (See http://www.faqs.org/rfcs/rfc1738.html ) Remove ! and , (exclamation and comma) Allow . and / but remove .. and // Replace all internal spaces with a dash Collapse adjacent dashes into one dash Trim whitespace Convert to lowercase based on config setting (would need a new config setting that defaults to yes). I rewrote the function to include most (but not all) of the functionality above. It needs a little cleaning, but works pretty well. function cleanAlias($alias) { $alias= mb_convert_case($alias, MB_CASE_LOWER, "UTF-8"); // This should be done unless turned off via a config option $alias= preg_replace('/&.+?;/', '', $alias); // kill entities $alias= preg_replace('/[&=+%#<>~"`@:;\?[]{}|^\\]/', '', $alias); // remove reserved and unsafe chars $alias= preg_replace("/[\']/", '', $alias); // remove single quotes $alias= preg_replace('/[!\,]/', '', $alias); // remove common punctuation, but not . or / // @todo: remove '..' and '//' $alias= preg_replace('/\s+/', '-', $alias); $alias= preg_replace('|-+|', '-', $alias); $alias= trim($alias); return $alias; } (Note: The calls to this function may also need to be modified so that strtolower is not performed on the result.)

**Comment by rfoster** [comment]
rfoster submitted:

Better code (and related discussion) can be found here:
 http://modxcms.com/forums/index.php/topic,36080.msg220134.html#msg220134

**Comment by opengeek** [comment]
opengeek submitted:

I have combined the ideas presented here by Ryan Foster with the TransAlias work for Evo, along with some ideas of my own and from around the web. I believe this covers everyone's needs on the surface, and I'll be releasing an Extra called translit that will provide the same facility which TransAlias provided for Evo. When installed, you can configure custom transliteration tables. You can also provide your own service class to do what translit does, if you so choose.
