### ISSUE TITLE
Revo on Centos 5.2 - no web resources tree panel

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1684]
shamblett created Redmine issue ID 1684

This bug report is raise from forum topic http://modxcms.com/forums/index.php/topic,34460.0.html to give a more formal report of the error and workround should other people hit this. In summary, beware of PHP 5.1.6, it has known issues with PDO and it may have more effect on revo than was first appreciated. Details follow. On update of one of my Centos 5.2 boxes to SVN revision 4876 I noticed that the resource tree did not draw in the web resources panel, although the elements and file panels were OK. A similar effect was seen on the Actions and Topmenus trees where only the top level tree element was drawn with no sub-items. The fault was accompanied by a 'no element' error in the firefox error console. I didn't check for any other effects here as the fault could be easily repeated by pressing the refresh icon on the web resource panel toolbar. Firebug reported the POST request issued by pressing the refresh icon as returning no data, also this request itself did not appear in the apache access log.
On inspection using a debugger the problem was traced to line 75 of modconnectorresponse.class.php. Even though the '$this->body' variable contained a well formed json data string to return to the browser when the line was actually executed a null body was always returned. Not being able to see any problem with revo here I decided to see if this happened on any of my other test machines , the results were as follows :- Platform pre r4876 r4876
----------- -------------- --------- Windows 2K No No
FC6 No Yes
FC7 No No
Centos 5 with
PHP 5.2.6 No No As can be seen from the above the FC6 box showed the fault when updating to r4876, the others didn't . On inspection it was found that the FC6 box and the newly commisioned Centos box both had PHP 5.1.6 on them, the others had 5.2.5 or 6. A workaround for the fault was found as follows :- Change Line 75 of modconnectorresponse.class.php, change 'die ($this->body);' to 'return $this->body;' Change Line 93 of modconnectorrequest.class.php, change '$this->modx->response->outputContent($options);' to '$content = $this->modx->response->outputContent($options);' Add new line 94 as 'die($content);' i.e move the die up a level of scope and the json body is always returned correctly. This lead me to believe a fault existed with PHP 5.1.6 that was affecting revo operation. On inspection of the PHP changelog between revisions 5.1.6 and 5.2.6 approx 1100 lines of bug fixes/rewrites and additions had been introduced and it was not practical to pin this down to a specific entry. The affected Centos machine, like its predecessor has been upgraded to PHP 5.2.6, hence the fault has now gone. I have left the FC6 box however frozen, I intend to update this with subsequent revo versions to see if the fault disappears again.

**Comment by splittingred** [comment]
splittingred submitted:

5.1.6 is definitely the issue, as there are multiple PHP bugs with PDO support in that version.

**Comment by splittingred** [comment]
splittingred submitted:

Since PHP 5.1.6 is the issue, and there's nothing we can do about the faulty PDO drivers in that version, closing this ticket.
