### ISSUE TITLE
Modfiy the browser for image and file TVs

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1701]
bobray created Redmine issue ID 1701

The current browse function is somewhat confusing with only folders showing up in the tree and files in the right panel. It seems like something is wrong when clicking on a folder won't show the files under it in the tree itself. I've selected the wrong file more than once. It would be easier and less error-prone if there were a single tree that expanded fully and users could select the desired file in the tree itself.

**Comment by splittingred** [comment]
splittingred submitted:

Probably will leave as-is, as the idea is that directories only are in the left-hand nav. Adding files introduces a few issues - mainly scrollability, length issues, and JS handler issues. Not worth it to change, imo.

**Comment by BobRay** [comment]
bobray submitted:

How about some instruction for the user? Something like this: "Click on a folder to display its files, then select the file in the right-hand panel."
