### ISSUE TITLE
500 server error when running /setup/index.php?action=install

### ISSUE THREAD

**Issue by jolyon2000** [modxbot/migrate#1709]
jolyon2000 created Redmine issue ID 1709

I am currently trying to install Modx. Went through the process of enabling PDO_MYSQL then making the httpdoc directory writable. Showed up as all having green ticks just before hitting the install button. When i hit the button, it redirected to http://MYDOMAIN/setup/index.php?action=install then threw a 500 Server Error !!

**Comment by splittingred** [comment]
splittingred submitted:

Did you read this: http://svn.modxcms.com/docs/display/revolution/Development+and+Testing+Notes
