### ISSUE TITLE
lexicon bug in Manage User Groups & Roles (action 66)

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#1712]
netprophet created Redmine issue ID 1712

No language strings were being loaded up for Security > Manage User Groups and Roles. Debugged connectors/lang.js.php?topic=topmenu,file,resource,role,user&action=66
and found string of errors starting with
(ERROR @ /connectors/lang.js.php) Could not find topic "role" to generate lexicon cache. I could not find the lexicon topic "role" in my database, but found a number of lexicon_entries related to "role" belonging to the "user" lexicon topic. So I edited action 66 through the Actions screen in the manager, and removed "role" from the Language Topics field.
This seems to have solved my problem (on both systems). The Manage User Groups and Roles page appears to contain the language strings it needs.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4906
