### ISSUE TITLE
cannot always save or delete users from Update User page

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#1715]
netprophet created Redmine issue ID 1715

When editing a user, the Save or Delete buttons may return "User not found".
This is because the processor is getting the id from the user_attributes table, and not the user id itself.
We cannot assume that records in this table will have the same value for id and internalKey.

**Comment by splittingred** [comment]
splittingred submitted:

Confused as to where you're talking about this happening. In what file are you referring to?
