### ISSUE TITLE
Template Variables not showing up in Resource Edit panel

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1717]
bobray created Redmine issue ID 1717

After creating a TV and assigning it to a template, it doesn't show up when I edit docs using that template. I looked in the DB and things look right.

**Comment by splittingred** [comment]
splittingred submitted:

This might have been fixed in a recent commit. Can you check?

**Comment by BobRay** [comment]
bobray submitted:

Works OK on localhost with the most recent commit so it's probably fixed. Will reopen if not.
