### ISSUE TITLE
Error when saving snippet

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1724]
bobray created Redmine issue ID 1724

This error appears in the MODx error log after saving a snippet in the manager (the snippet has no property set). &#91;2009-03-20 15:18:39&#93; (ERROR @ /wm-modx/connectors/element/propertyset.php) Error 42S22 executing statement:
Array
(
 &#91;0&#93; => 42S22
 &#91;1&#93; => 1054
 &#91;2&#93; => Unknown column 'modPropertySet.category' in 'field list'
)

**Comment by shamblett** [comment]
shamblett submitted:

Can't reproduce this here on my windows box using XAMPP, when a snippet is created and saved or an existing snippet is edited and saved I don't get this error, look as though it was fixed at rev 4758, log entry for modx.mysql.schema.xml states :- &#91;REBUILD/UPGRADE REQUIRED&#93; Added `category` field to modPropertySets; they can now be categorized Enhanced UI to support new modPropertySet category ability

**Comment by BobRay** [comment]
bobray submitted:

I no longer see that error, now I see this one when saving a snippet after editing it: &#91;2009-03-26 13:35:25&#93; (ERROR @ /modx097/connectors/layout/tree/resource.php) Instantiated a derived class modSnippet that is not a subclass of the requested class modResource I also see it when saving a resource.

**Comment by splittingred** [comment]
splittingred submitted:

BobRay, I can't reproduce this - does this still happen after you try a rebuild/upgrade, as well as a cache clear?

**Comment by BobRay** [comment]
bobray submitted:

I'm seeing no errors at all now after the latest commit. Don't know what was up but it's gone.
