### ISSUE TITLE
Install following uninstall shows blank console

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1725]
bobray created Redmine issue ID 1725

If you uninstall a package (removing all versions), then install a new version of that package, the console is blank for the install. I think it happens no matter what you install after the uninstall.

**Comment by splittingred** [comment]
splittingred submitted:

Should be solved now with introduction of new MODx.Console.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
