### ISSUE TITLE
Change the second heading on Create/Edit Resource panel

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1726]
bobray created Redmine issue ID 1726

Change "Resource Settings" to "Create/Edit {resourceType}." The Create/Edit phrase carries over from 0.9.6 so it will look familiar. It will match what we've done for elements. There's really no definition for "Resource Settings" and it would be nice to reserve the term "settings" for user, context, and system settings (Page Settings is a familiar term so I'd leave it).

**Comment by splittingred** [comment]
splittingred submitted:

Applied in r5661.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
