### ISSUE TITLE
Install fails with fatal error - cannot load class

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1727]
shamblett created Redmine issue ID 1727

Rev 4823 install fails on the database page, stack trace is :- PHP Fatal error: Class 'modContext_' not found in /var/www/html/revdev/core/xpdo/xpdo.class.php on line 670, referer: http://localhost/revdev/setup/index.php?action=database
PHP Stack trace:, referer: http://localhost/revdev/setup/index.php?action=database
PHP 1. {main}() /var/www/html/revdev/setup/processors/connector.php:0, referer: http://localhost/revdev/setup/index.php?action=database
PHP 2. modInstallConnector->handle() /var/www/html/revdev/setup/processors/connector.php:29, referer: http://localhost/revdev/setup/index.php?action=database
PHP 3. include() /var/www/html/revdev/setup/includes/modinstallconnector.class.php:72, referer: http://localhost/revdev/setup/index.php?action=database
PHP 4. modInstall->getConnection() /var/www/html/revdev/setup/processors/database.php:5, referer: http://localhost/revdev/setup/index.php?action=database
PHP 5. modInstall->_modx() /var/www/html/revdev/setup/includes/modinstall.class.php:187, referer: http://localhost/revdev/setup/index.php?action=database
PHP 6. modX->initialize() /var/www/html/revdev/setup/includes/modinstall.class.php:742, referer: http://localhost/revdev/setup/index.php?action=database
PHP 7. modX->_initContext() /var/www/html/revdev/core/model/modx/modx.class.php:357, referer: http://localhost/revdev/setup/index.php?action=database
PHP 8. xPDO->newObject() /var/www/html/revdev/core/model/modx/modx.class.php:2378, referer: http://localhost/revdev/setup/index.php?action=database Commenting this line out seems to just shift the error elsewhere, seems pervasive.

**Comment by shamblett** [comment]
shamblett submitted:

Just to clarify, this is from pressing 'Next' on the database page. Verified my windows box also fails here.

**Comment by splittingred** [comment]
splittingred submitted:

Manually clear your cache - especially core/cache/config.cache.php This was due to a recent revamp of the caching system. Sorry for the inconvenience.

**Comment by shamblett** [comment]
shamblett submitted:

Yes, OK now. I really must get in the habit of clearing the cache before I do a rebuild/upgrade.
