### ISSUE TITLE
Can't run setup on r4822

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1729]
bobray created Redmine issue ID 1729

Can't get past the screen with the "Test Connection" button. Test Connection is succesful, but when I click on "next" nothing happens (except that Firebug shows a new error). Firebug shows: "Invalid flag after regular expression." <b>Warning</b>: array_merge() [<a href=...class.php</b> on line <b>2517</b><br />\n It looks like it may be choking on the mootools eval: 1//MooTools, My Object Oriented Javascript Tools. Copyright (c) 2006 Valerio Proietti, < http://mad4milk.net >, MIT Style License.
2eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.r . . . . . . . .

**Comment by splittingred** [comment]
splittingred submitted:

Manually clear your cache - especially core/cache/config.cache.php This was due to a recent revamp of the caching system. Sorry for the inconvenience.

**Comment by BobRay** [comment]
bobray submitted:

Manually clearing the cache took care of it.
