### ISSUE TITLE
Can't create a property set while editing a TV

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1730]
bobray created Redmine issue ID 1730

The commands are all there, but trying to save a new property set gives an error.

**Comment by splittingred** [comment]
splittingred submitted:

I had no problems with this - how'd you get this to happen?

**Comment by BobRay** [comment]
bobray submitted:
1. Edit an existing Template 2. Under Properties, click Add Property Set. 3. Check "Create new" checkbox. 4. Give a name and description and click save. I get this error: "An error occurred while trying to associate the property set to the element." It happens in both IE7 and FF3.

**Comment by splittingred** [comment]
splittingred submitted:

This was fixed in r4928.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed, FF3, IE7 Vista.
