### ISSUE TITLE
Bring back Menuindex

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1731]
bobray created Redmine issue ID 1731

Put the "Menu Index" field back on the Create/Edit document panel (please). If menu position depends on the position in the tree, people won't be able to sort the tree alphabetically without screwing up their menus and might easily mess up their menus by accident . Also, it's nice to set Menu Index for some items to high or low numbers to make sure they stay at the top or bottom. Otherwise, you'd have to drag the last item up every time you create a new resource.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4829

**Comment by BobRay** [comment]
bobray submitted:

Confirmed Fixed.
