### ISSUE TITLE
Make capitalization on the document create/edit screen consistent

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1732]
bobray created Redmine issue ID 1732

Almost all words in the the field name terms are capitalized. These exceptions should be changed for consistency: Page Settings section: Un-publish date > Un -publish Date
Empty cache -> Empty Cache Right panel: Resource's alias -> Resource Alias (I'd request ditching the apostrophe so I don't have to refer to it as the "Resource's Alias field" to be accurate). Menu title -> Menu Title Hide from Menus -> Hide From Menus (could go either way on this one, but it would be the only field name word not capitalized if not changed). introtext -> no change.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5863

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
