### ISSUE TITLE
Content disposition: attachment doesn't stick

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1735]
bobray created Redmine issue ID 1735

When you save a Static Resource after setting the Content Disposition to "attachment" it switches back to "inline."

**Comment by BobRay** [comment]
bobray submitted:

The content_dispo field stays at 0 in the DB, although content_type is set correctly. If I change content_dispo to 1 manually in the DB, I do get the download dialog via a link to the Static Resource, but if I then save the SR again without touching the content-dispo field, it reverts to inlineand shows 0 in the DB.

**Comment by BobRay** [comment]
bobray submitted:

This problem occurs for Documents also.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4832

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
