### ISSUE TITLE
All resource group access permissions selected on resource edit

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1739]
shamblett created Redmine issue ID 1739

When editing a resource the access permissions pane shows all available resource groups ticked, not just the ones the resource belongs to. The database is correct here.

**Comment by shamblett** [comment]
shamblett submitted:

Ok guys, fix for this :- change line 33 of \core\model\modx\processors\resource\resourcegroup\getlist.php from :- $rgr = $rg->getOne('modResourceGroupResource',array(
'document' => $_REQUEST &#91;&#39;resource&#39;&#93; ,
)); to $rgr = $rg->getOne('modResourceGroupResource',array(
'document' => $_REQUEST &#91;&#39;resource&#39;&#93; ,
'document_group' => $rg->get('id')
)); You need to tie the document_group in the criteria, the object instance i.e $rgr wont do this for you, this I believe is because of line 1026 in
xpdoobject.class.php i.e if ($object= $this->xpdo->getObject($fkdef &#91;&#39;class&#39;&#93; , $criteria, $cacheFlag)) The $criteria here is not specific to $this its just what's passed.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4935. Actually did a join on the main query to limit # of total queries.
