### ISSUE TITLE
Quirks in Content Fields

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1744]
bobray created Redmine issue ID 1744

Some of these may be by design, but others are definite bugs: Can't make an existing document a container by checking the Container Checkbox [ &#91;*createdon&#93; ] prints 0000-00-00 00:00:00 Published On (in Manager) shows 12/31/69 7:00 pm for unpublished documents and continues to show that after they're published. Can't publish a document with a future Publish Date by checking the Published checkbox (should probably clear Publish Date and set createdon). No way to set:
donthit
haskeywords
hasmetatags

**Comment by splittingred** [comment]
splittingred submitted:

Not sure what's going on with createdon. Publishedon bug fixed in r4795. Will look into the publish bug. Also, donthit is deprecated and has no function in Revo, hence why there's no UI. Keywords/Metatags are also phased out and have no meaning in Revo.

**Comment by BobRay** [comment]
bobray submitted:

Don't forget the Container bug. At present there's no way to turn an existing doc into a container without creating something under it (i.e., there's no way to have an empty container).

**Comment by shamblett** [comment]
shamblett submitted:

MODX-535 now contains a fix for the container bug

**Comment by BobRay** [comment]
bobray submitted:

Container bug confirmed fixed. Still to do: Created on: 0000-00-00 00:00:00
Checking "published" won't publish a document with a future publish date.

**Comment by splittingred** [comment]
splittingred submitted:

Createdon was fixed in a prior commit.

**Comment by BobRay** [comment]
bobray submitted:

One more quirk. If you publish a resource, then unpublish it by unchecking the published checkbox, it keeps its original publication date. If you later publish it, either manually, or automatically via a published date, it still keeps the original pub date. I think we agreed that pub date should show the date of the most recent change from unpublished to published status.
