### ISSUE TITLE
URL TV - prefix is forgotten

### ISSUE THREAD

**Issue by Caomhin** [modxbot/migrate#1749]
caomhin created Redmine issue ID 1749

If a template features a TV set to URL the manager splits the variable into a prefix and a URL. When you create a resource and fill in the TV with a value such as http://www.example.com and then navigate away from the resource in the manager, then re-enter the manager the select box will be "--" instead of "http://" If you stay on the edit page with the "continue editing" option the TV will stay as http://www.example.com across multiple saves, however any time you return to the resource from elsewhere the prefix value will be forgotten. Seems plausibly related to MODX-660

**Comment by splittingred** [comment]
splittingred submitted:

Confirmed. It's unrelated to MODX-660 , but definitely does happen. Seems to be a mis-step in the TV mgr render.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4778
