### ISSUE TITLE
Parent ID needs setting for every save

### ISSUE THREAD

**Issue by Caomhin** [modxbot/migrate#1750]
caomhin created Redmine issue ID 1750

When a resource is created as a child of another the parent needs setting. This setting seems to be partially forgotten when you navigate away from the manager page. i.e. A resource is created that is the child of resourceID 4 - the resource is displayed accurately both in the manager and the front end site. Navigate to another page in the manager, now if this resource is edited the Parent Resource select box will say "4" however when the resource is saved this will change to 0 and the resource will no longer be a child of resourceID4. When editing if you select the Parent Resource selectbox the standard tree structure of web appears, if you select resourceID 4 the data in the selectbox will then say "pagetitle (4)" and saving the document will retain the resource as a child of resourceID4. If you don't navigate away from the manager page (with the "continue editing" option selected) the selectbox will revert to "4" however the correct setting will be retained until you do navigate away.

**Comment by splittingred** [comment]
splittingred submitted:

This should have been fixed as of last evening. Confirm?

**Comment by Caomhin** [comment]
caomhin submitted:

I just grabbed r4777 and did Flush All Sessions but the problem seems to persist.

**Comment by splittingred** [comment]
splittingred submitted:

Try clearing your browser cache and doing a force refresh (shift+r).

**Comment by Caomhin** [comment]
caomhin submitted:

Hmm, I appear to have broken my manager in general somehow now. The Save button does nothing... I just tried a quick rebuild but it didn't help so I'll try to figure out where I broke it and get back to you.

**Comment by Caomhin** [comment]
caomhin submitted:

Okay, yep the Parent ID seems to saving correctly running r4778.
