### ISSUE TITLE
Cannot edit top level document

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1751]
shamblett created Redmine issue ID 1751

If a document doesn't have a parent i.e. is at the top level trying to edit it fails with :- Fatal error: Call to a member function get() on a non-object in C:\Program Files\xampp\htdocs\revdev\manager\controllers\resource\update.php on line 51
Call Stack Time Memory Function Location
1 0.0032 86408 {main}( ) ..\index.php:0
2 0.4606 6158016 modManagerRequest->handleRequest( ) ..\index.php:76
3 0.4669 6226848 modManagerRequest->prepareResponse( ) ..\modmanagerrequest.class.php:141
4 0.4758 6370472 modManagerResponse->outputContent( ) ..\modmanagerrequest.class.php:188
5 2.0432 7068312 include( 'C:\Program Files\xampp\htdocs\revdev\manager\controllers\resource\update.php' ) ..\modmanagerresponse.class.php:69 Looking at update.php line 45 $parent is only set if the resource has a parent otherwise it is null hence line 51 fails.

**Comment by splittingred** [comment]
splittingred submitted:

Fix in r4777
