### ISSUE TITLE
Cannot add templates to newly created template variable

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1752]
shamblett created Redmine issue ID 1752

When creating a TV from scratch you cannot assign a template to it until you have saved it first, the template pane always shows no templates even when refreshed. The response string from firebug contains the following string 'template variable not found' until the TV is saved. I suspect this applies to the other panes as well e.g use perms but I've noty checked this

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4767
