### ISSUE TITLE
False "Resource Alias" duplication error

### ISSUE THREAD

**Issue by zaigham** [modxbot/migrate#1753]
zaigham created Redmine issue ID 1753

If I create a new document under a container, which doesn't have alias explicitly associated, upon saving MODx gives me alias duplication error and doesnt save until an alias given. eg. Container (100) New doc (101) - Yet to be saved for first time and expecting an id of (101) MODx will give me error: "Resource (100) is already using the alias 100.html" etc.

**Comment by zaigham** [comment]
zaigham submitted:

One more thing I noticed is, it only happens when there is no other child docs under that container. IOW: if container already has 1 or more documents under it, this error doesn't appear.

**Comment by opengeek** [comment]
opengeek submitted:

Unable to reproduce this problem in current SVN branches.
