### ISSUE TITLE
In snippet "add property set" a "0" property set is always listed, even if there are no property sets.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1758]
bobray created Redmine issue ID 1758

"save" tries to save with the 0 property set but generates an error.

**Comment by opengeek** [comment]
opengeek submitted:

This does not appear to still be an issue.

**Comment by BobRay** [comment]
bobray submitted:

Still shows a 0 for the property set in the drop-down in FF 3.5.7, but the error no longer occurs on save.
