### ISSUE TITLE
Topic field blank in Lexicon Management

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1767]
bobray created Redmine issue ID 1767

If you switch from the core to another namespace, the default topic items are shown but the topic box is red and empty. It's trivial except that if the topic is really not set, I'm not sure that new entries or changes would be recorded correctly. I'd swear that the very first time I tried selecting another namespace, the grid was blank until I selected "default" for the topic but I can't get it to do this again, even after clearing the cache.

**Comment by splittingred** [comment]
splittingred submitted:

This is to tell you to select the new topic for that namespace. Since you're changing namespaces, the old selected Topic won't apply (since each namespace has different topics), and the red line makes sure you are selecting a topic for your newly-selected namespace before proceeding.

**Comment by BobRay** [comment]
bobray submitted:

Wouldn't it be better to pre-select "default" and put that in the topic box, since that's the only topic most non-core namespaces will have? Also, Although it's convenient for experts, I think it's somewhat confusing to have all three Lexicon Management functions on the same screen. When you select a new namespace, the grid is empty until you pick a topic so the other two Management boxes move up and users might assume that they are part of what you're currently doing. This is especially true if the user is browsing here and selects a namespace with no topics and no lexicon entries (e.g.ThermX). The Topic box stays red and won't show you any topics (because there aren't any). IMO, tabs would be a better option here (and elsewhere).

**Comment by BobRay** [comment]
bobray submitted:

I still think the grid should be set to the default topic and show those items when first accessed. I'd guess that over 90% of add-on component namespaces will only have a "default" topic. It might also be cool to show "no topics" in the topic field if their aren't any.
