### ISSUE TITLE
System Settings missing in FF3 and IE7

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1769]
bobray created Redmine issue ID 1769

After upgrading to r4733, the System Settings table is empty. The settings must exist because the Manager works fine so it's just a display issue. The grid is there and it says "Page 1 of 1" but no settings.

**Comment by BobRay** [comment]
bobray submitted:

Now I have this in two separate installs of Revo. After a little while, the "loading" animation comes up and continues to spin, but it never goes away. I did the usual build/setup and cleared all caches and cookies with no luck.

**Comment by splittingred** [comment]
splittingred submitted:

I can't replicate this at all. Did you make sure to completely empty your browser cache?

**Comment by BobRay** [comment]
bobray submitted:

Yep. Cleared everything a number of times. I now have it on three installs in both IE7 and FF3 (see attached file). Firebug reports this: A &#91;C.xtype || D&#93; is not a constructor
Component()()ext-all.js (line 57) renderDynField()("iso-8859-3", Object id=value value=Character encoding, Object id=1041 data=Object json=Object store=Object, 5, 2, Object data=Object baseParams=Object paramNames=Object, Object exp=Object config=Object store=Object menu=Object)modx.gri...ttings.js (line 258)
getViewWidth()()ext-base.js (line 9)
initTemplates()( &#91;Object id=expander style=width:18px;, Object name=name id=1 style=width:468px;, Object name=value id=value style=width:280px;, 3 more... 0=Object 1=Object 2=Object 3=Object 4=Object 5=Object&#93; , &#91;Object id=1006 data=Object json=Object store=Object, Object id=1008 data=Object json=Object store=Object, Object id=1021 data=Object json=Object store=Object, 47 more... 0=Object 1=Object 2=Object 3=Object 4=Object 5=Object&#93; , Object data=Object baseParams=Object paramNames=Object, 0, 6, true)ext-all.js (line 144)
HeaderDragZone()( &#91;Object id=expander style=width:18px;, Object name=name id=1 style=width:468px;, Object name=value id=value style=width:280px;, 3 more... 0=Object 1=Object 2=Object 3=Object 4=Object 5=Object&#93; , &#91;Object id=1006 data=Object json=Object store=Object, Object id=1008 data=Object json=Object store=Object, Object id=1021 data=Object json=Object store=Object, 47 more... 0=Object 1=Object 2=Object 3=Object 4=Object 5=Object&#93; , Object data=Object baseParams=Object paramNames=Object, 0, 6, true)ext-all.js (line 145)
initTemplates()(0, 49)ext-all.js (line 144)
HeaderDragZone()()ext-all.js (line 145)
initTemplates()(undefined)ext-all.js (line 144)
initTemplates()(undefined)ext-all.js (line 144)
initTemplates()()ext-all.js (line 144)
EventManager()()ext-all.js (line 12)
EventManager()()ext-all.js (line 12)
SimpleStore()(Object success=true records= &#91;50&#93; totalRecords=94, Object params=Object scope=Object, true)ext-all.js (line 43)
ScriptTagProxy()(Object params=Object request=Object reader=Object, true, Object tId=4 status=200 statusText=OK, undefined)ext-all.js (line 50)
getViewWidth()(function(), Object events=Object conn=Object useAjax=true, &#91;Object params=Object request=Object reader=Object, true, Object tId=4 status=200 statusText=OK 0=Object 1=true 2=Object&#93; , undefined)ext-base.js (line 9)
constructor()(Object tId=4 status=200 statusText=OK)ext-all.js (line 17)
getViewWidth()(Object conn=XMLHttpRequest tId=4, Object scope=Object argument=Object timeout=30000, undefined)ext-base.js (line 10)
getViewWidth()()ext-base.js (line 10)
 &#91;Break on this error&#93; Ext.ComponentMgr=function(){var B=new Ex...);Ext.reg=Ext.ComponentMgr.registerType;
ext-all.js (line 57)
POST http://localhost/modx097/connectors/layout/tree/resource.php?action=getNodes&id=web_0&type=context
 http://localhost/modx097/connectors/layout/tree/resource.php?action=getNodes&id=web_0&type=context

**Comment by BobRay** [comment]
bobray submitted:

Screen shot

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4739

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed. IE7/FF3
