### ISSUE TITLE
Changing a Template Variable value does not enable "Save" button. It remains disabled.

### ISSUE THREAD

**Issue by zaigham** [modxbot/migrate#1772]
zaigham created Redmine issue ID 1772

Changing a Template Variable value does not enable "Save" button. It remains disabled.

**Comment by splittingred** [comment]
splittingred submitted:

Actually, it does - you have to lose focus on the field, first. If you were to click the save button, it would enable right as you click it. If you want to add a ticket instead looking for a keydown event rather than an onchange event, feel free to do that.

**Comment by zaigham** [comment]
zaigham submitted:

The behavior you described isn't consistent and user should be given a visual clue. Honestly I think you should leave the buttons in "enabled" state regardless the change in the document.

**Comment by zaigham** [comment]
zaigham submitted:

Also if selected the "Save and Stay" option, the reloaded interface literally disable the "Save" button if I change the TVs, I will have to put the cursor in non-tv field and press space and backspace (just to make js think that i changed something) and then "Save" button gets enabled.
