### ISSUE TITLE
Changing Template does not reload associated TVs

### ISSUE THREAD

**Issue by zaigham** [modxbot/migrate#1773]
zaigham created Redmine issue ID 1773

Upon changing a template, the user is not presented with the TVs associated with it. Instead old TVs from previous template remain displayed. User has to save and re-open the document to see the TVs associated.

**Comment by splittingred** [comment]
splittingred submitted:

I can't seem to replicate this - my TVs have no problems with replicating. Please specify the screen you got this on (create/update), browser, and your server info/php/mysql, etc.

**Comment by zaigham** [comment]
zaigham submitted:

Its new modx site. And the problem happens when I create a new document and then change the template for the same. Now manager reloads and doesnt not display the TVs associated with the new template I select, but keep the screen as is (it seems) and only changes the template name in template selection input.
