### ISSUE TITLE
Document Tree doesn't remember last state while editing/saving a document

### ISSUE THREAD

**Issue by zaigham** [modxbot/migrate#1775]
zaigham created Redmine issue ID 1775

When creating a new document, the Document Tree resets to the default view instead of remembering the last state. eg. If I am creating a new document couple level deep, on editing screen if I view the tree it shows the default tree view instead of "opened" tree view to the current "container".

**Comment by splittingred** [comment]
splittingred submitted:

Confirmed. Statefulness in the tree is proving difficult - going to try some other ideas for how to preserve state later, rather than the current, which is to save the state on a click of a node.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4738
