### ISSUE TITLE
Update xmlrpc lib to version 2.2.1

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1778]
bobray created Redmine issue ID 1778

If the internal version numbers are correct, we're using xmlrpc Version 1.158, which has known eval-based security vulnerabilites, a conflict with PHP 5.2.2, and potential conflicts with another xmlrpc lib that might be installed on the server. xmlrpc 2.2.1 still supports PHP4 (last version to do so). More info here: http://phpxmlrpc.sourceforge.net/ Download 2.2.1 here: http://sourceforge.net/projects/phpxmlrpc/

**Comment by splittingred** [comment]
splittingred submitted:

Done in r4760

**Comment by BobRay** [comment]
bobray submitted:

resolved
