### ISSUE TITLE
More progress reporting from transport.core.php

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1783]
bobray created Redmine issue ID 1783

People downloading from Jira may think the build script isn't executing because it doesn't produce any message until the end. I can take up to 9 minutes on my machine. Suggest printing "Building . . . please be patient" at the beginning and echoing a dot every now and then.

**Comment by splittingred** [comment]
splittingred submitted:

Added in r4731.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
