### ISSUE TITLE
Change config warning message.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1784]
bobray created Redmine issue ID 1784

This has bugged me forever but I keep forgetting to post it here:
On the Manager Home page: "What does this mean?
Very naughty people could potentially wreak some havoc on your site and everything associated with it. Really. Please make your config file read only! Please contact a systems administrator and warn them about this message!" For me, it conjures up images of sixties swingers with gold chains, mullets, bad mustaches, leather accessories and B&D equipment, trashing the site with studded wooden paddles &#8211; maybe it's just me. How about: ""What does this mean?
Your site is vulnerable to hackers who could do a lot of damage to the site. Please make your config file read only! If you are not the site admin, please contact a systems administrator and warn them about this message!" If we don't want to use the word hackers, how about vandals, intruders, miscreants, or people with ill intent &#8211; anything but "very naughty people."

**Comment by zaigham** [comment]
zaigham submitted:

Bob! very naughty explanation!....

**Comment by BobRay** [comment]
bobray submitted:

LOL

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6292

**Comment by BobRay** [comment]
bobray submitted:

Yes! Thanks.
