### ISSUE TITLE
Fresh install of basic version / blank page at /setup/index.php?action=login

### ISSUE THREAD

**Issue by michaelGregoire** [modxbot/migrate#1788]
michaelgregoire created Redmine issue ID 1788

At the end of the fresh installation of the basic version I got a blank page when loading /setup/index.php?action=login with the following error: PHP Warning: modContext::include(/Library/WebServer/Documents/mamp/modx/core/cache/mgr/context.cache.php) &#91;<a href=&#39;modcontext.include&#39;>modcontext.include</a>&#93; : failed to open stream: No such file or directory in /Library/WebServer/Documents/mamp/modx/core/model/modx/modcontext.class.php on line 49 During the installation process I had checked the delete setup directory checkbox. After the failed install, I decided to reinstall and this time I left the delete setup directory checkbox unchecked. The install completed successfully and the login page loaded fine. It looks to me that there may be bug in the setup directory deletion process.

**Comment by splittingred** [comment]
splittingred submitted:

Cant duplicate this; will assume its related to server misconfiguration, directory permissions, or another one of the setup related bugs (most likely).
