### ISSUE TITLE
Show all and hide all buttons for package management  and properties grids

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1792]
bobray created Redmine issue ID 1792

It looks so good in system settings, it would be great in PM and properties too.

**Comment by splittingred** [comment]
splittingred submitted:

Added to PM grid in r4667. Properties grids already had it.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed FF3. (Buttons may be off screen in IE7).
