### ISSUE TITLE
No Package Management in FF3

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1797]
bobray created Redmine issue ID 1797

When I click on Package Management in the drop-down menu, I get a blank right pane on the right (r4655). Firebug gives an error: H is null The page displays fine in IE7 and Chrome.

**Comment by BobRay** [comment]
bobray submitted:

Only happens when Firebug is enabled.

**Comment by splittingred** [comment]
splittingred submitted:

Since I can't replicate this in FF3 Mac, I'm going to assume it's a Firebug error - which we do not support. We will, however, upon release, put a warning stating for users to not use Firebug at the same time as MODx.

**Comment by BobRay** [comment]
bobray submitted:

My only concern would be that Firebug is detecting an actual bug on the page. It doesn't show an error on any other Manager page I've tried.
Also, some users will certainly want to use Firebug to diagnose CSS issues while previewing pages in the Manager.

**Comment by BobRay** [comment]
bobray submitted:

No longer happening.
