### ISSUE TITLE
Hovering over a plus/minus icon on the accordion lhs menu (elements, resources, etc) broken

### ISSUE THREAD

**Issue by redman** [modxbot/migrate#1798]
redman created Redmine issue ID 1798
# the plus sign is shown even when an accordion is expanded, and hovering over it should display a minus sign. vice versa for unexpanded items. the patch below fixes this issue in file /var/www/html/modx/manager/assets/ext2/resources/css/ext-all.css Index: ext-all.css

&#8212; ext-all.css (revision 4651)
+++ ext-all.css (working copy)
@@ -854,8 +854,8 @@
.x-tool-expand-east,.x-tool-expand-west{float:none;margin:3px auto;}
.x-accordion-hd .x-tool-toggle{background-position:0 -255px;}
.x-accordion-hd .x-tool-toggle-over{background-position:-15px -255px;}
-.x-panel-collapsed .x-accordion-hd .x-tool-toggle{background-position:0 -240px;}
-.x-panel-collapsed .x-accordion-hd .x-tool-toggle-over{background-position:-15px -240px;}
+.x-panel-collapsed .x-accordion-hd .x-tool-toggle{background-position:0 -120px;}
+.x-panel-collapsed .x-accordion-hd .x-tool-toggle-over{background-position:0px -240px;}
.x-accordion-hd color: Color value is not a valid CSS2 color
.x-layout-collapsed{position:absolute;left:-10000px;top:-10000px;visibility:hidden;background-color:#d2e0f2;width:20px;height:20px;overflow:hidden;border:1px solid #98c0f4;z-index:20;}
.ext-border-box .x-layout-collapsed{width:22px;height:22px;}

**Comment by redman** [comment]
redman submitted:

and here is a diff in unified diff format instead: &#8212; ext-all.css 2009-01-24 11:30:04.000000000 +0000
+++ ext-all.css.new 2009-01-22 21:31:56.000000000 +0000
@@ -854,8 +854,8 @@
.x-tool-expand-east,.x-tool-expand-west{float:none;margin:3px auto;}
.x-accordion-hd .x-tool-toggle{background-position:0 -255px;}
.x-accordion-hd .x-tool-toggle-over{background-position:-15px -255px;}
-.x-panel-collapsed .x-accordion-hd .x-tool-toggle{background-position:0-240px;}
-.x-panel-collapsed .x-accordion-hd .x-tool-toggle-over{background-position:-15px -240px;}
+.x-panel-collapsed .x-accordion-hd .x-tool-toggle{background-position:0-120px;}
+.x-panel-collapsed .x-accordion-hd .x-tool-toggle-over{background-position:0px -240px;}
.x-accordion-hd color: Color value is not a valid CSS2 color
.x-layout-collapsed{position:absolute;left:-10000px;top:-10000px;visibility:hidden;background-color:#d2e0f2;width:20px;height:20px;overflow:hidden;border:1px solid #98c0f4;z-index:20;}
.ext-border-box .x-layout-collapsed{width:22px;height:22px;}

**Comment by redman** [comment]
redman submitted:

unified diff attached (pasting it didn't work)

**Comment by splittingred** [comment]
splittingred submitted:

No longer valid with new design.
