### ISSUE TITLE
Make the results of Clear Site Cache appear in a popup window

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1800]
bobray created Redmine issue ID 1800

Clearing the cache will very often be done by developers working on code. It would be nice if they could just close a pop-up window rather than having to navigate back to what they were working on.

**Comment by splittingred** [comment]
splittingred submitted:

Excellent suggestion. This would require editing the modMenu code for that item, creating a MODx.Window object for the popup's contents, and then hooking it to the proper connector/processor. However, we'll look into this - we're going to add some options to clearing the cache (such as which files to clear).

**Comment by splittingred** [comment]
splittingred submitted:

Done in r4938

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed in FF3 (Yes!!!). Can't test in IE7 until menu is fixed (no way to clear cache).

**Comment by BobRay** [comment]
bobray submitted:

Confirmed awesome.
