### ISSUE TITLE
Logging messages during installation causes nesting error

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1805]
shamblett created Redmine issue ID 1805

I'm seeing a manifestation of MODX-596 again on my linux box, i.e if the installation procedure tries to log anything it causes a nesting error and fails. My windows box installs OK now buts that's because I don't think its trying to log anything, so, as a test I updated the last line of 2.0.0-beta-1.php in /includes/upgrades with this :- $this->install->xpdo->log(XPDO_LOG_LEVEL_ERROR,"SJH test log"); With this line in I get this :- {main}( ) ..\index.php:0
2 0.0555 930504 modInstallRequest->handle( ) ..\index.php:90
3 0.0577 947504 include( 'C:\Program Files\xampp\htdocs\revdev\setup\controllers\install.php' ) ..\modinstallrequest.class.php:70
4 0.0583 956640 modInstall->execute( ) ..\install.php:15
5 0.3810 5640192 modInstallVersion->install( ) ..\modinstall.class.php:309
6 0.5706 6405504 include_once( 'C:\Program Files\xampp\htdocs\revdev\setup\includes\upgrades\2.0.0-beta-1.php' ) ..\modinstallversion.class.php:91
7 0.9430 6613888 xPDO->log( ) ..\2.0.0-beta-1.php:66
8 0.9430 6613888 modX->_log( ) ..\xpdo.class.php:1384
9 0.9430 6615792 xPDO->_log( ) ..\modx.class.php:2539
10 0.9434 6618624 xPDOCacheManager->writeFile( ) ..\xpdo.class.php:1438
11 0.9453 6619400 xPDO->log( ) ..\xpdocachemanager.class.php:153
12 0.9454 6619400 modX->_log( ) ..\xpdo.class.php:1384
13 0.9454 6621304 xPDO->_log( ) ..\modx.class.php:2539
14 0.9458 6624304 xPDOCacheManager->writeFile( ) ..\xpdo.class.php:1438
15 0.9476 6625080 xPDO->log( ) ..\xpdocachemanager.class.php:153
16 0.9476 6625080 modX->_log( ) ..\xpdo.class.php:1384
17 0.9476 6626984 xPDO->_log( ) ..\modx.class.php:2539
18 0.9480 6629984 xPDOCacheManager->writeFile( ) etc. If I remove the line the install completes OK. I think this maybe why some people are reporting failed installation/blank page/apache crashes etc. here SVN rev is 4636

**Comment by shamblett** [comment]
shamblett submitted:

Ok, why do we need this line :-
83: $this->install->xpdo->setPackage('modx', MODX_CORE_PATH . 'model/');
in the install() function of modinstallversionclass.php?
The scripts just use the XPDO object don't they?

**Comment by shamblett** [comment]
shamblett submitted:

OK, commenting the above line out makes no difference to the prob, back to being baffled for now

**Comment by shamblett** [comment]
shamblett submitted:

Think we have a cause :-
xpdocachemanager.class, function, writeFile calls xpdo->log on line 153, you can't do this if the log target is FILE and the logging fails, you could make it FATAL rather than ERROR or not do it . Ultimately this is a perms issue on the log directory, OK, but why does it fail on windows?

**Comment by opengeek** [comment]
opengeek submitted:

This was an xPDO issue and is resolved in xPDO as of revision 298.

**Comment by opengeek** [comment]
opengeek submitted:

Resolved nested calls in revision 4637.

**Comment by shamblett** [comment]
shamblett submitted:

Thanks Jason
