### ISSUE TITLE
Sync the menu link texts of "Site" menu links with "Quick Links" where applicable. E.g. "New Document" on "Site" menu should be something like "Create New Document" in "Quick Links"

### ISSUE THREAD

**Issue by kongondo** [modxbot/migrate#1810]
kongondo created Redmine issue ID 1810

On the "site" menu, we have "new document" and on the quick links "create resource" yet they do the same thing. Could these link texts be synced so that they use the same terminology? It can be confusing the way it is. So, the menu item "New Document" on "Site" menu should be, IMHO, something like "Create New Document" in "Quick Links" so as to avoid confusion and also have uniformity. Thanks! /k

**Comment by splittingred** [comment]
splittingred submitted:

This would just require changing the text in the lexicon topic "topmenu" for those items (or adding them if they're not in it, and removing the legacy entries from the default topic.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4672
