### ISSUE TITLE
Lexicon entries always created with topic 'id of 1'

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1812]
shamblett created Redmine issue ID 1812

When creating an entry for a topic, the entry is always saved to the database with a topic identifier of 1, regardless of the real id of the topic. Create a namespace e.g 'tester'
Create a topic for namespace 'tester' e.g.'default'
Check the database for the id of the newly created topic, this was around 50 on my install
Create an entry for the 'default' topic
The database table lexicon_entries shows the entry saved with a 'topic' of 1, not the correct one.

**Comment by splittingred** [comment]
splittingred submitted:

When you change the namespace in the lexicon entries grid, you need to also change the topic. You're still on the 'default' topic for the core namespace. This is somewhat of a bug, related to:
 http://svn.modxcms.com/jira/browse/MODX-354

**Comment by shamblett** [comment]
shamblett submitted:

Yep, MODX-354 explains, I fell for this as well, when I now change namespace then click the 'topic' column I can select 'default', this being the 'default' for my docmanager namespace so it's OK.
