### ISSUE TITLE
"show all" and "hide all" buttons for expanding descriptive text in system settings and property sets

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1814]
bobray created Redmine issue ID 1814

Would be useful for new users exloring the system settings and everyone looking over the properties of a new snippet. Might be useful for packages too.

**Comment by splittingred** [comment]
splittingred submitted:

Added in r4660

**Comment by BobRay** [comment]
bobray submitted:

Confirmed excellent. FF3 & IE7.
