### ISSUE TITLE
Cannot get provider package list if behind a proxy

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1829]
shamblett created Redmine issue ID 1829

On selecting 'add new package, 'select a provider' select the MODX transport provider, then 'next' from here on to the package downloading page I get a loading box followed by a blank screen, i.e. no packages appear. I get this in the error log :_ &#91;2009-01-07 15:21:47&#93; (ERROR @ /revdev/connectors/workspace/providers.php) Error in getting a response from the server: http://wtf.modxcms.com/addons2.js This machine is behind a proxy server, if I define wtf.modxcms.com in my local hosts file the package list appears OK.

**Comment by splittingred** [comment]
splittingred submitted:

Does this still happen?

**Comment by shamblett** [comment]
shamblett submitted:

Yes, On r5455 of the revolution branch :- &#91;2009-07-21 07:52:45&#93; (ERROR @ /revdev/connectors/workspace/providers.php) Error in getting a response from the server: http://modxcms.com/assets/provider.js If I bypass the proxy it works Ok

**Comment by splittingred** [comment]
splittingred submitted:

Probably wont be able to get around this, tbh, unless you open up the proxy ports. This isn't, imo, a modx issue so much as a user configuration issue.

**Comment by shamblett** [comment]
shamblett submitted:

Yes I understand running MODx behind a proxy is not what most people do, I only do this on some of my dev boxes for instance. However it is possible to instantiate a jsonrpc_client with proxy parameters as it extends xmlrpc_client which supports this. Auto detection of proxy parameters could be tricky so it may be better to just add proxy settings to the system settings. If set, use them, if not don't, that way its up to the user. I'm sure the proxy settings could also be used elsewhere when we have them, the RSS feeds for example maybe. I'll trial this as soon as I can and see if there are any gotcha's here.

**Comment by shamblett** [comment]
shamblett submitted:

Ok, just quickly hacking my the proxy params into the getClient() function in modtransportprovider.class seems to work . What we need to do is plug in proxy settings in more managed way. I also have my snoopy class similarly hacked to take proxy settings. Maybe a seprerate JIRA on this for future tracking, where we can address the whole area at once.
