### ISSUE TITLE
Items in Element view remain on package removal

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1830]
shamblett created Redmine issue ID 1830

If you force remove a package that contains say a snippet when the element view is open and showing that snippet even though the package is successfully removed the snippet persists in the element view. If you click on it it you get, 'Error, snippet not found'. This condition persists until the element view tree is refreshed. I guess this would occur with all elements not just snippets. Should package removal force a refresh of tree views on display, or is it expected the user will do this manually?

**Comment by splittingred** [comment]
splittingred submitted:

It does refresh the trees after an uninstall or install. Perhaps the package you are uninstalling is broken. Please provide more information about that package.

**Comment by shamblett** [comment]
shamblett submitted:

Ok, it happens on removing the Andreas01 template from components and one other of my own I tested. If the templates are open in the element view the view remains the same after the removal, no refresh occurs. Note this is not install/uninstall as such, its package removal with the 'force removal' box checked if it makes a difference.

**Comment by splittingred** [comment]
splittingred submitted:

It shouldn't - I also cannot verify that the Andreas01 template package is up-to-date. I would assume it is not. Try with a more recent package from WTF. Note that none of the packages in modx-components are production-ready or stable, so if they don't work; well, that's to be expected.

**Comment by shamblett** [comment]
shamblett submitted:

OK, installed TinyMCE from WTF on a linux box, just to rule out the platform here, did a remove package, force removal with the element tree open and the TinyMCE plugin in view, the plugin stays at the end of console output and when you press OK, ie the fault seems to persist. As an aside I've sure I've asked this on the forums but if the modx-components packages aren't the ones in WTF then where is the code for the ones in WTF? Which code base should I be using to develop/report bugs on these packages.

**Comment by splittingred** [comment]
splittingred submitted:

WTF are previously compiled versions from modx-components - however, since modx-components is always in development, they may be newer than the builds on WTF. Please report bugs on WTF versions only at this time.
