### ISSUE TITLE
Cannot select TinyMCE as document editor

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1831]
shamblett created Redmine issue ID 1831

Succesfully built and installed TinyMCE 2.1.1-beta from modx-components rev 382. On editing documents the 'Editor To Use' selection can only be set to 'None', ie TinyMCE cannot be selected although the system settings correctly has this as the editor to use and is enabled.

**Comment by splittingred** [comment]
splittingred submitted:

Try clearing your cache?

**Comment by shamblett** [comment]
shamblett submitted:

OK, logged in cleared the cache, problem persists, logged back out and in again, problem still persists.

**Comment by splittingred** [comment]
splittingred submitted:

Does this happen when you try downloading the package through WTF/Package Installer, as well? I tried installing the package from the Package Downloader, and had no problems.

**Comment by shamblett** [comment]
shamblett submitted:

Ok I removed ny local install, selected 'add new package, selected 'select a provider' selected the MODX transport provider, when I 'next' from here on to the package downloading page I get a loading box followd by a blank screen, ie no packages appear so I can't test this. The URL its using is http://wtf.modxcms.com/addons2.js I get this in the error log :_ &#91;2009-01-07 15:21:47&#93; (ERROR @ /revdev/connectors/workspace/providers.php) Error in getting a response from the server: http://wtf.modxcms.com/addons2.js although I can get to http://wtf.modxcms.com no problem. I'll try this from another box.

**Comment by splittingred** [comment]
splittingred submitted:

Are you using alpha-6 or SVN? If alpha-6, then that's the issue - this has been fixed as of SVN.

**Comment by shamblett** [comment]
shamblett submitted:

OK, I'm using SVN, just tried this on a fully updated linux box(the windows box was a shade behind) and I get the package list OK so this looks good now. Installed TinyMCE from WTF, throws an install error which I believe is to do with ticket ADDON-31 but the install succeeds. System settings say editor to use is TinyMCE and that it is enabled, still can only select editor as 'none' on document resources i.e the fault persists.

**Comment by splittingred** [comment]
splittingred submitted:

A few q's: 1. Did you clear your cache after installing?
2. Can you verify the plugin exists and is active?
3. Can you verify the resource you are editing has the 'richtext' checkbox checked?

**Comment by shamblett** [comment]
shamblett submitted:

Ah! point 3 was the one, I didn't have this checked on the docs I tested. Ok working fine now thanks.
Although the 'editor to use' box is still empty and only 'none' can be selected. If you select this it turns off the TinyMCE editor
