### ISSUE TITLE
Creating a Resource with no Template results in an error in the log

### ISSUE THREAD

**Issue by Pont** [modxbot/migrate#1838]
pont created Redmine issue ID 1838

When creating a Resource before any Templates exist or creating a Resource with Template set to "Empty" creates the following error in the Error Log. &#91;2008-12-27 14:40:01&#93; (ERROR @ W:\www\modx\core\model\modx\processors\resource\create.php : 268) PHP warning: Invalid argument supplied for foreach() No visible error is shown and the Template is saved as it should be. Checking for an empty $tmplvars variable fixes the issue.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4589
