### ISSUE TITLE
Better message in property set popup dialog

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1842]
bobray created Redmine issue ID 1842

The current message, "Add Element to Property Set" is confusing, IMO. Since the property set is a set of properties, the message will suggest to some that an element is a property that's being added to the list. I think it would be easier to understand what's happening if this were "Attach Element to Property Set" or even beter, IMO, "Attach Property Set to Element." Since you've just selected the Property Set, putting it first makes sense and then saying what you're doing with it (attaching it to an element). IOW, "this property set will be available to that element." I'd also suggest changing the message on the main Property Set screen to: "You can also right-click on property sets in the tree to attach them to elements." I like "attach" better than "assign" for all these. I think it's because assign sort of implies a membership or categorization role that doesn't quite fit here, but I could live with assign of others prefer it. It might also be better to use "element" instead of "object" in the popup. Having it match the caption above would be good and it will help people learn what an element is.

**Comment by splittingred** [comment]
splittingred submitted:

Agreed on all counts.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4575
