### ISSUE TITLE
Cannot create a new user

### ISSUE THREAD

**Issue by mouton** [modxbot/migrate#1844]
mouton created Redmine issue ID 1844

Hi, When testing alpha6, I tried to create a new user. When I want to 'save' this new user, nothing happens. The log shows: &#91;2008-12-20 15:51:40&#93; (ERROR @ /modx/connectors/security/user.php) modUserProfile: Attempt to set NOT NULL field photo to NULL
 &#91;2008-12-20 15:51:40&#93; (ERROR @ /modx/connectors/security/user.php) modUserProfile: Attempt to set NOT NULL field blocked to NULL Shouldn't those fields be set to authorize null values? Thanks,
Kevin

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4590
