### ISSUE TITLE
After unstall using "uninstall package and all prior versions" the older versions still show as "installed" and MODx still thinks they are installed.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1846]
bobray created Redmine issue ID 1846

Steps to reproduce: Install SPForm 3.0.6
Install SPForm 3.0.7 Uninstall 3.0.7 with the "remove prior versions option." 3.0.6 still shows as installed and uninstalling it generates error messages (since it's not really installed).

**Comment by splittingred** [comment]
splittingred submitted:

Confirmed. Will look into this.
