### ISSUE TITLE
Add "lock" checkbox for default snippet properties

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1847]
bobray created Redmine issue ID 1847

It would help keep us from changing them accidentally and, more importantly, it would let us keep non-admin manager users from changing the default set while letting them edit the custom ones.

**Comment by splittingred** [comment]
splittingred submitted:

Added in r4782-r4783. Will add in permission-based ability to unlock later.

**Comment by splittingred** [comment]
splittingred submitted:

Added in permission and check in r4784.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed lockable. Did not test permissions.
