### ISSUE TITLE
Bug in reverting individual property to default.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1851]
bobray created Redmine issue ID 1851

If you try to revert a yes/no property to the default and the property above it in the grid is not a yes/no property, you get a duplicate property instead of reversion. It looks like this is only in the grid display, the action seems to be completed correctly. I don't know if this happens in IE7 because the Manager is still unusable in IE7.

**Comment by splittingred** [comment]
splittingred submitted:

I can't duplicate this. Is this on the latest version?

**Comment by BobRay** [comment]
bobray submitted:

Appears to be fixed.
