### ISSUE TITLE
Unpublished pages can always be reached through sendRedirect() in snippets.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1855]
bobray created Redmine issue ID 1855

An unpublished resource still shows in the browser via sendRedirect() in a snippet, even after clearing the cache, logging out, and clearing the browser cache and cookies.

**Comment by opengeek** [comment]
opengeek submitted:

Whoa! Thanks for catching this; I seem to have overlooked the fact that if no context policy was attached to the web context, all permissions would pass, including the check for view_unpublished. I'll have some commits for this soon once I work out the best way to finalize the solution. I may end up just attaching the default context policy to 'web' for the default Administrators group on new installation/upgrade from alphas.

**Comment by opengeek** [comment]
opengeek submitted:

This is resolved, but understand that in order for any context to properly reject requests for unpublished resources, the context must be assigned at least one Context policy (which is now added automatically to the web context for the Administrators group via setup) for each front-end context. Also note that deleted resources were also accessible in some cases and that too has been resolved.
