### ISSUE TITLE
Package installer flashes previous user input screen

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1858]
bobray created Redmine issue ID 1858

This barely qualifies as a bug. If you install one package, then install another, and both have user input screens, during the second install, the first package's user input screen will flash briefly before being replaced by the second one.

**Comment by splittingred** [comment]
splittingred submitted:

This is pretty much unfixable - and not really necessary to fix, anyway.

**Comment by BobRay** [comment]
bobray submitted:

Closing. My only concern was that users on slow connections might be disoriented by having the wrong screen up for a while.
