### ISSUE TITLE
PHx-filter not working with $modx->parseChunk

### ISSUE THREAD

**Issue by bruno** [modxbot/migrate#1859]
bruno created Redmine issue ID 1859

PHx-filter did not work with $modx->parseChunk added the parameter $chunkArr to
 &#91;code&#93; if ($chunk= $this->getChunk($chunkName)) &#91;/code&#93;
and did work on my first test.
 &#91;quote&#93; function parseChunk($chunkName, $chunkArr, $prefix='[ &#91;+&#39;, $suffix=&#39;&#93; ]') {
$chunk= '';
if ($chunk= $this->getChunk($chunkName &#91;color=red&#93; ,$chunkArr &#91;/color&#93; )) {
if(is_array($chunkArr)) {
reset($chunkArr);
while (list($key, $value)= each($chunkArr)) { $chunk= str_replace($prefix.$key.$suffix, $value, $chunk); }
}
}
return $chunk;
}
 &#91;/quote&#93;

**Comment by bruno** [comment]
bruno submitted:

There is no need for this. See also http://modxcms.com/forums/index.php/topic,31214.msg189283.html#msg189283

**Comment by opengeek** [comment]
opengeek submitted:

As updated by original reporter; this is not needed or supported.
