### ISSUE TITLE
Can`t edit context

### ISSUE THREAD

**Issue by MadeMyDay** [modxbot/migrate#1868]
mademyday created Redmine issue ID 1868

If editing the name or description and then saving of a context gives an error: Context not found with key: %s

**Comment by splittingred** [comment]
splittingred submitted:

I can't duplicate this problem. Can you give me some more information? 1. What is the context you are trying to edit?
2. Where are you editing it from? (What page in the manager?)
3. What is your server info? (PHP version, server, PDO extensions installed)
4. Anything in the core/cache/logs/error.log about this problem?

**Comment by MadeMyDay** [comment]
mademyday submitted:

Hi Shaun,
okay, now I know why... It is not possible to change the key of a context. This sounds alright to me, but then I shouldn`t have the possibility to edit the key in the edit view. I think there better should be the "name" of the context, which I can`t see or edit in editing mode. Log says: &#91;2008-12-02 10:24:16&#93; (ERROR @ /modx2alpha/connectors/context/index.php) modManagerLog: Attempt to set NOT NULL field item to NULL

**Comment by splittingred** [comment]
splittingred submitted:

Prevented editing of key in r4528.
