### ISSUE TITLE
Undefined constant when building packages

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1869]
shamblett created Redmine issue ID 1869

When running the build.transport.php packaging script this error is appearing in the output :- PHP Notice: Use of undefined constant MODX_BASE_URL - assumed 'MODX_BASE_URL' in /var/www/html/revdev/core/model/modx/modx.class.php on line 933 It doesn't affect the package building.

**Comment by shamblett** [comment]
shamblett submitted:

Also getting these now :- PHP Notice: Use of undefined constant MODX_MANAGER_URL - assumed 'MODX_MANAGER_URL' in /var/www/html/revdev/core/model/modx/modx.class.php on line 947
PHP Stack trace:
PHP 1. {main}() /var/www/html/revdev/core/packages/snippets/ultimateparent/_build/build.transport.php:0
PHP 2. modX->initialize() /var/www/html/revdev/core/packages/snippets/ultimateparent/_build/build.transport.php:24
PHP 3. modX->getConfig() /var/www/html/revdev/core/model/modx/modx.class.php:347
PHP Notice: Use of undefined constant MODX_ASSETS_URL - assumed 'MODX_ASSETS_URL' in /var/www/html/revdev/core/model/modx/modx.class.php on line 951
PHP Stack trace:
PHP 1. {main}() /var/www/html/revdev/core/packages/snippets/ultimateparent/_build/build.transport.php:0
PHP 2. modX->initialize() /var/www/html/revdev/core/packages/snippets/ultimateparent/_build/build.transport.php:24
PHP 3. modX->getConfig() /var/www/html/revdev/core/model/modx/modx.class.php:347
PHP Notice: Use of undefined constant MODX_CONNECTORS_URL - assumed 'MODX_CONNECTORS_URL' in /var/www/html/revdev/core/model/modx/modx.class.php on line 955
PHP Stack trace:
PHP 1. {main}() /var/www/html/revdev/core/packages/snippets/ultimateparent/_build/build.transport.php:0
PHP 2. modX->initialize() /var/www/html/revdev/core/packages/snippets/ultimateparent/_build/build.transport.php:24
PHP 3. modX->getConfig() /var/www/html/revdev/core/model/modx/modx.class.php:347

**Comment by splittingred** [comment]
splittingred submitted:

Could not reproduce. Is this still occurring?

**Comment by shamblett** [comment]
shamblett submitted:

It is, but looking again in some of my build.config.php files I have this :-
// define the MODX path constants necessary for core installation
define('MODX_BASE_PATH', dirname(dirname(dirname(dirname(dirname(dirname(dirname(_ FILE _))))))) . '/revdev/');
define('MODX_CORE_PATH', MODX_BASE_PATH . 'core/');
define('MODX_MANAGER_PATH', MODX_BASE_PATH . 'manager/');
define('MODX_CONNECTORS_PATH', MODX_BASE_PATH . 'connectors/');
define('MODX_ASSETS_PATH', MODX_BASE_PATH . 'assets/'); in some I only have the first line, not that this affects the fault but should we define all these or what should we define here? Is this just the way packaging works?

**Comment by splittingred** [comment]
splittingred submitted:

You need them all, just like the build.config.sample.php file. If you're still producing this error, post up the build script. I still can't get your bug to occur.

**Comment by opengeek** [comment]
opengeek submitted:

Actually, the only constants that need to be defined in the build.config.php are: define('MODX_CORE_PATH', '/path/to/your/modx/core/');
define('MODX_CONFIG_KEY', 'nameofconfig'); The MODX_CONFIG_KEY is optional and if not specified, it will use the default key (i.e. 'config'), but if you plan to maintain more than one configuration from a single core, specify a MODX_CONFIG_KEY with a value other than 'config'. Everything else is determined by the configuration file that gets loaded from the specified file in core/config/ (i.e. core/config/nameofconfig.inc.php).

**Comment by opengeek** [comment]
opengeek submitted:

I'm marking this resolved as it is not really a bug. This needs to be documented however for developers.

**Comment by BobRay** [comment]
bobray submitted:

I'm not sure agree. I think it might be considered an error in the logic of  config.inc.php.   If the PATH constants are defined, the URL constants won't be defined. I think the code is assuming that if MODX_BASE_PATH is set, MODX_BASE_URL has been set, but this is not the case for me when running outside of MODX.

e.g.:

<pre>
if (!defined('MODX_BASE_PATH')) {
    $modx_base_path= 'C:/xampp/htdocs/addons/';
    $modx_base_url= '/addons/';
    define('MODX_BASE_PATH', $modx_base_path);
    define('MODX_BASE_URL', $modx_base_url);
}
</pre>

If MODX_BASE_PATH is defined, MODX_BASE_URL will not be defined, even if it is currently undefined. I question whether this is the intention of the code.
