### ISSUE TITLE
Allow different user options input during install for upgrades, versus new install.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1870]
bobray created Redmine issue ID 1870

One simple way of doing it would be to just add tokens to the user input file: XPDO_TRANSPORT_ACTION_INSTALL: User input stuff BREAK;
XPDO_TRANSPORT_ACTION_UPGRADE: alternate user input stuff. BREAK; or it could be done more like a case statement that would fall through so you could do this if they were the same:
XPDO_TRANSPORT_ACTION_INSTALL:
XPDO_TRANSPORT_ACTION_UPGRADE: user input stuff.

**Comment by splittingred** [comment]
splittingred submitted:

Added in r4953. 'setup-options' now can be a script, that has access to $modx object, that can grab current values of whatever you need. Example: 'setup-options' => array(
'source' => $sources &#91;&#39;build&#39;&#93; .'setup.options.php',
), The php file must return the form HTML output.

**Comment by splittingred** [comment]
splittingred submitted:

This is also backwards-compatible; if you just specify a string for 'setup-options', it will just use that string.

**Comment by BobRay** [comment]
bobray submitted:

confirmed fixed
