### ISSUE TITLE
Cannot convert child document into a container

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1873]
shamblett created Redmine issue ID 1873

If a document resource which is a child of a container resource is edited and the 'Container' field is checked on the 'Resource Settings' tab and subsequently saved the child document remains as a child document, it is not changed into a container. On re-editing the 'Container' field is cleared. Basically you cant seem to create a container as a child of a container by editing the document properties, you can do this however if you create a document in the target container and click its 'Container' field.

**Comment by splittingred** [comment]
splittingred submitted:

This really needs to actually depreciate the notion of 'containers', since those aren't really relevant anymore.

**Comment by shamblett** [comment]
shamblett submitted:

Seems to be line 239 of \core\model\modx\processors\resource\update.php :- $_POST &#91;&#39;isfolder&#39;&#93; = $count_children > 0; If the resource has no children it will not make it a container, this of course stops people from doing this before they add children, they may know they want this resource to be a container and add the children later as in evo I believe. Simple fix is to remove this line unless of course this behaviour is intended.

**Comment by opengeek** [comment]
opengeek submitted:

Removed most of the code that automatically sets isfolder property based on presence or absence of child documents.
