### ISSUE TITLE
Parent Resource field uses a digit, should it be a name?

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1874]
shamblett created Redmine issue ID 1874

The Parent Resource field on the General Settings document tab shows the numeric id of the parent resource, would this not be better as a text field with the name of the resource as shown in the document tree rather than a number.

**Comment by splittingred** [comment]
splittingred submitted:

No, it wouldn't - names can be tricky, and non-UTF-8 characters would have issues. It would be best as a staticfield that uses some JS trick to grab it from a window or tree like the old one - but currently we postponed that until beta. The best way to assign parents is through drag/drop in the left tree.

**Comment by splittingred** [comment]
splittingred submitted:

Added in r4726
