### ISSUE TITLE
Document tree contains double entries on document creation

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1875]
shamblett created Redmine issue ID 1875

When creating a resource by right clicking on a container in the document tree and the resource is saved the document tree under the container is expanded(even if it wasn't in the first place). This expansion contains two entries for each document in the container. This is easily remedied by refreshing the document tree, this now correctly shows one entry per document.

**Comment by splittingred** [comment]
splittingred submitted:

Confirmed. That is a very odd bug.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4593
