### ISSUE TITLE
Dependency on zlib not pre-empted

### ISSUE THREAD

**Issue by fmilitao** [modxbot/migrate#1876]
unknown created Redmine issue ID 1876

I've just tried installing MODx on my test server, and got the following error when it tried to perform the install: "Abort pclzip.lib.php : Missing zlib extensions" This should ideally be highlighted in the pre-system check just before you press "Install" to pre-empt the failure.

**Comment by splittingred** [comment]
splittingred submitted:

Great catch. WIll work on this Monday.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4673
