### ISSUE TITLE
Readme file truncated on install.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1877]
bobray created Redmine issue ID 1877

SPForm's readme file (as shown during the install) was truncated at the e in René and I thought it was a character encoding issue, but everything at my site is in utf-8 and the character code for that letter is the same for utf-8 and latin1 anyway. Now the EZfaq file is being truncated as well. It has an example showing HTML code and it's truncated at the first "<." I suspect that the readme text is being sanitized with a fairly limited regular expression or being run through a PHP sanitizing function. (or modOutputFilter?), unless there's just something weird about my local setup. The htmlentities() function is known to cause trouble with accented characters if the charset isn't specified, but I can't find any case of that in the code. I found this: function smarty_modifier_escape($string, $esc_type = 'html', $char_set = 'ISO-8859-1'), though I can't find it being called anywhere and I don't think it would cause the problem. I wonder if the default should but utf-8, though.

**Comment by splittingred** [comment]
splittingred submitted:

I can't reproduce this no matter how hard I try. Even installed latest SPForm...closing until we get some good example test cases.
