### ISSUE TITLE
Resource General Settings field error

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1881]
shamblett created Redmine issue ID 1881

On update to svn rev 4489 a spurious field is now present on the General Settings tab of document resources. In between the fields 'Uses Template' and 'Menu Title' another field has appeared named ':', this consists of a text box with a digit in it, usually 0 but I have seen it change

**Comment by splittingred** [comment]
splittingred submitted:

It's "Parent Resource"...you'll need to run a Lexicon Reload. Anytime you see &#91;LEXICON RELOAD REQUIRED&#93; in a commit message, you'll need to do this. To do it, go to the Lexicon Management page, then click the "Reload Core Entries From Base" button. It'll take a few seconds, and then that will fill out your lexicon strings.

**Comment by shamblett** [comment]
shamblett submitted:

Yep, this fixed it. I got this in the console output :- 'PHP notice : Undefined variable : foc'
