### ISSUE TITLE
Snippet properties modified with "update" don't get the visible dirty flag

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1882]
bobray created Redmine issue ID 1882

If you modify a snippet property by double-clicking (only yes/no props can be edited this way in FF3 and IE7), it gets the red flag. If you modify any property by right-clicking and selecting "update property," it doesn't. The unflagged properties are seen as dirty internally and are updated on save so it's just a UI issue.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4606

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
