### ISSUE TITLE
Resource created during install gets no template

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1883]
bobray created Redmine issue ID 1883

Resources created during an install used to get the default template (at least I think they did), but now they get no template at all so they look pretty lame when previewed.

**Comment by splittingred** [comment]
splittingred submitted:

This will have to be handled via a resolver - you'll have to set the resource's template field to $object->xpdo->config &#91;&#39;default_template&#39;&#93; ;

**Comment by BobRay** [comment]
bobray submitted:

Won't be fixed.
