### ISSUE TITLE
Console output during package installation cannot be saved.

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1885]
shamblett created Redmine issue ID 1885

The console output box displayed on installing packages has a button option to 'copy to clipboard'. This works on linux, but not on the environment above, i.e. windows.

**Comment by splittingred** [comment]
splittingred submitted:

Maybe a good thing to output to a .log file.

**Comment by splittingred** [comment]
splittingred submitted:

Moving this to a later beta, since now you can just select the text and copy it.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5753 by providing "Download to File" link
