### ISSUE TITLE
Removing a package containing a template does not remove document associations

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1886]
shamblett created Redmine issue ID 1886

When removing a package through the package management page, if the package contains a template and that template has been previously assigned to a document or documents this link is not removed. The site_contents table template column retains the association to the id of the removed template, hence breaking when displayed. This is not remedied on re-installation of the template as its id in the template table changes.

**Comment by splittingred** [comment]
splittingred submitted:

What do you mean by "previously assigned"? When was it previously assigned?

**Comment by shamblett** [comment]
shamblett submitted:

Ok, I've just run through this again from the top :- 1. Install template x using the package manager
2. Create a document that uses template x
3. View the document, this is all OK.
4. Remove template x's package using package manager(force removal here). The document using template x still shows its template as the now removed one. Also looking in the database the category that I created for the template has been removed, but not the template itself, it is still in site_templates. No errors are reported by package manager on the removal. If you now delete the template from the database(which you have to do to re-install it) the documents template field reads as an integer e.g. '4' or whatever the id of the removed template was. Build script attached in case I've missed something at this stage.

**Comment by shamblett** [comment]
shamblett submitted:

Build script I'm using for the template above.

**Comment by splittingred** [comment]
splittingred submitted:

This isn't necessarily a MODx core problem; you'll have to add a resolver in your script (to execute on uninstall) that removes those associations.

**Comment by shamblett** [comment]
shamblett submitted:

Yes, uninstallation should be considered while packaging, how would you know however that this particular scenario would need an uninstall resolver whilst other parts of the package are just removed by the core? Could you derive this from the XPDO foreign key references somehow?
