### ISSUE TITLE
Bad require in php resolver fubars Package Installer

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1888]
bobray created Redmine issue ID 1888

Putting require_once("xxx"); (where 'xxx' is missing) in a php resolver script hangs the install and makes uninstalling impossible. You get an error message about the bad require_once, but the package appears to be mostly installed and thinks it's not installed. This may be true for other PHP fatal errors as well. Doing a reinstall with a repaired script doesn't work (you get the same error again) probably due to MODX-#518 (workspace cache not cleared when the site cache is cleared). Forcing Removal of the script doesn't work either. The only out is to manually delete the package contents and manually clear the workspace cache. There may not be a way of recovering gracefully from PHP fatal errors in an install script and they are unlikely to affect end users. Fixing MODx-#518 would probably help make this less of a problem for developers, though.

**Comment by splittingred** [comment]
splittingred submitted:

Unfortunately PHP4 doesn't support Exception handling.
