### ISSUE TITLE
Clearing site cache doesn't clear core/cache/registry/mgr/workspace/package dir

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1889]
bobray created Redmine issue ID 1889

In the case of a bad install/uninstall, files left there can make it impossible to uninstall or, after a manual uninstall, to install a repaired package (obsolete errors keep appearing and the install hangs).

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4472

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
