### ISSUE TITLE
Can no longer publish documents

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1893]
shamblett created Redmine issue ID 1893

Updated to SVN revision 4448, can't sem to publish documents now. I edited a document and when saved noticed in the tree view that it had reverted to being not published, on inspection a published and unpublished date were filled in, both being 1970-01-01, if clear them and tick published on saving they just reset to 1970-0101 and publish is unticked. If I set todays date in publish and alater one in un-publish I can get the document tp publish, but when I re-edit both date fields have reverted.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4458

**Comment by shamblett** [comment]
shamblett submitted:

Confirmed, the issue is now fixed on my setup.
