### ISSUE TITLE
Packages directory needs to be writable for install to succeed

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1895]
shamblett created Redmine issue ID 1895

During revolution installation from SVN the packages subdir of core needs to be writable or when 'Install' is pressed the installation fails with the following debug message from XPDO :- &#91;2008-11-18 14:30:08&#93; (ERROR @ /revolution/setup/index.php) Could not unpack package: /var/www/html/web/revolution/core/packages/ is not writable. SIG: This is not explicitly checked for on the summary page although it is unclear why this should be, the core is already unpacked, also the installation doesn't actually write anything into this directory. The error is generated somewhere around line 307of /setup/includes/modinstall.class.php

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4469
