### ISSUE TITLE
Package Installer quirks in IE7

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1897]
bobray created Redmine issue ID 1897

You have to click twice on "install package"
License agreement comes up with a tiny, blank window for the license and the "I disagree" button is not visible.
Readme is shown in the same tiny window &#8211; almost impossible to read the file.
Sometimes, only the left side of the console's right scroll bar is visible.
Sometimes no console is shown at all.
In either case, a gray rectangle is left on the screen after the install and the Packages panel is dead.
After the install, the MODx main menu is gone until you refresh the page in the browser, which takes you to the "home" panel. The missing main menu also happens after changing snippet properties and saving &#8211; This sometimes happens in FF too. Just to make sure, I saw all of these on a fresh build/install (emptied the whole DB, but did not delete files or do a fresh checkout).

**Comment by splittingred** [comment]
splittingred submitted:

I'm afraid that getting IE7 to work is going to be a project all in itself.

**Comment by BobRay** [comment]
bobray submitted:

I believe it. It's still crashing Apache in the Manager often enough that I've had to stop using it except for the occasional test.

**Comment by splittingred** [comment]
splittingred submitted:

This should be fixed now as of the new Package Management UI.
