### ISSUE TITLE
Local packages still show "update" as an option.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1904]
bobray created Redmine issue ID 1904

Option still shows for SPForm which has never been anything but a local package.

**Comment by splittingred** [comment]
splittingred submitted:

In your packages grid, what does the 'Provisioner' column have for that package?

**Comment by BobRay** [comment]
bobray submitted:

It shows a 0. All my packages show 0 for that field (and a 0 in DB for provider).

**Comment by splittingred** [comment]
splittingred submitted:

You sure you have the latest SVN of core/model/modx/processors/workspace/packages/getlist.php ? I can't replicate this on mine, and the check: if ($package->get('provider') != 0) { should prevent that from showing.

**Comment by BobRay** [comment]
bobray submitted:

Sorry, maybe a cache issue. It's gone now.
Confirmed in FF3 and IE7.
