### ISSUE TITLE
Package Builder GUI still shown in Tools Menu

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1905]
bobray created Redmine issue ID 1905

It's still there but gives an error when selected (r4428).

**Comment by splittingred** [comment]
splittingred submitted:

BobRay - this only happens on your install, since you're using old data. You'll have to remove it manually (it's a stray modMenu object in modx_menus), but future installs wont have this problem.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed. Closing.
