### ISSUE TITLE
Package uninstall then install leaves old Resources and Elements in the tree.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1906]
bobray created Redmine issue ID 1906

When you uninstall and reinstall a package, the original resources or elements are still shown in the tree. Trying to preview a resource or edit anything fails . Refreshing the tree first fixes it but you have to refresh both trees separately. Refreshing one still leaves the other one out of date.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4437. All trees now refresh.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
