### ISSUE TITLE
Menu index field missing from Resource create/edit screen.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1907]
bobray created Redmine issue ID 1907

Title says it all.

**Comment by splittingred** [comment]
splittingred submitted:

It has been removed purposely - you now reorder resources by drag/dropping them in the tree.

**Comment by BobRay** [comment]
bobray submitted:

I'm somewhat disappointed in this. I liked setting menu index to 999 for a document I always want at the end of the menu and not having to drag it down to the bottom every time I create a new document. Also, dragging things around seems to keep turning resources into containers &#8211; even when there's only one level below "web." I have to edit the document to undo that.
