### ISSUE TITLE
Cannot save document if published date set on site start page

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1912]
shamblett created Redmine issue ID 1912

When adding a published date to the start page of the site and saving the document this error is generated :- 'document_err_unpublish_sitestart_dates' If the published date is removed the document saves OK. This does not happen on initial createion, ie creation with a published date is OK. Seems to be to do with line 187 in \core\model\modx\processors\resource\update.php :- if ($resource->get('id') == $modx->config &#91;&#39;site_start&#39;&#93; && ($_POST &#91;&#39;pub_date&#39;&#93; != '0' || $_POST &#91;&#39;unpub_date&#39;&#93; != '0')) {
return $modx->error->failure($modx->lexicon('document_err_unpublish_sitestart_dates')); Ok, not sure what this is for, do we ever need an unpublish date for a site start page, or any page for that matter? Also the error message itself is terse to say the least

**Comment by opengeek** [comment]
opengeek submitted:

Scheduling a publish date for the site_start page is an error and it is preventing you from causing problems with your site. The error message does need to be fixed.

**Comment by Phize** [comment]
phize submitted:

MODx 0.9.6.x also have this issue... when the future date is set to published date on site start page,
preventing it is good behavior, I think. But even if we set "the past date" to published date, they are prevented..
