### ISSUE TITLE
References to nonexistent directory in filetree.css

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1915]
bobray created Redmine issue ID 1915

The file manager/assets/modext/util/filetree/css/filetree.css has several references to the ../ext directory which isn't there.

**Comment by BobRay** [comment]
bobray submitted:

Corrected typo.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4592

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed
