### ISSUE TITLE
Package Builder can't handle more than one object of each type

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1916]
bobray created Redmine issue ID 1916

When I include more than one snippet and more than one chunk in a build script, only the last of each is installed and, if a resover is attached to one of the elements that didn't install, the resolver doesn't execute. If I use exactly the same build script but with one snippet and one chunk, both are installed fine (complete with properties for the snippet) and the resolver transfers all files. In either case the lexicon tranfers properly. I tried this with a build script written with a loop for creating the elements. When that didn't work, I created a traditional build script with no loop and all the elements created in sequence and got the same result.

**Comment by BobRay** [comment]
bobray submitted:

Looking in the core/packages directory, I see that the manifest shows all 6 elements but the source files are not there for the ones that don't transfer.

**Comment by splittingred** [comment]
splittingred submitted:

BobRay, Make sure you're setting a primary key for each object...say if you have 3 snippets, then make sure to: $snippet1->set('id',1);
$snippet2->set('id',2);
$snippet3->set('id',3);
...etc... And make sure that XPDO_TRANSPORT_PRESERVE_KEYS = false. The package builder creates its vehicles files based on the PK. Those IDs wont propagate into the actual installed packages, but are used as placeholders to distinguish between packages.

**Comment by BobRay** [comment]
bobray submitted:

Yes! It works fine now. Is it ok if there is a sequential id set for every element created as long as they're all unique? ie. the snippets have ids 1 and 2 and the chunks 3, 4, 5, and 6, and the resources 7 and 8, etc?
