### ISSUE TITLE
Package dates show as "false" in Package Management

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1917]
bobray created Redmine issue ID 1917

I marked this a major because it could make users think an installed package is not installed. Is shows "False" in the installed column.

**Comment by splittingred** [comment]
splittingred submitted:

BobRay, are you using SVN for this? My latest SVN version doesn't show false - it shows "Not Installed" if it hasnt been installed, or the formatted datetime if installed. I can't seem to replicate this.

**Comment by BobRay** [comment]
bobray submitted:

Sorry, I should have been clearer. The uninstalled ones show "Not Installed" for the installed column but all other fields show "false" &#8211; installed or not. No dates are showing in FF3 or IE7 at all. This just happens in Package Management. I have r4414 installed.

**Comment by splittingred** [comment]
splittingred submitted:

I still don't get this in my install. How'd you get this to happen? Have a SS?
