### ISSUE TITLE
Double-click editing of snippet properties.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1919]
bobray created Redmine issue ID 1919

I'm not sure about this because I don't know what's supposed to happen. The only thing that's editable through double-clicking in IE7 and FF3 in the snippet properties grid is the value field for Yes/No types. Names, IMO, shouldn't be editable that way but I'm not sure about types. I think the value field of all types should be editable this way. Even if the other fields and types are not meant to be edited, there's a small bug that makes the fields turn white and show a cursor briefly in FF3 when double-clicked on. That doesn't happen in IE7.

**Comment by splittingred** [comment]
splittingred submitted:

Prevented name field from dbl-click edit in r4403. I can't replicate the 'white' clicking bug, but I bet it's a windows issue, and as long as it's not breaking things I'm sure it's okay.

**Comment by BobRay** [comment]
bobray submitted:

Now the "white" double-click effect appears in both FF3 and IE7 so at least we're consistent . If you look closely, there's a vertical cursor that appears just after the end of the value. It only happens on the value field now. Is it possible to pop up a small edit window for the value of non-Yes/No type values on double-click? That would solve (or hide) the problem.

**Comment by BobRay** [comment]
bobray submitted:

Another user has reported this issue as an annoyance to I thought I'd reopen it, since it's not just me.

**Comment by amdbuilder** [comment]
amdbuilder submitted:

I think I would be that other user so... I just installed the SVN from Saturday and noticed if you double click on a text based field (ex: change site name) I am unable to edit the value. I only tested in FF3 (primary browser).

**Comment by Kleist** [comment]
kleist submitted:

I've got the issue in Safari 3.2.1 on Mac OS X 10.5.6. Runnning r4731.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4733.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed IE7/FF3.

**Comment by BobRay** [comment]
bobray submitted:

Just found out that double-click doesn't work to edit properties with type integer.

**Comment by splittingred** [comment]
splittingred submitted:

Works for me - can you try again with latest SVN?

**Comment by BobRay** [comment]
bobray submitted:

It works, but the text is flush right in a very wide input field in FF 3.5.6.
