### ISSUE TITLE
"Delete setup directory" doesn't

### ISSUE THREAD

**Issue by fmilitao** [modxbot/migrate#1925]
unknown created Redmine issue ID 1925

In alpha-5, when you go through setup and check the "delete setup directory" box - the setup directory remains after the installer is finished. When you then login to the manager, you get a warning about the setup directory still existing. The obvious workaround is just to delete the setup directory manually. The apache user has full read/write/execute access to this directory so there's no reason it shouldn't have been deleted.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4475.
