### ISSUE TITLE
Sorting columns in snippet properties grid resets column widths

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1926]
bobray created Redmine issue ID 1926

If you change the column widths in the grid and sort, the colum widths stay the same, but if you sort when you first visit the grid, they change. Also, the value column doesn't extend to the right of the grid when you first visit so some values can be cut off. Once you do a sort, it does extend all the way to the right. It also extends after you do a save.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4399

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed IE7, FF3.
