### ISSUE TITLE
Can't change lexicon entries with dialog.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1927]
bobray created Redmine issue ID 1927

Editing lexicon entries in the dialog results in a "topic not found" on save. Probably related, dialog in a non-core namespace shows all the core topics in the drop-down and shows a number as the current topic. I thought maybe the it was trying to save the core "default" topic under other namespaces but the core lexicon entries can't be saved either. Editing with double-click works.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4397

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed .
