### ISSUE TITLE
First snippet property accessed in the grid shows no value.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1928]
bobray created Redmine issue ID 1928

After going to the snippet properties tab, if you right click on a property and select "update" the dialog will show with the value field as blank.
If you click on "cancel" then right-click and select "update" the value shows. This only happens with the first one visited. After that, it's fine. If you click on "cancel" then right-click and select "update" the value shows. If the user clicks on "Done" instead of "Cancel" with the empty value field showing, the value is lost (i.e, the property is saved with an empty value field) so it's potentially a serious problem.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4398

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed. FF3, IE7.
