### ISSUE TITLE
Errors when contexts have _ in the name

### ISSUE THREAD

**Issue by fmilitao** [modxbot/migrate#1932]
unknown created Redmine issue ID 1932

When a context has an _ in the name, MODx stops parsing the resource tags (e.g. [ &#91;*content&#93; ]) for all resources in that context. A side effect of this is that when you move a document out of the web context to a context with an underscore, the document's context_key in the modx_site_content table is set to the part of the context before the underscore, and documents in the web context have their context_key set to 0 (zero.) As discussed on http://modxcms.com/forums/index.php?topic=30353

**Comment by splittingred** [comment]
splittingred submitted:

Pushing this to 2.0-rc1.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5124 - contexts cannot be created with _ in name.
