### ISSUE TITLE
Manager main menu disappears

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1936]
bobray created Redmine issue ID 1936

Certain actions sometimes cause the MODx top menu to disappear (Site Components, Security, etc.). Saving snippet properties after modifying one at the bottom of a long list of them (where the property is below the bottom of the initial properties screen) does it the most reliably but I sometimes see it with selecting "edit" from the right-click menu in the tree. Reloading the page fixes it but takes you back to the home screen in the Manager.

**Comment by splittingred** [comment]
splittingred submitted:

I can't duplicate this - and I think I've fixed the problem scenarios (when an '<a>' tag has '#' as its href).

**Comment by BobRay** [comment]
bobray submitted:

I've been seeing this with some regularity in separate installs with both IE7 and FF3. I'll let you know if I see it again.
