### ISSUE TITLE
Other than wayfinder all packages report  no vehicle

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#1947]
wshawn created Redmine issue ID 1947

Package found...now preparing to install.
Workspace environment initiated, now installing package...
Attempting to install package with signature: tinymce-2.1.0-beta3
Grabbing package workspace...
Could not install package with signature: tinymce-2.1.0-beta3
No vehicles are defined in the transport package (tinymce-2.1.0-beta3) manifest for installation Package found...now preparing to install.
No vehicles are defined in the transport package (personalize-2.0.97-beta1) manifest for installation
Could not install package with signature: personalize-2.0.97-beta1
Workspace environment initiated, now installing package...
Grabbing package workspace...
Attempting to install package with signature: personalize-2.0.97-beta1 Grabbing package workspace...
Package found...now preparing to install.
No vehicles are defined in the transport package (breadcrumbs-0.9-d) manifest for installation
Could not install package with signature: breadcrumbs-0.9-d
Workspace environment initiated, now installing package...
Attempting to install package with signature: breadcrumbs-0.9-d I also never see the accept license, additional options, or the readme screens from my Suse 11 with firefox 3.0.3 I have attempted local download and installs, as well as using a provision. Both return the same errors. Wayfinder did install.. Excluding names, I see no differences between wayfinder's vehicle and breadcrumb's

**Comment by splittingred** [comment]
splittingred submitted:

We redid the package vehicle structure since alpha-5 due to some problems we were running into. I'll see if I can get working versions of those packages up and running soon for the svn version, and we should have an alpha-6 on the way as well.

**Comment by splittingred** [comment]
splittingred submitted:

This also seems to have to do with uninstalling of lexicons and other related objects. We've found a design flaw if objects already exist on install. Working on a solution to not remove objects that already existed during install - which should clear up most issues.

**Comment by splittingred** [comment]
splittingred submitted:

Packages online via the download panel wont work in alpha-6 until we release alpha-6 officially. We've also fixed in r4442 the bug with keeping pre-existing objects should an install run into them.
