### ISSUE TITLE
Can't save snippet after visit to properties page

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1955]
bobray created Redmine issue ID 1955

Steps to reproduce: Click on the properties tab of the snippet create/edit screen
Click on "Create Snippet Property"
Click on "Cancel" Snippet can no longer be saved. Error message popup: Array ( &#91;action&#93; => update &#91;modx-ab-stay&#93; => stay &#91;properties&#93; => [] &#91;id&#93; => 6 &#91;name&#93; => spfconfig &#91;description&#93; => SPForm configuration file &#91;category&#93; => 1 &#91;snippet&#93; => )

**Comment by BobRay** [comment]
bobray submitted:

Bigger problem than I thought. I can't save any edited snippet, even a newly created one. The initial save on creation is ok but any subsequent edit and save gets the error above. Changed to "critical."

**Comment by BobRay** [comment]
bobray submitted:

See line 11 of core/model/modx/processors/element/snippet/update.php

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4354. Was fixed in the revolution-elements/ branch, but not in revolution/
