### ISSUE TITLE
Edit resource page is blank

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1969]
bobray created Redmine issue ID 1969

Brand new checkout and install of r4322. I can create a new resource and save its content. It shows up in the tree but when I try to edit it, I get a completely blank right panel. I can right-click on it in the tree and select "view" and everything looks fine until I try to edit it &#8211; completely blank panel again. Happens in both IE7 and FF3. I can preview the document, so the content is there. I thought I might have a corrupt checkout, so I deleted everything and dropped all tables in the DB, did another checkout, build, and setup &#8211; same result. This is also happening in another site I recently updated.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4323.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed - IE7/FF3
