### ISSUE TITLE
Package won't install in FF3

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1972]
bobray created Redmine issue ID 1972

The install process goes along and the new windows appear, but when I click on "Finish" I get a popup with this message and an OK button. installing: ({signature:"captcha-3.0.2-beta", created:false, updated:"", installed:null, state:1, workspace:1, provider:0, disabled:false, source:"captcha-3.0.2-beta.transport.zip", manifest:false, attributes:false, menu: &#91;{text:"Update Package", handler:"this.update"}, {text:"Install Package", handler:"this.install"}, "-", {text:"Remove Package", handler:"this.remove"}&#93; }) Clicking on OK, just takes me back the the screen with the "Finish" button.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4308

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
