### ISSUE TITLE
Package management is dead in IE7

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1973]
bobray created Redmine issue ID 1973

In IE7, selecting "Add new package" in r4307 brings up the dialog, but it's grayed out and won't function. Works fine in FF3.

**Comment by BobRay** [comment]
bobray submitted:

Same thing with "Iinstall package." After "add new package" in FF, the new package shows up in IE7 but "Install Package" brings up a grayed-out dialog.

**Comment by splittingred** [comment]
splittingred submitted:

I think I got the dialogs at least loading...but it seems that IE hates Javascript. The tree for the package downloader wont expand its nodes. This is ridiculous.

**Comment by splittingred** [comment]
splittingred submitted:

Duplicate of # MODX-510

**Comment by BobRay** [comment]
bobray submitted:

Duplicate.
