### ISSUE TITLE
Can't uninstall captcha package, then can't install new version

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1974]
bobray created Redmine issue ID 1974

Uninstall fails for captcha 1.0-beta. This package was built with an earlier version of package builder (via script). Install then fails for 3.02-beta. Here's the console output for the uninstall (second attempt): Finding package with signature: captcha-1.0-betaPackage found. Preparing to uninstall.Finding package with signature: captcha-1.0-betaPackage found. Preparing to uninstall.No class specified for loadClassProblem instantiate object from vehicle: xPDOVehicle Object ( &#91;payload&#93; => Array ( ) ) No class specified for loadClassProblem instantiate object from vehicle: xPDOVehicle Object ( &#91;payload&#93; => Array ( ) ) No class specified for loadClassProblem instantiate object from vehicle: xPDOVehicle Object ( &#91;payload&#93; => Array ( ) ) No class specified for loadClassProblem instantiate object from vehicle: xPDOVehicle Object ( &#91;payload&#93; => Array ( ) ) No class specified for loadClassProblem instantiate object from vehicle: xPDOVehicle Object ( &#91;payload&#93; => Array ( ) ) No class specified for loadClassProblem instantiate object from vehicle: xPDOVehicle Object ( &#91;payload&#93; => Array ( ) ) Error occurred during uninstall.

**Comment by BobRay** [comment]
bobray submitted:

Deleting the plugin manually let me install the new version, but I still can't remove the old version from the workspace grid. Grabbing package to remove...Successfully grabbed package. Now attempting to remove transport zip...Transport zip was not found and could not be removed from the core/packages directory.Attempting to remove extracted transport directory...Transport directory was not found and could not be removed from the core/packages directory.No class specified for loadClassProblem instantiate object from vehicle: xPDOVehicle Object ( &#91;payload&#93; => Array ( ) ) No class specified for loadClassProblem instantiate object from vehicle: xPDOVehicle Object ( &#91;payload&#93; => Array ( ) ) No class specified for loadClassProblem instantiate object from vehicle: xPDOVehicle Object ( &#91;payload&#93; => Array ( ) ) No class specified for loadClassProblem instantiate object from vehicle: xPDOVehicle Object ( &#91;payload&#93; => Array ( ) ) No class specified for loadClassProblem instantiate object from vehicle: xPDOVehicle Object ( &#91;payload&#93; => Array ( ) ) No class specified for loadClassProblem instantiate object from vehicle: xPDOVehicle Object ( &#91;payload&#93; => Array ( ) ) Error occurred during uninstall.Error removing package with signature: [ &#91;+signature&#93; ]

**Comment by splittingred** [comment]
splittingred submitted:

This seems to be a captcha-only issue. Not sure why, though. Will look into it later.

**Comment by BobRay** [comment]
bobray submitted:

If it's not happening to other packages, it's probably not worth your time at this point, although what happens when packages created with earlier versions of package builder are uninstalled is worth thinking about. And the uninstaller seems to choke when a previous uninstall was only partially successful. Maybe it could be more flexible in that case. It's easy to get into a situation where you can't uninstall an older package and can't re-install it or install a newer version of the same package. It's happened to me a number of times. I learned of another possible reason for the problem with uninstalling the captcha package (and why it would be specific to captha) when I tried to uninstall the package manually. Under Windows, FreeType likes to keep the .ttf files open indefinitely, even after leaving MODx and closing the browser. That means it's impossible to delete them. Closing Apache or rebooting before the uninstall might have worked.

**Comment by splittingred** [comment]
splittingred submitted:

BobRay, I've added in a 'force' ability for removing packages. If checked, it will remove packages regardless of errors. This might help a bit.

**Comment by splittingred** [comment]
splittingred submitted:

Seems this might be an issue with uninstall() in the transport package class. We're working on a solution now. I'm using your SVN captcha stuff for testing, if you don't mind.

**Comment by BobRay** [comment]
bobray submitted:

Be my guest. I've been digging into it and the new and improved console error messages suggest a problem with the lexicon. The only things I could come up with are that the quotes in my lexicon file are single quotes and that there's a couple of escaped single quotes in them ( \' ). But I wouldn't think that would cause that many errors in the uninstall. Let me know if it's anything I did incorrectly.

**Comment by splittingred** [comment]
splittingred submitted:

Nah, it's not you. It's definitely something to do with xPDOTransport and modTransportPackage.

**Comment by splittingred** [comment]
splittingred submitted:

Does this still occur?

**Comment by BobRay** [comment]
bobray submitted:

I don't have a copy of captcha 1.0 any more to test it. I'm closing this and will create a new issue if something like this occurs in the future.
