### ISSUE TITLE
Can't create Resources

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1978]
bobray created Redmine issue ID 1978

Result of trying to create a new resource is: Fatal error: Call to undefined method modManagerRequest::hasFormValues() in C:\xampp\htdocs\MODx097\manager\controllers\resource\create.php on line 30 It appears that hasFormValues() was recently removed from the modManagerRequest class, but is still called in the three create.php files for documents, symlinks, and weblinks. Note that there is some following code dealing with restored form values that should probably also be removed from the create.php files.

**Comment by BobRay** [comment]
bobray submitted:

hasFormValues() is also called when creating static resources. The only four files that need correcting are: manager/contollers/resource/
&#8211; resource/create.php
&#8211; staticresource/create.php
&#8211; weblink/create.php
&#8211; symlink/create.php

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4296

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
