### ISSUE TITLE
Provide package install/usage info to user.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1982]
bobray created Redmine issue ID 1982

In 0.9.6, users get information on a package by reading the package's screen at the repository. Since we no longer have that functionality in Revolution, we need standard (hopefully easy) way for users to get information on packages without making them do a web search on their own or wander through the file system looking for a readme file. One possiblity is to put a plus sign on the left side of the workspace packages grid and have it open a "description" as we do in System Settings. The description would, ideally, give a short description and multiple links to support pages (Wiki, author's site, tutorials, etc.). These could be inserted via a file, db, or direct input as part of the vehicle in the package builder script. This doesn't solve the problem of how users investigate packages and find out what they do before downloading them, but it would be a handy feature.

**Comment by splittingred** [comment]
splittingred submitted:

Before-download is currently already solved - if you try to download a package from WTF in alpha-5, you'll see on the right-hand side a name and description and other details...those will be filled out based on the provider's data. We're thinking about other solutions for post-download. Good suggestions - we'll get back to you on this one.

**Comment by splittingred** [comment]
splittingred submitted:

Working on adapting xPDOTransportPackage/modTransportPackage to allow for license agreements, readme, and 'setup options' to be put inside packages. These will 'popup' before installation proceeds, allowing you full flexibility on designing your packages. Think of it like .msi installer abilities.

**Comment by BobRay** [comment]
bobray submitted:

That sounds great. It would also be good to provide something like I described above that would be permanently available if it's possible.

**Comment by splittingred** [comment]
splittingred submitted:

Yeah we might be able to get a 'View Readme' context menu option for each package, as well.

**Comment by BobRay** [comment]
bobray submitted:

I had in mind just duplicating the plus sign feature in System Settings, but allowing links in the description.

**Comment by splittingred** [comment]
splittingred submitted:

Yeah, that would require some non-standard code. Not sure if we want to go that way.

**Comment by splittingred** [comment]
splittingred submitted:

Added in r4404.
