### ISSUE TITLE
MODx beeps at me when I log in in IE7

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1999]
bobray created Redmine issue ID 1999

If I log in by hitting the enter key after typing my password, IE7 gives me a "ding" sound. I usually have my sound on mute so I just noticed it. If I log in by clicking with the mouse &#8211; no ding. FF3 doesn't ding either way.

**Comment by splittingred** [comment]
splittingred submitted:

You're just messing with me now, BobRay.

**Comment by BobRay** [comment]
bobray submitted:

No, really . . . I keep thinking someone's at the door.

**Comment by splittingred** [comment]
splittingred submitted:

Isn't happening to me, so closing this.
