### ISSUE TITLE
Description field is cleared on update setting in "system settings"

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2002]
bobray created Redmine issue ID 2002

When updating a system setting, via right-click, all the current values appear in the dialog except description, which is blank.

**Comment by splittingred** [comment]
splittingred submitted:

Part of a bigger issue with creating default topics and assigning them correctly. Fixed in r4251.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
