### ISSUE TITLE
Provide name of element in delete confirm dialog

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2018]
bobray created Redmine issue ID 2018

It would be useful to see the name of the item you're deleting in the delete confirmation dialog in case you've accidentally selected the wrong item to delete.

**Comment by splittingred** [comment]
splittingred submitted:

Must have missed this; this was fixed a while back.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
