### ISSUE TITLE
Quirks in "duplicate"

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2021]
bobray created Redmine issue ID 2021

Chunks, plugins, and snippets can't be duplicated from the button on the edit panel, only from the tree. Also, duplicating templates and resources is inconsistent. The item is duplicated the old way (automatically with "duplicate of x" as the title) from the right-hand screen but with a dialog box for the new title on right-click from the tree. It should probably be consistent

**Comment by splittingred** [comment]
splittingred submitted:

Resolved in r4228 by removing the buttons until we can come up with a more elegant and working solution. Deletes and duplicates can still be done via tree.
