### ISSUE TITLE
No min/width or scrollbar when browser window is reduced horizontally

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2032]
bobray created Redmine issue ID 2032

Shrinking the browser window horizontally causes overlapping text and unreachable text off the right side of the screen in right-hand panels . No horizontal scrollbar ever appears. It is pretty much site wide and occurs with the Tools menu items as well as the element editing screens.

**Comment by splittingred** [comment]
splittingred submitted:

BobRay, I can't reproduce this in FF3/mac. My text resizes to the new window width. I do, however, note that in Safari/mac the text resizes but Ext widgets do not. I think this is a browser issue and something we probably wont be able to fix.

**Comment by BobRay** [comment]
bobray submitted:

Here's a shot in FF3-Vista. It's the same in IE7. Without expanding the window, there's no way to reach the stuff that's off the screen (in System Settings, you can use the tab key to see different parts of it but it's a pretty funky experience). Notice the overlapping text at the bottom right also. That happens in IE7 as well. screen shot-1 Isn't there a way to set a min-width so you'd get a scroll bar in this situation?

**Comment by BobRay** [comment]
bobray submitted:

I was wrong about the tab key, sometimes it works in FF, sometimes not. Here's what happens when you tab to the right column, then expand the window. screenshot-2

**Comment by splittingred** [comment]
splittingred submitted:

Ah, I follow now. I'll look into it tomorrow.

**Comment by splittingred** [comment]
splittingred submitted:

Unfortunately, this seems to be an ExtJS issue that is unfixable. Closing.
