### ISSUE TITLE
Remove captcha entry from core/lexicon/en/default.inc.php

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2034]
bobray created Redmine issue ID 2034

There's still a harmless captcha-related entry in default.inc.php that should be removed. I've verified that it's not used anywhere else and it's duplicated in the captcha add-on lexicon. Remove line 80 of the file:
$_lang &#91;&#39;captcha_code&#39;&#93; = 'Security code'; The attached patch will remove the line, but would have to be used before any other changes to the file. I couldn't resist also changing the last line "You got mail" to the classier "You have mail"

**Comment by BobRay** [comment]
bobray submitted:

Patch for default.inc.php

**Comment by splittingred** [comment]
splittingred submitted:

Patched in r4253

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed r4265.
