### ISSUE TITLE
regClientCSS() doesn't insert  type

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2035]
bobray created Redmine issue ID 2035

In 0.9.6, regClientCSS() inserted: type = "text/css" into the inserted link statement. This no longer happens in Revolution. Not sure if any browsers care about this any more. modx.class.php line 1101

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4254

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed r4265.
