### ISSUE TITLE
Package installation trashes lexicon

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2036]
bobray created Redmine issue ID 2036

This is a tough one to pin down. I created a snippet package for which the build and install on a separate site went smoothly. The snippet works fine in the new location. The Manager is fubared, however, with lots of missing prompts and empty buttons, although everything still seems to work. Looking in Lexicon Management, the core | default section has no entries and "default" isn't listed in the dropdown foci list for core. In the DB, the "default" focus for the core namespace no longer appears in the lexicon_foci table.

**Comment by BobRay** [comment]
bobray submitted:

Here is the package that caused the trouble.

**Comment by splittingred** [comment]
splittingred submitted:

I'm gonna actually need the build scripts for this... Can you zip your package development folder and send that? Or did you build this via the GUI?

**Comment by splittingred** [comment]
splittingred submitted:

Hmmm, we might have to remove the package builder because of this. The Package Builder GUI seems to be creating more problems than it's worth. We're going to remove it for now, and maybe add it back in in the future.

**Comment by BobRay** [comment]
bobray submitted:

I built it with the GUI, but it's possible that I built it with a version of MODx that was not up-to-date. Have you confirmed this with a GUI build of your own? If not, I'll do some more testing. There's nothing special about the package. It's just one snippet, a lexicon with an ezfaq namespace and a default focus, and some support files you can see in /snippets/ezfaq. There's no php script involved. Reloading the core lexicon seems to solve the problem it creates.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in alpha-4 removal of Package Builder GUI.

**Comment by BobRay** [comment]
bobray submitted:

Not an issue since PB GUI is gone.
