### ISSUE TITLE
Confusing help in Package Builder Resolver

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2037]
bobray created Redmine issue ID 2037

When creating a file resolver in the Package Builder GUI, the hover help suggests that the "name" field is just used for organizational purposes. The name field is actually used as the filename of the created file(s) instead of the original names. If this is not intended, then it's a bug. If it is intended, the help message should say so. I'm not sure which would be better. It may be of some value to be able to change the name of the file in the package but it makes package creation more error-prone (I used ezfaq-css for the name of a file called ezfaq.css and don't want to admit how long it took me to figure out why my snippet wouldn't work).

**Comment by splittingred** [comment]
splittingred submitted:

Since package builder is being removed, this task is now invalid.
