### ISSUE TITLE
Possible bug with $modx->getChunk (incorrectly parsing placeholders)

### ISSUE THREAD

**Issue by garryn** [modxbot/migrate#2040]
garryn created Redmine issue ID 2040

Got something strange going on whilst working on the Ditto port ... When using $modx->getChunk(), it seems that any placeholders that have been set using $modx->setPlaceholder() prior to the $modx->getChunk() call get parsed into the chunk if they are referenced in the chunk. IMO, $modx->getChunk() should return the raw output for the chunk and not do any preprocessing on the output. Has anyone else experienced this?

**Comment by opengeek** [comment]
opengeek submitted:

Garry, can you explain why you believe that this should not attempt to process the chunk? I think it's important that we make the recursive parsing approach consistent, i.e. all elements are responsible for parsing their own content, but without removing any unreplaced tags.
