### ISSUE TITLE
regClientCSS() and regClientStartupScript() fail when page and snippet are both cached

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2042]
bobray created Redmine issue ID 2042

When a document is set to cacheable and snippet is called as [ &#91;snippet&#93; ], regClientCSS() and regClientStartupScript() work once after the site cache is cleared. On subsequent visits (once the page and snippet are cached), they produce nothing. The other three combinations (page cached, [ &#91;!snippet&#93; ]; page uncached, [ &#91;!snippet&#93; ]; page uncached, [ &#91;snippet&#93; ]) all work as they should.

**Comment by opengeek** [comment]
opengeek submitted:

Great catch BobRay; this is fixed now. Just needed the jscripts and sjscripts variables to be cached along with each Resource.

**Comment by BobRay** [comment]
bobray submitted:

This seems to be back. Neither works at all if both the snippet and page are cached, even after the cache is cleared.

**Comment by opengeek** [comment]
opengeek submitted:

This bug was re-introduced between 2.0.0-alpha6 and 2.0.0-pl, but is again fixed for 2.0.3-pl

**Comment by oori** [comment]
oori submitted:

with 2.0.3-pl this is resolved,  but the _exact same_ issue still appears in getPage wrapped pages.  $modx->regClientStartupScript call from within a cached snippet (in a cached page, and  getPage cache) works only once (uncached) - but these params are not written to the cache file and never retrieved on cached hits.

i couldn't quickly trace why:
- the cache files do not contain any *jscript (not in the main resource's cache (where it should be), nor in the getPage caches).  so it's not written.
- i've looked in guthub at your last related commit, but it all seems right there.
