### ISSUE TITLE
Save button grayed-out  in Create/Edit Plugin

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2047]
bobray created Redmine issue ID 2047

The "Save" button doesn't become active in Create/Edit Plugin until the plugin is dirty, but editing the code, changing a system event,, changing the name description or category, or messing with Plugin Properties doesn't change the dirty status. The only way to make the plugin "dirty" and save an it is to check or uncheck one of the checkboxes.

**Comment by BobRay** [comment]
bobray submitted:

Also applies to editing templates and snippets (chunks and resources seem ok).

**Comment by splittingred** [comment]
splittingred submitted:

Added fix in r4123. Confirm?

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed - IE7, FF3.
