### ISSUE TITLE
Serious CAPTCHA problems

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2049]
bobray created Redmine issue ID 2049

SInce the changes to login.tpl, turning CAPTCHA on in System Settings results in no image and no CAPTCHA input field (nothing related to CAPTCHA is visible). Logins fail with the message that the captcha input didn't match the image. Perhaps more serious: There appears to be no way to add CAPTCHA back in via a plugin. Any output from the login page events is rendered outside the login box and the $_SESSION variable set in the plugin does not match the user input.

**Comment by splittingred** [comment]
splittingred submitted:

Are you sure the CAPTCHA plugin is inserting the HTML via the "onManagerLoginFormRender" event? The code is there...not sure why it wouldn't work. It worked when I tested it when we redid the manager login page.

**Comment by BobRay** [comment]
bobray submitted:

I tried having the plugin respond to both onManagerLoginFormRender and onManagerLoginFormPrerender. One put the image above the login box, the other put it below, but both outside of the box and neither allowed a login, though the same code worked fine before. Let me make sure I've got everything current and try it again.

**Comment by BobRay** [comment]
bobray submitted:

OK, I did an update, build, and update install. The image is definitely being output by the plugin. If it responds to OnManagerLoginFormPrerender, the CAPTCHA stuff appears below the login box. If it responds to OnManagerLoginFormRender, nothing shows up at all on the login screen but the copyright message. Maybe there's something wrong with my plugin code. Here it is: <?php $rt = ""; if (isset ($modx->config['use_captcha']) && $modx->config['use_captcha'] == 1) { $modx->lexicon->load('captcha: default '); if (isset ($modx->config['captcha_use_mathstring']) && $modx->config['use_mathstring'] == 1) { $alt = $modx->lexicon( "login_mathstring_message" ); } else { $alt = $modx->lexicon( "login_captcha_message" ); } $captcha_image= '<a href= "'.$_SERVER['PHP_SELF'].'" class= "loginCaptcha" ><img src= "'.$modx->config['site_url'].'assets/captcha/captcha.php?rand='.rand().'" alt= "'.$alt.'" /></a>'; if (isset ($modx->config['captcha_use_mathstring']) && $modx->config['captcha_use_mathstring'] == 1) { $captcha_prompt = '<p class= "caption" >'.$modx->lexicon( "login_mathstring_message" ).'</p>'; $captcha_input= '<label>'.$modx->lexicon( "captcha_mathstring_code" ).'</label> <input type= "text" name= "captcha_code" tabindex= "3" value="" />'; } else { $captcha_prompt = '<p class= "caption" >'.$modx->lexicon( "login_captcha_message" ).'</p>'; $captcha_input= '<label>'.$modx->lexicon( "captcha_code" ).'</label> <input type= "text" name= "captcha_code" tabindex= "3" value="" />'; } $rt = $captcha_prompt.$captcha_image.$captcha_input; } $modx->event->_output = $rt; ?>

**Comment by BobRay** [comment]
bobray submitted:

After a little debugging, the $_SESSION variable set in the CAPTCHA code is getting through to the validator but the user input is not.

**Comment by splittingred** [comment]
splittingred submitted:

Added a fix in r4121, try now.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
