### ISSUE TITLE
Imported Lexicon entries don't show in grid

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2052]
bobray created Redmine issue ID 2052

Imported lexicon entries under a new namespace (default focus / en) are written to the DB but don't show up in the lexicon grid under that namespace.

**Comment by splittingred** [comment]
splittingred submitted:

You have to reselect the focus in the toolbar. The reason being, that the 'default' focus for the core namespace is a different focus than the 'default' for the new namespace. I'm not sure how I can work around that.

**Comment by BobRay** [comment]
bobray submitted:

Yup, there they are. I tried everything I could think of to make them appear with no luck. I'm not sure anyone would ever think of selecting "default" when "default" is already showing. Hopefully, there's some way to reload the "default" focus when a different namespace is selected.

**Comment by splittingred** [comment]
splittingred submitted:

Moving this to beta (or next alpha)

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4725

**Comment by BobRay** [comment]
bobray submitted:

Fixed.
