### ISSUE TITLE
Reload Core Entries from Base no longer works in Lexicon Management

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2056]
bobray created Redmine issue ID 2056

Reload Core Entries from Base no longer works in Lexicon Management (as of r4103). The button animation works but nothing happens except an "error on page" status message from IE7.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4105

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed. FF3/IE7 r4105.
