### ISSUE TITLE
When applying Admin ACL to mgr/connectors contexts, Contexts menu item generates 'Access Denied'

### ISSUE THREAD

**Issue by garryn** [modxbot/migrate#2057]
garryn created Redmine issue ID 2057

When applying the Administrator group and Admin ACL to the 'mgr' and 'connectors' contexts, the Contexts menu items becomes unavailable ('Access Denied' message) when logging with a user who is a member of the Administrator group. I presume there's some context-specific permissions that need to be added to the Admin ACL.

**Comment by opengeek** [comment]
opengeek submitted:

This should work after logging out and logging back in; user policies are cached in session and I will be introducing some options to allow flushing access permissions without logging out, as well as general improvements in the thoroughness of the core security checks

**Comment by opengeek** [comment]
opengeek submitted:

This should now be resolved but needs thorough testing.
