### ISSUE TITLE
'Save' button only becomes enabled when editing document content

### ISSUE THREAD

**Issue by garryn** [modxbot/migrate#2059]
garryn created Redmine issue ID 2059

When editing a document, the save button only becomes enabled when editing the document content textarea. It should become enabled when editing any of the properties such as page title, alias, and published status. Tested in both Firefox and Safari and had the same behaviour.

**Comment by splittingred** [comment]
splittingred submitted:

Garry, you sure you are testing the latest SVN? Mine works on the latest, and I posted a fix to this a couple days ago.

**Comment by garryn** [comment]
garryn submitted:

I think I must've had a problem when I did my SVN update yesterday because it wasn't working after the update but I've done an update today and it's working now - close this one off if you want
