### ISSUE TITLE
User Group Access to Contexts grid not refreshing after adding record

### ISSUE THREAD

**Issue by opengeek** [modxbot/migrate#2064]
opengeek created Redmine issue ID 2064

When adding a record to the grid for managing modAccessContext records, the dialog does not close and the grid does not refresh. Here is the JavaScript error that is reported in FF3: Error: a is undefined
Source File: http://localhost/revolution/manager/assets/modext/widgets/security/modx.grid.access.context.js
Line: 51

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4071
