### ISSUE TITLE
Make "Provisioner" non-editiable in Package Installer grid

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2067]
bobray created Redmine issue ID 2067

Unless I'm misunderstanding it, the "Provisioner" field should be a record of where the package came from and shouldn't be editable.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4075

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed IE7, FF3.
