### ISSUE TITLE
Jira won't accept bug reports for Add-ons or Core extensions

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2075]
bobray created Redmine issue ID 2075

Not a bug in MODx but: Bugs can't be reported in Jira for MODx add-ons or core extensions because "affects versions" is required and there are no options for that field.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed. Whoops.

**Comment by BobRay** [comment]
bobray submitted:

Fixed.
