### ISSUE TITLE
%s instead of filename in Package install success message in console

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2076]
bobray created Redmine issue ID 2076

need an sprintf() to display package name. Patch attached.

**Comment by BobRay** [comment]
bobray submitted:

Patch for %s error in package installer install.php

**Comment by BobRay** [comment]
bobray submitted:

This may be an artifact of MODX-336

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4061

**Comment by BobRay** [comment]
bobray submitted:

Fixed
