### ISSUE TITLE
Browser "remembers" user even when "remember me" is not checked.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2077]
bobray created Redmine issue ID 2077

Both IE and FF "remember" the user if the browser is closed without logging out.

**Comment by BobRay** [comment]
bobray submitted:

Changed to reflect current behavior.

**Comment by opengeek** [comment]
opengeek submitted:

Fixed. Was always using system setting despite not checking the remember me checkbox.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
