### ISSUE TITLE
Lexicon reload reports 0 strings regenerated

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2081]
bobray created Redmine issue ID 2081

After the change to "hide from menus" the lexicon reload reported 0 strings regenerated even though that entry was successfully loaded. Also, this probably shouldn't be an "error" message, but rather a "status" or "information" message since reloading when there are no new entries should give a non-error result of 0.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4036.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
