### ISSUE TITLE
Site start resource can be saved as unpublished

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2088]
bobray created Redmine issue ID 2088

When creating a new site, documents default to unpublished. The first document created (1) can be saved and then previewed as unpublished, evn though it's the default site-start. Later saves cause an error message but the initial one doesn't.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4028

**Comment by BobRay** [comment]
bobray submitted:

resolved
