### ISSUE TITLE
"Hide Menu" semantically incorrect on "create/edit" doc screen

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2089]
bobray created Redmine issue ID 2089

"Hide Menu" implies that a menu will be hidden which isn't the result. There's no very good way of saying what this should say in English short of "Don't show this resource on menus" or somesuch and I worry about the translations. Experienced MODx users will figure it out but new users will be very confused. IMO, it might be better to go back to "Show in Menu" and have it default to checked because it's short and there's no question what it means.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4029

**Comment by BobRay** [comment]
bobray submitted:

Resolved.
