### ISSUE TITLE
modCacheManager::generateLexiconCache ignores the language parameter and doesn't filter by namespace

### ISSUE THREAD

**Issue by redman** [modxbot/migrate#2095]
redman created Redmine issue ID 2095

modCacheManager::generateLexiconCache can take 3 parameters: a namespace, focus and language. However, in the query around line 305, the namespace is not given as a WHERE condition, and the language is not set to the language parameter of the method, but is instead set to $this->modx->config &#91;&#39;manager_language&#39;&#93; . To fix this, the WHERE condition should restrict results based on the namespace and language parameters of the method.

**Comment by splittingred** [comment]
splittingred submitted:

Resolved in r4016
