### ISSUE TITLE
There should be a way to specify the language of a lexicon to load

### ISSUE THREAD

**Issue by redman** [modxbot/migrate#2096]
redman created Redmine issue ID 2096

modLexicon::load can take a variable number of comma-separated parameters of the form 'namespace:focus'. Foci are loaded by calling modLexicon::loadCache. modLexicon::loadCache supports 3 parameters, a namespace, focus and language. However, modLexicon::load only passes in the namespace and focus. There should be a way for lexicon languages to be specified so modLexicon::load can pass all three parameters to modLexicon::loadCache and support loading foci in languages other that English.

**Comment by splittingred** [comment]
splittingred submitted:

Why would you want to load a language other than the set language for the mgr context?

**Comment by redman** [comment]
redman submitted:

I want to allow users to select their language when they register on the site. I am building a web application based on Ext, so I want to be able to load the lexicon in the same way as lang.php.js, so that Ext can replace language keys with values. In this situation I need some way to select the language of the lexicon to load.

**Comment by splittingred** [comment]
splittingred submitted:

Fair enough. Will work on it soon.

**Comment by splittingred** [comment]
splittingred submitted:

Implemented in r3041
