### ISSUE TITLE
Quirks in Lexicon Management

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2097]
bobray created Redmine issue ID 2097

When a new namespace is created in Lexicon Management, it doesn't show up in the drop-down list on the main LM page until quite a bit later (I couldn't get it to show without clearing the site cache). Creating lexicon entries is still quirky from the main LM screen. It should use the settings from the fields as defaults but doesn't and will sometimes fail with a "focus not found" error after you pick the only focus it shows you (default). Also, the fields with the drop-down lists at the top of the Lexicon Management screen desperately need labels, otherwise new users won't be able to make any sense of them. And the focus drop-down on the main LM screen still shows all the core foci regardless of the namespace selected.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4015

**Comment by BobRay** [comment]
bobray submitted:

Almost there. All foci are still there if you come in fresh from the tools menu. 1. select Tools | Lexicon Management 2. select Create New | Namespace and create a new namespace 3. select the new namespace 4. select Create New Entry 5. select the focus drop-down before doing anything else and all the core foci show up.
