### ISSUE TITLE
Change "Configuration" to "System Settings" in Tools menu

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2110]
bobray created Redmine issue ID 2110

The menu choice should match the title of the heading of the screen it takes you to. I think all the rest do. I think it's also more accurate since there are a number of other ways to configure MODx (e.g. .htaccess, installing packages, editing Lexicon entries, etc.) that can't be reached via that menu entry.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3999
