### ISSUE TITLE
In System Settings and Lexicon Management selecting from a drop-down list doesn't update the screen until the user clicks again somewhere else.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2111]
bobray created Redmine issue ID 2111

Selecting a namespace, focus, or language in Lexicon Management or selecting Yes/No on the System Settings screen (after a double-click) doesn't update the screen until the user clicks again anywhere in the window. Selecting a namespace and then immediately selecting "create new" updates the screen to show that namespace but doesn't launch the "create new" drop-down. That takes an extra click. The same thing happens with the dropdowns in Package Builder. Is there an onChange event for the drop-downs that could launch a screen update without the extra click?

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3993
