### ISSUE TITLE
Lexicon entry can be assigned a non-existent focus

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2112]
bobray created Redmine issue ID 2112

When creating a new Lexicon entry, the full list of foci are shown whether that namespace has them or not. This might not be a bug, per se, but it leads to what looks like trouble. I created the "captcha" namespace and created a single "default" focus for it. When I create a new entry under that namespace, I can select any of the core focus categories. If I pick "about," for example, the entry is saved. The captcha namespace still only has "default" on the drop-down focus list, so you can't see the new entry. It doesn't (and shouldn't) show up under the core either. It will show, however, if you select the "core" namespace, select the "about" focus, then reset the namespace to "captcha". I'm not sure what would (or should) happen on export. I think what I did should either: 1. not be possible because the other foci don't show or 2. Create that new focus under the given namespace ("captcha" in this case).

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3994.

**Comment by BobRay** [comment]
bobray submitted:

This is definitely better, but in IE7, you can set the namespace to a new namespace, select "create new" and see and select from the full list of core foci. Saving gives a "focus not found" error, which is good. After the error, the full list doesn't show, only the real available foci will show. It would be better if they didn't show up in the first place although the current behavior is at least safe.
