### ISSUE TITLE
Last Modified time incorrect for Lexicon entries

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2113]
bobray created Redmine issue ID 2113

On the Lexicon Management screen the "Last Modified" field shows 8:00 pm as 08:00 instead of 20:00 or 8:00 pm

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3995

**Comment by BobRay** [comment]
bobray submitted:

Last modified now shows "false" for modified entries.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4400

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed. IE7, FF3.
