### ISSUE TITLE
For System Settings, "Last Modified" field shows "false"  rather than date/time.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2114]
bobray created Redmine issue ID 2114

Title says it all. (Note: date/time now shows for Lexicon entries but 8:00 pm is shown as 08:00 instead of 20:00 or 8:00 pm &#8211; I'll put that in as a separate issue but thought I'd mention it here in case this one gets fixed first.)

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3995

**Comment by BobRay** [comment]
bobray submitted:

System Settings and Lexicon Management items are all showing last modified as "false" for me in IE7 and FF3 as of 4014.

**Comment by BobRay** [comment]
bobray submitted:

This one is back.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4401

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed. IE7, FF3.
