### ISSUE TITLE
Make lexicon management screen match system setting

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2115]
bobray created Redmine issue ID 2115

The format on the Lexicon Management screen should probably match the excellent new format of the system settings screen (i.e. put "search" inside the box and add a "clear filter" button to the left of the search box).

**Comment by BobRay** [comment]
bobray submitted:

On second thought, I think the "create new" button on the Lexicon Management screen would work better just to the right of the three drop-down boxes at the left. Then the "clear filter" button could go at the far right, with the "Search . . ." inside the search box. The right side would then look exactly like the System Settings screen.

**Comment by splittingred** [comment]
splittingred submitted:

Done in r3991

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
