### ISSUE TITLE
Put a path example in the source field of the Package Builder resolver page

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2120]
bobray created Redmine issue ID 2120

There's a path example in the Target field. It would help users to have one in the Source field as well. It might be better to move the examples outside the input box so they won't get overwritten by the users mistakes or disappear as soon as anything is typed.

**Comment by splittingred** [comment]
splittingred submitted:

Implemented in r3975.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed working FF / IE7
