### ISSUE TITLE
Put a path example on the "Create Namespace" page

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2121]
bobray created Redmine issue ID 2121

e.g.: Example: MODX_CORE_PATH . 'assets/captcha'

**Comment by BobRay** [comment]
bobray submitted:

It might be better to keep the example outside the input box so it won't get overwritten by the users mistakes or disappear as soon as anything is typed.

**Comment by splittingred** [comment]
splittingred submitted:

Implemented in r3974.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed working FF / IE7
