### ISSUE TITLE
Lexicon grid can show non-existent page

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2124]
bobray created Redmine issue ID 2124

On either lexicon management tab, If you're looking at a later page (say page 3) in the core, for example, and change to another namespace that has fewer pages, you'll still be on page 3 and it will show no entries.

**Comment by splittingred** [comment]
splittingred submitted:

This is a bug with ExtJS...I'm thinking about coding an extension to their PagingToolbar to get around this.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3971

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed FF/ IE7

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
