### ISSUE TITLE
Newly created yes/no system settings not editable in grid.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2128]
bobray created Redmine issue ID 2128

Newly created yes/no values can't be edited (double-click has no effect). Pre-existing ones and text values work as they should

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3945-3946.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed working IE7 / FF

**Comment by BobRay** [comment]
bobray submitted:

Fixed.
