### ISSUE TITLE
Lexicon entries can no longer be loaded from files in directories added with $modx->lexicon->addDirectory().

### ISSUE THREAD

**Issue by redman** [modxbot/migrate#2135]
redman created Redmine issue ID 2135

modLexicon allows lexicon directories to be added via addDirectory(). However, as of r3943 directories added to modLexicon like this are never searched for lexicon files unless the namespace is 'core'.

**Comment by splittingred** [comment]
splittingred submitted:

This isn't really a bug; the Lexicon is now DB-loaded, and are now DB entries called modLexiconEntry. The next todo on the commits is creating a import mechanism for the Lexicon Management pane that allows you to import lang files into the DB.

**Comment by splittingred** [comment]
splittingred submitted:

Not a bug - lexicons are no longer loaded in this way. Changing tutorial to reflect this soon.
