### ISSUE TITLE
Improve Package Install error message

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2137]
bobray created Redmine issue ID 2137

It would be really helpful if there were more information about why a package failed to install.
I have a package that had no problems with the build and all I know is that it won't install. A series of Installation progress messages might be useful as well about which vehicles and/or resolvers are being installed.

**Comment by splittingred** [comment]
splittingred submitted:

Working on what's called MODx.Console, which will provide real-time error/message/status reporting on procedures.

**Comment by BobRay** [comment]
bobray submitted:

Great idea. Here's some practice for it. The Wayfinder package from the WTF on 4025. installed but the message box said it couldn't install it and the grid in Workspaces still lists it as uninstalled. Here's the console log: (BTW, there's no easy way to cut and paste from the console in FF or IE7. I couldn't find a way to highlight just the text in the console. Console running...
Attempting to install package with signature: wayfinder-1.0.1-beta
Package found...now preparing to install.
Validation called but no rules were found.
Grabbing package workspace...
Workspace environment initiated, now installing package...
Validation called but no rules were found.
Resolving transport files: xPDOVehicle Object ( &#91;payload&#93; => Array ( &#91;unique_key&#93; => name &#91;preserve_keys&#93; => 1 &#91;update_object&#93; => 1 &#91;resolve&#93; => Array ( &#91;0&#93; => Array ( &#91;source&#93; => /Applications/MAMP/htdocs/modx-components/wayfinder/branches/1.0.1/assets/snippets/wayfinder &#91;target&#93; => return MODX_ASSETS_PATH . 'snippets/'; &#91;type&#93; => file &#91;body&#93; => {"source":"wayfinder-1.0.1-beta\/modSnippet\/554b031ef8a553804fd730cc17d79213\/","target":"return MODX_ASSETS_PATH . 'snippets\/';","name":"wayfinder"} ) ) &#91;validate&#93; => &#91;class&#93; => modSnippet &#91;guid&#93; => 5d4518d0d561921cacb6e0e0e9a16f1a &#91;object&#93; => {"id":null,"name":"Wayfinder","description":"1.0.1 beta 1<\/strong> Wayfinder 1.0 for MODx 0.9.7","editor_type":"0","category":0,"cache_type":"0","snippet":"\/_\n::::::::::::::::::::::::::::::::::::::::\n Snippet name: Wayfinder\n Short Desc: builds site navigation\n Version: 1.0.1\n Authors: Ryan Thrash (vertexworks.com)\n Kyle Jaebker (muddydogpaws.com)\n Date: October 23, 2006\n::::::::::::::::::::::::::::::::::::::::\nDescription:\n Totally refactored from original DropMenu nav builder to make it easier to\n create custom navigation by using chunks as output templates. By using templates,\n many of the paramaters are no longer needed for flexible output including tables,\n unordered- or ordered-lists (ULs or OLs), definition lists (DLs) or in any other\n format you desire.\n::::::::::::::::::::::::::::::::::::::::\nExample Usage:\n [ &#91;Wayfinder? &startId=`0`&#93; ]\n::::::::::::::::::::::::::::::::::::::::\n_\/\n\ninclude_once(MODX_BASE_PATH . \"assets\/snippets\/wayfinder\/wayfinder.inc.php\");\n\nif (class_exists('Wayfinder')) {\n $wf = new Wayfinder();\n} else {\n return 'error: Wayfinder class not found';\n}\n\n\/\/parameter overrides\n$wf->id = isset($startId)? $startId: $modx->resourceIdentifier;\n$wf->level = isset($level)? $level: 0;\n$wf->ph = isset($ph)? $ph: FALSE;\n$wf->debug = isset($debug)? TRUE: FALSE;\n$wf->ignoreHidden = isset($ignoreHidden)? $ignoreHidden: FALSE;\n$wf->hideSubMenus = isset($hideSubMenus)? $hideSubMenus: FALSE;\n$wf->useWeblinkUrl = isset($useWeblinkUrl)? $useWeblinkUrl: TRUE;\n$wf->showSubDocCount = isset($showSubDocCount)? $showSubDocCount: FALSE;\nisset($removeNewLines)? $wf->ie = '': $wf->ie = \"\n\";\n\/\/Set ordering options\n$wf->sortOrder = isset($sortOrder)? strtoupper($sortOrder): 'ASC';\n$wf->sortBy = isset($sortBy)? $sortBy: 'menuindex';\n$wf->limit = isset($limit)? $limit: 0;\n\/\/Include javascript & css chunks\n$wf->cssTpl = isset($cssTpl)? $cssTpl : FALSE;\n$wf->jsTpl = isset($jsTpl)? $jsTpl : FALSE;\n\/\/get user class definitions\n$wf->css &#91;&#39;first&#39;&#93; = isset($firstClass)? $firstClass: '';\n$wf->css &#91;&#39;last&#39;&#93; = isset($lastClass)? $lastClass: 'last';\n$wf->css &#91;&#39;here&#39;&#93; = isset($hereClass)? $hereClass: 'active';\n$wf->css &#91;&#39;parent&#39;&#93; = isset($parentClass)? $parentClass: '';\n$wf->css &#91;&#39;row&#39;&#93; = isset($rowClass)? $rowClass: '';\n$wf->css &#91;&#39;outer&#39;&#93; = isset($outerClass)? $outerClass: '';\n$wf->css &#91;&#39;inner&#39;&#93; = isset($innerClass)? $innerClass: '';\n$wf->css &#91;&#39;level&#39;&#93; = isset($levelClass)? $levelClass: '';\n$wf->css &#91;&#39;self&#39;&#93; = isset($selfClass)? $selfClass: '';\n$wf->css &#91;&#39;weblink&#39;&#93; = isset($webLinkClass)? $webLinkClass: '';\n\/\/prefix for adding id to each row\n$wf->rowIdPrefix = isset($rowIdPrefix)? $rowIdPrefix: FALSE;\n\/\/get fields to output\n$wf->textOfLinks = (isset($textOfLinks)) ? $textOfLinks : 'menutitle';\n$wf->titleOfLinks = (isset($titleOfLinks)) ? $titleOfLinks : 'pagetitle';\n\/\/get user templates\n$wf->templates &#91;&#39;outerTpl&#39;&#93; = isset($outerTpl) ? $outerTpl : '';\n$wf->templates &#91;&#39;rowTpl&#39;&#93; = isset($rowTpl) ? $rowTpl : '';\n$wf->templates &#91;&#39;parentRowTpl&#39;&#93; = isset($parentRowTpl) ? $parentRowTpl : '';\n$wf->templates &#91;&#39;parentRowHereTpl&#39;&#93; = isset($parentRowHereTpl) ? $parentRowHereTpl : '';\n$wf->templates &#91;&#39;hereTpl&#39;&#93; = isset($hereTpl) ? $hereTpl : '';\n$wf->templates &#91;&#39;innerTpl&#39;&#93; = isset($innerTpl) ? $innerTpl : '';\n$wf->templates &#91;&#39;innerRowTpl&#39;&#93; = isset($innerRowTpl) ? $innerRowTpl : '';\n$wf->templates &#91;&#39;innerHereTpl&#39;&#93; = isset($innerHereTpl) ? $innerHereTpl : '';\n$wf->templates &#91;&#39;activeParentRowTpl&#39;&#93; = isset($activeParentRowTpl) ? $activeParentRowTpl : '';\n$wf->templates &#91;&#39;categoryFoldersTpl&#39;&#93; = isset($categoryFoldersTpl) ? $categoryFoldersTpl : '';\n\n\/\/Process Wayfinder\n$output = $wf->run();\n\n\/\/Ouput Results\nif ($wf->ph) {\n $modx->setPlaceholder($wf->ph,$output);\n} else {\n return $output;\n}","locked":"0","properties":null,"moduleguid":""} &#91;native_key&#93; => &#91;signature&#93; => 554b031ef8a553804fd730cc17d79213 ) )
Could not install package with signature: wayfinder-1.0.1-beta
OK

**Comment by splittingred** [comment]
splittingred submitted:

Yeah, package installs seem to be currently broken - I bet you Wayfinder actually did install (check the snippets). For now, you'll have to remove wayfinder manually. I also added a Copy to Clipboard option, that should help with pasting.

**Comment by BobRay** [comment]
bobray submitted:

Yup &#8211; as I said, it installed but the package installer thinks it didn't.

**Comment by splittingred** [comment]
splittingred submitted:

BobRay: the most recent commits as of today should have fixed those bugs - can you confirm?

**Comment by BobRay** [comment]
bobray submitted:

Handled through console.
