### ISSUE TITLE
Move search box away from "create new key" to make it clear they are separate functions

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2138]
bobray created Redmine issue ID 2138

The placement of the search box will look to some like you fill it in to create a new key since, visually, they have the relation of caption and input box (especially since the search box sometimes ends up blank). Moving it to the right side and giving it it's own caption outside the box might be best. A good caption might be "search filter" since it really is a filter in that you have to delete the contents to get the full list back. A "remove filter" or (better) "complete list" button might make sense too. It's not immediatly obvious how to get your full list back after a search.

**Comment by splittingred** [comment]
splittingred submitted:

Resolved in r3983

**Comment by BobRay** [comment]
bobray submitted:

Very nice implementation.
