### ISSUE TITLE
Manager won't run in IE7

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2157]
bobray created Redmine issue ID 2157

In IE7 I can log on and see all my plugins and snippets in the tree but the initial screen shows an IE7 error box showing: "Internet Explorer cannot open the internet site
 http://localhost/modx097/manager/index.php?id=0 Operation aborted" And that message is repeated on any action in the manager. The manager works fine in FF.
The front end looks fine in either IE7 or FF. I first saw the problem in 3904 but hadn't upgraded since 3885 (I think). If the symptoms and error message (below) don't identify the problem. I can try reverting to various versions to see when this happened. I found this in error.log: &#91;2008-08-11 22:31:16&#93; (ERROR @ /modx097/index.php) `[ &#91;++site_start)&#93; ]~` is not numeric and may not be passed to makeUrl() One for each login with IE7. This is what's in config.cache.php $this->config &#91;&#39;site_start&#39;&#93; = '1'; I did a clean check-out in a new directory with a new database and a new build and install and the problem remains. At first, I suspected MySQL 5.0.51 but the manager runs fine in FF.

**Comment by BobRay** [comment]
bobray submitted:

I checked the version out from: http://svn.modxcms.com/svn/tattoo/tattoo/branches/revolution

**Comment by splittingred** [comment]
splittingred submitted:

It's Ext2.2 that is causing the problem. Apparently the upgrade from 2.1 to 2.2 broke it. I'll have to do some research and figure out what the Ext boys changed that would cause it to break.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3914. Was a Ext2.2 bug that is a known issue; a problem with the onReady and document loading mechanism they used that they changed. Applied a fix until an official patch comes out.

**Comment by BobRay** [comment]
bobray submitted:

Fixed.
