### ISSUE TITLE
Can't view site when offline and logged in to the manager

### ISSUE THREAD

**Issue by fmilitao** [modxbot/migrate#2159]
unknown created Redmine issue ID 2159

As discussed in this post: http://modxcms.com/forums/index.php/topic,27499.msg168926.html When logged into the manager, and the site is set as off-line, you should still be able to view the site as a normal user would, if the site was online. Currently, Revolution outputs the template of the document without parsing any tags. According to Jason, MODx should output a flat PHP file located on the filesystem when the site is off-line. As discussed on the afore-mentioned thread, I personally feel it should still process tags, so we can set an offline message in the manager and use the rest of the site's images/CSS files etc as normal. At the very least, we should have the option to choose whether MODx outputs an offline page stored in the CMS, or an offline page on the filesystem.

**Comment by opengeek** [comment]
opengeek submitted:

You can provide a resource id as the page to render when the site is offline. Some adjustments just need to be made regarding the offline functionality to make sure the parser works as expected when a member of the Administrator group is viewing the site. I'm working on this now. Thanks for the feedback. There are many significant changes to security and identity in Revolution, so some of these things just haven't been addressed yet.

**Comment by opengeek** [comment]
opengeek submitted:

Revision 3943 should address part of this issue. More complete testing is needed for complex security scenarios.

**Comment by opengeek** [comment]
opengeek submitted:

This was fixed for alpha-4
