### ISSUE TITLE
UpdateFromGrid doesn't work for context settings

### ISSUE THREAD

**Issue by redman** [modxbot/migrate#2163]
redman created Redmine issue ID 2163

Edits to context settings for contexts I create aren't saved to the database when I try editing values by double-clicking on the value in the context settings dialogue.

**Comment by splittingred** [comment]
splittingred submitted:

Seems to be a possible issue with Ext grids in windows, and the particular implementation of the MODx.grid.SettingsGrid. Unfortunately, I can't seem to find a solution. So it looks like in-place-editing there will have to go. I'll add a "Update Setting" menu option and a window in the meantime.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3897. Added an Update Setting option to the context menu.
