### ISSUE TITLE
Category Problem with Templates

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2168]
bobray created Redmine issue ID 2168

Saving a template creates a "null" category and places that template under it. Template can't be loaded for editing again until "null" category is removed. Error message: No action with ID element/template/update found. (Similar to the problem we had with snippet categories.)

**Comment by splittingred** [comment]
splittingred submitted:

Looks like I missed applying that last fix to the templates. Fixed in r3884.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed 3887.
