### ISSUE TITLE
Refresh Tree uses two different icons

### ISSUE THREAD

**Issue by pbear** [modxbot/migrate#2173]
pbear created Redmine issue ID 2173

The icon for "Refresh Tree" under "Resources" is different from the one used under "Elements" and "Files."

**Comment by pbear** [comment]
pbear submitted:

The icon used for "Resources" is the same used for "Clear Cache" under "Site" in the Toolbar. So "Resources" seems to be the icon in error.

**Comment by splittingred** [comment]
splittingred submitted:

To be resolved in restyling, to happen around beta/rc1 releases. There is already a ticket for that issue, so closing this one.
