### ISSUE TITLE
Autofadeout Tooltips in Manager

### ISSUE THREAD

**Issue by pbear** [modxbot/migrate#2176]
pbear created Redmine issue ID 2176

I would appreciate if tooltips would fade out after NN seconds so I can see what I'm typing. I can always wiggle the mouse if I need to read it again.

**Comment by pbear** [comment]
pbear submitted:

Arrgh! (I would like to post the screenshot directly, but the upload interface seems to freeze on my system: why do I have to paste from the clipboard instead of just specifying a file as above? Apologies.)

**Comment by splittingred** [comment]
splittingred submitted:

Implemented in r3878.
