### ISSUE TITLE
With elements showing in doc tree, clicking on Resources closes elements but doesn't open resources.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2183]
bobray created Redmine issue ID 2183

With elements showing in doc tree, clicking on Resources closes elements but doesn't open resources. Happens in both IE7 and FF (as of 3872).

**Comment by BobRay** [comment]
bobray submitted:

Issue is intermittent. I can't find any sequence that makes it happen every time. I definitely got it several times in a row with this sequence: Right click on a snippet and select "edit"
Change the snippet.
Save using the top button.
Click on "Resources" I suspect a slight mismatch between the screen location of the resources bar and the sensed mouse position (or possibly just sloppy clicking on my part - I'll click more carefully and report back).

**Comment by splittingred** [comment]
splittingred submitted:

BobRay, I can't seem to replicate this at all.

**Comment by splittingred** [comment]
splittingred submitted:

No matter how much I try, I can't replicate this. Closing the ticket unless otherwise.

**Comment by BobRay** [comment]
bobray submitted:

I believe it has happened to me a few more times but I can't find any sequence that does it reliably. There's a possibility that I'm clicking on Resources when it's already open, which would close it, but thinking I was in elements. I'm going back and forth a lot working with multiple snippets and resources. I don't think that's the case but I'm usually in the middle of some work when it happens so I could be distracted. I'm trying to pay more attention. It's trivial anyway so go ahead and close it. I'll report back if I can come up with anything definite.
