### ISSUE TITLE
Multiple package installation ability

### ISSUE THREAD

**Issue by chucktrukk** [modxbot/migrate#2196]
chucktrukk created Redmine issue ID 2196

It would be nice to checkbox or shift-click packages to install/un-install many at once

**Comment by splittingred** [comment]
splittingred submitted:

Closing this for a few reasons: 1. Package installation is a heavy thing if the packages are large, and having multiple installations might cause heavy server loads that are unnecessary.
2. Multiple installations would cause problems with debugging installs, logging to console, and dependencies.
3. If one fails, do the others continue? Questions like such prevent us from implementing this at this time.
