### ISSUE TITLE
Several UI issues with elements/categories

### ISSUE THREAD

**Issue by mrichards** [modxbot/migrate#2199]
mrichards created Redmine issue ID 2199

Problem with categories and most element types, full steps to reproduce with template variables: Create a new category "Test" (right-click on an element type and select "New Category") Right click on "Template Variables" and create "New Template Variable" Fill in fields, select "Test" as existing category, then save Category "Test" folder appears in "Template Variable" folder Right click on the "Test" folder and select "Create a New Tv here" Existing category field will already be populated with "Test" Leave this field alone but fill in other appropriate fields and save Error occurs: "An error occurred while trying to save the category" Manually selecting the category and resaving fixes error Slightly different behaviour with Chunks:
Create chunk in existing category folder -> category field is already populated, but ignored unless manually selected (as though it was empty) Another variation with Snippets and Templates:
Create snippet/template in existing category folder -> the category field is not populated, so snippet/template will not appear in category by default Plugins seem to work OK in this regard. I can't get modules to work with categories, found it hard to save them at all in fact. A related category concern: you are able to create and save a new category whilst at the same time as editing/saving an element - nice if it works but seems more likely to cause problems.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed category saving problems in r3682. Please file the problems with Module saving in a separate ticket.
