### ISSUE TITLE
Right Click menus not functional in Opera 9.51

### ISSUE THREAD

**Issue by mrichards** [modxbot/migrate#2200]
mrichards created Redmine issue ID 2200

Right clicking on resources, elements or files does not bring up Modx menu but instead Opera's context menu for right-clicking on a link (to "mysite/manager/index.php?id=0"). Makes operation in Opera impossible due to lack of alternative methods to perform certain actions (e.g. create template).

**Comment by Rx2** [comment]
rx2 submitted:

I am getting similar behaviour in Firefox 3 (Windows). Except it brings up both. You have to click on the MODx specific pop-up to view it.

**Comment by splittingred** [comment]
splittingred submitted:

Opera, being idiots, have disabled right-click javascript events in their browser. See topic: http://extjs.com/forum/showthread.php?t=7526 As for firefox 3, I cannot replicate that problem at all. Please open a separate ticket if you are having FF3 problems.
