### ISSUE TITLE
Tree collapses (does not remember) settings when a item is added

### ISSUE THREAD

**Issue by chucktrukk** [modxbot/migrate#2202]
chucktrukk created Redmine issue ID 2202

When I add a new Document, chunk, snippet, TV, etc., the tree refreshes and collapses. Also, when I expand the tree (with the arrow), it only expands one level not all of them.

**Comment by splittingred** [comment]
splittingred submitted:

This should be fixed in SVN, if not, please repost with more specifics - which actions refresh entire tree, etc.
