### ISSUE TITLE
Dropdowns on TV page not working correctly

### ISSUE THREAD

**Issue by chucktrukk** [modxbot/migrate#2203]
chucktrukk created Redmine issue ID 2203

The dropdown arrow is on top of the label. The category dropdown does not show any categories. It is blank.

**Comment by splittingred** [comment]
splittingred submitted:

Have you created any categories? Also, editing out the dropdown arrow bug; already known and is a problem with Ext.

**Comment by chucktrukk** [comment]
chucktrukk submitted:

Do you create categories by typing in a value, and it gets saved for future use (like 096)? If so, yes.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3858.
