### ISSUE TITLE
Can't save snippets in IE7

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2208]
bobray created Redmine issue ID 2208

Trying to save any snippet, edited or not gives this error message in IE7: An error occurred while trying to save the category. Save works fine in FF.

**Comment by BobRay** [comment]
bobray submitted:

Same result from Duplicate or Delete for snippets. No problem with chunks or resources &#8211; only snippets.

**Comment by BobRay** [comment]
bobray submitted:

The problem seems to be related to a phantom category called "null" It's my only category (I didn't create it, it just showed up). If I delete it, I can edit snippets, but as soon as I save them, the Null category comes back. It contains the first snippet. If I create a new category, it gets the name "null" regardless of what I call it. In FF, deleting the "null" category fixes things permanently but creating any new category seems to have no effect. No new category shows up.

**Comment by BobRay** [comment]
bobray submitted:

This is the error in the log: &#91;2008-07-18 00:06:00&#93; (ERROR @ /modx097/connectors/element/snippet.php) Error 23000 executing statement:
INSERT INTO `modx_categories` (`category`) VALUES (:category)
Array
(
 &#91;0&#93; => 23000
 &#91;1&#93; => 1062
 &#91;2&#93; => Duplicate entry 'null' for key 2
)

**Comment by splittingred** [comment]
splittingred submitted:

Confirmed as a bug. Will work on it today.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3861.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed - 3864
