### ISSUE TITLE
Missing data in tables on fresh install

### ISSUE THREAD

**Issue by netdoctor** [modxbot/migrate#2209]
netdoctor created Redmine issue ID 2209

No valid content types exist in tbl content_type on a fresh install. In addition numerous configuration errors displayed on manager default page as follows.. Configuration warning: The Unauthorized page defined in the site configuration settings is not published.
....
Configuration warning: Your site's Error page is not published or does not exist.
... Also going to Manager>Tools>Configuration to view configuration results in blank display with no config data being shown. I confirmed that the db table -> system_settings has 90 rows present. I saw the info note about adding content types but no record example was given. I performed repeated installations using both the advanced and normal setups. The files were unzipped on the server. The apache server had full rights to the root of virtual host as well as all files. Does not appear to be permissions issue. I followed instructions step by step. Then set rwx-rwx-rwx for all files and dirs on a clean unzipped install dir. Same results. I am available to assist in fault isolation. Thanks in advance.

**Comment by opengeek** [comment]
opengeek submitted:

What distribution did you use? The content type data is installed by the installer. If it is not there, the installation failed and we need to go back to that.

**Comment by netdoctor** [comment]
netdoctor submitted:

http://wtf.modxcms.com/downloads/&d=core/modx-2.0.0-alpha-2.zip
and
 http://wtf.modxcms.com/downloads/&d=core/modx-2.0.0-alpha-2-advanced.zip

**Comment by opengeek** [comment]
opengeek submitted:

Jeff: Can you confirm this is not because of an 8M memory_limit setting in your PHP configuration or some other installation failure? Does the installation return a blank page when you click install? Were there any error messages produced?

**Comment by netdoctor** [comment]
netdoctor submitted:

I had it set to 64 so that was not it. I tried it on a ubuntu hardy heron server and it worked. So then I upgraded my PHP from the Centos repository to the yum repository created by Jason Litka available at http://www.jasonlitka.com/yum-repository/ (php 5.26) and performed a new install. Problem disappeared. So there was a dependency during install that this system did not meet. Important note: There were no error messages during installation when I first reported this issue.

**Comment by opengeek** [comment]
opengeek submitted:

Jeff, based on some similar issues reported by a team member, I think this may be related to some bugs in the PDO layer of PHP that resulted in Apache segfaults, especially in 5.1.6. One solution is to force xPDO to use the built-in PDO emulation classes (which use the mysql extension directly) and avoid the PDO errors on those platforms. This can be done by editing all of the config.core.php files and adding the line: define('XPDO_MODE', 2); This will force xPDO to use the PDO_ emulation classes rather than the built-in PDO classes.

**Comment by netdoctor** [comment]
netdoctor submitted:

Thank you for your effort on this issue.

**Comment by opengeek** [comment]
opengeek submitted:

Unfortunately this is not something that can be easily detected or remedied, so I'm resolving this with Won't Fix. I think we'll need to add this kind of supplemental information to the system requirements page for Revolution as we discover configurations/environments that trigger these kinds of problems. I don't think this one is the only recent configuration to experience these kinds of problems.
