### ISSUE TITLE
saving a doc in safari doesn't work

### ISSUE THREAD

**Issue by xpix** [modxbot/migrate#2211]
xpix created Redmine issue ID 2211

Saving a document in safari does not work. I tried to change the title of a doc that was created in safari and it did not work

**Comment by xpix** [comment]
xpix submitted:

It's for the Revolution-2.0.0-alpha-2 not 1
and the document was created previously in firefox I cleared the error log an refreshed the manager in safari:
Here is what I got &#91;2008-07-15 14:08:01&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/core/model/modx/xmlrss/rssfetch.class.php : 242) User warning: MagpieRSS: fetch_rss called without a url
 &#91;2008-07-15 14:08:01&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: array_keys() &#91;<a href=&#39;function.array-keys&#39;>function.array-keys</a>&#93; : The first argument should be an array
 &#91;2008-07-15 14:08:01&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: Invalid argument supplied for foreach()
 &#91;2008-07-15 14:08:01&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/core/model/modx/xmlrss/rssfetch.class.php : 242) User warning: MagpieRSS: fetch_rss called without a url
 &#91;2008-07-15 14:08:01&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: array_keys() &#91;<a href=&#39;function.array-keys&#39;>function.array-keys</a>&#93; : The first argument should be an array
 &#91;2008-07-15 14:08:01&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: Invalid argument supplied for foreach()
 &#91;2008-07-15 14:10:23&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/core/model/modx/xmlrss/rssfetch.class.php : 242) User warning: MagpieRSS: fetch_rss called without a url
 &#91;2008-07-15 14:10:23&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: array_keys() &#91;<a href=&#39;function.array-keys&#39;>function.array-keys</a>&#93; : The first argument should be an array
 &#91;2008-07-15 14:10:23&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: Invalid argument supplied for foreach()
 &#91;2008-07-15 14:13:34&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/core/model/modx/xmlrss/rssfetch.class.php : 242) User warning: MagpieRSS: fetch_rss called without a url
 &#91;2008-07-15 14:13:34&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: array_keys() &#91;<a href=&#39;function.array-keys&#39;>function.array-keys</a>&#93; : The first argument should be an array
 &#91;2008-07-15 14:13:34&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: Invalid argument supplied for foreach()
 &#91;2008-07-15 14:14:36&#93; (ERROR @ /bmm2/connectors/workspace/packages.php) Object for class modPlugin not found using criteria Array
(
 &#91;name&#93; => TinyMCE
) &#91;2008-07-15 14:29:55&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/core/model/modx/xmlrss/rssfetch.class.php : 242) User warning: MagpieRSS: fetch_rss called without a url
 &#91;2008-07-15 14:29:55&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: array_keys() &#91;<a href=&#39;function.array-keys&#39;>function.array-keys</a>&#93; : The first argument should be an array
 &#91;2008-07-15 14:29:55&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: Invalid argument supplied for foreach()
 &#91;2008-07-15 14:29:55&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/core/model/modx/xmlrss/rssfetch.class.php : 242) User warning: MagpieRSS: fetch_rss called without a url
 &#91;2008-07-15 14:29:55&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: array_keys() &#91;<a href=&#39;function.array-keys&#39;>function.array-keys</a>&#93; : The first argument should be an array
 &#91;2008-07-15 14:29:55&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: Invalid argument supplied for foreach()
 &#91;2008-07-15 14:50:59&#93; (ERROR @ /bmm2/connectors/resource/document.php) No foreign key definition for parentClass: modDocument using relation alias: modDocumentGroupDocument
 &#91;2008-07-15 14:50:59&#93; (ERROR @ /bmm2/connectors/resource/document.php) No foreign key definition for parentClass: modDocument using relation alias: modTemplateVarDocument
 &#91;2008-07-15 15:36:48&#93; (ERROR @ /bmm2/connectors/workspace/packages.php) Object for class modSnippet not found using criteria Array
(
 &#91;name&#93; => Wayfinder
) &#91;2008-07-15 16:30:38&#93; (ERROR @ /bmm2/connectors/resource/document.php) No foreign key definition for parentClass: modDocument using relation alias: modDocumentGroupDocument
 &#91;2008-07-15 16:30:38&#93; (ERROR @ /bmm2/connectors/resource/document.php) No foreign key definition for parentClass: modDocument using relation alias: modTemplateVarDocument
 &#91;2008-07-15 16:30:49&#93; (ERROR @ /bmm2/connectors/resource/document.php) No foreign key definition for parentClass: modDocument using relation alias: modDocumentGroupDocument
 &#91;2008-07-15 16:30:49&#93; (ERROR @ /bmm2/connectors/resource/document.php) No foreign key definition for parentClass: modDocument using relation alias: modTemplateVarDocument
 &#91;2008-07-15 17:09:52&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/core/model/modx/xmlrss/rssfetch.class.php : 242) User warning: MagpieRSS: fetch_rss called without a url
 &#91;2008-07-15 17:09:52&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: array_keys() &#91;<a href=&#39;function.array-keys&#39;>function.array-keys</a>&#93; : The first argument should be an array
 &#91;2008-07-15 17:09:52&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: Invalid argument supplied for foreach()
 &#91;2008-07-15 17:09:54&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/core/model/modx/xmlrss/rssfetch.class.php : 242) User warning: MagpieRSS: fetch_rss called without a url
 &#91;2008-07-15 17:09:54&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: array_keys() &#91;<a href=&#39;function.array-keys&#39;>function.array-keys</a>&#93; : The first argument should be an array
 &#91;2008-07-15 17:09:54&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: Invalid argument supplied for foreach()
 &#91;2008-07-15 17:11:23&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/core/model/modx/xmlrss/rssfetch.class.php : 242) User warning: MagpieRSS: fetch_rss called without a url
 &#91;2008-07-15 17:11:23&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: array_keys() &#91;<a href=&#39;function.array-keys&#39;>function.array-keys</a>&#93; : The first argument should be an array
 &#91;2008-07-15 17:11:23&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: Invalid argument supplied for foreach()
 &#91;2008-07-15 17:11:24&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/core/model/modx/xmlrss/rssfetch.class.php : 242) User warning: MagpieRSS: fetch_rss called without a url
 &#91;2008-07-15 17:11:24&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: array_keys() &#91;<a href=&#39;function.array-keys&#39;>function.array-keys</a>&#93; : The first argument should be an array
 &#91;2008-07-15 17:11:24&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: Invalid argument supplied for foreach()
 &#91;2008-07-16 11:13:27&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/core/model/modx/xmlrss/rssfetch.class.php : 242) User warning: MagpieRSS: fetch_rss called without a url
 &#91;2008-07-16 11:13:27&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: array_keys() &#91;<a href=&#39;function.array-keys&#39;>function.array-keys</a>&#93; : The first argument should be an array
 &#91;2008-07-16 11:13:27&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: Invalid argument supplied for foreach()
 &#91;2008-07-16 11:13:27&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/core/model/modx/xmlrss/rssfetch.class.php : 242) User warning: MagpieRSS: fetch_rss called without a url
 &#91;2008-07-16 11:13:27&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: array_keys() &#91;<a href=&#39;function.array-keys&#39;>function.array-keys</a>&#93; : The first argument should be an array
 &#91;2008-07-16 11:13:27&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: Invalid argument supplied for foreach()
 &#91;2008-07-16 11:13:40&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/core/model/modx/xmlrss/rssfetch.class.php : 242) User warning: MagpieRSS: fetch_rss called without a url
 &#91;2008-07-16 11:13:40&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: array_keys() &#91;<a href=&#39;function.array-keys&#39;>function.array-keys</a>&#93; : The first argument should be an array
 &#91;2008-07-16 11:13:40&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: Invalid argument supplied for foreach()
 &#91;2008-07-16 11:13:40&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/core/model/modx/xmlrss/rssfetch.class.php : 242) User warning: MagpieRSS: fetch_rss called without a url
 &#91;2008-07-16 11:13:40&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: array_keys() &#91;<a href=&#39;function.array-keys&#39;>function.array-keys</a>&#93; : The first argument should be an array
 &#91;2008-07-16 11:13:40&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: Invalid argument supplied for foreach()
 &#91;2008-07-16 11:15:03&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/core/model/modx/xmlrss/rssfetch.class.php : 242) User warning: MagpieRSS: fetch_rss called without a url
 &#91;2008-07-16 11:15:03&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: array_keys() &#91;<a href=&#39;function.array-keys&#39;>function.array-keys</a>&#93; : The first argument should be an array
 &#91;2008-07-16 11:15:03&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: Invalid argument supplied for foreach()
 &#91;2008-07-16 11:15:03&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/core/model/modx/xmlrss/rssfetch.class.php : 242) User warning: MagpieRSS: fetch_rss called without a url
 &#91;2008-07-16 11:15:03&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: array_keys() &#91;<a href=&#39;function.array-keys&#39;>function.array-keys</a>&#93; : The first argument should be an array
 &#91;2008-07-16 11:15:03&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: Invalid argument supplied for foreach()
 &#91;2008-07-16 11:15:04&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/core/model/modx/xmlrss/rssfetch.class.php : 242) User warning: MagpieRSS: fetch_rss called without a url
 &#91;2008-07-16 11:15:04&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: array_keys() &#91;<a href=&#39;function.array-keys&#39;>function.array-keys</a>&#93; : The first argument should be an array
 &#91;2008-07-16 11:15:04&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: Invalid argument supplied for foreach()
 &#91;2008-07-16 11:15:04&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/core/model/modx/xmlrss/rssfetch.class.php : 242) User warning: MagpieRSS: fetch_rss called without a url
 &#91;2008-07-16 11:15:04&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: array_keys() &#91;<a href=&#39;function.array-keys&#39;>function.array-keys</a>&#93; : The first argument should be an array
 &#91;2008-07-16 11:15:04&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: Invalid argument supplied for foreach()
 &#91;2008-07-16 11:15:04&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/core/model/modx/xmlrss/rssfetch.class.php : 242) User warning: MagpieRSS: fetch_rss called without a url
 &#91;2008-07-16 11:15:04&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: array_keys() &#91;<a href=&#39;function.array-keys&#39;>function.array-keys</a>&#93; : The first argument should be an array
 &#91;2008-07-16 11:15:04&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: Invalid argument supplied for foreach()
 &#91;2008-07-16 11:15:05&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/core/model/modx/xmlrss/rssfetch.class.php : 242) User warning: MagpieRSS: fetch_rss called without a url
 &#91;2008-07-16 11:15:05&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: array_keys() &#91;<a href=&#39;function.array-keys&#39;>function.array-keys</a>&#93; : The first argument should be an array
 &#91;2008-07-16 11:15:05&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: Invalid argument supplied for foreach()
 &#91;2008-07-16 11:31:06&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/core/model/modx/xmlrss/rssfetch.class.php : 242) User warning: MagpieRSS: fetch_rss called without a url
 &#91;2008-07-16 11:31:06&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: array_keys() &#91;<a href=&#39;function.array-keys&#39;>function.array-keys</a>&#93; : The first argument should be an array
 &#91;2008-07-16 11:31:06&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: Invalid argument supplied for foreach()
 &#91;2008-07-16 11:31:07&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/core/model/modx/xmlrss/rssfetch.class.php : 242) User warning: MagpieRSS: fetch_rss called without a url
 &#91;2008-07-16 11:31:07&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: array_keys() &#91;<a href=&#39;function.array-keys&#39;>function.array-keys</a>&#93; : The first argument should be an array
 &#91;2008-07-16 11:31:07&#93; (ERROR @ /Applications/MAMP/htdocs/bmm2/manager/controllers/welcome.php : 69) PHP warning: Invalid argument supplied for foreach()

**Comment by splittingred** [comment]
splittingred submitted:

Repeated exact steps in same environment. Cannot reproduce. Please try and download and install again.

**Comment by xpix** [comment]
xpix submitted:

it's was tinymce problem.
