### ISSUE TITLE
Missing error message on name collision in duplicating snippets

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2212]
bobray created Redmine issue ID 2212

Duplicating a snippet and using the name of an existing snippet triggers line 35 of duplicate.php: $modx->error->failure($modx->lexicon('snippet_err_duplicate')); But there's no such error in the lexicon. 'snippet_err_exists_name' would work although it appears that the error is thrown on any failed save so it might have another cause (e.g. permissions). 'snippet_duplicate_error' might be a better choice. Down the road, we might want to diagnose the problem and report various causes.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3846. Also added check for existing name.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed. Nit: Edit box for the duplicate filename in IE7 is about 8 lines high. It's a single line in FF. I think this is new since this fix.

**Comment by splittingred** [comment]
splittingred submitted:

My IE7 shows it normal height. Odd.
