### ISSUE TITLE
Language setting in setup is not loaded.

### ISSUE THREAD

**Issue by KMD** [modxbot/migrate#2228]
kmd created Redmine issue ID 2228

Language setting in setup is not loaded. Cookie name of language setting uses ".".
PHP changes "." to "_". "/setup/includes/modinstall.class.php"
line 81 if (isset ($_COOKIE &#91;&#39;modx.setup.language&#39;&#93; )) {
$language= $_COOKIE &#91;&#39;modx.setup.language&#39;&#93; ;
} to if (isset ($_COOKIE &#91;&#39;modx_setup_language&#39;&#93; )) {
$language= $_COOKIE &#91;&#39;modx_setup_language&#39;&#93; ;
} "/setup/processor/language.php"
line 7 setcookie('modx.setup.language', $language); to setcookie('modx_setup_language', $language, 0, '/');

**Comment by KMD** [comment]
kmd submitted:

setcookie 4th parameter "/" is unsecured. Create path from AJAX processor path "/setup/processors/language.php". "/setup/processors/language.php"
line 7 setcookie('modx.setup.language', $language); to $cookie_path = preg_replace('/(.*\/) &#91;^\/&#93; +\/ &#91;^\/&#93; */', "\ \1", $_SERVER &#91;&#39;REQUEST_URI&#39;&#93; );
setcookie('modx_setup_language', $language, 0, $cookie_path); preg_replace 2nd parameter "\ \1" is "backslash backslash one".
Don't put " "(space) between "\".

**Comment by mkschell** [comment]
netprophet submitted:

I tried the update to /setup/processors/language.php above, and found a couple of problems. 1) $cookie_path is getting set to "/setup/onnector.php?action=language" which doesn't seem right.
I'm not clear on what the regular expression is trying to do, or why allowing a path of / is "unsecured". PHP's default is "the current directory that the cookie is being set in."
kmd, are you trying to set the cookie path to whatever the /setup/ directory is? 2) even if I put the setcookie path back to /, the cookie does not get set. /setup/processors/language.php is sending json data, and even though the cookie header is sent, at least for me, the browser is not seeing it. I'm on LAMP - PHP4 testing this with FF 2.0. We might have to find a way to send the cookie information from language.php back to a script that can send it with the html to the browser

**Comment by KMD** [comment]
kmd submitted:

1)
the regular expression replace the path "/setup/processors/language.php"($_SERVER &#91;&#39;REQUEST_URI&#39;&#93; ) to "/setup/".
ajax request is sent to "/setup/processors/language.php" after choose language and click "Next" button.
a page request uri "/setup/index.php" can not read the cookie path "/setup/processors/language.php" (the current directory that the cookie is being set in). 2)
I tried it.
FF 2.0 / 3.0 can not read cookie information, but IE 6 / 7 can do it.
FF can do it only cookie path "/setup/". If put the cookie path "/", the other user can read the cookie information with IE.

**Comment by KMD** [comment]
kmd submitted:

Hi, Mike.
Please test this file. This file is "/setup/processors/language.php".
Add the regular expression that replace the path "setup/processors/language.php" to "setup/".

**Comment by KMD** [comment]
kmd submitted:

I'm on LAMP -
Cent OS 4.5
Apache 2.0.50
PHP 5.0.5
web browser
FF 2.0 / 3.0
IE 6 / 7
safari for windows 3.1 Set the cookie path "/", safari can not read cookie information too.

**Comment by opengeek** [comment]
opengeek submitted:

Corrected in commit 3854 and 3855

**Comment by mkschell** [comment]
netprophet submitted:

Confirmed fixed for me in PHP4 enviro, in FF2.0 (Linux) Opera 9.5 (Linux) IE 6 (Linux/WiNE)
