### ISSUE TITLE
Language setting in manager pages is not  loaded.

### ISSUE THREAD

**Issue by KMD** [modxbot/migrate#2229]
kmd created Redmine issue ID 2229

Set language japanese in manager configuration, but it is not loaded. I think "cultureKey" is always "english". "/core/model/modx/modlexicon.class.php" line 124 // include_once the language file
if(!isset($this->modx->config &#91;&#39;manager_language&#39;&#93; )) { $this->modx->cultureKey= 'english'; // add // set cultureKey >>> } else { $this->modx->cultureKey= $this->modx->config['manager_language']; // set cultureKey <<< }

**Comment by opengeek** [comment]
opengeek submitted:

This is fixed in commit 3849
