### ISSUE TITLE
Cannot setup with IE6.

### ISSUE THREAD

**Issue by KMD** [modxbot/migrate#2230]
kmd created Redmine issue ID 2230

Cannot setup with IE6. Choose language and click "next".
but not move to next page. I think "<option>" tag has no "value=" attribute. In "/setup/controllers/language.php", $navbar .= '<option>' . $language . '</option>' . "\n";
to
$navbar .= '<option value="' . $language . '">' . $language . '</option>' . "\n";

**Comment by splittingred** [comment]
splittingred submitted:

Committed in r3792.
