### ISSUE TITLE
Japanese language files for manager pages.

### ISSUE THREAD

**Issue by KMD** [modxbot/migrate#2231]
kmd created Redmine issue ID 2231

We create japanese language files for manager pages. put the files in "/core/lexicon/japanese"

**Comment by KMD** [comment]
kmd submitted:

Sorry, please change the above beta in Affects Version/s to alpha. I took a mistake.

**Comment by opengeek** [comment]
opengeek submitted:

FYI, it should go in a directory called ja now; we are going to use the IANA country codes for cultureKey as of alpha-2

**Comment by opengeek** [comment]
opengeek submitted:

I'll be working on creating a proper distribution package (using the new transport packaging system) for the language files and will update this thread when it is completed.

**Comment by Paprikas** [comment]
paprikas submitted:

why japanese calls ja not jp?

**Comment by opengeek** [comment]
opengeek submitted:

Language distros for Revo will be made available as Add-Ons.
