### ISSUE TITLE
Configuration is not updated.

### ISSUE THREAD

**Issue by KMD** [modxbot/migrate#2236]
kmd created Redmine issue ID 2236

Change configuration in "Tools > Configuration", but update configure are not reflected. "core/cache/config.cache.php" is not updated.
I think when configuration is updated, "core/cache/config.cache.php" is needed to updated too. Function "reloadConfig" in "core/model/modx/modx.class(864)" function reloadConfig() {

> > add
> > $cacheManager= $this->getCacheManager();
> > $cacheManager->clearCache();
> > << add if (!$this->_loadConfig()) { $this->_log(MODX_LOG_LEVEL_ERROR, "Could not reload core MODx configuration!"); }
> > return $this->config;
> > }

**Comment by splittingred** [comment]
splittingred submitted:

Comitted in r3791.
