### ISSUE TITLE
Cannot save Template.

### ISSUE THREAD

**Issue by asaism** [modxbot/migrate#2237]
asaism created Redmine issue ID 2237

Cannot save template elements.Still progres window open and running. I think JS bug. manager/assets/modext/sections/element/template/create.js(14) formpanel: 'template-panel' >>> formpanel: 'panel-template'

**Comment by mkschell** [comment]
netprophet submitted:

Thanks SA - that fixed the bug in my environment too.

**Comment by mkschell** [comment]
netprophet submitted:

Committed r.3786
