### ISSUE TITLE
Vehicles grid in Package Builder is not cleared after first use

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#2240]
netprophet created Redmine issue ID 2240

After using the Package Builder, subsequent trips to the "Add Vehicles" dialog have the grid preloaded with the items added in the last round. However, if you leave the items as they are and continue, the package does not actually build. The grid can be refreshed (to empty) by entering a 0 (zero) in the paging toolbar, pressing enter, then entering a 1 and pressing enter.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3793.
