### ISSUE TITLE
Invalid characters in DB for non latin symbols

### ISSUE THREAD

**Issue by atma** [modxbot/migrate#2252]
atma created Redmine issue ID 2252

When I use cyrillic symbols in page content, I get somesing like this in DB: Ñ?ÐµÑ?Ñ?
In MODx symbols present normally.
character_set_client | utf8
character_set_connection | utf8
character_set_database | utf8
character_set_filesystem | binary
character_set_results | utf8
character_set_server | utf8
character_set_system | utf8
collation_connection | utf8_general_ci
collation_database | utf8_unicode_ci
collation_server | utf8_unicode_ci When I have added SET NAMES utf8 COLLATE utf8_unicode_ci in /core/xpdo/pdo.class.php, nothing has changed.

**Comment by opengeek** [comment]
opengeek submitted:

The PDO class you are attempting to edit is only used if PDO emulation is enabled, so that will not work. I will play around with SET NAMES, but this may have more to do with JSON, or perhaps the collation_connection being utf8_general_ci instead of unicode_ci is causing problems. What do the database and actual table collations show?

**Comment by atma** [comment]
atma submitted:

MySQL connection_collation is utf8_unicode_ci, all tables and columns in utf8_unicode_ci too. I need to use this collation, but _general_ci give me nothing... btw, mysqldump with --default-character-set=latin1 give me right symbols in dump file.

**Comment by opengeek** [comment]
opengeek submitted:

Sounds to me like your database or the tables in it are using a latin1 collation then.

**Comment by atma** [comment]
atma submitted:

How I can to set PDO_MYSQL_ATTR_INIT_COMMAND to "SET NAMES utf8" in XPDO?

**Comment by atma** [comment]
atma submitted:

To resolve this situation I use skip-character-set-client-handshake in &#91;mysqld&#93; section for ignore character set request from the client and force server settings (utf8). From what follows what problem in client (MODx).?

**Comment by atma** [comment]
atma submitted:

BTW, in latest (rev 5044) SVN versions this issue is gone.
