### ISSUE TITLE
Add support for parameters on modx::lexicon() and [[%Lexicon]] tags

### ISSUE THREAD

**Issue by bs** [modxbot/migrate#2254]
bs created Redmine issue ID 2254

The modx->lexicon method should be altered to support php's sprintf ( http://nl3.php.net/sprintf ) or similar string format solution.
An optional "array" of values can then be assigned to replace the string variables. for example: $_lang &#91;&#39;my_replacement_string&#39;&#93; = 'Your name is %s and you are from %s'; usage from code:
$modx->lexicon('my_replacement_string','myfoci',array('Armand','The Netherlands')) or usage from tag:
[ &#91;%my_replacement_string?key1=`Armand`&key2=`The Netherlands`&#93; ] output: 'Your name is Armand and you are from The Netherlands'

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3771
