### ISSUE TITLE
Loading of manager and loading eyecandy takes ages. (firebug is off)

### ISSUE THREAD

**Issue by dimmy** [modxbot/migrate#2270]
dimmy created Redmine issue ID 2270

When logging in or swithing manager pages the "please wait..." loading"" window/statusbar takes a long time to disapear. (if it does at all) I noticed that when I klik on the suport /jira buton that the pleasewait window disapears and that the page is accesible. somhow this small popup does not get the trigger to stop. Also the statusbar is not filling up at all.
in Plesk there is also an option like this called "disable screen until page is loaded" its realy anoying somtimes I do not wish to wayt but want to klik on a link that I already know is sin that page an dI do not mind that all images are not there yet. Could this be optional so that it can be switshed of? this loading thing I mean. While I am typing this (and I am not that fast) the manager is stil loading , I presed the home button but noting apears only when i click it again I see a blocked home screen with some config warnings but than its blank again and it starts loading again. Maybe less eyecandy and more speed?

**Comment by splittingred** [comment]
splittingred submitted:

This seems to be an issue related to just your setup - it runs smooth and fast on other setups. Please provide more information about your server setup: PHP Version MySQL Version Server type (apache,IIS,etc) and what version # OS which 097 alpha version you downloaded any errors you've found in logs

**Comment by splittingred** [comment]
splittingred submitted:

Closing b/c of no response.
