### ISSUE TITLE
RTE not working

### ISSUE THREAD

**Issue by tvachon** [modxbot/migrate#2272]
tvachon created Redmine issue ID 2272

When I try to create a page, it defaults to no editor. When I try and select the built in Rich Text Editor, the selection is blank in the drop down. When I select it, it refreshes but has no RTE.

**Comment by splittingred** [comment]
splittingred submitted:

Not a bug. The alpha does not include TinyMCE - you must install it as a package. See here to download: http://wtf.modxcms.com/downloads/?relPath=add-ons And learn how to install it here:
 http://svn.modxcms.com/docs/display/MODx097/Package+Management
