### ISSUE TITLE
Settle backtick requirement issue

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2280]
bobray created Redmine issue ID 2280

The issue is whether backticks should always be required for snippet parameters. At present, [ &#91;Wayfinder? &startId=0&#93; ] doesn't work. There may be an issue of backward compatibility here since parameters with no spaces in them worked in earlier versions of MODx. This could also be handled in the site conversion utility.

**Comment by wshawn** [comment]
wshawn submitted:

I have written a huge set of functions to protect the backend from "lazy" or newby developers. One of which removed the spaces: if(!function_exists('replaceSpace')) {
function replaceSpace($string= '') { /\* Replaces spaces in a given string to an underscore _/ $patterns[0]= '/ - /'; $patterns[1]= '/ /'; return preg_replace($patterns, "", $string); }
} Another of which locks down the snippet parameters: if(!function_exists('cleanParameters')) { /_ processes input for inclusion in database, trim for display, etc */
function cleanParameters($parameter, $setDefaultText, $length, $cleanForMysql, $makeUpper) {
$parameter=(isset($parameter)) ? $parameter : $setDefaultText; // if parameter comes in empty and a setDefault is given, insert default in parameter
if(!$parameter) { return NULL; } else {
$parameter= trim($parameter); // trim leading and trailing content
$parameter=(!empty($length)) ? $parameter= $parameter= substr($parameter, 0, $length) : $parameter; // if size change is requested cut it from left
if(!$cleanForMysql) { $parameter=(get_magic_quotes_gpc()) ? stripslashes($parameter) : $parameter; // strips the slashes added when get_magic_quotes_gpc is on (which is the default php setting) $parameter= htmlspecialchars($parameter, ENT_QUOTES); $parameter= nl2br($parameter); // still need to run mysql_real_escape_string at database call for clean database insert }
$parameter=(!empty($makeUpper)) ? strtoupper($parameter) : $parameter; // do this to help guard against improper cased snippet call parameters
}
return $parameter;
}
} I hope these help. credit: shawnwilkerson.com

**Comment by splittingred** [comment]
splittingred submitted:

This seems to be more of a Wayfinder issue. It should work as stated.
