### ISSUE TITLE
Menu icons cause 404 when clicked

### ISSUE THREAD

**Issue by fmilitao** [modxbot/migrate#2281]
unknown created Redmine issue ID 2281

When clicking on an icon in the menu (the menu wording works fine) it causes a 404 with the following error: "The requested URL /modx-097/manager/ &#91;object HTMLImageElement&#93; was not found on this server." /modx-097 is obviously my install path.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3680.
