### ISSUE TITLE
Page data display alignment 

### ISSUE THREAD

**Issue by bossloper** [modxbot/migrate#2285]
uxello created Redmine issue ID 2285

When viewing 'Page data' in IE7 the labels are not all aligned correctly and the labels column is excessively wide. All looks fine in Firefox.

**Comment by opengeek** [comment]
opengeek submitted:

Thanks for the note on this. This will be addressed when we get to styling the new manager. We are currently using default Ext styles and this will not be the way final release goes out.

**Comment by opengeek** [comment]
opengeek submitted:

Can someone confirm if this is still the case in IE7 as of alpha-2 release?

**Comment by splittingred** [comment]
splittingred submitted:

Confirmed, still occurs. The page needs to be redesigned, anyway. Probably best to wait until restyling.

**Comment by splittingred** [comment]
splittingred submitted:

Converted to MODx.FormPanel, in 3881.
