### ISSUE TITLE
In safari the dropdown list are displayed properly

### ISSUE THREAD

**Issue by xpix** [modxbot/migrate#2287]
xpix created Redmine issue ID 2287

The drop down list looks funny See the attachement

**Comment by splittingred** [comment]
splittingred submitted:

Known Ext issue: http://extjs.com/forum/showthread.php?t=12338
 http://extjs.com/forum/showthread.php?t=16843

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4381
