### ISSUE TITLE
checking/unchecking checkboxes in page settings generates a javascript error

### ISSUE THREAD

**Issue by bossloper** [modxbot/migrate#2288]
uxello created Redmine issue ID 2288

When editing the 'Page Settings' for any page, checking/unchecking any of the radio buttons generates a javascript error. Error: Ext.getCmp(C.dom.id) has no properties
Source File: http://......./modx97/manager/assets/ext2/ext-all.js
Line: 131 I cannot see any obvious problems resulting from this error and changes to checkboxes are saved correctly.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3671
