### ISSUE TITLE
Ext2 bug - On scrool the table has a strange behaviour

### ISSUE THREAD

**Issue by xpix** [modxbot/migrate#2289]
xpix created Redmine issue ID 2289

Go to tools/Configuration
Click on + to open an Item
Scroll You should see that the table breaks. All the items disappear.

**Comment by xpix** [comment]
xpix submitted:

after just touching the scroll all items dissapear exept the one you opend clicking on +. If there is no item open and you scroll everything dissappears.

**Comment by splittingred** [comment]
splittingred submitted:

Happens if you scroll, period. Seems to be either a core Safari issue or a core Ext issue.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3673. Apparently Safari doesn't like Ext's autoHeight property.
