### ISSUE TITLE
Unable to reset user password in the manager using Internet Explorer 7

### ISSUE THREAD

**Issue by bossloper** [modxbot/migrate#2292]
uxello created Redmine issue ID 2292

When updating a user and trying to reset the password I cannot complete this using Internet Explorer 7.0.6001.18000 Checking 'New Password' displays the Password notification method fields as expected.
But then if I check the 'Let me specify the password' option the password fields are displayed then are immediately hidden so the password cannot be entered. I checked this under Firefox 2.0.0.14 and it displays fine.

**Comment by BobRay** [comment]
bobray submitted:

Problem confirmed for IE7.

**Comment by mkschell** [comment]
netprophet submitted:

Problem confirmed in IE6 (Linux/WiNE) As in # MODX-89 , once you click on a field underneath the password fields, the password fields appear and can be used.

**Comment by mkschell** [comment]
netprophet submitted:

signing off this issue because I can no longer even get to this screen in IE6 or IE7
