### ISSUE TITLE
When editing the profile of the "Default Admin User (admin)" date is alway's wrong 

### ISSUE THREAD

**Issue by dimmy** [modxbot/migrate#2293]
dimmy created Redmine issue ID 2293

When editing a member profile I can not create a date that validates I used the js datepicker that is next to the field and it creates this date: Sat Dec 21, 1974
that is ok I think but the tooltip, say's:
Sat Dec 21, 1974 is not a valid date - it must be in the format D M d, Y because of this I can not save the profile

**Comment by bossloper** [comment]
uxello submitted:

This appears to be browser specific as it is ok for Firefox 2.0.0.14. I get this same error when using IE7.

**Comment by dimmy** [comment]
dimmy submitted:

Actually I got this error using ff 2.0.0.14 on pc and IE7 as well

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3703.
