### ISSUE TITLE
Add database information to the site info page

### ISSUE THREAD

**Issue by ghost** [modxbot/migrate#2294]
sottwell created Redmine issue ID 2294

Add three lines to the Server tab of the system info page. Database type (mysql or whatever), database charset, and database version (applicable to MySQL, will need modification for other database types).

**Comment by ghost** [comment]
sottwell submitted:

Files modified:
manager/controllers/system/info.php
manager/templates/default/system/info.tpl
core/lexicon/english/system_info.inc.php

**Comment by splittingred** [comment]
splittingred submitted:

Added in r3806.
