### ISSUE TITLE
Upgrading from previous 097 to the one released today trows some errors

### ISSUE THREAD

**Issue by xpix** [modxbot/migrate#2297]
xpix created Redmine issue ID 2297

Here is what I got after choosing upgrade &#91;CMS and PHP Application Framework&#93;
MODx version 0.9.7-alpha
[ close ] Installation Summary Core installation was successful. Click finish to complete the installation process.
(scroll to bottom) \* Successfully created table for class modAccessAction
- Successfully created table for class modAccessElement
- Successfully created table for class modAccessMenu
- Successfully created table for class modAccessPolicy
- Successfully created table for class modAccessResource
- Successfully created table for class modAccessResourceGroup
- Successfully created table for class modAccessTemplateVar
- Successfully created table for class modAction
- Successfully created table for class modContextResource
- Successfully created table for class modContentType
- Successfully created table for class modManagerLog
- Successfully created table for class modMenu
- Successfully created table for class modWorkspace
- Successfully created table for class transport.modTransportPackage
- Successfully created table for class transport.modTransportProvider
- Successfully upgraded table for class modResource
  Removed full-text index `content_ft_idx`.
- Error upgrading table for class modResource
  Array
  (
  &#91;0&#93; => 42S21
  &#91;1&#93; => 1060
  &#91;2&#93; => Duplicate column name 'content_type'
  )
- Successfully upgraded table for class modResource
  Added new `content_ft_idx` full-text index on the fields `pagetitle`, `longtitle`, `description`, `introtext`, `content`.
- Error upgrading table for class modUserGroup
  Array
  (
  &#91;0&#93; => 42S21
  &#91;1&#93; => 1060
  &#91;2&#93; => Duplicate column name 'parent'
  )
- Error upgrading table for class modUserGroup
  Array
  (
  &#91;0&#93; => 42000
  &#91;1&#93; => 1061
  &#91;2&#93; => Duplicate key name 'parent'
  )
- Error upgrading table for class modUserGroupMember
  Array
  (
  &#91;0&#93; => 42S21
  &#91;1&#93; => 1060
  &#91;2&#93; => Duplicate column name 'role'
  )
- Error upgrading table for class modUserGroupMember
  Array
  (
  &#91;0&#93; => 42000
  &#91;1&#93; => 1061
  &#91;2&#93; => Duplicate key name 'role'
  )
- Error upgrading table for class modModule
  Array
  (
  &#91;0&#93; => 42S21
  &#91;1&#93; => 1060
  &#91;2&#93; => Duplicate column name 'disabled'
  )
- Error upgrading table for class modUser
  Array
  (
  &#91;0&#93; => 42S21
  &#91;1&#93; => 1060
  &#91;2&#93; => Duplicate column name 'cachepwd'
  )
- Successfully upgraded table for class modActiveUser
  Modified modActiveUser `action` field to allow longer action labels
- Error upgrading table for class modAction
  Array
  (
  &#91;0&#93; => 42S21
  &#91;1&#93; => 1060
  &#91;2&#93; => Duplicate column name 'lang_foci'
  )
- Error upgrading table for class modSystemSetting
  Array
  (
  &#91;0&#93; => 42S22
  &#91;1&#93; => 1054
  &#91;2&#93; => Unknown column 'setting_name' in 'modx_system_settings'
  )
- Error upgrading table for class modSystemSetting
  Array
  (
  &#91;0&#93; => 42S22
  &#91;1&#93; => 1054
  &#91;2&#93; => Unknown column 'setting_value' in 'modx_system_settings'
  )
- Error upgrading table for class modSystemSetting
  Array
  (
  &#91;0&#93; => 42S21
  &#91;1&#93; => 1060
  &#91;2&#93; => Duplicate column name 'xtype'
  )
- Error upgrading table for class modContextSetting
  Array
  (
  &#91;0&#93; => 42S21
  &#91;1&#93; => 1060
  &#91;2&#93; => Duplicate column name 'xtype'
  )
- Error upgrading table for class modUserSetting
  Array
  (
  &#91;0&#93; => 42S22
  &#91;1&#93; => 1054
  &#91;2&#93; => Unknown column 'setting_name' in 'modx_user_settings'
  )
- Error upgrading table for class modUserSetting
  Array
  (
  &#91;0&#93; => 42S22
  &#91;1&#93; => 1054
  &#91;2&#93; => Unknown column 'setting_value' in 'modx_user_settings'
  )
- Error upgrading table for class modUserSetting
  Array
  (
  &#91;0&#93; => 42S21
  &#91;1&#93; => 1060
  &#91;2&#93; => Duplicate column name 'xtype'
  )
- Error upgrading table for class modManagerLog
  Array
  (
  &#91;0&#93; => 42S22
  &#91;1&#93; => 1054
  &#91;2&#93; => Unknown column 'class_key' in 'modx_manager_log'
  )
- Error upgrading table for class modUserMessage
  Array
  (
  &#91;0&#93; => 42S22
  &#91;1&#93; => 1054
  &#91;2&#93; => Unknown column 'postdate' in 'modx_user_messages'
  )
- Error upgrading table for class modUserMessage
  Array
  (
  &#91;0&#93; => 00000
  &#91;1&#93; => 1054
  &#91;2&#93; => Unknown column 'postdate' in 'modx_user_messages'
  )
- Error upgrading table for class modUserMessage
  Array
  (
  &#91;0&#93; => 42S22
  &#91;1&#93; => 1054
  &#91;2&#93; => Unknown column 'messageread' in 'modx_user_messages'
  )
- Config file successfully written.
- Config file permissions successfully updated.
- Updated the active workspace path. © 2005-2007 the MODx Content Mangement Framework (CMF) project. All rights reserved. MODx is licensed under the GNU GPL. MODx is free software. We encourage you to be creative and make use of MODx in any way you see fit. Just make sure that if you do make changes and decide to redistribute your modified MODx, that you keep the source code free!

**Comment by xpix** [comment]
xpix submitted:

How do you delete this. The bug was in my brain. Now it's fixed Thx

**Comment by opengeek** [comment]
opengeek submitted:

It needed to be noted actually; I'd like to see us hide the upgrade warning messages to be honest, with toggles to reveal them if you are curious. Errors will prevent the process from allowing you to continue.

**Comment by xpix** [comment]
xpix submitted:

Because the download of the new release was not working(some download snnipet problem) I tried the CVS and downloaded the latest version on top of the old one.
When I tried to install it over the old one I got those errors. But everything was ok. Maybe we should try the same for the alpha release.
