### ISSUE TITLE
Template Change warning message now blank (3653)

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2299]
bobray created Redmine issue ID 2299

When attempting to change a document's template, the warning message box pops up but contains no message.

**Comment by splittingred** [comment]
splittingred submitted:

Probably a lexicon issue. Also, what are we wanting this thing to say, anyway? What it should say has probably changed.

**Comment by garryn** [comment]
garryn submitted:

It should warn about losing unsaved changes to template variables as they get refreshed when changing the template - still relevant in my opinion.

**Comment by BobRay** [comment]
bobray submitted:

Bug still there in Revolution 2.0.0. I tried to find the code that launches the message box but had no luck.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3850

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
