### ISSUE TITLE
File editor truncates files on non UTF-8 characters

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2302]
bobray created Redmine issue ID 2302

The editor invoked in File Manager truncates files at non UTF-8 characters such as 0xE9 character. René Tschannen's name in a readme.txt file caused the rest of the file not to be displayed. It would be nice if the editor recognized this and offered an option to change the charset (eg to Latin1).

**Comment by splittingred** [comment]
splittingred submitted:

BobRay, would you happen to have a non-UTF-8 char file that we can test with?

**Comment by BobRay** [comment]
bobray submitted:

I'm 99% sure this is the file that bit me. It should truncate fairly near the beginning.

**Comment by splittingred** [comment]
splittingred submitted:

Cant seem to replicate this at all, including with this file.

**Comment by BobRay** [comment]
bobray submitted:

I just tried this again and it's still happening. The DB is all UTF-8 and the MODx charset is also UTF-8. The charset of the readme.txt file is also UTF-8, but Package Manager truncates the readme.txt file at the third character in René Tschannen during the install.

**Comment by BobRay** [comment]
bobray submitted:

This is the package with the troublesome readme.txt file. René Tschannen's name is near the end.
