### ISSUE TITLE
Move "allow root" from system configuration to role

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2303]
bobray created Redmine issue ID 2303

IMHO, this should be set on a per-user basis rather than being a global setting. It would make sense and be more consistent for it to go in Role | Permissions | Content Management. That's where most users would look for it.

**Comment by opengeek** [comment]
opengeek submitted:

I don't agree here; there is no more Role | Permissions | Content Management. This is a setting, that can be set system wide, and then overridden by both context and user settings. If this should be a permission, then it needs to be moved to Access Policies as an attribute that can be checked in each context.

**Comment by BobRay** [comment]
bobray submitted:

Things look a lot different now than when I reported this. My real point is that I think this should be set solely on a "per user" basis. Having it as as a global yes/no setting that can be over-ridden by contex and user settings seems likely to cause confusion and I quesion the necessity for the global setting. Maybe I'm not understanding its purpose. Maybe if I describe the event that led to the issue, there's a better way to deal with it. As a new user of MODx, I had a manager user who I gave the right to create new documents. He couldn't do it. I spent hours looking at his role and the various permissions I had given him. It was actually a day or two later that I stumbled onto the somewhat cryptic "allow root." and realized that the document he was trying to create was in the MODx "root." Since my user clearly had a "permission" problem, I was looking in roles and permissions for a solution. The best thing to do for a user is to put the solution to a problem where the user is likely to look for it. Remember also that a new user from a Windows or Mac enviroment has no reason to believe that the root is any different than any other directory and may not even be familiar with the term "root."

**Comment by opengeek** [comment]
opengeek submitted:

Problem here is that there is no way to attach User/Resource Group access controls to the root element of each Context (consider a theoretical Resource with id=0) since a Context cannot be assigned to a Resource Group, and having an allow_root that applies to all contexts (or can be overridden by context) is a workaround. I now fully agree this should be an attribute of an Access Policy, but I'm just trying to consider the optimal way to work this into the new permission scheme.

**Comment by opengeek** [comment]
opengeek submitted:

I believe this has been resolved with the introduction of new_document_in_root permission.

**Comment by BobRay** [comment]
bobray submitted:

How does udperms_allowroot System Setting interact with the new_document_in_root permission? If udperms_allowroot is set to "Yes" can everyone create docs in the root without the new_document_in_root_permisson?
