### ISSUE TITLE
Show all elements in every acess policy

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2304]
bobray created Redmine issue ID 2304

The "Basic" policy shows only attributes set to "true." It would be easier to modify existing policies if all attributes were shown as either true or false for every policy. It might also make sense to have a "default" policy that could be edited by the user and would be used when the user clicked on "Add."

**Comment by opengeek** [comment]
opengeek submitted:

All policies will show the attributes of that policy, regardless if they are true or false. I think you are simply confused at the different between the Basic policy, which applies to object access (i.e. can I load, create, remove, and/or save an object), and the Admin policy, which applies to Content Management actions (i.e. can a take this action in the manager). As an example to emulate 0.9.6 style permissions, you would assign a new copy of the Basic policy to a User Group with some attributes set to false to restrict access to a Resource Group (formerly Document Group), and you might create a new Admin policy with some attributes set to false to limit User Group permissions in a Context (specifically mgr and connector contexts, though those same content management activities could also be limited in other contexts if you enabled content management activities from a front-end for instance). Does that make any sense BobRay?

**Comment by BobRay** [comment]
bobray submitted:

I'm still a little hazy on the very last part but you're right, I was confused about the difference. I read them at first as basic user and admin user. In fact, I thought admin was for the back end and basic for the front end. I'd suggest calling them: Basic Object Access Policy
Basic Manager Action Policy or Default Object Access Policy
Default Manager Action Policy or at least changing the descriptions to avoid confusion since these are totally new concepts for many migrators from 0.9.6.

**Comment by opengeek** [comment]
opengeek submitted:

Great ideas BobRay; I'll make it so. The idea I had was to distribute some more complex, pre-defined policies that people can install and use, but I haven't worked out all the details yet. It's simple enough to distribute those in a transport package, but it still doesn't make usage any clearer. Thanks again for all your input.

**Comment by opengeek** [comment]
opengeek submitted:

I modified these recently to be the Resource and Context policies. Nice and simple to understand.
