### ISSUE TITLE
Add duplicate and rename to drop-down box in access policies

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2305]
bobray created Redmine issue ID 2305

Creating a new policy is largely unworkable without a separate list of the possible settings. A full-page checkbox list (like the one in roles) is probably coming, but it would also be nice to have the chance to duplicate existing policies, rename them, and edit them and this would provide an interim solution for creating and testing policies.

**Comment by splittingred** [comment]
splittingred submitted:

Implemented in r3643.

**Comment by BobRay** [comment]
bobray submitted:

Works in IE and FF, but there are some display quirks and bugs on edit of access policies (as of 3645). In IE, right scroll bar is half visible and the bottom of the description box isn't visible. It's usable but awkward In FF, nothing is visible but the cancel and save buttons. Expanding the window will show the tabs but there's no way to enter a description or edit the policy name. Dragging the bottom of the window down to expand it doesn't appear to do anything. Access Policies can be edited but you can't rename them or edit their descriptions.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3649 - confirm?
