### ISSUE TITLE
Edit box partially off screen in Access Policies

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2306]
bobray created Redmine issue ID 2306

Selecting edit for an Access Policy produces an edit box that extends below the bottom of the screen with no scoll bar to bring it up. In IE7 the buttons at the bottom are almost completely off the screen. In FF, they are partly off the screen. The window with the box can be moved up manually but should probably be positioned higher to begin with.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3601. Confirm?

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed (3611).
