### ISSUE TITLE
Drag and Drop not working for Resource Groups

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2308]
bobray created Redmine issue ID 2308

Resources can't be added to Resource Groups using drag and drop.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3561. Confirm?

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed &#8211; FF & IE7. Note: You can't drag and drop from the main tree at the left (which some users will try to do &#8211; I did at first) and get some strange effects when you try.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
