### ISSUE TITLE
Suggested improvement to document list in Profile | Statistics

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2309]
bobray created Redmine issue ID 2309

It would be a nice improvement if the "documents you created" list under Profile | Statistics mirrored the document tree rather than appearing as links so you could right-click on a document and go directly to edit or preview.

**Comment by splittingred** [comment]
splittingred submitted:

How about a grid? Check out latest update.

**Comment by BobRay** [comment]
bobray submitted:

The grid is WAY cool but it seems unintuitive that you have to select "edit profile" to see it.

**Comment by splittingred** [comment]
splittingred submitted:

Yeah, maybe "Edit Profile" needs to be changed to "Profile". Also, if you didnt notice, you can also dbl-click on most grids to edit their cells. (Not all, but most). This one, you can as well.

**Comment by splittingred** [comment]
splittingred submitted:

Deferring the Edit Profile fix until 097-beta.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed FF3, IE7, Chrome r4730
