### ISSUE TITLE
Add button on "Access Policies" page doesn't do anything.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2310]
bobray created Redmine issue ID 2310

Clicking on the Add button on the "Access Policies" page doesn't have any effect.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3560.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed FF, IE7.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
