### ISSUE TITLE
Html code showing in change username warning message

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2312]
bobray created Redmine issue ID 2312

In both FF and IE7, the two <br /> tags are visible in the warning popup seen when clicking on "change name" for an existing user.

**Comment by garryn** [comment]
garryn submitted:

Fixed in rev 3647.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed in FF and IE7 but the warning message box appears to be in a different style than other warning boxes (e.g. file delete and template change).
