### ISSUE TITLE
Quirks with password fields in User management

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2313]
bobray created Redmine issue ID 2313

When manually entering a new password for an existing user: In IE7, password entry fields don't appear until cursor is moved below the fields. In both IE7 and FF, success message is: The User has been created. The password is:.
(password is not shown and message is not really accurate). In both IE7 and FF, the password minimum length message shows up after the first character is typed. It makes the confirm password field jump down and is quite distracting for the user. It would be better if there was a message about min. length there to begin with and then a separate error message if a save is clicked for a too-short password.

**Comment by BobRay** [comment]
bobray submitted:

Related to MODx-110 Now, no password can be entered manually for new users in IE7. Double-clicking reveals a blue input area but it won't accept any characters.

**Comment by mkschell** [comment]
netprophet submitted:

This issue has been broken down into sub-issues.
The name of this issue has been generalized to more accurately reflect scope of the sub-issues.

**Comment by mkschell** [comment]
netprophet submitted:

updated Affects Versions because I'm still getting used to this

**Comment by splittingred** [comment]
splittingred submitted:

No longer valid in new layout. Issues are most likely deprecated.

**Comment by BobRay** [comment]
bobray submitted:

Still a couple of quirks. 1. The prompt string for the field with the "none, member, superuser" dropdown is blank in both IE7 and FF3. 2. In IE7, "let me select the password" - the two fields flash and disapper. Even when they're there, there's no way to enter data in them until after you've clicked on a field further down the page (good ol' IE7).

**Comment by BobRay** [comment]
bobray submitted:

Oops, one more issue. After creating a new user and saving, the screen reverts to the edit screen for the profile of the default admin user which seems kind of dangerous. It should probably revert to the users grid.

**Comment by splittingred** [comment]
splittingred submitted:

This is an old task; if problems are still occurring in IE7, please open up new tasks for each problem.
