### ISSUE TITLE
Move version checking to setup script and add notifications

### ISSUE THREAD

**Issue by ConseilsWeb** [modxbot/migrate#2314]
conseilsweb created Redmine issue ID 2314

Move version checking out of the manager front controller and insert it inside the setup/upgrade process.
Add common issues warnings like problems in certain PDO and MySQL versions.

**Comment by opengeek** [comment]
opengeek submitted:

Added some more checks up front in setup including version checking. Still need more but we should discuss those individually as issues are identified and solutions found.
