### ISSUE TITLE
Unset elements and elements returning empty should be handled differently by the parser

### ISSUE THREAD

**Issue by bs** [modxbot/migrate#2318]
bs created Redmine issue ID 2318

an element (in testing i used a placeholder) returning an empty string is not resolved until the end of the parsing. In general there should be a difference between an element being not set (yet) and an existing element returning an empty string . Currently both cases will not be resolved by the parser until the end.
In some cases this can result in wrong values in the final output.

**Comment by opengeek** [comment]
opengeek submitted:

Try this patch and see if it solves the problem without causing any other detrimental side effects.

**Comment by bs** [comment]
bs submitted:

Run into similar issues with snippets, as reported on irc, returning empty (as designed). The patch provided will also fix this. Also haven't noticed anything breaking because of this patch so i think it's save to commit.

**Comment by opengeek** [comment]
opengeek submitted:

Patch has been applied in changeset 3523.
