### ISSUE TITLE
Radio Options not working in TV

### ISSUE THREAD

**Issue by atma** [modxbot/migrate#2319]
atma created Redmine issue ID 2319

Radio Options in template variables displayed incorrectly - only first radio button without any lable.
Example code:
testchunk1==[ &#91;$testchunk1&#93; ]||testchunk2==[ &#91;$testchunk2&#93; ]
or
[ &#91;$testchunk1&#93; ]||[ &#91;$testchunk2&#93; ]

**Comment by mkschell** [comment]
netprophet submitted:

confirmed in LAMP / PHP4/MySQL 4 enviro

**Comment by mkschell** [comment]
netprophet submitted:

Committed r.3851
