### ISSUE TITLE
Convert File Browser to Ext 2

### ISSUE THREAD

**Issue by ConseilsWeb** [modxbot/migrate#2320]
conseilsweb created Redmine issue ID 2320

templates/default/js/browser/browser.js needs to be converted to Ext 2

**Comment by splittingred** [comment]
splittingred submitted:

Converted MODx.Browser to Ext2 in r3515, now waiting on valid TinyMCE package to test with.

**Comment by splittingred** [comment]
splittingred submitted:

Implemented in r3516.
