### ISSUE TITLE
Remove mcpuk and resolve all dependencies to new file browser

### ISSUE THREAD

**Issue by opengeek** [modxbot/migrate#2327]
opengeek created Redmine issue ID 2327

mcpuk must go now! the new file browser should be used in all the remaining locations where mcpuk is still being used

**Comment by opengeek** [comment]
opengeek submitted:

The new browser is at templates/default/js/browser/browser.js

**Comment by ConseilsWeb** [comment]
conseilsweb submitted:

Files still using mcpuk: manager/templates/default/element/module/_javascript.tpl manager/templates/default/element/tv/widgets/file.tpl manager/templates/default/element/tv/widgets/image.tpl manager/templates/default/security/user/_javascript.tpl Must be replaced by: manager/templates/default/js/browser/browser.js

**Comment by ConseilsWeb** [comment]
conseilsweb submitted:

manager/templates/default/js/browser/browser.js
needs to be converted for ExtJS 2.0
