### ISSUE TITLE
Can't edit files

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2331]
bobray created Redmine issue ID 2331

I can't edit any files in the new file manager. I can see them in the tree, but they are appear to be greyed out and the only right-click menu choice is "remove file."

**Comment by splittingred** [comment]
splittingred submitted:

Implemented in r3559.

**Comment by BobRay** [comment]
bobray submitted:

No quite there yet. I updated, did a build, and cleared all caches but the problem is still there in IE7. grayed filenames, no dropdown menu at all on right-click In FF, the filenames are still grayed out but I do get the dropdown menu. Clicking on Edit gives this error:
No action with ID system/file/edit found.

**Comment by splittingred** [comment]
splittingred submitted:

Sounds like your action cache didn't update. Make sure that there are records with ID 70 and 71 in the modx_actions table, and if so, delete the file: core/cache/mgr/actions.cache.php Then try.

**Comment by BobRay** [comment]
bobray submitted:

Now works in FF (upgrade install probably cleared the cache) but still no go in IE7. In IE7, no amount of right or left clicking on a filename has any effect (no drop-down menu, ever) except that double-clicking at just the right speed allows you to rename the file. Double-clicking has no effect in FF. It should probably launch edit as well.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3589.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed, IE7/FF (3611).

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
