### ISSUE TITLE
Change the way properties work within the scope of a chunk (modChunk)

### ISSUE THREAD

**Issue by bs** [modxbot/migrate#2336]
bs created Redmine issue ID 2336

Currently if you call a chunk with properties it will create (global) placeholders (prefixed with the chunkname).
As discussed on IRC it would be better to make these properties available only within the scope of the chunk and not make them into placeholders.
parseChunk get's close but only works programmatically. Limitation on parseChunk also is that is uses a string replace and stuff like output filtering wouldn't work.

**Comment by opengeek** [comment]
opengeek submitted:

I suppose we could add a function to unset placeholders so they are not available outside of whatever scope you want to limit them to, but if you want output filtering on these placeholders in a chunk, I don't see any other way to do it.

**Comment by bs** [comment]
bs submitted:

I think we should create a unset placeholder function for each placeholder creation function: toPlaceholder -> unsetPlaceholder
toPlaceholders -> unsetPlaceholders Also, in modChunk.class.php somewhere after the output is generated there should be a call for unsetPlaceholder to get the required effect.

**Comment by opengeek** [comment]
opengeek submitted:

This is fixed for alpha-5
