### ISSUE TITLE
Strange behaviour for nested snippet and chunks (called programmatically)

### ISSUE THREAD

**Issue by bs** [modxbot/migrate#2337]
bs created Redmine issue ID 2337

Test Case Create a snippet called "LevelOneSnippet" with the following code: <?php $ret = "<b>Level 1 SNIPPET</b><br />Calling getChunk for LevelTwoChunk with a value of " . $value . "<br />" . $modx->getChunk('LevelTwoChunk',array('value'=>$value)); return $ret; ?> Create a chunk called "LevelTwoChunk" with the following code: <b>Level 2 - CHUNK</b>:<br /> This is calling the LevelThreeSnippet with it's property value of (PLACEHOLDER) <br /> [[LevelThreeSnippet?value=`[[+LevelTwoChunk.value]]`]] Create a snippet called "LevelThreeSnippet" with the following code: <?php return "<p><b>Level 3 SNIPPET</b><br />Returning the passed value from the chunk as: " . $value . "</p>" ; ?> Create a new document ( uncheck Richt Text and Cacheable) with the following calls in it: [[LevelOneSnippet?value=`A`]]<br /> [[LevelOneSnippet?value=`B`]]<br /> [[LevelOneSnippet?value=`C`]]<br /> Scenario 1
View your page and you notice that they all return the same value (the first value being A). Scenario 2
Now make the snippet call in LevelTwoChunk uncached by changing [[ in [[!.
Save and view the page again.. notice that now they all show the LAST value being C. Scenario 3
Now in LevelTwoChunk replace (PLACEHOLDER) with [ &#91;+LevelTwoChunk.value&#93; ].
Save and view again... notice that they now return the correct value?!

**Comment by opengeek** [comment]
opengeek submitted:

This is resolved except scenario 2, which delays the processing of the snippet contained in the chunk until after all the chunks are processed. As a result, the value of the the placeholder nested in it's tags is not replaced until after the final chunk is processed, so the value will always be C in that case.

**Comment by opengeek** [comment]
opengeek submitted:

Note that Scenario 3 fixed the scenario 2 problem because the parser replaces all instances of a tag string in the content it is working on, regardless if it is nested in tags that are otherwise unreachable by the parser (i.e. processing delayed with a non-cacheable token).
