### ISSUE TITLE
Required fields on Create User

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2340]
bobray created Redmine issue ID 2340

Date of Birth, Blocked Until, and Blocked After are all required fields on the create user screen. Are these really necessary fields for a non-blocked user?

**Comment by BobRay** [comment]
bobray submitted:

Consider taking a stiff drink before reading further: This only occurs with IE7. In FF, email is the only required field. In IE7, email is not a required field, but the other three are (yikes) Environment: localhost, Windows Vista Ultimate Edition PHP5 MySQL 5.0.51a

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3449. Was occurring because IE is case-sensitive on HTML namespaced attributes. Yet one more motivational point to move this to a grid at some point.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed, IE7, FF2 - as of r3463
