### ISSUE TITLE
Create User has two General tabs

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2341]
bobray created Redmine issue ID 2341

The three tabs on the Create User screen are General, General, and Access Permissions

**Comment by BobRay** [comment]
bobray submitted:

Occurs in both FF and IE7 - Vista Ultimate Edition, PHP5, MySQL 5.0.51a

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3448.

**Comment by BobRay** [comment]
bobray submitted:

As of 3455:
Fixed in IE7
but in FF, selecting New on the user screen leads to a blank pane with this error: C has no properties
BasicForm(undefined)ext-all.js (line 133)
MixedCollection(undefined, undefined)ext-all.js (line 22)
MixedCollection( &#91;Object initialConfig=Object width=300 maxLength=100, Object initialConfig=Object width=100 inputType=password, Object initialConfig=Object width=100 inputType=password, 13 more...&#93; )ext-all.js (line 22)
BasicForm()ext-all.js (line 133)
_loadForm()create.js (line 36)
Create(Object)create.js (line 12)
(no name)()create.js (line 3)
Observable()ext-all.js (line 12)
EventManager()ext-all.js (line 13)
 &#91;Break on this error&#93; Ext.form.BasicForm=function(B,A){Ext.apply(this,A);this.items=new Ext.util.Mixed...

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed IE7 & FF2 as of r3463
