### ISSUE TITLE
Show filename when editing a file in File Manager

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2342]
bobray created Redmine issue ID 2342

At present, there's no way to tell which file you're editing in File Manager unless something in the file content tells you. In a directory with many similar files, it's easy to forget which one you're working on. One suggested solution to MODx-59 would take care of this at the same time.

**Comment by splittingred** [comment]
splittingred submitted:

File Manager has been deprecated and will be replaced by the file tree tab.
