### ISSUE TITLE
Setting a placeholder to the value 0 will return empty.

### ISSUE THREAD

**Issue by bs** [modxbot/migrate#2344]
bs created Redmine issue ID 2344

Reproduce: create a small snippet that sets a placeholder like this: $modx->setPlaceholder('myInteger',0); now retrieve the myInteger from a document, template or chunk with: [ &#91;+myInteger&#93; ] It will return empty. Same goes for: $modx->setPlaceholder('myString','0');
$modx->setPlaceholder('myBoolean,false); Probably because getPlaceholder Returns 0.

**Comment by mkschell** [comment]
netprophet submitted:

Are placeholders supposed to be strictly for strings?
If so, I wonder if there's a way to force them to output "0" under certain conditions (ie if the value evaluates to === 0 or === false) and "" (ie empty string) (if the value !is_set or an actual empty string) under others in a way that would solve this and not break anything.

**Comment by opengeek** [comment]
opengeek submitted:

This should be resolved as of revision 3446.
