### ISSUE TITLE
Updating an element attached to an existing category throws an error. (has workaround)

### ISSUE THREAD

**Issue by bs** [modxbot/migrate#2345]
bs created Redmine issue ID 2345

Updating an element attached to an existing category throws an error: "An error occurred while trying to save the category" log: (ERROR @ /modx/connectors/element/snippet.php) Error 23000 executing statement:
INSERT INTO `modx_categories` (`category`) VALUES (:category)
Array
(
 &#91;0&#93; => 23000
 &#91;1&#93; => 1062
 &#91;2&#93; => Duplicate entry 'Jot' for key 2
) Because i only have chunks and snippets i can only confirm that this happens for both these element. Reproduce: Create a category Create a chunk in this category Reopen the chunk you just created (have to be sure it's reloaded) Click save without touching the existing category dropdown Cause: When loading an element the formfield value of the Existing category (id: category) is populated with the NAME of the category instead of the ID.
When saving, this results in an insert of the category which fails because of duplicatie keys. If you touch the dropdown and make a selection the formfield value is correctly populated with the category id of the selection which enables the update to perform correctly.

**Comment by splittingred** [comment]
splittingred submitted:

I can't seem to reproduce this. I followed the exact steps, and mine updates fine. Also, the category field is being filled out with the ID on mine, correctly.

**Comment by splittingred** [comment]
splittingred submitted:

Submitter was using an old version; clearing cache fixed.
