### ISSUE TITLE
Top menu disappears in IE7 on search past bottom of page

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2346]
bobray created Redmine issue ID 2346

To duplicate: In IE7: Click on the MODx News tab.
press Ctrl-F and search for "remember" Top menu disappears and can only be recovered by refreshing the page.
Happens on a similar search on any long page, including editing resources.

**Comment by splittingred** [comment]
splittingred submitted:

It doesn't actually disappear...it looks like the bottom 2 panels (Ext.BoxComponents) actually move up 'over' it. This looks like an internal IE bug with positioning. May not be able to fix it.

**Comment by mkschell** [comment]
netprophet submitted:

Similar problem under IE6/Linux (under WINE - WINdows Emulator).
See IE6_scrolling_bug-Jira_ MODX-56 .jpg, attached.
About 1/3 of the top toolbar tucks up underneath the top margin.
I can not confirm IE6/Windows but I've found IE6 layout bugs on my system to be consistent with results from other testers on Windows in the past.

**Comment by BobRay** [comment]
bobray submitted:

In IE7, it's curious that it does not occur with scrolling, as far as I can tell, only with a browser search of the page. It does seem like an IE bug.

**Comment by BobRay** [comment]
bobray submitted:

I wanted to mention that on my machine, the top menu is completely gone in this condition and is unaccessible without a page reload. It's not partially covered as in the IE6 screen shot. It may depend on the screen resolution, I'm at 1680 x 1050. It would not be trivial to me if I used IE7 all the time because I often use Ctrl-F to jump to text I want to edit at the bottom of a long document.
