### ISSUE TITLE
Correct Trac URL in Support dropdown menu

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2347]
bobray created Redmine issue ID 2347

Trac URL should be updated or deleted: Line 474 : _build\data\transport.core.menus.php

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3428

**Comment by BobRay** [comment]
bobray submitted:

Shaun, I updated to 3439, did a build, and cleared the site cache and browser cache, but it's still going here: http://svn.modxcms.com/trac/tattoo/report/1

**Comment by splittingred** [comment]
splittingred submitted:

BobRay, it might happen on the setup/ run. I've done a complete build/setup run and it works. If you don't want to do that, you can always go to Tools -> Actions, then the Top Menu tab, and edit the values there for now.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed. Never did a setup but I've done a couple more builds and it's fine now &#8211; maybe a browser cache issue.
