### ISSUE TITLE
Change name of Configuration Tab.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2354]
bobray created Redmine issue ID 2354

The "configuration" tab (where warnings about config being writable, etc. appear) should be changed to avoid confusion with Tools | Configuration. Suggest changing it to "Site Status" or just "Status"

**Comment by BobRay** [comment]
bobray submitted:

Line 14 is the only change.

**Comment by BobRay** [comment]
bobray submitted:

The patch file changes the tab from "Configuration" to "Configuration check" which I think is what it was meant to be.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3426.
