### ISSUE TITLE
Change item grouping on doc. edit screen

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2356]
bobray created Redmine issue ID 2356

The grouping of the menu items on the document editing screen seems arbitrary: save | unpublish duplicate delete | preview cancel | options Suggest a vertical bar between all items or none

**Comment by BobRay** [comment]
bobray submitted:

Still needs a separater between "preview" and "cancel" IMO.

**Comment by splittingred** [comment]
splittingred submitted:

Added in r4092

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed IE7/FF3
