### ISSUE TITLE
Change double-click on Resource

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2358]
bobray created Redmine issue ID 2358

Double-click launches edit for Elements. It would be less confusing if it did the same for Resources. Single-click could either launch View for Resources or it could launch edit as with Elements.

**Comment by splittingred** [comment]
splittingred submitted:

Single-click launches elements for me...just like resources. What do you mean?

**Comment by BobRay** [comment]
bobray submitted:

Sorry, I wasn't realizing that there's no "view" as opposed to edit for elements. I was referring to the fact that you could get to editing an element by clicking on it's name but can't do the same for resources. It would be a nice feature for Resources if single-click launched "view" (as it does now) and double-click launched edit.
