### ISSUE TITLE
Add edit to drop-down list for elements

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2360]
bobray created Redmine issue ID 2360

The right-click drop-down menu for elements should include an "edit" option like the menu for resources.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3456

**Comment by BobRay** [comment]
bobray submitted:

Fixed in IE7 In FF, 2.0, right-click on element gives: Create a new %sHeresnippet
Create a new %sHerechunk etc.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed in both FF2 and IE7 as of r3478.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed Fixed.
