### ISSUE TITLE
Add another choice not sticky

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2361]
bobray created Redmine issue ID 2361

When "add another" is checked for editing chunks, snippets, or resources, clicking on save does create a new screen for adding another item but "add another" is no longer checked (changes to "continue editing").

**Comment by splittingred** [comment]
splittingred submitted:

None of the stay options are sticky atm...this needs to be fixed, somehow. Not sure how yet - I wish there was some nice way to communicate PHP's SESSION with Javascript

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3441.

**Comment by BobRay** [comment]
bobray submitted:

As of 3457: No on-save options appear in IE7 at all. In FF 2.0, icons appear at the far right (tooltips mostly off the screen) and clicking on them makes them jump back and forth slightly and makes scroll bar come and go. Clicking doesn't seem to have a consistent effect. I couldn't get it to go to "add another" at all. I think the radio buttons in 0.9.6 are much more user-friendly than the icons, BTW, and supply a more consistent interface. I prefer icons to be for things that happen right away like clearing the cache and trashing stuff. Radio buttons are more intuitive for settings.

**Comment by ConseilsWeb** [comment]
conseilsweb submitted:

How about making them buttons with labels and stick them to the left instead of the current 'save' button? This way, every action is only one click. No need to save status in session Example: Save & Close Save & Keep Editing Save & Add Another Cancel

**Comment by splittingred** [comment]
splittingred submitted:

So what's the verdict guys? I'm okay with however, but note that getting rid of the Stay options is a BIG_DEAL , programming wise. So I'd like a strong verdict from a majority of the team on this issue first before making any decisions. Vote for the issue, plz, to get it attention.

**Comment by BobRay** [comment]
bobray submitted:

I can't vote since I reported it but my first choice is the radio boxes because, once set, you don't have to think about it if you're working on a snippet and making a number of changes and testing them. Second choice would be Olivier's idea. Sorry, I don't know what you mean by "getting rid of the Stay options." Bob
