### ISSUE TITLE
Can't edit locked snippets or chunks (plugins ok)

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2362]
bobray created Redmine issue ID 2362

Snippets and chunks that are locked for editing can't be edited, even by the main admin, until locked status is changed in PhpMyAdmin. Also, the "item is locked" error message should probably be the same for all locked elements.

**Comment by BobRay** [comment]
bobray submitted:

FS#1009

**Comment by BobRay** [comment]
bobray submitted:

Possible solution: Uncomment line 239 of moduser.class.php // $_SESSION &#91;&#39;mgrRole&#39;&#93; = $ua->get('role'); It's the only place I can find where this $_SESSION var is set. Fixes the problem after deleting cookies. Should fix a number of other problems as well since that session var. is queried in many places. I thought it might fix MODx-71 (Can't edit files) but it doesn't appear to.

**Comment by BobRay** [comment]
bobray submitted:

Patch uncomments line 239 of moduser.class.php

**Comment by BobRay** [comment]
bobray submitted:

See MODX-137 - snippet now disappears from tree. The patch listed here still hasn't been implemented. Locked chunks seem well-behaved now.

**Comment by mkschell** [comment]
netprophet submitted:

Could not replicate in LAMP - PHP4 environment. MODx r.3819
Was able to edit > lock > close > edit > update > verify Snippet.
Has this been fixed, maybe by a fix for something else?

**Comment by opengeek** [comment]
opengeek submitted:

This is no longer an issue; to allow users to edit locked Elements, they must have the edit_locked policy attribute in the mgr and connector contexts. Just FYI the role field on the modUser object is no longer used and will be removed for beta. Roles in MODx now define a user's role within a group, defining an authority level that user has within a specific group membership.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed - no longer an issue.
