### ISSUE TITLE
echo in snippet - output appears at top of page

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2363]
bobray created Redmine issue ID 2363

echoed output in a snippet appears at the top of the page rather than at the snippet call location. Document content: <h1>Title</h1>

<p>Some text</p>

[ &#91;Snippet Call&#93; ] Snippet content: echo "Hello";
return "goodbye"; Output: Hello
Title
Some Text
Goodbye

**Comment by BobRay** [comment]
bobray submitted:

Note: This is NOT FS#1010. This is new since that was fixed.

**Comment by opengeek** [comment]
opengeek submitted:

Fixed by prepending any echo/print content captured in an output buffer wrapping the function representing the modScript to any content returned by the function.
