### ISSUE TITLE
getParentsIds infinite recursive loop

### ISSUE THREAD

**Issue by ghost** [modxbot/migrate#2377]
sottwell created Redmine issue ID 2377

Under certain conditions the getParentsIds function in modx.inc.php can go into an infinite loop, causing a PHP out-of-memory error. This was triggered in a case with two documents in the Tree, one container document in the document root and one child document. Array_search returns either FALSE or the key of the array element found. If the key happens to be 0, as in the parent of the document being processed is 0, then the IF condition will evaluate to FALSE and a value is not put into the $parents array. This can lead to an empty $parents array, which in the final array_merge function where the recursive getParentsIds call is made will cause an infinite loop. The fix is in two parts, one in making an explicit comparison to FALSE in the IF conditional expression, and the other is adding a check for an empty $parents array before the array_merge call. Below is the patched getParentsIds function. getParentsIds function getParentIds($id= null , $height= 10) { $parentId= 0; $parents= array (); if ($id && $height >= 0) { foreach ($ this ->resourceMap as $parentId >= $mapNode) { if (array_search($id, $mapNode) !== false ) { $parents[]= $parentId; break ; } } if ($parentId && !empty($parents)) { $parents= array_merge($parents, $ this ->getParentIds($parentId, $height--)); } } return $parents; }

**Comment by opengeek** [comment]
opengeek submitted:

Committed at revision 3417
