### ISSUE TITLE
New Weblink Page is out-of-date

### ISSUE THREAD

**Issue by splittingred** [modxbot/migrate#2380]
splittingred created Redmine issue ID 2380

Convert to 0.9.7. Talk with Jason about this possibly being a new Resource Type and how to handle it from there.

**Comment by opengeek** [comment]
opengeek submitted:

The delegate processors for modWebLink already exist at core/model/modx/processors/resource/weblink/\* along with the Smarty templates for the delegate views at manager/templates/default/resource/weblink/\* You'll need to create any needed delegate views in manager/controllers/resource/weblink/*

**Comment by ConseilsWeb** [comment]
conseilsweb submitted:

I had to hack manager/templates/default/resource/weblink/create.tpl to make it think that it's a modResource, instead of a modWebLink. Otherwise I get an error in loadForm, I'm thinking it could be a missing class definition somewhere, but I'm not sure.
