### ISSUE TITLE
Various User Management Errors

### ISSUE THREAD

**Issue by opengeek** [modxbot/migrate#2383]
opengeek created Redmine issue ID 2383

Found several problems in user management: New in the toolbar when viewing the grid results, in message: "No action with ID 11 found." Several required fields should automatically select default values (Editor to use and Language specifically) When saving a new user without selecting a gender, the grid of users will no longer load. Close and Continue Editing options both just continue editing; close should act like Cancel after a save. After creating a new user and selecting role of Administrator, logging in as that user results in no permission to do anything, including logout.

**Comment by splittingred** [comment]
splittingred submitted:

Someone want to verify these and split them up into separate tickets? Right now this ticket is a mess...
