### ISSUE TITLE
Add transport package installation processors and manager user-interface

### ISSUE THREAD

**Issue by opengeek** [modxbot/migrate#2385]
opengeek created Redmine issue ID 2385

The default manager interface needs to now include a transport package management interface with the following features: MODx Software Update Configuration Management Panel
o List of installed transport packages and controls (disable, uninstall, remove)
o List of local transport packages that are not installed and controls (install, remove)
o Package detail panel with version information and package controls (install, disable, uninstall, remove) Package Provisioning Panel
o List of remote package update sites with add/edit/remove controls
- Remote package update site editor panel (dialog)
  o Search for New packages to install
  o Search for Updates to installed packages

**Comment by opengeek** [comment]
opengeek submitted:

This is in progress, but on hold pending completion of the reference package provider service implementation.

**Comment by opengeek** [comment]
opengeek submitted:

Shaun, is this completed as described or do we have more to complete on this side of the issue?

**Comment by splittingred** [comment]
splittingred submitted:

No, it's not done. The 'update package' processors and code still need to be done fixing uninstall; doesn't work properly there's also problems if you remove a package that was never installed (it wont work). "search for updates to installed packages" doesn't exist
