### ISSUE TITLE
Import HTML Needs Conversion to 097

### ISSUE THREAD

**Issue by splittingred** [modxbot/migrate#2388]
splittingred created Redmine issue ID 2388

Neither page has yet been converted to 097. May need to work with 097 packaging support.

**Comment by opengeek** [comment]
opengeek submitted:

There are now two separate import features, one similar to legacy import of HTML, and the other is a more generic import for bringing in static and/or traditional resources. Export is not yet converted

**Comment by opengeek** [comment]
opengeek submitted:

I'm reopening a duplicate task for the export process and editing this ticket to relate only to import

**Comment by opengeek** [comment]
opengeek submitted:

this has been in for a while

**Comment by opengeek** [comment]
opengeek submitted:

closing
