### ISSUE TITLE
404 Redirect not working in IE6

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2391]
bobray created Redmine issue ID 2391

Trying to navigate to a non-existant document redirects to the error document selected in Tools | Configuration in FireFox? but in IE6, generates IE's standard 404 "Page cannot be found" page (tested only on localhost). &#8212; Error pages need to be greater than 512 bytes in size else IE6 will ignore them and default to the generic error page. First I tested with a custom error page less than 512 bytes and had the behaviour you described; then I tested with an custom error page of 3032 bytes and the custom error page is used as intended. Can you confirm if using a larger-sized custom error page works for you as well?
-garryn

**Comment by garryn** [comment]
garryn submitted:

Could somebody please try my suggestion above? I think this is an IE6/7 issue and not a 097 issue. In which case, we can get this bug report closed off.

**Comment by BobRay** [comment]
bobray submitted:

I no longer have a machine with IE6 and a localhost 0.9.7 install. I do have IE6 on my laptop but I don't think there's enough space for 0.9.7 and XAMPP on it. When I saw the bug, I think I had the site's home page set as the 404 page but it could have been a very small page at that point. Do you have some 0.9.7 URLs I could try with IE6? I can go to a non-existent page and see if I get the error. If not, I think you can close out the issue since it's not really a problem if it only happens on localhost. (and IE6 is probably fading fast as a browser of choice, expecially for anyone savvy enough to install a localhost web server). Bob

**Comment by ConseilsWeb** [comment]
conseilsweb submitted:

This is not a MODx problem, but a browser "feature". It seems that if you install the Google Toolbar, you'll also get this sort of feature, as garryn mentionned. Here's a non-technical debate about it:
 http://www.techcrunch.com/2008/02/13/google-officially-hijacks-404-pages-what-do-you-think/
