### ISSUE TITLE
Scrollbar not showing in policy property list

### ISSUE THREAD

**Issue by ghost** [modxbot/migrate#2392]
sottwell created Redmine issue ID 2392

When editing a policy with a long list of properties the scrollbar does not appear initially, one needs to close the list view then open it again.

**Comment by splittingred** [comment]
splittingred submitted:

This doesn't happen to me - server/browser info?

**Comment by ghost** [comment]
sottwell submitted:

Probably a browser issue; FF 2.0.0.12/Mac

**Comment by splittingred** [comment]
splittingred submitted:

You're right. Seems that FF/Mac isn't respecting the height on initial loading.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed by applying this.doLayout(); after the form was rendered.
