### ISSUE TITLE
Top Menu not updated in upgrade

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2476]
bobray created Redmine issue ID 2476

After upgrading an older site (not sure -- probably RC1), I'm still seeing the old Top Menu (no "Access Controls"). I'm pretty sure the menu had not been customized in any way.

**Comment by splittingred** [comment]
splittingred submitted:

Can't reproduce this at all; just tried an update with some different menus, and the menus were added or changed fine.
