### ISSUE TITLE
Revolution TV display in the Resource Documents

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#2480]
onepack created Redmine issue ID 2480

Some people have to get used to the "tabs display" for the TV's. I had to get used to them as well. For me it's ok now but it would be great if there could be an option in the system setting where people can choose the way of displaying the TV's. Classic or New with the tabs.

End users understand the "content managing" better when they can see the TVs in the same order in one page as they are displayed on the frontend.

**Comment by splittingred** [comment]
splittingred submitted:

There's now a setting in 2.2 that allows you to move the TVs to below the content.
