### ISSUE TITLE
Duplicating a Resource document doesn't auto generate alias

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#2483]
onepack created Redmine issue ID 2483

"automatically generate resource alias" in the system settings doesn't work when a document gets duplicated with a new name.

**Comment by opengeek** [comment]
opengeek submitted:

Fixed for 2.0.5-pl -- see commit details at http://github.com/modxcms/revolution/commit/f5532a31bd024a6f15e218e7a7e6a2ad78738045
