### ISSUE TITLE
Include "noaccents" feature in the core ( modtransliterate )

### ISSUE THREAD

**Issue by maxpiepenbrink** [modxbot/migrate#2489]
mido created Redmine issue ID 2489

As evo had, it will be good to have "noaccents" feature in the core of Revo.
It is done here:
http://modxcms.com/forums/index.php?topic=52617

**Comment by opengeek** [comment]
opengeek submitted:

The official custom transliteration extension is available now as a Core Extension. This will not go in the core as it is meant to be an extension to the core functionality. The translit service could also be useful for other components, but people may want to change the implementation for specific purposes.

See http://modxcms.com/extras/package/740
