### ISSUE TITLE
All links to online documentation need to reflect rtfm.

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#2492]
wshawn created Redmine issue ID 2492

Some links are still pointing to the old svn documentation.  Also, some of these links are still requiring log in -- which may send the user to a never ending loop of a redirect.

Example from the Form customization page (text in paragraph): 
[[http://svn.modxcms.com/docs/display/revolution/Form+Customization]]

Sends me to a log in page. Once logged in I get continuously looped (redirected).  Even clicking a link on that page to leave it gets redirected back to that page. Any and all links going to http://svn.modxcms.com/docs/display/revolution have this issue, but http://svn.modxcms.com/docs/display/revolution20 does not.

Closing the browser tab / window is the only recourse. At one point this redirect was most likely responsible for the doc server coming down.

**Comment by splittingred** [comment]
splittingred submitted:

Most of these are already fixed; fixed the Bugs reference in the Support menu in: http://github.com/modxcms/revolution/commit/f776e552ab890b35f913ec9a8a02661d7be2b5e9
