### ISSUE TITLE
Help button on Form Customization returns 404 

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#2493]
wshawn created Redmine issue ID 2493

Broken link:
[[http://rtfm.modx.com/display/revolution20/Form+Customization]]

Corrective action: change link to [[http://rtfm.modx.com/display/revolution20/Customizing+the+Manager]]

or Rename the doc page to Form+Customization

**Comment by splittingred** [comment]
splittingred submitted:

Already fixed in http://github.com/modxcms/revolution/commit/aa79cebd9cf61d885012deb8567587a088afc1cb
