### ISSUE TITLE
parent resource icon toggles when collapsed/expanded

### ISSUE THREAD

**Issue by jrotering** [modxbot/migrate#2496]
jrotering created Redmine issue ID 2496

While trying to reproduce issue 2495, I found that when a resource becomes a parent as the result of a drag+drop operation, it doesn't properly change its icon to the 'folder' parent icon.  It gets the folder icon when in collapsed state, but when expanded it keeps the regular resource icon.

When a resource becomes a parent by a "create resource here" operation, it gets the folder icon in both collapsed & expanded  state.

This seems to persist throughout the immediate manager session - if I log in to a new session, the parent icons behave 100% as expected.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/7c70bf9cedc048367ff86d5c4693702f52fdcddf
