### ISSUE TITLE
Property Sets export filename hardcoded

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#2507]
wshawn created Redmine issue ID 2507

Currently, all exports are called properties.js,

Can we be afforded the opportunity to export the entire set by the setname?

Can we be afforded the ability to name the properties via a save dialogue?

**Comment by splittingred** [comment]
splittingred submitted:

Fixed; now prefixes JS file with name of property set.

http://github.com/modxcms/revolution/commit/c6f0422c28990f579af3ad58de4394705bcae46d
