### ISSUE TITLE
Have setup clear the site cache and flush permissions before starting

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#2511]
wshawn created Redmine issue ID 2511

Would it be feasible to have setup clear the site cache and log everyone out before starting?

**Comment by splittingred** [comment]
splittingred submitted:

It already does this - if it doesn't, that's a problem with your environment.

**Comment by wshawn** [comment]
wshawn submitted:

I have read the changes to the JavaScript web browser caching mechanism, but did not notice any mention this had been implemented.

Thank you, and yes it works fine.
