### ISSUE TITLE
Have "Remove setup folder" default to selected at end of setup

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#2512]
wshawn created Redmine issue ID 2512

The default action of the majority of users is to have this selected, or get warnings from the Manager. The minority of users will probably want to keep the setup folder.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/913490d3068669ba67636ffba9794420b6bc71fc

Although, for Git checkouts of MODx, this box will remain unchecked by default.
