### ISSUE TITLE
Cannot Drag&Drop elements  to tinymce

### ISSUE THREAD

**Issue by maxpiepenbrink** [modxbot/migrate#2515]
mido created Redmine issue ID 2515

I cannot drag&drop elements ( chunks or snippets ) to tinymce. 
A green "V" is shown but it cannot be dropped. It can be dropped to summary or if i toggle editor to textplain.

**Comment by splittingred** [comment]
splittingred submitted:

This is because of a security restriction in Firefox; DOM elements cannot be drag/dropped into an IFRAME, which TinyMCE uses. There is, unfortunately, no way to get around this.

**Comment by MokoJumbie** [comment]
MokoJumbie submitted:

CKEditor uses iframes in firefox and is able to accept dropped elements. Is it possible to use their implementation to get this functionality in TinyMCE?
