### ISSUE TITLE
TinyMCE TV doesn't work when moved from tab

### ISSUE THREAD

**Issue by ghost** [modxbot/migrate#2518]
paramaniac created Redmine issue ID 2518

I have noticed a bug whereby when I move a custom richtext (TinyMCE) TV from the TV tab, to the main Edit tab, the TinyMCE editor does not work.
The TinyMCE editor is visible but you cannot put the cursor or type into the editor, and none of the buttons in the toolbar work.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/81d67feee42e13cd156d4f056f44d7caddbcd518
