### ISSUE TITLE
Preview not working as expected for context documents

### ISSUE THREAD

**Issue by xpix** [modxbot/migrate#2523]
xpix created Redmine issue ID 2523

Hi,

Preview functionality for context pages is not working.
There are 2 ways to preview a page:
1. using the drop menu in the tree
2. when in document click the Preview button top right

Both of them do not generate/redirect to the correct page.

Some examples
http://www.Site.com/manager/ContextSite.comindex.php?id=8
http://Site.comindex.php/?id=3

Meanwhile I'll just build the url myself

**Comment by splittingred** [comment]
splittingred submitted:

Works for me. What are your Context Settings and how did you set up the context?

**Comment by xpix** [comment]
xpix submitted:

I thought this should work without the "Switch Context" plugin. Now that I configured the plugin it works.

Thank you
