### ISSUE TITLE
Text values not is not selectable for some tables

### ISSUE THREAD

**Issue by xpix** [modxbot/migrate#2524]
xpix created Redmine issue ID 2524

Hi,

It would be very useful if we can select the text in some of the tables.

Examples:
I cannot select the KEY value from System Settings. When creating context is very useful to just copy the value instead of writing it. e.g settings_version
In order to copy the value I have to click Update than copy the  value in the first row.

Another example is the "Database version:" value in "System Info". I can select/copy "Database version:" but not the actual value.

Thanks

**Comment by splittingred** [comment]
splittingred submitted:

This is an ExtJS bug; postponing this until later releases.
