### ISSUE TITLE
Revo-Update still overwrites filemanager path values

### ISSUE THREAD

**Issue by gerritvanaaken** [modxbot/migrate#2526]
gerritvanaaken created Redmine issue ID 2526

Although this bug was marked as fixed – after upgrading from 2.0.3 to 2.0.4, my filemanager values in system preferences have been overwritten once again.

**Comment by splittingred** [comment]
splittingred submitted:

The code that updated them has been erased; not sure how you're still getting this unless all your files are not being uploaded correctly.
