### ISSUE TITLE
Database entries for all file uploads

### ISSUE THREAD

**Issue by gerritvanaaken** [modxbot/migrate#2527]
gerritvanaaken created Redmine issue ID 2527

An unmodified installation of MODx lets you upload and manage files within the physical file system, just as if using FTP. Which is basically fine.

However, in 98% of real world use cases, the editor would want to add meta information to the files she just uploaded. In most other CMS you simply cannot upload a file without creating a database entry with several meta data such as title, description, unique ID, file size, image size and so on. It’s just good practice that helps to connect and embed the files within resources, slideshow plugins, download lists and so on.

While I understand that MODx wants these database things to be done by add-ons (like "Gallery"), I do think it’d be better to have core functionality for that.

File and Image handling is rather a weakness of MODx, especially in comparison to WordPress, where you have quite a clever system of attaching files to certain pages, or just place them on a global scope.

In my opinion, the _default_ way to upload files should be to create easy-to-access database entries alongside the physical file, as a basis. If there is the need for more sophisticated file handling, we can still use add-ons to do that.

**Comment by opengeek** [comment]
opengeek submitted:

This is what Static Resources are for, uploading files and providing MODx metadata for them. This is already possible. The file and image management outside of Static Resources is for convenience where needed, i.e. for files that you want to manage on the filesystem only.
