### ISSUE TITLE
TinyMCE Link-Popup: No string replacements

### ISSUE THREAD

**Issue by gerritvanaaken** [modxbot/migrate#2528]
gerritvanaaken created Redmine issue ID 2528

The labels and tab titels of the "MODx link" popup in TinyMCE are cryptic and not replaced by their proper natural language strings. See attached screenshot!

**Comment by splittingred** [comment]
splittingred submitted:

TinyMCE is an Extra and not part of the core - please file TinyMCE issues in the proper location. 

TinyMCE issues can be filed here:
http://github.com/splittingred/TinyMCE/issues
