### ISSUE TITLE
Problem uninstalling a component (gallery)

### ISSUE THREAD

**Issue by stratboy** [modxbot/migrate#2530]
stratboy created Redmine issue ID 2530

(revo 2.0.4)

If I uninstall Gallery, I continue to see it under the components menu item. Even if I force permanent removal (by following the right click options), I continue to see it under the components menu.

Also, (but maybe this is unrelated or it depends on the component, not on modx) the gallery component simply doesn't work. I made some posts very recently under the general support forum.

**Comment by splittingred** [comment]
splittingred submitted:

Please post bugs related to Gallery under Gallery issues on Github:

http://github.com/splittingred/Gallery/issues
