### ISSUE TITLE
Problem installing revo 2.0.4-pl2

### ISSUE THREAD

**Issue by stratboy** [modxbot/migrate#2531]
stratboy created Redmine issue ID 2531

This is a problem of a friend of mine that's not registered to jira-

? Test database server connection and view collations.
Connecting to mysql server:  Success!
- Checking MySQL server version: OK! Running: 4.1.22-standard-log
- Checking MySQL client version: OK! Running: 4.1.22

Till here, all fine. Then:

Create or test selection of your database.

> there's a js error on ext-core.js (line 9)

syntax error
[Break on this error]()

So he can't install.

This happens both on safari and ff. 
On ie, also the charset and collation combo remain empty.

**Comment by stratboy** [comment]
stratboy submitted:

windows xp sp2 (forget to write sp2)

**Comment by opengeek** [comment]
opengeek submitted:

Going to have to provide a lot more details in order for us to diagnose or reproduce this. So far no luck.

**Comment by wshawn** [comment]
wshawn submitted:

I would suggest a couple of things:  install a new version of WAMP.  The MySQL version is quite old.  Secondly re-download and re-install the file from scratch.
Lastly, opengeek is correct.  We need alot more information that what has been provided to sufficiently help.

**Comment by opengeek** [comment]
opengeek submitted:

No feedback in over a week. Closing.
