### ISSUE TITLE
page tree: folder icons looks too different from resource icon

### ISSUE THREAD

**Issue by gerritvanaaken** [modxbot/migrate#2532]
gerritvanaaken created Redmine issue ID 2532

There is not much difference between a resource folder and a simple resource without child resources. So it’s a little bit confusing for editors that the icons of those two types look so dramatically different. 

Evolution does a better job at this, here the icons share the same color and style.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/d2cc3b85d5a2a5ca922d5d26ad0a3e77b46c07a9
