### ISSUE TITLE
Tiny MCE base reference in correct

### ISSUE THREAD

**Issue by keiron77** [modxbot/migrate#2546]
keiron77 created Redmine issue ID 2546

TinyMCE adds /assets/components/tinymce/ to every link I add using the TinyMCS "add link" function.
When changing the tiny.path_options setting the path changes but still contains the above fragment - e.g. http://www.mydomain.com/assets/components/tinymce/PATH-I-WANT

This (wrong) replacing occurs before saving the page using modx. I.e. after adding a link [[~17]] and clicking insert, then editing the link again without saving tinyMCE already transformed the link to: /assets/components/tinymce/[[~17]].

**Comment by splittingred** [comment]
splittingred submitted:

TinyMCE issues should be reported on the TinyMCE GitHub issues page, here:

http://github.com/splittingred/TinyMCE/issues

Closing since this isn't a Revo issue but a TinyMCE one. Thanks!
