### ISSUE TITLE
Array-based properties not unset as placeholders in an iterative chunk

### ISSUE THREAD

**Issue by splittingred** [modxbot/migrate#2552]
splittingred created Redmine issue ID 2552

$this->xpdo->unsetPlaceholders(array_keys($this->_properties));

array_keys isn't recursive, so stuff like [[+extended.color]] isn't unset.

A good solution would be to automatically convert it to prefix dot syntax before passing into toPlaceholders earlier, or writing a recursive array_keys method.

**Comment by opengeek** [comment]
opengeek submitted:

This is resolved for the "next" release.

See http://github.com/modxcms/revolution/commit/3dea257d6ef4b046c94d8db942bfd1dc07f5813a for commit details.
