### ISSUE TITLE
browser file list does not load from the correct asset folder of the current context

### ISSUE THREAD

**Issue by scotto** [modxbot/migrate#2553]
scotto created Redmine issue ID 2553

/core/model/modx/processors/directory/getfiles.php is making calls to FileHandler::getBasePath() without providing the context parameter

$root = $modx->fileHandler->getBasePath();

should be 

$root = $modx->fileHandler->getBasePath(null, $scriptProperties['ctx']);

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/d5ce53cca0bee6976b33ad6333daebbf13c7d934
and http://github.com/modxcms/revolution/commit/ff2f88dfb5498f2ed3cf2ededc252240f6b44189
