### ISSUE TITLE
browser folder list does not load the correct asset folder of the current context

### ISSUE THREAD

**Issue by scotto** [modxbot/migrate#2554]
scotto created Redmine issue ID 2554

/core/model/modx/processors/directory/getlist.php is making calls to FileHandler::getBasePath() without providing the context parameter

$root = $modx->fileHandler->getBasePath();

should be 

$root = $modx->fileHandler->getBasePath(null, $scriptProperties['ctx']);

**Comment by splittingred** [comment]
splittingred submitted:

This was fixed in an earlier 2.0.5-dev commit.
