### ISSUE TITLE
phpthumb refuses to traverse outside of its docroot

### ISSUE THREAD

**Issue by scotto** [modxbot/migrate#2555]
scotto created Redmine issue ID 2555

By default config in /core/model/phpthumb/phpthumb.class.php phpThumb is not allowed to do anythign with files outside of its docroot, this causes asset folders outside of the docroot ( from other contexts ) to fail when generatign the thumbnail.

public $config_allow_src_above_docroot              = false;

should be 

public $config_allow_src_above_docroot              = true;

unless theres a security risk that im not aware of.

**Comment by opengeek** [comment]
opengeek submitted:

Will add system settings for more of the phpthumb configuration options that need to be available, including this one with better defaults.

**Comment by opengeek** [comment]
opengeek submitted:

Fixed for next release along with a major bug in phpthumb nohotlink logic.

Commit details at http://github.com/modxcms/revolution/commit/a744ac66cb678e6180bbe44d786f4e2077b6544b
