### ISSUE TITLE
Difficulties using the resourcelist

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#2560]
onepack created Redmine issue ID 2560

I ran into difficulties using the resourcelist. It doesn't save the selected page/ resource. In the backend it keeps on showing "home" even when I save it displaying "contact" and the default is "2" (contact). This happens for all users, also the administrators.

**Comment by onepack** [comment]
onepack submitted:

This issue is actually more than minor... Every time a page loads with assigned TVs with Input Type "resourcelist" their values reset to "Home".

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in: http://github.com/modxcms/revolution/commit/2f2977e3001674f761ecb483ba4b07826f0fbbc0
