### ISSUE TITLE
Removing resource group

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#2564]
onepack created Redmine issue ID 2564

Removing a resource group from the resource groups list doesn't activate a save button.

**Comment by splittingred** [comment]
splittingred submitted:

On what screen?

**Comment by onepack** [comment]
onepack submitted:

Hi Shaun, I'm sorry but I got confused with the available "save button" in the "resource Group Access" tab under the "access controls".
After I removed the resource group from the list I expected the save button to become available, not being aware of the fact that the system already saved the new setting. 

Sorry for the confusion, I have to get used to the new system ;-)
