### ISSUE TITLE
Resourcelist ouput as URL

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#2566]
onepack created Redmine issue ID 2566

A nice improvement would be to be able to retrieve the Page title of the selected document from the resourcelist when the outputfilter is set to "URL".
The display Text should be able to handle the [[+pagetitle]]. It now renders empty.

Next to that when using the URL output filter it would be nice if the page id that you retrieve by using the resourcelist was already transformed to a path with [[~id]]
or at least give the developer the ability to select that option in the tv setup.

When I want to make a link within the site I now need to have at least 2 TVs. One for the Display text and one for the Link ID.

The "end-user" friendly approach would be using the resourcelist with output as URL.

**Comment by onepack** [comment]
onepack submitted:

Do I need to target a release to have a ticket picked up? I see this one is from 19-10-2010

**Comment by splittingred** [comment]
splittingred submitted:

Done: https://github.com/modxcms/revolution/commit/91f0f86ab1ecabb9a6376ffa9e445c30d2f5facb
