### ISSUE TITLE
German table for translit

### ISSUE THREAD

**Issue by MadeMyDay** [modxbot/migrate#2567]
mademyday created Redmine issue ID 2567

http://modxcms.com/forums/index.php/topic,52617.msg321774.html#msg321774

In german we have some transliterations that are not the same as in the common/noaccent table, so I decided to make an own one.

**Comment by opengeek** [comment]
opengeek submitted:

I have incorporated this into a "translit" core extension package, which I am now hosting at http://github.com/opengeek/translit so we can collaborate and track additional translit table contributions, etc.

I am going to provide it as a package in the Extras section so it can be downloaded and installed from package management in the Revolution manager UI.
