### ISSUE TITLE
Ability to remove multiple permissions in access policy

### ISSUE THREAD

**Issue by ukwiz** [modxbot/migrate#2568]
ukwiz created Redmine issue ID 2568

There is currently no way to remove several permissions at once in access policy. For instance, when duplicating the administrator policy as the basis for a much stripped down policy. Removing each permission individually is time-consuming.
It is possible to highlight several by using ctrl-click, but remove permission doesn't operate on them all.

**Comment by splittingred** [comment]
splittingred submitted:

No longer valid due to new Access Policy / Access Policy Template UI.
