### ISSUE TITLE
Variable filemanager path

### ISSUE THREAD

**Issue by theuros** [modxbot/migrate#2569]
theuros created Redmine issue ID 2569

When you create a TV with input type image or file, filemanager opens allways on defined path. I'd like to have an option to limit this path for each TV. For example if i write in "Input Option Values" something like  "/assets/myfiles/", file manager will open exactly in that defined folder "myfiles".

**Comment by wshawn** [comment]
wshawn submitted:

Additionally,

please allow the "Input option Values" to limit file type either string (pdf) or double-pipe delimited (gif||jpg||png)

**Comment by splittingred** [comment]
splittingred submitted:

Already fixed through TV input options.
