### ISSUE TITLE
Move TV to tab and attach action @ creation

### ISSUE THREAD

**Issue by charliez** [modxbot/migrate#2574]
charliez created Redmine issue ID 2574

When creating a new TV, have a drop-down with the new tabs (if they exist) and actions (multi-select) to select.  So in essence we would be creating the new TVs and its rules at the same time.

Reference: Whttp://modxcms.com/forums/index.php?topic=53126
Topic #2

**Comment by splittingred** [comment]
splittingred submitted:

Invalid due to new FC UI.
