### ISSUE TITLE
Pack new tabs, actions & rules

### ISSUE THREAD

**Issue by charliez** [modxbot/migrate#2575]
charliez created Redmine issue ID 2575

Package the FC Rules, new tabs, etc in PackMan so then all is set after installing the distribution.

Reference: http://modxcms.com/forums/index.php?topic=53126
Topic: #2

**Comment by splittingred** [comment]
splittingred submitted:

Can you file this here: http://github.com/splittingred/PackMan/issues

Since this is a PackMan issue and not a Revo one.
