### ISSUE TITLE
Make parameters case insensitive

### ISSUE THREAD

**Issue by MadeMyDay** [modxbot/migrate#2577]
mademyday created Redmine issue ID 2577

Just discovered that snippet calls are case insensitive, what is good imho. I think it would be consequent to handle the parameters the same way. For example it is very hard to understand why it is "&sortby" and "&showHidden" in getResources. If we would eleminate the the need for case sensitivity, a lot of mistakes wouldn't occur.

**Comment by opengeek** [comment]
opengeek submitted:

Actually, the intention is for all Element names to be case-sensitive. I do not think case-insensitivity is a solution, and instead might argue that a Snippet with wrong case should not work, and that is the bug.

**Comment by wshawn** [comment]
wshawn submitted:

All of my homespun snippets utilize strtoupper (string $string) with any of the parameters which deal with operation modes.  Actual user input is left alone.  This insures the maximum compatibility with typos within the snippet call.
