### ISSUE TITLE
resourcelist not respecting parent across contexts

### ISSUE THREAD

**Issue by ghost** [modxbot/migrate#2581]
andy@andyshellam.eu created Redmine issue ID 2581

I've created a template variable with the type "resourcelist" and set a parent ID in the "input option values" field.

If I enter the parent ID of a resource that's in a different context, it lists all resources across the entire site (including those in other contexts.)

I believe it should just list the resources under the parent ID I've entered, regardless of which context it's in.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/7e320b88e3388293171541a503ed704e0c264311
