### ISSUE TITLE
TVs not assigned to a template still displayed

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#2583]
onepack created Redmine issue ID 2583

I have a case here where I have a template where TVs are "called" like this: [[*teaser1]]

Even though I didn't assign the TVs in the manager to this template (anymore) they are still displayed with their default values.

Maybe because I assigned them in the manager before, I don't know, but the case is they are no longer assigned to this template and still being displayed.

I know I can take away the code but I thought this would be worth pointing out.

**Comment by opengeek** [comment]
opengeek submitted:

This is a duplicate of #1852
