### ISSUE TITLE
File Manager tree, limiting access, previewing images

### ISSUE THREAD

**Issue by SebastienDaniel** [modxbot/migrate#2587]
Askarii created Redmine issue ID 2587

_The situation_
1. We have created a client website, to avoid the clint tampering with system files we limit the file-tree to "assets" only.
 we changed the following system settings:
@filemanager_path : assets/
filemanager_url : http://www.domainname.ca/assets/@
1. Once those changes have been applied, the file-tree works fine, we have access to "assets" only.

_The BUG_
When the previously mentioned filemanager settings have been changed, hovering over an image no-longer shows a preview, it simply shows a small white box with an error icon.

When we set the filemanager settings back to default, all was fine.

**Comment by splittingred** [comment]
splittingred submitted:

I assume your site's site_url is http://www.domainname.ca/

Set the filemanager_url to: assets/

**Comment by SebastienDaniel** [comment]
Askarii submitted:

Shaun McCormick wrote:

> I assume your site's site_url is http://www.domainname.ca/
> 
> Set the filemanager_url to: assets/

Its not a context, so we haven't modified "site_url", in fact I can't even find that in the system settings.
But everything else works fine, so we can suppose its http://www.domainname.ca/

By changing the filemanager_url to "assets/" only, the file-tree is not limited to assets, but the image previewing gets broken.

I also tried editing the "web context" by adding "site_url" as "http://www.csvg.ca/", but the same problem persists.

**Comment by splittingred** [comment]
splittingred submitted:

I'd recommend removing site_url as a System Setting. It's auto-generated by MODx.

What are _both_ your:
- filemanager_path
- filemanager_url

...settings set to?

**Comment by SebastienDaniel** [comment]
Askarii submitted:

Shaun McCormick wrote:

> I'd recommend removing site_url as a System Setting. It's auto-generated by MODx.
> 
> What are _both_ your:
> - filemanager_path DEFAULT ... _i.e. nothing, but we have also tried with the above mentioned: assets/_
> - filemanager_url DEFAULT ...  _i.e. nothing, but we have also tried with the above mentioned: http://www.domainname.ca/_
> 
> ...settings set to?

As for site_url we removed it after seeing that it didn't change anything, so its the MODx default now.

**Comment by splittingred** [comment]
splittingred submitted:

This has all been resolved in 2.0.5, through the filemanager_path_relative and filemanager_url_relative settings, and better context support in connectors.
