### ISSUE TITLE
MagpieRSS / Snoopy and WordPress datafeed error

### ISSUE THREAD

**Issue by pixelchutes** [modxbot/migrate#2589]
pixelchutes created Redmine issue ID 2589

Has anyone been able to have MagpieRSS shipped w/ MODx Revolution correctly parse a blog feed from a clean install of the latest WordPress (v.3.0.1)? getFeed (using core Magpie/Snoopy class) is functioning fine for other sample feeds, but I am running into magpie parse errors related to the latest WordPress feeds (v3+)

<pre>
(ERROR @ /modx/revolution/core/model/modx/xmlrss/rssfetch.class.php : 242) User warning: MagpieRSS: Failed to fetch http://localhost/modx/revolution/blog/?feed=rss2 (HTTP Response: HTTP/1.0 301 Moved Permanently)
</pre>

_MODx Forum Post w/ Solution:_ http://modxcms.com/forums/index.php/topic,51232.msg307230.html#msg307230 (more detail)
_getFeed Issue:_ http://github.com/splittingred/getFeed/issues#issue/6 (issue is actually related to core Snoopy class used with Revo 2.0.0-pl+)

I found a solution for this scenario (which has worked under multiple impacted environments), which is basically overriding the port (when == 80) just before the _httprequest() call in the fetch() method of "snoopy.class.php" (right before Line 156)

<pre>if( $this->port == 80 ) $this->port = '';</pre>

**Comment by wshawn** [comment]
wshawn submitted:

Why in the world is it checking the port?

http = 80
https = 443

The responding server itself will redirect.  I would think they would simply check the protocol, at the most.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/722ec4fa1f0c46b301e4b50f099b298d012ddcc0
