### ISSUE TITLE
Proposed cache setting per element to clear at specified time

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#2590]
wshawn created Redmine issue ID 2590

Currently, I have snippets which handle their own output based on the number of days from a given start date.  My Issue is with the associated chunks, which appear to reset every twenty-four hours from the creation date and time.

I was wondering on the feasibility of allowing caches to be cleared at a specific time, like midnight for a given element.

I understand I could simply run everything uncached, but with high usage sites (million visitors) it may prove handy to have this times cache ability.

**Comment by opengeek** [comment]
opengeek submitted:

You can use a Snippet like the getCache Snippet to wrap Elements with any cache provider you want, using any time to live (expiration time) you want.
