### ISSUE TITLE
Revo "cache" from uploadable file types

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#2592]
wshawn created Redmine issue ID 2592

Unless I am mistaken, cache should not be an uploadable file type.

Can this be corrected?

**Comment by wshawn** [comment]
wshawn submitted:

In the system settings....

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/d4c70977412bc906087beb8995c38c5aa44431ab
