### ISSUE TITLE
Property list attachment not showing elements

### ISSUE THREAD

**Issue by ghost** [modxbot/migrate#2593]
andy@andyshellam.eu created Redmine issue ID 2593

Since upgrading my Revo 2.0.3 install to 2.0.4-pl2, whenever I try to attach a property set to an element from the Tools > Property Sets screen, I cannot select an element.

To reproduce:

Right-click property set -> attach to element.
Select the element type (e.g. modChunk.)
Click second list, it expands for a second then disappears.  It looks as though it's loading elements, then not finding anything.

This worked fine in 2.0.3 in the same browser, and I can attach the property to an element if I start from the element, rather than the property sets screen.

**Comment by splittingred** [comment]
splittingred submitted:

Works fine for me. Can you ensure you have a modx_class_map table, and that it has records in it?

**Comment by ghost** [comment]
andy@andyshellam.eu submitted:

Hi Shaun,

Yes I have modx_class_map and it contains 9 rows of data.

It's the second list that's not displaying though - after you've selected the class (e.g. modChunk) you then select the element name from the second list - it's this second list that's not showing anything.

There's nothing in either the modx error log or the PHP error log.

Andy

**Comment by ghost** [comment]
andy@andyshellam.eu submitted:

As an update, I've run a trace on the requests while performing this action, and I'm getting the following response back when I expand the second list:

{"success":false,"message":"Permission denied!","total":0,"data":[],"object":[]}

What permissions are required to perform this action?

**Comment by splittingred** [comment]
splittingred submitted:

Do you have the 'class_map' Permission set in your Administrator policy? That will fix it.
