### ISSUE TITLE
Phone numbers block required characters

### ISSUE THREAD

**Issue by keiron77** [modxbot/migrate#2594]
keiron77 created Redmine issue ID 2594

When entering a phone/mobile/fax number characters a restricted that are required. The user should be able to include + and () (and spaces) when entering international number.

**Comment by keiron77** [comment]
keiron77 submitted:

I have realised the problem isn't with the special characters, but non-US numbers cause a problem until the + and () have been removed.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/89fcdaaf3a211db39af7a7f41b3eb3f5a6bf4f83
