### ISSUE TITLE
Context Settings - Field Types other then textfield, change to textfield after first update.

### ISSUE THREAD

**Issue by AESmith** [modxbot/migrate#2597]
aesmith created Redmine issue ID 2597

Go to "web" Context Settings.
Create site_status (or anything)
Field Type: Yes/No
Save

Creates properly.

Now go back into "web" Context Settings
Update "No" to "Yes"
Save

Now go back in "web" Content Settings (notice that "Yes" is no longer red)
Click to update from "Yes" to "No"
You are given a textfield.

Go look at DB table
Record now have a value of "Yes" not 1 and xtype is textfield.

I have gone through this several times. You can do the same thing with textarea and get the same results. Also click to update and "right click, Update change from overlay" end in the same failer.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/5e558d50c9ab807b90456d2dc249b038665c58c2
