### ISSUE TITLE
Output filter 'date' isn't working in Login snippets

### ISSUE THREAD

**Issue by bertoost** [modxbot/migrate#2606]
bertoost created Redmine issue ID 2606

A small bug; but the output filter 'date' isn't working..

I'm using the Login snippet and when I want to show the date-of-birth field, then I would like to use the 'date' output filter but [[+dob:date=`%A %e %B %Y`]] returns nothing. I did some prints inside the modoutputfilter.class.php and I see the $m_val isset as I would but $value = 0 + $output; stays '0' and then the if statemant will be false

I did not test it with other date fields

**Comment by splittingred** [comment]
splittingred submitted:

It works fine; you just need to do:

[[+dob:strtotime:date=`%A %e %B %Y`]]

since dob is stored as an integer.

**Comment by bertoost** [comment]
bertoost submitted:

It doesn't work for me. Did you test it?

**Comment by bertoost** [comment]
bertoost submitted:

It realy doesn't work for me.. even when I add an extended field with a timestamp and do [[+myfield:strtotime:date=`%A %e %B %Y`]] it doesn't work, prints nothing... while [[+myfield]] prints the timestamp correctly.. [[+myfield:strtotime]] is already does nothing; so I don't know what I'm doing wrong but it doesn't work for me!
