### ISSUE TITLE
Remove filter_commands and filter_modifiers from scriptProperties

### ISSUE THREAD

**Issue by opengeek** [modxbot/migrate#2609]
opengeek created Redmine issue ID 2609

Because filter_commands and filter_modifiers are set as properties, they are passed to Snippets when executed in the scriptProperties array. In order to then pass the properties into other Elements programmatically, these filter properties are passed into the unsuspecting Element you are calling and the filters are executed again when it is processed.

To work around this, you can manually remove the filter_commands and filter_modifiers from a copy of the scriptProperties you are passing to another Element, but this should not be happening.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/5f9047afe20d3ffe97aa360f6e0fb959a609a62a
