### ISSUE TITLE
Category policy inconsistant

### ISSUE THREAD

**Issue by jamestan** [modxbot/migrate#2610]
jamestan created Redmine issue ID 2610
- Add a category "xyz".
- Assign policy to user group: administrator:
  category: xyz
  min-role: Member
  access policy: administrator
  context: mgr
## Now i will be able to see the category after flush permission. If cant, please logout and login again.

Right click on category "xyz" and create new chunk
## key in a random name, and save: "Access denied"

Right click on "Chunk" (no category) and create new chunk.
Do not choose any category, and save: "OK".
## Edit the chunk, choose category "xyz", and save. "OK"

This above part is okay when we edit the chunk and set the category.
I'm not sure if this is the correct way to configure, but i assumed that im suppose to be able to save new chunk of category "xyz" with the above access policy set.
Listing and viewing okay.

**Comment by mkschell** [comment]
netprophet submitted:

Fixed in https://github.com/modxcms/revolution/commit/011ea69ad627b1f9ae48fecac47d61fccb8d1df1

add_children permission has been added to Element Policy and Policy Template

To test, follow instructions in ticket above.
