### ISSUE TITLE
[Template Variable] Cannot toggle between radio options

### ISSUE THREAD

**Issue by zaigham** [modxbot/migrate#2611]
zaigham created Redmine issue ID 2611

MODx Revolution 2.0.4-pl2

I am unable to select between radio values. eg. clicking on radio options doesn't work.

Tested in Firefox, Chrome, IE, Safari.

Quick demo http://screencast.com/t/rwJNDzW9i

**Comment by splittingred** [comment]
splittingred submitted:

I have no problems toggling. What is your:
- Default Value
- Input Option Values

**Comment by zaigham** [comment]
zaigham submitted:

Input Options: Include==0||Exclude==1
Default: 0

**Comment by splittingred** [comment]
splittingred submitted:

Was an ExtJS bug with values of "0". Added workaround that fixes it here: https://github.com/modxcms/revolution/commit/19489bd88c9231da05abb244cf130da9146eb437

**Comment by Crunch** [comment]
crunch submitted:

I am still observing the same behaviour in Revo 2.0.8pl
Have created a radio option tv with values: @show==1||hide==0@
If I change the 0 value to 2, the tv then works as expected.

Tested in Firefox 3.6.14, Safari 5.0.3 (both on Mac OSX 10.6.6)
