### ISSUE TITLE
Increase user comment capacity

### ISSUE THREAD

**Issue by keiron77** [modxbot/migrate#2614]
keiron77 created Redmine issue ID 2614

The user comments field limited to 255 characters is too restrictive. 

I suggest turning in from varchar(255) into text for potentially unlimited volume. The website owner can limit the length field using front-end/php scripts if he/she so wishes.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/b4e92414320d2cecbb666ba7a9a1f8de1326ee95
