### ISSUE TITLE
 error 'D is null' increments on each saving

### ISSUE THREAD

**Issue by bruno** [modxbot/migrate#2630]
bruno created Redmine issue ID 2630

I get error 'D is null' on all manager-pages after saving the form multiple times.

With each saving this function, which returns that error, is called one more times.

In modx.component.js I found this function is called one times more with each saving:

o.form.on('success',function(r)

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/ea98936a1a2c51fa54fc33a29aeabb8d9624a009
