### ISSUE TITLE
TVs disappear when moving their parent category

### ISSUE THREAD

**Issue by dae** [modxbot/migrate#2631]
dae created Redmine issue ID 2631

Imagine the following in "Elements" browser/tab:

<pre>
Categories
    |- Category A
    |- Category B
        |- Some TV 1
        |- Some TV 2
        |- Some TV 3
</pre>

If you drag-n-drop Category B into Category A (thus making Category A the parent of Category B) and refresh the tree, you will lose all the TVs of Category B.

They will exist in database (see the screenshot) but will not be reachable through the interface.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/2cfe6faf94ecdc8d4a8509c904ae867e3db83414
