### ISSUE TITLE
Resource not in tree after create

### ISSUE THREAD

**Issue by eerne** [modxbot/migrate#2634]
eerne created Redmine issue ID 2634
- click create new Document button
- specify a parent, that is in a different context (not web context)
- add pagetitle and save

The newly created document does neither show up in the resource tree nor in recent documents.

Only way I can find the document is by pagetitle in Site / Search.

Also is there any way to find such lost documents?

**Comment by opengeek** [comment]
opengeek submitted:

Seems to not be setting the context_key of the Resource based on the selected parent.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/79d6687a2f76e3b3e1e8e4922e7d45ca86828b6f
