### ISSUE TITLE
Cannot change labelWidth in MODx.window

### ISSUE THREAD

**Issue by skndn60** [modxbot/migrate#2635]
skndn60 created Redmine issue ID 2635

The labelWidth property of MODx.window cannot be changed as it is hard coded to 100 pixels in the createForm method:

<pre>
    createForm: function(config) {
        config = config || {};
        Ext.applyIf(config,{
            labelAlign: 'right'
            ,labelWidth: 100
            ,frame: true
            ,border: false
            ,bodyBorder: false
            ,autoHeight: true
            ,errorReader: MODx.util.JSONReader
            ,url: this.config.url
            ,baseParams: this.config.baseParams || {}
            ,fileUpload: this.config.fileUpload || false
        });
        return new Ext.FormPanel(config);
</pre>

It can be easily fixed (I think) by implementing this method as: 

<pre>
    createForm: function(config) {
        config = config || {};
        Ext.applyIf(config,{
            labelAlign: 'right'
            ,labelWidth: this.labelWidth
            ,frame: true
            ,border: false
            ,bodyBorder: false
            ,autoHeight: true
            ,errorReader: MODx.util.JSONReader
            ,url: this.config.url
            ,baseParams: this.config.baseParams || {}
            ,fileUpload: this.config.fileUpload || false
        });
        return new Ext.FormPanel(config);
</pre>

**Comment by splittingred** [comment]
splittingred submitted:

You sure? My createForm looks like this:

<pre>
    ,createForm: function(config) {
        config = config || {};
        Ext.applyIf(config,{
            labelAlign: this.config.labelAlign || 'right'
            ,labelWidth: this.config.labelWidth || 100
            ,frame: this.config.formFrame || true
            ,border: false
            ,bodyBorder: false
            ,autoHeight: true
            ,errorReader: MODx.util.JSONReader
            ,url: this.config.url
            ,baseParams: this.config.baseParams || {}
            ,fileUpload: this.config.fileUpload || false
        });
        return new Ext.FormPanel(config);
    }
</pre>

Are you sure your files were all updated when you upgraded?

**Comment by skndn60** [comment]
skndn60 submitted:

I'm on Revo 2.0.0 as stated in my environment. Was this fixed in one of the minor releases since 2.0.0?

**Comment by splittingred** [comment]
splittingred submitted:

Yes. You need to upgrade to 2.0.4-pl2.
