### ISSUE TITLE
When changing the category, element appears twice

### ISSUE THREAD

**Issue by dae** [modxbot/migrate#2638]
dae created Redmine issue ID 2638

Imagine the following in "Elements" browser/tab:

<pre>
Template Variables
    |- Category A
        |- Category B
        |- templateVariable 1
</pre>

If you change the parent category of _templateVariable 1_ to _Category B_ and press "Save", _templateVariable 1_ will appear twice: in the old place and in the new place. However if you refresh the page, it'd appear where it's supposed to be in the new place. Obviously it is some sort of an UI/JavaScript bug.

**Comment by garryn** [comment]
garryn submitted:

Fixed.

https://github.com/modxcms/revolution/commit/5ec551edd126734d8b221195c57669ef93762502
