### ISSUE TITLE
Rule disappears from Form Customization but not from the database

### ISSUE THREAD

**Issue by dae** [modxbot/migrate#2639]
dae created Redmine issue ID 2639

Steps to reproduce:
# Go to "Form Customization".
# Click "Add", create a new rule, save.
# Edit the newly created rule: change "Action" to "No action", click Save.

What happens: the rule disappears from the list, but you can still see it in the database (table _modx_actiondom_).

**Comment by splittingred** [comment]
splittingred submitted:

Not really a bug with displaying; user shouldn't ever be able to specify a FC rule with Action of "none".

Fixed in http://github.com/modxcms/revolution/commit/92a66dc7d312690c911d9577a8a0827cb02612e9
