### ISSUE TITLE
Right-click-create-document doesn't use default_template

### ISSUE THREAD

**Issue by eerne** [modxbot/migrate#2640]
eerne created Redmine issue ID 2640

Right-click create document doesn't use default_template system setting.

It works fine for the button "New Document" as well as in the menu under Site / New Document, but not for right-click-create.

**Comment by splittingred** [comment]
splittingred submitted:

Works 100% fine for me. You sure it's not working? Is this in the web context or another ctx?

**Comment by eerne** [comment]
eerne submitted:

Sorry that I wasn't more specific. Right-click on web context then create resource takes the default_template, but right-click on a container (in web context) does _not_ take the default_template. In my case it takes the one with id 1.

**Comment by splittingred** [comment]
splittingred submitted:

Hrm, I can't reproduce this at all. Mine always takes the default_template. Might have been fixed in 2.0.5.
