### ISSUE TITLE
Canceling the warning still resets the template setting

### ISSUE THREAD

**Issue by dae** [modxbot/migrate#2641]
dae created Redmine issue ID 2641

Steps to reproduce (assuming you have at least two templates):
# Click a document to open it in editing mode.
# Find "Uses Template" dropdown, choose a new template.
# There will be a warning "Are you sure you want to change this template?", press "No".

The "Uses Template" setting will now change to _(empty)_, while it was supposed to remain unchanged.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/4221a05d1d570606fe1b9f6a617bc6141e64e618
