### ISSUE TITLE
Removing Context Access Web

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#2646]
onepack created Redmine issue ID 2646

I was playing around with the system and removed the WEB Context Access for the manager....

This was not a good idea :-( because after this the whole Context disappeared from the available contexts in the list when I tried to add the Context again. 
It's just no longer available in the context Access list and it's also gone in the Context page. I tried to add the Context again in the Contexts Page but this results in a error: "An error occurred while creating the context". (still exists of course but cannot see it)

Logging in with a general user shows the context still exists and is available to them.. It's just gone for the Admin.. 

How to get it back?

**Comment by onepack** [comment]
onepack submitted:

I managed to get it back by making another user Admin and assigning the Web Context to me as an Admin...

When you are the admin.. why does a context disappear from all the views, contexts included, when you decide not to have it in the access policy...  The site admin should always be able to restore this themselves.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/97ba1a759ca5a95eda98e96eddf6581f86ebef82
