### ISSUE TITLE
Erroneous drag-n-drop in the Elements pane

### ISSUE THREAD

**Issue by dae** [modxbot/migrate#2652]
dae created Redmine issue ID 2652

You can drag-n-drop an Element (such as a Template) onto another Element so they will form a hierarchy (until you reload the page in browser). Please see the screenshot.

This option is unsupported in the engine, thus I believe drag-n-drop of Elements onto the other Elements should not be allowed.

**Comment by splittingred** [comment]
splittingred submitted:

Awaiting integration: https://github.com/modxcms/revolution/pull/108
