### ISSUE TITLE
Session timeout leads to "save until death"

### ISSUE THREAD

**Issue by mindeffects** [modxbot/migrate#2655]
mindeffects created Redmine issue ID 2655

When working a long time in Revolution it happens, that the session is no longer valid. And then, when hitting "save", Revo hangs in the save loop like forever.

Logout and login helps, but it would be nicer if the login screen would automaticaly be displayed and after a successful login the edited content would then be saved.

best
Oliver

**Comment by vhollo** [comment]
vhollo submitted:

In 2.0.4-pl2 I've seen this issue solved (login screen showed up on saving a resource), but
1) it didn't take me back to the right workflow,
2) a manager session should have been renewed on every valid action, so logging out could olny happen on idle.

**Comment by splittingred** [comment]
splittingred submitted:

Pushing this back further, this will require major work to get all AJAX requests to monitor session loss.

**Comment by opengeek** [comment]
opengeek submitted:

See https://github.com/modxcms/revolution/commit/8ca90fc5ae03a47bb4dec26b0f402e87976db6b4 for a resolution to this issue.
