### ISSUE TITLE
Save/Preview/Duplicate-Buttons overlap resource tabs

### ISSUE THREAD

**Issue by gerritvanaaken** [modxbot/migrate#2659]
gerritvanaaken created Redmine issue ID 2659

On Safari 5 / Mac, the action buttons collide/overlap width the resource tabs, see screenshot!

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/77544190e163001c0a475e823a22fe3271332826
