### ISSUE TITLE
PNG images with trancparency look damaged and unclear in Resource Backend

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#2662]
onepack created Redmine issue ID 2662

When I Upload an .png with transparency they look black and damaged in the image overview and also when I assign them to an image TV.

**Comment by onepack** [comment]
onepack submitted:

See screenshot

**Comment by MarkH** [comment]
markh submitted:

This looks fixed in 2.2.7-dev

**Comment by MokoJumbie** [comment]
MokoJumbie submitted:

I guess I filed a dupe of this at #9149 but also suggested that the thumbs be saved in the same format as the original image. Mark, do you know if this is the case now?

**Comment by onepack** [comment]
4,5 Years later. Closed!
Please create a new case if someone still thinks this is valid.
