### ISSUE TITLE
Access permission for Templates

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#2669]
onepack created Redmine issue ID 2669

Although I always try to keep the number of Templates for the user to a bare minimum I still end up with two or more templates that I need but that the other "editors" should not see.

For instance the Maintenance Template. I don't want the "Editors" to see this template.

So my suggestion is to add the "Access Permission" feature for templates too so I can hide them from the view for others than Administrators.
(The same functionality as with TVs)

**Comment by splittingred** [comment]
splittingred submitted:

This can be done via Element Category ACLs.
