### ISSUE TITLE
Naming convention TV input type "Text"

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#2670]
onepack created Redmine issue ID 2670

The current Naming convention for the text field is very confusing.

Currently we have: 

1 Richtext
2 Text
3 Textarea
4 Textarea (mini)
5 textbox

Why not something like:

Text - One line
Text - Small Box
Text - Box
Text - Richtext Box

I left out "textbox". The difference between "Text" and "textbox" is unclear for me because apparently in the backend and in the frontend they render the same.

Small Box and Box could be merged to be just Box because I noticed the box adjusts the size to the content. Just make it Box (Textarea Mini).

Well.. you get the idea I hope :-)

**Comment by MarkH** [comment]
markh submitted:

As of I think 2.1 we have:
- text
- textarea
- richtext

That seems to fix this issue doesn't it?

**Comment by onepack** [comment]
5 Years later. Closed!
Please create a new case if someone still thinks this is valid.
