### ISSUE TITLE
[REVO-2.0.4-pl2] Extended Fields seems not to work

### ISSUE THREAD

**Issue by phron** [modxbot/migrate#2673]
anso created Redmine issue ID 2673

I'm trying to create new users with extented fields, I'm trying with something very trivial and easy... BUT the extented fields seems buggy.

h3. In the tab "Extended Field"

1) _Add Container_ : I cannot save, I have the following error message :

c is undefined
http://localhost/Master/manager/assets/modext/widgets/core/modx.orm.js?v=204pl2
Line 247

2) _Add Attribute_ : same problem, same error message :

3) Try directly _fill in the two fields_ on right hand (with Name:'Color' and Value:'Blue') I get the following error message (the line with the error has changed from _247_ to _303_)

n is null
http://localhost/Master/manager/assets/modext/widgets/core/modx.orm.js?v=204pl2
Line 303

Did I miss something or do something wrong ?
Thanks and cheers

Configuration :
Windows7
Wamp 2.0.i
PHP 5.3.1
Apache 2.2.14
MySQL 5.1.41
MySQLClient mysqlnd 5.0.5-dev - 081106 - $Revision: 289630 $ 
All privileges and grant on the DB... 

Revo 2.0.4-pl2

Reported in forum too : #msg324107

**Comment by phron** [comment]
anso submitted:

EDIT : Sorry for this one (not the right place) I put the bug in the right section now... You can delete this one. Thanks

**Comment by splittingred** [comment]
splittingred submitted:

This was fixed in https://github.com/modxcms/revolution/commit/5870bd52a4d0e75b3ebf3d549c04024f86bcc62a
