### ISSUE TITLE
Control alias settings at resource level

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#2684]
gadamiak created Redmine issue ID 2684

For some resources it's necessary to use different settings for aliases, namely:
- Automatic alias generation (<code>automatic_alias</code>). It should be possible to prevent automatic alias generation at resource level, which would often apply to site start resource.
- Using alias path (<code>use_alias_path</code>). It would be useful to be able to enable/disable using alias path at resource level.

**Comment by opengeek** [comment]
opengeek submitted:

This is resolved by the new freeze URI feature in 2.1
