### ISSUE TITLE
Add another template group for policies

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2689]
bobray created Redmine issue ID 2689

It might make sense to have three groups rather than two: Administrator, Resource Object, and Element Object

**Comment by splittingred** [comment]
splittingred submitted:

Done in https://github.com/modxcms/revolution/commit/b7143d039f64eec5022c2be5377a0aeb9fef22db

Rebuild/upgrade required.

Decided to just add Element/Resource policy templates, and leave the Object one. This will be more flexible. Enhanced the policy getlist processors to be able to accept multiple groups as filters; this allows a Policy combo to grab Policies of both Object and, say, Element templates. Much more flexible.
