### ISSUE TITLE
Change "Administrator" to "Admin" in policy group names.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2690]
bobray created Redmine issue ID 2690

I think "Admin" is a better name for it than "Administrator" since it's more of an administration type than an administrator type -- that makes a better parallel to Object. It also downgrades the importance, which I think is appropriate and it avoids the possible confusion with the standard "Administrator" policy and the "Administrator" user group.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/d2bdb79d0ef9db80b1d7264cda1f4e36f2e404b1
