### ISSUE TITLE
Duplicate Alias issue

### ISSUE THREAD

**Issue by jcamachott** [modxbot/migrate#2691]
john@pixelstation.com created Redmine issue ID 2691

Before turning on Use Friendly Aliases, I had already created a Container 1 with these documents

Gallery
Features
Specifications

I duplicated the container and now got Container 2 (after renaming it) and

Duplicate of Gallery
Duplicate of Features
Duplicate of Specifications

Aliases were not automatically created before so I turned that on and also Use Friendly Aliases.

Now when I went back into the first Gallery document, I resaved it and it created the 'gallery' alias, however, going to the Duplicate of Gallery, when I renamed it back to 'Gallery' (since that is how i want it as its in another container), it created the _same_ alias 'gallery'. This shouldnt be since allow_duplicate_aliases is off by default, and in fact if I manually change the alias and try to change it back to 'gallery' I get an error.

Shouldnt the system, on autocreating a new alias (where there was none before), check to make sure its not being used? If I rename the other documents, removing the 'Duplicate of', the aliases are created the same way and I'm left with duplicate aliases in the system.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/1bd24cd367f11104c3a42c43f17a37ac669e7cd7

Will require rebuild/upgrade if using from Git.
