### ISSUE TITLE
Add the word "Template" to the end of each standard Policy Template name

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2695]
bobray created Redmine issue ID 2695

If the template names ended in Template (e.g., AdministratorTemplate, ObjectTemplate) it would help prevent people from editing a template when they mean to be editing a policy and vice versa (and we have enough different things called 'Administrator' already).

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/875c5499adb82cb8611f42fff1a90cbfafcccd69
