### ISSUE TITLE
Changed Policy Template name reverts on save

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2700]
bobray created Redmine issue ID 2700

If you duplicate a Policy Template, then edit it to change the name, the name in the form reverts to the old name on Save.

This is cosmetic, the actual name is changed, but it appears that it hasn't.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/25687630bb7a56a30fddbf1038ac0e6c1697c6cd
