### ISSUE TITLE
Custom permission description does not appear until reload

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2701]
bobray created Redmine issue ID 2701

If you add a custom permission to a Policy Template, the new permission appears at the bottom of the list, but without its description.

This is cosmetic, if you reload the page after saving the template, the description appears.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/ac080e06db65e9a2100b9f5265465f63930a38c1
