### ISSUE TITLE
make "getResourcesTag@NewsList?tag=`bla`" snippetcall possible

### ISSUE THREAD

**Issue by gavro** [modxbot/migrate#2703]
gavro created Redmine issue ID 2703

See forumthread: http://modxcms.com/forums/index.php/topic,56107.0.html

Perhaps it might be handy to make a custom snippet call with an extra 'tagRequestParam' possible, which is still overruled by http://URL?tag=`othertag`.

Additional code could something like just an extra else-if-statement:
else if(!empty($$tagRequestParam)){
    $scriptProperties['tvFilters'] = $tagKey.'==%'.$modx->stripTags($$tagRequestParam).'%';
}

**Comment by splittingred** [comment]
splittingred submitted:

If this is for tagLister, it should be filed here:

http://github.com/splittingred/tagLister/issues/
