### ISSUE TITLE
Search allows any user access to restricted documents

### ISSUE THREAD

**Issue by lexiconlondon** [modxbot/migrate#2708]
jimbob72 created Redmine issue ID 2708

The search facility (through the main Site menu option) allows any user, regardless of access group or user profile, to access any document in the resource tree. This should be close so that search is restricted to only those documents that are available to that user.

**Comment by splittingred** [comment]
splittingred submitted:

I cannot replicate this at all; in fact, I just hid a Resource in a Resource Group protected by an ACL and was not able to find it.

If you're still having issues, please post all the exact steps you took to get to this issue.

**Comment by lexiconlondon** [comment]
jimbob72 submitted:

Thanks. The issue I have is with a child resource in a container that is protected by an ACL. The container is defined as being part of a restricted Resource Group but the children are not.

The container is not visible, nor any of its children in the Resource tree. However, the Search facility shows up the children. Do I have to manually allocate each child to the Resource group also?

**Comment by splittingred** [comment]
splittingred submitted:

Yes.
