### ISSUE TITLE
Object policies not available for Resource Group Access ACLs

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2709]
bobray created Redmine issue ID 2709

When creating Resource Group Access ACL entries, only the Resource-based policies are available on the drop-down list. You can't easily give anonymous users, for example, load or load, list, and view policies for the web context.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/b7143d039f64eec5022c2be5377a0aeb9fef22db

Rebuild/upgrade required.
