### ISSUE TITLE
Unauthorized pages no longer redirect to unauthorized page in some browsers.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2710]
bobray created Redmine issue ID 2710

When accessing protected pages in the front end, anonymous users with load; or load, list, and view permissions for those pages see a blank screen in Chrome, in IE7 they get a 404 error. In FF, they get the unauthorized page.

**Comment by opengeek** [comment]
opengeek submitted:

I cannot reproduce this in the latest develop branch. Any other details? It is possible it has been fixed since 2.0.4-pl via another bug/fix.

**Comment by opengeek** [comment]
opengeek submitted:

Resolving since no feedback in 5 days.
