### ISSUE TITLE
makeUrl problems

### ISSUE THREAD

**Issue by dmitriy-karpov** [modxbot/migrate#2714]
dmitriy-karpov created Redmine issue ID 2714

makeUrl doesn't work with just created recourse. Here is code:

```
      $broadcast = $modx->newObject('modResource');
      $broadcast->set('pagetitle',$_REQUEST['broadcast_name']);
      $broadcast->set('description',$_REQUEST['broadcast_description']);    
      $broadcast->set('published',1);
      $broadcast->set('template',2);    
      $broadcast->set('searchable',1);    
      $broadcast->set('cacheable',1);    
      $broadcast->set('createdby',$modx->user->get('id'));
      $broadcast->set('publichedby',$modx->user->get('id'));
      $broadcast->set('parent',2);    

   if($broadcast->save()===true){
         $id=$broadcast->get('id');
         $url = $modx->makeUrl($id,'','','full');
         echo $url." ".$id;
   }
```

$id has right value, but $url is empty. Also I've tried this way: $url=$modx->makeUrl((int)$id,'','','full'); but result is the same.

**Comment by splittingred** [comment]
splittingred submitted:

You'll most likely need to clear the cache before running makeUrl. Try:

<pre>
$modx->executeProcessor(array(
   'location' => 'system',
   'action' => 'clearCache',
));
</pre>

**Comment by dmitriy-karpov** [comment]
dmitriy-karpov submitted:

I've tried this. But there is no changes.
