### ISSUE TITLE
Selecting Default on Auto-Tag does not reset tags in Auto-Tag list to match

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#2719]
wshawn created Redmine issue ID 2719

Selecting the Default option to the left of the TV Name does not also update the list of Auto-tags presented on the screen.

Expected:
The default values should be highlighted and non-defaulted (previously existing) tags should now be underlined

Actual:
Nothing changes in the Auto-tags-- only in the input field itself.

Page is also not set "dirty" and no warning is given upon leaving it.

**Comment by splittingred** [comment]
splittingred submitted:

Awaiting integration: https://github.com/modxcms/revolution/pull/110
