### ISSUE TITLE
Package retriever navigation

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#2721]
onepack created Redmine issue ID 2721

When using the Package Management window I get errors when using the navigation in a result window.

Adding a custom number to display the extras overview results in a broken navigation.

When I chose to change the results number to be displayed nothing happens until I press the "next Page" link..
I then end up in page 101 and the 3th page is even 10101..
Next to that the pages don't respect the number that I entered.. If I enter 30 nothing happens.. only the navigation ends up broken.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/d8e7a35a841eb783a5468a684bd5c66b28c2ec33
