### ISSUE TITLE
If Date TV "If no value, use current date" have time set to 00:00:00 by default

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#2722]
wshawn created Redmine issue ID 2722

When entering the data into a Date TV for the first time and the manager user clicks out of the Calender for setting date the current time is automatically populated with the current time even when "If no value, use current date" is set to "No"

Can this field be left empty (preferred) or set to midnight by default when the user clicks out of the calendar?

**Comment by splittingred** [comment]
splittingred submitted:

This must have been fixed prior, I can't seem to replicate it.
