### ISSUE TITLE
Possible glitch in multi-select listbox

### ISSUE THREAD

**Issue by lkossis** [modxbot/migrate#2728]
lkossis created Redmine issue ID 2728

I created a multi-select listbox TV in Revo 2.0.4.pl2 and one of the values was `12" vinyl`
Output was set to delimiter: `,`

That didn't save well, only the value(s) selected upto the `12" vinyl`entry appeared as being selected when getting back to the page.

After removing the quote from the list item everything worked well.

**Comment by splittingred** [comment]
splittingred submitted:

I can't reproduce this at all; can you post _exactly_ how your TV was created? (all values)

**Comment by lkossis** [comment]
lkossis submitted:

Listbox multiselect TV with values: CD||CD Single||DVD||Vinyl - Maxi Single||12-inch Vinyl LP - Select CD, DVD and 12-inch Vinyl LP, save resource, refresh resource, everything OK
Listbox multiselect TV with values: CD||CD Single||DVD||Vinyl - Maxi Single||12"-inch Vinyl LP - Select CD, DVD and 12"-inch Vinyl LP, save resource, refresh resource, CD, DVD are selected, 12"-inch Vinyl LP is not.

PLease let me know if you still can't reproduce - I'll let you into my manager

**Comment by splittingred** [comment]
splittingred submitted:

This must be fixed in a prior commit; cannot reproduce using 2.0.5-dev from Git.
