### ISSUE TITLE
You do not have permission to create a Resource in this location

### ISSUE THREAD

**Issue by u007** [modxbot/migrate#2734]
u007 created Redmine issue ID 2734

I'm not sure if this is a bug, but i find it a bit misleading...

Create a user group #A.
Assign resource group "My doc" to user group #A.
Create a document "Test Me", assign resource group access permission to "My doc".
Edit user group > resource group access:
Assign: resource group: "My doc", min role: "Member", Access policies: "Administrator", Context: "mgr"

Login as User with group "group #A".
Edit the resource "Test Me", Okay.
Right click and add child resource on "Test Me" , Get Error:
 "You do not have permission to create a Resource in this location"

But , work around is to add another resource group access:
Resource group: "My Doc", min role: "Member", Access policies: "Resource", Context: "mgr"

The question is, why do we need this additional policy when we already assign administrator?
Maybe im missing some concept here, please advice me :)

Thanks

**Comment by wshawn** [comment]
wshawn submitted:

Make sure the current user is actually a member of the group in question.  It is possible to create a group and not actually have assigned the site admin.

**Comment by u007** [comment]
u007 submitted:

yes, ive the user assigned to that user group required.
mm if you read carefully my notes.. its not about that...

**Comment by opengeek** [comment]
opengeek submitted:

First, Administrator policy is for Contexts, not Resource Groups, that's what Resource policies are for; they define important Resource-specific permissions like add_children, which is probably what you are missing and why you can't add children. ;)

**Comment by u007** [comment]
u007 submitted:

i see :)
thanks a lot :)
