### ISSUE TITLE
Menu permission also effecting actual action executed?

### ISSUE THREAD

**Issue by u007** [modxbot/migrate#2735]
u007 created Redmine issue ID 2735

Hi,

The Top Menu permission works fine by hiding menu from users.
But if the user knows the url, the user can still access the components / action.
Is it possible to check permission of the executed components from Top menu permission setting as well?
This way, we could also do custom permission configuration to totally limit access to the action.

thanks :)

**Comment by splittingred** [comment]
splittingred submitted:

Fixed (along with another issue) here: https://github.com/modxcms/revolution/commit/5b115539d3d772cbbe40a18c51bc142d4961f579
