### ISSUE TITLE
auto alias with :

### ISSUE THREAD

**Issue by u007** [modxbot/migrate#2736]
u007 created Redmine issue ID 2736

Hi,

i realise the auto alias could populate invalid charactor like ":"
is it possible to filter it out when auto creating alias?

thanks :)

**Comment by wshawn** [comment]
wshawn submitted:

you could use the replace filter on the output

**Comment by onepack** [comment]
onepack submitted:

Maybe the "FURL Alias Character Restriction Pattern" on the 2nd page of system settings needs to get ":" added in the default value.

from: /[\0\x0B\t\n\r\f\a&=+%#<>"~`@\?[]{}|^'\]/

to: /[\0\x0B\t\n\r\f\a&=+%#<>"~:`@\?[]{}|^'\]/

Or just add it yourself now to instantly fix this issue for you.

**Comment by mkschell** [comment]
netprophet submitted:

Committed https://github.com/modxcms/revolution/commit/6e5acaf23cb26659058b7dde638d3d33c1d84007
