### ISSUE TITLE
Sample Site removal Issues

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#2739]
onepack created Redmine issue ID 2739

Upon deleting the Sample Site I noticed the Site Name not being displayed in the Templates anymore.
Checking the site settings for this value made me end up with the conclusion that the fields are gone in the system settings.

Checking the former "Sample Site" with a "heathy" Revo site shows that at least the next values are missing:

Error Page
Site Name.

I didn't check all the values on all the 5 pages but this definitely needs to be checked.

See my other related Bug related to Removing the Sample Site here: http://bugs.modx.com/issues/2732

**Comment by onepack** [comment]
onepack submitted:

I reinstalled revo 2.0.4-pl2 and the values that went missing in the system settings now returned but with the default values which means the old settings got their values deleted in the database as well. (sometimes TV's keep the values in the database even though the actual TV got removed)

**Comment by splittingred** [comment]
splittingred submitted:

Please file Sample Site bugs in http://github.com/splittingred/MODxSampleSite/issues/

**Comment by onepack** [comment]
onepack submitted:

Hi Shaun, sorry my fault that I created this bug here... but still I have one question before closing this bug.

I think a 3th party plugins or whatever should never be able to completely delete system settings.

I hope you agree with me and maybe reopen this case.
