### ISSUE TITLE
plugin/duplicate references obsolete evtid field

### ISSUE THREAD

**Issue by martinf55** [modxbot/migrate#2742]
martinf55 created Redmine issue ID 2742

The Plugin duplicate processor still references the old "evtid" field which was replaced by "event".
This change fixes the issue in 2.0.4-pl:

index 913779c..28893b4 100644
@@ -51 +51 @@ if (is_array($events) && !empty($events)) {
-        $newEvent->set('evtid',$event->get('evtid'));
-        $newEvent->set('event',$event->get('event'));

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/387bac2fc6fd56b390fc39e36ec88745f9045acf
