### ISSUE TITLE
makeUrl() fails on newly created resource

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2745]
bobray created Redmine issue ID 2745

After getting the ID of a newly created resource, makeUrl($id) returns nothing. The ID is correct. Every once in a while it works but it's not a timing issue.

To reproduce:

<?php
$resource = $modx->newObject('modResource',array('pagetitle'=>'testing','published'=>'1'));
$resource->setContent('Some Content');
$resource->save();
// sleep(5);  // makes no difference
$postid = $resource->get('id');

// redirect to post id
$goToUrl = $modx->makeUrl($postid);

if (empty($goToUrl)) {
   die ('Postid: ' . $postid . '<br />goToUrl: ' . $goToUrl);
}
$modx->sendRedirect($goToUrl);

**Comment by opengeek** [comment]
opengeek submitted:

This has never worked and will not unless you manually clear the cache as part of your process. The newly created Resource will not be available in the context until the context cache is rewritten.
