### ISSUE TITLE
Email vs username in user registration email

### ISSUE THREAD

**Issue by jobatkin** [modxbot/migrate#2746]
jobatkin created Redmine issue ID 2746

Originally raised in the forum at http://modxcms.com/forums/index.php/topic,56599.0.html.

Basically the issue is that the user welcome email fills the value of the +uri parameter with the users email, which is not always the same as their username, and can prevent them from logging in correctly.

**Comment by splittingred** [comment]
splittingred submitted:

The code shows: 

<pre>'uid' => $user->get('username'),</pre>

So I'm not sure how it's sending anything but the username here. I cannot replicate your issue - creating a new user and sending the email sent it with my username, not the email.

**Comment by jobatkin** [comment]
jobatkin submitted:

I still get the problem consistently, with new users, old users, MODx passwords, custom passwords, etc. Not sure what the difference is. I'm trying to look through code to see if I can spot something but I can't even find the point where it sets the uid parameter - can you point me in the right direction please?

**Comment by splittingred** [comment]
splittingred submitted:

core/model/modx/processors/security/user/create.php (or update.php for existing users).

**Comment by gavro** [comment]
gavro submitted:

Hm, create.php is correct here; core/model/modx/processors/security/user/create.php:

<pre>
    $placeholders = array(
        'uid' => $user->get('username'),
        'pwd' => $newPassword,
        'ufn' => $user->profile->get('fullname'),
        'sname' => $modx->getOption('site_name'),
        'saddr' => $modx->getOption('emailsender'),
        'semail' => $modx->getOption('emailsender'),
        'surl' => $modx->getOption('url_scheme') . $modx->getOption('http_host') . $modx->getOption('manager_url'),
    );
</pre>

Update.php has an error on the other hand, 

<pre>
    $placeholders = array(
        'uid' => $user->profile->get('email'),
        'pwd' => $newPassword,
        'ufn' => $user->profile->get('fullname'),
        'sname' => $modx->getOption('site_name'),
        'saddr' => $modx->getOption('emailsender'),
        'semail' => $modx->getOption('emailsender'),
        'surl' => $modx->getOption('url_scheme') . $modx->getOption('http_host') . $modx->getOption('manager_url'),
    );
</pre>

See SVN, it's still faulty here: http://bugs.modx.com/projects/revo/repository/revisions/master/entry/core/model/modx/processors/security/user/update.php

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/1009fde3db9c833446e9ecaecfd590c893fde4a8
