### ISSUE TITLE
Improve parser performance with recursive regex

### ISSUE THREAD

**Issue by rickj** [modxbot/migrate#2763]
rickj created Redmine issue ID 2763

Since the recursive parser is invoked on every page, it's important to optimize its performance.

A recursive regular expression may replace current methods for extracting revo tags with significant performance increases. The regex I'm proposing is this:

<pre>
/\[\[(?>[^\[\[\]\]]]+|(?R))*\]\]/
// in code looks like this:
$prefix = preg_quote('[[');
$suffix = preg_quote(']]');
$regex = '/' . $prefix . '(?>[^' . $prefix . $suffix . ']+|(?R))*' . $suffix . '/';
</pre>

This regex can be used in 2 places:
1) in place of the second call to processElementTags() in modResponse::outputContent()
2) modParser::collectElementTags()

The second call to processElementTags() in modResponse::outputContent() just strips revo tags that couldn't be parsed. It could be replaced by this:

<pre>
$prefix = preg_quote('[[');
$suffix = preg_quote(']]');
$regex = '/' . $prefix . '(?>[^' . $prefix . $suffix . ']+|(?R))*' . $suffix . '/';
if($result = preg_replace($regex ,'',$this->modx->resource->_output))
{
   $this->modx->resource->_output = $result;
}
</pre>

The modParser::collectElementTags() could be replaced by this for 4X less code and more than 3X better performance:

<pre>
 public function collectElementTags($origContent, array &$matches, $prefix= '[[', $suffix= ']]') {
        $regex = '/' . preg_quote($prefix) . '(?>[^' . preg_quote($prefix) . preg_quote($suffix) . ']+|(?R))*' . preg_quote($suffix) . '/';
        $results = array();

        if (!empty ($origContent) && is_string($origContent) && strpos($origContent, $prefix) !== false) {

            // All tags found will be stored in an array within the first index of $results (within $results[0])
            if(preg_match_all($regex,$origContent,$results)) {
                /*
                An example of what the $results array will now look like:
                Array
                (
                    [0] => Array
                        (
                            [0] => [[$my_chunck? &replace=`[[$chunk_to_replace]]`]]
                            [1] => [[$my_snippet]]
                        )
                )

                Below, it is converted to to match the output of the current collectElementTags() method:

                Array
                (
                    [0] => Array
                        (
                            [0] => [[$my_chunck? &replace=`[[$chunk_to_replace]]`]]
                            [1] => $my_chunck? &replace=`[[$chunk_to_replace]]`
                        )

                    [1] => Array
                        (
                            [0] => [[$my_snippet]]
                            [1] => $my_snippet
                        )
                )
                */
                $prefixLength = strlen($prefix);
                $suffixLength = strlen($suffix);
                $prefixSuffixLength = $prefixLength + $suffixLength;
                foreach($results[0] as $result) {
                    $matches[] = array($result, substr($result, $prefixLength, strlen($result) - $prefixSuffixLength));
                }
            }
        }

        return sizeof($results[0]);
    }

</pre>

I have only tested these changes using simple templates. I haven't created a "real world" site to test. I would be very interested in test results and benchmarks using a complex site.

**Comment by opengeek** [comment]
opengeek submitted:

This is good stuff, and something I have been experimenting with for a while, but I could not solve issues regarding unicode data getting lost in some cases. Has this been tested with a variety of UTF-8 data by chance?

**Comment by rickj** [comment]
rickj submitted:

Not at all, sorry. I'm hoping work will use modx so I can play a little more. Do you have a complex application you could test?

**Comment by opengeek** [comment]
opengeek submitted:

This is a longer-term research and development project

**Comment by opengeek** [comment]
opengeek submitted:

After many experiments, I could find no way to make this work properly, and what I could get to work by removing the recursive rules performed much slower than the current parsing algorithm.
