### ISSUE TITLE
Elements Tree Not Expanding

### ISSUE THREAD

**Issue by adamwintle** [modxbot/migrate#2764]
adamwintle created Redmine issue ID 2764

I've just updated a MODx Revo install and when I click the [+] on any of the items in the elements tree (e.g. Templates, Chunks, Snippets, etc) it displays no results, like there's no items inside, yet the site does have templates, chunks, etc.

I've tried reinstalling MODx a few times but the problem is still there.

**Comment by splittingred** [comment]
splittingred submitted:
- Any errors in core/cache/logs/error.log?
- Did you mess with Access Controls at all?
- OS/Browser?
- PHP/MySQL Version?
- Server OS and version?

**Comment by adamwintle** [comment]
adamwintle submitted:
- I've not changed the Access Controls for this site, the view_element permission is there.
- Using Chrome, Safari and Firefox on Mac OS X
- PHP version 5.2.12 and mySQL 5.0.90 - Server running Linux
- The error log is 34.3 MB - I've quickly scanned it but I couldn't see anything which could be related to this issue - what type of errors could this generate?

I have other MODx installations on this server without any problems, so something's gone wrong with the upgrade - is there a way to preserve the website content but install the Manager fresh?

**Comment by splittingred** [comment]
splittingred submitted:

Just run setup in upgrade mode.

**Comment by adamwintle** [comment]
adamwintle submitted:

I've fixed this now - I'm not sure if its actually a bug with MODx - I suggest we close this ticket?
