### ISSUE TITLE
Username missing from top right corner

### ISSUE THREAD

**Issue by xpix** [modxbot/migrate#2765]
xpix created Redmine issue ID 2765

Username missing from top right corner
See attached. 

This is for MODx Revolution 2.0.5-dev (git)

Maybe related to this 2666 issue
Thanks

**Comment by splittingred** [comment]
splittingred submitted:

There is no attachment in this ticket?

**Comment by xpix** [comment]
xpix submitted:

Please close. Probably a cache issue although I cleared the cache even removed the core/cache folder
