### ISSUE TITLE
Session cookie secure 

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#2768]
onepack created Redmine issue ID 2768

Setting session cookie secure to "yes" kicks me out of the system and prevents me from logging in again and redirects me to the manager login even after deleting all domain cookies and sessions.

Going into the database and setting the secure session cookie value back to 0 and then deleting config.cache.php fixed the problem for me.

This needs to be checked.

See: http://modxcms.com/forums/index.php/topic,57099.0.html

**Comment by opengeek** [comment]
opengeek submitted:

You should never set this unless you have https access to your site. This means only allow cookies to be set if the connection is secure. I don't know that there is a way to detect this easily, but we'll research it.

**Comment by onepack** [comment]
onepack submitted:

If HTTPS cannot be detected another option could be: Clicking "yes" should show a confirmation message before executing the change. In the message something like this:

Only activate this when you have HTTPS access to your site. If not your site and manager interface will become inaccessible.

If that's impossible maybe showing a hover with the above message. Or show this description with the above message at all times in a slightly different "warning color".

I don't know.. just some ideas. Hope I can help out a bit :-)

**Comment by onepack** [comment]
5 Years later. Closed!
Please create a new case if someone still thinks this is valid.
