### ISSUE TITLE
E-mail Template Variable doesn't perform syntax checking

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#2770]
wshawn created Redmine issue ID 2770

In its current rendition - the E-mail TV appears to be little more than a text box. 

Other input type have some basic syntax checking / validation.

Could this be added to the Email TV also?

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/e023a05830ac35ac317a20e29ca07439a0ecbd3d
