### ISSUE TITLE
Access policy for Editor

### ISSUE THREAD

**Issue by u007** [modxbot/migrate#2779]
u007 created Redmine issue ID 2779

Hi,

Would it be good to have an editor configuration to come with modx default installation?
I would like to suggest a new role: "Editor", with authority level of maybe: 5000.

And comes with "editor" policy, with policies:
- change_profile
- class_map
- countries
- edit_document
- frames
- help
- home
- load
- logout
- resource_tree
- save_document
- view
- view_document
- new_document

and another policy for editor to edit while seeing the resource tree:
Policy: "_Load, list, view and tree_", with policies same as "load, list, view" and "resource_tree" policy.

And a default user group "editor" which inherit context access:
- context: mgr, min role: "editor", access policy: "editor"
- context: web, min role: "editor", access policy: "Load, list, view and tree"

**Comment by wshawn** [comment]
wshawn submitted:

I do not know if there will be any "default" users ever provided outside of the 0 (admin) and 9999 (anonymous) users. This might be something for someone to create an add-on to provide.

**Comment by u007** [comment]
u007 submitted:

cool, thanks Shaun :)

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/6fc832eada8edc059e0886e4fb142ccaf5ca4830

**Comment by u007** [comment]
u007 submitted:

Hi,
Sorry, i missed out this permission: "delete_document" in the policy list ...
Could you please help to add?
thanks :)

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/c0c0dce6e16e86454aa98005c9d7579c6b39524e
