### ISSUE TITLE
modx.userLoggedIn to accept context?

### ISSUE THREAD

**Issue by u007** [modxbot/migrate#2783]
u007 created Redmine issue ID 2783

Hi,

I think the method of modx.class.php userLoggedIn shall have parameter of "context"?
Is there any other way for me to get if a user is logged in on certain context?

thanks.

**Comment by u007** [comment]
u007 submitted:

Also isMemberOfWebGroup...

**Comment by splittingred** [comment]
splittingred submitted:

Yes:

<pre>
$modx->user->hasSessionContext('contextKey');
/* or */
$modx->user->hasSessionContext(array('ctx1','ctx2'));
</pre>

**Comment by u007** [comment]
u007 submitted:

thanks :)

**Comment by splittingred** [comment]
splittingred submitted:

Since this method is to be removed in 2.1, closing ticket.
