### ISSUE TITLE
Image Input TV type broken

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#2785]
wshawn created Redmine issue ID 2785

Provides only the caption and description.  

Suspect it should create a box to browse for the image, but wouldn't that be the purpose of the file input type?

As this is an input type
My thinking is that this should be a company logo displayed on every page using it, such as twitter or whatever.

Input value: http://a0.twimg.com/a/1289518607/images/fronts/logo_withbird_home.png (or what ever logo)

Default value field in the TV: http://twitter.com/

With each resource adding to the base url to a designated page /#!/shawnwilkerson

Which could output the logo: <a href="default value" . resource specific value> <img src"input value"></a>

If a resource does not have the TV defined -- nothing happens.

**Comment by splittingred** [comment]
splittingred submitted:

The image TV input render is not broken; and changing it would break many sites.

**Comment by wshawn** [comment]
wshawn submitted:

Apparently, I needed to clear cache.  Even the initial creation of the TV did not provide the drop down / file browser.

After clearing cache, it appears.
