### ISSUE TITLE
tinymce and opera: "Saving..." doesn't disappear

### ISSUE THREAD

**Issue by yurkobb** [modxbot/migrate#2786]
yurkobb created Redmine issue ID 2786

Hello.
I've noticed that after I installed timymce, when I click "Save" on a resource in Opera, the "Please wait" popup no longer disappears when the operation gets finished and stays there forever. The page needs to be reloaded to be usable again.
My server info:
- System: FreeBSD web48.nic.ru 6.4-RELEASE-p7 FreeBSD 6.4-RELEASE-p7 #7: Sun Oct 4 02:40:13 MSD 2009 root@hdad.nic.ru:/usr/obj/usr/src/sys/HNIC-SMP-ULE-IBM pl#12 i386
- PHP version: 5.2.10
- Apache Version: Apache/1.3.37 (Unix) mod_fastcgi/2.4.2 mod_perl/1.29 PHP/5.2.10
- MySQL Version: client: 5.1.16-beta (from php_info()); server: 5.1.41-log (from MODx System Info) with pdo_mysql

Opera version:
"Opera 10.63. Build 6450 for Linux.
Compiled on Oct  8 2010 by gcc 4.3.2 (ABI: 1002) for GNU libc 2.7."

Thank you for any attention,
Good luck.

**Comment by wshawn** [comment]
wshawn submitted:

Have you tried other browsers?

Opera does tend to be finicky at times...

**Comment by yurkobb** [comment]
yurkobb submitted:

W ShawnWilkerson wrote:

> Have you tried other browsers?
> 
> Opera does tend to be finicky at times...

Of course, I use Mozilla Firefox and it works great. This is Opera-specific behavior.

**Comment by splittingred** [comment]
splittingred submitted:

Issues related to TinyMCE should go in the TinyMCE tracker: http://github.com/splittingred/TinyMCE/issues

**Comment by gadamiak** [comment]
gadamiak submitted:

I observe this on every resource regardless @richtext@ setting since installed TinyMCE 4.1.2. I guess this may concern MODx itself.

Running MODx 2.0.5-pl (git).
