### ISSUE TITLE
Installation of 2.0.4 pl2 gives blank screen when PHP is in Safe_Mode

### ISSUE THREAD

**Issue by BertCatsburg** [modxbot/migrate#2789]
bertcatsburg created Redmine issue ID 2789

Installation of 2.0.4 pl2 gives blank screen when PHP is in Safe_Mode.
This is either a documentation issue and should be solved in the Installation Instruction on the website,
or this is a installation issue which should be solved by letting the software check if PHP is running is Safe_Mode and then giving an error message on the screen.
Or it's a more serious issue if we want MODX to be able to run in Safe_Mode (which is unlikely I think)

**Comment by wshawn** [comment]
wshawn submitted:

As much as I hate the environment box, we will need that information to look into the issue.

I have not checked to see if install fails under safe mode with my production or live servers, but I do happen to know we can easily run Revolution with safe mode on.

Please provide additional server information.

**Comment by BertCatsburg** [comment]
bertcatsburg submitted:

Environment is a Linux CentOS server.
Hosting Environment is Plesk.
PHP version is 5.2.13
Apache is 2.2.3 (CentOS)

There is a SUHOSIN Security layer running, although that has probably nothing to do with this issue.

Please let me know if you need more environment details.

**Comment by splittingred** [comment]
splittingred submitted:

Check added in https://github.com/modxcms/revolution/commit/7c2af15ef24c985fa68f728aae714fda07476e86

**Comment by warenhaus** [comment]
warenhaus submitted:

hi. I just had a blank-screen on setup problem that was not solvable reading all the install-documentation i could find - it was solved however by me turning safe_mode OFF.

then, after a couple of steps INTO the setup, reaching the system-check, it told me the safe mode was correctly OFF. However, the check at that point is useless, as I could never have reached the check having SafeMode still ON.

safe mode ON means blank install page.
safe mode OFF means I can install fine, including running the systemcheck, which then tells me that safe mode is OFF. 

modx version 2.0.6-pl2 (traditional install) 
PHP Version 5.2.12
Apache/2.2.8 (Linux/SUSE) 
mysql 5.0.51a
