### ISSUE TITLE
URL output type appears to ignore FURLs setting

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#2794]
wshawn created Redmine issue ID 2794

If output type is set to URL using the resourcelist TV it returns the ID number of the resource instead of the friendly URL equivalent.

Could this be modified to return the FURL instead?

**Comment by wshawn** [comment]
wshawn submitted:

Typically, a URL output allows for output to be entered.  If these fields are left empty, could not a call to makeURL to an internal link be implemented instead?

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/e0a49254dc2ca98e9fb4eb344671ca71e97fe8e7
