### ISSUE TITLE
ext.js : debug and debug-with-comments should be taken out of distribution

### ISSUE THREAD

**Issue by BertCatsburg** [modxbot/migrate#2799]
bertcatsburg created Redmine issue ID 2799

ext js
It seems like the ext Javascript library is included. But is that only for the modx manager?
If so, why also include the debug and debug-with-comments files? They take up another 4 Mb's of uploading files.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/a31b6d6b67746e31001c3bb1474ded10a31bc03c
