### ISSUE TITLE
Checkbox TVs not saving properly

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2801]
bobray created Redmine issue ID 2801

For a checkbox with input option values: Red||Blue||Green,

When Red and Green are checked, saving the resource puts 0||0 in the database for the TV value.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/48c876137c0fdfa7959b65a2837d575b8d7af8ca
