### ISSUE TITLE
Info blocks on Manager-Homepage not fully shown in width. 

### ISSUE THREAD

**Issue by BertCatsburg** [modxbot/migrate#2803]
bertcatsburg created Redmine issue ID 2803

On the first page in the Manager, the blocks are too wide for the width. Making the window wider does resize the block, but the right-side still disappears. 
I guess that a picture says more than this complicated description...
This happens on Max OS-X version Leopard with a Firefox browser version 3.6.12

**Comment by onepack** [comment]
onepack submitted:

Changing this in the CSS should fix the problem I suppose.

ext-all-notheme-min.css

.x-column {
float:left;
margin:0px 8px 0px 0px;
/_overflow:hidden;_
/padding:0px;
}

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/c187d3b04955981b0619001af922d5f6f278d7ec
