### ISSUE TITLE
getLoginUserID for other context than web/mgr

### ISSUE THREAD

**Issue by u007** [modxbot/migrate#2806]
u007 created Redmine issue ID 2806

I realise the code for modx.class.php, method: getLoginUserID
try to get $context."internalKey" to get the user logged in.
It seems to fail because if the context is not mgr or web, it will be set to modx.user.contextTokens.

Perhaps we could fix this issue by assigning $context."internalKey" to session to fix this? :)

thanks...

**Comment by u007** [comment]
u007 submitted:

if my solution is good, then i found the method to fix:
moduser.class.php -> addSessionContext

hope it helps :)

**Comment by opengeek** [comment]
opengeek submitted:

Correct, to log a user in, you use modUser::addSessionContext().
