### ISSUE TITLE
settings for browser sort by default

### ISSUE THREAD

**Issue by eerne** [modxbot/migrate#2807]
eerne created Redmine issue ID 2807

currently the modx browser has "name" as sort by default. It would be great if this could be configured through system settings. I.E sometimes showing "last modified" by default can be very useful.
thanks for looking into this.

**Comment by splittingred** [comment]
splittingred submitted:

Added in https://github.com/modxcms/revolution/commit/1de02c10b48c8d93e40b256f989283e22ea14dfa
