### ISSUE TITLE
Possible bug: Rich Text Output Type does not place widget in page

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#2815]
wshawn created Redmine issue ID 2815

Choosing a rich text output type places the following in the page:

<pre>
<div class="MODX_RichTextWidget"><textarea id="tvauthor_summary" name="tvauthor_summary" style="width:500px; height:300px;">
</pre>

Essentially it is only a text area.

Is this as intended or is there supposed to a TinyMCE attached?

**Comment by splittingred** [comment]
splittingred submitted:

Not a bug at all; if there is an issue, it's that TinyMCE at this time doesn't support front-end RTEs.

And if that's the case, that should go in the TinyMCE tracker on GitHub; not in the core Revo tracker here.
