### ISSUE TITLE
profile tabs dom id: ext-comp-1033

### ISSUE THREAD

**Issue by u007** [modxbot/migrate#2820]
u007 created Redmine issue ID 2820

Hi,

i realise the profile page, the tabs target id is ext-comp-1033.
is it possible to name it to something like _modx-panel-profile-tabs_?
it seems to effect form customization as current target to modx-panel-profile doesnt seems right..

thanks :)

**Comment by u007** [comment]
u007 submitted:

I really hope that someone could enlighten me on how i could go about adding fields into the tab i created for it..
i tried duplicate some code, and then
Ext.extend(MODx.panel.mypanelfields, MODx.FormPanel, {...});
Ext.reg("mypanelname", MODx.panel.mypanelfields);

but nothing happen...but not error.
did i miss anything?

**Comment by wshawn** [comment]
wshawn submitted:

Simply follow the examples here: http://rtfm.modx.com/display/revolution20/Customizing+the+Manager

**Comment by splittingred** [comment]
splittingred submitted:

Will fix, but be warned - FC will no longer work for non-Resource pages post 2.0.4.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/7574a5dc2cd8328eb013280c9a8f36ef30dd9f35
