### ISSUE TITLE
Capitalise first letter of username 

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#2822]
onepack created Redmine issue ID 2822

I wanted to capitalize the first letter of an existing username but got the message that the Username already exists. So now I'm unable to change it in the system.

**Comment by onepack** [comment]
onepack submitted:

Changed it directly in the database but this should be possible in the CMS environment I guess.

**Comment by wshawn** [comment]
wshawn submitted:

You may want to change the name altogether to something else and then change it back.

I believe this functionality is to keep multiple people from sharing similar names.

**Comment by onepack** [comment]
onepack submitted:

Ok, I totally agree.
I just thought it was checked in the database if another user with that name is present or not but not on the user you are editing.

Closing this ticket seems fine for me!
