### ISSUE TITLE
HTML Tag TV output typeplaces duplicate id="text"

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#2825]
wshawn created Redmine issue ID 2825

If someone opts to use the HTML Tag Output type, it places "tvauthor_tag" as the default for every item's id -- even if left empty.

As HTML standards dictate there can only be one ID in a given page, this would cause the page to break in some implementations -- such as being passed to jQuery or simple w3c validation.

<pre>
<li id="tvauthor_tag" class="tag">tag</li><li id="tvauthor_tag" class="tag">tag2</li><li id="tvauthor_tag" class="tag">tag3</li>
</pre>

I understand we can use a replace filter to delete it on the fly, but this is a tad cumbersome.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/ad5f80dd160ad8f528a018737f000126b4d9f2bf

Now appends idx of each item to dom id.
