### ISSUE TITLE
Packman 1.2rc set incorrect namespace path

### ISSUE THREAD

**Issue by jgulledge19** [modxbot/migrate#2836]
jgulledge19 created Redmine issue ID 2836

I used packman and it exported to the transport file.  But it seems that the Namespace was set the {assest}templates/churchevents rather then what I have in the namespace: {assets}components/churchevents.

When I downloaded and installed the churchevents transport package via the package manager to another site it used the incorrect path and did not work.  I just switched the namespace path and it worked fine.

**Comment by splittingred** [comment]
splittingred submitted:

This bugtracker is for Revo core issues only. Please file PackMan issues here:

http://github.com/splittingred/PackMan/issues
