### ISSUE TITLE
Property set import does not give fail message

### ISSUE THREAD

**Issue by JimKillock** [modxbot/migrate#2837]
jimkillock created Redmine issue ID 2837

On importing a property set which fails, no error message is generated. Instead, the import appears to still be "saving". 

An error report would be useful. I've included the file that failed to import, which i'll also attach to another report, about export or import of property sets.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/d4564e1f3e4f70befb35352d9faccb2db07816ec
