### ISSUE TITLE
Limitation in the way the parser is handling the properties when caching them

### ISSUE THREAD

**Issue by loxy** [modxbot/migrate#2838]
loxy created Redmine issue ID 2838

It seems to be that the parser of modx is caching the result of another snippet when it is bound to a property.

Example:

I link from a page to a form via:

<pre>
<a href="[[~15 ?job=`[[*id]]`]]"><strong>A link to a form...</strong></a>
</pre>

At the affected site I fetch the job parameter:

<pre>
[[!getUrlParam? &name=`job` &int=`1`]] 
[[!getResources? &resources=`[[!getUrlParam? &name=`job` &int=`1`]]`]]
</pre>

After caching (first loading loading) the job paramter is frozen.
The cached file shows (in the elementCache entry):

<pre>
[[!getUrlParam? &name=`job` &int=`1`]]
[[!getResources? &resources=`8`]]
</pre>

So the actual parameter of getUrlParam is not used any more. Adding a "dummy" parameter like:

<pre>
[[!getUrlParam? &name=`job` &int=`1`]]
[[!getResources? &resources=`[[!getUrlParam? &name=`job` &int=`1` &instance=`2`]]`]]
</pre>

to avoid an identical signature did not solve the issue. So it seems to be a general caching problem of the the property signature. 

Turn off caching of the resource solves the problem...but...

Kersten

**Comment by opengeek** [comment]
opengeek submitted:

I believe this was fixed via #5152
