### ISSUE TITLE
Failed Login Count doesn't update

### ISSUE THREAD

**Issue by neilness** [modxbot/migrate#2839]
neilness created Redmine issue ID 2839

When the wrong password is supplied, failedlogincount isn't updated in the database. 

needs something like:

@$up->set('failedlogincount', $up->get('failedlogincount')+1);
$up->save();@

around line 140 in core/model/modx/processors/login.php

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/99fd45224549a1a721c1a3ee61438450404098a8
