### ISSUE TITLE
session_save_path is_writeable check fails

### ISSUE THREAD

**Issue by Traxmaxx** [modxbot/migrate#2840]
traxmaxx created Redmine issue ID 2840

When changing the session_save_path in the system settings, the if statement in modx.class.php on line 2715 fails, also when the session directory is writeable.

@
if ($sessionSavePath = $this->context->getOption('session_save_path') && is_writable($sessionSavePath)) {
    session_save_path($sessionSavePath);
}
@

**Comment by splittingred** [comment]
splittingred submitted:

Already fixed in a prior commit.
