### ISSUE TITLE
Editing files in manager

### ISSUE THREAD

**Issue by ghost** [modxbot/migrate#2841]
peteedley created Redmine issue ID 2841

MODx Revolution 2.0.5-dev (git)

Server running CentOS
SQL 5.0.91-community-log
PHP 5.2.14

Browser Firefox and Chrome unable to test in IE at this point

When I click on a file in the files tab of the manager instead of opening the file editor which is what normally happens it displays the following error message 

Fatal error: Call to a member function getBasePath() on a non-object in /home/cwworguk/public_html/sgibbs/manager/controllers/default/system/file/edit.php on line 15

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/2cb44d4f34d4b0cfaace3b503c65f5eb95bbcd66
