### ISSUE TITLE
MODx Tags shown on Hover Tooltip

### ISSUE THREAD

**Issue by jacobkball** [modxbot/migrate#2846]
jacobkball created Redmine issue ID 2846

At present, when you hover over the field name on the Create/Edit Document tab, you get a description of that field, eg Title - The name/title of the resource.

Is it possible to add the Tag for that field to the beginning of that tooltip? eg Title - [[*pagetitle]] The name/title of the resource.

It's already being done with Template Variables.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/c9785492bb5ed8ae12991106145a73c98f1a2653
