### ISSUE TITLE
Drag Files into TV type image/file

### ISSUE THREAD

**Issue by eerne** [modxbot/migrate#2849]
eerne created Redmine issue ID 2849

It would be a great help if we could drag Files from the File tab, into TV's that have type image or type file.

**Comment by eerne** [comment]
eerne submitted:

These are some related issues, but afaik they want to drag it into content or new tv-types.

http://bugs.modx.com/issues/482

http://bugs.modx.com/issues/147

**Comment by splittingred** [comment]
splittingred submitted:

Done in https://github.com/modxcms/revolution/commit/35dc2ea06eaf22855353b810f11f6745bad6a7c7

**Comment by eerne** [comment]
eerne submitted:

I upgraded from 2.0.4pl to 2.0.5-dev (git), as described on rtfm install from git. then: 
- Site / Clear Cache
- Clear Browser Cache
- Flush all Session
- Flush Permissions
- Login again
- Shift-reload

When editing a resource I get:
TypeError: Result of expression 'MODx.makeDroppable' [undefined] is not a function.

**Comment by splittingred** [comment]
splittingred submitted:

Sounds like you didn't run the build, or your browser cache isn't fully cleared. The method is definitely there in the modx.js MODx class.

**Comment by eerne** [comment]
eerne submitted:

Oups yes, i didn't run it correctly (built it first locally and then uploaded to the server). Now I built and run and setup again. I'm definitely feel a lot of 2.0.5 awesomeness. everything is much faster and the new Form Customization is great.

I'm also able to drag and drop Files from the File tab into the standard Resource Variables like pagetitle or resource content. Then the url of the image appears.

But it doesn't drag into a custom TV's, tried Input Type: text, file and image.

**Comment by eerne** [comment]
eerne submitted:

and still:
MODx.makeDroppable is not a function
(24 out of range 3)
42 (line 24)
http://mydomain.com/manager/assets/ext3/ext-all.js/eval/seq/42

**Comment by splittingred** [comment]
splittingred submitted:

Definitely cannot reproduce this. What's your:

modx/manager/assets/modext/core/modx.js

file contain? If it doesn't have the makeDroppable method, then you did something wrong.

**Comment by eerne** [comment]
eerne submitted:

Yes the makeDroppable is there in manager/assets/modext/core/modx.js see http://pastie.org/1327793 but in the minified version it's missing http://pastie.org/1327796 (using http://jsbeautifier.org/ to un-minify it)

Setting compress_js to No makes drag'n'drop files into TV's just working!!! I'm very exited!
Thank you Shaun!

About the path it now generates: before when picking an image thorugh TV/browser it made a path
assets/files/dir/file.jpg
if you pick an image in 2.0.5-dev by TV/browser OR drag file onto TV the path doesn't include filemanager_path anymore.
/dir/file.jpg

This is no big problem as I know filemanager_path and can add it manually in the template, but before I change it: Is this change in the path intended?

another minor thing is, I believe it would make sense that on dropping that it clears the tv content first. currently if you have a tv set to : /dir/file.jpg and you drag another file onto it it result in something like: /dir/file.jpg/dir/file2.jpg

This is now really a minor detail: It would be nice to have the preview thumb again after dragging an image.

**Comment by splittingred** [comment]
splittingred submitted:

The reason it's not in your minified JS is because you didn't run the build and uncheck the 2 boxes on the setup/ options screen as the Git Installation docs indicates. ;)

As for the path issue, that would be a bug. Can you file that in a separate ticket?

**Comment by eerne** [comment]
eerne submitted:

Yes the first time I uploaded a local build version, but the second time it was build online by manually browsing to the php after giving proper db credentials.

But I didn't uncheck, as I understood it in the docs on http://rtfm.modx.com/display/revolution20/Git+Installation say:

<pre>
Make sure you +check+ both the "Core package has been manually unpacked" and "Files are already in-place" options when installing from Git.
</pre>

shouldn't that be "Make sure you +uncheck+" ? 

added the path issue on #2872 and #2873

**Comment by splittingred** [comment]
splittingred submitted:

Hm, actually, it's right - I commented wrongly. They should be checked unless you're deploying using "git archive".

I'm not sure why your files didn't update. They should, if you're running the build at _build/transport.core.php
