### ISSUE TITLE
md5 password reveal in connector

### ISSUE THREAD

**Issue by u007** [modxbot/migrate#2858]
u007 created Redmine issue ID 2858

hi,

i realise the md5 password and other information like email is being revealed when the user in the manager screen is allowed to use the message screen. This could lead to md5 crack of the md5 password and let the person to have access as administrator. 

I would suggest that the user list be trimmed down to limited fields. Perhaps the processor should have a new restrictive policy for access "full user list" to be use with managing user information, and a "simple user list" for messaging.

Hmm.. other feature suggestion:
I think it would be good to have another type of permission control to allow user to manage certain user base on user group. If there is a context base user group-user administration, then it would be more lovely :D

**Comment by u007** [comment]
u007 submitted:

My test case is focused on message module.
I've found out the policy needed to view user list is view_user, and usergroup is access_permissions.

Maybe we could have a simple_list_user for listing user for message purpose...
Or could the message screen be an open text field for people to key in the recipient username?

**Comment by u007** [comment]
u007 submitted:

Sorry, the urgency should be trivial... 
my mistake for not noticing the view_user permission...

**Comment by splittingred** [comment]
splittingred submitted:

Extra sanity checks added in https://github.com/modxcms/revolution/commit/21eed25edc86af768ca75fc0d004be2203344257
