### ISSUE TITLE
Parent ID Field in Resource editing view

### ISSUE THREAD

**Issue by zaigham** [modxbot/migrate#2869]
zaigham created Redmine issue ID 2869

When editing the resource, I can only see ID of the parent, please make it page title and ID.

Please see the attached screenshot.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/e82d4c6e88712c3dc9a362e60c3e38d8f509672c

**Comment by zaigham** [comment]
zaigham submitted:

I have checked this and this doesnt show the Parent's pagetitle, instead it shows the current page's pagetitle.

Also, when I change the parent via this field, it becomes like the attached screenshot.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/6c204344180e41467dd2842b3aaef31b4552ab2a
