### ISSUE TITLE
moduserprofile.map.inc.php should have the default value of 'internalKey' as NULL.

### ISSUE THREAD

**Issue by goldsky** [modxbot/migrate#2870]
goldsky created Redmine issue ID 2870

This error

[2010-11-27 19:40:49](ERROR @ /modx-revo-discuss/index.php) modUserProfile: Attempt to set NOT NULL field internalKey to NULL

makes me think that the moduserprofile.map.inc.php should have the default value of 'internalKey' as NULL.
It aggregates one-to-one to modUser.

**Comment by opengeek** [comment]
opengeek submitted:

No, NULLS should not be allowed in that field. A modUserProfile with a NULL internalKey is an orphaned record.

**Comment by splittingred** [comment]
splittingred submitted:

This seems to pop up when using addOne($profile) on a new modUser object, attaching a modUserProfile to it before saving (to allow transaction-simulation).
