### ISSUE TITLE
Picking File/image TV path changed

### ISSUE THREAD

**Issue by eerne** [modxbot/migrate#2873]
eerne created Redmine issue ID 2873

in 2.0.4 when picking an image through TV/browser it made a path
assets/files/dir/file.jpg
in 2.0.5-dev if an image is picked by TV/browser OR drag file onto TV the path doesn't include filemanager_path anymore.  it's just
/dir/file.jpg

This is no big problem as I know the filemanager_path and can add it manually in the template, but before I change it: Is this change in the path intended?

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/5c62708ed949c778e48afd8b9ce00adb259822b0
