### ISSUE TITLE
manager blockedafter, blockeduntil

### ISSUE THREAD

**Issue by u007** [modxbot/migrate#2874]
u007 created Redmine issue ID 2874

Hi,

i realise the blockedafter and blockeduntil does not show properly after setting it to a user.
Since both may contain time, im would like to suggest that the xtype to "xdatetime".
And changing from width: 150 to width: 210.
Instead of format, change it to dateFormat, 
and add in hiddenFormat: 'Y-m-d H:i:s'
file effected:
manager/assets/modext/build/widgets/security/modx-panel.user-min.js

And i think that its more suitable to have processor:
core/model/modx/processors/security/user/get.php
to retrieve the blockedafter and blockeduntil in iso format.
There fore, suggested formating is:
%Y-%m%d %H:%M:%S

thank you :)

**Comment by u007** [comment]
u007 submitted:

Also need to include this js file to have the xdatetime field to work :)

MODx.config.manager_url + "assets/modext/util/datetime.js

**Comment by splittingred** [comment]
splittingred submitted:

Fixed.
