### ISSUE TITLE
Wayfinder: Boolean parameter values

### ISSUE THREAD

**Issue by ottogal** [modxbot/migrate#2884]
ottogal created Redmine issue ID 2884

For the parameters  _&ignoreHidden_  and  _&hideSubMenus_ only the value _`0`_ is interpreted as false, whereas all of the following are interpreted as true:   _`1`, `TRUE`, `FALSE`_ (!!)
By the way: 
With   _&ignoreHidden=`1`_  the submenus are not any more hidden, despite the parameter  _&hideSubMenus=`1`_

**Comment by wshawn** [comment]
wshawn submitted:

This is not a Revolution issue, and should probably be moved to the Wayfinder bugs: [[http://github.com/splittingred/Wayfinder/issues/]].

You might also want to include which version of Wayfinder you are running.

**Comment by splittingred** [comment]
splittingred submitted:

Adjusted shawn's message to note that bugtracker is _not_ for Extras, but rather for the extras website specifically.
