### ISSUE TITLE
PublishedOn date does not set after page saved

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#2885]
wshawn created Redmine issue ID 2885

Create a document, adjust the published settings -- it works.

Create a Document
Adjust the date, leave default "now" time
Save The Document.

Edit the Document and attempt to change the time.

Will not save the updated time.

Once a publishedon time is set it can not be updated -- without manually updating the field in the table.

**Comment by splittingred** [comment]
splittingred submitted:

I can't reproduce this at all. Must have been fixed in latest.
