### ISSUE TITLE
image upload on different context

### ISSUE THREAD

**Issue by u007** [modxbot/migrate#2897]
u007 created Redmine issue ID 2897

ive login as a user who have access to only context "mycontext".

When i login and edit resource for "mycontext" (parent) context,
 and try to insert a image, and clicking to list images from server,

i realise the browser retrieve from processor getlist and getfiles.
But, it turn out that the ctx wasnt pass in for getfiles, but getlist has ctx passed in.

When i refresh both the top left directory or top files filter list, ctx is passed in.

---

both getFiles and getList doesnt collect context information:

And inside getFiles.php:
getBasePath(); //is missing 2 param,
Example: ....getBasePath(false, $context);
getBaseUrl($context);

And inside getList.php:
Same issue as above...

I'm not sure if this is a bug or not, but im getting modFileHandler:
$context->prepare(); // call to prepare on a non-object...

im confused, anyone can enlighten me on it? :)

thanks you...

**Comment by splittingred** [comment]
splittingred submitted:

This is already addressed and fixed in 2.0.5.
