### ISSUE TITLE
Bad long cookie ys-modx-resource-tree and 400 Bad Request report from server when reach about 35+ resources in resource tree

### ISSUE THREAD

**Issue by vedy** [modxbot/migrate#2898]
vedy created Redmine issue ID 2898

Suddenly, I bump with problem at opening and editing my site as administrator in manager backend.
When count of document  resources in one  resources tree  container reached about 30+ and I recieved '400 Bad Request' from server when I tried open one for editing, or even open site's main page.

After some investigation I found, that one of backend's cookie, named 'ys-modx-resource-tree', has too long size and probably was trimed, for examle:

@ys-modx-resource-tree=a%3As%253A/root%5Es%253A/root/web_0/web_1%5Es%253A/root/web_0/web_28%5Es%253A/root/web_0/web_38%5Es%253A/root/web_0/web_39%5Es%253A/root/web_0/web_40%5Es%253A/root/web_0/web_4%5Es%253A/root/web_0/web_33%5Es%253A/root/web_0/web_5%5Es%253A/root/web_0%5Es%253A/root/web_0/web_2/web_97%5Es%253A/root/web_0/web_2/web_114%5Es%253A/root/web_0/web_2/web_102%5Es%253A/root/web_0/web_2/web_6%5Es%253A/root/web_0/web_2/web_7%5Es%253A/root/web_0/web_2%5Es%253A/root/web_0/web_2/web_35%5Es%253A/root/web_0/web_134/web_137%5Es%253A/root/web_0/web_134/web_136%5Es%253A/root/web_0/web_134%5Es%253A/root/web_0/web_43/web_47%5Es%253A/root/web_0/web_43/web_55%5Es%253A/root/web_0/web_43%5Es%253A/root/web_0/web_43/web_41/web_42%5Es%253A/root/web_0/web_43/web_41/web_135%5Es%253A/root/web_0/web_43/web_41/web_44%5Es%253A/root/web_0/web_43/web_41/web_45%5Es%253A/root/web_0/web_43/web_41%5Es%253A/root/web_0/web_2/web_35/web_138%5Es%253A/root/web_0/web_2/web_35/web_36%5Es%253A/root/web_0/web_2/web_35/web_37%5Es%253A/root/web_0/web_2/web_35/web_126%5Es%253A/root/web_0/web_2/web_35/web_95%5Es%253A/root/web_0/web_2/web_35/web_96%5Es%253A/root/web_0/web_2/web_35/web_99%5Es%253A/root/web_0/web_2/web_35/web_101%5Es%253A/root/web_0/web_2/web_35/web_103%5Es%253A/root/web_0/web_2/web_35/web_104%5Es%253A/root/web_0/web_2/web_35/web_105%5Es%253A/root/web_0/web_2/web_35/web_106%5Es%253A/root/web_0/web_2/web_35/web_109%5Es%253A/root/web_0/web_2/web_35/web_110%5Es%253A/root/web_0/web_2/web_35/web_111%5Es%253A/root/web_0/web_2/web_35/web_112%5Es%253A/root/web_0/web_2/web_35/web_113%5Es%253A/root/web_0/web_2/web_35/web_115%5Es%253A/root/web_0/web_2/web_35/web_116%5Es%253A/root/web_0/web_2/web_35/web_117%5Es%253A/root/web_0/web_2/web_35/web_118%5Es%253A/root/web_0/web_2/web_35/web_119%5Es%253A/root/web_0/web_2/web_35/web_120%5Es%253A/root/web_0/web_2/web_35/web_121%5Es%253A/root/web_0/web_2/web_35/web_122%5Es%253A/root/web_0/web_2/web_35/web_123%5Es%253A/root/web_0/web_2/web_35/web_124%5Es%253A/root/web_0/web_2/web_35/web_125%5Es%253A/root/web_0/web_2/web_35/web_127%5Es%253A/root/web_0/web_2/web_35/web_128%5Es%253A/root/web_0/web_2/web_35/web_129%5Es%253A/root/web_0/web_2/web_35/web_130%5Es%253A/root/web_0/web_2/web_35/web_131%5Es%253A/root/web_0/web_2/web_35/web_132%5Es%253A/root/web_0/web_2/web_35/web_133; expires=Fri, 03 Dec 2010 09:38:47 GMT; path=/; domain=38mama.ru@

Problem happens if I fully expand resource tree with more than 35 elements in one of container-resource and then try to open nay document for editing or just even open main site's (or other) page,+ until I clean cookies.+

So, I have totally unusable backend for now and have no ideas what to do to repair it.

!http://38mama.ru/forum/images/screens/38mama.ru%20screen%20capture%202010-12-2-18-7-48.png!

!http://38mama.ru/forum/images/screens/screenshot_191.png!

**Comment by splittingred** [comment]
splittingred submitted:

This has already been addressed in 2.0.5.
