### ISSUE TITLE
unselectabled 'Topic' field when Create Entry on Lexicon

### ISSUE THREAD

**Issue by goldsky** [modxbot/migrate#2900]
goldsky created Redmine issue ID 2900

I tried to add a new entry into the Lexicon.
The Topic was set to 'default'.
When I changed the Namespace to 'spiefeed', then the Topic changed automatically and became an empty dropdown list.

Revo 2.0.4-pl2, on Firefox 3.6.12

**Comment by splittingred** [comment]
splittingred submitted:

Invalid; spiefeed must:
1. Not have any lexicons
2. Not have their namespace and lexicon directory setup correctly
