### ISSUE TITLE
When you check "container" checkbox on resource doesn't change on menu unless something is in

### ISSUE THREAD

**Issue by theuros** [modxbot/migrate#2903]
theuros created Redmine issue ID 2903

If you check "container" in a resource, icon on left menu doesn't change unless some other resource is inside. This doesn't bother me, but is confusing for my clients.

**Comment by opengeek** [comment]
opengeek submitted:

This is because having children is not the same as being marked as a container. You just need to educate your client on the difference between a Resource having child Resources and being a container (i.e. acts like a folder on a webserver in terms of URL access).
