### ISSUE TITLE
Saving resource causes error (server-specific)

### ISSUE THREAD

**Issue by Nimja** [modxbot/migrate#2906]
nimja created Redmine issue ID 2906

_When saving any normal web resource (ie. a web-page); saving crashes. This is because:_

Fatal error:  Allowed memory size of 41943040 bytes exhausted (tried to allocate 82 bytes) in 
/core/xpdo/om/xpdoobject.class.php on line 616

Have tried to update xpdo to rc3, no difference

Noticed no error checking in /manager/assets/ext3/ext-all.js

Ext.util.JSON
        doDecode = function (json) {
            return eval("(" + json + ")")  <---- It parses data directly used, so PHP errors will cause java-errors, causing the save-dialog to crash.
        },

Issue is not 'critical' because resource DOES get saved. Any other resources saved (template, chunk, etc.) have no problems. But a manual (slow) refresh after every save does get annoying fast.

**Comment by splittingred** [comment]
splittingred submitted:

Sounds like your server is either:
a) incorrectly setup
b) doesn't have enough memory allocated to it

Please provide more information about your server environment:
- Traditional or Advanced distribution (for Revo)
- MySQL Version (client and server)
- If you are using any opcode caching such as eAccelerator, APC, winCache, xCache, etc
- If you are using mod_security or suhosin
- Any relevant errors in core/cache/logs/error.log
- Any other environment data we should know

**Comment by SebastienDaniel** [comment]
Askarii submitted:

Hi Shaun,

We have the same issue, and it happened since we updated from 2.0.4 to 2.0.5, never had this issue before.
Considering this, do you still believe it is server related?

**Comment by Nimja** [comment]
No longer relevant.
