### ISSUE TITLE
Radio TV options not saved - default not shown

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2912]
bobray created Redmine issue ID 2912

A radio option TV does not show a default value in the Mgr.

Even if it is checked manually, the value 0 is stored in the DB when the doc is saved -- whether it has a default value or not.

Radio TV:
Input Option Values: red||green||blue
Default Value: blue

**Comment by splittingred** [comment]
splittingred submitted:

Already fixed in Git.
