### ISSUE TITLE
Form Customization

### ISSUE THREAD

**Issue by ghost** [modxbot/migrate#2915]
peteedley created Redmine issue ID 2915

Form customization is not being restricted by user group here are the details 

Set up a profile called - Sub Editor

> With a user group of Subadmin
> And 2 sets
> 
> > resource/update
> > resource/create

Added a user called Editor to Subadmin group

So now the problem the Editor can sign in and gets to edit as expected with the customized form np,  But the main admin who is not a member of Subamin  also gets the customized form.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/98e75fc7a0a015b062e8a47364bcbe1b0ff92e4c

Thanks!
