### ISSUE TITLE
Parsing error with output filter

### ISSUE THREAD

**Issue by mikrobi** [modxbot/migrate#2917]
mikrobi created Redmine issue ID 2917

The following code isn't parsed correctly:
@
[[_url:notempty=`<p>[[%visit? &topic=`default`&namespace=`space`]]: <a href="[[_url]]">[[*pagetitle:htmlent]]</a></p>`]]@

There is a workaround (adding =`` after htmlent) which seems to be parsed corretly:

@[[_url:notempty=`<p>[[%portfolio.visit? &topic=`default`&namespace=`classzec`]]: <a href="[[_url]]">[[*pagetitle:htmlent=``]]</a></p>`]]@

**Comment by splittingred** [comment]
splittingred submitted:

You need to do [[!*url since you expect dynamic results for the URL tv.

**Comment by mikrobi** [comment]
mikrobi submitted:

Shaun McCormick wrote:

> You need to do [[!*url since you expect dynamic results for the URL tv.

I tried to use the TV uncached:

@<div>
[[!_url:notempty=`<p>[[%portfolio.visit? &topic=`default`&namespace=`classzec`]]: <a href="[[_url]]">[[*pagetitle:htmlent]]</a></p>`]]
</div>@

In the frontend I get:

@<div>
[[!*url:notempty=`<p>[[%portfolio.visit
</div>@

Am I doing something wrong? Can't figure-out where I'm using the wrong syntax...
