### ISSUE TITLE
Manager Login redirects to Front End

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2932]
bobray created Redmine issue ID 2932

After updating to 2.0.5-dev, whenever I log in to the manager, it redirects me to a nonexistent URL in the front end. If I hit the browser's back button, I'm in the Manager.

The URL is: http://localhost/gitfork/gitforkmanager

It only happens in a fresh browser session.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/de765f2b34cabe34de7671ae165503c83ed88702
