### ISSUE TITLE
Export Properties no longer works

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2934]
bobray created Redmine issue ID 2934

If I click when on a property set or a snippet's default properties, it offers to let me save a js file. This happens on the snippet's Properties tab and in Tools->Property Sets.

**Comment by splittingred** [comment]
splittingred submitted:

Uhm, that's how it's _supposed_ to work.

**Comment by BobRay** [comment]
bobray submitted:

<sound of hand hitting forehead> Doh </sound of hand hitting forehead>
