### ISSUE TITLE
Changing Ressource Template does not refresh Form-Mods

### ISSUE THREAD

**Issue by gerritvanaaken** [modxbot/migrate#2964]
gerritvanaaken created Redmine issue ID 2964

I’ve build several form customization rules for several ressource templates (the new interface is great!). 

If I create a new ressource now, the first thing I usually do is to change the assigned template. There is  a modal dialogue which askes if I am sure. Yes, of course.

Now the assigned template changes, but the form elements do not! They should, because there are different rules for different templates!

**Comment by gadamiak** [comment]
gadamiak submitted:

I observe the same running from Git develop f3fb933.

**Comment by gadamiak** [comment]
gadamiak submitted:

Any update on this? It breaks the manager functionality when FC is used extensively.

**Comment by splittingred** [comment]
splittingred submitted:

Unless you reload the page, the FC rules won't apply. I don't know what to tell you - there's no way to apply dynamic, onload FC rules without a page reload.

**Comment by gerritvanaaken** [comment]
gerritvanaaken submitted:

But the Form Customization process is only a JavaScript/Ajax call, isn’t it? It always happens _after_ loading the form. Well, I’m not an extJS expert, but IMHO it should be possible to call this "modify my form"-function after each change of template ... 

I’m just saying that the UI does not behave like expected here, which is sub-optimal.

**Comment by gadamiak** [comment]
gadamiak submitted:

On changing the template, user is asked for confirmation, which makes him expect the form being reloaded. Would it be possible to trigger a page reload on confirmation?

**Comment by gerritvanaaken** [comment]
gerritvanaaken submitted:

Yea, that’d be perfectly okay!

**Comment by splittingred** [comment]
splittingred submitted:

Gerrit,

It's not just an JS call; there's quite a few things involved in it.

As for reloading the page - what happens to your current unsaved work? Do you lose it when you reload the page? Or does it save? If it saves, well, wait - what if you don't want it to?

Just sayin' this is more complex than sneaking into a patch release. ;)

**Comment by gadamiak** [comment]
gadamiak submitted:

Shaun McCormick wrote:

> As for reloading the page - what happens to your current unsaved work? Do you lose it when you reload the page? Or does it save? If it saves, well, wait - what if you don't want it to?

MODx can't decide for the user. It should inform the user of what will happen on template switch and let him decide, what to do. I mean, the warning should point about reloading the form and discarding all unsaved changes. Then user decides:
- goes on switches template and discards any pending changes
- or cancels and prepares the resource for template switch (or not).

It's rather straightforward IMO.

**Comment by gerritvanaaken** [comment]
gerritvanaaken submitted:

@Shaun: I understand that: page reload is required. Maybe this problem connects nicely with Ticket #3113 and can be solved together.

the user has to learn that changing the template is a bold thing to do. He must be warned of data loss, but that's already the case now!

Grezegorz's suggestion sounds very good!

**Comment by splittingred** [comment]
splittingred submitted:

We'll consider this for the 2.1/2.2 versions; I hesitate to doing a considerable code change for 2.0.x.

If we did this, then the AJAX stuff for TVs probably should be removed, and TVs would be loaded via the main create/update controller. Those need refactoring, anyway.

**Comment by zaigham** [comment]
zaigham submitted:

If user is creating a new resource, and want to input the data as per the form rules, he is actually not seeing anything similar, so he has to change the template anyway. Data loss is irrelevant here IMO.

**Comment by ncrossland** [comment]
ncrossland submitted:

If I've set form customization rules for a specific template, I'd expect them to be applied as soon as that template is selected. Requiring a reload is confusing. The user is already warned that changing templates could cause them to lose data.

**Comment by splittingred** [comment]
splittingred submitted:

Nick Crossland wrote:

> If I've set form customization rules for a specific template, I'd expect them to be applied as soon as that template is selected. Requiring a reload is confusing. The user is already warned that changing templates could cause them to lose data.

While that may seem ideal, applying such complicated rules such as hiding fields, moving tabs, and renaming them (while maintaining data integrity) is not simple to do; a safer route is a page reload.

A page reload is also a more preferred route, as Form Customization will, in future Revo versions, be done on the PHP side, rather than the JS side, to prevent the 'flicker effect' currently seen in FC rules now. This would require a page reload to make the rules take effect.

**Comment by ncrossland** [comment]
ncrossland submitted:

Would it therefore be possible to trigger an automatic page reload IF the template is changed AND the new template has FC rules? 

From a usability perspective, if I've set up FC rules, I ALWAYS want them to be applied. I don't ever want my user to see the unmodified form.

**Comment by gadamiak** [comment]
gadamiak submitted:

Wouldn't it help and increase usability if user could choose the template in a mid-step when creating new resource? I would expect a simple modal with template combo (and parent maybe to satisfy parent-template FC conditions).

That way, a reload on resource creation would not happen and user would see what he should. IMO, the template reload applies mostly (if not only) to new resources, so it could add to usability.

**Comment by gerritvanaaken** [comment]
gerritvanaaken submitted:

@Grzegorz: I love this idea! You nailed the problem!

**Comment by kenquad** [comment]
kenquad submitted:

At a minimum, couldn't the page automatically reload when the template is changed by a form customization rule on create, rather than by the user?  That would solve my personal difficulties, and I bet it would solve some others' too.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed and Awaiting integration: https://github.com/modxcms/revolution/pull/71

**Comment by opengeek** [comment]
opengeek submitted:

Integrated into develop for 2.1.0-rc1
