### ISSUE TITLE
Elements-Tab: arrows are easily missed

### ISSUE THREAD

**Issue by gerritvanaaken** [modxbot/migrate#3020]
gerritvanaaken created Redmine issue ID 3020

It would be nice if you could click on the very text "templates", "template variables", "chunks", "snippets", plugins", "categories" to toggle those sub trees.

Now you have to hit the tiny arrow.

**Comment by splittingred** [comment]
splittingred submitted:

Awaiting integration: https://github.com/modxcms/revolution/pull/65

**Comment by opengeek** [comment]
opengeek submitted:

Integrated into develop for 2.1.0-rc1
