### ISSUE TITLE
cultureKey system setting changes language of manager main menu when editing resource

### ISSUE THREAD

**Issue by vertexer** [modxbot/migrate#3023]
vertexer created Redmine issue ID 3023

When editing a resource, the manager main menu language changes to the one defined in cultureKey system setting ('de').
All other manager language strings are still in the language defined in manager_language ('en').

**Comment by vertexer** [comment]
vertexer submitted:

Expected behaviour: Everything in manager should be displayed in the language defined by manager_language.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/b54c68d4713cc2f5a209d3bf9615814febb4f2eb
