### ISSUE TITLE
Add method to reload context data in same request

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#3033]
bobray created Redmine issue ID 3033

It should be possible to use these (makeUrl and sendRedirect) to forward a user to a newly created resource immediately after saving it.

When using $resource->save() and clearing the cache, it works, but it fails for me when executing the resource/create processor (even if the ID is correct and the cache is cleared).

$modx->sendRedirect('index.php?id='. $forwardId) works, however.

In any case, if the resource is in the DB and you know it's ID, makeUrl() and sendRedirect() ought to be able to forward to it with no tricks, IMO.

At the least, the if($found) part of context->makeUrl() should have an else at the end, IMO.

I know that forwarding to an intermediate page and then onward is a possible solution, but it seems like a kludge to me and it complicates front-end editing for both developers and users.

**Comment by opengeek** [comment]
opengeek submitted:

You must reload the the new context data to be able to create the proper URL in the same request; the act of clearing the cache does no reload the data. This has nothing to do with makeUrl or sendRedirect being dumb. Also note that you should ALWAYS use absolute URLs including the scheme and hostname when using sendRedirect().

What would be more appropriate would be to make a public method to modX that calls the protected _initContext() method, with an additional parameter to indicate that the data should be reloaded even if in memory already. This would allow you to reload the new context data and apply it properly for use within the same request with a single method call, e.g.

<pre>
$modx->initContext('web', true);
</pre>

**Comment by mkschell** [comment]
netprophet submitted:

modContext->prepare(true) seems to work in the update resource processor, to allow FURL to be generated in the same request that it's updated
