### ISSUE TITLE
Unable to create new resources in contexts other than "Web"

### ISSUE THREAD

**Issue by SebastienDaniel** [modxbot/migrate#3034]
Askarii created Redmine issue ID 3034

When creating a new resource in one of our "contexts" other than "web" (the original context), the resource is created, but it does not show up in the resource tree, and is very difficult to access.

To access the resource i must "Search" for the resource, edit it, change ite parent to a resource in the "web" context, then DRAG it to the proper context. 

ONLY DRAGGING THE RESOURCE WORKS, giving it a new parent through the "edit resource" screen does NOT WORK.

**Comment by komelgman** [comment]
komelgman submitted:

Some information is here
http://modxcms.com/forums/index.php/topic, 58435.0.html

**Comment by SebastienDaniel** [comment]
Askarii submitted:

This issue appears to be linked to:
http://bugs.modx.com/issues/2737

**Comment by komelgman** [comment]
komelgman submitted:

Removing default value solves the problem. Use the system for several days, additional bugs with patch not found.

\core\model\modx\mysql\modresource.map.inc.php line 49

'class_key' => 'modDocument',
'context_key' => '',               <---  then change the value
'content_type' => 1,

**Comment by SebastienDaniel** [comment]
Askarii submitted:

Sergey,

I'm not sure what you want me to do. I found the file, found the line 49 which says:

<pre>
    'context_key' => 'web',
</pre>

What exactly should I be changing it to?
I'm not convinced this is the solution for my issue...

**Comment by komelgman** [comment]
komelgman submitted:

Daniel,

Simply remove the default value 

```
   'context_key' => 'web'  --> 'context_key' => ''
```

and try to work with contexts

**Comment by SebastienDaniel** [comment]
Askarii submitted:

I confirm this solution works!

I have not done extensive testing to see if it causes any other issues, but the main issue invoked in this thread is resolved.

Thank you Sergey!

**Comment by opengeek** [comment]
opengeek submitted:

That should not be the proper solution; researching...

**Comment by opengeek** [comment]
opengeek submitted:

https://github.com/modxcms/revolution/commit/3952453f8e9608e9998cf1935040513ce24f634c
