### ISSUE TITLE
Image TV - slash before filepath

### ISSUE THREAD

**Issue by wanze** [modxbot/migrate#3038]
Wanze created Redmine issue ID 3038

I'm using several Image Template Variables.
In Revo 2.0.5, when I select an image, the path is set with a slash in front:

for example:
/data/images/image.jpg

the correct path to get the image showed on the site with <img src="[[*image]]"> should be:
data/images/image.jpg

Worked correctly with previous versions.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/ee8f423b4c5b3cddd3576e1ee23fa78e5be3ecbd
