### ISSUE TITLE
Symlinks do not work properly in 2.0.5

### ISSUE THREAD

**Issue by leoandrews** [modxbot/migrate#3039]
leoandrews created Redmine issue ID 3039

In 2.0.4 and prior, the purpose of a symlink was to replicate content from the tree at another location. It used to be sufficient to create a symlink resource, specify the base template, the resource alias, the name of the page, the menu values and the value of the ID to replicate and it would do so at the new location.

In 2.0.5 it seems to be doing weirdness with templates. Instead of merely replicating the content from the original location, it's trying and failing to apply the content to any template which might be set in the symlink's template field. Only it doesn't work properly - because things like Wayfinder and getResources get confused about where in the tree the new page resides.

_But more importantly, the upgrade from 2.0.4 to 2.0.5 causes all Symlinks to break. This is not acceptable in a live environment._

**Comment by opengeek** [comment]
opengeek submitted:

The changes to Symlink behavior were in response to bug reports and a feature request to fix the behavior of Symlinks in Wayfinder and other components, as well as to allow non-empty fields of the Symlink to override the target. This change actually fixed the use of Symlinks in many sites we have developed.

That said, we can add a Setting to allow you to disable the new "merge" behavior for your Symlinks.

**Comment by opengeek** [comment]
opengeek submitted:

I have added a new setting with the key symlink_merge_fields which you can set to No (0). This will disable the new merge behavior of SymLinks and restore the original pre-2.0.5 behavior.

See commit details @ https://github.com/modxcms/revolution/commit/1518a26881e3b3f7a6da3db8a99e9a6040b3a3a9
