### ISSUE TITLE
Missing lexicon string in Core-Resource

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#3041]
bobray created Redmine issue ID 3041

The resource/update processor uses permission_denied in several places but it's not there.

It should probably be resource_update_access_denied, but that's not there either.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/891b4bbb7b17f5ce3da622a6bfff6bb5268e5b2a
