### ISSUE TITLE
XPDO addOne doesnt work...

### ISSUE THREAD

**Issue by jamestan** [modxbot/migrate#3042]
jamestan created Redmine issue ID 3042

Hi,

im not sure if im doing it right.
I've a snippet which create a resource on the fly.
The resource get created, but i couldnt get addOne to work for a template variable.
## this code below does not save the tv:

$tv = $modx->newObject("modTemplateVarResource");
$tv->set("tmplvarid", 10);
$tv->set("value", "profile");

$doc = $modx->newObject("modResource");
$doc->set("pagetitle", "test");
$doc->set("published", 1);
$doc->set("hidemenu", 0);
$doc->set("publishedby", $iUserId);
$doc->set("template", 89);
$doc->set("content", "testing");
$doc->set("alias", "test");
$doc->set("isfolder", 1);
$doc->set("parent", 5274);
$doc->set("context_key", "mycontext");
$doc->addOne($tv, "TemplateVarResources");
$doc->save();

---

this work:
$tv = $modx->newObject("modTemplateVarResource");
$tv->set("tmplvarid", 10);
$tv->set("value", "profile");

$doc = $modx->newObject("modResource");
$doc->set("pagetitle", "test");
$doc->set("published", 1);
$doc->set("hidemenu", 0);
$doc->set("publishedby", $iUserId);
$doc->set("template", 89);
$doc->set("content", "testing");
$doc->set("alias", "test");
$doc->set("isfolder", 1);
$doc->set("parent", 5274);
$doc->set("context_key", "mycontext");
//$doc->addOne($tv, "TemplateVarResources");
$doc->save();

$tv->set("contentid", $doc->get("id"));
$tv->save();

**Comment by splittingred** [comment]
splittingred submitted:

Use addMany.
