### ISSUE TITLE
HTTP 200 OK returned on not found

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#3043]
gadamiak created Redmine issue ID 3043

The error page for non-existing resource returns @HTTP 200 OK@ instead of @404@.

**Comment by gerritvanaaken** [comment]
gerritvanaaken submitted:

I can confirm that!

**Comment by opengeek** [comment]
opengeek submitted:

This is fixed and will be pushed out with a few other critical bug fixes as 2.0.6-pl.
