### ISSUE TITLE
MODx Manager Login - 404 Error After Successful Login

### ISSUE THREAD

**Issue by pixelchutes** [modxbot/migrate#3056]
pixelchutes created Redmine issue ID 3056

Was running MODx Revo up to 2.0.4-pl2 without issue, until the 2.0.5 upgrade.

Manager Login URL: http://localhost/~username/modx/revolution/manager

Since 2.0.5, am not getting 404 error on successful login...

URL from browser (post-login): http://localhost/username/modx/revolution/manager

Notice the dropped "~" in the URL...

**Comment by pixelchutes** [comment]
pixelchutes submitted:
- Above should read: "am _now_ getting 404 error"

NOTE: This was a 2.0.5 Advanced install (both boxes unchecked), upgrading from 2.0.4-pl2

What's interesting is that prior to the POST, the returnURL seems perfectly valid:

<input type="hidden" name="returnUrl" value="/~username/modx/revolution/manager/" />

**Comment by splittingred** [comment]
splittingred submitted:

I think this is due to: [#3076]. Closing this as a duplicate.
