### ISSUE TITLE
Manager hangs on saving a Parent Resource change

### ISSUE THREAD

**Issue by jeremy** [modxbot/migrate#3057]
jeremy created Redmine issue ID 3057

When saving a document with a modified "Parent Resource", Modx manager hangs with displaying the "Saving" dialog box/animation. The "Parent Resource" change is saved. If you reload the manager the resource tree does reflect the saved change.

Create two new documents as containers, then edit one of the resources and modify it's "Parent Resource" to be the other container and then save. "Please Wait, Saving" dialog box hangs. This problem occurred after upgrading a MODx Revolution 2.0.4-pl(traditional) install, and also on a fresh install of MODx Revolution 2.0.5-pl (traditional).

Original forum post about the issue: http://modxcms.com/forums/index.php/topic,58521.0.html

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/67613031393be553911453efdecd61a0a257fc6b
