### ISSUE TITLE
TinyMCE won't load when the Resource template is set to empty (0)

### ISSUE THREAD

**Issue by nomark** [modxbot/migrate#3058]
nomark created Redmine issue ID 3058

Whenever I change a resource's template to the template (empty) (ie: no template), TinyMCE won't load anymore.

After changing the template back to one of my own templates, saving ánd refreshing it does appear again.

**Comment by splittingred** [comment]
splittingred submitted:

Can't reproduce; plus - this would be a TinyMCE bug, not a Revo bug.
