### ISSUE TITLE
TV Output Type: "HTML Tag" stripping attributes

### ISSUE THREAD

**Issue by pixelchutes** [modxbot/migrate#3078]
pixelchutes created Redmine issue ID 3078

Using the "HTML Tag" output type, I noticed my assigned TV "Attributes" (under "Rendering Options") was not coming through. After some testing, it seems that the attribute _values_ are being stripped (where attr_name="attr_value", etc). The initial save seems to strip the values, but even the resulting, stripped Attributes aren't coming through in the final HTML.

When I save the TV with a simple string, however, it does show up in the resulting HTML (please see attached images)

**Comment by pixelchutes** [comment]
pixelchutes submitted:

NOTE: The title of this issue should probably be changed, as this issue does not seem limited to "HTML Tag" Output Type, but also others such as URL, Image, etc...

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/0350990b9af1a2bd5f1c28bcaceedc3c2f20931d
