### ISSUE TITLE
Problems with resource aliases when multiple articles match

### ISSUE THREAD

**Issue by leoandrews** [modxbot/migrate#3087]
leoandrews created Redmine issue ID 3087

There is a strange bug here

I have two pages - they are news pages in fact. Both articles have the same page titlr, the same resource alias. The differences are different content and different start/end dates.

News article 2's start date is immediately AFTER the unpublish date of news article 1.

However for some reason if you have two pages with the same resource alias, even if one is supposed to be live and the other is currently unpublished, neither will show and modx will just hang.

This is a big problem. You might write a news page in advance with the intention of having it automatically replace the current news page. At the moment this wouldn't work. They only way to make it function is to manually delete an article.

This effectively renders article scheduling inoperable.

**Comment by leoandrews** [comment]
leoandrews submitted:

_Important: Affects: Revo Revolution-2.0.4-pl_ Not verified in 2.0.5

**Comment by leoandrews** [comment]
leoandrews submitted:

Bumping this. Has it been resolved?

**Comment by mkschell** [comment]
netprophet submitted:

Leo, until there is a solution to this, there is a workaround. Under the news resource whose url you want to stay the same, create child resources with the different content and different publishing schedules. The children can all have different aliases - they will never get viewed as pages directly. Use the getResources snippet to load the content from whichever child resource is currently published.

**Comment by opengeek** [comment]
opengeek submitted:

This is already addressed by changes in 2.1.
