### ISSUE TITLE
Empty console on clear cache

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#3090]
bobray created Redmine issue ID 3090

I think I've found the issue. Apparently unlink is intermittently unreliable in Windows. There's been some discussion of this in the mysysGit mailing list.

unlink will fail if it thinks the file is in use (and it's sometimes confused about that). 
unlink will fail if it gets too busy.
rmdir will fail if you try to delete a non-empty directory.

I think you will get ERROR_ACCESS_DENIED back in all cases, but you might get ENOTEMPTY or EBUSY.

**Comment by splittingred** [comment]
splittingred submitted:

Was fixed in caching updates to 2.1.0.

**Comment by BobRay** [comment]
bobray submitted:

I'm seeing this again in 2.1.0-rc4. I can't reproduce it reliably and it comes and goes. Once I saw a message about unlink failing, but all other times I just see a blank console. Retrying sometimes works, but sometimes I have to clear the cache manually. Usually, the cache is not cleared when this happens.

I also see it when removing packages (though the packages are removed).

I'm on a fresh install, XAMPP Vista with no resources except the original home page and no packages installed except SPForm and Captcha.
