### ISSUE TITLE
New Event to react on a change of a system setting via plugins

### ISSUE THREAD

**Issue by mikrobi** [modxbot/migrate#3095]
mikrobi created Redmine issue ID 3095

Would be nice to have a system event "OnSystemSettingChange" with the system setting's key, old and new value as parameters.

See forum post: http://modxcms.com/forums/index.php/topic,58588.0

**Comment by mkschell** [comment]
netprophet submitted:

Perhaps OnSettingChange with a parameter to indicate whether it's a system, context or user setting?
