### ISSUE TITLE
Extension Packages features (multiple)

### ISSUE THREAD

**Issue by CyntaxDotDev** [modxbot/migrate#3098]
ReSpawN created Redmine issue ID 3098

_This is the second time I have to post this, since it didn't save it._

We would like to see two features (brought back?) into the extension packages.
- The usage of {core_path} and other placeholders such as {base_path}
- The ability to automaticly not only add the package but start the service of a package

_Placeholders_
Currently placeholders are not supported in the extension packages. We would like to see these brought back, since the server's absolute path is different on each installation AND not user friendly.

_Automaticly instantiate a package service_
Currently the format has only the package as the main key in a JSON array, with a path in the sub array (object) beneath it. We would like to see something like:

<pre>[{"visioncart":{"path":"path to the package, placeholders included!","service":true}}]</pre>

... that will automatically not only add the package (which is great) but also pushes 'visioncart' into $modx->visioncart as a service.

Thanks from the guys at VisionCart.

**Comment by splittingred** [comment]
splittingred submitted:

Duplicate of [#3097]
