### ISSUE TITLE
Resource/create on a static resource

### ISSUE THREAD

**Issue by zeVen** [modxbot/migrate#3099]
zeven created Redmine issue ID 3099

I have successfully created a set of FormCustomizations on a modStaticResource on resource/update.
Everything works fine when i edit an existing static resource.

I have duplicated the set and changed resource/update to resource/create.

Now when i add a static resource, nothing happens..

**Comment by zeVen** [comment]
zeven submitted:

See http://modxcms.com/forums/index.php/topic,58557.0.html for my post on the forums.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/bc46ed7d3131961a16e9e561f736f4ed3fc9cf03
