### ISSUE TITLE
incorrect memory_limit test when memory_limit value is number (without letter M,k,b)

### ISSUE THREAD

**Issue by esche** [modxbot/migrate#3105]
esche created Redmine issue ID 3105

when memory_limit value is in bytes without any letter (for example: 
memory_limit    134217728   128M

function modInstallTest -> _returnBytes($val) 
return this value without last digit:
input val 134217728 
returned 13421772

How to fix (my proposal):
/setup/includes/modinstalltest.class.php

protected function _returnBytes($val) {
        $val = trim($val);
// insert this line or anything else:
_if (is_integer($val)) return $val;_
... //unchanged
}

Found:
http://modxcms.com/forums/index.php/topic,58433.msg334413.html#msg334413

ps Sorry for my pretty English.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/8bef7628bcdea37275b3debba18005abc0cddd04
