### ISSUE TITLE
Resource Create and Update Processors will create resourceGroupResource for nonexistent group

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#3106]
bobray created Redmine issue ID 3106

If you send the ID of a non-existent group in the 'resource_groups' JSON string, the create and update processors will create resourceGroupResource objects for groups that don't exist, without creating the resource groups themselves. In that case the resourceGroupResource will point to a nonexistent group with no name.

<pre>
<?php
if (!empty($resourceGroupAccess['access'])) {

      // Should probably check for existence of modResourceGroup here first, and if it doesn't exist,
      // create it using $resourceGroupAccess['name'] and then get its ID for the next step.
      // ( or else just skip the group assignment altogether for nonexistent groups).

     $resourceGroupResource = $modx->getObject('modResourceGroupResource',array(
            'document_group' => $resourceGroupAccess['id'],
            'document' => $resource->get('id'),
            ));
     if (empty($resourceGroupResource)) {
          $resourceGroupResource = $modx->newObject('modResourceGroupResource');
     }
     $resourceGroupResource->set('document_group',$resourceGroupAccess['id']);
     $resourceGroupResource->set('document',$resource->get('id'));
     $resourceGroupResource->save();
}
</pre>

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/cec14998fd9ebd3af441d47b4b5a718d39547c22
