### ISSUE TITLE
System defaults not used for unset properties in resource/create

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#3118]
bobray created Redmine issue ID 3118

The code uses empty() but doesn't check isset() for these properties.

The system default settings should be used if the property is not set for these fields (around line 75):

published (publish_default)
hidemenu (hidemenu_default)
richtext (richtext_default)
searchable (search_default)
cacheable (cache_default)

**Comment by BobRay** [comment]
bobray submitted:

Sorry, I meant this to be in the processors category, but I don't have the option to change it after the fact.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/27c814bf9641e764b9d9d334c6a290e6d04dbc7e
