### ISSUE TITLE
Calling Resource/Create with no alias can result in a PHP error

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#3119]
bobray created Redmine issue ID 3119

If you call resource/create with no alias set and automatic_alias is off, setAliasPath() returns only the path, so the function that checks for duplicates considers any child documents to be be duplicates (even with unique pagetitles). 

This may be intended, but the $response object returned is not an object so any attempt to get the error message generates a function call on non-object PHP error.

We might consider using the pagetitle for an empty alias in resource/create even if automatic_alias is off.

**Comment by splittingred** [comment]
splittingred submitted:

According to the code, that already happens:

<pre>
if ($workingContext->getOption('friendly_alias_urls', false)) {
    /* auto assign alias */
    $aliasPath = $resource->getAliasPath($scriptProperties['alias'], $scriptProperties);
    $duplicateId = $resource->isDuplicateAlias($aliasPath, $scriptProperties['context_key']);
    if (!$workingContext->getOption('allow_duplicate_alias', false) && $duplicateId) {
        $err = $modx->lexicon('duplicate_alias_found',array(
            'id' => $duplicateId,
            'alias' => $aliasPath,
        ));
        $modx->error->addField('alias', $err);
    } else {
        if(empty($scriptProperties['alias']) && $workingContext->getOption('automatic_alias',null,false)) {
            $scriptProperties['alias'] = $scriptProperties['pagetitle'];
        }
    }
}
</pre>

Not sure what you are referring to here.

**Comment by BobRay** [comment]
bobray submitted:

Unless I'm misreading it, that code only executes if friendly_alias_urls is true.

Even if that's intended, you shouldn't get a PHP error if you forget to set the alias and friendly_alias_urls is false.

To reproduce: Call resource/create with friendly_alias_urls off and no alias provided.

**Comment by BobRay** [comment]
bobray submitted:

For a simpler way to reproduce this, just run this code twice or run it once with friendly_alias_urls off and no alias in the array:

$fields = array ('pagetitle'=>'testing', 'content'=>'some content', 'alias'=>'testing');

$response = $this->modx->runProcessor('resource/create',$fields);

if ($response->isError()) {
       if ($response->hasFieldErrors()) {
           $fieldErrors = $response->getAllErrors();
           $errorMessage = implode("\n",$fieldErrors);
       } else {
           $errorMessage = 'An error occurred: '.$response->getMessage();
       }
       return $errorMessage;
}
