### ISSUE TITLE
Caching stops articles being unpublished

### ISSUE THREAD

**Issue by leoandrews** [modxbot/migrate#3141]
leoandrews created Redmine issue ID 3141

This needs the community to verify. It appears that automatic publishing/unpublishing isn't working properly on a heavily cached site. We have our site cached at 3600 (default) and 180 for partial resource cache and 60 for db cache.

However it's not uncommon to find articles still live long after their unpublish time. I'm not sure if this is due to caching or if publishing/unpublishing just doesn't work very well

_This has been duplicated and upgraded to Major since it has now become clear that articles are not getting unpublished unless you manually go into the manager and clear the site cache_

**Comment by opengeek** [comment]
opengeek submitted:

This was fixed in 2.0.5-pl -- automatic publish/unpublish was broken from front-end; was not related to caching.
