### ISSUE TITLE
Auto-Trimming tags in TV of type 'autotag' and 'tag'

### ISSUE THREAD

**Issue by mikrobi** [modxbot/migrate#3142]
mikrobi created Redmine issue ID 3142

It would be helpful if one can always be sure that values in a TV of type 'autotag' or 'tag' are stored only with the following syntax: tag1,tag2,tag3 (no white spaces before or after a comma).

Here are some reasons why I think this would be helpful:
- When you are using a TV named 'tags' of type 'autotag' and you set _tags_ to "tag1,&nbsp;tag1,&nbsp;&nbsp;tag1,&nbsp;&nbsp;&nbsp;tag1" You will have listed for times  "tag1" as a clickable default value under the TV textfield, because the leading spaces after are comma are not trimmed (-> "tag1" is not equal to "&nbsp;tag1", "&nbsp;&nbsp;tag2", etc.)
- Solving this problem: https://github.com/splittingred/tagLister/issues#issue/7 would be much easier if I can be sure that there are no white spaces before or after a comma which separates the tags.

What do you think of this? I might solve this problem by using a plugin which does the job, but autotag is a core input type so I think the trimming job should be done by the core, too.

Cheers,
Jakob (alias mikrobi)

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/063316eac555ca8d83246a8c0e1db02e27fe312a
