### ISSUE TITLE
Excecute the Search

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#3143]
onepack created Redmine issue ID 3143

When I'm in Lexicon management and I want to submit a search with a enter nothing happens unless I press somewhere outside the search box.
When you don't know about this behavior you might think the search is broken.

I noticed this behavior on more places. (One of them is the plugin Doodles)

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/218f31d33c630fa673a8ec50d061b93f8954b8b4
