### ISSUE TITLE
Bug using the manager with IE and a richtext tinymce tv

### ISSUE THREAD

**Issue by ChrisNieu** [modxbot/migrate#3149]
sbm created Redmine issue ID 3149

In a clean 2.0.6 install with TinyMCE 4.1.2-pl added using all default settings--in the manager using IE, when viewing a RichText (TinyMCE) TV with previously entered content nothing will be visible in the window unless you click in the window and start typing. This is not an issue using Firefox. Sometimes it will appear correctly in IE the very first time, but if you navigate away to another page and back the problem is consistent. This also affected 2.0.5 and 4.1.2-rc.

**Comment by splittingred** [comment]
splittingred submitted:
1. Please do not set target versions.
2. This would be an issue for TinyMCE, not for the Revolution core issue tracker. Please post them here:

http://github.com/splittingred/TinyMCE/issues/
