### ISSUE TITLE
updatefromgrid missed published field

### ISSUE THREAD

**Issue by u007** [modxbot/migrate#3165]
u007 created Redmine issue ID 3165

Hi ,

updatefromgrid is missing this when the user does not have publish_document permission

$_DATA['published'] = $resource->get('published');

please add, thank you :)

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/ce97e41ef94cd2be5d0f477a3920252b4d4e9cab

**Comment by u007** [comment]
u007 submitted:

thank you Shaun :)
