### ISSUE TITLE
which_element_editor setting is ignored

### ISSUE THREAD

**Issue by andrewk** [modxbot/migrate#3166]
andrewk created Redmine issue ID 3166

which_element_editor system setting is ignored when displaying chunks. 

See BobRay's comment here: http://modxcms.com/forums/index.php/topic,57964.msg333850.html#msg333850

Assuming that TinyMCE is the default RTE for resources, and which_element_editor is set to none, the template for tinymce is rendered when editing chunks (but not when quick-editing).

I would expect it not to be rendered.

**Comment by splittingred** [comment]
splittingred submitted:

This should be a TinyMCE bug, filed here:

http://github.com/splittingred/TinyMCE/issues/
