### ISSUE TITLE
Add $tv->hasTemplate() and $template->hasTv() methods

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#3201]
bobray created Redmine issue ID 3201

New method for the TV object:

$tv->hasTemplate($tvId)

New method for the Template object:

$template->hasTv($templateID)

**Comment by splittingred** [comment]
splittingred submitted:

Done in https://github.com/modxcms/revolution/commit/4741e9c941d65761c565773d46368d4ddaabbb66
