### ISSUE TITLE
Renaming modx-resource-content via FC prevent some other rules from working

### ISSUE THREAD

**Issue by MadeMyDay** [modxbot/migrate#3205]
mademyday created Redmine issue ID 3205

When trying to rename the modx-resource-content via Form Customization all other rules for modx-resource-settings are not applied. Tried to hide most of them (longtitle,description etc.), but they are only hidden if I don`t change the label of the modx-resource-content. Renaming of pagetitle works, so it seems the hiding feature gets interrupted.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/cd75f9f23accc950d267e569fa03978a4ddf754c and https://github.com/modxcms/revolution/commit/cf8824c45cb0811c5be6cd6da23e296f4e5be657
