### ISSUE TITLE
Epoch Date in Lexicon management

### ISSUE THREAD

**Issue by zeVen** [modxbot/migrate#3206]
zeven created Redmine issue ID 3206

The column _Last modified on_ on the _Lexicon Management_ page only shows the Epoch Date when a row is modified.

I found this in 2.0.6, dunno which versions are also affected..

Also note that i cannot choose 2.0.6 in the 'Affects Revolution Version' dropdown, when creating an issue.

**Comment by MarkH** [comment]
markh submitted:

Shows "Jan 02, 2011 02:00 AM" for me for a resource I just edited. 

It aint 2am though, but I'm not sure if the time is set right.
