### ISSUE TITLE
Login, Update Profile allows duplicate email address

### ISSUE THREAD

**Issue by JRG** [modxbot/migrate#3208]
JRG created Redmine issue ID 3208

The site has the system setting "allow_multiple_emails" set to "No". Using the "Login" extra, the "UpdateProfile" snippet allows a logged in user to update the email address to the address being used by another user.

Revo 2.0.6 Login 1.5.0

**Comment by splittingred** [comment]
splittingred submitted:

Hi, this should go here, as this tracker is for Revo-only tickets.

http://github.com/splittingred/Login/issues

Thanks!

**Comment by JRG** [comment]
JRG submitted:

The same issue exists when a user registers. The user can specify an email address that is in use by another registered user. The "Login" system processes the registration and sends the person an activation link. Clicking on the activation link allows the user account to be activated.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in a prior version; also, should be filed in Login project.
