### ISSUE TITLE
Duplicate alias resources with same parent are allowed to be saved

### ISSUE THREAD

**Issue by SiNNuT** [modxbot/migrate#3225]
sinnut created Redmine issue ID 3225

I use Friendly Aliases, Friendly Alias Path, Allow duplicate aliases. Of course this is working fine for duplicate aliases that belong to different parents, the resulting url is different. (page1/contact , page2/contact, page3/contact etc.)

Now let's consider this: I set up a resource based news section where people can post news items. All news items are directly below the news parent. Because i have no direct control over user input it can happen that there are multiple news items with the same alias. Because they also share the same parent this results in duplicate url's.
Saving two resources with same alias and parent works, no warning or anything, and this is probably understandable because of the setting that allows duplicate aliases.
But when i iterate over my news items with getResources the newest duplicate alias item falls back to site_url, the older one keeps the correct url.

**Comment by SiNNuT** [comment]
sinnut submitted:

see also: http://modxcms.com/forums/index.php/topic,58904.0.html

**Comment by bertoost** [comment]
bertoost submitted:

I have this issue also, it would be great if the generation of the alias will check if the alias already exists; and if so, creates one with an unique number behind. Like page/contact-1, page/contact-2 etc.

**Comment by opengeek** [comment]
opengeek submitted:

This is resolved by the refactoring that removed allow_duplicate_alias — now a complete URI is checked for each Resource and you will not be allowed to save the Resource without changing the alias or overriding/freezing the URI to something unique.
