### ISSUE TITLE
filemanager_path outside the root but no thumbs

### ISSUE THREAD

**Issue by eerne** [modxbot/migrate#3304]
eerne created Redmine issue ID 3304

First of all: HAPPY NEW YEAR! :)

With the following setup:
- filemanager_path absolute outside the root
- filemanager_url absolute on a different subdomain

Filetree seems to work pretty well, I can create directories and upload files, but MODx Browser and TV preview thumbs can't create. Looking at the src, the path is like:

<pre>/connectors/system/phpthumb.php?h=150&w=150&src=http://subdomain.mydomain.ch//filename.jpg
</pre>

Which gives the following error in Error Log:

<pre>PHP warning: getimagesize() [<a href='function.getimagesize'>function.getimagesize</a>]: URL file-access is disabled in the server configuration
PHP warning: getimagesize(http://subdomain.mydomain.ch//filename.jpg) [<a href='function.getimagesize'>function.getimagesize</a>]: failed to open stream: no suitable wrapper could be found
</pre>

It seems phpthumb is using filemanager_url to create the thumbs, but in this case I believe it should take filemanager_path.

I created a snippet just to check if modx on my environment is able to do getimagesize to an absolute path that is outside of modx.
<pre>return getimagesize('/home/httpd/vhosts/mydomain.ch/subdomains/files/httpdocs/filename.jpg');</pre>That seem to work and give back an array.

I wish you all a happy and successful 2011!!! (sorry to start it with a bug report=

**Comment by eerne** [comment]
eerne submitted:

Possibly related to http://bugs.modx.com/issues/3052

**Comment by splittingred** [comment]
splittingred submitted:

phpThumb should be using the filemanager_url. Otherwise, multi-server support would not work.

You need to check to make sure the Setting "phpthumb_nooffsitelink_enabled" is set to No, and make sure you have ImageMagick and the proper PHP settings to enable grabbing of files off of remote servers.
