### ISSUE TITLE
PHP bug causes php failure

### ISSUE THREAD

**Issue by splittingred** [modxbot/migrate#3350]
splittingred created Redmine issue ID 3350

Not a MODx bug, per se, but a workaround is needed:

Loading a site with the ID of 2.2250738585072011e-308 crashes PHP, because of this bug:

http://www.exploringbinary.com/php-hangs-on-numeric-value-2-2250738585072011e-308/

**Comment by splittingred** [comment]
splittingred submitted:

Fixed here: https://github.com/modxcms/revolution/commit/7a374fa39c0e14dc22dc2f8fd879a76b4fb3ccbd

**Comment by splittingred** [comment]
splittingred submitted:

A better fix made here: https://github.com/modxcms/revolution/commit/3d8175c010374a3662fb86492fe7e808df0bae66

**Comment by mkschell** [comment]
netprophet submitted:

For consideration:
All GPC variables are not guaranteed to be part of $_REQUEST, it is default behavior but can be configured.
Perhaps this could be done for 2.1.0

<pre><code class="php">
// php bug 53632 (php 4 <= 4.4.9 and php 5 <= 5.3.4)
if (strstr(str_replace('.','',serialize(array_merge($_GET, $_POST, $_COOKIE))), '22250738585072011')) {
    header('Status: 422 Unprocessable Entity');
    die();
}
</code></pre>

**Comment by splittingred** [comment]
splittingred submitted:

Awaiting integration: https://github.com/modxcms/revolution/pull/80
