### ISSUE TITLE
TV bug: doesn't store to DB if the value == default value

### ISSUE THREAD

**Issue by goldsky** [modxbot/migrate#3353]
goldsky created Redmine issue ID 3353

http://modxcms.com/forums/index.php/topic,59431.msg338203/topicseen.html#msg338203
I don't know it it's intended to do as such, but this behavior returns [[!getResources? ... &tvFilters=`tvName==defaultValue` ...]] as an empty result.

**Comment by opengeek** [comment]
opengeek submitted:

This is not a bug.

This is simply an issue with the way getResources does tv filtering. In the documentation for getResources, it is noted that this will ONLY work with explicit values set for each Resource, and not with the default values or with calculated values. getResources chose efficiency over features, but other Snippets can certainly find ways to handle the default values as well—just will be a little  less efficient.
