### ISSUE TITLE
Toggle Resources IDs view in the Resource Tree

### ISSUE THREAD

**Issue by gOmp** [modxbot/migrate#3366]
gOmp created Redmine issue ID 3366

Just a minor thing. The tiniest semantic aesthetic suggestion,
Add a button to the resources tree which gives the option to toggle the view (hide/show) of the ids near the resources names.
Maybe even under the options of the 'show sorting options'.
As separated button even better :)

**Comment by splittingred** [comment]
splittingred submitted:

Already fixed through Permissions in a Policy: https://github.com/modxcms/revolution/commit/e98f632fcc706361e43e9de64d08eef9ccdd9077
