### ISSUE TITLE
Broken thmbnails in backend

### ISSUE THREAD

**Issue by sparrow** [modxbot/migrate#3374]
sparrow created Redmine issue ID 3374

I only have this issue on sites installed on a particular host but its where I have several critical sites installed. 

When browsing my images folder (assets/images) with the resource browser (usually triggered from insert image via TinyMCE) I can see 'placeholders' for all my images but no real thumbnail.Images are basically small white squares with a red X. Interestingly, once I select the image, it will show up in the Content area in the back and from end.

A related issue which may give some insight is that I have a similar issue using the Gallery Add on. Any thumbnails in this case on the front end have a broken path on both the front and backend.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/290dd4c810b6d969c22e7afeb8978d91637afe23

**Comment by sparrow** [comment]
sparrow submitted:

Hi Shaun
Thanks for looking at this. I updated the code files directly and it hasn't fixed the issue for me.
Is there a link to the very latest Revo package that I can download and reinstall? 
P
