### ISSUE TITLE
Revo installation fails on mysql 5.5 servers

### ISSUE THREAD

**Issue by marshall** [modxbot/migrate#3376]
marshall created Redmine issue ID 3376

Hello all,

In the 5.5 branch, MySQL has changed the default database engine to InnoDB (more info: http://dev.mysql.com/doc/refman/5.5/en/innodb-default-se.html).
The MODx setup fails - it isn't possible to create the table "site_content" because FULLTEXT indexes aren't supported by InnoDB.

Temporary solution: switch the default engine type to MyISAM by adding the following line to my.cnf:
default-storage-engine=MyISAM
and restart the database service (confirm by querying: "SHOW ENGINES").

Of course, the preferred solution is to explicitly declare the engine in the setup script (ENGINE=MyISAM).

Regards,
Pete

**Comment by opengeek** [comment]
opengeek submitted:

Fixed with upgrade to xPDO 2.0.1-pl — see https://github.com/modxcms/revolution/commit/18a5c0b477fba40894c8beb78dbcdb78f6572426 for commit details
