### ISSUE TITLE
Auto Generate Alias when field is empty

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#3377]
onepack created Redmine issue ID 3377

I noticed that the auto generate Alias only works the first time you save a document.
When you remove the generated alias because the used pagetitle was wrong and you adjust that it will not generate a new alias upon a new page-save.

**Comment by pixelchutes** [comment]
pixelchutes submitted:

I believe this is a duplicate of this reported bug: http://bugs.modx.com/issues/3084
