### ISSUE TITLE
manager/index.php to handle MODX_API_MODE

### ISSUE THREAD

**Issue by u007** [modxbot/migrate#3396]
u007 created Redmine issue ID 3396

Hi,

is it possible to allow manager/index.php to support MODX_API_MODE?
It would be good, as same as the modx root index.php, but for manager side.

thank you :)

**Comment by splittingred** [comment]
splittingred submitted:

https://github.com/modxcms/revolution/commit/a0a3b837727cd6f56153eea54468d40b40fe5a1a

**Comment by opengeek** [comment]
opengeek submitted:

Also for 2.1.4: https://github.com/modxcms/revolution/commit/1e0f72dfa5d44b5a6ead4050be1ccfa1d0aa338d
