### ISSUE TITLE
Modx Browser

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#3413]
onepack created Redmine issue ID 3413

Some improvements for the Modx browser would be.

Remember the sorting option of files in the modx browser or being able to set this in the system settings.
The behavior now is that when a sorting option is set this is lost when a new document is loaded.
The default sorting option is back in this case.

Default opening of Files folder in the modx browser when a file is accessed.
Default opening of Images folder when an image is being attached/uploaded

Being able to set these default modx browser folders per file type in the system settings.

**Comment by splittingred** [comment]
splittingred submitted:

Most of this is no longer applicable because of Media Sources. Please file other issues as separate tickets per issue. Closing this for now.
