### ISSUE TITLE
Modx Browser: change sort by button to text

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#3418]
onepack created Redmine issue ID 3418

The Sort by button in the Modx Browser doesn't do/ sort anything when clicked.
When the page loads with sorting option "name" as the default value and you decide to click this button to actually sort the list by name. (this doesn't work upon page load. bug: 3417) nothing happens.
You see the button move but the list stays the same.

**Comment by splittingred** [comment]
splittingred submitted:

The sort button isn't what changes it - change a value in the dropdown.

**Comment by onepack** [comment]
onepack submitted:

Maybe this should not be a clickable button then when it doesn't do anything. Maybe change this bug to UX/UI improvement?
Thanks and greetings from Holland!

**Comment by onepack** [comment]
4 Years later. Closed!
Please create a new case if someone still thinks this is valid.
