### ISSUE TITLE
Image TV path issue - Revo 2.0.6

### ISSUE THREAD

**Issue by jbeach** [modxbot/migrate#3422]
jbeach created Redmine issue ID 3422

http://modxcms.com/forums/index.php?topic=59666.new;topicseen#new

filemanager_url / filemanager_path settings - assets/files/

When I choose an image via file browser, the link that is displayed in the TV is:

assets/files/path/to/file/file.jpg

but when I leave and come back to that same resource and check that image TV it shows

path/to/file/file.jpg

In the database the path is correct, but the manager is chopping that filemanager_url/filemanager_path bit off the front of the image TV.  That would be fine except that if you make an edit to another part of the resource and save it, it's now written over the proper image path, breaking all image TVs.

In Revo 2.0.4 it would maintain the full and proper path, while still locking down root files in the file browser.  I double checked (using another client's site that still uses Revo 2.0.4) and everything works as expected.

This site was created with a new Revo 2.0.4 install with a 2.0.6 upgrade, and was after the upgrade when it broke/changed.

Revo 2.0.6-pl2 (trad)
CENTOS 5.5
Apache 1.3.42
PHP Version 5.2.14
MySQL 5.0.91-community (local)
pdo_mysql installed
Firefox 3.6.13, Safari 5.0.3

**Comment by jbeach** [comment]
jbeach submitted:

for what it's worth, a poster made this observation:
http://modxcms.com/forums/index.php/topic,59666.msg339484.html#msg339484

Shaun seemed to think it was a bug, but this looks purposeful.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/290dd4c810b6d969c22e7afeb8978d91637afe23

**Comment by jbeach** [comment]
jbeach submitted:

perfect, thanks!
