### ISSUE TITLE
Unable to drag snippets when the RTE/CodeMirror is active

### ISSUE THREAD

**Issue by adamwintle** [modxbot/migrate#3435]
adamwintle created Redmine issue ID 3435

Not sure if this should go onto the RTE/CodeMirror bugs page or here.

But I've realised the feature where you can drag snippets, chunks, etc straight into the content area doesn't work when the RTE is active - this bug also occurs when CodeMirror is installed and you try and drag a snippet into a Template.

**Comment by splittingred** [comment]
splittingred submitted:

Issue with CodeMirror, not MODX; probably due to browser security issues with IFRAMEs.
