### ISSUE TITLE
Duplicate context and sort order don't work

### ISSUE THREAD

**Issue by theuros** [modxbot/migrate#3463]
theuros created Redmine issue ID 3463
1. After you drag and drop context to position you want doesn't stay there. you can't change context order. 
2. I created context named MySite-en and then i tryed to duplicate it with name MySite-it but i couldn't

Context order must have an option of changing order, at least needs to be order by name.

**Comment by theuros** [comment]
theuros submitted:

if i duplicated context with name xxx i didn't have problems

**Comment by theuros** [comment]
theuros submitted:

Also there is not possible to change context using $mody->switchContext if context name have - in name

**Comment by garryn** [comment]
garryn submitted:

Fixed.

There are system settings that control the sorting of the contexts in the tree. A rank field has now been added for contexts so custom sort orders can now be used (by dragging and dropping contexts into the correct order via the tree, just make sure you have correctly set the system settings related to this).

Also corrected the name validation rule when duplicating a context so it matches the validation rule used when creating a context.
