### ISSUE TITLE
PHP Fatal error:  Call to a member function getPrimaryKey() on a non-object

### ISSUE THREAD

**Issue by goldsky** [modxbot/migrate#3465]
goldsky created Redmine issue ID 3465

I logged in with a restrictive username, and then this error came out on my Apache's error log.
It's funny that it wasn't shown on the MODx's.

<pre>
[Fri Jan 14 09:45:02 2011] [error] [client 127.0.0.1] PHP Fatal error:  Call to a member function getPrimaryKey() on a non-object in D:\\localhost\\modx-id.com\\core\\model\\modx\\modaccessibleobject.class.php on line 26, referer: http://localhost/modx-id.com/manager/index.php
</pre>

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/9f511dd2a65dcbfdf45d688efd3dee617fc526b5
