### ISSUE TITLE
Tinymce spellchecker plugin files incomplete from package management

### ISSUE THREAD

**Issue by andybaughman** [modxbot/migrate#3471]
andybaughman created Redmine issue ID 3471

Not sure if this is a modx or tinymce issue, but the files included in the tinymce 4.1.2 package management download (specifically 'assets/components/tinymce/jscripts/tiny_mce/plugins/spellchecker') are incomplete. After downloading the PHP Spellchecker plugin from http://tinymce.moxiecode.com/download/download.php and replacing the 'assets/components/tinymce/jscripts/tiny_mce/plugins/spellchecker' folder with the new files, the spellchecker plugin works.

**Comment by MarkH** [comment]
markh submitted:

I can verify this. I added the steps needed to enable the spellchecker to the RTFM a short while ago: http://rtfm.modx.com/display/ADDON/TinyMCE.Spellchecker

**Comment by splittingred** [comment]
splittingred submitted:

This is a TinyMCE issue; whereas this tracker is for MODX core issues only. Closing.
