### ISSUE TITLE
Cannot give my own admin user group the Admin access policy

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#3489]
onepack created Redmine issue ID 3489

Admin policy is not listed in the dropdown list to select at "Resource Group Access" and so I cannot give my own administrator the admin access policy.

In two other sites where I didn't touch anything with the rules it's listed as "Access Policy" 2 BUT clicking the dropdown doesn't show it and so it's not selectable in that list.

Only: Load - load, list and view - object - resource. Only these are available in 4 of my web projects. Nowhere "Admin" is to be found!

This way one of my projects became not-editable because I cannot see my elements tree anymore.

**Comment by onepack** [comment]
onepack submitted:

Setting it in the database: mod_access_resource_groups the policy to 2 for my usergroup makes the usergroup have "Administrator" displayed in the access policy again but until now the element tree files are still not viewable.

**Comment by onepack** [comment]
onepack submitted:

Changing the database policy to 2 (administrator) for my admin user group in table: modx_access_category solved the fact that I clouldn't see anything in the elements resource tree.... I don't know if It was my mistake in the first place but the fact that I see the same problem on my other projects makes me think this is a bug.

**Comment by opengeek** [comment]
opengeek submitted:

I think this may be a misunderstanding, as the Administrator policy should never be assigned to a Resource Group or Category ACL. Those should only be available on Context ACLs.

Otherwise, I cannot reproduce this problem.

**Comment by onepack** [comment]
onepack submitted:

I'm getting confused here as well... Lets start with the element-category-access tab.
I used to be able to set a category to be only accessible for Administrators. I need this to hide some templates for standard editors.

Before I would assign these templates to category Admintemplates with Access Policy Administrator. 

This worked before but after an upgrade the list doesn't show Administrator and any custom access-policies anymore.
How can I hide these Admintemplates from standard editors now?

The same for resource-group-access. Before I could assign all available access policies and now they are gone... If this is the way it is supposed to work that's fine but for element-category-access it seems very strange that I'm not able to assign a category to the administrator access policy.

Maybe I just lost it ;-)

**Comment by opengeek** [comment]
opengeek submitted:

Right, you were using policies not intended for the target of your ACL. You should be using a policy derived from the Element Policy Template or Resource Policy Template respectively. The Administrator access policy is for Context ACLs only; it defines what actions a user is allowed to take in a specific Context.

**Comment by onepack** [comment]
onepack submitted:

Thank you for your time! I will check again how to solve this then in a proper way. 
And as I understand, it was a bug that I was able to assign these rights before.
