### ISSUE TITLE
Adding 'Slidebar/Range' Input Type.

### ISSUE THREAD

**Issue by gOmp** [modxbot/migrate#3490]
gOmp created Redmine issue ID 3490

Examples of sliders (Ext JS): http://dev.sencha.com/deploy/dev/examples/slider/slider.html
I Think the most suitable would be the "Slider with tip" example.

Instead of using workarounds like: (GenerateNumList Snippet)
http://modxcms.com/forums/index.php/topic,59718

see also:
http://modxcms.com/forums/index.php?topic=59204.0

**Comment by splittingred** [comment]
splittingred submitted:

We won't do this in the core, due to the problems with the slider widget for ExtJS. Someone can make an Extra for it though.
