### ISSUE TITLE
Dashboard should save it's panel positions

### ISSUE THREAD

**Issue by gadgetto** [modxbot/migrate#3501]
gadgetto created Redmine issue ID 3501

It would be nice if the MODx Revolution dashboard (manager home page) could save it's panel states: position and opened / closed state.

**Comment by gadgetto** [comment]
gadgetto submitted:

With "panels" I meant the boxes which holds the MODx News, Security Informations, Last Dokuments, Online, ...

**Comment by splittingred** [comment]
splittingred submitted:

Fixed through Dashboards in 2.2..
