### ISSUE TITLE
tree_default_sort - by alias please :)

### ISSUE THREAD

**Issue by AESmith** [modxbot/migrate#3535]
aesmith created Redmine issue ID 3535

Original Post: http://modxcms.com/forums/index.php/topic,53102.msg340301.html#msg340301

Just noticed I can set System Setting "resource_tree_node_name" to "alias" but then I cant seem to set "tree_default_sort" to sort by "alias". You can set it to "alias" but since it is not one the the previously defined values in the "Show Sort Settings" of the manager resource tree it appears to make no diff.

This is most helpful when you are the developer or more familiar with the structure vs the meta info. Page Titles can change with SEO all the time and the ability to list by a known constant (or more constant for sure) would be great.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed; https://github.com/modxcms/revolution/commit/a909aa177ea4cf7b51eb18e0842748f36050e7b0
