### ISSUE TITLE
Filemanager_path and user settings

### ISSUE THREAD

**Issue by odeclas** [modxbot/migrate#3546]
odeclas created Redmine issue ID 3546

I have tried applying a restrictive filemanager_path to users in Revo 2.0.7 but neither a custom access policy user nor the admin user seem to take any notice of the setting. Applying the same value at the System setting does result in restricted view of Files directory.

I have also tried the deprecated rb_base_dir for users with same non-effect.

**Comment by odeclas** [comment]
odeclas submitted:

Apologies - this is a duplicate of [[3427]]

**Comment by splittingred** [comment]
splittingred submitted:

Duplicate of #3427
