### ISSUE TITLE
Property Set: List Item: Name/Values reversed

### ISSUE THREAD

**Issue by debussy** [modxbot/migrate#3552]
debussy created Redmine issue ID 3552

To recreate:
- Create a property for a snippet/chunk
  >\* set property type to list
  >\* create the list, i.e., name:value = a:1, b:2, c:3
- drag the created snippet/chunk into document to add
- in the resulting pop-up window, instead of showing a list with the names (a,b,c) the values are shown (1,2,3).

Which field is shown (name or value) also seems to be inconsistent when managing properties on a snippet/chunk

**Comment by splittingred** [comment]
splittingred submitted:

Awaiting integration: https://github.com/modxcms/revolution/pull/93
