### ISSUE TITLE
Context not added to tv-image on reload

### ISSUE THREAD

**Issue by rubenk** [modxbot/migrate#3569]
rubenk created Redmine issue ID 3569

When selecting an image as a template variable in a context with an own file_manager_path/url (eg assets/contexta/images/), after saving the context parameter (&wctx=contexta) isn't added to the preview image URL. 

Also, while this is a nice feature to hide the actual path of the context files, how do outputfilters have to know what context they have to use? I use the phpthumbof outputfilter, but this filter uses the path after the file_manager_path/url to try to use the image, which obviously fails.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in 2.1 commits, found in merge here: https://github.com/modxcms/revolution/commit/ff0d004ae327e6a357ca57680c083ac6bf3ccc4c
