### ISSUE TITLE
image tvs outputting path when empty

### ISSUE THREAD

**Issue by g5604** [modxbot/migrate#3571]
g5604 created Redmine issue ID 3571

After I add an image to an image tv and then delete it, part of the path (as set in the file settings) remains. 

before any changes to the tv:
output = nothing

after choosing image:
output = assets/resources/images.my.jpg

after adding image and then deleting it:
output = assets/resources/

my file settings look like this

filemanager_path:  assets/resources/
filemanager_url: assets/resources/

the problem goes away if you leave both of the options blank and use the full file tree.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in 2.1 commits, found in merge here: https://github.com/modxcms/revolution/commit/ff0d004ae327e6a357ca57680c083ac6bf3ccc4c
