### ISSUE TITLE
Call to a member function get()

### ISSUE THREAD

**Issue by ghost** [modxbot/migrate#3599]
blr created Redmine issue ID 3599

i duplicate the original context.
i add access control at tis new context (see the png file).
When i valid, i can see in the apache log :

[Sun Jan 23 20:41:59 2011] [error] [client 127.0.0.1] PHP Fatal error:  Call to a member function get() on a non-object in C:\wamp\www\modx-2.0.7-pl\core\model\modx\processors\security\access\getlist.php on line 69, referer: http://localhost/modx-2.0.7-pl/manager/?a=5&key=newsite

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/cc36097216dd16dc2c0245895094a2c89551f5aa
