### ISSUE TITLE
no confirmation dialog on template change

### ISSUE THREAD

**Issue by aceman3000** [modxbot/migrate#3601]
aceman3000 created Redmine issue ID 3601

If I create a new ressource, the first thing I usually do is to change the assigned template. There is a modal dialogue which askes if I am sure. But that is obsolete. Why ask me for that? This is a new document so no data loss is expected.
Even if it is an existing document the only thing that seems to happen to me is that the tab "template variables" gets another content. There is no data loss if i switch between templates back and forth. The template var contents are still there.
So why ask the user if he is sure?

**Comment by splittingred** [comment]
splittingred submitted:

Awaiting integration: https://github.com/modxcms/revolution/pull/71

**Comment by opengeek** [comment]
opengeek submitted:

Integrated into develop for 2.1.0-rc1
