### ISSUE TITLE
runSnippet not working with [[*parent]]

### ISSUE THREAD

**Issue by xpix** [modxbot/migrate#3610]
xpix created Redmine issue ID 3610

Hi,

I discovered that this works

$date = $modx->runSnippet('getResourceField', array(
    'id' => $modx->resource->get('parent'),
    'field' => 'StartDate',
    'processTV' => '1'
  ));

but this doesn't

$date = $modx->runSnippet('getResourceField', array(
    'id' => '[[*parent]]',
    'field' => 'StartDate',
    'processTV' => '1'
  ));

[[*parent]] is not parsed. If this is the intended behavior than ignore this post

**Comment by splittingred** [comment]
splittingred submitted:

That is intended behavior - you can't just place Resource placeholders in a runSnippet call.
