### ISSUE TITLE
Output-Filter :cdata adds unwanted whitespace

### ISSUE THREAD

**Issue by XoD** [modxbot/migrate#3612]
xod created Redmine issue ID 3612

Every textblock in a TV with outputfilter :cdata has whitespace at the beginning of the line...I had a look into the core "core/model/modx/filters/modoutputfilter.class.php" and there was the problem, the whitespace is already in the code, I changed it to:

<pre>

                    case 'cdata':
                        $output= "<![CDATA[{$output}]]>";
                        break;
</pre>

and now the problem is gone...I think this sould be changed in the next version, it's done in 2 seconds (finding the file where the output filters are in took longer than the fix)

**Comment by splittingred** [comment]
splittingred submitted:

Awaiting integration: https://github.com/modxcms/revolution/pull/60

**Comment by opengeek** [comment]
opengeek submitted:

Integrated into develop for 2.1.0-rc1
