### ISSUE TITLE
getUserDocGroups doesnt work on other context

### ISSUE THREAD

**Issue by u007** [modxbot/migrate#3615]
u007 created Redmine issue ID 3615

I found out that the function modx->getUserDocGroups() does not work properly on other context.
I would like to suggest to change the line:
if ($this->isFrontend() && isset ($_SESSION['webDocgroups']) && isset ($_SESSION['webValidated'])) {

to:
$sContext = is_object($modx->context)? $modx->context->get("key"): "web";
if ($this->isFrontend() && isset ($_SESSION[$sContext.'Docgroups'])) {

issues:
- frontend may consists of other context, therefore using active context 
- inconsistant "web"Validated as this is not assigned on login of other context

**Comment by u007** [comment]
u007 submitted:

Sorry, the new code propose:
$sContext = is_object($this->context)? $this->context->get("key"): "web";
if ($this->isFrontend() && isset ($_SESSION[$sContext.'Docgroups']) && isset ($_SESSION[$sContext.'Validated'])) {
   $dg= $_SESSION[$sContext.'Docgroups'];
   $dgn= isset ($_SESSION[$sContext.'DocgrpNames']) ? $_SESSION[$sContext.'DocgrpNames'] : false;

But also need to fix the login handler to add $sContext."Validated"=1 on login.

**Comment by u007** [comment]
u007 submitted:

By the way, im just wondering,
why do we need $_SESSION["webValidated"]?
Doesnt the log out suppose to wipe out $_SESSION["webDocGroups"] as well?

please advice, thank you :)

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/f99259c0ed7478e0e0bcf8091936039226388678

$modx->getUserDocGroups will be deprecated in 2.1; you'll be able to use the fixed $modx->user->getResourceGroups()

**Comment by u007** [comment]
u007 submitted:

Hi Shaun,

this is to return resource groups ID, not name.
Please fix the comments in the function.
thank you.
