### ISSUE TITLE
TV content removed on template change

### ISSUE THREAD

**Issue by jbeach** [modxbot/migrate#3622]
jbeach created Redmine issue ID 3622

When multiple templates share a TV, if that TV has content in it, then you change the template to another that also has that TV, that TV content is cleared on the template refresh, and if not caught that TV content will be deleted on save since it's now empty.

In addition, if you switch back to the original template before saving, that TV content continues to be empty.

**Comment by opengeek** [comment]
opengeek submitted:

This definitely needs to be addressed as soon as possible.

**Comment by splittingred** [comment]
splittingred submitted:

Maybe related to code around line 225 on modTemplateVar.setValue:

<pre>
elseif (!$templateVarResource->isNew()
                  && ($value === null || $value === $this->get('default_text'))) {
  $templateVarResource->remove();
}
</pre>

Might be related to [#3353], where the value isn't getting stored if it's null or the default value.

**Comment by jbeach** [comment]
jbeach submitted:

not sure if Shaun's reply is an internal note, but thought I'd mention that in my case it's when the TV is a unique value, not the default or null.

In fact, since this is kind of an old bug, I thought I'd check its behavior in 2.0.8pl (trad) - it has a new quirk that makes me wonder if it's not a TinyMCE issue, or the way The TV category tabs are outputted.  Here are the steps:
1. Open resource for edit
2. Change template (to template that shares similar TV's)
3. Check TV's (all TV's intact, except RichText fields which are all empty - good TV's include text field, dropdown, checkbox, image)
4. Switch back to original template
5. Check TV's (TV category tabs are now all missing, so all TV's are lumped together.  What's weird here is now the RichText data is displayed, but in a very tiny textarea rather than RichText editor (with all the TinyMCE buttons).
6. Now switch to template (from #2), and you get the behavior in #5.

If you'd like, I'd be happy to let you check it in active manager - the website is http://www.ecolifefoundation.org

Thanks guys!
Justin

**Comment by jbeach** [comment]
jbeach submitted:

should clarify, the above behavior happens with FF 3.6.15.

**Comment by opengeek** [comment]
opengeek submitted:

This was fixed for 2.1.0-rc1—see commit details at https://github.com/modxcms/revolution/commit/8000aceeb435b70c7d587fae3b01fc4c260a0714
