### ISSUE TITLE
Can't create empty option for dropdown and list TVs

### ISSUE THREAD

**Issue by Qowyn** [modxbot/migrate#3636]
Qowyn created Redmine issue ID 3636

If you try to create an empty option for dropdown and list tvs the label of that option becomes its value.

Reproduce:

Create a dropdown TV "myTV" with the following value:

<pre>Empty==</pre>

Use the TV somewhere:

<pre>[[*myTV]]</pre>

It will display its value as "Empty" instead of "" (empty String).

**Comment by Qowyn** [comment]
Qowyn submitted:

Bug seems to be in

<pre>
core/model/modx/processors/element/tv/renders/mgr/input/dropdown.php
core/model/modx/processors/element/tv/renders/mgr/input/listbox.php
core/model/modx/processors/element/tv/renders/mgr/input/listbox-multiple.php
</pre>

The following line makes it impossible to have empty values:

<pre>
<code class="php">
if (strlen($itemvalue)==0) $itemvalue = $item;
</code>
</pre>

**Comment by splittingred** [comment]
splittingred submitted:

Awaiting integration: https://github.com/modxcms/revolution/pull/85
