### ISSUE TITLE
TV's not showing in Manager in IE7

### ISSUE THREAD

**Issue by vitalized** [modxbot/migrate#3637]
vitalized created Redmine issue ID 3637

As you'll see in the attached screen shot some custom TV's aren't showing in the Manager when using IE7 and sometimes on IE8.
My PC and my clients PC's (3 Windows XP & Vista boxes) all have the same issue.

The issue has been around since 2.0.5. I was hoping the updates may fix the issue but it's still prevalent in the latest 2.0.7

_Example TV setup:_
TV name:  EventStartTime
Input Type: Text
Input Option Values: Empty
Default Value: Empty
Output Type: Default

TV name:  EventStartTime
Input Type: Date

**Comment by vitalized** [comment]
vitalized submitted:

Sorry, my bad... use this example TV

_Example TV setup:_
TV name: EventStartTime
Input Type: Date
Input Option Values: Empty
Default Value: Empty
Output Type: Default

**Comment by onepack** [comment]
onepack submitted:

Hi there. This was reported before in case #3498: Rendering issues IE7

You can minimize and maximize the panel to make the tabs show their content in IE7 as a workaround for now.

**Comment by splittingred** [comment]
splittingred submitted:

Duplicate of #4111
