### ISSUE TITLE
Add a base URL prefix to the help URLs

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#3641]
bobray created Redmine issue ID 3641

If there were a base_help_url System Setting, the help urls in the language files could be just resource/create, resource/update, etc.

That way, users could create their own complete help systems and connect them just by changing the system setting without having to edit multiple language files.

**Comment by splittingred** [comment]
splittingred submitted:

Awaiting integration: https://github.com/modxcms/revolution/pull/94
