### ISSUE TITLE
Date selector in Template Variable causes problem with manager page in IE8

### ISSUE THREAD

**Issue by lexiconlondon** [modxbot/migrate#3658]
jimbob72 created Redmine issue ID 3658

Using the Date input type in a TV (with Output Default) causes the associated Resource manager page to load incorrectly in IE8 and generate a javascript error . Also, the Date field is wiped and will not resave.

Error details:

_Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; MDDC; .NET CLR 1.1.4322; .NET4.0C; .NET4.0E)

Message: Invalid argument.
Line: 7
Char: 30669
Code: 0
URI: http://www.seemore-indices.com/manager/assets/ext3/ext-all.js

Message: Could not complete the operation due to error 80020101.
Line: 7
Char: 79522
Code: 0
URI: http://www.seemore-indices.com/manager/assets/ext3/ext-all.js_

This error is NOT replicated in Firefox or Chrome.

**Comment by lexiconlondon** [comment]
jimbob72 submitted:

This is still happening in Revolution 2.0.8

**Comment by splittingred** [comment]
splittingred submitted:

Duplicate of #4111
