### ISSUE TITLE
Revo: Quick Update: Keep Open After Save

### ISSUE THREAD

**Issue by debussy** [modxbot/migrate#3673]
debussy created Redmine issue ID 3673

When doing editing on multiple snippets, chunks, and pages, Quick Update is the _quickest_ way to go (groan), but it would be nice if one could edit and save without having to constantly reopen the Quick Update windows.

By default, I believe that their behavior should be as it is now (close on save), but perhaps there could be a checkbox in the upper right with the other window/frame controls that, when checked, keeps the window open on save. ...or, perhaps even easier, just add a button to the bottom: [Cancel] [Save] [Save & Close]

**Comment by splittingred** [comment]
splittingred submitted:

Awaiting integration: https://github.com/modxcms/revolution/pull/62

**Comment by opengeek** [comment]
opengeek submitted:

Integrated into develop for 2.1.0-rc1
