### ISSUE TITLE
Access Policy - new_document_in_root

### ISSUE THREAD

**Issue by theuros** [modxbot/migrate#3692]
theuros created Redmine issue ID 3692

i denied new_document_in_root, and it works fine, but you can create a resource somewhere else and then drag it to the root level.

**Comment by theuros** [comment]
theuros submitted:

doesn't work on version: MODx Revolution 2.0.7-pl (traditional)

**Comment by opengeek** [comment]
opengeek submitted:

See commit details at https://github.com/modxcms/revolution/commit/4ca9b5e93e6be9eeaa08a20a65fb19a920275deb
