### ISSUE TITLE
Content disposition logic in static resource reversed (and patch)

### ISSUE THREAD

**Issue by alito** [modxbot/migrate#3693]
alito created Redmine issue ID 3693

The patch should make it clearest.  Content disposition is being set to 'inline' when the content_dispo is set to 1, which means attachment, and the reverse.  There seem to be a couple of problems with static resource serving, but this is the most obvious one.  This appears to exist in Revolution-2.0.7 and revolution svn trunk (not sure if they are the same).
# Index: modstaticresource.class.php

--- modstaticresource.class.php (revision 7221)
+++ modstaticresource.class.php (working copy)
@@ -147,7 +147,7 @@
                 }
                 $header= 'Cache-Control: public';
                 header($header);
-                $header= 'Content-Disposition: ' . $this->get('content_dispo') ? 'inline' : 'attachment' . '; filename=' . $name;
-                $header= 'Content-Disposition: ' . $this->get('content_dispo') ? 'attachment' . '; filename=' . $name : 'inline';
               header($header);
               $header= 'Vary: User-Agent';
               header($header);

**Comment by opengeek** [comment]
opengeek submitted:

Confirmed this is indeed reversed and I am researching to make sure the patch is the proper solution. I believe the tertiary statement is actually reversed AND improperly grouped. Doing some testing in various browsers...

**Comment by opengeek** [comment]
opengeek submitted:

Fix committed as https://github.com/opengeek/revolution/commit/efd81d3d23abb2037c941c3b4f543397510d4b16.
