### ISSUE TITLE
Files tab: Dragging files 

### ISSUE THREAD

**Issue by eerne** [modxbot/migrate#3702]
eerne created Redmine issue ID 3702

Dragging files from the Files tab _broke_ for:
- dragging into a directory (in the Files tab)
- dragging files (.jpg or .png) onto Image TV

Dragging files onto a Text TV works correctly.

On FireFox 3.6.14 Safari 5.0.3, there is no JavaScript error.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed TV issue in https://github.com/modxcms/revolution/commit/4aa3ecef3303154c0b0e77ddde1e7096e519b592

However, drag/dropping files into directories in the Files tree is not currently a feature of MODX Revolution.

**Comment by gadamiak** [comment]
gadamiak submitted:

Shaun McCormick wrote:

> However, drag/dropping files into directories in the Files tree is not currently a feature of MODX Revolution.

How can user move files and folders then? By re-uploading them? I noticed it's not available after upgrade to 2.1-pl but thought it's a bug. But no, in 2.0.8-pl it's disabled too.
