### ISSUE TITLE
Inconsistent treatment of combo-boolean element properties in DB!

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#3716]
bobray created Redmine issue ID 3716

When combo-boolean element properties are created, They are stored in the DB as strings: s:1:"0" and s:1:"1". When they are changed in the Manager and the element is saved, they become booleans: b:1  and b:0.  

This is serious because a test of the scriptProperties member in code using === '1' or ==='0' may succeed after installation but fail after the user changes the value of the property. Tests for === false and === true will work only with properties whose values have been changed in the Manager. This could explain a number quirks with add-ons that are hard to reproduce because they won't occur unless the property values are changed in the Manager.

New properties are saved as strings both when a new combo-boolean property is created in the Manager, and when a package is installed (regardless of whether the value is set to '0' or false, '1' or true in the property array).

**Comment by garryn** [comment]
garryn submitted:

Fixed.

https://github.com/modxcms/revolution/commit/1b05a8e6ba4978ee1de0d1997404b05c7de7714f
