### ISSUE TITLE
Curl Proxy settings missing from transferPackage

### ISSUE THREAD

**Issue by terkkila** [modxbot/migrate#3740]
terkkila created Redmine issue ID 3740

Curl does not have all of the options set in modtransportpackage.class.php
The package manager will be unable to download files until these are set.
Our suggestion:

curl_setopt($ch, CURLOPT_PROXY, $this->xpdo->getObject('modSystemSetting', array('key' => 'proxy_host'))->value);

curl_setopt($ch, CURLOPT_PROXYPORT, $this->xpdo->getObject('modSystemSetting', array('key' => 'proxy_port'))->value);

Note: these values must be added to the system settings too

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/6b6229de56ea2d4cea9c8ed11c95a010981b174f
