### ISSUE TITLE
Recursive parent setting is possible

### ISSUE THREAD

**Issue by kurucu** [modxbot/migrate#3754]
kurucu created Redmine issue ID 3754

One of my clients was able to save a page as a child of one of its own children. I believe that this was done by clicking the resource to edit, then changing parent, and choosing one of its children.

While the GUI may have checks built in for this, the problem was still committed to the database (something to check server side?) which lead to:
- Front end: 500 premature end of script error
- Manager: All ok, except resource tree not loading

I resolved it by reselecting the parent in the database and then clearing the cache in the manager.

**Comment by splittingred** [comment]
splittingred submitted:

Awaiting integration: https://github.com/modxcms/revolution/pull/69

**Comment by opengeek** [comment]
opengeek submitted:

Integrated into develop for 2.1.0-rc1
