### ISSUE TITLE
Option "Rich Text" also affects Rich Text TVs 

### ISSUE THREAD

**Issue by mindeffects** [modxbot/migrate#3776]
mindeffects created Redmine issue ID 3776

Turning off the "Rich Text" option, also turnes all rich text tvs to text mode. I allways thought, that this option would ONLY affect the content!

When I decide to use rich text TVs (and not text areas) I would expect them to be displayed allways as rich text, because that is what they were ment to be. Having a poor text content and still being able to have richt text tvs would be realy nice and handy in some situations when one exactly needs that.

So I don't no if that's a "bug" or a "feaure". ;-)

**Comment by mindeffects** [comment]
mindeffects submitted:

Oh, my fingers! Again: So I don't know if that's a "bug" or a "feature". ;-)

**Comment by splittingred** [comment]
splittingred submitted:

This is more an issue with TinyMCE. Closing here.
