### ISSUE TITLE
Divide Template Variables into categories when editing a template

### ISSUE THREAD

**Issue by debussy** [modxbot/migrate#3785]
debussy created Redmine issue ID 3785

There should be some method by which one could sort or view TVs by their assigned category when on the Template Variables tab in the Template Manager. 

Probably just a sortable Category Column on the existing list would suffice.

**Comment by splittingred** [comment]
splittingred submitted:

Added, along with a search box as well: https://github.com/modxcms/revolution/commit/ca280a43972d11fd38c07ba8b470a7f761847ab1
