### ISSUE TITLE
italian translation

### ISSUE THREAD

**Issue by pandro** [modxbot/migrate#3849]
pandro created Redmine issue ID 3849

I send you the italian translation both of the core and of the setup, 
thanks!
Alessandro

**Comment by pandro** [comment]
pandro submitted:

Italian translation checked for revolution 2.0.8

**Comment by splittingred** [comment]
splittingred submitted:

Done in: https://github.com/modxcms/revolution/commit/90f6fc4e51b0455192191c6974892e6f1d33aa8a

Can you update the lexicons to 2.1.0? Thanks!
