### ISSUE TITLE
TinyMCE not automatically wrapping a <p> tag around new content

### ISSUE THREAD

**Issue by Martijn1981** [modxbot/migrate#3864]
Martijn1981 created Redmine issue ID 3864

Revolution's TinyMCE editor doesn't behave the same way as Evolution's editor does. A <p> tag isn't automatically wrapped around any text. We need at least the TinyMCE parameter "forced_block_root" present in the Revo manager, so we can modify this behavior whenever needed. See this Tiny WIKI page for example: http://wiki.moxiecode.net/wiki.php/Configuration:forced_root_block.

**Comment by splittingred** [comment]
splittingred submitted:

TinyMCE issues need to go in TinyMCE issue queue.
That said, this is fixed in latest TinyMCE.
