### ISSUE TITLE
post db driver in package mgmt REST queries

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#3872]
netprophet created Redmine issue ID 3872

We will likely need at some point to designate what db drivers a package is compatible with (tested against), and have providers return packages to Package Management that are compatible with the install in question.
(For example, if ExtraX works in MySQL but not in SqlSrv, we may not want it to be visible and/or downloadable and/or installable in a SqlSrv environment.)

**Comment by splittingred** [comment]
splittingred submitted:

FYI, the name of the key sent should be: 'database'

**Comment by splittingred** [comment]
splittingred submitted:

https://github.com/modxcms/revolution/commit/5fcbd797be72b5f3a0d2e942bf6a6209ce742317
