### ISSUE TITLE
UserSettings not overwrite systemSettings.

### ISSUE THREAD

**Issue by Fi1osof** [modxbot/migrate#3886]
fi1osof created Redmine issue ID 3886

_UserSettings not overwrite systemSettings._
Problems in SESSIONS and WRONG CONTEXTS.

_Description_:"
SystemSettings: 'filemanager_path: assets/'

My userContext: context_1 (not 'web') 
My UserSetting: 'filemanager_path: assets/files/'

I want overwrite SystemSetting by my UserSettings. But this not working. print_r($modx->user->UserSettings) is empty array;
"

_Cause:_ "
modx.class.php  str. 977:  public function getUser($contextKey= '',$forceLoadSettings = false)

_Error_: (commented)

'

 if ($this->user !== null && is_object($this->user)) {
            // Wrong Context Check
            // If  This commented, UserSettings do initialize
            /_if ($this->user->hasSessionContext($contextKey) || $forceLoadSettings) {
                if (isset ($_SESSION["modx.{$contextKey}.user.config"])) {
                    $this->_userConfig= $_SESSION["modx.{$contextKey}.user.config"];
                } else {_/
                    $settings= $this->user->getMany('UserSettings');
                    if (is_array($settings) && !empty ($settings)) {
                        foreach ($settings as $setting) {
                            $v= $setting->get('value');
                            $matches= array();
                            if (preg_match_all('~{(._?)}~', $v, $matches, PREG_SET_ORDER)) {
                                $matchValue= '';
                                foreach ($matches as $match) {
                                    if (isset ($this->config["{$match[1]}"])) {
                                        $matchValue= $this->config["{$match[1]}"];
                                    } else {
                                        $matchValue= '';
                                    }
                                    $v= str_replace($match[0], $matchValue, $v);
                                }
                            }
                            $this->_userConfig[$setting->get('key')]= $v;
                        }
                    }
               /_ }
                if (is_array ($this->_userConfig) && !empty ($this->_userConfig)) {
                    $_SESSION["modx.{$contextKey}.user.config"]= $this->_userConfig;
                    $this->config= array_merge($this->config, $this->_userConfig);
                }
            }*/

```
    }
```

'

"

**Comment by splittingred** [comment]
splittingred submitted:

Has already been fixed in 2.1.0 Git.
