### ISSUE TITLE
Context cache folder being deleted entirely after clearing site cache - causes 404s

### ISSUE THREAD

**Issue by bmilton** [modxbot/migrate#3889]
bmilton created Redmine issue ID 3889

Have a site with two contexts, the default 'web' and a second context.  Both sites are resolving for the home page and are hosted inside a shared CPanel account.
Whenever the site cache is cleared, the second context starts returning 404s for all pages.  No amount of clearing the browser cache or refresh will make it work.
However, if while logged into the ModX Manager I click on any resource underneath this context it will immediately start to resolve again.

After looking at the core/cache folder during this behavior I see the following:
1.  There is a subfolder underneath core/cache that matches the context name.  
2.  Whenever the site cache is cleared, this entire subfolder is deleted.
3.  When the subfolder is not present, the site does not resolve.
4.  When I click on a context resource in the manager, the subfolder is created again and the site works.

To resolve the two domain names I am using a plugin like below:
<?php
switch ($modx->getOption('http_host')) {

```
case 'www.domain2.com':
    $modx->switchContext('www.domain2.com');
    break;
default:
    $modx->switchContext('web'); 
    break;
```

}

**Comment by bmilton** [comment]
bmilton submitted:

Problem occurs on Revolution 2.0.7-pl

**Comment by wshawn** [comment]
wshawn submitted:

have you tried this in 2.0.8pl with its cache corrections?

**Comment by bmilton** [comment]
bmilton submitted:

Didn't realize that was released.  Will try it today.

**Comment by bmilton** [comment]
bmilton submitted:

Just checked this with 2.08pl and it is still a problem.

I am wondering why there haven't been any other reports of this.  Note that my context name includes the "." character in case this is an important point.
The behavior seems slightly different now in that the context specific cache folder is no longer being deleted.  There is a cache file that is still deleted when clearing the cache: \core\cache\www.mydomain.com\context.cache.php

When this file is gone, the site fails.  When I click on a resource under the context the file is re-created.

**Comment by opengeek** [comment]
opengeek submitted:

That's how the cache works—I guess I'm confused as to what you are saying the problem is. If it's about the way the cache works, this has been refactored for 2.1.0 already so that the config and context cache entries are never deleted, only updated during the cache refresh process.

But I cannot reproduce any issue with 404's with contexts when refreshing the cache. I think this might be related to how CPanel is handling the domain redirects, but I'm not sure.

**Comment by bmilton** [comment]
bmilton submitted:

The problem is that the add-on site context 404s the instant the site cache is cleared.  The default 'web' context continues to work fine.

I was just making observations about what I see happening with the cache folders.  I don't think it is a Cpanel issue because I first observed it in my Dev environment running a XAMPP service.  Did you try to reproduce this with a site context name containing '.' characters?  ex: "www.domain.com".  I'll try to retest mine with a different context name when I have a chance.

**Comment by bmilton** [comment]
bmilton submitted:

Ok, I've experimented with the context name.  There is no way to rename a context key, so I duplicated the context in it's entirety and changed the name.
I tested many variations of the key name without using a '.' character in the name.  All of them worked fine when clearing the cache.

Then I decided to duplicate my 'www.domain.com' named context and name it something else containing a '.' character. Not possible. I keep getting a validation error when I add a '.' to the name: "Please specify a valid key for the context".  I was also unable to duplicate a context and give it a name starting with a number.

If I create a brand new context, I can assign a name containing a '.' such as abc.test.123.  Can't start a new context name with a number though.

Short story...there are definitely some inconsistencies in naming behavior between creating a new context and duplicating a context and assigning  a new name.  Maybe you could tell me the requirements/expected behavior for context name validation and I can sort out what works and what doesn't?  Personally, I'd really like to be able to start a context name with a number and I'd like to be able to use periods as the domain name is a likely context name.

Thanks,
-Brian

**Comment by opengeek** [comment]
opengeek submitted:

The context key is used in places as a php variable and the validation is ensuring that the context key is a valid php variable, i.e. cannot start with a number of contain non-alphanumeric characters other than an underscore. This is scheduled for refactoring in releases post 2.1, so a context name can be presented using whatever characters you desire.

Otherwise, I still cannot reproduce this in latest develop branch when following the latest validation, so I'm marking this ticket resolved.
