### ISSUE TITLE
mail reset does not reset reply-to

### ISSUE THREAD

**Issue by robink** [modxbot/migrate#3920]
robink created Redmine issue ID 3920

When sending multiple messages at once in a loop. After each message I do '$modx->mail->reset()'

For some reason this does not work for '$mail->address('reply-to', 'some@address.tld')' The reply-to address is added to the reply-to address of the previous message.

See forum thread: http://modxcms.com/forums/index.php?topic=53703.0

**Comment by opengeek** [comment]
opengeek submitted:

Merged into develop for 2.1.0-rc1
