### ISSUE TITLE
Access policies get reset on upgrade

### ISSUE THREAD

**Issue by ghost** [modxbot/migrate#3936]
pms created Redmine issue ID 3936

I made an advance install of Revo 2.0.7-pl. I modified the access policy for Content Editors to allow them to publish and access the file manager so that they can insert images into documents. I then upgraded to 2.0.8-pl using the advanced installer. The access policies were reset to their new installation state. The customisations I had made were lost.

**Comment by mkschell** [comment]
netprophet submitted:

Please see comments in related ticket #3977
