### ISSUE TITLE
TV values for resources are reset to defaults when duplicating a context

### ISSUE THREAD

**Issue by bmilton** [modxbot/migrate#3941]
bmilton created Redmine issue ID 3941
# Setup a radio option tv with multiple options and a default setting.
# Create a context with at least one resource document and assign the tv to that document.
# Set the tv to a non-default option value.
# Right click on the context and "duplicate context", assigning a new name to the duplicate.
# Open the resource in the new context and check the tv value...it will be reset to default.

If duplicating a context, tv values should remain the same in my opinion.  At the least, there should be an option to keep tv values or reset to defaults.

A common use for site contexts that I see will be to setup an entire site template as a context.  Many tvs will be configured for styling, etc...  
To duplicate the entire site, you will duplicate the context and if the tvs are all reset then that will be a lot of work to go back through each resource and set the values.

**Comment by bmilton** [comment]
bmilton submitted:

This one is a real time killer when you are trying to duplicate a complex site context.  Hope this gets on the radar for the next release.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in: https://github.com/modxcms/revolution/commit/db5356550462bbfb0e6556f2935566a01975ee7a
