### ISSUE TITLE
Package management updates available

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#3946]
onepack created Redmine issue ID 3946

In the new version of package management I see that there is an upgrade available.
Clicking the "yes" upgrade link results in the message that I already have the latest version installed...
After clicking away the message the "upgrade" link available is still showing "yes".

This is in the latest version of modx 2.0.8-pl traditional
This is in more than one modx projects.
Browser: FF 3.6.13

See screenshot.

**Comment by splittingred** [comment]
splittingred submitted:

Should be fixed now.

**Comment by onepack** [comment]
onepack submitted:

Hi Shaun,

In what version will it be fixed? 1.0.9-pl? Where can I find the fix in Github?

Thanks!

**Comment by splittingred** [comment]
splittingred submitted:

It should be fixed automatically in your Revo installation.
