### ISSUE TITLE
Form customization - execute rules on template change

### ISSUE THREAD

**Issue by kenquad** [modxbot/migrate#3955]
kenquad created Redmine issue ID 3955

It would be very nice if form customization rules associated with "create" or "update" on a particular template would fire when that template is selected after creation of the resource.

Case in point:
Suppose that the blog section of my site consists of a resource called "blog" with a number of child resources, which are the posts.  The main blog page needs to use one template; the posts another.  I also have some special form customization rules to hide and move certain fields for blog posts.  Now by default, child resources inherit their parent's template.  I can change this with a form customization rule so that the posts default to use the correct template and not the template for the main blog page.  However, the field-related rules associated with the blog post template do not work in this case, until the resource has been saved and reopened.  This is extremely inconvenient.

**Comment by gerritvanaaken** [comment]
gerritvanaaken submitted:

This is a duplicate issue from http://bugs.modx.com/issues/2964
