### ISSUE TITLE
double slash url with custom filemanager_* settings

### ISSUE THREAD

**Issue by vertexer** [modxbot/migrate#3966]
vertexer created Redmine issue ID 3966

steps to reproduce:
- set filemanager root folder to assets subfolder by setting filemanager_path to "assets", filemanager_path_relative to "Yes", filemanager_url to "/assets" and filemanager_url_relative to "No"

result:
- filemanager access is restricted to the contents of the assets subfolder

bug:
- drag'n'drop an image file to resource content
- url is set to e.g. "/assets//foo/bar.jpg" in resource content (notice the double slash between assets and the actual file

expected result:
- url set to "/assets/foo/bar.jpg"

**Comment by vertexer** [comment]
vertexer submitted:

Bug still exists in MODX Revolution 2.1.0-rc3 (advanced)

**Comment by gadamiak** [comment]
gadamiak submitted:

I observe something related after upgrading from 2.0.8-pl to 2.1-pl however it's limited to preview in file tree.

I've got @filemanager_url@ set to @/content/@ and @filemanager_url_relative@ set to @No@. In 2.0.8-pl it works ok and preview is shown, but in 2.1-pl it's empty and in webserver log a 404 with a double slash path is shown. Changing @filemanager_url@ to @content/@ resolves it, but hey, that's no absolute anymore!

**Comment by garryn** [comment]
garryn submitted:

Fixed.

https://github.com/modxcms/revolution/commit/a34f57a4fee88e9adb66676c029e44e63387df8f
