### ISSUE TITLE
User rights dissapeared upon udate 2.0.7 to 2.0.8

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#3977]
onepack created Redmine issue ID 3977

I had a client sitting with me today and I was amazed when this user got a message that she was not permitted to see the image files in the modx browser window. She could see and work with them before. I remembered that I just updated the system a day ago to 1.0.8 so I went to check the user Access Controls and I saw that the Content Editor had the basic 16 out of 127 rights selected. Also the Admin lost a custom made right and had 126 out of 127 selected.

_Admin note_: updated versions from 1.x.x to 2.x.x

**Comment by onepack** [comment]
onepack submitted:

I really hope this can be fixed in the nearest release because it gives a lot of work checking all the user rights upon update.
Great work guys! Thanks.

**Comment by onepack** [comment]
onepack submitted:

There has not been any feedback on this issue.
This is a very serious bug when users loose their permissions and cannot even save a document after an upgrade.

**Comment by splittingred** [comment]
splittingred submitted:

We haven't been able to reproduce it, mostly. Can you provide more information about your policies, and what specific permissions were lost?

**Comment by onepack** [comment]
onepack submitted:

In this case I gave the users including myself a "standard" access policy. For instance. I have the Administrator policy and the user has Content Editor.
I never expected that if I "update the policies" from these standard access policies these adjustments would get lost on a system upgrade. This happened on all my current modx revo projects (5). Why would an admin be able to adjust these policies if it gets overwritten at every upgrade.

When an Administrator should not use these default policies make them read only, only available for copy and don't give the ability to "update" them when they get overwritten anyway.
This is a very confusing way of working because in other CMS solutions it is quite default to assign a user to a policy and adjust what this policy can.

**Comment by onepack** [comment]
onepack submitted:

This seems to be the same issue as: http://bugs.modx.com/issues/4223 mentioned by Nick

**Comment by opengeek** [comment]
opengeek submitted:

We agree it is not intuitive that the pre-installed default policies would be updated on core updates, but this is in fact the case, and we need to make the default policies uneditable (or at least display warnings/confirmation dialogs before taking the action) in the UI. I am changing this to an improvement ticket and re-scheduling for 2.1.1-pl.
