### ISSUE TITLE
plugin property sets not applied

### ISSUE THREAD

**Issue by Yoshix** [modxbot/migrate#3988]
yoshix created Redmine issue ID 3988

in 'core/model/modx/modx.class.php'
line '1365'

the code trys to find the propertyset name for a given plugin event.

It seems like $pluginPropset is initially set to: %pluginid%:%propertysetname%.

But the code in line '1365':

$this->event->propertySet= (($pspos = strpos($pluginPropset, ':')) > 1) ? substr($pluginPropset, $pspos + 1) : '';

will only work if the %pluginid% has at least two digits. So for plugins with ids <= 9, the code will not work.

**Comment by splittingred** [comment]
splittingred submitted:

This has already been fixed for 2.1: https://github.com/modxcms/revolution/commit/b845f3d0b1801850e0861f2b86c7e5cdd25503dd

Thanks!
