### ISSUE TITLE
Snippets & Chunks Not Working If In Categories

### ISSUE THREAD

**Issue by rossco** [modxbot/migrate#3989]
rossco created Redmine issue ID 3989

When installing packages that categorise chunks or snippets the snippets do not work.  

An example is the GoogleSitemap package that installs chunks and snippets in a category that does not appear to work at all.

When moving the snippets and chunks out of the category everything works fine.

This has happened on several sites using 2.0.7 traditional and seems to still be an issue in 2.0.8 traditional.  See this post http://modxcms.com/forums/index.php/topic,60682.0.html

I am signed in as super admin with no other usergroups or specific settings setup.  This appears to be a bug that I will consider critical as many users will assume the snippets do not work, like I did!  

Thanks.

**Comment by kenquad** [comment]
kenquad submitted:

In my case, the GoogleSiteMap chunks did not have to be removed from categories, just the snippet itself.  2.0.7 Traditional.

**Comment by splittingred** [comment]
splittingred submitted:

Erm, this definitely does not cause problems for me. I can use Snippets and chunks easily within categories. Perhaps a bug with GoogleSiteMap?
