### ISSUE TITLE
Better cdata output modifier

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#4012]
bobray created Redmine issue ID 4012

The current modifier is:

@$output= "<![CDATA[ {$output} ]]>";@

I think this would be better:

@$output= "\n" . '//<![CDATA[' . "\n" . $output . "\n" .  '//]]>' . "\n";@

I'm not sure about the newlines, but I think the comment tokens are necessary in some situations. If it would ever be used for CSS, it should probably use /\* */ comments instead.

**Comment by splittingred** [comment]
splittingred submitted:

I don't think we can do the comments; that would break CDATA usage in XML/YAML.

However, will look into newlines.

**Comment by splittingred** [comment]
splittingred submitted:

Decided against newlines, as this also would cause issues in some XML/YAML interpretations, and may have unwanted side effects. You can feel free to make your own custom output filter if needed.

Closing ticket.
