### ISSUE TITLE
When adding a new setting, the description text is not shown until page reloaded

### ISSUE THREAD

**Issue by ncrossland** [modxbot/migrate#4016]
ncrossland created Redmine issue ID 4016

To reproduce:
1. Create a new setting - e.g. create a plugin, unlock properties, create property
2. Add property details, including a description
3. Click "Done"
4. The property is added
5. Click the [+] icon on newly created property

The green panel is opened, but is empty of text. The page must be reloaded before the description text is visible.

**Comment by garryn** [comment]
garryn submitted:

Fixed.

https://github.com/modxcms/revolution/commit/7dfeeb0da91ba483cd17a919a1620e2021c10664
