### ISSUE TITLE
Manager Favicon

### ISSUE THREAD

**Issue by jswing83** [modxbot/migrate#4021]
jswing83 created Redmine issue ID 4021

I personally spend a lot of time in the MODx manager so I pin the browser tab so that it is always open.  When doing this, the title disappears and only the favicon is visible.  (This is in Chrome with similar results in other browsers.)

I put together the necessary code and images to add a favicon to the manager pages.

/manager/templates/default/header.tpl ~ line 7
/manager/templates/default/security/login.tpl ~ line 6
<link rel="shortcut icon" type="image/x-icon" href="assets/images/modx1.ico">

I noticed the redesign of the MODx homepage and the new MODx logo so I included two icon options.

**Comment by splittingred** [comment]
splittingred submitted:

Awaiting integration: https://github.com/modxcms/revolution/pull/79
