### ISSUE TITLE
Plugin property lists display value instead of label

### ISSUE THREAD

**Issue by ncrossland** [modxbot/migrate#4024]
ncrossland created Redmine issue ID 4024

When a plugin has properties of "list" type, there is an inconsistency between whether the dropdown's value or label is shown.

When a plugin properties sheet is first loaded, only the values are shown. After a value is edited, the label is shown. This is confusing for the user, and defeats the point of allowing a label.

e.g.

if a property has the options of:

<pre>
NAME    VALUE
One          1
Two          2
Three       3
</pre>

and "Three" has been previously selected as the current value, when the Plugin -> Properties page is loaded, it is displayed as

<pre>
3
</pre>

But if you double click it and change the value (e.g. to "2") it is now displayed as 

<pre>
Two
</pre>

If the point of having a label is to make it more user friendly, this is defeated by it being hidden on reload, as the user cannot review their setting in a human friendly way.

**Comment by splittingred** [comment]
splittingred submitted:

This is related to a bug with Ext Grids; where custom renderers with combos that have remote stores dont load their proper value.

**Comment by splittingred** [comment]
splittingred submitted:

Awaiting integration: https://github.com/modxcms/revolution/pull/84

Works here as there is no ajax loading of data, vs remote stores in certain grids.

**Comment by ncrossland** [comment]
ncrossland submitted:

I am still seeing this occuring in 2.1 RC3. Can you see whether you still see this issue?

**Comment by splittingred** [comment]
splittingred submitted:

Fixed here: https://github.com/modxcms/revolution/commit/5d8533478511b219905798975dc42773b089f71a
