### ISSUE TITLE
Plugin property list labels wrongly displayed after save 

### ISSUE THREAD

**Issue by ncrossland** [modxbot/migrate#4025]
ncrossland created Redmine issue ID 4025

After changing the value of a plugin property list, all properties that are lists incorrectly display the same value.

To reproduce:
1. Create a plugin which has several properties of type "list", and separate option names and values set in the property options.
2. Reload the plugin page, and change the value of one of the dropdowns by double clicking it on the property grid
3. Press "Save"

All property value labels now display the same (the label of the value you have just set).

e.g.

if each of the properties has 3 options

<pre>
NAME     VALUE
One         1
Two         2
Three      3
</pre>

Properties list:

<pre>
NAME           TYPE         VALUE
property1       list             3
property2       list             3
property3       list             1
property4       list             2
</pre>

Double click the value of property2, and change dropdown to "Two"

Click "save"

Property list now displays

<pre>
NAME           TYPE         VALUE
property1       list             Two
property2       list             Two
property3       list             Two
property4       list             Two
</pre>

but double clicking on a value reveals it's true value (e.g. double clicking property3 value reveals "One" selected in the dropdown).

**Comment by garryn** [comment]
garryn submitted:

Tested this but could not reproduce on the latest 2.2 branch, I suspect previous fixes surrounding the property grid have resolved this issue.
