### ISSUE TITLE
phpthumb doesn't support far

### ISSUE THREAD

**Issue by maciej-ludwinski** [modxbot/migrate#4042]
vartype created Redmine issue ID 4042

In /core/model/phpthumb/phpthumb.class.php on line 1366:
switch (strtoupper($this->_zc_)) {
should be:
switch (strtoupper($this->_far_)) {

Explanation:
$zc is bool value turning the ZoomCrop option on.
$far is string determining the alignment of a cropped image.

**Comment by splittingred** [comment]
splittingred submitted:

Awaiting integration: https://github.com/modxcms/revolution/pull/73
