### ISSUE TITLE
Add resource_tree_node_tooltip setting

### ISSUE THREAD

**Issue by ncrossland** [modxbot/migrate#4049]
ncrossland created Redmine issue ID 4049

You can currently choose which field is displayed as the name of a resource in the tree via the preference resource_tree_node_name

However the tooltip that is displayed is hard-coded to always display the longtitle.

It would be helpful if the choice of field to display for the tooltip was a setting to, to avoid duplication if the longtitle is selected for the resource_tree_node_name

**Comment by splittingred** [comment]
splittingred submitted:

Awaiting integration: https://github.com/modxcms/revolution/pull/72

**Comment by ncrossland** [comment]
ncrossland submitted:

Wow that was quick, thanks!

**Comment by gadamiak** [comment]
gadamiak submitted:

I know that's been implemented already, but it would be more useful if the tooltip could be composed of information required. I would like the tooltip to display something like:

<pre>longtitle (id)
editedon (editedby)
menuindex</pre>

**Comment by ncrossland** [comment]
ncrossland submitted:

Perhaps the tooltip content format could be optionally be defined as a chunk?

e.g. 

if the value is set to a field name such as longtitle, this value is used

if the field name is not recognised, a chunk with that name is retrieved, and used as a template for the tooltip. Placeholders within the chunk would define the content - for the example given by gadamiak the chunk would look like

[[ +longtitle]]([[+id]]) <br/>
[[ +editedon]]([[+editedby]]) <br/>
[[ +menuindex]]

If no chunk was found, no tooltip would appear.

(edit - the bugbase is mangling my Modx markup - but you get the idea!)
