### ISSUE TITLE
Make display of doc IDs in tree an option, customisable by role

### ISSUE THREAD

**Issue by ncrossland** [modxbot/migrate#4050]
ncrossland created Redmine issue ID 4050

For non-technical editors, the display of the document ID in the tree is unnecessary and confusing. When providing training to new users, it's always something that comes up as a question / point of confusion, as they often think it is a count of documents, or something else.

It would be very helpful if the display of these numbers could be made an option, which could be set on a "per role" basis. For example a superuser or developer role might wish to see them, but a content editor they could be hidden.

I'd propose the setting has options of "Show", "Hide" and a third option where the IDs only appear on mouseover, e.g. normally

[  ]  Resource title

Mouseover: 

[  ] Resource title (32)

Or on a tooltip. This would make the interface cleaner and easier to scan while still keeping the information available.

**Comment by splittingred** [comment]
splittingred submitted:

Done as a Permission, which can be turned off in a Policy.

Awaiting integration: https://github.com/modxcms/revolution/pull/95
