### ISSUE TITLE
JS error when importing plugin properties

### ISSUE THREAD

**Issue by ncrossland** [modxbot/migrate#4052]
ncrossland created Redmine issue ID 4052

When importing plugin properties, the import fails with a JS error leaving the progress bar cycling indefinitely.

To reproduce (ensure Firebug open first):
1. On plugin properties, click "Import properties"
2. Upload the attached file, which was created using "Export properties"

Progress bar opens, gets stuck - console says:

"missing ] after element list" - ext-all.js (line 7)

**Comment by splittingred** [comment]
splittingred submitted:

Awaiting integration: https://github.com/modxcms/revolution/pull/75
