### ISSUE TITLE
TinyMCE templates not working in Revo 2.0.7

### ISSUE THREAD

**Issue by kenquad** [modxbot/migrate#4059]
kenquad created Redmine issue ID 4059

See forum thread at [[http://modxcms.com/forums/index.php/topic,62076.msg353040.html#msg353040]] for details.  Since one user did get it working under his test environment, perhaps it's an issue that only shows up in certain server configurations.

**Comment by kenquad** [comment]
kenquad submitted:

Forgot to mention TinyMCE version: 4.2.1

**Comment by onepack** [comment]
onepack submitted:

Hi Jason... just wanted to let you know that all bugs not related to the core-modxcms system will be closed immediate with the message to file some in plugin/module related bugs in github. I remember TinyMCE related bugs can be assigend to splitting red.

**Comment by splittingred** [comment]
splittingred submitted:

onepack's right: ;)

http://github.com/splittingred/TinyMCE/issues/

Thanks!
