### ISSUE TITLE
site_sessionname/session_name did not works

### ISSUE THREAD

**Issue by lokamaya** [modxbot/migrate#4073]
lokamaya created Redmine issue ID 4073

Cookies always return default PHP session name: "PHPSESSID", no matter how I change the value of $site_sessionname on ../core/config/config.inc.php.

The bug was on ../core/model/modx/modx.class.php, function _initSession.

<pre>
//LINE 2843: always null
$site_sessionname= $this->getOption('session_name', '');
</pre>

_HINT:_
# Add global variable _$site_sessionname_ to/before line 2843 above.
# There is no _session_name_ key on System Event on fresh installation. Adding that key will solve the problem (but it's also will override $site_sessionname value provided config.inc.php).

_FURTHER DISCUSSION:_
Do we need session_name configured on system event or we only need one session name? If we only need one session name, so config.inc.php is sufficient. But having session_name on system event, will give the ability to change session name, for example, on each context.

Cheers,

**Comment by splittingred** [comment]
splittingred submitted:

Awaiting integration: https://github.com/modxcms/revolution/pull/97
