### ISSUE TITLE
Quick update inaccessible in element tree when inside category

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#4076]
gadamiak created Redmine issue ID 4076

Elements inside categories have "Quick Update" and "Edit" actions inaccessible. They are available only for elements outside of any category.

**Comment by splittingred** [comment]
splittingred submitted:

I have no problems using Quick Update or Edit in Elements in Categories.

Have you added any Element Category ACLs?
Or a file did not update correctly on your server?

**Comment by gadamiak** [comment]
gadamiak submitted:

I did in fact add this: @INSERT INTO `modx_access_category` (`id`, `target`, `principal_class`, `principal`, `authority`, `policy`, `context_key`) VALUES (1, '', 'modUserGroup', 1, 9999, 6, 'mgr');@. Notice that @target@ is empty, as I wanted to restrict access to all elements but those without a category only to Administrator user group.

**Comment by splittingred** [comment]
splittingred submitted:

Does removing that make it work again?

**Comment by gadamiak** [comment]
gadamiak submitted:

Yes, removing it made it work again.

The @target@ mentioned above came from selecting "none" from categories available. Should an "all" or "any" category be added for this kind of scenario?

**Comment by jrotering** [comment]
jrotering submitted:

"Have you added any Element Category ACLs?"

Is there a known issue with Element Category ACLs and Quick Update?  Sounds like the problem I'm seeing: [[ http://modxcms.com/forums/index.php/topic,62361.0.html]]

**Comment by gadamiak** [comment]
gadamiak submitted:

> The @target@ mentioned above came from selecting "none" from categories available.

Is "None" category a valid choice if this causes this problem? In fact, a category choice of "all" or "any" should be available instead or in addition to "none". And "none" should mean just that -- ie. elements without a category assigned.

**Comment by opengeek** [comment]
opengeek submitted:

I can reproduce this as well, any Elements that are listed within Categories that are protected by an ACL are not showing the Update or Quick Update Context menu items, regardless of the ACL permissions.

**Comment by opengeek** [comment]
opengeek submitted:

See commit details for resolution at https://github.com/modxcms/revolution/commit/471a6371b7d1d468388de4c3931817bed1cfc921
