### ISSUE TITLE
Add permission for using Quick actions

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#4077]
gadamiak created Redmine issue ID 4077

Quick Update and Quick Create actions in resource tree ignore form customization rules. As a result, users with set of fields for resources limited or altered by FC have full access to them through Quick action.

I guess it's possible that Quick modal windows apply FC, but simpler would be to add permission for using Quick actions. While not the most optimal and being a workaround, that would help fix the inconsistency.

**Comment by splittingred** [comment]
splittingred submitted:

Went the permission route, as FC rules on modal windows would be a nightmare.

Awaiting integration: https://github.com/modxcms/revolution/pull/96

**Comment by gadamiak** [comment]
gadamiak submitted:

I'm impressed by the speed of reaction! Thanks.
