### ISSUE TITLE
Add content type and content disposition select combos to Quick Create resource

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#4080]
gadamiak created Redmine issue ID 4080

The Quick Create resource modal window lacks content type selection combo. This makes Quick not so quick, as it requires editing the resource afterwards to set the content type.

The same applies do content disposition combo, which is required for at least static resources.

**Comment by garryn** [comment]
garryn submitted:

Added fields.

https://github.com/modxcms/revolution/commit/c8eddd285673af3c9e586080e02ca8ac6582e201
