### ISSUE TITLE
Super users access rights

### ISSUE THREAD

**Issue by theuros** [modxbot/migrate#4089]
theuros created Redmine issue ID 4089

I have multiple context on my site, and i accidently deleted access permission to one context in User Group Administrator ... i was unable to see that context on left menu and i couldn't restore permission to it.
I tryed to add permissions but in "User group access to context" i couldn't see that context in drop down menu.

I had to manually add entryes to database to regain access to that context ..

Admin users or default Super User must have all access rights all over modx .. regardless of access settings

**Comment by splittingred** [comment]
splittingred submitted:

This is mostly applicable; Admins are auto-added to contexts when created.
