### ISSUE TITLE
ensure check for colon char in xPDOTransport->pack() is Windows-safe

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#4096]
netprophet created Redmine issue ID 4096

pack() method contains the following

<pre><code lang="php">
        $pos = strpos($path, ':');
        if ($pos !== false) {
            $path = substr($path, $pos +1);
        }
</code></pre>

This has the effect of stripping a drive letter from a windows path, potentially making an "absolute path" from c: or whatever drive PHP is running on. This could be problematic if the path needs to be on a different drive.

**Comment by opengeek** [comment]
opengeek submitted:

This was an update merged from xPDO (see #4128) to resolve problems when packages are being zipped on Windows platforms where the installation is not on the c: drive.
