### ISSUE TITLE
Changing chunk content in OnBeforeChunkSave doesn't work

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#4122]
bobray created Redmine issue ID 4122

This plugin code to replace bad words with [expletive deleted] works perfectly with resources, but has no effect on chunks:

<pre>
$useWords = 'hell,damn','crap');
$replacement = '[Expletive Deleted'];

$words = explode(',',$useWords);
foreach($words as $k => $word) {
    $pattern[$k] = "/\b($word)\b/is";
    $replace[$k] = $replacement;
}
unset($words);

switch ($modx->event->name) {
    case 'OnBeforeDocFormSave':
        $resource->setContent(preg_replace($pattern, $replacement, $resource->getContent() ));
        break;
    case 'OnBeforeChunkFormSave':
       $chunk->setContent(preg_replace($pattern, $replacement, $chunk->getContent() ));
        break;
}
</pre>

For a simpler case, this has no effect in a plugin connected to OnBeforeChunkFormSave:

<pre>
$chunk->setContent('New Content');
</pre>

**Comment by BobRay** [comment]
bobray submitted:

Running the simple plugin above puts about 50 of these in the error log:

 [2011-03-20 02:39:26](ERROR @ C:xampphtdocsmodx208corexpdoxpdo.class.php : 1884) PHP warning: json_encode() [<a href='function.json-encode'>function.json-encode</a>]: recursion detected

**Comment by splittingred** [comment]
splittingred submitted:

Erm:

<pre>$useWords = 'hell,damn','crap');
$replacement = '[Expletive Deleted'];</pre>

Both lines would cause a parse error...

**Comment by splittingred** [comment]
splittingred submitted:

OOE was a bit off; events were running before the fromArray was called. 

Awaiting integration into develop: https://github.com/modxcms/revolution/pull/103
