### ISSUE TITLE
taglister appends &key=tags to URL

### ISSUE THREAD

**Issue by tommls** [modxbot/migrate#4140]
tommls created Redmine issue ID 4140

I posted on the forum before I found this bug reporting section.
It is not clear if this is a true bug or something I'm doing wrong.

http://modxcms.com/forums/index.php/topic,62548.0.html -- forum post

Taglister tolinks appends &key=tag to URLs, how to fix??
Using this code in blog/news post chunk as explained in MODx documentation:
http://rtfm.modx.com/display/revolution20/Creating+a+Blog+in+MODx+Revolution

[[+tv.news_tags:notempty=`| Tags2: [[!tolinks? &items=`[[+tv.news_tags]]`&target=`7`]]`]]

It doesn't matter if &key=`tag` is omitted or included or changed to &key=`news_tags`...

It always produces this kind of unusable URL:
http://foo/bar/news/?tag=test&key=tags

Clearing cache and restarting browser/xampp/apache has no effect.

This breaks tagging and I would really like to get tagging to work properly.

I notice only developers are in here...If I am not supposed to post here, please advise...

Thank you, Tom

**Comment by splittingred** [comment]
splittingred submitted:

TagLister issues should go in the TagLister error tracker. This is for Revolution core issues only.

http://github.com/splittingred/tagLister/issues/
