### ISSUE TITLE
unable to save chunk or template

### ISSUE THREAD

**Issue by ghost** [modxbot/migrate#4158]
gguenette created Redmine issue ID 4158

Unable to save chunk or template

When I save a chunk (same for templates) with no HTML, the chunk is saved and got msg "successfully saved"

When I enter random text "klasjdlfka" the chunk is saved and got msg "successfully saved"

When I put simple HTML code, saving progress bar appears then disappear with no error message... but the content is'nt saved.

Tried to modify htaccess, with no results

Any idea?

HTML Exemple:

<div></div>

or

<ul><li>A</li><li>B</li></ul>

**Comment by splittingred** [comment]
splittingred submitted:

Turn off PHP safe_mode or mod_security.
