### ISSUE TITLE
Revo Manager crashes in Firefox 4

### ISSUE THREAD

**Issue by Gallenkamp** [modxbot/migrate#4161]
gallenkamp created Redmine issue ID 4161

If a chunk or page contains an invalid html comment like <-- something --//>, the manager shows a blank page.
One can bypass it via rightclick "quick edit".
http://validator.w3.org/ helps finding the comments.

**Comment by splittingred** [comment]
splittingred submitted:

Cannot replicate on Mac.

**Comment by Gallenkamp** [comment]
gallenkamp submitted:

Wrong code....

try <!-- <span id="trashcan"></span> --//>

**Comment by Gallenkamp** [comment]
gallenkamp submitted:

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"  lang="de" xml:lang="de">

2.0.7-pl (traditional)

could also be TinyMCE, if i think twice. Version 4.2.0.pl

**Comment by splittingred** [comment]
splittingred submitted:

Does it happen if you disable TinyMCE?

**Comment by Gallenkamp** [comment]
gallenkamp submitted:

Right now my job is rather "fixing clients pages" as these chunks don't get rendered in the frontend.
Which - if I think again - points out that it can't be TinyMCE. Right?

**Comment by mkschell** [comment]
netprophet submitted:

I am unable to replicate in FF4 on Windows. However I do see related problems in IE8 and IE9
Bad HTML in the content field or other resource fields (but not TVs) triggers a javascript error on the Update Resource page.

**Comment by Gallenkamp** [comment]
gallenkamp submitted:

Strange... i see broken chunks in the frontend (chrome and ie even before fx4) but have to admit that I never used the manager in these two. They are only for "how does it look over there". Do you have TinyMCE installed?

**Comment by Gallenkamp** [comment]
gallenkamp submitted:

no, cant be related to "displaying". It must be related to "processing the chunk" maybe on cleaning the code. Because the "defective" chunks are missing in the frontend. Not the whole chunk, just the evaluated part (like i postet here: http://modxcms.com/forums/index.php/topic,62217.msg353681.html#msg353681)
The <a> part gets rendered, but with empty placeholders.

**Comment by wshawn** [comment]
wshawn submitted:

Make sure Firebug is disabled.  There is a bug which sounds remotely similar to your experience:

http://getfirebug.com/knownissues

**Comment by mkschell** [comment]
netprophet submitted:

Guido,
Sorry, I'm a little confused on the issue you're having then, as it relates to the Manager.
Do your manager pages still come up blank in FF4? Any issue related to chunk processing on the front end should be in another ticket.

**Comment by Gallenkamp** [comment]
gallenkamp submitted:

It appears to be gone with firebug deactivated. At least on my workstation.
