### ISSUE TITLE
2.1 Documentation Migrations

### ISSUE THREAD

**Issue by splittingred** [modxbot/migrate#4162]
splittingred created Redmine issue ID 4162

Duplicate the revolution20/ space to revolution21/

Some System Settings also need to be adjusted:
- _welcome_screen_url_ - Need to update to http://misc.modx.com/revolution/welcome.21.html
- _base_help_url_ - Need to update to http://rtfm.modx.com/display/revolution21/ from http://rtfm.modx.com/display/revolution20/ Can do this in the version-specific upgrade scripts (and the build for new installs), check for default value of http://rtfm.modx.com/display/revolution20/, and if set, update; otherwise, leave alone to allow custom help urls.

Also will need to issue out community notice on the Confluence space duplication.

**Comment by wshawn** [comment]
wshawn submitted:

Now if we could get rid of the "display"

http://rtfm.modx.com/revolution21/

Is much prettier and SEO friendly than

http://rtfm.modx.com/display/revolution21/
