### ISSUE TITLE
Output Filter date not show time

### ISSUE THREAD

**Issue by unglued** [modxbot/migrate#4169]
unglued created Redmine issue ID 4169

 Construction like [[+some_string:strtotime:date=`%d.%m.%Y %H-%i-%s`]] don't want show minutes and seconds
If some_string == 2011-03-12 13:56:31
then result will be: 12.03.2011 13-i-1299927391
See the test page http://salaska.ru/test/

**Comment by garryn** [comment]
garryn submitted:

The date output modifier actually uses strftime() to do the formatting. Please see the PHP manual for valid date formatting: http://php.net/manual/en/function.strftime.php
