### ISSUE TITLE
Output filter 'add' and intval() returns unexpected value

### ISSUE THREAD

**Issue by bertoost** [modxbot/migrate#4173]
bertoost created Redmine issue ID 4173

I try two values together with the 'add' output filter like this;

[[+number1:add=`[[+number2]]`]]

number1 = 9.95
number2 = 7.5

This should be 15.45 but the 'add' output filter uses intval() of php. (the filters substract, multiply, divide and mod also). This isn't what I expect and without the intval() it is working correctly. I understand why intval() is used, but there could be checkbox before the calculation or am I wrong?

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/86188a2d4c325abde7053162669685df3f36851d
