### ISSUE TITLE
Getting real IP and add it to session

### ISSUE THREAD

**Issue by lokamaya** [modxbot/migrate#4175]
lokamaya created Redmine issue ID 4175

First of all, sorry if this sugestion is not in place. I just found that there are so many addOn trying to get client IP address by it's own, also some core function like modmanagerrequest.class. So, why MODx did not provide one and add it into session variable? 

Anyway, sometimes REMOTE_ADDR does not provide the actual client IP. This could happen if the server (HOST) are behind firewalls or use applications such as Squid, and also could happen if client uses a proxy server (like Google WebAccelerator); then the IP obtained from the REMOTE_ADDR become the IP of the Firewall, Squid or user proxy server.

There are others variables like HTTP_X_FORWARDED_FOR, HTTP_CLIENT_IP, ect. But, if the requests come from many proxies, it's possible That the HTTP_X_FORWARDED_FOR contain comma separated IP addresses. The real client IP should be the first one.

Below are little function to determine client IP address.

<pre>
    function get_real_client_ip() {
        $ip = 'UNKNOWN';
        $ipAll = array();    //networks IP
        $ipSus = array(); //suspected IP

        $vars = array(
            'HTTP_X_FORWARDED_FOR',
            'HTTP_X_FORWARDED',
            'HTTP_X_CLUSTER_CLIENT_IP',
            'HTTP_X_COMING_FROM',
            'HTTP_FORWARDED_FOR',
            'HTTP_FORWARDED',
            'HTTP_COMING_FROM',
            'HTTP_CLIENT_IP',
            'HTTP_FROM',
            'HTTP_VIA',
            'REMOTE_ADDR'
            );
        
        foreach($vars as $var) {
            $_ip = "";
            if (isset($_SERVER[$var])) {
                $_ip = $_SERVER[$var];
            } elseif (getenv($var)) {
                $_ip = getenv($var);
            }
            if (!empty($_ip)) {
                $tmp = explode(',', $_ip);
                $ipSus[] = $tmp[0];
                $ipAll = array_merge($ipAll,$tmp);
            }
        }
        
        $ipSus = array_unique($ipSus);
        $ipAll = array_unique($ipAll);
        $ip    = (sizeof($ipSus) > 0) ? $ipSus[0] : $ip;
        
        return array('ip'=>$ip, 'suspect'=>$ipSus, 'network'=>$ipAll);
    }
</pre>

Thank you,
Zaenal (a.k.a lokamaya)

**Comment by splittingred** [comment]
splittingred submitted:

Have you signed a CLA? http://modx.com/cla/

If you do, we can accept this code.

**Comment by lokamaya** [comment]
lokamaya submitted:

Yes I have signed the CLA.

**Comment by wshawn** [comment]
wshawn submitted:

Eventually you will need to go to something more complete than even this.

The basis for IPv6 should also be considered.  I have had this on my site for a year:

[[http://www.shawnwilkerson.com/modx-revolution/php-code/php-utilities/getipaddress.html]]

Maybe you should consider combining these into a suitable forward reaching implementation.

**Comment by lokamaya** [comment]
lokamaya submitted:

Agree. It's should cover for both IPv4 and IPv6.

**Comment by splittingred** [comment]
splittingred submitted:

Done here: https://github.com/modxcms/revolution/commit/4ceca13ffab4c22e5f6d9181903123ca712d8d5e

You can feel free to open another issue for ipv6 handling.
