### ISSUE TITLE
Placeholders not being interpolated in TV input options

### ISSUE THREAD

**Issue by ncrossland** [modxbot/migrate#4202]
ncrossland created Redmine issue ID 4202

The tooltip for the base path / URL on image TV Input options says you can use placeholders of [[++base_path]] [[++core_path]] or [[++assets_path]]. None of these are replaced, giving an error message when you use the TV.

To reproduce:
1. Create a new TV
2. Choose Image type
3. Set the "base path" value to 

<pre>[[++assets_path]]images/news</pre>

1. Ensure that the /assets/images/news folder exists
2. Assign the TV to a template
3. Save
4. Edit a document which uses this template
5. Click the image TV to insert a value

Result: Error message saying:

<pre>
/home/xxxxx/public_html/[[++assets_path]]images/news
</pre>

It appears the resource browser is looking for that literal path, rather than interpolating the value

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/536f8b88f754fe49534d6f7588f655dbf9eca329
