### ISSUE TITLE
After upgrade to 2.1, old modxcms.com provider not deleted

### ISSUE THREAD

**Issue by ncrossland** [modxbot/migrate#4205]
ncrossland created Redmine issue ID 4205

After upgrading to 2.1 from 2.0.8, a new package provider of modx.com is added, but the old modxcms.com provider is not removed, leaving two "official" providers in the list.

Would it be tidier if the old one removed, and all references of existing packages were updated?

**Comment by splittingred** [comment]
splittingred submitted:

Done: https://github.com/modxcms/revolution/commit/035ef4c66add0d3847a09b0b3e8bc6144f0c40a9
