### ISSUE TITLE
File manager path & TV issues

### ISSUE THREAD

**Issue by Martijn1981** [modxbot/migrate#4208]
Martijn1981 created Redmine issue ID 4208

I've used the same path in my (Area: File System) settings for "filemanager_path" and filemanager_url" for quite some time now: "/assets/files", so that the client (and me) could only upload files to that directory through the Filemanager. 

However, having a new site updated to 2.1 RC1, I noticed some big errors. The path of all image URL's (generated through image TV's) now contained the above path _twice_.

Like this:

<pre>
/assets/files/assets/file/name_image.jpg
</pre>

So I was getting errors everywhere. I just deleted all the filemanager_path and filemanager_url settings. The image problem seems gone now, but the client has access to all directories now...

**Comment by Martijn1981** [comment]
Martijn1981 submitted:

Also, all thumbnails are completely blank. I've only uploaded PNG and PDF files so far and there are no miniature images available.

**Comment by Martijn1981** [comment]
Martijn1981 submitted:

Regarding the filemanager path bugs: I forgot to mention that I'm using the Image TV URL in combination with the "phpthumbof" filter!

Sorry for all these extra updates. These are my settings, by the way:

All the bugs I've submitted so far are regarding a MODx upgrade: from 2.0.8 to RC 2.1. All templates, permissions and FC settings were defined before the upgrade. I'm running the CMS with PHP 5.3.4 and mySQL 5.1.42. In retrospect, most bugs I've reported are visible in all main browers: IE8, Opera, Safari, Chrome and FF3/4. In my opinion, 80% of the bugs seem to revolve around FC: template fields that are unexplicably turned off or on, TVs that shouldn't be visible in the first place. Just a few things. Perhaps something went wrong with these permissions per user by upgrading to 2.1

**Comment by splittingred** [comment]
splittingred submitted:

Erm, you should be setting your path/url to:

<pre>assets/files/</pre>

Note the lack of a leading /.

Also, I can't replicate this at all after setting my filemanager_path/url to 'assets/files/'.

**Comment by Martijn1981** [comment]
Martijn1981 submitted:

No, unfortunately it has got something to do with filemanager_path and filemanager_url allright. Here's a link to the page where it happened: http://bit.ly/dPHRq7 (not using a direct link due to Google crawlers). The images went blank the moment I changed filemanager_path/url to 'assets/files/'. Check out my screenshots. It's a lot clearer that way.

The only thing I changed were those two settings. I'm producing these image links through the Image TV URL option and I'm combining that with phpthumbof and getResources.

**Comment by splittingred** [comment]
splittingred submitted:

Can you paste the chunk that you're using for getResources with the placeholders for the TV in them?

**Comment by Martijn1981** [comment]
Martijn1981 submitted:

This is the chunk for the overview page

<pre>
<li><a href="[[~[[+id]]]]"><img src="[[+cabin_image:phpthumbof=`w=160&h=98&zc=1`]]" width="160" height="98"><br> [[+pagetitle]]</a></li>
</pre>

This is the chunk for the detail page (directly used inside a template)

<pre>
      <div id="details_list">
        <h2>[[*pagetitle]]</h2>
        <ul>
          <li>[[*cabin_dimensions]]</li>
          <li><a href="[[~4? &type=`[[*pagetitle]]`]]">Stuur mij informatie</a></li>
          <li><a href="[[*cabin_document]]" target="_blank">Download de tekening</a></li>
        </ul>
      </div>
      <div id="details_image">
        <img src="[[*cabin_image:phpthumbof=`w=360&h=222&zc=1`]]" width="360" height="222" alt="Afbeelding [[*pagetitle]]">
      </div>
</pre>

Could the new Input Options have something to do with it, by the way? I've left the Base Path and URL settings untouched, fyi.

**Comment by splittingred** [comment]
splittingred submitted:

Does it not work in either the chunk or the Template?

**Comment by Martijn1981** [comment]
Martijn1981 submitted:

The chunk and template both work fine. It's just that the URL of both

<pre>
[[+cabin_image:phpthumbof=`w=160&h=98&zc=1`]]
</pre>

and

<pre>
[[*cabin_image:phpthumbof=`w=360&h=222&zc=1`]]
</pre>

are messed up once I modify the settings for "filemanager_path" and filemanager_url". As you saw in the screenshot.

**Comment by splittingred** [comment]
splittingred submitted:

Is the URL fine if you remove the phpthumbof filter?

**Comment by Martijn1981** [comment]
Martijn1981 submitted:

Excellent thinking, but unfortunately no. Same "double-URL" bug.

**Comment by splittingred** [comment]
splittingred submitted:

So, let me get this straight. These are your settings:
- filemanager_path - assets/files/
- filemanager_path_relative - YES
- filemanager_url - assets/files/
- filemanager_url_relative - YES

And an Image TV called cabin_image.

---

I went ahead and did the same (except used assets/images/), and my ImageTV shows this:

<pre>assets/images/icons/framework.png</pre>

Which is correct. I'm not sure what's causing your issue.

**Comment by Martijn1981** [comment]
Martijn1981 submitted:

It seems I have _kinda_ found the solution. 

Check out http://bit.ly/dPHRq7. I've only adjusted the filemanager_path key: assets/files/. I have left the filemanager_url key blank. The URL's of the images however are very, very ugly. Is that just the doing of phpthumbof, by the way? I'm just not sure.

**Comment by splittingred** [comment]
splittingred submitted:

Probably. You should look into the &q param for phpthumb.

Closing this ticket.
