### ISSUE TITLE
member_groups add a sequence column

### ISSUE THREAD

**Issue by jgulledge19** [modxbot/migrate#4217]
jgulledge19 created Redmine issue ID 4217

I would like to request that a sequence column be added to the member_groups table.  I want to order them for a custom snippet.  Initially the manager does not need to have the ability to order them but that would be desirable in the future. 

Also could the membergroup_names id be shown in the manager?  Security -> Access Controls page view.

Thanks

**Comment by splittingred** [comment]
splittingred submitted:

Done: https://github.com/modxcms/revolution/commit/ab7eef84a13683b54fb24699d5f862f099893d2d

**Comment by jgulledge19** [comment]
jgulledge19 submitted:

Thanks Shawn for getting this so quickly.

I think I may have been unclear on what I was asking so I will try to clarify.  I was referring to modUserGroupMember the actual member_groups table to add in rank/order.  I am wanting to order the all members in that group (or how I am using it Staff/Faculty Departments).  Based on the this order I will create Faulty/Staff pages listing them by group and ordered by rank/order.  I don't think I will order the groups by rank but probably just alphabetical.

**Comment by splittingred** [comment]
splittingred submitted:

Done: https://github.com/modxcms/revolution/commit/62789d41f5211954e331586616274116cb83f35f
