### ISSUE TITLE
TinyMCE keeps disappearing

### ISSUE THREAD

**Issue by Martijn1981** [modxbot/migrate#4222]
Martijn1981 created Redmine issue ID 4222

This problem only occurs when I decide to make a "New Document". Pages that already exist don't seem to suffer from this issue.

When I'm creating a new document, TinyMCE is completely gone from its usual "Resource content" spot. However. the HTML Area template variable that I've attached to the page is still there and working!

There´s one more thing. I´ve used extensive FC to move the HTML Area TV to the first tab. I'm using that option for a lower user-group "Webmasters", which contains profiles for the client. When the HTML Area is moved to the 1st tab, it has suddenly become a full-fledged TinyMCE editor, instead of providing us with only the most basic layout (b, i, italic etc.) options.

**Comment by Martijn1981** [comment]
Martijn1981 submitted:

Regar the "New Document" problem: it even occurs when I'm logged in as an admin. So no FC involved for my profile. However, it seems that not only TinyMCE was removed: other standard page settings, like Cacheable, Searchable etc., were turned off by default! I had to recheck every single page, turn on these settings and press save again. 

Once more: this only happens with making new document. The documents that were already present when the CMS was at its 2.08 stage, are all good.

**Comment by ncrossland** [comment]
ncrossland submitted:

See this reply on forums, so may be fixed via bug 4207:

> Seems to be directly related to this bug in 2.1.0-rc1:
> http://bugs.modx.com/issues/4207#note-3
> A fix has been posted here:
> https://github.com/modxcms/revolution/commit/6f610fc1b1ec386b983d5ae6cc40a69e62c1335d
> I can confirm TinyMCE works as expected after that fix.

http://modxcms.com/forums/index.php/topic,62922.msg356682.html#msg356682
