### ISSUE TITLE
New permissions not added during upgrade

### ISSUE THREAD

**Issue by ncrossland** [modxbot/migrate#4223]
ncrossland created Redmine issue ID 4223

When upgrading a site from 2.0.8, the 4 new permission items were not added on one particular site (leaving 126 items in the default Administrator policy, rather than the 130 of other sites).

I'm unable to isolate why it should fail on one site but work on another. Presumably around line 152 of setup/includes/upgrades/mysql/2.1.0-rc-1.php the conditions around $adminTpl or $policies were false.

Other MySQL updates appear to have been performed correctly.

**Comment by onepack** [comment]
onepack submitted:

This http://bugs.modx.com/issues/3977 seems to be related to the same thing. Upgrading from 1.07 to 1.08 wiped out all the custom assigned user rights.

**Comment by splittingred** [comment]
splittingred submitted:

Did you happen to rename the AdministratorTemplate policy template before upgrading?
