### ISSUE TITLE
Unable to save chunk or template

### ISSUE THREAD

**Issue by ghost** [modxbot/migrate#4227]
gguenette created Redmine issue ID 4227

Unable to save chunk or template

When I save a chunk (same for templates) with no HTML, the chunk is saved and got msg "successfully saved"

When I enter random text "klasjdlfka" the chunk is saved and got msg "successfully saved"

When I put simple HTML code, saving progress bar appears then disappear with no error message... but the content is'nt saved.

Tried to modify htaccess, with no results

Any idea?

HTML Exemple:

<div></div>

or

<ul><li>A</li><li>B</li></ul>

PHP configs:

Language Options    asp_tags    Allow ASP-style <% %> tags.     On
File Uploads    file_uploads    Whether to allow HTTP file uploads.     On
Paths and Directories   include_path    Windows: "\path1;\path2" c:\php\includes"   .:/usr/lib/php:/usr/local/lib/php
Resource Limits     max_execution_time      120
Resource Limits     max_input_time      120
Resource Limits     memory_limit        128M
Language Options    safe_mode       Off

Please confirm the bug is resolved before closing it. Thanks...

**Comment by ghost** [comment]
gguenette submitted:

This environment is hosted, not local

**Comment by splittingred** [comment]
splittingred submitted:

Turn off mod_security and safe_mode in your PHP instance.

I cannot replicate this locally or on a remote host.

**Comment by ghost** [comment]
gguenette submitted:

Safe Mode is OFF
