### ISSUE TITLE
Removing a file with the file manager triggers an error the 1st time

### ISSUE THREAD

**Issue by Martijn1981** [modxbot/migrate#4228]
Martijn1981 created Redmine issue ID 4228

I've made a few directories inside /assets: /assets/files and /assets/files/images and /assets/files/documents.

Uploading goes fine, but I've encountered a strange bug while trying to delete an image inside /assets/files/images. This is how I trigger the bug
# I'm opening a page which has a Image TV attached to it.
# I click on the Image TV in order to access the File Manager
# I click on the directory to see the files appear and I right-click on a image (.png in this case) to remove a file
# Now I see the following popup appear: File does not exist!: /usr/home/[further location of the image]

However, when I click on another directory, /assets/files/documents in this case, and then go back to the images directory again, the bug seems to be gone! I can remove the file. I can remove other files as well now.

The bug reappears again when I reload the document and have to click on the Image TV once more to access the File Manager.

**Comment by splittingred** [comment]
splittingred submitted:
1. Please do not assign Target Versions or Assignees to tickets.
2. Make sure you have filemanager_path and filemanager_url set correctly, if you're using them.
3. Make sure PHP has permissions to remove the file.

I can't replicate this at all.
