### ISSUE TITLE
No image preview in file manager

### ISSUE THREAD

**Issue by Martijn1981** [modxbot/migrate#4229]
Martijn1981 created Redmine issue ID 4229

There are _no_ thumbnail previews present inside the file manager. All I see are blank squares. The images _are_ uploaded though. It just seems that the preview option has been disabled.

**Comment by splittingred** [comment]
splittingred submitted:
1. Please do not assign Target Versions or Assignees to tickets.
2. Make sure you have ImageMagick installed.
3. Make sure you have filemanager_path and filemanager_url set correctly, if you're using them.

**Comment by Martijn1981** [comment]
Martijn1981 submitted:

I set filemanager_path correctly now and it works! Case closed.

One more thing: what is filemanager_url exactly used for then?

**Comment by splittingred** [comment]
splittingred submitted:

To match the URL to the path of the images; especially useful if your path isn't relative.
