### ISSUE TITLE
Listbox multiselect output delimiter not saved

### ISSUE THREAD

**Issue by krisj** [modxbot/migrate#4232]
krisj created Redmine issue ID 4232

Cannot set a custome delimiter in output of TV type List Mulsti Select.
To reproduce:
- create multiselect list TV
- set input option to: @DIRECTORY /assets/files/mp3
- set output option to: delimiter
- set field to anything
- save
- delimiter field returned as blank and renderd with default delimiter ","

**Comment by krisj** [comment]
krisj submitted:

it looks like the correct custom delimiter value gets saved into the DB. checked the "modx_site_tmplvars" table and output_properties shows: a:1:{s:9:"delimiter";s:3:"|";} which is what I entered in back end...

so it has trouble reading it back out and rendering it in back and front end.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed, was a problem with all of Output Options being ignored: https://github.com/modxcms/revolution/commit/1666dc6994cb6511c52e7de5612ceb35b152d3d7
