### ISSUE TITLE
Remove hyphen from end of template name in dropdown

### ISSUE THREAD

**Issue by ncrossland** [modxbot/migrate#4236]
ncrossland created Redmine issue ID 4236

The templates dropdown (when editing a resource) has a hyphen appended at the end of each template name which is unneccesary and adds visual clutter. 

It appears even when there is no description of the template appearing on the second line underneath. If you choose not to include descriptions of templates it makes no visual sense.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/f671429719d89f543e18d993a7fcc1983bcef4df
