### ISSUE TITLE
Indicate if file is read-only

### ISSUE THREAD

**Issue by ncrossland** [modxbot/migrate#4243]
ncrossland created Redmine issue ID 4243

When editing a file via the File panel, there is no indication at any point if a file cannot be written by the web server. This can be frustrating if a user spends a long time editing a file only for it to be unsavable.

For example, if a CSS file has been uploaded via FTP, it is likely to be owned by the FTP user without world writable permissions, rather than nobody which is necessary to edit via the Manager interface.

The information could be obtained simply via PHP's is_writable. It would be helpful if this was indicated via:

1) A padlock icon on files in the file tree
2) A notification on the "edit" page when a non-writable file is being edited, e.g. alongside the metadata such as last modified date
3) An alert when the user tries to save a file which in un-writable -- at the moment this silently fails.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/4a81cae78937c0c7b6c5ccca72c7b5c80d334447
