### ISSUE TITLE
After upgrade to 2.1RC1, plugin property lists lose their "name" values

### ISSUE THREAD

**Issue by ncrossland** [modxbot/migrate#4244]
ncrossland created Redmine issue ID 4244

Steps to reproduce:
1. In 2.0.8, install a plugin which uses properties of type "list" - e.g. TinyMCE's "entity_encoding" property
2. Upgrade to 2.1-RC1
3. Go to the plugin's properties; create a new property set
4. Double click to edit the "entity_encoding" property

Result:

No options are visible in the dropdown that appears.

Right click to edit the property, and the values are still present, but the name fields are empty.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/ae63dcd3549a3a0085778825c67d68f9a70e3b75
