### ISSUE TITLE
"View" (previously Preview) button in the manager just opens a blank page

### ISSUE THREAD

**Issue by zaigham** [modxbot/migrate#4253]
zaigham created Redmine issue ID 4253

In resource editing screen, "View" (previously Preview) button in the manager just opens a blank page. It should be opening the current page.

Tested in Fx and Chrome.

**Comment by splittingred** [comment]
splittingred submitted:

Do you have FURLs enabled?

**Comment by zaigham** [comment]
zaigham submitted:

After enabling FURL it worked. Then after disabling FURLs it worked again.

Is it possible its related to this one? http://bugs.modx.com/issues/4220
