### ISSUE TITLE
Deeper Partial Caching Needed

### ISSUE THREAD

**Issue by yoleg** [modxbot/migrate#4255]
yoleg created Redmine issue ID 4255

In my 2.0.8 revo install, partial caching only works up to the first level. In other words, 

@Cached Chunk --> Uncached Snippet@ (uncached snippet is inside of the cached chunk) updates the snippet with every page load as it's supposed to.

However,

@Cached Chunk --> Cached Chunk --> Uncached Snippet@ caches the result of the uncached snippet, which defeats the purpose of partial caching.

Improving the partial caching to deeper levels will speed up sites with nested chunks that need to be cached except for specific snippet calls.

**Comment by yoleg** [comment]
yoleg submitted:

By the way, this is even more so the case for 2.1 rc3. Right now caching ANY chunk or other element automatically caches everything inside of that chunk, even if it is called uncached. I would really like to structure my site with cached chunks except for an occasional uncached snippet call (such as Wayfinder or Login) nested deep inside. Otherwise, I have to leave almost everything uncached, which more than triples page load times.

**Comment by opengeek** [comment]
opengeek submitted:

I can't reproduce what you are referring to. You can mark only specific things uncached in Chunks, unless you are iterating over them, in which case the chunks should not be cached anyway. If you can provide a specific case to reproduce this, we'll be glad to research further.

**Comment by yoleg** [comment]
yoleg submitted:

This seems to be resolved in 2.1.0-rc4. Thank you!
