### ISSUE TITLE
Quick Update/ Create TV should include Caption

### ISSUE THREAD

**Issue by yoleg** [modxbot/migrate#4256]
yoleg created Redmine issue ID 4256

Currently, when you create or duplicate a template variable, you have to open it in full edit view to modify the caption. Adding the caption to the "quick update" and "quick create" dialogues would really speed up workflow.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/c6ef4657cf48ad446ca36c7c85065d7e903f7074
