### ISSUE TITLE
Impreove the title tag of manager pages

### ISSUE THREAD

**Issue by pepebe** [modxbot/migrate#4260]
pepebe created Redmine issue ID 4260

Change the title attribute of the manager to display something like  "MODx | Add name/title of currently active ressource". 

Examples: 

"MODx | Homepage" or 
"MODx | New Template Variable" or 
"MODx | Package Mangement"

This makes working in multiple tabs/windows MUCH more comfortable.

Regards,

pepebe

**Comment by splittingred** [comment]
splittingred submitted:

Done in: https://github.com/modxcms/revolution/commit/2302693aa6a8dbb4d6b6f6124593538d5179604f
