### ISSUE TITLE
Safe current resource on ctrl+s

### ISSUE THREAD

**Issue by pepebe** [modxbot/migrate#4261]
pepebe created Redmine issue ID 4261

Safe the current document on ctrl+S. This is a keyboard shortcut that most developers are EXTREMELY familiar with and a habit thats hard to break (you can do that in google Mail and it feels sooo RIGHT). 

Though splittingred revealed that you can already do that on [shift+ctrl+s] I agree with lossendae that [ctrl+c] wold be a much better choice.

Though there are concerns that this shortcut is usually reserved for saving a page to your computer I still think it is a good idea to override that behaviour.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/7a1fb197d76b03844a52029e578f05991efcccf4
