### ISSUE TITLE
Form Customization Error when using HTML Tags for Label Names

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#4262]
wshawn created Redmine issue ID 4262

I changed the Label of longtitle via Form Customization to <title></title>

It sends the raw content to the Manager, which makes it invisible...

Maybe a call to htmlentities or the like is necessary.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/82b6a5cf14e8dc061a74c0912c427da90f496d0b
