### ISSUE TITLE
Cannot delete images from file browser on Image TVs with base path/URL input options set

### ISSUE THREAD

**Issue by ncrossland** [modxbot/migrate#4270]
ncrossland created Redmine issue ID 4270
1. Create an image TV, and set a base path / URL, e.g. assets/images
2. Attach to a template
3. Create a document using that template
4. Click the TV to choose an image
5. Upload an image to that folder (which should be the one specified by your base path) e.g. myfile.jpg
6. Right click and choose "Remove" to delete the uploaded file

The delete fails, with an error message showing the path to that image has not included the base path you defined, e.g. it has tried to delete

/home/xxx/public_html/myfile.jpg

instead of 

/home/xxx/public_html/assets/images/myfile.jpg

If there was a file actually at that path, it could result in that file being incorrectly deleted.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/b28488353d604c65649c5dd44a778ca1a295056d
