### ISSUE TITLE
Highlight the document you are currenty editing/viewing in the resource tree

### ISSUE THREAD

**Issue by pepebe** [modxbot/migrate#4271]
pepebe created Redmine issue ID 4271

I have noticed that clients sometimes get confused about the document they are working on. 

It would be nice to have some visual feedback from the ressource tree which ressource is currently "acitve"

Possible solutions: Add class "active" to the active ressource so it'S possible to change element background or text color.

**Comment by splittingred** [comment]
splittingred submitted:

Done: https://github.com/modxcms/revolution/commit/ac19cf87fea78bd866151eeda1e35a13ad455746
