### ISSUE TITLE
If you duplicate a resource, offer to automaticaly open said resource.

### ISSUE THREAD

**Issue by pepebe** [modxbot/migrate#4272]
pepebe created Redmine issue ID 4272

If you duplicate a resource, offer to automaticaly open said resource. Most probably this is what you have to do next anyway.

Use a checkbox or whatever to prevent that. Catches two birds with one stone.

**Comment by wshawn** [comment]
wshawn submitted:

This is a duplicate request : http://bugs.modx.com/issues/4159
