### ISSUE TITLE
Cannot remove package if package files no longer exist

### ISSUE THREAD

**Issue by opengeek** [modxbot/migrate#4280]
opengeek created Redmine issue ID 4280

If you have packages installed and the physical package files get removed, you cannot remove the package (with or without force package removal option checked) and the modal console window locks up.

Here is the error:

<pre>
Console running...
Grabbing package to remove...
Successfully grabbed package. Now attempting to remove transport zip...
Could not open file for reading: getpage-1.0.0-pl.transport.zip?revolution_version=Revolution-2.1.0-rc2
MODX could not download the file. You must enable allow_url_fopen, cURL or fsockopen to use remote transport packaging.
Could not transfer package getpage-1.0.0-pl.transport.zip to /opt/local/apache2/htdocs/jasoncoward.com/core/packages/.
Could not load transport package.
Error removing package with signature: [[+signature]]
</pre>

**Comment by krisj** [comment]
krisj submitted:

second that

**Comment by opengeek** [comment]
opengeek submitted:

This is critical because you cannot download updates to some packages when this occurs without going into the database and removing the rows for the missing packages.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/f2caa0f45650de93fd1d4bf5678105b660af622e
