### ISSUE TITLE
getPage: property pageActiveTpl missing and broken

### ISSUE THREAD

**Issue by rfoster** [modxbot/migrate#4284]
rfoster created Redmine issue ID 4284

This affects getPage 1.1.0-pl (but probably not earlier versions)

The property pageActiveTpl is not in the default property set for getPage. If you add it manually to a property set or the default properties, it still is not used, so something broke.

**Comment by splittingred** [comment]
splittingred submitted:

Please file getPage issues here:

https://github.com/opengeek/getPage/issues/

This tracker is for core issues only.
