### ISSUE TITLE
FirstChildRedirect is LAST child redirect

### ISSUE THREAD

**Issue by rfoster** [modxbot/migrate#4285]
rfoster created Redmine issue ID 4285

The default property for sortDir is 'DESC.' This should be changed to 'ASC.'

Affects 2.2.0-pl (and previous versions for quite some time http://modxcms.com/forums/index.php?topic=47186)

By the way...it is not clear at all where we are supposed to file bugs like this. Nothing turned up at the forums, githup, forums, etc. so posting it here.

**Comment by splittingred** [comment]
splittingred submitted:

Bugs for Extras go in their respective issue trackers. FirstChildRedirect does not have one; though you could post a comment in the forums.
