### ISSUE TITLE
Missing lexicon items in czech localization

### ISSUE THREAD

**Issue by pavsyk** [modxbot/migrate#4291]
pavsyk created Redmine issue ID 4291

_File:_ core/lexicon/cs/tv.inc.php
_Missing items:_ tv_input_options, tv_input_options_msg, tv_output_options, tv_output_options_msg

**Comment by pavsyk** [comment]
pavsyk submitted:

It is included within the task #4216. I did not notice it before, sorry.

**Comment by splittingred** [comment]
splittingred submitted:

This was fixed in a recent pull request.
