### ISSUE TITLE
I am able to save snippet in modex 2.0.7

### ISSUE THREAD

**Issue by ghost** [modxbot/migrate#4306]
cipher created Redmine issue ID 4306

Saving pop up appears 3 times but snippet is not saved still.
So i am trying to add it from backend.
I am very tired of this issue.
I need helf from you guys ,Please help me.

**Comment by ghost** [comment]
cipher submitted:

Priyanka Mane wrote:

> Saving pop up appears 3 times but snippet is not saved still.
> So i am trying to add it from backend.
> so it appears in snippet but not reflected on front end.
> it is reflected after enable system cache setting.
> I am very tired of this issue.
> I need helf from you guys ,Please help me.

**Comment by opengeek** [comment]
opengeek submitted:

This is not a bug with MODX, but most likely is the result of mod_security rules in your hosting environment. However, you have provided no information about your hosting environment. I would keep these kinds of reports limited to forum posts unless you have details on what is causing the error, or at least the environment you are running it in.
