### ISSUE TITLE
I am not  able to save snippet in modex 2.0.7

### ISSUE THREAD

**Issue by ghost** [modxbot/migrate#4307]
cipher created Redmine issue ID 4307

Saving pop up appears 3 times but snippet is not saved still.

So i am trying to add it from backend.

I am very tired of this issue.

I need helf from you guys ,Please help me.

**Comment by wshawn** [comment]
wshawn submitted:

First, test your database to see if it is corrupted.

Second, update to the newest version of Revo.

If issue still exists then post more information, such as the environment and software versions on the server.
