### ISSUE TITLE
TV's not being saved on Resource create

### ISSUE THREAD

**Issue by opengeek** [modxbot/migrate#4310]
opengeek created Redmine issue ID 4310

Template Variable values not being saved when creating a new Resource.

**Comment by opengeek** [comment]
opengeek submitted:

steps to reproduce:

1)Create a new post. 
2)Do not save the post 
3)Set a TV value 
4)Save the post 
5)The TV values will now be blank

TVs values are posted to /connectors/resource/index.php:

but, the id value is blank.

It responds with:

{"success":true,"message":"","total":0,"data":[],"object":{"id":119693}}

But none of the TVs are saved!

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/0041a4295255b126545377689bf79efaeddad6e9
