### ISSUE TITLE
Template change on new unsaved resource incorrect

### ISSUE THREAD

**Issue by juro** [modxbot/migrate#4343]
juro created Redmine issue ID 4343

Changing template on newly created (unsaved) resource tries to save and reopen that resource. The resource is saved with old template and instead another new resource with new template is opened for editing. Very confusing when adding many new resources with different templates.
Changing template on saved resources works fine.

**Comment by splittingred** [comment]
splittingred submitted:

This has already been fixed for 2.1-rc2.
