### ISSUE TITLE
system setting values missing in manager after upgrade

### ISSUE THREAD

**Issue by krisj** [modxbot/migrate#4345]
krisj created Redmine issue ID 4345

i just upgraded to 2.1.0-rc2 and went to system setting panel. all the setting values show up empty. nothing in error logs on system or modx.

**Comment by splittingred** [comment]
splittingred submitted:

Refresh your JS cache.

**Comment by krisj** [comment]
krisj submitted:

i cleared browser, modx (core/cache folder) cache and tried different browsers. DB table has the correct settings, just ui not showing them...

**Comment by krisj** [comment]
krisj submitted:

the UI shows the last modified date of each setting too, but not the value...

**Comment by krisj** [comment]
krisj submitted:

and it might be worth moentioning that i upgraded rfom the git rc2 (about 2-3 days old) to rc2 traditional. was that a bad idea?

**Comment by MadeMyDay** [comment]
mademyday submitted:
- 1 here. Upgraded from 2.0.8.pl. The grid cell is empty, so it is no CSS/Browser issue. Chrome, FF, Safari, all the same. Language german, but english the same. If you change a value you can see it and it is stored but after refresh the values are gone.

**Comment by splittingred** [comment]
splittingred submitted:

This has been fixed here: https://github.com/modxcms/revolution/commit/47bdab9230afe12f5261e69765972e70c2d2e9f6

We'll re-release rc2 later today to fix this issue.

**Comment by krisj** [comment]
krisj submitted:

nice, it works now. thank you! that is really amazing support.. and i will never get tired of mentioning it.
