### ISSUE TITLE
Logic Code - Security FIX

### ISSUE THREAD

**Issue by lyubomir** [modxbot/migrate#4352]
Lyubomir created Redmine issue ID 4352

changes in /core/model/modx/processors/security/login.php

1) if the user login is incorrect, then the count of incorrect entries are counted twice
example: login incorrect (incorrect password) - in manager -> user security -> Failed logins: 2
again incorrect - in manager -> user security -> Failed logins: 4 ..etc.
Why is that?

in code line #136:

<pre>
/* check if plugin authenticated the user */
if (!$rt || (is_array($rt) && !in_array(true, $rt))) {
    /* check user password - local authentication */
    if ($user->get('password') != md5($givenPassword)) {
        $flc = ((int)$up->get('failedlogincount'))+1;
        $up->set('failedlogincount',$flc);
        $up->save();
        
        return $modx->error->failure($modx->lexicon('login_username_password_incorrect'));
    }
}
</pre>

function RETURN is like external, and this code executes twice, and increments Failed logins +1 +1, t.e. two times

Solution:

<pre>
/* check if plugin authenticated the user */
if (!$rt || (is_array($rt) && !in_array(true, $rt))) {
    /* check user password - local authentication */
    if ($user->get('password') != md5($givenPassword)) {
        /* add session for count, when return function reload page */
        /* if not session - value 0 */
        if ($_SESSION['login_failed'] == NULL){
            $_SESSION['login_failed'] = 0;
        }
        /* if it goes for the first time through this */ 
        if ($_SESSION['login_failed'] == 0){            
            $flc = ((int)$up->get('failedlogincount'))+1;
            $up->set('failedlogincount',$flc);
            $up->save();
            $_SESSION['login_failed'] ++; // increment session value
        /* if it doesn't go for the first time through this (after reload of return function) */
        }else{
            $_SESSION['login_failed'] = 0; // zeroing session
        }
        return $modx->error->failure($modx->lexicon('login_username_password_incorrect'));
    }
}
</pre>

2) When the number of wrong logins is above the allowed in system settings (failed_login_attempts), then user is not blocked and only its written the time till the user is blocked  - the current time() -1 sec, which is not logical. Line #91:

<pre>
if ($up->get('failedlogincount') >= $modx->getOption('failed_login_attempts') && $up->get('blockeduntil') < time()) {
    $up->set('failedlogincount', 0);
    $up->set('blockeduntil', time() - 1);
    $up->save();
}
</pre>

Modified code:

<pre>
if ($up->get('failedlogincount') >= $modx->getOption('failed_login_attempts') ) {
    $up->set('failedlogincount', 0);
    $up->set('blocked', 1);
    $up->set('blockeduntil', time() + (60 * $modx->getOption('blocked_minutes')));
    $up->save();
}
if ($up->get('blockeduntil') !=0 && $up->get('blockeduntil') < time()) {
    $up->set('failedlogincount', 0);
    $up->set('blocked', 0);
    $up->set('blockeduntil', 0);
    $up->save();
}
</pre>

The first part blocks the user for the time set in system settings at "blocked_minutes", and the second part nulls all the blocks if the time for blocking has passed already.

**Comment by opengeek** [comment]
opengeek submitted:

This is implemented for 2.1.0-pl release — thanks for the report and solution.
