### ISSUE TITLE
File TV only stores first directory in path

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#4363]
wshawn created Redmine issue ID 4363

I created a test in assets/authors
Pointed the TV to [[++assets_url]]/authors
File is selected

Output: 
http://www.domain.com/assets/MensMeeting201103.pdf

Expected:
http://www.domain.com/assets/authors/MensMeeting201103.pdf

**Comment by wshawn** [comment]
wshawn submitted:

Found a work around:

Also designate the Base URL as it will be presented to the visitor.  Personally, I think this is redundant, unless we can place a Snippet call to obfuscate the path, or we are utilizing a download server....

In any case, there is a plausible solution already provided.

**Comment by splittingred** [comment]
splittingred submitted:

I can't replicate:
- Setup a File TV with Input Type "File"
- Set Base Path to: &#91;&#91;++assets_path&#93;&#93;js/
- Set Base Path Relative to: Yes
- Set Base Url to: &#91;&#91;++assets_url&#93;&#93;js/
- Set Base Url Relative to: Yes
- Set Prepend Url If No Beginning / to: Yes
- Assign to Template

Selected file in TV in Resource, output content to resource:

<pre>FileComboTV: [[!*FileComboTV]]</pre>

Output is as expected:

<pre>FileComboTV: /modx/assets/js/property.js</pre>

**Comment by splittingred** [comment]
splittingred submitted:

Closing as def. cannot reproduce.
