### ISSUE TITLE
Saving resource doubles Toggle editor check box

### ISSUE THREAD

**Issue by juro** [modxbot/migrate#4370]
juro created Redmine issue ID 4370

Clicking Save button or Ctrl+S doubles (triples etc.) "Toggle editor" check box under content editor for resources with "Rich text" set to off.

**Comment by splittingred** [comment]
splittingred submitted:

This is an issue with TinyMCE, rather than MODX, it seems.

**Comment by splittingred** [comment]
splittingred submitted:

Also, are you sure you have the latest TinyMCE installed?
