### ISSUE TITLE
View button on Resource save does not get uri change

### ISSUE THREAD

**Issue by opengeek** [modxbot/migrate#4372]
opengeek created Redmine issue ID 4372

When a change is made to a Resource which causes the uri to change, the View button is not updated with the new uri and thus appears broken when clicking it. In contrast, the tree is refreshed properly and using Preview Resource from context menu works as expected.

**Comment by mkschell** [comment]
netprophet submitted:

Fixed in commit https://github.com/modxcms/revolution/commit/ca34bb0d9c247c85dc16e7b4ff6a39c511716f7d
