### ISSUE TITLE
Template Variable HTML Tag Output Attempts Return of empty array

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#4373]
wshawn created Redmine issue ID 4373

Using Tag as input type
Using HTML Tag Output Type

Not putting any tags into a resource

Returns "Array" on empty array

Maybe need an Intval()

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/895777c24ecbcb62ba3b334aaf89f5d40d1d4d2e
