### ISSUE TITLE
Invalid Error Message in Mgr UI - on File Save

### ISSUE THREAD

**Issue by AESmith** [modxbot/migrate#4374]
aesmith created Redmine issue ID 4374

On fresh install on 2.1 rc3. Go to Files->assets-> %anything%. Open file, then save, . "Error Unable to Rename File ... check permission". 

Permissions are fine and file does actually save but you get this message each time.

Both myself and Mark H. have reproduced

**Comment by splittingred** [comment]
splittingred submitted:

Confirmed. Likely due to issues with new filemanager_path mappings.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/fd3530e218acda78b41e563e2e3b939340e8e5bd

Was due to some old, deprecated code relating to renaming files.
