### ISSUE TITLE
the top action buttons in resource editing view dont work

### ISSUE THREAD

**Issue by krisj** [modxbot/migrate#4375]
krisj created Redmine issue ID 4375

these seem to have no functionality in 2.1.0-rc3
[[http://awesomescreenshot.com/09cb9mtd8]]

in Chrome browser they dont even "switch" the appearance.

**Comment by opengeek** [comment]
opengeek submitted:

 I can't reproduce any problem with this behavior. These affect what happens when the Resource is saved and it is working fine on Chrome in OS X as far as I can tell.

**Comment by krisj** [comment]
krisj submitted:

Just rechecked - it is working now on FF and Chrome on Win. It probably was a local caching issue. Sorry about the false alarm.
