### ISSUE TITLE
Caching Problems

### ISSUE THREAD

**Issue by yoleg** [modxbot/migrate#4376]
yoleg created Redmine issue ID 4376

I found several problems with caching in 2.1.0 RC3:
1. I'm not sure if this is a problem with Wayfinder or MODx, but I have an uncached Wayfinder call inside of an uncached chunk directly inside of template, with partial resource caching enabled. However, despite making sure that Wayfinder is not inside any cached element, the Wayfinder call does NOT update to reflect changes in resource names or URLs until the cache is cleared manually.
2. Again, not sure if this is a Wayfinder issue, but clearing the cache leaves lots of Wayfinder cache files inside of /core/cache/default/wayfinder/. This doesn't make sense to me, since all of my wayfinder calls are uncached, and I also noticed that other cache files are left on the server. Not sure which files are supposed to be cleared, but the Wayfinder ones at LEAST should have been removed.
3. Clearing the cache when some resources have empty aliases with duplicate page titles causes a bunch of errors (this is actually kind of cool, but needs to look less like an error and more of a notice).
4. Nested cached/ uncached elements - please see improvement number 4255. I noticed that page load times for recent releases have decreased drastically, even if every element on the page is uncached. However, I used to be able to put uncached elements inside of cached elements and could still be sure that they would work properly. Now, I have to make everything uncached and triple my page load time just to make sure my Login call works (from about 1.7sec to 6 sec). I am seriously considering downgrading my version of MODx to an older version just because of this issue.

**Comment by gadamiak** [comment]
gadamiak submitted:

I just upgraded from 2.0.8-pl to 2.1.0-rc3 and observe caching problems. However, what I get is of different nature than reported here.

For me, uncached chunks inside cached chunks do work and output filters seem to work too. This is unlike reported in #4255 and #3857, which I guess are related. What I observe is no change in output of a chunk after saving a source chunk or resource (with clear cache enabled) for that chunk. Clearing the site cache doesn't help either. I had to change uncache chunk tags to make them update.

h3. What I do:
- I use getPage with getResources and template @res.list-image@.
- I display static resources.
- The @res.list-image@ chunk contains (simplified):
  <pre>
  <li><p>
  <a href="[[~[[+id]]]]">[[+pagetitle]]</a>
  [[+contentType:limit=`5`:eq=`image`:then=`
  <a href="[[~[[+id]]]]">
  <img src="[[+content:phpthumbof=`&w=156&h=109&zc=1`]]" />
  </a>`]]
  </p></li>
  </pre>

h3. What happens:
- Changing alias doesn't update output. It updates on uncaching @[[~[[+id]]]]@ to @[[!~[[+id]]]]@.
- Modifying page title doesn't update output.
- Clearing site cache removes phpThumbOf cache, which is correct, but the thumbnails don't get recreated unless uncaching the tag to @[[!+content:phpthumbof...]]@.
- Clearing site cache doesn't update output.
- Refreshing the resource with getPage call manually with context menu "Refresh Resource" command or by opening and saving resource doesn't update output.

**Comment by gadamiak** [comment]
gadamiak submitted:

I forgot to specify my MODx version: I run git 4945198.

**Comment by yoleg** [comment]
yoleg submitted:

Update: Although I didn't do any in-depth testing, I have not had any caching issues yet in 2.1.0-rc4. All or most of these issues seem to have been resolved.
