### ISSUE TITLE
Forgotten manager password activates incorrect user

### ISSUE THREAD

**Issue by pavsyk** [modxbot/migrate#4382]
pavsyk created Redmine issue ID 4382

If 'allow_multiple_emails' is on and a user forgets his manager password, system may send an e-mail with activation of another user, if they share the e-mail address. 

Such user is unable to change her password without a help from admin (or another user with user managemet permissions).

**Comment by garryn** [comment]
garryn submitted:

Updated so that the account is identified using the username and not the email.

https://github.com/modxcms/revolution/commit/fccc0a36459ffcacdebbf4bca80d8f8ff2f4fe6d
