### ISSUE TITLE
Manager CSS Error not allowing for CMPs

### ISSUE THREAD

**Issue by jgulledge19** [modxbot/migrate#4396]
jgulledge19 created Redmine issue ID 4396

For CMPs that are HTML based not using the ExtJS components they no longer scroll down if the content is longer then the screen size.

Test in both FF4 and Safari 5 and a couple of my CMP that don't use ExtJS that worked before I upgraded from 2.1rc1.

The attached screenshot is of the Slideshow-manager: http://modx.com/extras/package/slideshowmanager. 

Thanks for looking into it.

**Comment by jgulledge19** [comment]
jgulledge19 submitted:

I created a quick fix for this, but don't recommend adding to MODX CSS styles.  I added the following CSS to my style sheet only for CMPs that output HTML.  If time allows, I will write some JS to make the height load based on window height.

/\* Revo 2.1 rc3 CSS CMP fix: */
body div #modx-content {
    height: 700px;
    overflow: auto;
    border: 1px solid #e4e4e4;
    padding:5px;
}

**Comment by splittingred** [comment]
splittingred submitted:

Was fixed in 2.1.2.
