### ISSUE TITLE
Simplesearch search by ids/idType doesn't work

### ISSUE THREAD

**Issue by lexiconlondon** [modxbot/migrate#4431]
jimbob72 created Redmine issue ID 4431

Using the following:

@[[!SimpleSearchForm? &tpl=`mysearchform` &landing=`64` &useAllWords=`1` &searchStyle=`match` &ids=`6` &idType=`parents`]]@

This returns results from all resources, not just resource 6 and it's children.

I have also tried

@[[!SimpleSearchForm? &tpl=`mysearchform` &landing=`64` &useAllWords=`1` &searchStyle=`match` &ids=`6`]]@

This has the same result.

**Comment by Martijn1981** [comment]
Martijn1981 submitted:

This is the wrong place for SimpleSearch bugs. You should report these at https://github.com/splittingred/SimpleSearch/issues
