### ISSUE TITLE
Using certain characters in password prevents login

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#4439]
bobray created Redmine issue ID 4439

On a site upgraded from pre 2.1 to 2.1 RC3, changing the Manager password locks out the user.

I think the password hash itself is changed to PBKDF2, but the hash class in the DB remains at MD5, so neither the old or the new password works.

**Comment by opengeek** [comment]
opengeek submitted:

I cannot reproduce this behavior with any legacy MD5 users. Changing their password works as expected from Profile and when editing the User.

**Comment by BobRay** [comment]
bobray submitted:

Does the hash class change from MD5 when you do it? It remained at MD5 for me.

**Comment by webandflow** [comment]
webandflow submitted:

I've upgraded two sites from RC-1 to RC-3 and have been locked out in both circumstances.  Once the setup completes, and I'm presented with the login screen I simply can't log in.  Simple says that my username and password don't match.

**Comment by opengeek** [comment]
opengeek submitted:

I can't reproduce any of these problems. I need steps or more information. Existing MD5 users can still login fine on my setups and new ones with PBKDF2 can as well.

**Comment by opengeek** [comment]
opengeek submitted:

BobRay: there is no change, MD5 remains MD5 — only new users added in 2.1 are created with PBKDF2. There is a plugin available for download to automatically convert MD5 users to PBKDF2 when the users next login to the system...

**Comment by BobRay** [comment]
bobray submitted:

Here are my steps:
1. Upgrade a site from 2.0.8-pl to 2.1 RC3.
2. Change the admin's password.

**Comment by opengeek** [comment]
opengeek submitted:

How/where did you do 2? There are many ways to "change the admin's password"...

**Comment by BobRay** [comment]
bobray submitted:

Sorry, I should have included more details. 

I did it in Security -> Manage users. Right-clicked on the Admin and selected "Update User,"  then on "new password" and "let me choose the password."
Typed a new password twice, then saved the user.

**Comment by opengeek** [comment]
opengeek submitted:

I just upgraded a clean 2.0.8-pl to the latest release-2.1.0 branch HEAD in git and I still cannot reproduce this at all. I did get locked out for another reason after the upgrade, as the session_cookie_domain was set to / for some reason in my system settings, but this seems unrelated to this issue as I could not login at all after the upgrade, before I even attempted to change the password...

**Comment by opengeek** [comment]
opengeek submitted:

This was determined to be a a bug with using specific character strings within a password, which are being stripped by the manager login controller from the POST variables before being sent to runProcessor on the security/login action. These characters are being stripped to prevent various XSRF vulnerabilities. This occurs regardless of the password hashing method.

I am investigating solutions, but it looks like the only solution for now is going to involve preventing the use of certain characters in the password via validation rules.

**Comment by opengeek** [comment]
opengeek submitted:

There is now validation on User Create/Update -> Specify New Password and Profile -> Change Password actions to not allow the characters which are cleansed from the login form POSTs. These characters are also not allowed in the username.

These invalid characters are currently:

<pre>'"()<>;</pre>

Note that this is not enforced by the model and can be used in the username/password when other login forms do allow such characters in a POST.

Also note that this will not fix users with passwords set that already contain one of these invalid characters. Such users will have to have their passwords manually changed or reset.

**Comment by webandflow** [comment]
webandflow submitted:

There doesn't seem to be any validation in place in RC4 for the installation process.  A fresh install of RC4 doesn't prevent me from using one of these characters and so my password is accepted.  This prevents my admin user from being able to log in following the installation process.

**Comment by mkschell** [comment]
netprophet submitted:

I just tried this with rc4 and it is definitely validating the password field in the installer for me
http://easycaptures.com/fs/uploaded/423/8200854121.png

The code even seems to have been in place since early 2010.
https://github.com/modxcms/revolution/commit/250ee2f2505ac247573d78443cb7ba6011995925

Are you using Traditional, Advanced or from git, Desmond?

**Comment by webandflow** [comment]
webandflow submitted:

I've tried passwords with the ) in the installer.  None have worked.  When I run the installer again and use the same password WITHOUT the ) it works just fine. 

I haven't tried other special characters at this point - just with and without the ).

I'm using 2.1.0-rc4 traditional.

_UPDATE_ - Validation IS working for the { } characters.  However I've tried several passwords now using normal parentheses ( both left and right ) that both pass the validation in the installer and fail when I attempt to log in.

Also, I did confirm what Jason said above - that validation rules are now in place in the "Update User" section of the manager.  The same password that passed validation in the installer failed in the update user form.  Just seems like we need to apply the same validation rules to the installer as we do to the update/change user from inside the manager.

**Comment by mkschell** [comment]
netprophet submitted:

need to add validation to disallow ( and ) from passwords in installer

**Comment by webandflow** [comment]
webandflow submitted:

As I've been thinking through this a little more, this also affects upgrades from 2.0.x to 2.1.  I realize this is probably late for 2.1.0-pl but if there is a single user in a 2.0.8 install (e.g. admin), with a password containing one of these special characters, the upgrade will lock them out without any recourse of getting in, correct?

Should there be a step in the install process for existing admin users to select a new password?  Not sure off the top of my head how to best approach that.

**Comment by mkschell** [comment]
netprophet submitted:

Any users with illegal password characters in their passwords, whether still in 2.0.x or upgraded to 2.1.0, will already be locked out. The solution is to change their password in the manager if there is access to a manager user that can do it, or in the case that you have outlined, directly in the db for users with md5 hashed passwords. (You can get the hash of the desired password from the command line of from a handful of sites that generate the md5 hashes of strings.)
Allowing the Administrator user to change their password during the upgrade process is an interesting idea, but it's scope is broader than just this issue, and you're right, it's too late in the 2.1.0 cycle to introduce a feature like this.

**Comment by mkschell** [comment]
netprophet submitted:

Added ( and ) characters to list of disallowed password characters in the installer, updated installer language files to change validation message
https://github.com/modxcms/revolution/commit/365778aaf14f988b04e592296b8129ef5865b697
