### ISSUE TITLE
fatal error editing Access Controls for anonymous usergroup

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#4446]
netprophet created Redmine issue ID 4446

clicking "Update User Group" context menu option on "anonymous" user group takes user to

> /manager/index.php?a=27&id=0

where the following error occurs:

> Fatal error: Call to a member function get() on a non-object in {{path}}\manager\controllers\default\security\usergroup\update.php on line 20

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/5dc1e25af0b87832be08ab8b52dfe7f98c39d2a4
