### ISSUE TITLE
Placeholder with filter passed to snippet evaluates to value in filter parameter

### ISSUE THREAD

**Issue by javadecaf** [modxbot/migrate#4452]
javadecaf created Redmine issue ID 4452

Consider the following code:

@[[!echoThis? &output=`[[!+getValue.fruit:default=`apple`]]`]]@

In this snippet call, a placeholder with a filter is passed as a parameter to the snippet.  The code in the _echoThis_ snippet itself is only one line:

@return $output@

(This is useless, of course, but it's only for demonstration purposes.)  The placeholder, _getValue.fruit_,  derives its value from an earlier call to _getParameters_, which executes the following code:

@$modx->toPlaceholders($_GET, 'getValue');
return '';@

Once again, very straightforward - this simply takes the values from $_GET, and puts them into a placeholder called _getValue_.  In the original code, therefore, the placeholder 

@[[!+getValue.fruit:default=`apple`]]@

should and does evaluate to the value of $_GET['fruit'] or, if that parameter is not found, "apple."  This is confirmed by putting the placeholder alone, elsewhere on the page.  When we pass it to the snippet, however, as in the original code, the output is "apple" - no matter what the placeholder evaluates to separately.  Since all the snippet does is to output the input, it stands to reason that the placeholder with the filter, in the context of a snippet parameter, is incorrectly evaluating to the value of the filter parameter.

**Comment by wshawn** [comment]
wshawn submitted:

Curious:
Have you tried calling the TV as uncached?

I understand your thinking here, it should be pretty straight forward.  The other "solution" would be to:
[[!echoThis:default=`apple`?output=`[[!+getValue.fruit]]`]]

**Comment by javadecaf** [comment]
javadecaf submitted:

Sorry, I don't understand your question - I didn't use a TV in the example.  Do you mean the snippet, or the placeholder?  Both of these are already called uncached.  Since I'm not really clear on the effects of caching, I did try changing them to cached, both individually and combined, but none of these combinations altered the output.  Passing a URL parameter of "?fruit=peach", I still get an output of "apple".  By contrast, when I call the placeholder separately:

@[[!+getValue.fruit:default=`apple`]]@

I get the correct output, "peach".

I also tried the alternate construction you suggested:

@[[!echoThis:default=`apple`?output=`[[!+getValue.fruit]]`]]@

This doesn't parallel the real-world situation where I first encountered the problem, in which the snippet was a call to the Gallery plugin, rather than a simple "output = input" script.  It doesn't work in any case, though; it will return the parameter if found, but if not, it returns null.  I'm not a MODx dev (or anything close to it) but my guess is that, once again, this has to do with the way placeholders are evaluated in the context of snippet parameters.  The "default" filter will only return the value passed to it if the subject of the filter (perhaps not the right term, but in this case, the snippet) returns an "empty" output.  If the placeholder:

@[[!+getValue.fruit]]@

evaluates programmatically to something other than null, at least in the context of a snippet parameter, is it possible that this is why the default value does not kick in?  I think if I could drill down to the PHP code, I could get the answers to these questions, but I'll leave that to those whose area of expertise it is, namely the devs.

**Comment by opengeek** [comment]
opengeek submitted:

This issue was addressed by commits made for issues #3857 and #4526
