### ISSUE TITLE
TinyMCE problem with path writing for inline images

### ISSUE THREAD

**Issue by leoandrews** [modxbot/migrate#4456]
leoandrews created Redmine issue ID 4456

This issue is getting a lot of traffic on the forums (1600 views and counting) There's an ever-growing problem with TinyMCE not writing paths correctly, regardless of whichever path option setting you use. Personally I've always worked around it by not using it for images but because there's so much interest in it, I think it needs to be looked at. 

Issue thread: http://modxcms.com/forums/index.php/topic,55391.0.html

Hopefully the fix is easy.

**Comment by splittingred** [comment]
splittingred submitted:

Please file bugs for TinyMCE in the TinyMCE tracker, here: http://github.com/splittingred/TinyMCE/issues/

This bugtracker is for core Revolution issues only.
