### ISSUE TITLE
active-node class not removed from tree when editing element after resource

### ISSUE THREAD

**Issue by ncrossland** [modxbot/migrate#4466]
ncrossland created Redmine issue ID 4466
1. Edit a document (resource in tree has active-node applied to it, and is bold)
2. Don't save or cancel the document
3. Switch to "elements" tree
4. Click on a template (or other element) to edit it
5. Click back to Resources tree

Previously edited resource is still bold.

**Comment by garryn** [comment]
garryn submitted:

Already fixed as part of a related report.
