### ISSUE TITLE
Frozen URI not displayed when editing resource

### ISSUE THREAD

**Issue by opengeek** [modxbot/migrate#4470]
opengeek created Redmine issue ID 4470

When frozen, the new URI field is not being displayed on load of the edit resource view. You have to uncheck freeze URI and recheck it to get it to display.

**Comment by mkschell** [comment]
netprophet submitted:

Fixed in https://github.com/modxcms/revolution/commit/52a5d9475f28ac257e6acb9cd8e5d5c9e8f3c572
