### ISSUE TITLE
clarify messaging around changing Template on Add/Update Resource pages

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#4472]
netprophet created Redmine issue ID 4472

The dialog box that appears when user selects a new Template for a Resource may lead the user to believe that they do not need to Save the Resource again.

> Are you sure you want to change the Template? WARNING: This will save your changes and reload the page; ensure you are ready to do so before proceeding. 

Either this message could be altered, or an additional message could be placed somewhere in the UI after the page reloads, to tell the user that they still need to Save the Resource.

**Comment by MarkH** [comment]
markh submitted:

The message definitely needs to be more clear - it seemed to me it was being saved (when creating a new resource it evidently did - it suddenly showed up in the nav tree) but when updating it just wouldn't show up on the front-end properly.

I guess this is done in a way to improve the speed / perceived speed by getting rid of some Ajax request related to grabbing TVs, but I'm not sure it's a good change to force a refresh when changing a template. 

You also can't change a template before filling in a pagetitle..

**Comment by splittingred** [comment]
splittingred submitted:

Right, the change was made to address the following issues:
- Remove AJAX loading of TVs for more stable TV loading and quicker FC rule loading
- Changing the Template in 2.0.x did not adjust the FC rules loaded; this prevents users from doing FC rules on Templates for new Resources

The text can definitely be edited.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/f2b60cdb6bf24cc2c967720dabe74d2db68b3b65
