### ISSUE TITLE
Placeholders set in uncached snippets disappear after first load

### ISSUE THREAD

**Issue by ncrossland** [modxbot/migrate#4476]
ncrossland created Redmine issue ID 4476
1. Clear site cache to ensure fresh start,
2. Create a resource with 'cacheable' checked, and the following content:
   
   <pre>
   Test snippet: [[Test]]
   Test placeholder: [[+testplaceholder]]
   </pre>
3. Create a snippet called Test with the following code:

<pre>
<?php
$modx->setPlaceholder('testplaceholder', 'testvalue');
return 'Snippet output';
</pre>

1. View the page in front end. Output is:
   
   <pre>
   Test snippet: Snippet output
   Test placeholder: testvalue
   </pre>
2. Refresh the page, output is now:
   
   <pre>
   Test snippet: Snippet output
   Test placeholder:
   </pre>

(the placeholder value has been lost).
1. Reload the page - it continues to be lost.
2. Clear the site cache 
3. Reload the page - it appears again, but only on the first load. Reloading again loses the value.

See screenshot attached for caching settings.

**Comment by opengeek** [comment]
opengeek submitted:

Placeholder tags cannot be cached. Placeholder tags always reflect placeholder values set in the scope of any Element as it is processed. Once it is processed, the placeholders go out of scope. If they were cached as Element tags the way other tags are, you could not iterate over Chunk tpls; the first execution would cache the value and all additional iterations would simply return those same placeholder tag values.

This means if you want to use a placeholder tag outside of an Element in which it is being set, you must make sure that Element is not cacheable. The placeholder will never be set after the first load of the Resource if the Snippet setting a placeholder is cacheable on a cacheable Resource.

IOW, this will work:

<pre>
Test snippet: [[!Test]]
Test placeholder: [[+testplaceholder]]
</pre>

And this will not:

<pre>
Test snippet: [[Test]]
Test placeholder: [[+testplaceholder]]
</pre>

**Comment by ncrossland** [comment]
ncrossland submitted:

If you change the setting "Disable Global Cache Options" (setting_cache_disabled) to disable ALL caching features, it still happens as I describe. If I've turned all caching off, the snippet should be being run every time, and filling the placeholder every time?

**Comment by opengeek** [comment]
opengeek submitted:

Disable global cache options does not work at the current time. You would need to set cache_resource to 0.
