### ISSUE TITLE
PHP errors from PHPThumb - calling functions with array instead of string

### ISSUE THREAD

**Issue by ncrossland** [modxbot/migrate#4477]
ncrossland created Redmine issue ID 4477

PHPThumb is generating errors, as it is trying to call functions which expect a string with an array.

On line 3171 of /core/model/phpthumb/phpthumb.class.php, is this code:

<pre>
 $gd_image = call_user_func($ImageCreateFromFunctionName,array($filename));
</pre>

In this case, it is calling one of these PHP native functions (specified lines 3156 - 3159):

<pre>
1  => 'ImageCreateFromGIF',
2  => 'ImageCreateFromJPEG',
3  => 'ImageCreateFromPNG',
15 => 'ImageCreateFromWBMP',
</pre>

all of which expect a string of the filename, rather than an array. Therefore line 3171 should be changed to:

<pre>
 $gd_image = call_user_func($ImageCreateFromFunctionName, $filename);
</pre>

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/c278a3635f9dcbcffa15fbabadcd808ae2230b7e
