### ISSUE TITLE
html title in manager

### ISSUE THREAD

**Issue by theuros** [modxbot/migrate#4483]
theuros created Redmine issue ID 4483

when i develop a site, i have multiple tabs open in wich i edit chunks, snippets ect...  all tabs have title "MODx :: MODx Revolution" it will be a nice thing to change titles to name of the open element

so instead of  "MODx :: MODx Revolution" you get

MODx :: my-snippet   or   MODx :: chunk-name

**Comment by splittingred** [comment]
splittingred submitted:

Already done in 2.1.
