### ISSUE TITLE
Cannot use external targets in modUser->loadAttributes

### ISSUE THREAD

**Issue by splittingred** [modxbot/migrate#4502]
splittingred created Redmine issue ID 4502

This prevents using custom modAccessibleObject classes, since the modUser object never gets the ACLs on load. 

The hard-coded queries there should be a static method in their target classes, so that MODX can look for such static methods in any custom classes.

**Comment by opengeek** [comment]
opengeek submitted:

See commit details at https://github.com/modxcms/revolution/commit/9a562db719763a1af2d1fea00a5d2dca5b39bbf2
