### ISSUE TITLE
When Element has category added, Element Tree has injection but retains old position as well untill page refresh

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#4525]
wshawn created Redmine issue ID 4525

Simply create a category
Edit Element (in my case it was Chunks)
Change the Category 
Save

Element Tree will display the injection of the item at the new location
Old location remains until fill page refresh or the Element Tree is reloaded on some other action.

**Comment by garryn** [comment]
garryn submitted:

Fixed as part of [#2638].
