### ISSUE TITLE
Fatal error when trying to update Usergroup "anonymous"

### ISSUE THREAD

**Issue by XoD** [modxbot/migrate#4538]
xod created Redmine issue ID 4538

I stumbled over this while trying to grant access to new created contexts for the anonymous usergroup. The problem doesn't exist for the Adminstartor Usergroup, there I can right-click > update usergroup without problems. When I try the same for the anonymous Usergroup I get the following error:

<pre>
Fatal error: Call to a member function get() on a non-object in /home/exsidech/public_html/blackspot/manager/controllers/default/security/usergroup/update.php on line 20
</pre>

I checked the file and it seems to be this line of code:

<pre>
$modx->smarty->assign('_pagetitle',$modx->lexicon('user_group').': '.$usergroup->get('name'));
</pre>

so I simply commented it out and after that it works as expected...sorry for not providing a real fix but I had to make it work fast =)...hope you know what the issue is there!

thanks for your great work!

**Comment by opengeek** [comment]
opengeek submitted:

I cannot reproduce this in RC4. Can you confirm or deny this behavior still exists for you in RC4?

**Comment by XoD** [comment]
xod submitted:

Hi Jason,

installed a 2.1rc4 yesterday and it works flawless. Could you reproduce it in rc3 or was it maybe just my installation?

regards

**Comment by opengeek** [comment]
opengeek submitted:

I could not reproduce in my RC3 either. But we'll call it fixed until it rears it's ugly head again...
