### ISSUE TITLE
Quick Edit UI / Popup paste-"overstretching"

### ISSUE THREAD

**Issue by XoD** [modxbot/migrate#4539]
xod created Redmine issue ID 4539

I'm not 100% sure, but I think this "issue" is present since 2.1rc3. When I for example Quick-Create a chunk in the Elements Tree via right-click Quick-Create > Chunk the popup opens nicely and as usual (I like the Save and Close Button, by the side =D) but when I paste in a long chunk of code (for example the code of a whole form) the popup stretches over the bottom edge of the browser window so I can't get to the save button anymore (scrolling the main window doesn't help, popup seems to have fixed positioning?). It's somehow possible by dragging'n'dropping the popup but with very long paste-ins this doesn't help too...another option is to use the tab key until the save button is activated, then press enter (or click it). While the click-the-save-button works as expected the behaviour when pressing enter is very strange...it somehow cuts off a big part of the manager page and only shows white...a F5 reload of the whole manager helps to see anything again, but I don't think that this behaviour is planned =)...

**Comment by XoD** [comment]
xod submitted:

This one should maybe changed to a "minor bug", it's also present in 2.1rc4 and seems to have some other related things not working...

if I just open a ressource to edit, it is cut-off at the bottom, no matter how big the browser window is...scrolling down doesn't reveal the whole conten-textarea (scrolling in the text-area doesn't do it either...) --> see screenshot...

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/dd617ed9600762be85bb79fd8155541b1acea6e7
