### ISSUE TITLE
in 2.1.0-rc4 lost the ability to have cyrillic context description

### ISSUE THREAD

**Issue by yurkobb** [modxbot/migrate#4550]
yurkobb created Redmine issue ID 4550

Hello,

I'm working on 2 sites on same hosting provider (byethost free account), one runs on 2.1.0-rc3 and other one -- on 2.1.0-rc4.

In rc4 i noticed that when i save a cyrillic context description it turns into sequence of "?"s. On rc3, there's no such thing happening. The mysql charset is utf8 on both sites.

Thank you!

**Comment by yurkobb** [comment]
yurkobb submitted:

Well, looks like the same with resources. UTF-8 strings get replaced with "?"s in all the fields...

**Comment by yurkobb** [comment]
yurkobb submitted:

Ok, i found the problem. It was something during installation, because in phpmyadmin i see "latin1_swedish_ci" as collation encoding. It was my mistake i suppose. Sorry for disturbing.

**Comment by yurkobb** [comment]
yurkobb submitted:

Again an update.

I tried to reinstall modx, and during installation selected utf8 as mysql session charset and utf_bin as the collate charset.

But after checking it in phpmyadmin i saw latin_swedish_cl as collate charset again. Only after emptying the db and setting utf8 as default collate charset _in phpmyadmin_ modx was able to create the tables properly.

I'm still not sure if it's modx bug or hostings, but just in case...

Thank you very much for all your work!

**Comment by opengeek** [comment]
opengeek submitted:

This is not a bug. You need to manually set the collation of the database if you create it via your hosting provider before installing MODX. MODX will not change the database collation, but will create the database with the correct collation if it does not yet exist when you run setup, assuming you have permission to create databases with the database user you are installing MODX with.

**Comment by yurkobb** [comment]
yurkobb submitted:

Thank you for answering.

Then maybe hide the collation charset chooser when using pre-existing database and warn if one of the charsets is not utf8?
Just an idea.
Thanks.
