### ISSUE TITLE
Wrong update message from www.modx.com provider

### ISSUE THREAD

**Issue by Coroico** [modxbot/migrate#4551]
coroico created Redmine issue ID 4551

See [[http://modxcms.com/forums/index.php/topic,59202.msg362080.html#msg362080]] for more details

gmaps101_331.zip is the evo version of Gmaps. 
Unfortunately this package (without a transport.zip extension) is highlighted as possible update for the revo version (gmaps-1.0.0-pl.transport.zip)

May be the "transport.zip" should be mandatory for revo packages.

This trouble doesn't occur when the package is installed from locally. Only from www.modxcms.com

**Comment by splittingred** [comment]
splittingred submitted:

Fixed now. Thanks!
