### ISSUE TITLE
Hide menu item from menus issue

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#4560]
onepack created Redmine issue ID 4560

When I decide to show/hide an existing page in the menu and save the resource it will still show on the frontend. A cache refresh on the frontend and a site cache clearing on the backend don't even seem to fix things. Sometimes the menu item is hidden on one page but still visible on other pages.

**Comment by opengeek** [comment]
opengeek submitted:

I cannot reproduce this. I believe this may be an issue with the version of Wayfinder you are using. Can you disable the internal caching in your version of Wayfinder and see if this is the source of the problem? If so, this needs to be entered as a bug for the Wayfinder extra.

**Comment by onepack** [comment]
onepack submitted:

Yes, you are right... The issue disappears when I turn off wayfinder caching. Turning it back on results in the above behavior after clicking around and show/hide the menu item a couple of times. You only see the change on the pages that were not cached yet. After they are cached you won't see the changes.

**Comment by Martijn1981** [comment]
Martijn1981 submitted:

A few other people have reported similar situations on https://github.com/splittingred/Wayfinder/issues/27. Unfortunately no response yet. I hope this can be fixed soon.

**Comment by onepack** [comment]
onepack submitted:

I have reported this case under: https://github.com/splittingred/Wayfinder/issues/30
