### ISSUE TITLE
Quick Update UI: can't scroll to see buttons

### ISSUE THREAD

**Issue by yurkobb** [modxbot/migrate#4563]
yurkobb created Redmine issue ID 4563

Hello,

I like the new scrolling behavior of the main edit window (when the resource tree and manager menu stays in place and only the action window scrolls) but there's one drawback: when a Quick Update popup opens in a smaller browser window, it's too big to be able to see buttons without scrolling. However, I can't scroll to see them anymore. Maybe it will be somehow possible to have another scroolbar for the whole page including popups?

Thanks.

**Comment by XoD** [comment]
xod submitted:

see also http://bugs.modx.com/issues/4539

I have it in FF 3.6 and also in Chrome 10 (didn't test further, doesn't seem to be a browser problem)

**Comment by MarkH** [comment]
markh submitted:

Fixed as per #6496
