### ISSUE TITLE
"No currently active users" in welcome page's 'Online' section

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#4566]
netprophet created Redmine issue ID 4566

Users are no longer appearing in this list. This was working in 2.0.8.

**Comment by mkschell** [comment]
netprophet submitted:

Original table that this data came from is no longer used.
A new source for this data is likely the manager_log table, however
- cross-platform query for rows containing most recent visits of individual users, grouped by those individual users, is tricky and may not happen in one query
- IP addresses are no longer stored, so some changes to the template are needed

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/9018c3d8e64d864ca5349d4f9c2b36be66a75a18
