### ISSUE TITLE
getResources tvFilters BUG

### ISSUE THREAD

**Issue by 7471697** [modxbot/migrate#4597]
galliush created Redmine issue ID 4597

using &tvFilters, makes options: &where, &context, &showDeleted, &showUnpublished, &showHidden, &hideContainers, &resources, unuseful at the query resources.

Sory for my english.

**Comment by 7471697** [comment]
galliush submitted:

using &tvFilters, makes options: &where, &context, &showDeleted, &showUnpublished, &showHidden, &hideContainers, &resources, are not significant at the query resources.

**Comment by opengeek** [comment]
opengeek submitted:

This bug needs to filed for getResources at https://github.com/opengeek/getResources/issues
