### ISSUE TITLE
Resource Group Access stopped working

### ISSUE THREAD

**Issue by Martijn1981** [modxbot/migrate#4600]
Martijn1981 created Redmine issue ID 4600

Resource Group Access Policies have stopped working properly. Here's how to track down the bug:
# Security > Resource Groups > Create Resource Group. "Secured pages" for example.
# Security > Access Controls > Right-click on "Administrator" User Group > Update User Group
# Resource Group Access > Add Resource Group > Resource Group: Secured pages, Minimum role: 0, Access Policy: resource, Context: mgr > Save
# Security > Resource Groups > now add a Page to the "Secured pages" Resource Group.

The page completely disappears when you're logged in as a user in the "Administrator" User Group! That shouldn't be happening.

**Comment by opengeek** [comment]
opengeek submitted:

I cannot reproduce this, but I noticed you did not mention Flush Permissions or Clear Cache in your steps.

After changing any access controls, on the User side, you'll need to Flush Permissions (or Flush Sessions to make changes immediately affect other users than the one you are logged in as) before a user will have the new access policies loaded into their MODX session. For the Resources, you will also need to Clear Cache so the policy changes are respected by any Resources that are cacheable.

**Comment by Martijn1981** [comment]
Martijn1981 submitted:

It seems to work properly now.... the only thing I've changed in the past couple of days was assigning 10 FC-sets to a lower usergroup. Before that, those FC-sets were active for every usergroup, including Administrators.

You can close this issue, but can you give me any insight on whether ACLs and FC sets are related in the back-end in any way? Perhaps there was some connection.

**Comment by opengeek** [comment]
opengeek submitted:

Martijn van Turnhout wrote:

> You can close this issue, but can you give me any insight on whether ACLs and FC sets are related in the back-end in any way? Perhaps there was some connection.

Might be better to ask in the forums about this, as my knowledge of FC sets are minimal.

**Comment by onepack** [comment]
onepack submitted:

I have the exact same issue with one of my projects after upgrading to the latest rc4. All the admin templates simply dissapeared. I had to assign the templates in the database to other gategories to make them visible again. Same with the tv's assigned to the admin alone.

**Comment by opengeek** [comment]
opengeek submitted:

That is a different issue onepack — see https://github.com/modxcms/revolution/commit/46dcec6fb85f993b378c9a5e159f896b1c19f53d
