### ISSUE TITLE
change installer references to "connector context" since no longer a context

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#4606]
netprophet created Redmine issue ID 4606

Connectors were at one time a "context" in MODX, but their relationship to contexts is now more flexible, loosely coupled and therefore of course complex.
So as to avoid confusion, connectors should no longer be called a context in the installer.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/09d0ccded7c5e4fdc24342d6269d5854b029d42e
