### ISSUE TITLE
"set_locale" should be part of System Settings

### ISSUE THREAD

**Issue by Martijn1981** [modxbot/migrate#4610]
Martijn1981 created Redmine issue ID 4610

See my forum post: http://modxcms.com/forums/index.php/topic,64146.0.html. 

I'm not a programmer, so i was actually surprised to see that I actually had to write a plugin to set the "locale" on nl_NL. An option to modify "setlocale" should be part of System Settings and be located in the "Language" category.

For a system that's actually pretty good with Internationalization, I was surprised to see I just couldn't flip a switch in the System Settings. This should definitely be made possible.

**Comment by Martijn1981** [comment]
Martijn1981 submitted:

Or better yet: add an output filter to Revolution. Something like :locale=`nl_NL`. That would solve a _lot_ of things.

**Comment by gadamiak** [comment]
gadamiak submitted:

This one is quite old now ;) See #236

**Comment by Martijn1981** [comment]
Martijn1981 submitted:

I see, but I'm still strongly _for_ including this in system settings. It would be extremely useful for handling multilingual websites with different contexts. I'm sure others would agree with me.

**Comment by gadamiak** [comment]
gadamiak submitted:

Martijn van Turnhout wrote:

> I see, but I'm still strongly _for_ including this in system settings.

Definitely. I'm missing it too.

**Comment by mindeffects** [comment]
mindeffects submitted:

I allways include a snippet with "setlocale(LC_TIME, 'de_DE')" to get correct date format. I would love to see that replaced by a system setting! ;-)

**Comment by splittingred** [comment]
splittingred submitted:

Added for 2.2: https://github.com/modxcms/revolution/commit/66cf2fd13f58b74deb2dd21a0f422e39fb23e4be
