### ISSUE TITLE
Remove QuickUpdate

### ISSUE THREAD

**Issue by johnywhy** [modxbot/migrate#4611]
johnywhy created Redmine issue ID 4611

seems totally redundant. does not seem to offer any advantage over normal edit screen.

**Comment by mkschell** [comment]
netprophet submitted:

The advantage is that if you can edit several things without requiring a page reload. For example, if you're on an Edit Resource page, you can have a quick look at the contents of a Chunk, update it if you wish, and then continue editing the Resource.

**Comment by johnywhy** [comment]
johnywhy submitted:

Mike Schell wrote:

> The advantage is that if you can edit several things without requiring a page reload

Then, to edit several things at once, make it a true MDI-- Multiple Document Interface. Currently, its like the object in the Main window is "the main thing i'm editing, and these other items are subordinate."

And, to avoid page-reloads, make ALL the editors Quick Editors. The whole thing should be ajaxified anyway.

**Comment by johnywhy** [comment]
johnywhy submitted:

Sorry, I shouldn't say should. Just offering another perspective. You could be right.

**Comment by johnywhy** [comment]
johnywhy submitted:

MDI as in each item being edited opens in a separate tab or window. Windows could be on separate tabs. 

If users prefer a window for each object, I can imagine a system setting called:
MDI_arrangement

with values:
tiled, cascaded, tabbed.

Then modx would automatically arrange the windows for me. I do not want to waste my time rearranging windows, and i don't want clutter. 

Have the ability to manually switch between tiled, cascaded, or tabbed during editing. 

The object that has focus would auto-sync the Resource Tree.

**Comment by johnywhy** [comment]
johnywhy submitted:

advantage of a tabbed MDI is that each object gets full screen real estate always.

But for those who prefer cascaded or tiled, have a quick way to go full-size on the active editor (1 keyboard way, 1 mouse way. see http://modxcms.com/forums/index.php/topic,64153.0.html)

**Comment by XoD** [comment]
xod submitted:

So are preferences different from user to user =)...I love the quick edit thing, has speeded up my work dramatically. I agree with ajaxifying the whole interface (ie the main edit pages, so it does speed up the manager-reloading btw. makes it obsolet). It's anyway not usable without javascript, so why not make it a hardcore-ajax interface =)...

maybe the "tabbed MDI"-idea is also worth a thought, but I can't really imagine how it feels (never worked with one^^)

**Comment by splittingred** [comment]
splittingred submitted:

We will not be removing Quick Update. A MDI-interface was attempted at first, but problems occurred in older browsers, as well as with ExtJS at the time. Another attempt may occur post ExtJS4 upgrade, if possible.
