### ISSUE TITLE
Dropdown List Menu Not Available

### ISSUE THREAD

**Issue by rossco** [modxbot/migrate#4612]
rossco created Redmine issue ID 4612

After upgrading from rc3 to rc4 (revo 2.1) the DropDown List menu option in TVs is not in the list of Input Options.

Having checked the rc4 changes, I did not see this being dropped so I'm reporting this as a bug.

**Comment by splittingred** [comment]
splittingred submitted:

It has been deprecated, since its nearly identical to Listbox (Single-Select). Use that one instead.
