### ISSUE TITLE
Implement Ctrl-S to save objects in editor.

### ISSUE THREAD

**Issue by johnywhy** [modxbot/migrate#4615]
johnywhy created Redmine issue ID 4615

Implement Ctrl-S to save objects in editor.

**Comment by XoD** [comment]
xod submitted:

I think this is done in 2.1rcX...it does not work for the quick-edit popups, but for the rest (normal ressource/element editing) it does save with Ctrl+S.

**Comment by splittingred** [comment]
splittingred submitted:

Correct.
