### ISSUE TITLE
Combine Trees Vertically

### ISSUE THREAD

**Issue by johnywhy** [modxbot/migrate#4619]
johnywhy created Redmine issue ID 4619

Rather than putting trees onto separate tabs, combine them vertically on a single tab. 

With ability to collapse each of the 3 top levels. 

And ability to drag/drop between them. 

Some drag/drops might initialize a conversion, such as dragging from the File tree to the Resources tree, and vice versa.

**Comment by splittingred** [comment]
splittingred submitted:

No, there is strict separation between the trees to prevent confusion between the abstractions. Combination of the three would increase confusion. There is also no reason to do "conversions", as those would not be seamless or preferred.

Also, combining would cause too much horizontal scrolling in the left-hand tree.
