### ISSUE TITLE
Fix Position of Tree Panel

### ISSUE THREAD

**Issue by johnywhy** [modxbot/migrate#4620]
johnywhy created Redmine issue ID 4620

so as user scrolls down, the trees remain visible.

**Comment by johnywhy** [comment]
johnywhy submitted:

darn, supposed to be an improvement, not a bug, admin please fix

**Comment by splittingred** [comment]
splittingred submitted:

Already done in 2.1.

**Comment by johnywhy** [comment]
johnywhy submitted:

please reopen, and add header menus as well. only the editing pane should scroll.

**Comment by splittingred** [comment]
splittingred submitted:

It does as expected. Please refer to 2.1.
