### ISSUE TITLE
2.1rc4 Install error - Memory issue

### ISSUE THREAD

**Issue by jgulledge19** [modxbot/migrate#4622]
jgulledge19 created Redmine issue ID 4622

I did an upgrade and a complete new install on 2 different boxes.  My boxes are both Windows 2008R2 with IIS7 and PHP 5.3\* and MySQL 5.5_.  IIS gives a 500 Internal Server Error.  I have checked my logs and this is the only clue I can find:
*[04-May-2011 13:34:30] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 261904 bytes) in C:\inetpub\wwwroot\core\xpdo\xpdo.class.php on line 2045_

Then I went and changed the memory in these files listed below to 256M and it still errored out.  I then set them to 512M and then it did not error out just returned a white screen with no error logged or reported.  On the new install I can not use the manager it shows a 404 even though the file is there.

Search "ini_set(" (12 hits in 8 files)
  C:\inetpub\wwwroot\setup\includes\checks\modinstalltestadvanced.class.php (1 hits)
    Line 28:             $success = @ini_set('memory_limit','128M');
  C:\inetpub\wwwroot\setup\includes\checks\modinstalltestgit.class.php (1 hits)
    Line 27:             $success = @ini_set('memory_limit','128M');
  C:\inetpub\wwwroot\setup\includes\checks\modinstalltestsdk.class.php (1 hits)
    Line 28:             $success = @ini_set('memory_limit','128M');
  C:\inetpub\wwwroot\setup\includes\checks\modinstalltestsvn.class.php (1 hits)
    Line 27:             $success = @ini_set('memory_limit','128M');
  C:\inetpub\wwwroot\setup\includes\modinstall.class.php (2 hits)
    Line 327:         @ ini_set('memory_limit','128M');
  C:\inetpub\wwwroot\setup\includes\modinstalltest.class.php (1 hits)
    Line 87:             $success = @ini_set('memory_limit','24M');
  C:\inetpub\wwwroot\setup\index.php (3 hits)
    Line 31: ini_set('memory_limit', '256M');// I added this at first

**Comment by jgulledge19** [comment]
jgulledge19 submitted:

_For my new install_ 

The MODX error log had this error:
[2011-05-04 14:12:36](ERROR @ /manager/index.php) Could not load context: mgr

So I then checked the DB and there are a few things that are missing like
modx_content table - no mgr but it did have web
modx_user table- did not create admin

Attached is the full DB that was created for the new install, that should hopefully help.

Thanks

**Comment by mkschell** [comment]
netprophet submitted:

Josh, if you apply the changes from the following commits:
https://github.com/modxcms/revolution/commit/38bb1fb81de08b30418cadfdc612b2aace8d764a
https://github.com/modxcms/revolution/commit/a4e8ba35374fb9cbedabf2a223707a8e93821dd1
then run the installer again, does the problem go away?

**Comment by jgulledge19** [comment]
jgulledge19 submitted:

That fixed it, fresh install was really quick.

Thanks!
