### ISSUE TITLE
"RTE on" disabled not saved in quick-create

### ISSUE THREAD

**Issue by XoD** [modxbot/migrate#4637]
xod created Redmine issue ID 4637

When I quick-create a document and disable "Real Text Editor" in the settings tab (system settings it's default "on") it's not saved. I have to re-open the document (quick edit or normal) and disable the RTE setting again, then it's saved.

**Comment by garryn** [comment]
garryn submitted:

Fixed.

https://github.com/modxcms/revolution/commit/de7c93607bb680667f72621a9745490b35ca91e6
