### ISSUE TITLE
Placeholders inside of output filters are not being processed.

### ISSUE THREAD

**Issue by yoleg** [modxbot/migrate#4638]
yoleg created Redmine issue ID 4638

For 2.1.0-RC4, here are the steps to reproduce this:
1. Create a chunk called TestChunk and place the following inside: 
   
   <pre>
   Nested Deeply: [[+message:notempty=`[[label:notempty=`[[name:replace=`_== `:ucwords`]]`]]`]]
   <br />Nested Once: [[+label:notempty=`[[+name]]`]]
   <br />Not Nested Test 1: [[+name:replace=`_== `:ucwords]]
   <br />Not Nested Test 2: [[+name:notempty=`Hello World`]]
   <br />Simplest: [[+name]]
   </pre>
2. Now place the chunk somewhere on the page and set the name placeholder: 
   
   <pre>
   [[$TestChunk? &name=`hello_world`]]
   </pre>

The result is:

<pre>
Nested Deeply: 
Nested Once: 
Not Nested Test 1: Hello World 
Not Nested Test 2: Hello World 
Simplest: hello_world
</pre> 

The result _should be_:

<pre>
Nested Deeply: Hello World
Nested Once: hello_world
Not Nested Test 1: Hello World 
Not Nested Test 2: Hello World 
Simplest: hello_world
</pre>

Note: caching or uncaching the chunk does not seem to effect results.

**Comment by opengeek** [comment]
opengeek submitted:

Actually, this is parsing exactly as expected. I think you meant to use this in your chunk to get the expected results you posted here:

<pre>
[[+message:empty=`[[label:notempty=`[[name:replace=`_== `:ucwords`]]`]]`]]
<br />Nested Once: [[+label:empty=`[[+name]]`]]
<br />Not Nested Test 1: [[+name:replace=`_== `:ucwords]]
<br />Not Nested Test 2: [[+name:notempty=`Hello World`]]
<br />Simplest: [[+name]]
</pre>

**Comment by yoleg** [comment]
yoleg submitted:

Whoops, sorry, you're right. Actually, there's a couple differences.

Here is the new TestChunk:

<pre>
Nested Deeply: [[+message:default=`[[+label:default=`[[+name]]`]]`]]
<br />Nested Deeply w/ OF: [[+message:default=`[[+label:default=`[[+name:replace=`_== `:ucwords`]]`]]`]]
<br />Nested Once: [[+label:default=`[[+name]]`]]
<br />Nested Once w/ OF: [[+label:default=`[[+name:replace=`_== `:ucwords`]]`]]
<br />Not Nested w/ OF: [[+name:replace=`_== `:ucwords]]
<br />Not Nested w/ OF 2: [[+name:default=`Hello World`]]
<br />Simplest: [[+name]]
</pre>

And this results in:

<pre>
Nested Deeply: hello_world 
Nested Deeply w/ OF: 
Nested Once: hello_world 
Nested Once w/ OF: 
Not Nested w/ OF: Hello World 
Not Nested w/ OF 2: hello_world 
Simplest: hello_world
</pre>

So I think nesting breaks only if there's a [placeholder with an output filter] inside of an output filter. This also seems to break for placeholders inside of snippet parameters.

Sorry for the mistake!

**Comment by opengeek** [comment]
opengeek submitted:

You have a syntax error in this example that prevents your nested with output filters scenario from working. The correct chunk should be:

<pre>
Nested Deeply: [[+message:default=`[[+label:default=`[[+name]]`]]`]]
<br />Nested Deeply w/ OF: [[+message:default=`[[+label:default=`[[+name:replace=`_== `:ucwords]]`]]`]]
<br />Nested Once: [[+label:default=`[[+name]]`]]
<br />Nested Once w/ OF: [[+label:default=`[[+name:replace=`_== `:ucwords]]`]]
<br />Not Nested w/ OF: [[+name:replace=`_== `:ucwords]]
<br />Not Nested w/ OF 2: [[+name:default=`Hello World`]]
<br />Simplest: [[+name]]
</pre>

This works as expected.

Notice you had an extra ` after ucwords on the instances that were failing.

**Comment by yoleg** [comment]
yoleg submitted:

Now I am very confused.  When I copy and paste your code below, it works for me. However, removing ONE of the output filters (in the LOWER line) with the backspace key - being VERY careful not to make any mistakes - causes the code to break in BOTH "Nested w/ OF" lines, including the one I did not touch. Typing it manually back in makes it work again in both.

Could this be a character encoding issue? Or perhaps a codemirror issue?

I'm sure I'm causing the error somehow - but this bug has been very consistent in my installation, and I would really like to get rid of it.

Here is the working chunk that I copied and pasted directly from your post above:

<pre>
Nested Deeply: [[+message:default=`[[+label:default=`[[+name]]`]]`]]
<br />Nested Deeply w/ OF: [[+message:default=`[[+label:default=`[[+name:replace=`_== `:ucwords]]`]]`]]
<br />Nested Once: [[+label:default=`[[+name]]`]]
<br />Nested Once w/ OF: [[+label:default=`[[+name:replace=`_== `:ucwords]]`]]
<br />Not Nested w/ OF: [[+name:replace=`_== `:ucwords]]
<br />Not Nested w/ OF 2: [[+name:default=`Hello World`]]
<br />Simplest: [[+name]]
</pre>

And the broken chunk that breaks BOTH of the "Nested w/ OF" lines. The ONLY change is that I removed @:ucwords@ (very carefully) from the "Nested Once w/ OF" line.

<pre>
Nested Deeply: [[+message:default=`[[+label:default=`[[+name]]`]]`]]
<br />Nested Deeply w/ OF: [[+message:default=`[[+label:default=`[[+name:replace=`_== `:ucwords]]`]]`]]
<br />Nested Once: [[+label:default=`[[+name]]`]]
<br />Nested Once w/ OF: [[+label:default=`[[+name:replace=`_== `]]`]]
<br />Not Nested w/ OF: [[+name:replace=`_== `:ucwords]]
<br />Not Nested w/ OF 2: [[+name:default=`Hello World`]]
<br />Simplest: [[+name]]
</pre>

This results in:

<pre>
Nested Deeply: hello_world 
Nested Deeply w/ OF: 
Nested Once: hello_world 
Nested Once w/ OF: 
Not Nested w/ OF: Hello World 
Not Nested w/ OF 2: hello_world 
Simplest: hello_world
</pre>

The same thing happens when I remove @:replace=`_==`@ instead:

<pre>
Nested Deeply: [[+message:default=`[[+label:default=`[[+name]]`]]`]]
<br />Nested Deeply w/ OF: [[+message:default=`[[+label:default=`[[+name:replace=`_== `:ucwords]]`]]`]]
<br />Nested Once: [[+label:default=`[[+name]]`]]
<br />Nested Once w/ OF: [[+label:default=`[[+name:ucwords]]`]]
<br />Not Nested w/ OF: [[+name:replace=`_== `:ucwords]]
<br />Not Nested w/ OF 2: [[+name:default=`Hello World`]]
<br />Simplest: [[+name]]
</pre>

As a reminder, the test chunk is being placed like so: @[[$TestChunk? &name=`hello_world`]]@

How can it be breaking in BOTH lines, when I only touch ONE of them? Is there something wrong with my Browser/ editor? Is there any other way I can troubleshoot this?

**Comment by yoleg** [comment]
yoleg submitted:

I narrowed down the problem.

First of all, the problem is not with CodeMirror, because I disabled it and the problem still happened. 

Secondly, the problem does NOT only happen when output filters are used on the inside placeholders.

Jason's chunk worked only because the non-nested placeholders were being processed and used for all of the nested chunks. If you remove all non-nested placeholders, the chunk breaks again, but this time for all lines, not just the ones with output filters. In other words, if I use the original, working chunk that I copied and pasted from Jason's post above and remove the "Not Nested w/ OF" line OR change its output filter from ucwords to ucase OR remove the bottom three lines, the chunk breaks again:

Working:

<pre>
Nested Deeply: [[+message:default=`[[+label:default=`[[+name]]`]]`]]
<br />Nested Deeply w/ OF: [[+message:default=`[[+label:default=`[[+name:replace=`_== `:ucwords]]`]]`]]
<br />Nested Once: [[+label:default=`[[+name]]`]]
<br />Nested Once w/ OF: [[+label:default=`[[+name:replace=`_== `:ucwords]]`]]
<br />Not Nested w/ OF: [[+name:replace=`_== `:ucwords]]
<br />Not Nested w/ OF 2: [[+name:default=`Hello World`]]
<br />Simplest: [[+name]]
</pre>

Not Working example 1 (only thing changed is in line 5, changed ucwords to ucase):

<pre>
Nested Deeply: [[+message:default=`[[+label:default=`[[+name]]`]]`]]
<br />Nested Deeply w/ OF: [[+message:default=`[[+label:default=`[[+name:replace=`_== `:ucwords]]`]]`]]
<br />Nested Once: [[+label:default=`[[+name]]`]]
<br />Nested Once w/ OF: [[+label:default=`[[+name:replace=`_== `:ucwords]]`]]
<br />Not Nested w/ OF: [[+name:replace=`_== `:ucase]]
<br />Not Nested w/ OF 2: [[+name:default=`Hello World`]]
<br />Simplest: [[+name]]
</pre>

Example 1 result:

<pre>
Nested Deeply: hello_world 
Nested Deeply w/ OF: 
Nested Once: hello_world 
Nested Once w/ OF: 
Not Nested w/ OF: HELLO WORLD 
Not Nested w/ OF 2: hello_world 
Simplest: hello_world
</pre>

Not working example 2 (only thing I changed was I deleted the bottom 3 lines):

<pre>
Nested Deeply: [[+message:default=`[[+label:default=`[[+name]]`]]`]]
<br />Nested Deeply w/ OF: [[+message:default=`[[+label:default=`[[+name:replace=`_== `:ucwords]]`]]`]]
<br />Nested Once: [[+label:default=`[[+name]]`]]
<br />Nested Once w/ OF: [[+label:default=`[[+name:replace=`_== `:ucwords]]`]]
</pre>

Example 2 result: 

<pre>
Nested Deeply: 
Nested Deeply w/ OF: 
Nested Once: 
Nested Once w/ OF:
</pre>

Please try the examples above and see if they break for you.

**Comment by opengeek** [comment]
opengeek submitted:

Another ticket was opened for the valid bug identified in the previous comment...
