### ISSUE TITLE
Enable Undo After Save

### ISSUE THREAD

**Issue by johnywhy** [modxbot/migrate#4644]
johnywhy created Redmine issue ID 4644

it's necessary to save before previewing, but then impossible to undo the change if it does not look right in the preview.

feature: retain undo history after a save. 

this is consistent with MODx's awesome feature of not refreshing page after a save, so the scroll position of the editor does not change.

**Comment by splittingred** [comment]
splittingred submitted:

This will be available when Versioning is added. Closing this issue, as it's a part of a larger Roadmap feature. Thanks!
