### ISSUE TITLE
install error 2.1 adv

### ISSUE THREAD

**Issue by samz** [modxbot/migrate#4649]
samz created Redmine issue ID 4649

Empty page on action "?action=install"
Modx stop to create tables in db after creating "modx_system_eventnames"
Then after I reload page, modx complete installation successfully.

Then I install try to install modx in the same db twice with another prefix  modx create just tables:
dbo.modx1_access_actions
dbo.modx1_access_actions
dbo.modx1_access_category
dbo.modx1_access_context
dbo.modx1_access_elements
dbo.modx1_access_menus
dbo.modx1_access_menus
dbo.modx1_access_permissions

after reload i still have just empty page

core /cache/log  is empty

_installation check_
_Pre-installation tests were successful. Click Install below to continue._

```
Checking PHP version: OK! Running: 5.3.6
Checking PHP for zlib dependency: OK!
Checking for SimpleXML: OK!
Checking if memory limit is set to at least 24M: OK! Set to 128M
Checking if sessions are properly configured: OK!
Checking if C:/inetpub/wwwroot/server.test/modx-evo.test/core/cache directory exists: OK!
Checking if C:/inetpub/wwwroot/server.test/modx-evo.test/core/cache directory is writable: OK!
Checking if C:/inetpub/wwwroot/server.test/modx-evo.test/core/export directory exists: OK!
Checking if C:/inetpub/wwwroot/server.test/modx-evo.test/core/export directory is writable: OK!
Checking if C:/inetpub/wwwroot/server.test/modx-evo.test/core/packages directory exists: OK!
Checking if C:/inetpub/wwwroot/server.test/modx-evo.test/core/packages directory is writable: OK!
Checking if C:/inetpub/wwwroot/server.test/modx-evo.test/core/config/config.inc.php exists and is writable: OK!
Creating connection to the database: OK!
Checking to make sure safe_mode is off: OK!
Checking if memory limit is set to at least 24M for zip extensions: OK! Set to 128M
Checking if C:/inetpub/wwwroot/server.test/modx-evo.test/ directory is writable: OK!
Checking if C:/inetpub/wwwroot/server.test/modx-evo.test/manager/ directory is writable: OK!
Checking if C:/inetpub/wwwroot/server.test/modx-evo.test/connectors/ directory is writable: OK!
```

**Comment by mkschell** [comment]
netprophet submitted:

Sam,
Please see my comments in this ticket
http://bugs.modx.com/issues/4622#note-3
.. I think your issue sounds the same as this.
Please reopen if the suggested changes don't fix your problem.
