### ISSUE TITLE
unable to create new Static Resource in 2.1 RC4 with Firefox Mac

### ISSUE THREAD

**Issue by lukemcd** [modxbot/migrate#4654]
lukemcd created Redmine issue ID 4654

When going to create a new Static Resource with RC4 and Mac Firefox I get a blank screen in the content area. If the default template has TVs these show up as a list.

The following error comes up:
Error: console is not defined
Source File: http://www.test.com/manager/assets/modext/build/widgets/resource/modx.panel.resource.static-min.js?v=210rc4
Line: 1

**Comment by splittingred** [comment]
splittingred submitted:

Fixed; https://github.com/modxcms/revolution/commit/50386d7ad17feab606d20eefa8ac8c3ffa95e956
