### ISSUE TITLE
Add a function to use Ext layout Manager to load Components

### ISSUE THREAD

**Issue by lossendae** [modxbot/migrate#4656]
lossendae created Redmine issue ID 4656

MODx Manager use Ext viewport to handle the whole layout (and since 2.1 even the menu is included as well) with a _border layout_.
For now, all components use the function MODx.load(); to create the components in the main page, and use an additionnal div placeholder where each component is rendered.

It cause some issues:
- More div clutter in the page.
- Resize event are not fired since the main layout does not handle the loaded components.
- Some rendering issues for the same reason
- In Ext 2.1, since the main top menu is handled by the viewport, the scrolling bar goes above the components and it's impossible to solve this easily with CSS tricks.

There is another way to load components, solve the resizing issues and the scroll bar issue without breaking the compatibility with the old components.

By adding the following lines to the main MODx js class:

<pre>
,add:function( cmp ){
        center = Ext.getCmp("modx-content");
        center.removeAll();
        center.add({xtype:cmp});
        center.doLayout();
    }
</pre>

Then a component can be loaded directly using the xtype, example with setting page:

<pre>
Ext.onReady(function() {
    MODx.add('modx-page-system-settings');
});
</pre>

It require one more modification though in "_assets/modext/system/modx.panel.system.setting.js_" because this component use an additionnal created div for the grid (ct):

<pre>
/**
 * Loads the panel for managing system settings.
 * 
 * @class MODx.panel.SystemSettings
 * @extends MODx.FormPanel
 * @param {Object} config An object of configuration properties
 * @xtype modx-panel-system-settings
 */
MODx.panel.SystemSettings = function(config) {
    config = config || {};
    Ext.applyIf(config,{
        id: 'modx-panel-system-settings'
        ,bodyStyle: ''
        ,defaults: { collapsible: false ,autoHeight: true }
        ,items: [{
            html: '<h2>'+_('system_settings')+'</h2>'
            ,border: false
            ,id: 'modx-system-settings-header'
            ,cls: 'modx-page-header'
        },{
            layout: 'form'
            ,bodyStyle: 'padding: 15px'
            ,autoHeight: true
            ,defaults: { border: false }
            ,items: [{
                html: '<p>'+_('settings_desc')+'</p>'
            },{
                xtype: 'modx-grid-system-settings'
                ,preventSaveRefresh: true
            },{
                html: MODx.onSiteSettingsRender
            }]
        }]
    });
    MODx.panel.SystemSettings.superclass.constructor.call(this,config);
};
Ext.extend(MODx.panel.SystemSettings,MODx.FormPanel);
Ext.reg('modx-panel-system-settings',MODx.panel.SystemSettings);

/**
 * Loads a grid of System Settings
 * 
 * @class MODx.grid.SystemSettings
 * @extends MODx.grid.Grid
 * @param {Object} config An object of options.
 * @xtype modx-grid-system-settings
 */
MODx.grid.SystemSettings = function(config) {
    config = config || {};
    Ext.applyIf(config,{
        url: MODx.config.connectors_url+'system/settings.php'
    });
    MODx.grid.SystemSettings.superclass.constructor.call(this,config);
};
Ext.extend(MODx.grid.SystemSettings,MODx.grid.SettingsGrid);
Ext.reg('modx-grid-system-settings',MODx.grid.SystemSettings);
</pre>

No need to remove to remove the original MODx.load() function.

**Comment by splittingred** [comment]
splittingred submitted:

Done, although I changed the add: method a bit to include sanity checks, and not use the sometimes-reserved word 'center'.
