### ISSUE TITLE
TV access permissions broken

### ISSUE THREAD

**Issue by krisj** [modxbot/migrate#4658]
krisj created Redmine issue ID 4658

have not tried this on a frech install. upgraded from rc-3 to rc-4. rc-3 is affected too..

I am trying to limit user group's access to a TV using categories.
here's what going on:
- create a new category
- create TV (textarea in my case)
- assign TV to this category
- assign that category to usergroup1 in Element Category Access
- refresh Tree
- category and TV disappears for a SuperUser until I remove that category from the other usergroup.

Same if I add that category to Super User group - I loose access as well as the category stops showing up in the dialog when I try to add it to other user groups too.

Also the "resource group" permissions for TVs dont seem to work - I can not limit access using resource groups.

**Comment by krisj** [comment]
krisj submitted:

In fact if I just assign any category to any user group and refresh the tree - category is gone. It is also not showing up in dialogs by its name anymore, only by ID. (I am logged in mgr context as a SuperUser)

And just tested on a fresh 2.1.0-rc-4 install and it does the same thing.

**Comment by opengeek** [comment]
opengeek submitted:

This was caused by the changes related to #4602 and fixed shortly after RC4 release. See https://github.com/modxcms/revolution/commit/46dcec6fb85f993b378c9a5e159f896b1c19f53d for details (and note the commit message incorrectly indicates context access instead of category access).

**Comment by onepack** [comment]
onepack submitted:

Same here. Also the templates assigned to that category dissapeared. Seems related to http://bugs.modx.com/issues/4600

**Comment by opengeek** [comment]
opengeek submitted:

As indicated, this is already fixed.

**Comment by onepack** [comment]
onepack submitted:

Thank you Jason!
