### ISSUE TITLE
"modx-resource-content"-field can't be modified with FC

### ISSUE THREAD

**Issue by Martijn1981** [modxbot/migrate#4687]
Martijn1981 created Redmine issue ID 4687

I'm using more than 10 sets in a FC-profile I made for a lower usergroup. I've now deselected the "visible" checkbox of the "modx-resource-content"-field in both "resource/create" and "resource/update" actions. Yet the content field, complete with TinyMCE, still appears when I'm logged in as user who's part of that lower usergroup!

**Comment by splittingred** [comment]
splittingred submitted:

I cannot reproduce this; secondly, why are you using more than one set per action?

**Comment by Martijn1981** [comment]
Martijn1981 submitted:

No, I'm using 2 sets per template: 1 for resource/update and 1 for resource/create. But you're right. I was looking at the wrong template all the time. It works fine. Sorry!
