### ISSUE TITLE
Make Template changeable with empty title field

### ISSUE THREAD

**Issue by gerritvanaaken** [modxbot/migrate#4694]
gerritvanaaken created Redmine issue ID 4694

If you create a new resource, you usually fill out the fields from top to bottom. The first field is "template", which makes sense.

However, in many cases the first thing an editor wants to do is: changing the template to the right "content type". But she has to fill in a title first, which is a bit confusing.

Please make it possible to change the template of a completely empty resource!

**Comment by splittingred** [comment]
splittingred submitted:

This is already fixed in Git.
