### ISSUE TITLE
Firefox's right-click content menu hover the Ressources Tree

### ISSUE THREAD

**Issue by Spheerys** [modxbot/migrate#4699]
spheerys created Redmine issue ID 4699

With Firefox 4.0.1, when I do a right click on the Ressources Tree in the manager of MODx Revolution 2.1.0RC4 (but also with 2.0.8), the MODx's right-click menu (Create Ressource, Delete, Duplicate...) is hidden by the Firefox's right-click content menu.
One way to access to the MOD'x right-click menu is to click elsewhere to make the Firefox'x menu disappear.

It's a little bit boring for me, but very annoying when I have to do a presentation of Revolution to a customer :o/

**Comment by splittingred** [comment]
splittingred submitted:

Not an issue with MODX - an issue with Firefox deciding to go against Javascript standards. 

You need to go to Firefox Preferences -> Content -> Enable Javascript (check it) -> "Advanced" button -> Check "Disable or replace context menus"
