### ISSUE TITLE
User's settings are not wiped from session on logout

### ISSUE THREAD

**Issue by splittingred** [modxbot/migrate#4703]
splittingred created Redmine issue ID 4703

Only happens if user's session is completely cleared via mgr menu option Flush Sessions.

This causes issues when trying to refresh the user's settings (such as when a user setting is set, or a context setting is changed) after they logout and log back into that context.

My guess is that this occurs when the user is still logged into another context. Solution: store user's settings in a context-specific array in the session to prevent overlap/conflicts. This array is cleared upon the user logging out of that context. Settings should never be shared (in reading) cross-contexts.

**Comment by opengeek** [comment]
opengeek submitted:

This and ACL data should be easily refreshed within existing user sessions without having to wipe the session. Am considering using the modRegistry to send notices to refresh this data on demand without destroying any user sessions.
