### ISSUE TITLE
Resourse List results inconsistent

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#4738]
onepack created Redmine issue ID 4738

I have two resourselist tvs setup and assigned to one template. 
They have the exact same settings.

The first shows the list of child elements including the parents.
The second only shows the parents.

Resourcelist Settings:
Allow Blank: No
Allow Empty Choice: No
Parents: 5,8,22
Depth: 10
Include Parents: Yes

Changing parents to "No" in the first TV doesn't change a thing, the parents will still be shown even after a cache refresh.

The second TV shows a "dash -" as the first choice even though the setting for "allow blank" end "empty choice" is both set to "No".
The second tv doesn't show any children resources only the parents with "Show parents" set to "No"

**Comment by onepack** [comment]
onepack submitted:

Hmm...I cannot edit my initial case message: wanted to correct a typo: resourse -> resource

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/ca1e7c0a2834a30e628ba7ecdf1d464b1f0faa4a
