### ISSUE TITLE
Timestamps in the Actions log are incorrect

### ISSUE THREAD

**Issue by larscwallin** [modxbot/migrate#4764]
larscwallin created Redmine issue ID 4764

Hey, just saw that the Actions log does not register correct time stamps. Its like it uses some cached stamp as it never changes. The dates update ok though.

Tried to track the bug myself and ended up in the XPDO class. Did not have time to persue it further.

Checked it on two different servers and versions 2.0.7 -> 2.1 RC4

It makes auto publishing bug out to by the way.

Ciao

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/2e4ce0d2595035a31f17d894973f1b196baa07f3

**Comment by splittingred** [comment]
splittingred submitted:

P.S. The dates were registering correctly in the DB - the display was using wrong formatting for the strftime function.
