### ISSUE TITLE
User override of System Settings not working 

### ISSUE THREAD

**Issue by larscwallin** [modxbot/migrate#4765]
larscwallin created Redmine issue ID 4765

Applying a User Setting to overriding the filemanager_path setting does not work. I have tried this in versions 2.0.7 -> 2.1 RC4 and it does not give any result in either of them. This used to work fine in previous versions.

Ciao

**Comment by larscwallin** [comment]
larscwallin submitted:

This is not a trivial issue. Forgot to change this to critical before submiting.

**Comment by splittingred** [comment]
splittingred submitted:

I can't replicate this:

!https://img.skitch.com/20110518-e395knha468m5f7is45eyuaeeb.jpg!

Works fine for me; make sure you always either Flush Sessions or logout/login after changing User Settings.

**Comment by splittingred** [comment]
splittingred submitted:

Cannot reproduce this in multiple tests. Again, ensure that you relogin the user after setting the settings.
