### ISSUE TITLE
MODX Installer & manager raise errors with APC

### ISSUE THREAD

**Issue by Phize** [modxbot/migrate#4774]
phize created Redmine issue ID 4774

MODX Revolution with APC raises some errors.
1. MODX Installer doesn't work.
2. MODX manager often raises errors.
   And the pages the error occurred are cached by APC, so the pages cannot correctly be shown again.
## Warning and Error message is following.

Warning: require_once(smarty_internal_parsetree.php) [function.require-once]: failed to open stream: No such file or directory in ?29   /www/vhosts/modx-revo/httpdocs/core/model/smarty/sysplugins/smarty_internal_smartytemplatecompiler.php on line 13
## Fatal error: require_once() [function.require]: Failed opening required 'smarty_internal_parsetree.php' (include_path='.:/usr/share/pear:/usr/share/php') in ?29    /www/vhosts/modx-revo/httpdocs/core/model/smarty/sysplugins/smarty_internal_smartytemplatecompiler.php on line 13

After excluding smarty_internal_smartytemplatecompiler.php from APC, both work correctly.
##

**Comment by opengeek** [comment]
opengeek submitted:

I'm using APC opcode caching with PHP 5.3.3 and not having any problems with v2.0.8-pl or the latest release-2.1.0 branch. Is it possible this is a bug in your version of APC (or the combination of APC version and PHP version)?

**Comment by Phize** [comment]
phize submitted:

I have had some feedback about it and I have knew there are some people who meet with the same issue with APC.

Today, I updated APC to 3.1.9 from 3.1.8.
There are no problem like this issue and MODX Revo seems to work correctly. 

Actually, It is possible this is a bug in the version of APC...
