### ISSUE TITLE
some buttons in FFx4 are not sizing to fit text

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#4783]
netprophet created Redmine issue ID 4783

Example: clear cache
http://easycaptures.com/fs/uploaded/438/6660667495.png

**Comment by mkschell** [comment]
netprophet submitted:

Caused by fix for #4669

**Comment by leoandrews** [comment]
leoandrews submitted:

I'm seconding this - there are actually quite a lot of buttons whose text is too big. Console > Download Output, Template > Quick Update > Save and Close. Someone needs to go through the whole thing identifying them and sorting them out.

**Comment by mkschell** [comment]
netprophet submitted:

Resolved in commit "00e14597":https://github.com/modxcms/revolution/commit/00e14597e3b79f7e3d04d0d24dda47adddf49000 by reverting change made for #4669
