### ISSUE TITLE
MODx comment tags

### ISSUE THREAD

**Issue by hwmaier** [modxbot/migrate#4790]
hwmaier created Redmine issue ID 4790

As discussed on http://modxcms.com/forums/index.php?topic=49368
it would be nice to have a dedicated comment tag available to comment templates and chunks without generating any mark-up.

It was suggested to use the following tag format:

[[# This is a comment ]]

Reasoning and explanation see above forum thread.

**Comment by hwmaier** [comment]
hwmaier submitted:

Sorry the [ and ] where eaten away by the editor. The tag fomat should read as

<pre>
[[# This is a comment ]]
</pre>

**Comment by hwmaier** [comment]
hwmaier submitted:

As additional informaton: It was suggested in the forums that the
<pre>[[# comment]]</pre> notation already works as MODx discards silently unknown tags.

To rely on this side-effect would have the disadvantage that those unknown tags are not removed in the chached page output and hence parsed on every page request (I check the content of the .cache.php file and it is visisble in the '_content' element). 

So an official support would still be great and beneficial.

**Comment by wshawn** [comment]
wshawn submitted:

This is somewhat doable now.

[[:then=`Comment Text Here`]]

It would be very simple to add a :comment filter to simply return nothing to the outputfilters.

**Comment by MarkH** [comment]
markh submitted:

Jason reminded that  # is actually reserved for editable content (from Evo).

@curiositymind suggested [[- comment -]](similar to the  in HTML) and Jason seeemd positive about that: http://twitter.com/#!/drumshaman/statuses/106148018234998784

This has been updated on the RTFM: http://rtfm.modx.com/display/revolution20/Tag+Syntax

**Comment by opengeek** [comment]
opengeek submitted:

Now implemented in develop for 2.2.0-rc1 release. This implementation makes sure no nested tags are processed when the comment token is encountered; an empty string is immediately returned to replace the comment with no further processing or evaluation necessary.

See commit details at https://github.com/modxcms/revolution/commit/d820f05af39dfc52ec5dc5faf8bf58e6ba157d88
