### ISSUE TITLE
getService() and 'hooks' name

### ISSUE THREAD

**Issue by bertoost** [modxbot/migrate#4792]
bertoost created Redmine issue ID 4792

I have found an issue with the getService() method and the 'hooks' name. This name is used a lot (like in Discuss, Gallery (Quip?) and others). But when there are two components called on a single page, the $modx->hooks name is taken by the first loaded component.

I have found this issue while I developped my own component (with hooks) and uses Discuss on the same page. I don't know how to fix it, but for me worked choosing an other name (like: mycmphooks) in the getService() method call.

**Comment by splittingred** [comment]
splittingred submitted:

Not so much a bug with MODX, but a bug with those components. Would be best to file it in those components bugtrackers.
