### ISSUE TITLE
Gaining access to TVs of a denied template

### ISSUE THREAD

**Issue by Martijn1981** [modxbot/migrate#4793]
Martijn1981 created Redmine issue ID 4793

Here's the user-case.
- As Admin 1, I've denied access to template A to client 1.
- Admin has already created and published a resource that uses template A.
- Client 1 logs in and finds out he can edit the resource, but not the TVs that belong to it.

So what I want to do is give the client permission to update a resource that uses this template and its TVs, but _not_ create a new resource with that denied template.

**Comment by splittingred** [comment]
splittingred submitted:

This has already been fixed for 2.1-pl.
