### ISSUE TITLE
Restrict creation of derivative Resource types

### ISSUE THREAD

**Issue by Martijn1981** [modxbot/migrate#4794]
Martijn1981 created Redmine issue ID 4794

I want to restrict access to Resource types like Symlink, Weblink and Static Resource. Simply put: I don't want the client to be able to use them.

Those types can currently be accessed using the icons just above the Resources-tree. I'd love to see Access Policy rules to get disable these types.

**Comment by MarkH** [comment]
markh submitted:

create_symlink, update_symlink et al?

**Comment by MarkH** [comment]
markh submitted:

I stand corrected, there's no such thing.

I thought they existed, but it's only for the complete class. 

In that case, I agree with this feature request. :D

**Comment by splittingred** [comment]
splittingred submitted:

Done for 2.2. You'll need to rebuild/upgrade if running from Git. https://github.com/modxcms/revolution/commit/38e686d9072d3ba0b2cc63fb466ad00067458ec6
