### ISSUE TITLE
template switching without saving

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#4798]
netprophet created Redmine issue ID 4798

This ticket has been split off [#4642] where discussion began about the way Template switching is done in Revo 2.1 rc.
It has been proposed to handle template switching and page reloading without actually saving the resource.

**Comment by MarkH** [comment]
markh submitted:

Did you have any luck with your preliminary test as discussed in #4642?

**Comment by mkschell** [comment]
netprophet submitted:

Yes, but it is not complete.
https://github.com/netProphET/revolution/tree/tpl_switch_no_save
- it's only the New Resource screen so far
- I haven't verified the proper reloading of different TV types
- Resource Group assignments are not reloading properly
- the use of $_SESSION to store the data will likely be replaced with the cache or some other mechanism

Would welcome feedback if you have any ideas or questions.

**Comment by gadamiak** [comment]
gadamiak submitted:

Another thing has come to my mind regarding this: if switching template for a new resource and saving it what FC sets will apply -- resource/create or resource/update? From my testing resource/create doesn't, while I expect it to.

**Comment by gadamiak** [comment]
gadamiak submitted:

I reported a separate issue for resource/create sets not working due to saving a new resource on template change. See #5142.

**Comment by Martijn1981** [comment]
Martijn1981 submitted:

Any updates on this refactor? I can imagine it's very tricky, with the TVs having to be reloaded and all, but I think it's worth it.

**Comment by mkschell** [comment]
netprophet submitted:

Solved in commit:
https://github.com/modxcms/revolution/commit/1b14af7fe7bebc19d34e4960f450fbd6a26c66e6

**Comment by mkschell** [comment]
netprophet submitted:

Template switching does not work after a validation error has been encountered trying to save from the Create Resource page.
cache_db setting may be involved.
Errors seen:
- error duplicating resource
- resource not found

**Comment by splittingred** [comment]
splittingred submitted:

Fixed here: https://github.com/modxcms/revolution/commit/3d7ae560d9f56ce5ee966ca9dd5ffda5d39dfb58
And here: https://github.com/modxcms/revolution/commit/8186b8fa5fa802a7ecf0099f300eaacc4917a1a4
