### ISSUE TITLE
[sqlsrv] TV cannot be edited

### ISSUE THREAD

**Issue by traveler** [modxbot/migrate#4818]
traveler created Redmine issue ID 4818

After creating TVs (which contain @SELECT) and adding them to documents I make sure they are working. After clicking property set on any one of them and closing the window with Cancel TVs become uneditable. It looks like this: after editing saving is successful, but the web page looks like the TV never got saved in the database. I got error.log full of these:
(ERROR @ /Revo/manager/index.php) Error 42000 executing statement: 
Array
(
[0] => 42000
[1] => 156
[2] =>[Microsoft][SQL Server Native Client 10.0][SQL Server]Incorrect syntax near the keyword 'constraint'.
)

Also by trying to add property like [[*TVname?property=`value`]] it happened.
Here is error.log from that time (I'm not really sure if this is 100% connected to this problem):

(ERROR @ /Revo/connectors/element/tv.php) modTemplateVarTemplate: Attempt to set NOT NULL field rank to NULL

After some lines like above, I got more lines like in the first error. Apparently, once it gets broken, I get these errors.

**Comment by traveler** [comment]
traveler submitted:

Update: I narrowed it down. It happens when editing TVs with multiple tabs. Also note that all TVs become unusable this way. I tried clearing cache, releasing locks etc...

**Comment by mkschell** [comment]
netprophet submitted:

I was able to reproduce both of the above query errors.
The following commit solves them
https://github.com/modxcms/revolution/commit/620b024828cd42e24019ea8dddf17808ccae332d
