### ISSUE TITLE
Cannot install galery

### ISSUE THREAD

**Issue by traveler** [modxbot/migrate#4822]
traveler created Redmine issue ID 4822

After trying to install gallery I gat the following error:

Console running...
Attempting to install package with signature: gallery-1.2.0-rc1
Package found...now preparing to install.
Grabbing package workspace...
Workspace environment initiated, now installing package...
Skipping vehicle object of class modSystemSetting (data object exists and cannot be upgraded); criteria: Array ( [key] => xhtml_urls )
Could not load class: galItem from sqlsrv.galitem.
Could not load class: galAlbum from sqlsrv.galalbum.
Could not load class: galAlbumItem from sqlsrv.galalbumitem.
Could not load class: galAlbumContext from sqlsrv.galalbumcontext.
Could not load class: galTag from sqlsrv.galtag.
Could not load class: galAlbum from sqlsrv.galalbum.
Could not get table name for class:
Could not load class: galAlbum from sqlsrv.galalbum.
Could not get table name for class:
Could not load class: galItem from sqlsrv.galitem.
Could not get table name for class:
Could not load class: galItem from sqlsrv.galitem.
galItem::loadCollection() is not a valid static method.
PHP warning: Invalid argument supplied for foreach()
Could not load class: galItem from sqlsrv.galitem.
Could not load class: galAlbumItem from sqlsrv.galalbumitem.
Could not load class: galItem from sqlsrv.galitem.
galItem::loadCollection() is not a valid static method.
PHP warning: Invalid argument supplied for foreach()
Successfully installed package gallery-1.2.0-rc1

**Comment by splittingred** [comment]
splittingred submitted:

Gallery does not support sqlsrv at this time.

Please file issues for Gallery at:

http://github.com/splittingred/Gallery/issues/
