### ISSUE TITLE
Missing a way to comment wich not is in the source-view

### ISSUE THREAD

**Issue by bertoost** [modxbot/migrate#4824]
bertoost created Redmine issue ID 4824

Simple; I'm missing a way to place a comment in templates or chunks, for example above a snippet call of some logical expressions. The way Smarty does, I like;

{\* My comment here *}

For example in MODx could be;

[[*\* My comment here]] or [[*\* My comment here **]]

Of course this must be multiple line like the PHP block comment /\* ... */

**Comment by bertoost** [comment]
bertoost submitted:

Never mind; I had to take a better look at the docs

http://rtfm.modx.com/display/revolution20/Tag+Syntax#TagSyntax-Commenttags

**Comment by MarkH** [comment]
markh submitted:

Duplicate of #4790
