### ISSUE TITLE
Buttons in package manager not accessible on small screens

### ISSUE THREAD

**Issue by Gallenkamp** [modxbot/migrate#4826]
gallenkamp created Redmine issue ID 4826

When installing i.e. Wayfinder in 2.1.0-rc4 on a 1024 x768 screen, at some point the "changelog" appears. As this is a layer and higher as the size of the browser window, buttons ("next" / "continue" or whatever the label in english is) are not clickable because they appear below the visible bottom line. Scrolling is not possible. Due to that behavior, some packages can not be installed (ant the layer not be closed).

Only chance: ctrl + "-"

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in the Package Management changes in 2.2.
