### ISSUE TITLE
codemirror does not work

### ISSUE THREAD

**Issue by ivankravchenko** [modxbot/migrate#4848]
krava created Redmine issue ID 4848

I updated modx up to  2.1 pl and also updated codemirror up to 2.0.0 rc1. After that, codemirror does not work.
I do not see any error in log except this one:
(ERROR @ .............. /core/xpdo/xpdo.class.php : 1967) PHP warning: json_encode() [<a href='function.json-encode'>function.json-encode</a>]: recursion detected

**Comment by ivankravchenko** [comment]
krava submitted:

It happpens only in google chrome.

**Comment by ivankravchenko** [comment]
krava submitted:

This error I receive when opening new chunk, snippet etc.
"Uncaught TypeError: Cannot set property 'display' of undefined" 

file: codemirror-compressed.js

**Comment by splittingred** [comment]
splittingred submitted:

Please file issues with codemirror here: https://github.com/splittingred/CodeMirror/issues/
This tracker is for MODX core issues only.
