### ISSUE TITLE
Cannot change "context access" of a certain user group

### ISSUE THREAD

**Issue by gerritvanaaken** [modxbot/migrate#4850]
gerritvanaaken created Redmine issue ID 4850

When I’m trying to change access policy from "Content Editor" to "GISCAD Redakteur" (which is a duplicate of "content editor"), the ExtJS window stucks, and the change does not perform.

(see Screenshot)

**Comment by opengeek** [comment]
opengeek submitted:

Uncaught TypeError: Cannot call method 'isXType' of undefined occurring in modx.window.js:93 when selecting Update User Group from right click action on the ACL grid.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/62540218aee068b57857cb480e63e54e4e4144f4
