### ISSUE TITLE
safe_mode check for non-boolean safe_mode-result

### ISSUE THREAD

**Issue by warenhaus** [modxbot/migrate#4851]
warenhaus created Redmine issue ID 4851

bug #2789 implemented a check during modx revo setup if php safe mode is on or off. however, setup (incl. upgrade) does not work for me, something with the check seems to be wrong:

my host changed safe mode from on to off for me to use modx, and phpinfo also states safe mode is now OFF. however, the setup-check still fails for safe mode.

I had a look at the code https://github.com/modxcms/revolution/commit/7c2af15ef24c985fa68f728aae714fda07476e86  and changed
"setup/includes/modinstalltest.class.php" to echo the values for $safeMode and for ini_get('safe_mode') between lines 46 & 47. "$safeMode" gives me "1", while "ini_get('safe_mode')" gives me "Off". Is it possible that "Off" is treated as "true" and therefore the check fails?
I understand safe_mode can be set to 0 or 1 as well, in my config it seems to be set to 'Off' (without the '').
Also, "is_bool(ini_get('safe_mode'))" tells me in my environment the result of ini_get('safe_mode') is NOT a boolean, so if I am not mistaken the check during setup must be amended.

(I'm actually not a php programmer, all I do is google and trial&error, so I might be completely mislead by my semi-knowledge).

after commenting out the check, setup & modx work fine.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/74d1fb0a71ddafbefec0a33f0b8be014a1d80e0e
