### ISSUE TITLE
Default value checkbox fully rendered in frontend

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#4852]
onepack created Redmine issue ID 4852

I have a TV with input option checkbox with the default value set to: 1. so by default the checkbox is checked in the templates now.

However this value 1 is now also being rendered in the frontend with the underneath output filter when the checkbox is checked.

[[*showside:empty=`
<div id="maintxtwide">
`]]

**Comment by splittingred** [comment]
splittingred submitted:

Erm, you should be using:

<pre>
[[*showside:is=`1`:then=``:else=`
<div id="maintxtwide">
`]]</pre>

empty is behaving just as it should; you're just using it incorrectly. :)

**Comment by onepack** [comment]
onepack submitted:

Hi Shaun,

I remember trying that one but I now discovered by testing that I didn't see the change because of ... caching. ;-)

Thanks so much for your great work and support!
