### ISSUE TITLE
"Rename file" menu command missing

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#4854]
gadamiak created Redmine issue ID 4854

After upgrade from 2.0.8-pl to 2.1-pl I noticed files tree menu command "Rename file" is missing. I checked with administrator user to be sure, but it's not there in Opera 11 and FF 4.0.1

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/b3449e0f3265e5ec09fb20e2da078143684fb8ab

**Comment by gadamiak** [comment]
gadamiak submitted:

I confirm. Thanks.
