### ISSUE TITLE
System info page (CMS > Reports > System info) doesn't have any scrollbars!

### ISSUE THREAD

**Issue by Martijn1981** [modxbot/migrate#4856]
Martijn1981 created Redmine issue ID 4856

At least in FireFox 4. The tabs itself work fine, but I can't scroll any further! This can be very hard when trying to read out system info or checking on database tables.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/b70fea9d672e861e794ec7fb08b375a1fa00c5dc
