### ISSUE TITLE
Nothing happens after selecting an image in Resources Browser

### ISSUE THREAD

**Issue by Martijn1981** [modxbot/migrate#4860]
Martijn1981 created Redmine issue ID 4860

See it for yourself. 
- Go to a published resource and enter the Resource Content TinyMCE field.
- Click on the insert/edit image icon and click on Browse
- Now, select an image and click on OK at the bottom.

Nothing happens! You have to click on Cancel :S in order to see that the image _has_ been selected. Please make it so that you can actually click on OK in order to go to the previous screen.

**Comment by splittingred** [comment]
splittingred submitted:

Ensure you have the latest TinyMCE. I cannot replicate this issue at all.

**Comment by Martijn1981** [comment]
Martijn1981 submitted:

Just to be sure we're talking about the same steps being taken: I mean the OK button as seen in the screenshot attached to this post. I've put images in several directories (and used filemanager_path properly so that the client can only access a certain main directory) and when I select an image and try to press OK: nothing happens. I can click all I want. 

Strange thing is: when I have clicked OK, the image _is_ inserted in the original TinyMCE Image popup (located underneath the Resource Browser visually), but the Resource Browser itself doesn't close. So it seems stuck, yet it isn't.

Hope I make any sense! I have 4.2.4 running, by the way. But it seems the error lies with the Resource Browser?

**Comment by Martijn1981** [comment]
Martijn1981 submitted:

This is completely my own fault, LOL. I've made a habit of removing the "advimage" plugin of TinyMCE quite some time ago. I used to do that with Evolution as well. I put the "advimage" back in and voila, it works.

My apologies. Please close this issue.
