### ISSUE TITLE
PHP 5.3.6 needs a valid dsn charset on installation

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#4865]
shamblett created Redmine issue ID 4865

From this forum thread :- http://modxcms.com/forums/index.php/topic,64171.0.html

The charset parameter in the dsn cannot be empty for this version of PHP when the PDO object is initallly created, it must be set to something, on connection the actual charset of the database in question is reflected back into the dsn.

**Comment by opengeek** [comment]
opengeek submitted:

I believe this is fixed by https://github.com/modxcms/revolution/commit/4b92e0fd9a18c44124f6885518164d3dbe0f60cf
