### ISSUE TITLE
User Group Browser issue

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#4868]
wshawn created Redmine issue ID 4868

Go to almost any tab in the user group

Update a Role in the Context Tab for example.

Hit Cancel or Save.

Box remains on screen keeping users from performing other "updates" in a user group.

Requires a page refresh to remove box.

**Comment by wshawn** [comment]
wshawn submitted:

also Affects Chrome 11.0.696.71

**Comment by splittingred** [comment]
splittingred submitted:

Already fixed: https://github.com/modxcms/revolution/commit/62540218aee068b57857cb480e63e54e4e4144f4
