### ISSUE TITLE
Access Control Grid Settings not copied when Duplicating a Context

### ISSUE THREAD

**Issue by bmilton** [modxbot/migrate#4871]
bmilton created Redmine issue ID 4871

To replicate, define any Access Control settings for a context via "context settings".
Duplicate Context.
Check access control settings for new context - they are blank.

For a site to work properly, I've had to add these basic access settings each time after duplicating a context:
Admin, 0, Admin
Anonymous, 9999, Load Only.

**Comment by garryn** [comment]
garryn submitted:

Fixed.

https://github.com/modxcms/revolution/commit/4d67e38df332f9910e0710b0c9e4fefad229aa77
