### ISSUE TITLE
Add download right click command in files tree

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#4875]
gadamiak created Redmine issue ID 4875

There's no way to download files uploaded to server from withing manager other than creating a static resource for them first. Correct me if I'm missing it.

This should definitely be possible and often required in collaboration workflow.

File tree should provide a download command for files, at least. It would be also nice to be able to download a folder with its contents or a few selected files (only in MODX Browser I guess) in zip/gzip/tar.

**Comment by splittingred** [comment]
splittingred submitted:

Done for 2.2: https://github.com/modxcms/revolution/commit/822c4a3505342f8cc9d9fb236ddbe4ea093b928d

**Comment by pixelchutes** [comment]
pixelchutes submitted:

Shaun,

Thank you for this download option. This is actually a very cool feature!

I've been wondering, how easy would it be to CREATE A FILE in the File tree? For example, if you wanted to create a new static .CSS or .JS file (via MODx), it would be great if you could simply create an empty file, providing only the file name, then edit it directly like you would any existing file.

Today you can create a directory (mkdir), and I believe you can also rename (I'll have to double-check). It would be awesome if you could create static files, too. It would almost remove the need for a separate (S)FTP/SCP program for working on MODx Revo sites.

**Comment by splittingred** [comment]
splittingred submitted:

Sure, we can look into it. Can you file that as a new ticket Mike?

**Comment by pixelchutes** [comment]
pixelchutes submitted:

Welcome #5998 to the scene ;)
