### ISSUE TITLE
System Settings buttons

### ISSUE THREAD

**Issue by goldsky** [modxbot/migrate#4901]
goldsky created Redmine issue ID 4901

I see bugs on UI for the small screen size (1024 x 746).
The upper buttons of the System Settings don't fit the browser width, so the "Clear Filter" button is hidden off the screen.
Please see the attachments.

**Comment by mindeffects** [comment]
mindeffects submitted:

It's the CSS!

<pre>
.x-btn-noicon .x-btn-small .x-btn-text { *width: 100%;* }
</pre>

This "damages" the button.

!modx_packmang2bad.png!

When "width" is deleted, evething's fine again:

<pre>
.x-btn-noicon .x-btn-small .x-btn-text { }
</pre>

!modx_packmang2good.png!
