### ISSUE TITLE
Popup dialog in user group editing not cleared properly

### ISSUE THREAD

**Issue by juro** [modxbot/migrate#4914]
juro created Redmine issue ID 4914

Opening popup dialog "Add user to group", "Add Context", "Add Resource Group", "Add Category" in user group editing tabs and then closing the dialog by clicking Save or Cancel, leaves gray semi-transparent backgroud displayed in the front. Subsequent clicks on the buttons mentioned above not working. Must reload the page to continue editing, which is annoying when doing a lot of changes.
This was working fine in 2.1rc4

**Comment by splittingred** [comment]
splittingred submitted:

Already fixed: [#4915]

**Comment by juro** [comment]
juro submitted:

Please reopen this issue. It is different from #4915 and its fix _does not_ apply to this one.

**Comment by splittingred** [comment]
splittingred submitted:

Then it was fixed here: https://github.com/modxcms/revolution/commit/62540218aee068b57857cb480e63e54e4e4144f4

It however, is fixed, and is not needed to be reopened.
