### ISSUE TITLE
Broken popup dialogs in Access Controls

### ISSUE THREAD

**Issue by juro** [modxbot/migrate#4915]
juro created Redmine issue ID 4915

Opening dialog "Create access policy" in Access Controls->Access Policies, then pressing cancel, switching to Policy Templates tab, clicking "Create Policy Template" opens corrupted dialog. The same when switching between tabs the other way round.
Although not sure, seems to affect all 2.0.5+ versions including 2.1

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/be168cc963de0ba19be71491548f8a39e4fbef56
