### ISSUE TITLE
Resource Properties list breaks on Save 

### ISSUE THREAD

**Issue by larscwallin** [modxbot/migrate#4919]
larscwallin created Redmine issue ID 4919

When i save a Resource the Property Set list breaks. Sometimes. 
This is what happens:

For Resources where the Property Set list have not been unlocked, the unlocking feature is missing.

For Resources where the Property Set list _have_ been unlocked the "VALUE" column is missing as well as the options to "Update"/"Edit".

Cause:
It seems that this is a problem to post-save UI sync process. Sometimes the list control seems to break, but snaps out of the stall after a second or two. And sometimes it just stays non-func. Timeout issue?

**Comment by larscwallin** [comment]
larscwallin submitted:

Screenshot :)

**Comment by splittingred** [comment]
splittingred submitted:

Uhm, there is no Properties list for Resources.

Can you be more specific as to what screen this happens on? And if you mean Elements (which I am assuming), can you be specific as to which ones, how, and what properties?
