### ISSUE TITLE
Dim Disabled Plugins in Elements Pane

### ISSUE THREAD

**Issue by neilness** [modxbot/migrate#4927]
neilness created Redmine issue ID 4927

I think it would be useful if the elements list indicated which plugins are disabled or locked -- indicated  the same way that unpublished or hidden resources are shown in italics or light gray.

**Comment by splittingred** [comment]
splittingred submitted:

Great suggestion!

Done: https://github.com/modxcms/revolution/commit/b947e17d0c87c474080538e5b46c4451d822fce4
