### ISSUE TITLE
Caching issue with package manager

### ISSUE THREAD

**Issue by antonyf** [modxbot/migrate#4937]
AntonyF created Redmine issue ID 4937

Scenario: I download a new package. Click download, and after a short while the button changes to downloaded. I close the window, but the package list hasn't updated. I click refresh in the browser - but it's still not listed. I have to go to Site > Clear Cache, and only then can I see my newly downloaded package for me to install.

**Comment by opengeek** [comment]
opengeek submitted:

Fixed via #4955
