### ISSUE TITLE
Navigation on smaller browser resolution wrong

### ISSUE THREAD

**Issue by fourroses666** [modxbot/migrate#4941]
fourroses666 created Redmine issue ID 4941

I notice when i smallen my browser, the top main navigation is too wide and some buttons goes underneath each other. This will make the main tab buttons of the tree not work.

A simple solution will be to smallen the font size, it's 13px and could easely go 12 or even 11, maybe capitalise 'em and the subnav can be smaller too.

I think this way its more compact and gives a nicer overview and it also won't give the 'bug' on smaller screens.

**Comment by MarkH** [comment]
markh submitted:

This is something that only seems to happen on other languages, simply cause the text strings are too wide. I've seen it on the dutch mgr pages aswell.

I just launched a simple plugin yesterday "TopMenuFix" that decreases the padding of the menu to make it fit on smaller screens. It does look crammed together on bigger ones, but does the job.

**Comment by fourroses666** [comment]
fourroses666 submitted:

! 2 years later I see this lol, thx for the fix!

**Comment by opengeek** [comment]
opengeek submitted:

Not sure this is resolved if the solution is outside the core.

**Comment by cicero** [comment]
cicero submitted:

This could be fixed for small-screen desktop and/or tablets via css by css-media-queries or by narrowing the menu all together like suggested by fourroses666. But still there is not much wiggle-room. Should I look into it?
