### ISSUE TITLE
Setting specific access permissions for a context causes an infinite loop / won't save

### ISSUE THREAD

**Issue by bmilton** [modxbot/migrate#4947]
bmilton created Redmine issue ID 4947

Duplicate an existing context (May also occur if creating a new context but not certain).
After duplication, there will be no access permissions set for the context (Separate Bug entered).  Now if you attempt to set new access permissions on the new context, it will fail if done in this order:

Add Anonymous, 9999, Load Only
Add Administrator, 0, Administrator

Attempt to save the context - Status update says it is saving but it loops endlessly.  If you give up and refresh the page bad stuff happens.  The context will not show up in the Manager list, but there are some database entries created for it.  This prevents you from trying to add a context of that name again, unless the db is manually cleaned up.

I did this several times in different browsers (Firefox 4, Firefox 3, Chrome) before I realized it was the order of permissions that mattered.  If you instead apply the administrator permission first, the new context will save just fine.

I have not tried this since 2.1 was released, and I don't intend to as I don't have a throwaway Modx install at the moment.

**Comment by opengeek** [comment]
opengeek submitted:

If you add a first ACL for a group other than who you are working as currently, you will not have permission to load that Context any longer. Always add your permissions first. The first ACL added blocks access from any other user groups other than the one you added.

We're looking for ways to prevent this from being done incorrectly.

**Comment by opengeek** [comment]
opengeek submitted:

Scheduling for 2.2.0 to address problem of being able to assign ACLs that block access by a super administrator.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/7cf4103f0cb6b7e3ca4931211752801586f7853a
