### ISSUE TITLE
Site Cache appears to no longer be cleared

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#4953]
wshawn created Redmine issue ID 4953

More often than not, I am getting an empty screen stating "Console is Running"

I subsequently manually deleted all the cache contents from the file system and found quite a bit of stuff there, which should have been as five minutes before I received a "successful" response from clear cache.

After bouncing through various pages on the site, I hit clear cache again and it just sits there, even after a minute on an 8 core xeon.

After verifying via sftp and ssh the files are still in the cache for the pages I just clicked through.

If I refresh the browser window and force a full screen refresh, I will get:

<pre>
Console running...
Clearing the lexicon topics cache: Refresh successful!
Clearing the Snippet/Plugin script cache: Refresh successful!
Clearing the Resource cache: Refresh successful!
Processing automatic publishing dates
-> 0 documents were unpublished.
-> 0 documents were published.
Regenerating system settings cache: Refresh successful!
Regenerating the context caches
-> mgr: Refresh successful!
-> web: Refresh successful!
</pre>

But the cache continues to contain the files for the resources I visited.

After switching to IE the first time I cleared the cache I got the same empty "Console is running..."

The second time I clicked it the report is duplicated and in a different order:

<pre>

Console running...

-> 0 documents were unpublished.
 Clearing the Resource cache: Refresh successful!
 -> web: Refresh successful!
 -> mgr: Refresh successful!
 Regenerating system settings cache: Refresh successful!
 Processing automatic publishing dates
 -> 0 documents were published.
 Clearing the lexicon topics cache: Refresh successful!
 Clearing the Snippet/Plugin script cache: Refresh successful!
 Regenerating the context caches
 Processing automatic publishing dates
 Regenerating system settings cache: Refresh successful!
 Regenerating the context caches
 -> web: Refresh successful!
 -> 0 documents were published.
 -> 0 documents were unpublished.
 Clearing the Snippet/Plugin script cache: Refresh successful!
 Clearing the lexicon topics cache: Refresh successful!
 Clearing the Resource cache: Refresh successful!
 -> mgr: Refresh successful!

</pre>

**Comment by opengeek** [comment]
opengeek submitted:

Not everything is deleted from the cache in 2.1.1 — this is expected behavior. I cannot reproduce the problems with the console.

**Comment by opengeek** [comment]
opengeek submitted:

This was an issue with the console throwing away messages when the COMPLETED message was either received out of order from the registry (see #4836) or not received at all (the clearcache processor was not sending a COMPLETED message).
