### ISSUE TITLE
Package download cannot connect to provider (server-specific)

### ISSUE THREAD

**Issue by shevelev** [modxbot/migrate#4956]
shevelev created Redmine issue ID 4956

While trying to downlod addon or install new package I get the error about supplier connection error at the Package management page. It reports about the empty answer from supplier and says to make shure the supplier is correct.

**Comment by splittingred** [comment]
splittingred submitted:

Ensure cURL is installed and that you're not behind a proxy.

**Comment by shevelev** [comment]
shevelev submitted:

Thank You. The cURL really was not installed. It would be better to check this while installation. The issue may be closed.
