### ISSUE TITLE
add resource numbers to resource groups tree view

### ISSUE THREAD

**Issue by jrotering** [modxbot/migrate#4958]
jrotering created Redmine issue ID 4958

Managing resource groups is currently rather difficult because only the title of each resource is displayed under the resource group. When lots of resources have similar or identical titles, it is hard to know what's what.  If the resource ID was displayed next to each resource, it would make things much clearer.

**Comment by splittingred** [comment]
splittingred submitted:

Done for 2.2: https://github.com/modxcms/revolution/commit/3109025ec071d4149ce975cfab7fd8f6bb854cb5
