### ISSUE TITLE
modPHPMailer::reset() not compatible with modMail::reset() nagging error message

### ISSUE THREAD

**Issue by cyclissmo** [modxbot/migrate#4960]
cyclissmo created Redmine issue ID 4960

To suppress this error message:

<pre>
Declaration of modPHPMailer::reset() should be compatible with that of modMail::reset()
</pre>

Add the following _array_ type hint to reset() in modphpmailer.class.php as follows:

<pre>
public function reset(array $attributes= array()) {
</pre>

**Comment by garryn** [comment]
garryn submitted:

Fixed.

https://github.com/modxcms/revolution/commit/142903d86a8c93d3d19415190dc8b2b77746e052
