### ISSUE TITLE
Flush Permissions - not flushing all

### ISSUE THREAD

**Issue by jgulledge19** [modxbot/migrate#4963]
jgulledge19 created Redmine issue ID 4963

I have been setting permissions for Resource groups and changing settings and hitting the "Flush Permissions" button and then not seeing any difference in what was done for a different browser and (anonymous) user.  This has been really frustrating and then I realized that the Flush Permissions only does the user that is currently logged in, not all users.

Can this button flush all user permissions and all (anonymous) permissions and sessions if needed?  I think this would make Revo permissions easier to work with and understand.

Thanks

**Comment by wshawn** [comment]
wshawn submitted:

Check your issue against this:

[[http://bugs.modx.com/issues/4603#change-10838]]

Apparently, you are correct.  After pressing Flush All, one is left in the table as shown in the picture.

**Comment by opengeek** [comment]
opengeek submitted:

Flush Permissions only reloads the permissions for the current user you are logged in as. You have to Flush All Sessions to get other users permissions to reload after you make changes.
