### ISSUE TITLE
API call from Snippet 

### ISSUE THREAD

**Issue by jgulledge19** [modxbot/migrate#4972]
jgulledge19 created Redmine issue ID 4972

The API call for modResource->getContent() returns processed content, that is that snippets have already been ran/completed.  The docs say this should be raw: http://api.modxcms.com/modx/modResource.html#methodgetContent, I take that to mean snippets have not been ran/called.

In the mean time how can I get the raw content via a snippet?

**Comment by wshawn** [comment]
wshawn submitted:

This should have been posted in the forums as it deals more with implementation than a bug.

[[http://bobsguides.com/revolution-objects.html]]

To get a resource (formerly called a "document") that is published and has the name "Recipes," you'd do this:

$document = $modx->getObject('modResource',array(
    'published' => 1,
    'pagetitle' => 'Recipes'
));

Here's another way of doing the same thing:

$name = 'modResource';
$criteria = array(
    'published' => 1,
    'pagetitle' => 'Recipes'
)
$document = $modx->getObject($name,$criteria)

or

$resource = $modx->getObject('modResource',12);
$longTitle = $resource->get('longtitle');

$content =$resource->get('content');

**Comment by jgulledge19** [comment]
jgulledge19 submitted:

Thanks Shawn, but I think I was not clear in what I was stating.  I was not asking how to use xpdo to get the content or a resource back, but rather to get the raw unprocessed content back.  I want to get the content exactly as it appears in the Manager when you are updating the resource, not after the snippets have ran(processed).

Here is an example of what it should do after the $content = $resource->getContent(); (remember this is via a snippet call not a CMP that I am doing this if it makes a difference)

_If you where to output $content it should be like this:_
[ [!mySnippet? &didnotrun=`true`] ]

<p>My Content goes here</p>

_What is actually output is the processed version:_

<div>My Snippet ran and here is the HTML code for it</div>

<p>My Content goes here</p>

I have messed up about three hundred resources I need to remove a snippet from the content and resave the resource with the updated content.  But I can't do this if I can't get the raw content as it is stated in the API documentation.

**Comment by jgulledge19** [comment]
jgulledge19 submitted:

I stand corrected the $content = $resource->getContent(); does return the raw content, but the snippet output then appears to be processed which seems redundant and unnecessary to me.

_Example_
Create a simple snippet that only has this in it:
return '<p>Test snippet call: [ [someSnippet? ] ]</p>';

And it is processed.  Not sure if this is intended but it sure seems redundant to me.

**Comment by opengeek** [comment]
opengeek submitted:

This needs to be a forum thread...
