### ISSUE TITLE
Package management

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#4974]
onepack created Redmine issue ID 4974

I was wondering why my site had taken so much space on the server and starting searching trough the directories to find out that 70 MB was taken by older packages that were even not used anymore. TinyMCE had 5 versions and took most of the space.

Can this be changed? What is the underlying reason to keep all the transport zip and unzipped packages of all the versions available in the file system. If I have a 1 year old site and update on a regular basis how big would this become?

**Comment by wshawn** [comment]
wshawn submitted:

Thank you.  I was about to start looking into this myself.  i found a bunch of related stuff in the cache folder yesterday.

I have sites of over two years....  

One of them is a test site, with 168 megs on a site with only 200 pages.

**Comment by gadamiak** [comment]
gadamiak submitted:

Previous versions are saved to allow rolling back. They can be found and deleted from manager -- use right click > View Package + Uploaded Versions, then right click on version > Remove Package Version.

**Comment by wshawn** [comment]
wshawn submitted:

There are also files in the cache folder which are not removed when the site cache is cleared.

Here is a list from a site less than three months old.

**Comment by opengeek** [comment]
opengeek submitted:

Shawn, that last issue belongs in a different ticket please.

**Comment by onepack** [comment]
onepack submitted:

Hi gadamiak, Thanks for sharing this knowledge. I never even saw that one even though I always try to click around on as many links and buttons to find out what they do.
My suggestion is to improve the UI so you can see how much MB a plugin uses and/ or how many versions are present in the grid with a link to the package management. People new to modx or the modx-right-click menu won't miss this then.
Perhaps make the Package name Linkable to the same package management page as "view package" does.

**Comment by gadamiak** [comment]
gadamiak submitted:

onepack onepack wrote:

> Thanks for sharing this knowledge.

You're welcome :)

> Perhaps make the Package name Linkable to the same package management page as "view package" does.

Good idea IMO.

**Comment by onepack** [comment]
onepack submitted:

First of all, congratulations! The package management is already a lot better in the new 2.2 environment.

Regarding this case. It might be an idea to add a button "version management" or likewise to the list of options: 
uninstall | reinstall | check for updates | remove | version management

This way it's more intuitive and clear to (new) users that the old packages are still present and can be managed.

**Comment by onepack** [comment]
4 Years later. Closed!
Please create a new case if someone still thinks this is valid.
