### ISSUE TITLE
User 1 left with hashing.modMD5

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#4981]
wshawn created Redmine issue ID 4981

Expected action: to be updated to hashing.modPBKDF2 with the rest of the users.

**Comment by opengeek** [comment]
opengeek submitted:

This is not automatically done by the core. See pbkdf2Convert Extra to have user passwords auto-converted on next login — http://modx.com/extras/package/pbkdf2convert

**Comment by wshawn** [comment]
wshawn submitted:

I thought it had changed user 2 automatically during an upgrade.

I know the rest of the users were added afterwards and reflected the new password system.

I will look into the extra, but would have like to see it as part of the "update."
