### ISSUE TITLE
resource tree bolds resource with same ID as element being edited

### ISSUE THREAD

**Issue by lukemcd** [modxbot/migrate#4984]
lukemcd created Redmine issue ID 4984

In Manager click to edit an element, such as a template or chunk with an ID of 3. Then click the Resources tab, if there is a resource with with the same ID it will appear bold as if it is currently being edited.

**Comment by garryn** [comment]
garryn submitted:

Fixed.

https://github.com/modxcms/revolution/commit/1289287b7350881b4806347b01ebd99ad12bf2fb
