### ISSUE TITLE
Different document variable summary / introtext depending on resource Class Key

### ISSUE THREAD

**Issue by scottborys** [modxbot/migrate#5005]
scottborys created Redmine issue ID 5005

Depending on whether a resource is a modDocument or a modWebLink, a different document variable call is required to access the "Summary (introtext)" field.  If a resource is a Document, then one must use [[_introtext]].  If a resource is a WebLink, then one must use [[_summary]].

**Comment by wshawn** [comment]
wshawn submitted:

That is strange....  Maybe they should be made aliases of each other.

**Comment by opengeek** [comment]
opengeek submitted:

Do you mean when accessing the data via a Plugin in the manager? Because [[*introtext]] should work in both instances...not that you would ever use that tag on a WebLink since all it does is a redirect anyway.

**Comment by scottborys** [comment]
scottborys submitted:

Please take a look at the attached image.  You can see when my mouse is hovering over each of the fields that in each case the document variable call is different [[ *summary]] vs. [[ *introtext]].  The different in accessing the variables is apparent in templates, chunks, and as a getResources placeholder.

I do have a case where I'm using a WebLink with [[ *introtext]] and have for a few versions - this is the first one to break it.  It just seems like a confusing user experience to me - the same field is labeled the same but has two different calls depending on the type of the document.

**Comment by opengeek** [comment]
opengeek submitted:

Though the panel is labeled incorrectly as summary in the weblink panel, there does not appear to be any difference in parsing or behavior. [[_summary]] should never work in any case; the actual field in the object is always called introtext and would be parsed as [[_introtext]] in a Resource.

**Comment by splittingred** [comment]
splittingred submitted:

Whatever the case, I cannot replicate this in 2.2. Closing, as is fixed.
