### ISSUE TITLE
New Policy Template can't be edited

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#5006]
bobray created Redmine issue ID 5006

If you create a new policy template from scratch (without duplicating an existing template), when you "update" it, there are no buttons to save it or cancel so there's no way to add any permissions to it (tested in 2.1.1-pl).

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/42bf83cebad9a7193167c4f5689ac4142e32c3ea
