### ISSUE TITLE
Context Setting v.s. System Setting (and lexicon_entries table)

### ISSUE THREAD

**Issue by lokamaya** [modxbot/migrate#5007]
lokamaya created Redmine issue ID 5007

Adding a new context setting (for example site_start) also change table lexicon_entries for that existing value. 

For example, if I add "site_start" for specific context, the value of "setting_site_start" and "setting_site_start_desc" in lexicon_entries table also changed.

However there is no way back to restore the default value of that lexicon entries, both from System Setting page and Context Setting page. The only way to edit that lexicon entries by deleting that setting and creating the same one.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed mostly through this: https://github.com/modxcms/revolution/commit/a2063c1575f7a687052b788c4c873c8101545d7e

Now will not create Lexicon entries if no name/description is specified.

**Comment by lokamaya** [comment]
lokamaya submitted:

Hi Shaun, thank you for quick fix.
