### ISSUE TITLE
IE 6-7-8-9, Opera 11.11 manager not work correct

### ISSUE THREAD

**Issue by tonatos** [modxbot/migrate#5011]
tonatos created Redmine issue ID 5011

IE 6-7-8 - manager very slowly

IE 6-7-8-9  - Javascript Error

IE 6-7-8, Opera - The saving process is sometimes just hangs.

Does anyone in the team modx generally tested cross-browser admin panel?

**Comment by splittingred** [comment]
splittingred submitted:

Yes, we do. Opera does not support full ECMA standards. MODX does not officially support IE6 or IE7 in its default manager interface. IE8/9 work fine on our end.

If you have specific issues, please open them in a ticket with full details of the problem.

**Comment by tonatos** [comment]
tonatos submitted:

http://bugs.modx.com/issues/5012

http://bugs.modx.com/issues/5013

http://bugs.modx.com/issues/5014

ie9 fine?? ))
