### ISSUE TITLE
modUser::joinGroup should check if user is already a member

### ISSUE THREAD

**Issue by neilness** [modxbot/migrate#5021]
neilness created Redmine issue ID 5021

Trying to change the user's role like so:

$modx->user->joinGroup('Staff', 'Editor');
$modx->user->joinGroup('Staff', 'Admin');

will create multiple group entries in the database, instead of simply updating the role.

It probably shouldn't be required to leave the group first, or it could throw an error instead.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/8cf7166e01da84c5f04bd30dde35100135da27f2
