### ISSUE TITLE
Strange output on missing System Variable close bracket

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#5024]
wshawn created Redmine issue ID 5024

Sitemap: [[++site_url]sitemap.xml
returns: 

<pre>
Sitemap: " title="Site design and development by Sanity">Sanity
</pre>

Sitemap: [[++site_url]]sitemap.xml
returns the correct domain and path.

**Comment by splittingred** [comment]
splittingred submitted:

Dont put incorrect tags?

**Comment by wshawn** [comment]
wshawn submitted:

I would thought it would have not matched to anything if incorrect.  That is why I reported it.
