### ISSUE TITLE
Files in folder tree inside file browser are displayed inconsistently

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#5026]
gadamiak created Redmine issue ID 5026

File browser shows files in folder tree (left pane) when launched from file tree button. However, when launched from static resource content field or from inside TinyMCE only folders are shown.

Left pane should show only folders as files are displayed inside the main pane.

**Comment by garryn** [comment]
garryn submitted:

Fixed.

https://github.com/modxcms/revolution/commit/e230278835b5c08ee6e7886321ecf5d1663dc40e
