### ISSUE TITLE
Connectors Access by $site_id (used as $_REQUEST['HTTP_MODAUTH']) and fake context ($_REQUEST['ctx'])

### ISSUE THREAD

**Issue by Fi1osof** [modxbot/migrate#5044]
fi1osof created Redmine issue ID 5044

Non-authorized user can do any Ajax-requests if can get $site_id;

GET  connectors/resource/index.php?&HTTP_MODAUTH={$site_id}&ctx={fake ctx e.g. sfdfsdfsdfsdfsdfsd}&action=getToolbar

$ctx = isset($_REQUEST['ctx']) && !empty($_REQUEST['ctx']) ? $_REQUEST['ctx'] : 'mgr';
$modx->initialize($ctx);

$modx->initialize('sfdfsdfsdfsdfsdfsd');  Have not that context. Not policy, you can do anything

**Comment by MarkH** [comment]
markh submitted:

1) In 2.1.1 the HTTP_MODAUTH var has been changed to include a (from the top of my mind) user and session specific hash as well, stored in a session var. How are you going to get a hold of that?

2) When I try to replicate this using the actual HTTP_MODAUTH for my site while being logged in, I am getting this in my error log and an access denied on screen?
[2011-06-14 08:48:12](ERROR @ /connectors/resource/index.php) Could not prepare context: sad

**Comment by Fi1osof** [comment]
fi1osof submitted:

1) Yes, in 2.1.1 it`s fixed, as i see;
2) In versions 2.1.0 and  lower : /connectors/resource/index.php?action=(required e.g. getToolbar)&HTTP_MODAUTH=($site_id   required )&ctx=dgsfgfsgsdfsdfs(fake, for init wrong context and empty policy)
