### ISSUE TITLE
Setting 'parent-cmb' in FC doesn't work

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#5046]
gadamiak created Redmine issue ID 5046

Setting @parent-cmb@ from FC set doesn't work in both resource/create and resource/update sets. Other fields get filled properly (although I haven't checked all) but parent.

This should work as other fields and get filled with value specified inside FC set to allow forcing specific parent for new/updated resource. This is essential to ensure proper hierarchy of resources.

**Comment by gadamiak** [comment]
gadamiak submitted:

This one is indispensable to ensure a proper use of templates in resources hierarchy. It's a blocker for sites of mine.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/4b272de60ebf4baf16fda99e6b298d4cd258019b

**Comment by gadamiak** [comment]
gadamiak submitted:

It's working correctly for resource/create set as long as the template, which triggers the set, is the default one. Changing template on resource creation doesn't apply resource/create sets, which is a bug on its own.

Setting parent for a resource with the resource/update set should work exactly the same way as resource/create. This doesn't work and additionally it produces a fatal error (in a9fda58).

With such a set active any attempt to edit _any_ resource returns server error 500. The server log reports @PHP Fatal error:  Call to a member function get() on a non-object in /.../core/model/modx/modmanagercontroller.class.php on line 576@.

Please, reopen this issue.

**Comment by gadamiak** [comment]
gadamiak submitted:

Thanks Shaun for fixing this issue (in c7a30c8). One minor thing remains, resource/update changes parent ID but the title displayed in @[[*parent]]@ field doesn't update and shows the title of the previous resource's parent unless the editing page is reloaded. This is confusing.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/98f3c90c7bdc645a8611e670578c4aadba2470c1
