### ISSUE TITLE
Code executes when opening a chunk in manager

### ISSUE THREAD

**Issue by vrdriver** [modxbot/migrate#5047]
vrdriver created Redmine issue ID 5047

I couldn't find this issue in the bug tracker, so I have created a new one. Please forgive me if it already exists and has been solved

When in the manager, I created a new chunk with the follow code in it, leaving in the extra <!- bit by accident... 

<!--[if IE]>

It saved ok, but when I went to reload that chunk after editing other pages, the page simply wouldn't load.
It seems the browser could be looking at the actual code, not the text.

The compiled page executes fine, as the closing tag was in the rest of a template... but not the actual editing of the chunk.

I was able to solve the problem by manually editing the data in the sql table, but otherwise, for others, this may become an impossibility.
Cheers,
Steve

**Comment by opengeek** [comment]
opengeek submitted:

Is this using CodeMirror or just the default textarea?

**Comment by vrdriver** [comment]
vrdriver submitted:

no, just the default textarea.

**Comment by opengeek** [comment]
opengeek submitted:

This cannot be reproduced
