### ISSUE TITLE
'manager_language' is reset on upgrade

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#5049]
gadamiak created Redmine issue ID 5049

On upgrade the @manager_language@ system setting gets reset to defautl @en@.

**Comment by splittingred** [comment]
splittingred submitted:

Actually, it gets set to whatever language you used setup/ in. This is to allow those installing MODX in a separate language the ability to see the manager in their language.

**Comment by gadamiak** [comment]
gadamiak submitted:

All right now, although I'm using manager in other language I always perform upgrade in English. That explains the issue :) Thanks.

**Comment by exside** [comment]
exside submitted:

I actually wanted to report this as a bug when I found this ticket (hope it will get attention, even if it's marked as resolved)...I am always setting the language on upgrading to de and after the installation completes my manager_language is set back to "en", so it doesn't seem that this get taken over somehow...
