### ISSUE TITLE
Manager pages don't display

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#5053]
gadamiak created Redmine issue ID 5053

Manager pages don't show at all in Firefox 5, in Opera 11 the missing pages are Package Management and Users, plus a bunch of JS errors on manager home page.

See details in "my comments":http://bugs.modx.com/issues/260#change-11158 for #260. I guess it's related to the new on-the-fly CSS/JS compression so I posted there at first. However, a separate report will make it easier to track.

**Comment by gadamiak** [comment]
gadamiak submitted:

I've just re-run upgrade to latest develop branch (a9fda58) and it looks to be fixed. I checked in:
- Opera/9.80 (X11; Linux x86_64; U; pl) Presto/2.9.168 Version/11.50
- Mozilla/5.0 (X11; Linux x86_64; rv:5.0) Gecko/20100101 Firefox/5.0
- Chromium/12.0.742.112

Thanks.

**Comment by garryn** [comment]
garryn submitted:

Closing as per OP comments.
