### ISSUE TITLE
MODX browser

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#5060]
onepack created Redmine issue ID 5060

I have had many questions from people that wanted  to insert an image from the modx browser. The case is that they don't see the images because they forget to click the images folder to show them. I think they have a good point! Why would you still need to open a folder in the MODX browser called images if you already clicked the "add Image" button. Make it default to open at least something instead of nothing in the modx browser or create system settings where you can link folder names with actions/ operations.

First of all, I know you guys are busy and work hard to make Modx better and I really appreciate this. That's the reason why I spend quite some time reporting bugs and Improvements.  At this moment I have a lot of cases that I failed to report since I noticed that I still have 45 open cases with cases dating from 2010. I noticed that some of these issues have been reported by other users in new cases months later and sometimes even got resolved. This is off course a very good thing but it makes me wonder if reporting the Improvements and issues is still worth the effort.

Greetings

**Comment by gadamiak** [comment]
gadamiak submitted:

onepack onepack wrote:

> The case is that they don't see the images because they forget to click the images folder to show them. I think they have a good point! Why would you still need to open a folder in the MODX browser called images if you already clicked the "add Image" button.

Doesn't setting the base path for a image TV do that?

> ...create system settings where you can link folder names with actions/ operations.

Base path for TV handles this IMO.

> First of all, I know you guys are busy and work hard to make Modx better and I really appreciate this. ... This is off course a very good thing but it makes me wonder if reporting the Improvements and issues is still worth the effort.

I just saw my issue #260 (sic!) being handled lately :) So it definitely is worth effort. Do we have other option, anyway ;-) Thank you, modxers!

**Comment by splittingred** [comment]
splittingred submitted:

No longer applicable due to Media Sources; however, the issue with the Browser not opening the thumbs has been fixed here: https://github.com/modxcms/revolution/commit/06d58dd7c0a726f6435d9b9cf16bd812f5e1c301
