### ISSUE TITLE
Improve MODX Browser options and system settings

### ISSUE THREAD

**Issue by jgulledge19** [modxbot/migrate#5061]
jgulledge19 created Redmine issue ID 5061

I currently have a broken MODX Browser but before I report that bug I want to offer some ideas to improve customization and code maintainability.

_Suggestions to making the filemanager easier to use and customize:_

_Revise system setting:_
filemanager_path I would be great if it accepted a comma separated list of relative file paths (relative from filemanager_base)
    so I could do this:
    assets/images/,assets/pdfs/,assets/flvs/
    The MODX Browser would always returns the correct(complete) filemanager_path and the folder(s) and file name like so: assets/images/folder/my-image.jpg to tinyMce, TVs or however it is used.

```
Now to call on the returned value the user now has the choice to make the absolute call like this:  
[ [++filemanager_base_url] ]assets/images/folder/my-image.jpg 
or via PHP
$modx->getOption('filemanager_base').'assets/images/folders/my-image.jpg';

filemanager_path can overridden by user settings but it would be great if it could also be assigned to groups.
maybe a better name would be filemanager_relative_paths 
```

_Replace settings:_
filemanager_path_relative 
    - this is confusing, I would recommend to replace it with filemanager_base and the default should be {webroot}.  So instead of using base_path/url via phpthumb it would use the filemanager_base
        This could not be overwritten with a user/group setting only by context setting
filemanager_url_relative 
    -  again this is confusing, I would recommend to replace it with filemanager_base_url and the default is the {base_url}.
        This could not be overwritten with  a user/group setting only by context setting

_Remove setting:_
filemanager_url - don't need this anymore as it is confusing and seems redundant 

_Rename setting:_
strip_image_paths to filemanager_return_relative_url

This seems to get a lot of bug reports at least similarly reported. In my opinion it is because the current method is to complicated. 

Somewhat Related bugs: 
http://bugs.modx.com/issues/4804
http://bugs.modx.com/issues/5043
http://bugs.modx.com/issues/5023
http://bugs.modx.com/issues/4785

Thanks for reviewing and hopefully this is helpful.

**Comment by splittingred** [comment]
splittingred submitted:

All this is irrelevant in 2.2, due to the changes with Media Sources, which offer that level of flexibility.
