### ISSUE TITLE
MODX Browser does not render images

### ISSUE THREAD

**Issue by jgulledge19** [modxbot/migrate#5062]
jgulledge19 created Redmine issue ID 5062

I am running on IIS 7.5, windows 2008 and I followed the steps here:
http://modxcms.com/forums/index.php/topic,63523.msg369379.html#msg369379 but the images do not appear for me.  

_Here is the hack I did to make it work(not desirable):_

File: connectors/system/phpthumb.php insert the following code on line 2
Code:
@
if( isset($_REQUEST['HTTP_MODAUTH'])) {
    unset($_REQUEST['HTTP_MODAUTH']);
}
@

For some reason it is not sending the correct value, but if you unset the value it works fine.

When I looked at the path the image is calling on this was it:
http://my-server/connectors/system/phpthumb.php?HTTP_MODAUTH=modxXXX.XXX&wctx=web&basePath=assets%2Fcontent%2F&basePathRelative=1&baseUrl=assets%2Fcontent%2F&baseUrlRelative=1

Similar issue:
http://bugs.modx.com/issues/5008

**Comment by jgulledge19** [comment]
jgulledge19 submitted:

Note I removed the actual value for MODAUTH and replaced with X.

**Comment by splittingred** [comment]
splittingred submitted:

The fix mentioned in ticket #5008 fixes this; you need to make sure to set compress_js to 0.

The fix in this ticket causes a security vulnerability, as then anyone can use phpthumb remotely on your server.
