### ISSUE TITLE
package management issues on fresh MODX 2.1.1 install

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#5086]
onepack created Redmine issue ID 5086

Wamp modx 2.1.1 installation gives the following message when I try to install a package:

An error occurred while connecting to the Provider: MODX received a blank response from the provider. Please double check your service URL and make sure the provider is a valid provider.

**Comment by opengeek** [comment]
opengeek submitted:

See http://ttyl.modx.com/thread/28806/package-management-download-error#dis-post-392465 for a detailed report of the problems.

There has been some discussion of a resolution involving the final URL of the download being provided back to the client to avoid server-side redirection.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/d22b2dd2bfea89be477043a7b38aee4190da7b6c
