### ISSUE TITLE
Removing package versions in manager doesn't remove them in core/packages

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#5102]
onepack created Redmine issue ID 5102

I had a lot of space being taken by old package versions on the web-server so I decided to remove them like instructed via Package management -> View Package -> tab Uploaded Versions and removing the old versions.

The lists for the packages are now completely empty but when I checked the files under core/packages I could still see all the former "formit" and other packages sitting there taking space.
When a developer would never check this it could lead to a serious increase of the space used on the website that's why I assume it is a Major bug.

**Comment by wshawn** [comment]
wshawn submitted:

This is very similar to [[http://bugs.modx.com/issues/4974]]

**Comment by Martijn1981** [comment]
Martijn1981 submitted:

I've seen the same thing happen. Packages aren't really removed. This occupies a lot of space in the end.
