### ISSUE TITLE
Working with output filters

### ISSUE THREAD

**Issue by bertoost** [modxbot/migrate#5103]
bertoost created Redmine issue ID 5103

I was thinking about working with output filters. In the case I want to check if a TV or placeholder not is empty I do

<pre>
[[*tvName:notempty=`<div class="item">[[*tvName]]</div>`]]
</pre>

But is this not calling a TV twice? Maybe this is a better way?

<pre>
[[*tvName:notempty=`<div class="item">[[+contents]]</div>`]]
</pre>

The original TV content is set as placeholder in the output... I don't know for sure, but maybe it's a faster way for this...

**Comment by splittingred** [comment]
splittingred submitted:

The speed difference is negligible, since it has to be parsed anyway, and the TV value is cached.

You could always make your own filter, "wrapIfNotEmpty".

**Comment by bertoost** [comment]
bertoost submitted:

Just thought about this;

You said that the performance would be negligible and I understand it when you parse the [[+contents]] tag again. But what if you just do a str_replace() ? That wouldn't be that hard I think? In that case you have to parse the output once and just replace the [[+contents]] tag inside the output

Maybe it's worth to reconsider this?
