### ISSUE TITLE
Please sort Contexts in Resource Tree by name

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#5112]
wshawn created Redmine issue ID 5112

Currently, mine are "sorted" in reverse order, but that is probably how I created them.  

Could we have them in alphabetical order?

Drag and drop into position only appears to work in current Session.

**Comment by wshawn** [comment]
wshawn submitted:

Got to thinking it may even be cool to order them via a setting similar to menu_index provided in Resources.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/4cc7a9e5bbe0306e52bdc36ede5cbde2c9fe0aa4

**Comment by splittingred** [comment]
splittingred submitted:

Another commit, adds Settings for configurable options: https://github.com/modxcms/revolution/commit/2349f252d100b9774579c6fc9d693fa8e6f7e70c
