### ISSUE TITLE
TVs with filebrowser in other contexts

### ISSUE THREAD

**Issue by mschlegel** [modxbot/migrate#5139]
mschlegel created Redmine issue ID 5139

My problem was already described here [[http://bugs.modx.com/issues/4785#note-4]]. But since the bug was already closed when I commented I'm afraid that this last comment got lost. I'm still have some problems with the newest git version (except for the TinyMCE problem, which seems gone). 

In short, there are two problems:
1. While the location of the image TV filebrowser is correct, the file TV filebrowser ignores the filemanager_path/url settings (as described in the previous bug report). For me, applying the same modifications done in core/model/modx/processors/element/tv/renders/mgr/input/image.php also to (...)/file.php (commit: https://github.com/modxcms/revolution/commit/339e48924940de516a5a624983c134eb02983c00) solves the problem.
1. The Base Path/URL settings at the image/file TV input options are really useful for me, however context specific assets_path/url or base_path/url settings seem to be ignored when setting these as placeholders within these paths. E.g.:

@Base Path: [[++assets_path]]images/
Base Path Relative: No
Base URL [[++assets_url]]images/
Base URL Relative: No@

The filebrowser does not care about assets_path and assets_url settings and displays folder standard for the web context.

**Comment by mschlegel** [comment]
mschlegel submitted:

I found a fix that works for me at a first glance. Edited these files: 

@core/model/modx/processors/element/tv/renders/mgr/input/image.php
core/model/modx/processors/element/tv/renders/mgr/input/file.php@

and replaced '@$modx->getOption@' by '@$workingContext->getOption@' at lines 27-33, resp. 28-34 of the two files. 

If any context specific setting is present, it seems to be respected.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed here: https://github.com/modxcms/revolution/commit/08c721c0b36cd2f69be6f10b9fedce0cb5fed246 for Revolution 2.2 only.
