### ISSUE TITLE
Manager templates more hierarchical

### ISSUE THREAD

**Issue by bertoost** [modxbot/migrate#5141]
bertoost created Redmine issue ID 5141

It would be great if you could use an other template for the manager interface, but then more hierarchical in the way Magento does.

This could be done to copy the manager/templates/default/ to your own and change the settings.. But maybe it could be made easy to let users overrule the templates they want. For example I only would change the login screen smarty file to show my company logo at login. For this there is no need to copy all the templates.

A simple check could fix this;
Check if the template exists in the directory I have configured in the settings and otherwise use default anyway.

**Comment by bertoost** [comment]
bertoost submitted:

Note: working like this would made updating much more easier!

**Comment by splittingred** [comment]
splittingred submitted:

Hm, it should already work that way. If it doesn't, that's a bug. Will look into it.

**Comment by splittingred** [comment]
splittingred submitted:

Done in develop (2.2). Now can override a single controller AND/OR template in your custom theme. Will make custom theming much easier. :)

**Comment by bertoost** [comment]
bertoost submitted:

Shaun,
I have test this and it works much better now.. the only thing is; when I want to overrule the header.tpl (to add my own logo for example) then I will get an error about a nav tpl. This is because there is an include inside the header which include relative to the current tpl. I know smarty works like this but maybe you can look at it? overrule the smarty function?

An other issue I found is with the dashboard widgets. I must copy the dashboard widgets templates to get it working. This while I dont make changes to that. Maybe a little fix is needed for this?

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/aa246e9016b18a31be80b8de8624dcd25f37bd68

If you are having issues with Dashboard widgets, please open a separate ticket. Thanks!
