### ISSUE TITLE
resource/create doesn't apply when switching template

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#5142]
gadamiak created Redmine issue ID 5142

Switching template on resource creation requires it to be saved (see #4798). This has a side effect of the current implementation, which renders FC resource/create sets ineffective for new resources with non-default template. Simply, once saved the resource is not new anymore.

This is a side effect issue, which will get resolved once the main problem gets its resolution. However, a separate issue for this will help to track it.

**Comment by gadamiak** [comment]
gadamiak submitted:

Ups, forgot to set the priority. It's definitely not trivial.

**Comment by mkschell** [comment]
netprophet submitted:

Solved as per #4798
