### ISSUE TITLE
Create Document Here creates weblink or static resource

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#5149]
gadamiak created Redmine issue ID 5149

Using "Create document here" command in resource tree on weblink or static resource creates a weblink or a static resource respectively instead of a document. I didn't test with symlink.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/0c3476f411143764c0367ae6c2da18e7926f7568
