### ISSUE TITLE
Fatal error when TV uses non-existent category ID

### ISSUE THREAD

**Issue by adamlundrigan** [modxbot/migrate#5164]
adamlundrigan created Redmine issue ID 5164

Not sure how I fell into that situation, but one of my TVs ended up attached to a category ID which no longer existed.  Whenever editing a page which used a template using this TV, a fatal error would appear:

<pre>
Fatal Error: call to undefined method stdClass::get() in cms/manager/controllers/default/resource/tvs.php on line 126
</pre>

No check is performed on the loaded category to ensure it is valid.  I have a fix for this issue in my revolution fork on github and will issue a pull request.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/03519e5b087a8f9f5b628bdbfe2a7895f3357ac5
