### ISSUE TITLE
Duplicate items not appearing in resource tree

### ISSUE THREAD

**Issue by antonyf** [modxbot/migrate#5175]
AntonyF created Redmine issue ID 5175

Behaviour: right click a resource and select Duplicate. A dialog appears asking for a name, which you give and confirm. However the new resource does not appear in the resource tree, even with refreshing the browser.

The site cache must be cleared for it to appear in the tree.

**Comment by splittingred** [comment]
splittingred submitted:

Already fixed in 2.1.2.
