### ISSUE TITLE
Advanced Upgrade should validate extracted core package

### ISSUE THREAD

**Issue by apcherry** [modxbot/migrate#5185]
apcherry created Redmine issue ID 5185

Running an advanced upgrade from 2.0.8 to 2.1.1(pl) the manager fails to display the resource tree.
This is discussed in http://modxcms.com/forums/index.php/topic,65649.0

With a clean install the file connectors/layout/mod.config.js.php is 

<pre>
<?php
define('MODX_REQP',false);
require_once dirname(dirname(__FILE__)).'/index.php';
$_SERVER['HTTP_MODAUTH'] = $_SESSION["modx.{$modx->context->get('key')}.user.token"];
$modx->request->handleRequest(array('location' => 'system','action' => 'config.js'));
</pre>

Whereas with the upgrade the same file is

<pre>
<?php
define('MODX_REQP',false);
require_once dirname(dirname(__FILE__)).'/index.php';
$_SERVER['HTTP_MODAUTH'] = $modx->site_id;
$modx->request->handleRequest(array('location' => 'system','action' => 'config.js'));
</pre>

When I change the $_SERVER line of code to the $_SESSION version of the full install the resource tree appears. The same difference is also seen in connectors/system/phpthump.php

Sorry I don't know how the upgrade scripts work so I'm not sure if this is a problem in the upgrade script or how to fix it.

**Comment by apcherry** [comment]
apcherry submitted:

Sorry I meant phpthumb.php not phpthump.php!

**Comment by apcherry** [comment]
apcherry submitted:

Just tried the 2.1.2 (advanced) upgrade. This overwrote the files modx.config.js.php and phpthumb.php with the code 

<pre>
$_SERVER['HTTP_MODAUTH'] = $modx->site_id;
</pre>

The manager resource tree list then failed to appear. Changing this line back to the 

<pre>
$_SERVER['HTTP_MODAUTH'] = $_SESSION["modx.{$modx->context->get('key')}.user.token"];
</pre>

version from the full install makes the manager resource tree appear again.

**Comment by opengeek** [comment]
opengeek submitted:

This is not a bug. Make sure you do not check the "Core Package has been manually unpacked" or "File already in place" checkboxes when running the advanced install. Also make sure your previous version's core/packages/core/ directory and all it's contents are either writable by PHP or completely removed, and that all files in your deployment are writable by PHP as well.

**Comment by opengeek** [comment]
opengeek submitted:

Actually, this is a bug, as reported in the forums at http://modxcms.com/forums/index.php/topic,65649.msg374393.html#msg374393

The check for the package already being extracted should verify something which validates the version of the extracted manifest file (or any resource that can better validate the version).

**Comment by opengeek** [comment]
opengeek submitted:

The checkbox indicating the core transport is already extracted will now remain unchecked if the manifest file's modified time is lower than the modified time of the core.transport.zip.

See commit details at https://github.com/modxcms/revolution/commit/8ad317177d6aadc23eb2188db22395ee42665f97
