### ISSUE TITLE
resource_err_duplicate while create new resource after empty alias error

### ISSUE THREAD

**Issue by Fi1osof** [modxbot/migrate#5220]
fi1osof created Redmine issue ID 5220

Error:  while friendlyURL is activate and try to save new document whithout alias, return error $modx->error->addField('alias', $modx->lexicon('field_required')); , but unset $_SESSION['newResourceTokens'] ,  and when trying save this document return error "resource_err_duplicate". 

file: core/model/modx/processors/resource/create.php
errorCode: 
if($search !== false) {
                unset($_SESSION['newResourceTokens'][$search]);
                $tokenFound = true;
 }

solution:
1)       if($search !== false) {
                //unset($_SESSION['newResourceTokens'][$search]);
                $tokenFound = true;
 }
2)    $resource->save();
    unset($_SESSION['newResourceTokens'][$search]);

**Comment by opengeek** [comment]
opengeek submitted:

I cannot reproduce this in release branch for 2.1.4
