### ISSUE TITLE
Add check for cURL in Package Management

### ISSUE THREAD

**Issue by splittingred** [modxbot/migrate#5250]
splittingred created Redmine issue ID 5250

Add a check for cURL in the Package Management interface so that it flags a warning if cURL is not installed/configured.

**Comment by wshawn** [comment]
wshawn submitted:

Wow, this is overdue.  Great catch.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/ea9567fc51688b467040dc139f5321ec0e4f0338

**Comment by opengeek** [comment]
opengeek submitted:

Unfortunately, the patch for this was broken when cherry-picked for 2.1.4-pl and it has been reverted. This will be available in 2.2.0-rc1 still though.
