### ISSUE TITLE
Can't save resources in low connection

### ISSUE THREAD

**Issue by adhiarta** [modxbot/migrate#5251]
adhiarta created Redmine issue ID 5251

In low connection can't save resources with error "En error occurred while duplicating this resources "

**Comment by opengeek** [comment]
opengeek submitted:

You need to provide much more detailed information when submitting a bug report, especially one you are giving a priority of Critical. Post in the forums to figure out what the issue might actually be, then submit bug reports once anyone can reproduce it using the information provided.
