### ISSUE TITLE
Missing code in /setup/assets/js/sections/database.js

### ISSUE THREAD

**Issue by animir** [modxbot/migrate#5266]
animir created Redmine issue ID 5266

For correct test collation or create database on server side, we must add to function 'testCollation' (database.js, line 101) next code:

<pre>
        var user = Ext.get('database-user');
            if (user) { p.database_user = user.getValue(); }
            
        var password = Ext.get('database-password');
            if (password) { p.database_password = password.getValue(); }
            
            var dbserver = Ext.get('database-server');
            if (dbserver) { p.database_server = dbserver.getValue(); }
</pre>

Because, this information need on server for correct connection to DB (/setup/processors/database/collation.php, line 37):

<pre>
        $dbExists = $xpdo->manager->createSourceContainer(
            array(
                'dbname' => $install->settings->get('dbase')
                ,'host' => $install->settings->get('database_server')
            )
            ,$install->settings->get('database_user')
            ,$install->settings->get('database_password') ...
</pre>

**Comment by splittingred** [comment]
splittingred submitted:

Actually, the settings are cached, so that AJAX transmission data is not needed at all.
