### ISSUE TITLE
Search box in resource tree

### ISSUE THREAD

**Issue by kenquad** [modxbot/migrate#5268]
kenquad created Redmine issue ID 5268

If your site has hundreds or thousands of pages (which isn't an uncommon scenario) it can be difficult to quickly find the resource you want to edit.  I would like to see a "search" or "filter" box at the top of the resource tree to make this easier.

**Comment by splittingred** [comment]
splittingred submitted:

How would it filter the tree, since the tree is nested?

**Comment by kenquad** [comment]
kenquad submitted:

How about a "virtual resource" that appears at the top of the tree when you initiate a search, and aggregates every matching resource as a child under it, leaving the main tree itself untouched?  Would that be outrageously difficult/impossible to implement?

**Comment by splittingred** [comment]
splittingred submitted:

Outrageously difficult? No. Maybe a 'pseudo-context', ie, Search Results, that would show at the top, with a one-level-deep list of resources below it. We'll think about it. Good suggestion, though. Thanks!

**Comment by splittingred** [comment]
splittingred submitted:

This was implemented in the develop branch of Git, and slated for 2.2.
