### ISSUE TITLE
Resource Groups

### ISSUE THREAD

**Issue by lhanson** [modxbot/migrate#5293]
lhanson created Redmine issue ID 5293

Bug caused through user error.

If you drag a resource from a resource group, and place it on or under the _same resource_ in the resource list, modx appears to update it to be a parent of itself and the resource disappears from everywhere, until you manually alter the parent column in the modx resource table.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/64572e2b21bbcbb9c0ca994dff0732feade67e31
