### ISSUE TITLE
Add inval to Anonymous ID

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#5300]
wshawn created Redmine issue ID 5300

Currently the field reurns:

<pre>
Array
(
    [id] => 
    [username] => (anonymous)
    [password] => 
    [cachepwd] => 
    [class_key] => modUser
    [active] => 1
    [remote_key] => 
    [remote_data] => 
    [hash_class] => hashing.modPBKDF2
    [salt] => 
)
</pre>

When setting it can we have it id => intval(0)

Some filter implementations would be cleaner if this was an actual 0

**Comment by opengeek** [comment]
opengeek submitted:

This was addressed by the resolution for #5973
