### ISSUE TITLE
Placeholder not working correctly for snippet call inside chunk

### ISSUE THREAD

**Issue by jgulledge19** [modxbot/migrate#5309]
jgulledge19 created Redmine issue ID 5309

The problem is a snippet runs through a loop and calls on a chunk and sends placeholders via the API method.  The chunk also has a snippet in it and that snippet uses params that are placeholders.  But the placeholders for that snippet call are empty.  This worked as expected until I upgraded to 2.1.2.  Filters seem to work as expected and that is how I was able to get my pages to work by using filters, but I think probably have more chunks that use snippets that have params biased on properties. 

This is the snippet call to the chunk, nothing special:
@
            $members_output .= '
            '.$modx->getChunk($group_tpl, $member_data);
@
I also tried setting the placeholders before the getChunk call:
@
            foreach($member_data as $n=>$v) {
                $modx->setPlaceholder($n,$v);
            }
@
But this set the very last call/row to the placeholder rather then have the proper data for each row.

_I think the getChunk() method is not setting properties correctly._

Here is part of my original chunk:
@
<span >[[+office]][[!If?
                   &subject=`[[+office_number]]`
                   &operator=`!empty` 
                   &then=`, Room [[+office_number]]`
                ]]</span>
@

And how I made it work by removing the snippet call and using a filter:
@
<span>[[+office]][[+office_number:notempty=`, Room [[+office_number]]`]]</span>
@

Thanks for look at this.

**Comment by opengeek** [comment]
opengeek submitted:

This was already fixed in 2.1.3-pl — see #5222
