### ISSUE TITLE
Site homepage required resource alias bug

### ISSUE THREAD

**Issue by leoandrews** [modxbot/migrate#5315]
leoandrews created Redmine issue ID 5315

When editing the homepage of a site, typically you would not want to set a resource alias as the page is load in the root of the domain.

However 2.1.1 insists on a resource alias for ALL pages when friendly URLs are switched on which means you cannot submit edits without a value for this field. You can get round this validation by simply inputting a slash in the resource alias field in the resource editor but once submitted, it strips it out anyway.

Two preferred behaviours could be:
1) If the page you're is editing is set as the homepage and friendly URLs are on, modx simply doesn't do the validation of the resource alias field when edits are submitted or;
2) Resource aliases aren't mandatory with friendly URLs switched on. In the event of omission, it fails over to being able to access the page by its id.

**Comment by opengeek** [comment]
opengeek submitted:

IMO, since the site_start is a page in the site, it should have an alias like the rest. This is necessary for a number of reasons. I might suggest we give it a default alias of index so that requests to /index.html might properly redirect to the site_url as 301's by default.

If automatic_alias is turned off (or doesn't calculate anything), another option would be to automatically assign the id as the alias. Just be aware that this would be the canonical URL of the site_start page (with the HTML content type extension appended, e.g. /1.html), which would 301 redirect to the site_url.

Thoughts?

**Comment by opengeek** [comment]
opengeek submitted:

I gave the default Resource 'index' as an alias by default on new installs and changed the behavior of any site_start page to use automatic_alias behavior regardless if automatic_alias is enabled.

**Comment by leoandrews** [comment]
leoandrews submitted:

Apologies for the tardy reply - i wanted to see whether there was an RFC out there which gave guidance.

As a option this solution may work but we need to put this out to the community for testing and validation.

Here's why:
Lots of people in the real world remove the .html extension from the content type so that they get friendly urls like /news not /news.html
We need to be sure that by setting a default to index we don't end up with the homepage being written as /home by the likes of Wayfinder...or worse, that top level news page being written as /index/news

**Comment by opengeek** [comment]
opengeek submitted:

You can enter new tickets for suggested improvements. This will not affect anything except with automatically assign the pagetitle or the string 'index' as the alias. This will make that alias available as /index if content type extension is changed to blank, but this will still 301 redirect to the site_url if the Resource is site_start regardless. The only affect of changing the default on new installs is that they can turn on friendly urls without having errors about duplicate URI's that have blank aliases.

**Comment by opengeek** [comment]
opengeek submitted:

Also fixed for 2.1.4 — https://github.com/modxcms/revolution/commit/b7ee8bb61a766744741fa2d5df1d90bf39aec1c6
