### ISSUE TITLE
HTTP 500 in manager after upgrade to bcfd160

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#5358]
gadamiak created Redmine issue ID 5358

I just upgraded to bcfd160. The upgrade went well, I run setup, went through login screen and got blank page. My server log reports:

> @PHP Fatal error:  Call to a member function render() on a non-object in .../manager/controllers/default/welcome.class.php on line 59@

**Comment by gadamiak** [comment]
gadamiak submitted:

I was upgrading from cfb11b0. I had to revert.

**Comment by wshawn** [comment]
wshawn submitted:

Did you validate that all of the files had indeed been placed?

Also make sure the /core/cache is empty. You might have picked up some old links or cached content.

**Comment by splittingred** [comment]
splittingred submitted:

This was a known issue. Please upgrade again. Also, make sure you're running the build and setup after upgrading to this revision.

**Comment by gadamiak** [comment]
gadamiak submitted:

I reverted almost immediately, but before that I removed all mgr cache manually, which didn't help. Anyway, I'm running from git, and always run build before upgrading.

I will be upgrading to latest develop in a week or so and will report then.

**Comment by xpix** [comment]
xpix submitted:

I get the same after running build and installing modx from git(1e84e39).

**Comment by splittingred** [comment]
splittingred submitted:

This has been fixed, and can be remedied by updating to latest Git in develop branch and re-running build and setup.

**Comment by gadamiak** [comment]
gadamiak submitted:

I confirm it's been fixed.
