### ISSUE TITLE
getResources odd behaviour

### ISSUE THREAD

**Issue by sean69** [modxbot/migrate#5362]
sean69 created Redmine issue ID 5362

I hope this is the right place to post a bug/oddity about the getResources extra - I couldn't find a specific URL to post this to: 

I was trying to create a snippet that would take the idx value of the getResources output & create some row based CSS rules from that. The odd thing that happened was that the idx did not get passed to the snippet if I called it like this:

@[[!nthItem? &index=`[[+idx]]` ]]@ 

however if I called it like this:

@[[!nthItem? &index=`[[+idx]]` ]] @

only then did the idx get  passed, the snippet was very simple, just for testing.

@<?php
return $index;@

I obviously have a workaround, but I thought the behavior was odd.

-thanks
-sean

**Comment by Martijn1981** [comment]
Martijn1981 submitted:

Try updating to 2.1.3 first. It fixes cachable tags issues according to https://raw.github.com/modxcms/revolution/v2.1.3-pl/core/docs/changelog.txt

**Comment by opengeek** [comment]
opengeek submitted:

This was fixed in 2.1.3-pl — please upgrade.

See #5222
