### ISSUE TITLE
Policy Template Permission Lexicon Not Showing

### ISSUE THREAD

**Issue by rossco** [modxbot/migrate#5392]
rossco created Redmine issue ID 5392

I seem to of found a bug with custom lexicons loading in to the drop down menu of a policy template permissions.  When creating a new permission for a template, I set the Lexicon field to casestudy:permissions as per my CMP and the details fail to load in to the drop down. The namespace is correct and pointing to the correct path.

My CMP works fine everywhere else, lexicon files are showing in the lexicon management area but not when included in the policy template.

After discussing with Splittingred on IRC, it appears to be a bug.

Thanks,
Ross

**Comment by splittingred** [comment]
splittingred submitted:

Fixed for 2.2: https://github.com/modxcms/revolution/commit/78c04f96c8f9dde1871a0ff4be2adeefbbf58bc8
