### ISSUE TITLE
Include SiteName in Manager Title

### ISSUE THREAD

**Issue by mindeffects** [modxbot/migrate#5434]
mindeffects created Redmine issue ID 5434

Hi,
when using Chrome's homepage feature – the 8 overview thumbs – I have a lot of e.g. "MODX :: Dashboard" labels (see screenshot), unable to know, which website's manager shortcut is lying behind the thumb. Would be great to have the name of the website included in the <title>-tag of the manager pages.

Thanks!
Oliver

**Comment by splittingred** [comment]
splittingred submitted:

Done for 2.2: https://github.com/modxcms/revolution/commit/a7a258bb9baae0fae01c26057c3db69583ce4c2f
