### ISSUE TITLE
Wayfinder crashes after Update from 2.0.8 to 2.1.3

### ISSUE THREAD

**Issue by Gallenkamp** [modxbot/migrate#5451]
gallenkamp created Redmine issue ID 5451

"Call to undefined method modX::getUserDocGroups() in /home/client/www/domain.com/core/components/wayfinder/wayfinder.class.php on line 461"

So the whole page is not accessible. Solution is:
- uninstall Wayfinder (2.1.3 at the time of revo 2.0.8)
- redownload it as "new package" as package manager does not(!) recognize the newer package (says "no updates for wayfinder")
- install Wayfinder 2.3.1

**Comment by splittingred** [comment]
splittingred submitted:

Update Wayfinder. That method is deprecated in 2.1.

**Comment by Gallenkamp** [comment]
gallenkamp submitted:

once you installed modx 2.1.3 you can't login to the manager to update wayfinder.
