### ISSUE TITLE
Parser not functioning as expected -- processing tags out of order based on cached status

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#5482]
wshawn created Redmine issue ID 5482

[[!initializeModel]]
[[importLists]]

None of the content is cached or preexists.
Calling a Snippet uncached to initialize a new model first, will be processed after the "cached" calls which do not have content in the cache - causing a nonObject error.

I understand the cache has been reworked, and gradually changed over the last few Revo updates. 

For quite a while, the parser processed tags in the order found. 

Has the sequence intentionally been adjusted to parse all cached and then all uncached items?

And even if the cached Snippets do not exist in the cache?

**Comment by opengeek** [comment]
opengeek submitted:

This has always been the case with Revo. Uncached tags are not processed until all cacheable outer tags (and cacheable nested tags) have been processed and prepared caching.
