### ISSUE TITLE
Form Customization fails when renaming TV-tab when there are no TV's

### ISSUE THREAD

**Issue by nomark** [modxbot/migrate#5501]
nomark created Redmine issue ID 5501

When changing the 'Tab title' of the tab 'modx-panel-resource-tv' using form customization, without there being any TV's attached to a page, form customization will crash due to a javascript error (see screenshot).

The fix would be to add a check-if-element-exists before changing tab titles.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/93dc6347244f2314af581cab2f5a7c5f9c40355a
