### ISSUE TITLE
Quick Create/Edit resource window is too high

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#5502]
gadamiak created Redmine issue ID 5502

The quick create/edit resource window has minimum height fixed at ~800px and can't be resized. It doesn't fit inside the browser window and its controls can't be reached by scrolling the browser window.

I'm running at 1280×800 widescreen and observe the same in:
- Opera/9.80 (X11; Linux x86_64; U; pl) Presto/2.9.168 Version/11.50
- Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/535.1 (KHTML, like Gecko) Ubuntu/11.04 Chromium/13.0.782.112 
- Mozilla/5.0 (X11; Linux x86_64; rv:5.0) Gecko/20100101 Firefox/5.0
- Ubuntu 11.04 x86_64

**Comment by splittingred** [comment]
splittingred submitted:

This was fixed in a prior commit.
