### ISSUE TITLE
(G)UI: ComboBox height (FireFox 5)

### ISSUE THREAD

**Issue by CyntaxDotDev** [modxbot/migrate#5505]
ReSpawN created Redmine issue ID 5505

The height of the combobox option/value field is 1 or 2 pixels less high than the foldout/dropdown icon. The following fixes it in Firefox 5 on Windows 7, 64bit.

<pre>
.x-form-text { 
    min-height: 20px; 
}
</pre>

(as mentioned in this tweet: https://twitter.com/#!/MarkGHErnst/status/101729935407853568)

**Comment by splittingred** [comment]
splittingred submitted:

https://github.com/modxcms/revolution/commit/ae1e4eea121af730234a0879731d812e9bbc97fb

**Comment by CyntaxDotDev** [comment]
ReSpawN submitted:

Also, this fixes a slight overflow glitch on checkbox boxLabels;

<pre>
.x-form-check-wrap {
    min-height: 20px !important;
}
</pre>

Also, in the same environment.
