### ISSUE TITLE
Filenames are displayed to short

### ISSUE THREAD

**Issue by mindeffects** [modxbot/migrate#5515]
mindeffects created Redmine issue ID 5515

In the tumbnails section of the MODX Browser (files) the space for filename is quite small. Only one line ended by an elipsis. For image names that's by far not enough. The right side column is also way to narrow by default since the filename is not split over multiple lines but written in a single line.

Maybe php's wordwrap could help:

<pre>
$filenameWrapped = wordwrap( $filename,$width=24, $break = "<br />", $cut=true)
</pre>

Longer filename are VERY helpful, so maybe you give wordwrap a try?

**Comment by opengeek** [comment]
opengeek submitted:

Addressed by https://github.com/modxcms/revolution/pull/446
