### ISSUE TITLE
Can't save document after validation fails

### ISSUE THREAD

**Issue by deadcow** [modxbot/migrate#5517]
deadcow created Redmine issue ID 5517

Friendly URLS on
Automatic alias off

New Document, enter title, don't enter alias, save, see alias input becoming red, try to save again : "An error occurred while duplicating the resource". No more possibility to save, even when alias is filled.

**Comment by deadcow** [comment]
deadcow submitted:

OK I don't know if anyone cares but here's my update :

Everytime you create a ressource, just before there's a token generated in session so that you can call the save function once and no more after that. When you save your ressource, your token is removed from session, even though the save can fail (which happens in my example).

I see two problems here :
- the token should not be deleted before checking the save result
- when the token is not found, the message thrown is "An error occurred while duplicating the resource", which makes no sense in my case. Better check twice before throwing such a message.

Here's the code that deletes the token and throws the message (core/model/modx/processors/ressources/create.php) :

if(isset($scriptProperties['create-resource-token'])) {
    $tokenFound = false;
    $tokenPassed = $scriptProperties['create-resource-token'];
    if(!is_null($tokenPassed)) {
        if(isset($_SESSION['newResourceTokens']) && !is_null($_SESSION['newResourceTokens'])) {
            $search = array_search($tokenPassed, $_SESSION['newResourceTokens']);
            if($search !== false) {
                unset($_SESSION['newResourceTokens'][$search]);
                $tokenFound = true;
            }
        }
    }
    if($tokenFound === false) {
        return $modx->error->failure($modx->lexicon('resource_err_duplicate'));
    }
}

**Comment by gerritvanaaken** [comment]
gerritvanaaken submitted:

I can second that problem! 

Out-commenting the last three lines of the code above, however, solves it for me. I could not save new documents, regardless of wether I defined an alias manually or not.

This is a real blocker. Not being able to save a newly created document!!! This is the most basic task a CMS can perform!

**Comment by MarkH** [comment]
markh submitted:

This has been fixed in 2.2, based on the bug report #5068

"[#5068] Move token check for new resources below error validation in processor to prevent bogus duplicate resource issue"
https://github.com/modxcms/revolution/commit/9ea2233ae41b28be94f9f4e78beca581e78e196c

**Comment by gerritvanaaken** [comment]
gerritvanaaken submitted:

For me, de-activating "cache_db" solves the problem, too.

**Comment by opengeek** [comment]
opengeek submitted:

Both the cache_db issues and save issues have been addressed for 2.2
