### ISSUE TITLE
 doc manager 2.1 beta 6 error

### ISSUE THREAD

**Issue by pepebe** [modxbot/migrate#5531]
pepebe created Redmine issue ID 5531

Installing docmanager in modx revo fails. Uninstalling is not possible. You get an awful lot of error messages (for the uninstallation, see below) and the docmanager entry can not be removed from the list of installed plugins.

Though the  package manager claims that "This version works with Revolution 2.0.0-beta5 or later only." this is obviously not true.

For the time being, this package should be removed from the respository. We have janitor and this one doesn't cause any trouble...

Uninstallation messsages:
/*
- MODX Console Output
  *
- @date 2011-08-16 18:04:52
  */
  Finding package with signature: docmanager-2.1-beta6

Package found. Preparing to uninstall.

Could not load class: modLexiconLanguage from mysql.modlexiconlanguage.

Problem instantiating object from vehicle

Could not load class: modLexiconTopic from mysql.modlexicontopic.

Problem instantiating object from vehicle

Skipping modMenu object (data object does not exist and cannot be removed): Array
(
    [text] =&gt; docmanager
)

Skipping modAction object (data object does not exist and cannot be removed): Array
(
    [namespace] =&gt; docmanager
    [controller] =&gt; index
)

Removing files in file resolver: /home/public_html/subdomains/art/assets/components/docmanager

Could not find files to remove.

Removing files in file resolver: /home/public_html/subdomains/art/core/components/docmanager

Could not find files to remove.

Could not resolve vehicle for object of class modMenu; criteria: Array
(
    [text] =&gt; docmanager
)

Skipping modNamespace object (data object does not exist and cannot be removed): Array
(
    [name] =&gt; docmanager
)

Recoverable error: Object of class xPDOObjectVehicle could not be converted to string

PHP notice: Object of class xPDOObjectVehicle to string conversion

Error uninstalling package with signature: Object

/\* EOF */

**Comment by splittingred** [comment]
splittingred submitted:

This bugtracker is for MODX core issues only.

Secondly, Docmanager is compat with 2.0.x only. I've updated the package to reflect that. Use Batcher instead.
