### ISSUE TITLE
setting for en/disabling minification

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#5539]
netprophet created Redmine issue ID 5539

It would be useful in a couple of scenarios to be able to disable minification of javascript and css in the manager.
- during modx or extras development
- if minification is problematic in a particular configuration

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/89d1332cb3a2645fabb434066f5e7827ba5704f7
