### ISSUE TITLE
Possibility to move files/folders

### ISSUE THREAD

**Issue by frischnetz** [modxbot/migrate#5542]
frischnetz created Redmine issue ID 5542

At this time there is no possibility to move files, neither in the ressource-tree nor the modx-filebrowser. Publishers have to delete items and re-upload them.

Moving files by dragging and dropping them in the ressource tree would be the best solution. 

At this time users can get confused, because dragging of the filename works already, the files just snap back into original place when dropped.

**Comment by splittingred** [comment]
splittingred submitted:

Already done for 2.2.
