### ISSUE TITLE
Package Management: LIKE search

### ISSUE THREAD

**Issue by CyntaxDotDev** [modxbot/migrate#5561]
ReSpawN created Redmine issue ID 5561

Haven't got a clue if this has been reported already, but is definitly needs a LIKE search. For example, searching on "ion" should get me at least all VisionCart packages and "mail" should return at least modSwiftMailer, and perhaps even DitsNews, since the description contains it... :)

**Comment by splittingred** [comment]
splittingred submitted:

Done: https://github.com/modxcms/revolution/commit/195625032a57ad44c3686a7f65edab5dda1022af
