### ISSUE TITLE
Dashboard Widget - Clear cache on save

### ISSUE THREAD

**Issue by CyntaxDotDev** [modxbot/migrate#5587]
ReSpawN created Redmine issue ID 5587

Although this is not really a feature and the 2.2.0 is not even public yet, I reckon this is a minor oversight for developers. It really required a clear cache, if only it is a dashboard clear cache.

**Comment by splittingred** [comment]
splittingred submitted:

Erm, there is no caching on the dashboards. What are you referring to?

**Comment by CyntaxDotDev** [comment]
ReSpawN submitted:

When I create a "inline PHP" type dashboard, I cannot see any changes on the dashboard in the frontpage of the manager due to some sort of cache. When I clear my cache, it updates. Much like a Snippet but then without the automatic clear cache.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed here: https://github.com/modxcms/revolution/commit/cf48a01202a10e2727067bbcd2ed389ff1fbb25a#L2L129
