### ISSUE TITLE
Subtemplating

### ISSUE THREAD

**Issue by johnywhy** [modxbot/migrate#5588]
johnywhy created Redmine issue ID 5588

a subtemplate could be picked from the Document editor, same as the template is picked in the Document editor. Only then would it be active. 

further, it would only display it's TV's in the Document editor when it's active. for example, say i have a StandardPage template, a Tour sub-template with it's own TVs, and a Gallery sub-template with it's own TV's. Then in the Document editor, the manager picks the StandardPage template and the Tour subtemplate. Then, the Document editor should only display the TVs for the Tour subtemplate. 

a robust sub-templating system would allow multiple levels-- templates within templates within templates. Again, the Document editor would allow manager to pick which subtemplates and sub-subtemplates to use. 

a robust subtemplating system would be able to specify to which subtemplates Templates have access. So that, in the Document editor, when the manager picks a given Template, she would then only be able to pick the subtemplates it has access to. 

For example, my Parent template contains my header, menu, sidebar, and footer.

Now I want a template for my Tour pages, which would go into the content region of the Parent template. Like the parent template, it would contain template variables, which would be filled in by the resource pages. 

I have 2 or 3 different kinds of pages: Tours, Gallery, Assets. Each kind of page would have common layout (all Tour pages would have identical layout, all Gallery pages would share an identical layout which is different from the Tour pages). 

But all kinds (Tours, Gallery, Assets) would share the Parent template. 

Achieving this with Chunks seems a painful workaround, especially trying to achieve deeper levels of sub-subtemplates. 

Subtemplates should be listed in the Templates group (or a new classification just for subtemplates). 

i'd be surprised if this is not even on the roadmap for modx. It seems directly in-line with the modx philosophy. 

http://ttyl.modx.com/thread/28499/nested-or-sub-templates

**Comment by splittingred** [comment]
splittingred submitted:

Chunks are the preferred way of handling this. This is even more doable through using properties on Templates and Chunks.
