### ISSUE TITLE
Uncached placeholder with uncached children fails epicly

### ISSUE THREAD

**Issue by CyntaxDotDev** [modxbot/migrate#5606]
ReSpawN created Redmine issue ID 5606

In VisionCart we are usually using a couple of different pagetitles to put something on screen. The first bug occurred in 2.0.7, was fixed a couple versions later, reared its head back in 2.1.2 and got patched - somewhat - in 2.1.3. The following case is a working case that shouldn't work at all, or rather, not like this.

We have 2 placeholders, both available cached and uncached. vc.product and vc.category. When we try the following, it doesn't work.

<pre><h1>[[!+vc.product.name:empty=`[[!+vc.category.name:eq=``:then=`Webshop`:else=`[[!+vc.category.name]]`]]`]]</h1></pre>

When we try an uncached placeholder with cached placeholders (since an uncached placeholder in any uncached portion doesn't work, this example works.

<pre><h1>[[!+vc.product.name:empty=`[[+vc.category.name:eq=``:then=`Webshop`:else=`[[+vc.category.name]]`]]`]]</h1></pre>

Now, basically the parser recognizes the first placeholder as being uncached and parsed the inner the same, although those are called as uncached as well. We have the same problem in our parseChunk, which uses the modChunk basic functionality. It parses ALL cached content but not the uncached, although in our heads uncached content should ALWAYS ... ALWAYS be parsed.

_If our current example is the wrong way and our heads are messed up, please let us know directly or via this bug. Tx guys._

**Comment by opengeek** [comment]
opengeek submitted:

You can't process non-cacheable content until all cacheable content has been processed, including any nested tags and cacheable tags returned by other cacheable tags. That said, this was already addressed in 2.1.3. If this still persists in 2.1.3, the other possibility is your problem may be related to #5377, which is fixed for 2.2.

**Comment by CyntaxDotDev** [comment]
ReSpawN submitted:

The logic behind it is very strange to me at this point, but I'll look it over in the morning too see if this is indeed the correct behaviour. In any case, I can keep it in mind while developing and count on that type of behaviour. 

Tx Jason
