### ISSUE TITLE
Use groupsConfig & min_cachePath for Google Minify in 2.2

### ISSUE THREAD

**Issue by Martijn1981** [modxbot/migrate#5614]
Martijn1981 created Redmine issue ID 5614

Check out point 6 at http://www.mrclay.org/2008/09/19/minify-21-on-mrclayorg/.  It's the fastest way of serving these files. Also, make sure the min_cachePath has been properly enabled!

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/1312b818d99aefcc2a84254d4795909d291f613b

However, made a toggleable option defaulting to off, as this prevents people from using the limit-number-of-js files setting.
