### ISSUE TITLE
Action to lowercase

### ISSUE THREAD

**Issue by eprochasson** [modxbot/migrate#5664]
eprochasson created Redmine issue ID 5664

Not sure it's really a bug, but it cost me a lot of time to figure this out.

When calling a processor through a connector, the modConnectRequest::handleRequest method performs this :

<pre>
$options['action'] = strtolower($options['action']);
</pre>

I don't really see the purpose of it, and it was very misleading in my case, since I was working with a team of MacOS, Windows and myself, Linux. They designed the processors, using mixed case name for their names and directory. The problem is that MacOS and Windows file systems are case insensitive (in other word, this line has no effect) whereas Linux is case sensitive.

My concern is that people are likely to create and test a component with mixed case files and directory names, which will fail as they put them in production on a Linux server.

**Comment by splittingred** [comment]
splittingred submitted:

Actually, a ton of the views call for "getList" as the action, and this fix would break those on unix-based environments, which are case-sensitive.
