### ISSUE TITLE
console.log vs IE

### ISSUE THREAD

**Issue by webandflow** [modxbot/migrate#5665]
webandflow created Redmine issue ID 5665

In modext.js (line 4846) and modext-min.js, there is a single console.log() call that breaks the duplicate resource contextual menu command when using IE browsers. Removing this should correct the problem.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/d0745536d58e5b4ae09719af1a69af2eacfa9e5e
