### ISSUE TITLE
add outputfilters attached to MODX Core Functions

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#5671]
wshawn created Redmine issue ID 5671

I believe these help functions should have been implemented as filters some time ago...

:csstohead      $modx->regClientCSS($m_val);
:htmltobottom  $modx->regClientHTMLBlock($m_val);
:htmltohead     $modx->regClientStartupHTMLBlock($m_val);
:jslinktobottom $modx->regClientScript($m_val)
:toplaceholder $modx->toPlaceholder($m_val, $output,'','');

**Comment by splittingred** [comment]
splittingred submitted:

Added: https://github.com/modxcms/revolution/commit/c3df755eee362e8cb5b8703b3a0ff763435a69a6

**Comment by opengeek** [comment]
opengeek submitted:

Cherry-picked for inclusion in 2.1.4-pl
