### ISSUE TITLE
Buttons cannot be clicked

### ISSUE THREAD

**Issue by johnywhy** [modxbot/migrate#5705]
johnywhy created Redmine issue ID 5705

Modx is the only site I've ever seen on which buttons cannot be clicked. 

Only the text inside the button can be clicked. Clicking the button outside of the text does not work. 

I consider this critical, because an admin may click the save button, thinking, reasonably, that the file wad saved, when in fact it was not saved. 

I am surprised this was not considered essential last time I posted it, reason given that it's too difficult to fix so many buttons. Consider a global button CSS. Also, explore global search and replace. 

But thanks for modx just the same!

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/aa1536093edcd7678778784d3be55855be6c93fb

**Comment by johnywhy** [comment]
johnywhy submitted:

still affects some buttons around the interface, including:
- The main login button
- and others which i cannot remember, but will add them here as i notice them.
