### ISSUE TITLE
Ressource tree drag & drop functionality not working in package managemanet view

### ISSUE THREAD

**Issue by KristianP** [modxbot/migrate#5709]
KristianP created Redmine issue ID 5709

The drag & drop functionality in the ressource tree (same for category sorting) is not working when the user is in package managemanet view.
# Login to backend
# Open Package Management
# try to reorder the resources in the Resource tree

Tested in:
- Opera 11.51
- Chrome 13.0.782.220
- Firefox 6.0

Notice:
No JavaScript errors returned.

**Comment by opengeek** [comment]
opengeek submitted:

I can confirm that I cannot drop anything that is dragged when in this view, in the latest from the release-2.2 branch.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/59cd90d8d6f58f50cc1eb7cc19dfbf389b79114c
