### ISSUE TITLE
Upgrade to develop from Git failes

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#5710]
gadamiak created Redmine issue ID 5710

On upgrade to latest develop branch from Git, the installer fails with HTTP 500. The server log shows:

> @PHP Fatal error:  Call to a member function fromArray() on a non-object in /.../setup/includes/upgrades/common/2.2-media-sources.php on line 71@

In manager the media source command is missing and media source select on files tab doesn't work. The server log populates with:

> @PHP Fatal error:  Call to a member function getWorkingContext() on a non-object in /.../core/model/modx/processors/browser/directory/getlist.php on line 31@

**Comment by splittingred** [comment]
splittingred submitted:

Fetch/rebase, then rebuild, and run setup again. Was a typo. https://github.com/modxcms/revolution/commit/fd7a8bcabbf5a70e20810fba967cf10903a05168

**Comment by gadamiak** [comment]
gadamiak submitted:

That was quick! I confirm it's been fixed. Thank you.
