### ISSUE TITLE
Element name in H2 heading reverts after changing & saving

### ISSUE THREAD

**Issue by jrotering** [modxbot/migrate#5715]
jrotering created Redmine issue ID 5715

When you update the name of an existing element (in the standard editing panel), it changes immediately in the heading H2. However, after you save, the H2 reverts back to the original element name.  Seems to be true of all element types.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in 2.2: https://github.com/modxcms/revolution/commit/98248672298654ede564e97e8235c2e2a0039f94
