### ISSUE TITLE
"Published" checkbox aligns funny when "Template" field is hidden

### ISSUE THREAD

**Issue by jrotering** [modxbot/migrate#5716]
jrotering created Redmine issue ID 5716

When an FC rule hides the Template field on a resource form, the "Published" field floats all the way to the left margin.  Perhaps easily fixed with a CSS tweak(?)

**Comment by MarkH** [comment]
markh submitted:

A (temporary) option would be to use the movePublished plugin I made some time ago which actually places the element in another location (near "Hide from Menus") and aligns it normally. It's in the Extras repo.
