### ISSUE TITLE
MODX Browser doesn't open from files tab in Chromium

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#5721]
gadamiak created Redmine issue ID 5721

MODX Browser doesn't open from files tab in Chromium. It opens correctly from TV, however.

**Comment by splittingred** [comment]
splittingred submitted:

We do not support Chromium. Please use Chrome.

**Comment by gadamiak** [comment]
gadamiak submitted:

Works on Chrome? Should do on Chromium too. Besides it worked fine untill recently in 2.2 dev.
