### ISSUE TITLE
Media sources combo on files tab doesn't work for limited users

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#5722]
gadamiak created Redmine issue ID 5722

Media sources combo select on files tab doesn't work for manager users with limited access, ie. not belonging to Administrator group.

The combo shows id 1 instead of the media source name and clicking it doesn't open a list but just flashes and remains dead after that.

More to that, I assigned media source admin policy _only_ to Administrator group on the default media source "Filesystem" and it still shows up in files tab for limited users, who should not have any access to it, ie. its content shows, while it shouldn't.

**Comment by splittingred** [comment]
splittingred submitted:

You'll need to update to latest Git, for one.

Secondly, you'll need to ensure that the User has the permission 'source_view' for the mgr context.
