### ISSUE TITLE
Display media source title as root node on files tab

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#5754]
gadamiak created Redmine issue ID 5754

Despite media source being used, the root node on files tab is always "Files". This is misleading to users as they don't want to see "Files" but, say, "Images" which they've chosen.

The root node name should match the media source title. Other option is to not display it at all if possible.

**Comment by splittingred** [comment]
splittingred submitted:

Done: https://github.com/modxcms/revolution/commit/b612baee2c216ad36c383c6833159c48272667c1

Good idea!
