### ISSUE TITLE
Insert image / media window - CZECH - broken language

### ISSUE THREAD

**Issue by smiley** [modxbot/migrate#5756]
smiley created Redmine issue ID 5756

When opening the insert image or media window the labels of the fields show their name and not the propper description.

advimage, media

This happens when manager_language is set to CS

I looked i.e. for advimage_dlg.src to find some reference / not finding a language file. But for instance the "Insert link" translates well and also does not include an extra language file.
Also when I tried to replace / add the XX_dlg.js files for the above mentioned plugins I failed. (tried to add the en as cz etc.)

If there is translation to be done, tell me where :)
Jakub

**Comment by splittingred** [comment]
splittingred submitted:

Please use the TinyMCE tracker:

http://github.com/splittingred/TinyMCE/issues/

This tracker is for core MODX issues only.
