### ISSUE TITLE
Select / Copy for Manager List Key-Entries

### ISSUE THREAD

**Issue by mindeffects** [modxbot/migrate#5757]
mindeffects created Redmine issue ID 5757

It would be so super awesome if in Manager lists the "key"-entries would be selectable and therefore copy-/pasteable!

For example:

With system settings, to copy one setting to a context, there is no copy/paste possibility since the key-entry is not selectable.

In "form customization" when you want to shift a TV from one tab to another and have to type the name of the target tab. It would be easy if one would be able to copy the name from the "Tab"-tab but is is not selectable. So it must me entered manually which can cause trouble if misspelt.

Could this very little but life-time-saving feature be implemented? THANKS!!!

**Comment by splittingred** [comment]
splittingred submitted:

Fixed for 2.2: https://github.com/modxcms/revolution/commit/ca170198bda34f9a5cd81d4f3be8a13a3c06881f

**Comment by opengeek** [comment]
opengeek submitted:

And for 2.1.4-pl: https://github.com/modxcms/revolution/commit/c2dab05ff2f87c9b23d8bccb4c6125047ffec277
