### ISSUE TITLE
3rd-level categories not selectable by elements

### ISSUE THREAD

**Issue by jrotering** [modxbot/migrate#5763]
jrotering created Redmine issue ID 5763

If you create a category hierarchy more than two levels deep, categories at the 3rd depth level or greater do not appear in the "category" dropdown list on elements, property sets, etc.

**Comment by splittingred** [comment]
splittingred submitted:

An ugly fix, but one nonetheless, until we get true closure sorting working: https://github.com/modxcms/revolution/commit/554242f2b9f9e96ae358584835716f02643e8750
