### ISSUE TITLE
Manager: System setting default_per_page ignored for Package Management

### ISSUE THREAD

**Issue by warenhaus** [modxbot/migrate#5779]
warenhaus created Redmine issue ID 5779

The screen "Package Management" keeps showing only 10 packages, even if I set the Back-end Manager system setting default_per_page to 20 or 30. 

Package Management should use the default_per_page system setting, or get another one specific to Package Management, if necessary.

**Comment by splittingred** [comment]
splittingred submitted:

This is a forced setting, as we don't want someone to flood the modx.com provider by asking for 400 packages per page.

**Comment by warenhaus** [comment]
warenhaus submitted:

created feature request regarding notification on updatable packages: http://bugs.modx.com/issues/5811
