### ISSUE TITLE
Blocked user cannot be re-activated via manager

### ISSUE THREAD

**Issue by gerritvanaaken** [modxbot/migrate#5780]
gerritvanaaken created Redmine issue ID 5780

My customer logged in too often with a wrong password. The system blocked him. I re-activated him. He still cannot log in.

I looked in the DB – my re-activation was not saved, user still blocked.

Had to manually set the field in the DB, now he can login again.

**Comment by splittingred** [comment]
splittingred submitted:

This works fine for me. How are you 're-activating' him? By blocked, do you mean the "blocked" checkbox on the user edit screen? Or the "active" field?

**Comment by gerritvanaaken** [comment]
gerritvanaaken submitted:

Okay, this seems to be a caching issue with activated "DB Cache". 

DB Cache prevents correct display of settings in the manager, which makes it pretty useless.

You might close this issue!
