### ISSUE TITLE
User group context access: not updating status

### ISSUE THREAD

**Issue by gerritvanaaken** [modxbot/migrate#5781]
gerritvanaaken created Redmine issue ID 5781

Try this:

1) Add a new user group
2) add a new context access to this user group (works!)
3) add a second, different context access to the same user group (will not be shown!)

Only the first user group context access will be shown. The others exist, though. After several cache cleanings and logouts and logins and using a different browser, the context accesses get displayed.

Funnily enough, the counting number of context accesses (bottom-right at this table) is updated perfectly alright, only the table rows with the new entries are not displayed!
The ne

**Comment by opengeek** [comment]
opengeek submitted:

I assume this is with the setting cache_db enabled? If so, this is a known bug and requires manual cache refreshes after changes are made to see them in the manager. I would recommend disabling cache_db unless you absolutely need it for a specific reason (e.g. remote database server).

**Comment by gerritvanaaken** [comment]
gerritvanaaken submitted:

This is a "DB Cache" problem, yes. After deactivating cache_db, all is good.

You can close this issue!

**Comment by opengeek** [comment]
opengeek submitted:

Fixed for 2.2.0-rc1 — see https://github.com/modxcms/revolution/commit/aefac5a400b92095391e3f97067910878e603238
