### ISSUE TITLE
Instable Context Switching

### ISSUE THREAD

**Issue by gerritvanaaken** [modxbot/migrate#5782]
gerritvanaaken created Redmine issue ID 5782

I use the recommended method for multiple domains, using multiple contexts. In fact, my "web" context ist empty, and I switch to the appropriate context with a plugin that fires onHandleRequest.

However, the Context Settings, which should overwrite some of the base settings and add a lot of new settings to the system, are not loaded correctly – sometimes!

The context switch is alright. It always prints the correct $modx->context->key; when asked. But all the [[++my_setting]] TV show only the standard values.

Then I clear the cache, logout, login, use a different browser – works.

A few hours later my client calls me: The site is empty. No loading of context settings again! There is no real pattern here, MODX just sometimes looses the ability to get the context settings right. This is not acceptable! I cannot clear the cache every 15 minutes and check if all domains run their correct context settings!

**Comment by opengeek** [comment]
opengeek submitted:

Can you first make sure that all of your Contexts are loadable by anonymous users? Go to anonymous User Group and view Context Access. You should have at least a Load Only policy attached to each Context with an authority of 9999 or anonymous users will not be able to access those Contexts at all.

**Comment by gerritvanaaken** [comment]
gerritvanaaken submitted:

I changed that and we’ll see how it works. Thank you for helping!

You might close that issue for now.
