### ISSUE TITLE
content is not sent to browser until after shutdown function

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#5788]
netprophet created Redmine issue ID 5788

As an experiment, I added a 20 second sleep in a plugin attached to OnWebPageComplete, which is run during the registered shutdown function, which happens after ob_end_flush() loop and exit().
MODx did not send content to the browser until after the shutdown function was complete. In otherwords, the ob_end_flush() loop did not succeed in sending output to the client.
Adding flush() immediately following the ob_end_flush() and before exit() has improved this, in that the content is now flushed to the browser, even though the http connection isn't ended until after the shutdown function.

**Comment by opengeek** [comment]
opengeek submitted:

Cherry-picked for inclusion in 2.1.4-pl
