### ISSUE TITLE
min unstable on IIS

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#5804]
netprophet created Redmine issue ID 5804

Users have reported trouble in the manager related to min.

**Comment by MarkH** [comment]
markh submitted:

I've had issues (still do, tho I haven't had time to real dive into this) trying to run 2.2 locally using WAMP. That runs apache but on my W7 laptop obv.

I sent Shaun the debug info from Google Minify some time ago but haven't had  much time to get back to that. 

Just throwing this out there in case it's useful. :D

**Comment by splittingred** [comment]
splittingred submitted:

Testing has confirmed minify is working fine on IIS, WAMP, MAMP and other LAMP environments. Closing until more specific, targeted issues occur.
