### ISSUE TITLE
modInstallSmarty::fetch not compatible with Smarty::fetch

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#5805]
netprophet created Redmine issue ID 5805

Installer gives following error

Strict standards: Declaration of modInstallSmarty::fetch() should be compatible with that of Smarty::fetch() in C:\xampp\htdocs\revolution\setup\includes\parser\modinstallsmarty.class.php on line 35

On Win/Apache, attempts to mute reporting of strict standards errors do not stop this from showing.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/db4d8d692dc5436c86fc19e508c9b5cf6e5baf1a
