### ISSUE TITLE
Package Browser not scrollable

### ISSUE THREAD

**Issue by ottogal** [modxbot/migrate#5817]
ottogal created Redmine issue ID 5817

When you unfold the modx.com>Extras folder in the Package Browser (in Package Retriever) you get a list which is too long to be displayed as a whole. You can not scroll down, so the buttons at the end are unaccessible.
Only workaround is using the Browser's scaling down (Ctrl-minus) till a unreadable size.

**Comment by splittingred** [comment]
splittingred submitted:

This has been fixed with the recent Package Management revamp for 2.2.
