### ISSUE TITLE
First media source shows on files tab despite ACL

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#5832]
gadamiak created Redmine issue ID 5832

This is related to #5722:

> I assigned media source admin policy only to Administrator group on the default media source "Filesystem" and it still shows up in files tab for limited users, who should not have any access to it, ie. its content shows, while it shouldn't.

Resolving #5722 has hidden unprivileged media sources for selection in the combo. However, just after logging in, unprivileged user _has access to any first media source and its files despite ACL_. In most cases this will be the default "Filesystem" MS.
- If _there is no other_ MS for which a _user is authorized_, the combo shows first MS's numeric ID (which is incorrect) and expands to nothing (which is correct). MODX browser also displays this MS's files.
- If _there are other_ MSs for which user _is authorized_, they show in the combo. Selecting any of them displays related files and going back to "Filesystem" is impossible (which is correct).

Users without @source_view@ permissions _should not see _any_ media source_, ie. the media source combo and files tab content should be empty.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/2657528b661110d0b85436f140310183142ebd02
