### ISSUE TITLE
Add media source select to MODX browser

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#5834]
gadamiak created Redmine issue ID 5834

When opening MODX browser from files tab it shows only the media source selected on files tab. While this should apply to browser instances opened from inside resources and tvs, when opened from files tab it should allow to switch between media sources available to user.

**Comment by splittingred** [comment]
splittingred submitted:

No, it shoudn't - a TV is bound to the Media Source it uses. You should not be able to switch between sources in a TV.

**Comment by gadamiak** [comment]
gadamiak submitted:

Well, I guess my request was not explicit enough. Maybe my English failed ;)

Shaun McCormick wrote:

> No, it shoudn't - a TV is bound to the Media Source it uses. You should not be able to switch between sources in a TV.

That's not what I requested. My request is about switching media sources in browser opened _from files tab_, not from static resources or TVs. I hope, it's clear now.
