### ISSUE TITLE
Use the same paths for CLI and GUI setup

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#5835]
gadamiak created Redmine issue ID 5835
- CLI setup config file (@config.xml@) specifies more paths than are used by GUI setup and defined in @core/config/token.inc.php@. This is misleading and confusing and... unnecessary, I guess. Since GUI setup can go with 6 paths, CLI shouldn't need more.
- Additionally, the current naming convention for path nodes in @config.xml@ is not clear and leads to confusion. This is especially important for shared core installations.

See "this thread on MODX forums":http://forums.modx.com/thread/70591/considerations-for-setting-paths-for-cli-upgrade.

**Comment by splittingred** [comment]
splittingred submitted:

Resolved here: https://github.com/modxcms/revolution/commit/c1a3883d5c466524e17d2064e2d6657510c9a0c0
