### ISSUE TITLE
CLI setup has problem with paths on shared core installations

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#5837]
gadamiak created Redmine issue ID 5837

As "described on MODX forums":http://forums.modx.com/thread/70591/considerations-for-setting-paths-for-cli-upgrade, the CLI setup has difficulties with shared core installations. It basically messes the paths:
- The @MODX_CORE_PATH@ is taken from @web_path@ or @context_web_path@ in @config.xml@.
- @MODX_MANAGER_PATH@ and @MODX_CONNECTORS_PATH@ are taken from the 'context' group instead of 'core'.
- The @MODX_BASE_PATH@ is calculated from @MODX_CORE_PATH@, which is not the case in shared core installation.

I reported this one to keep track of a problem. It's related to #5835 and both will be resolved by the same fix, I guess.

**Comment by splittingred** [comment]
splittingred submitted:

Resolved here: https://github.com/modxcms/revolution/commit/c1a3883d5c466524e17d2064e2d6657510c9a0c0
