### ISSUE TITLE
Compressed JS doesn't work after 6 files to compress

### ISSUE THREAD

**Issue by bertoost** [modxbot/migrate#5840]
bertoost created Redmine issue ID 5840

Just installed the dev version of 2.2 (on my local linux development machine) and when I login I see the dashboard but without the left side panel (resource, elements and files). I can navigate through the top menu but all "subpages" are fully blank. The content is completely empty:

<pre><div id="modx-content">
    <div id="modx-panel-holder"></div>
    <div id="modx-panel-users-div"></div>
</div></pre>

I have to made a change to the system settings in the database. I have set "compress_js" to "0" (false) to let the manager work. The compressed css is working for me. When I see the source, I can click on the src of the script tags and when I do I end on the webroot of my local server. When I do the same for the compressed css I see the compressed css. The paths seems to be okay!

I did some debug; it seems to be a kind of limitation to the includable files. I opened the first script tag src and removed all files to minify. Add one for one back in and after the sixth one he fails. There ware just 2 files which couldn't be added, tried the last one before and didn't work either. The files do exists and do have the right permissions.

Can someone take a look at this? And can I help fixing it?

Version 2.2 looks very cool by the way!

**Comment by splittingred** [comment]
splittingred submitted:

Bert,

Can you update to the latest Git? (I've also updated the latest nightly, so you can try that as well.) There's a fix in there that might help.

**Comment by bertoost** [comment]
bertoost submitted:

Hi Shaun,
tried it directly and unfortunately it makes no difference :-(

let me know if I can try something... I can also give you access to my develop machine if you want to do some debug

**Comment by splittingred** [comment]
splittingred submitted:

Does turning xdebug off help?

**Comment by bertoost** [comment]
bertoost submitted:

no unfortunate not

**Comment by splittingred** [comment]
splittingred submitted:

What about suhosin?

**Comment by bertoost** [comment]
bertoost submitted:

Nothing changed unfortunately

**Comment by splittingred** [comment]
splittingred submitted:

Try now. (with latest Git)

**Comment by bertoost** [comment]
bertoost submitted:

No it still not works with compressed JS on.
Did you checked the limitation? The compressed javascript call I see on the dashboard;

http://~my-ip~/modx-2.2.0-dev/manager/min/?f=/modx-2.2.0-dev/manager/assets/modext/core/modx.localization.js,/modx-2.2.0-dev/manager/assets/modext/util/utilities.js,/modx-2.2.0-dev/manager/assets/modext/core/modx.component.js,/modx-2.2.0-dev/manager/assets/modext/widgets/core/modx.panel.js,/modx-2.2.0-dev/manager/assets/modext/widgets/core/modx.tabs.js,/modx-2.2.0-dev/manager/assets/modext/widgets/core/modx.window.js,/modx-2.2.0-dev/manager/assets/modext/widgets/core/modx.tree.js,/modx-2.2.0-dev/manager/assets/modext/widgets/core/modx.combo.js

When I remove the 2 last files then the compressing is working, with the last 2 files there is an redirect to my webroot

**Comment by splittingred** [comment]
splittingred submitted:

Well, I think this is specific to your environment. But, I've added a solution that may help you:

https://github.com/modxcms/revolution/commit/a725f869179870e15eda00b5c8c238b8e99d8308

Set the "compress_js_max_files" System Setting to 5. (You may need to do this in the DB and clear core/cache/ if you can't load the mgr.) That will restrict the number of the JS files compressed in one tag to 5.

**Comment by bertoost** [comment]
bertoost submitted:

Hmm I dont like this kind of solution; It sounds to me that you dont want to fix it.. you create a work around... I wanna help wherever  I can but this is the easiest way of course.

I used the minify also, even with more files to compress on the same envoirement and it's working great. Sorry for the words but this isn't the kind of solution I'll suggest.

**Comment by splittingred** [comment]
splittingred submitted:

"Dont want to fix it" is not really true - the problem is not replicable on any testing environment we have experienced, and so we cannot fix something we cannot reproduce.

Secondly, it's not a "workaround" in the sense that it's invalid - some machines with low memory allotments seem to putter out due to time limits and/or memory threshold requirements. Rather than just asserting that "they need to up the memory", this fix allows them to scale back the number of JS files that are being compressed on the fly.

**Comment by bertoost** [comment]
bertoost submitted:

I understand but as told you; I can give you access to my machine so you can take a look.. but you didn't react on that

My machine does have enough memory.. so that cannot be the issue.. It's a datacenter server locally so that couldn't be the problem, I understand when some software on my server creates the problem but I don't think any of the installed software is the problem
