### ISSUE TITLE
input-options are deleted after "quick-edit" a tv

### ISSUE THREAD

**Issue by thomasd** [modxbot/migrate#5852]
thomasd created Redmine issue ID 5852

When quick editing a tv (elements-tree right click -> quick edit) and saving the form, all input-options are deleted. I tried it with a tv-input-type "text" setting the min-length input-option. After saving and quick editing the tv, all input-options are empty.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/59e08ca8c77b8d888257b430d4ffe1543850e6e7
