### ISSUE TITLE
File Upload via Manager failing with error

### ISSUE THREAD

**Issue by zaigham** [modxbot/migrate#5859]
zaigham created Redmine issue ID 5859

File Upload via Manager failing with error:

_The specified directory is not a directory._

Please see the screenshots attached.

**Comment by gadamiak** [comment]
gadamiak submitted:

I confirm this in latest develop branch. I would suspect it's related to media sources.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/cfadbb486d639677ce941f77dd2fbcb693f03f34
