### ISSUE TITLE
Error parsing IN condition with key usergroup: Array()

### ISSUE THREAD

**Issue by opengeek** [modxbot/migrate#5860]
opengeek created Redmine issue ID 5860

This error seems to occur frequently when loading the manager, especially with fresh sessions.

It appears to be related to FC queries when a user is not in any user groups, but I'm not sure exactly what conditions are triggering this, since users accessing the manager should have at least one group membership.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/3eecf5425e384a421161fa76fcdd6f54dab121e7
