### ISSUE TITLE
pagetitle beginning with a < cause him to disapear

### ISSUE THREAD

**Issue by emmanuel** [modxbot/migrate#5879]
Emmanuel created Redmine issue ID 5879

 in the header when editing it show blank and in the tree when saved.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/df28d96b71d67912f3eaa91a6ba817dac77f8e6b

**Comment by opengeek** [comment]
opengeek submitted:

Fixed for 2.1.4-pl as well — https://github.com/modxcms/revolution/commit/d8ccd8b271caea1b742c173a5c182292bc970d60
