### ISSUE TITLE
Extension should not be required when creating Content Types

### ISSUE THREAD

**Issue by opengeek** [modxbot/migrate#5909]
opengeek created Redmine issue ID 5909

When creating a new Content Type in the manager, you currently have to include a value in the extension field. This should NOT be required.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/72622a4aeb4d3cb4008935885a4d8efdbb253819

**Comment by opengeek** [comment]
opengeek submitted:

Fixed for 2.1.4: https://github.com/modxcms/revolution/commit/9cbc5238e84e85f8afcc916696c855b65c70fb7a
