### ISSUE TITLE
ability to rename assets directory

### ISSUE THREAD

**Issue by Qwarble** [modxbot/migrate#5931]
Qwarble created Redmine issue ID 5931

To rename assets directory after modx installation you need to change not only configuration file but manager/controllers/default/workspaces/index.php too becouse of hard coded assets folder (package manager doesn't work without these changes).
There is such piece of code
@
/\* create assets/ */
$assetsPath = $modx->getOption('base_path').'assets/';
if (!is_dir($assetsPath)) {
    $cacheManager->writeTree($assetsPath,$directoryOptions);
}
if (!is_dir($assetsPath) || !is_writable($assetsPath)) {
    $errors['assets_not_created'] = $modx->lexicon('dir_err_assets',array('path' => $assetsPath));
}
unset($assetsPath);

/\* create assets/components/ */
$assetsCompPath = $modx->getOption('base_path').'assets/components/';
if (!is_dir($assetsCompPath)) {
    $cacheManager->writeTree($assetsCompPath,$directoryOptions);
}
if (!is_dir($assetsCompPath) || !is_writable($assetsCompPath)) {
    $errors['assets_comp_not_created'] = $modx->lexicon('dir_err_assets_comp',array('path' => $assetsCompPath));
}
unset($assetsCompPath);
@
which should probably be like

@/\* create assets/ _/
/_changed string*/
$assetsPath = defined("MODX_ASSETS_PATH")?MODX_ASSETS_PATH:$modx->getOption('base_path').'assets/';
if (!is_dir($assetsPath)) {
    $cacheManager->writeTree($assetsPath,$directoryOptions);
}
if (!is_dir($assetsPath) || !is_writable($assetsPath)) {
    $errors['assets_not_created'] = $modx->lexicon('dir_err_assets',array('path' => $assetsPath));
}
unset($assetsPath);

/\* create assets/components/ */

/_changed string_/
$assetsCompPath = (defined("MODX_ASSETS_PATH")?MODX_ASSETS_PATH:$modx->getOption('base_path').'assets/').'components/';
if (!is_dir($assetsCompPath)) {
    $cacheManager->writeTree($assetsCompPath,$directoryOptions);
}
if (!is_dir($assetsCompPath) || !is_writable($assetsCompPath)) {
    $errors['assets_comp_not_created'] = $modx->lexicon('dir_err_assets_comp',array('path' => $assetsCompPath));
}
unset($assetsCompPath);@

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/7e69e5b48b94078f84f9baf92cde6a92c63016e6
