### ISSUE TITLE
Optimize modResource::setTVValue and ::getTVValue

### ISSUE THREAD

**Issue by splittingred** [modxbot/migrate#5938]
splittingred created Redmine issue ID 5938

Currently not well optimized. Look into prior to 2.2.

**Comment by opengeek** [comment]
opengeek submitted:

What specifically is not optimized about these methods?

**Comment by opengeek** [comment]
opengeek submitted:

I have optimized getTVValue by allowing it to utilize the modParser sourceCache for elements, though this only works if looking up the TV by name. Feedback welcome for additional optimization ideas...

**Comment by splittingred** [comment]
splittingred submitted:

Good enough for me for 2.2. We can look at other optimizations in later releases.
