### ISSUE TITLE
Access policy "change_profile" in modMenu

### ISSUE THREAD

**Issue by CyntaxDotDev** [modxbot/migrate#5948]
ReSpawN created Redmine issue ID 5948

The change_profile is not bound to the User -> Change Profile modAction, when placing it myself as a required permission, all works fine.

Not sure if this is my MODX acting up, but it should definitly be fixed.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/b2c433ed096241d5bb3214687e1a0805eaa70bbe
