### ISSUE TITLE
schema: phptype for modContextResource->resource is "string"

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#5962]
netprophet created Redmine issue ID 5962

Seems that phptype should be "integer" here

<object class="modContextResource" table="context_resource" extends="xPDOObject">
        <field key="context_key" dbtype="varchar" precision="255" phptype="string" null="false" index="pk" />
        <field key="resource" dbtype="int" precision="11" attributes="unsigned" phptype="string" null="false" index="pk" />

Both MySQL and SQL Server schemas have this.

**Comment by opengeek** [comment]
opengeek submitted:

Fixed for 2.2.0-rc1 at https://github.com/modxcms/revolution/commit/b3ebc60ac23c9bd3b9a940ca31dddfd2af9baf52
