### ISSUE TITLE
Checking if directory exists: Failed! on setup

### ISSUE THREAD

**Issue by FickleLife** [modxbot/migrate#5982]
ficklelife created Redmine issue ID 5982

Trying to install 2.2-dev on site5 hosting I get this error:

Installation Summary

Problems were detected. Please review the pre-installation test results below, correct the problems as directed, and then click Test again.

Checking PHP version: OK! Running: 5.2.17

Checking PHP for zlib dependency: OK!

Checking for SimpleXML: OK!

Checking if memory limit is set to at least 24M: OK! Set to 64M

Checking if sessions are properly configured: OK!

Checking if /home/racedata/public_html/core/cache directory exists: OK!

Checking if /home/racedata/public_html/core/cache directory is writable: OK!

Checking if /home/racedata/public_html/core/export directory exists: OK!

Checking if /home/racedata/public_html/core/export directory is writable: OK!

Checking if /home/racedata/public_html/core/packages directory exists: OK!

Checking if /home/racedata/public_html/core/packages directory is writable: OK!

*Checking if directory exists: Failed!

Checking if directory exists: Failed!

Checking if directory exists: Failed!*

Checking if /home/racedata/public_html/core/config/config.inc.php exists and is writable: OK!

Creating connection to the database: OK!

Checking to make sure safe_mode is off: OK!

Checking for suhosin issues:OK!

**Comment by splittingred** [comment]
splittingred submitted:
- New install or upgrade?
- From Git or nightly?

**Comment by FickleLife** [comment]
ficklelife submitted:

New install from nighty at http://modx.com/revolution/download/nightlies/

Initially tired with 29th Oct, then 30th Oct nightlies and same problem. 

After the broken install, the site throws these errors:

Strict Standards: array_merge() [function.array-merge]: It is not safe to rely on the system's timezone settings. Please use the date.timezone setting, the TZ environment variable or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'UTC' for 'GMT/0.0/no DST' instead in /home/racedata/public_html/core/model/modx/modx.class.php on line 426

Warning: array_merge() [function.array-merge]: Argument #2 is not an array in /home/racedata/public_html/core/model/modx/modx.class.php on line 426

Strict Standards: xPDO::getDriver() [xpdo.getdriver]: It is not safe to rely on the system's timezone settings. Please use the date.timezone setting, the TZ environment variable or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'UTC' for 'GMT/0.0/no DST' instead in /home/racedata/public_html/core/xpdo/xpdo.class.php on line 1663

Fatal error: Class 'xPDODriver_' not found in /home/racedata/public_html/core/xpdo/xpdo.class.php on line 1663

**Comment by splittingred** [comment]
splittingred submitted:
1. Make sure you set the "date.timezone" value in your php.ini - this is required for php 5.3+.
2. Make sure core/config/ is writable.

Closing this issue for now, as I cannot reproduce. Please reopen after following the instructions here and problems still occur:
http://rtfm.modx.com/display/revolution20/Basic+Installation
http://rtfm.modx.com/display/revolution20/Troubleshooting+Installation

**Comment by Bruno17** [comment]
Bruno17 submitted:

I've the same issue when trying to install 2.2, I mean this part:

Checking if /home/racedata/public_html/core/packages directory is writable: OK!

*Checking if directory exists: Failed!

Checking if directory exists: Failed!

Checking if directory exists: Failed!*

seems $this->install->settings->get('context_web_path') is empty in function _checkContexts() at this time.

see also here:

http://forums.modx.com/thread/71618/missing-directories---issue-on-installing-2-2
