### ISSUE TITLE
Acces Policy content_types plays a double roll

### ISSUE THREAD

**Issue by chunkyRice** [modxbot/migrate#5990]
chunkyrice created Redmine issue ID 5990

When deselecting the content_types setting in an Access Policy, users can no longer access the Content Types page in the System menu (which is what you want) but they are also refrained from setting the Content Type when creating or editing a Resource (which is not what you want). Setting the Content Type should not be affected, since access to this setting should be regulated using Form Customizations.

**Comment by gadamiak** [comment]
gadamiak submitted:

Sigge Stegeman wrote:

> When deselecting the content_types setting in an Access Policy, users can no longer access the Content Types page in the System menu (which is what you want) but they are also refrained from setting the Content Type when creating or editing a Resource (which is not what you want).

It's definitely wrong behavior.

> Setting the Content Type should not be affected, since access to this setting should be regulated using Form Customizations.

I think having two separate settings in ACL for that would be a better way to go.
