### ISSUE TITLE
"Create File" option in MODx File Tree 

### ISSUE THREAD

**Issue by pixelchutes** [modxbot/migrate#5998]
pixelchutes created Redmine issue ID 5998

I've been wondering, how easy would it be to CREATE A FILE in the File tree? For example, if you wanted to create a new static .CSS or .JS file (via MODx), it would be great if you could simply create an empty file, providing only the file name, then edit it directly like you would any existing file (no upload required)

Today you can create a directory (mkdir), and I believe you can also rename (I'll have to double-check). It would be awesome if you could create static files, too. It would almost remove the need for a separate (S)FTP/SCP program for working on MODx Revo sites.

**Comment by splittingred** [comment]
splittingred submitted:

Done for 2.2: https://github.com/modxcms/revolution/commit/66999ea9e13ce609adf7a0790ac2d5746adfc574

**Comment by pixelchutes** [comment]
pixelchutes submitted:

There were over 15 files involved in this commit, permissions were taken into account, it supports Media Sources, and all in under 3 hours on the _same day_ as the request?

/me picks jaw up off the floor...
