### ISSUE TITLE
Collapsed left tree does not render on reload

### ISSUE THREAD

**Issue by lossendae** [modxbot/migrate#6012]
lossendae created Redmine issue ID 6012

If we collapse the left tree (either manually or programatically) and reload the page or change page, the left tree stay collapsed, which is normal, but if we activate it, the tree does render. 
It require a manual reload of the page while the tree is activated to be rendered.

**Comment by MarkH** [comment]
markh submitted:

Experienced as well.

**Comment by lossendae** [comment]
lossendae submitted:

There is a method added in modx.layout to allow left tree collapsing without saving it in the state manager.

https://github.com/modxcms/revolution/blob/develop/manager/assets/modext/core/modx.layout.js#L213

If the second parameter is set to false, the state will not be saved and tree rendered correctly on page reload (used with the package manager).

Concerning the issue itself, all left tree is actually rendered but hidden, and i did not find any way to show it via the ext API.

**Comment by splittingred** [comment]
splittingred submitted:

Merged PR for fix: https://github.com/modxcms/revolution/commit/c7c7f9f08cffc01ab3cc3631b0908e36cb0fec83
