### ISSUE TITLE
Increased control of Security items in policy templates

### ISSUE THREAD

**Issue by moniarde** [modxbot/migrate#6017]
moniarde created Redmine issue ID 6017

Request to add feature allowing more specific control to the Access Permissions tab on the Edit Resource window, and more specific control to Security menu items. "access_permissions" setting in policy templates enables tab, but also enables Security menu drop-down and access to Access Controls and Resource Groups items. Low-level access users should be allowed to add a resource to a Resource Group, and not rely on a higher authority.

**Comment by moniarde** [comment]
moniarde submitted:

Actually think this is a major issue, and needs to be upgraded thusly. Users with access_permissions disabled are barred from all Security, including being unable to assign resources to RGs. Users with access permissions enabled have complete access to Security (with exception to manage users where those related items are disabled).

**Comment by splittingred** [comment]
splittingred submitted:

Done for 2.2: https://github.com/modxcms/revolution/commit/5ea865a9ae7bcfa3c506b23b5f346d0c0771db9d
