### ISSUE TITLE
modx 2.2 s3 media source does not set mime-type correctly

### ISSUE THREAD

**Issue by AESmith** [modxbot/migrate#6024]
aesmith created Redmine issue ID 6024

When a file is uploaded to s3 over media source the mime-type based on extension but rather the generic octet-stream. This forces browser to download the file to be saved rather then display in browser.

Tested with both png and jpg file types.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/b134de45752b822ee20f8dab58be38c1593d2024 Thanks!
