### ISSUE TITLE
"Duplicate Template" - New Element name not honored

### ISSUE THREAD

**Issue by pixelchutes** [modxbot/migrate#6029]
pixelchutes created Redmine issue ID 6029

Using last night's nightly, when duplicating a Template, the name of the New Element is being ignored. The resulting name is the default "Duplicate of (original element name)" and not what was entered into the dialog box.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/3bb25e00458af32ab851194f8a3d20bdcbba7c1f
