### ISSUE TITLE
Contexts under Resource groups accepts dragged resources

### ISSUE THREAD

**Issue by Kleist** [modxbot/migrate#6039]
kleist created Redmine issue ID 6039

Security -> Resource Groups:

If I drag a resource from the left panel with resource groups to the right panel with the contexts, the resource is added to the context list. If I refresh the panels, the resource is back where it came from.

I wouldn't expect resources to be draggable to the context panel.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/6468bf2eeb85080d3dd8970256ad9d2bf945c681
