### ISSUE TITLE
Link to API Doc points to 2.1

### ISSUE THREAD

**Issue by mindeffects** [modxbot/migrate#6069]
mindeffects created Redmine issue ID 6069

Manager main menu > Support > API Documentation 
Link to the "API documentation" points to 2.1 where it should point to 2.2:
-http://api.modx.com/revolution/2.1/-  >> http://api.modx.com/revolution/2.2/

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/7d4c2100ad61f3513213a1a2cc1297c9139911dd
