### ISSUE TITLE
Package Manager +/- buttons act strange

### ISSUE THREAD

**Issue by mindeffects** [modxbot/migrate#6071]
mindeffects created Redmine issue ID 6071

After enlarging the description of a package by clicking on [+], a click in [-] colors the box somewhat "yellow/beige" but does not close it. Multiple clicks on [-] later the box is closed, but stays "yellow/beige".

**Comment by splittingred** [comment]
splittingred submitted:

I can't replicate this behavior at all, on the same environment.

Also, the yellow means that's the selected row.

**Comment by mindeffects** [comment]
mindeffects submitted:

Started my virtual machine and checked with Win7 and IE9: perfect, as you said. So the MODX installation seems to be OK. But with Mac OS and Firefox 8, Safari 5.1.1 ,Chromium 13, Opera 11.50 it's still that strange behavior. Will now reboot the system and see what happens ...

**Comment by mindeffects** [comment]
mindeffects submitted:

... nope still the same strange behaviour.
