### ISSUE TITLE
Duplicate Template Variable Values (front end)

### ISSUE THREAD

**Issue by pixelchutes** [modxbot/migrate#6083]
pixelchutes created Redmine issue ID 6083

I'm not sure exactly what happened, but I recently started getting duplicate TV values showing up in place of a few of my other TVs (but not all of them). 

Thinking I had lost all of the data, I checked the database directly and confirmed the "duplication" is only on the front end when editing a resource. _phew!_ (see attached)

I believe it started by me changing some TVs from textarea to RichText, adding a new category, and/or reorganizing the TV's categories via drag and drop. (trying to document my last steps before this issue happened) After doing so (adding to the new category), I noticed that only the DEFAULT TV input value was showing up when editing a resource -- even though the correct TV value was still present in the database.

Once I moved the TVs back to their previous category, their values started showing up again (vs. default input value) -- however, now I'm seeing this "duplicate tv value" issue... something is clearly off, I just don't know yet if it's user error or something greater.

Unfortunately, this is happening for all similar resources, and even under different browsers/sessions. So long as this issue is present, I cannot make changes to resources without overwriting the TV values with the "duplicate" values :(

**Comment by Seel-Media** [comment]
seel-media submitted:

Duplicate of Issue #6073

**Comment by pixelchutes** [comment]
pixelchutes submitted:

Thanks for flagging the dupe, Christian.

I've been using 2.2.0 nightlies _exclusively_ and none of this was happening until rc1. I have been trying to find the cause, and I believe it's related to the recent "template reloading without saving" changes.

Tracing through the code and dumping straight from @manager/controllers/default/resource/resource.class.php@ I can show that the problem is indeed happening server-side (prior to front-end rendering).

Looking at a specific TV, for example TV 5, I can clearly show the default value of TV 4 in modTemplateVar_mysql Object:

<pre> 
   [_fields] => Array
        (
            [id] => 5
            ...
            [value] => VALUE OF TV 4 IS HERE
            [processedValue] => VALUE OF TV 4 IS HERE
            [formElement] => <input id="tv5" name="tv5" type="text" class="textfield" value="VALUE OF TV 4 IS HERE" tvtype="text" />
            ...
        )
</pre>

_UPDATE:_ I can confirm that rolling back to Nov 15, 2011 nightly does temporarily resolve this major issue:

http://modx.s3.amazonaws.com/releases/nightlies/modx-2.2.0-dev-advanced-111511.zip
