### ISSUE TITLE
Deleting Content Type returns error

### ISSUE THREAD

**Issue by KristianP** [modxbot/migrate#6090]
KristianP created Redmine issue ID 6090

Deleting a Content Type returns an error when the function "isInUse" is called.

"Fatal error: Call to a member function get() on a non-object in .../core/model/modx/processors/system/contenttype/remove.class.php on line 24"

I think this was introduced with this commit:
https://github.com/modxcms/revolution/commit/a61aa2db8b02fcbf99545578561cf65e5c78cc8f

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/b3d96863d4e568b4f18865cf68fd7272906f04e2
