### ISSUE TITLE
"Error Duplicating Resource" when saving without alias

### ISSUE THREAD

**Issue by neilness** [modxbot/migrate#6096]
neilness created Redmine issue ID 6096

1) When Friendly URLs are enabled, attempting to save a _new_ resource without specifying an alias fails. (The alias field is highlighted)

2) After supplying a resource alias and trying to save again, an error box is displayed: "An error occurred while duplicating the resource."

It is not possible to save the resource without starting over.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/3d7ae560d9f56ce5ee966ca9dd5ffda5d39dfb58
