### ISSUE TITLE
package management repository down?

### ISSUE THREAD

**Issue by u007** [modxbot/migrate#6097]
u007 created Redmine issue ID 6097

Hi,

i tried several different installation of modx, all of them is giving out error on retrieving repository for package management:

An error occurred while connecting to the Provider: MODx received a blank response from the provider. Please double check your service URL and make sure the provider is a valid provider.

**Comment by opengeek** [comment]
opengeek submitted:

Are these new installs, or has package management worked on these sites in the current environment previously? Please provide as much detail as possible.

**Comment by u007** [comment]
u007 submitted:

yes, it used to work...
but ive migrated it to a new server.

ive just updated it to modx 2.1.5 and cleared cache.
i tried again, and i get the same error:

**Comment by jamestan** [comment]
jamestan submitted:

i did a upgrade again.
i was happily updating the packages, and finally i got the provider has returned a blank result when i attempt to download wayfinder.

The next thing i know, i get all sort of provider error after that.
I've changed nothing on it, as i was in the progress of updating all my packages.
when i open 
http://rest.modxcms.com/extras/
i get:
The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved.

**Comment by opengeek** [comment]
opengeek submitted:

Change your provider url to http://rest.modx.com/extras/ and try again. I'm betting the issue is due to openbase_dir restrictions on your configuration, which prevents cURL from allowing a redirect to the new provider. Setting this explicitly to the new URL should resolve your issue.

**Comment by jamestan** [comment]
jamestan submitted:

ive changed it to modx.com 
but still face the same issue.
the only difference is that the side left is working now, but clicking on a category or clicking on a package still shows
modx have returned a blank result

and the existing packages seems to show empty provider on the list

**Comment by jamestan** [comment]
jamestan submitted:

The xml returned properly,
but it seems that its malformed when it ran simplexml_load_string returning bool false..
When i click on the left side category for "Content"...
I got the error out after adding some xml debugging:
in modRestResponse::toXml()
@ini_set("display_errors", "On");
ini_set("error_reporting", E_ALL);
libxml_use_internal_errors(true);

foreach(libxml_get_errors() as $error) {
  echo "Err: " . $error->message . "<br/>\n";
 }
@

i got these errors:
@Err: error parsing attribute name
Err: attributes construct error
Couldn't find end of Start Tag pac line 139
Opening and ending tag mismatch: packages line 2 and package
Extra content at the end of the document
@

**Comment by jamestan** [comment]
jamestan submitted:

Attached the xml of the responded string

**Comment by jamestan** [comment]
jamestan submitted:

i found error on line 140:
<package>
    <id>4edfef39f2455442e500015b</id>
   <pac
1000
kage>4d556cbbb2b083396d000db1</package>
    <display_name>archivist-1.2.0-pl</display_name>

**Comment by jamestan** [comment]
jamestan submitted:

another error: line 395:
batcher module:
<d
93f
ownloads>5014</downloads>

These 2 error will solve the xml issue

**Comment by jamestan** [comment]
jamestan submitted:

clicking on tinymce package reveal an xml response with error on line 60

**Comment by splittingred** [comment]
splittingred submitted:

I've never seen anything like that. Can you provide more information about your environment? This is likely a server misconfiguration issue.

**Comment by jamestan** [comment]
jamestan submitted:

php 5.3.2
ubuntu 10.10
mysql 5.1.41
apache 2

modx 2.1.5-pl

**Comment by splittingred** [comment]
splittingred submitted:

Anything in the error.log?

**Comment by jamestan** [comment]
jamestan submitted:

ive enabled display error and error reporting set to e_all.
and i get no error or warning or notice printed when returned on from the restclient call

**Comment by jamestan** [comment]
jamestan submitted:

hi,

what should i do now?

**Comment by jamestan** [comment]
jamestan submitted:

ive another server updated to modx 2.1.5, and calling the curl seems to return "" string with no error......

**Comment by jamestan** [comment]
jamestan submitted:

ive tried to work around to use sockclient instead of the curl,
so it works on the other side, but on some category, still returned malformed xml

Extras > Blogging (works fine)
Extras > Communications (works)
Extras > Content (xml problem)
Extras > Core extension (works)
Extras > Ecommerce (xml problem)

by the way, since its using sockclient instead of curl, are you sure this is nothing todo with server side problem?

**Comment by jamestan** [comment]
jamestan submitted:

i manually updated the provider id to the id which the packages was using.
so the provider column is shown back as modx.com
but i found a problem on tinymce, its states 4.3.0 is latest version is 4.3.1pl

**Comment by splittingred** [comment]
splittingred submitted:

TinyMCE 4.3.1 is for Revo 2.2+ only.

And yes, cURL is required for Package Management. Sockets are a backup, but are not reliable due to inconsistencies in various environments.

**Comment by jamestan** [comment]
jamestan submitted:

Hi,

okay, its 2 cases here:
- one is , im not sure why my curl is not working in a box even thou its enabled, and no error return , curl_error also did not return anything. it just return empty string...
- 2nd box have curl, and its working. but on some category, its malformed xml return. (can we fix this on server?)
