### ISSUE TITLE
editor file browser window should be modal

### ISSUE THREAD

**Issue by lukemcd** [modxbot/migrate#6109]
lukemcd created Redmine issue ID 6109

Clicking on the Add Image or Insert Media button when using TinyMCE opens a new window. Clicking the browse button opens yet another window. These windows appear as separate full screen tabs on tablet browsers and browsers in full-screen mode (as promoted by OS X Lion). These browsing methods are most likely going to become more and more common. The user experience would be much better with modal windows instead of new tabs popping open.

I wasn't sure if this functionality could be integrated into the TinyMCE package but if so it would be a nice touch.

**Comment by MarkH** [comment]
markh submitted:

Shouldn't this be a feature request for the TinyMCE package instead of MODX? 

https://github.com/splittingred/Wayfinder

**Comment by lukemcd** [comment]
lukemcd submitted:

You're right Mark. I will move this to github
https://github.com/splittingred/TinyMCE/issues

My status box does not give me the option to close this issue. Does an admin need to close it?
