### ISSUE TITLE
Corrupt styling of Form Customized TVs

### ISSUE THREAD

**Issue by gerritvanaaken** [modxbot/migrate#6115]
gerritvanaaken created Redmine issue ID 6115

When I transfer a date input or a select field via "Form Customization" to a differenet tab in resource edit mask, its visual presentation is broken, see screenshot!

**Comment by Seel-Media** [comment]
seel-media submitted:

I had the same issue with modx 2.2.0-rc1, but not from the beginning. And after some days the styling was correct again. I have no idea why...

On my current 2.2.0-rc2 installation everything seems ok.

**Comment by gerritvanaaken** [comment]
gerritvanaaken submitted:

Styling problem is gone. Seems like a stubborn CSS caching error. You might close this issue.
