### ISSUE TITLE
Unable to change template

### ISSUE THREAD

**Issue by oksushi** [modxbot/migrate#6121]
oksushi created Redmine issue ID 6121

I am unable to change the template of a resource. I can edit it, then adjust the template, the page refreshes, and it is back to the template I am changing it from.

Also, I am unable to change the template on newly-created resources.

This was not an issue on sites using 2.2 pre the RC1.

This is the case one two Web sites.

**Comment by splittingred** [comment]
splittingred submitted:

I cannot reproduce this at all. Try using the latest nightly: http://modx.com/revolution/download/nightlies/

**Comment by oksushi** [comment]
oksushi submitted:

Since posting this bug, I have migrated the two Web sites to other (faster) servers, and they no longer have the issue. Both are now up to date with the latest nightly.

So perhaps it was/is an issue with the speed of the development server?

**Comment by oksushi** [comment]
oksushi submitted:

For completeness, this was due to a mismatch of timezones between MySQL and php.

Solution is here:
http://forums.modx.com/thread/73018/2-2-0-pl2-cannot-change-template-on-new-resource-console-errors#dis-post-405901
