### ISSUE TITLE
Not saving related events to plugin at creation

### ISSUE THREAD

**Issue by bertoost** [modxbot/migrate#6124]
bertoost created Redmine issue ID 6124

When I create a new plugin, link it to one or more events the relation between it looks not being saved. After adding the plugin I recheck the events I want and from then it is saved.

I've seen this before with TV's also.. maybe a general issue?

**Comment by splittingred** [comment]
splittingred submitted:

Eek, major bug. Fixed here: https://github.com/modxcms/revolution/commit/c132483d5ad2a907482d1a3f205dc8d5d5b8e88e and in latest nightly.
