### ISSUE TITLE
Plugin [event] OnInitCulture isn't launched

### ISSUE THREAD

**Issue by CyntaxDotDev** [modxbot/migrate#6125]
ReSpawN created Redmine issue ID 6125

The OnInitCulture event isn't launched. When I create an insanely simple plugin "test" with <?php exit(); on OnInitCulture it fails to exit the page. Dangerous yes, effective no. ;)

**Comment by CyntaxDotDev** [comment]
ReSpawN submitted:

Noticed the plugin event wasn't active but then still it didn't work ... The saving and checking of events is another bug.

**Comment by splittingred** [comment]
splittingred submitted:

I can't replicate this with latest release-2.2. My OnInitCulture event fires fine.

**Comment by CyntaxDotDev** [comment]
ReSpawN submitted:

If I put a simple exit into the plugin or what ever it still doesn't fire or even respond... Strange. I'll try another scenario and let you know.
