### ISSUE TITLE
Unauthorized page loads Error page

### ISSUE THREAD

**Issue by CyntaxDotDev** [modxbot/migrate#6136]
ReSpawN created Redmine issue ID 6136

I've got a authorized document in a resource group in a context named 'api'. The api is switched OnHandleRequest and works fine. When I log in on the context both backend and frontend in Firefox, I can see the restricted resource, since I placed in the resource group "Restricted", which Administrator has Resource permissions over. Frontend only Load, List and View, but it works fine non the less.

Checking the same resource in chrome (thus no cookies or sessions of any kind, besides those defaultly created by MODX) I get the error page instead of the unauthorized page. The unauthorized page is always available. Both in FF and Chrome.

I sort of traced it down to these complete of lines in the modrequest.class.php (line #120-126);

<pre>
        if (!is_object($this->modx->resource)) {
            if (!$this->modx->resource = $this->getResource($this->modx->resourceMethod, $this->modx->resourceIdentifier)) {
                $this->modx->sendErrorPage();
                return true;
            }
        }
</pre>

**Comment by CyntaxDotDev** [comment]
ReSpawN submitted:

Thinking it might have been my spotty browser... Can anybody duplicate? -_-'

Fixed it by removing the cookie resources in Chrome when pressing F12 » Resources [- Cookies] » domain.tld » [del] PHPSESSID (& others).

_Still strange that MODX loads the ERROR page instead of the UNAUTHORIZED page_. I clearly got them set up as 2 different resources, both accessable in-browser.

**Comment by opengeek** [comment]
opengeek submitted:

I can't reproduce, but I imagine this was just an old session hanging around without the new permissions. After making any changes to permissions, you should flush all permissions to make sure all users get fresh session data.

The error_page is shown if users do not have permission to "load" the protected Resource (i.e. looks as if it is not there).
