### ISSUE TITLE
Plugin Order of Execution

### ISSUE THREAD

**Issue by neilness** [modxbot/migrate#6144]
neilness created Redmine issue ID 6144

If you have multiple plugins that fire on the same event, it might be necessary to have one run before any others.

I haven't poked around in the code, but I _assume_ that plugins are called based on the order of their ID in the database.

It would be useful to add a "sort order" property for plugins that dictates order of execution -- similar to a resource's "menu index" field.

**Comment by splittingred** [comment]
splittingred submitted:

Look into the "Priority" field on the plugin event association to the plugin.
