### ISSUE TITLE
Documents not published on schedule

### ISSUE THREAD

**Issue by leoandrews** [modxbot/migrate#6150]
leoandrews created Redmine issue ID 6150

I've been defining resource publish dates - and times - in a number of resources but for some reason, after the time has passed, the resource still isn't published.

I've checked my server_offset_time value. The server which modx runs on is 8 hours behind my current location. I've set it to 8, +8, -8 and 0, clearing the site cache every time and still those articles won't publish. They do appear in the publish schedule report however.

**Comment by multimedia** [comment]
multimedia submitted:

I have this problem with MODx 2.2.0-pl2 where it sometimes doesnt auto publish a resource. 

The value Publish Date has been set to a date and time in the future, but when the time is past it is not automaticly published.
The date and time value is still in Publish Date and the checkbox at Published is not checked.

**Comment by opengeek** [comment]
opengeek submitted:

I think this may be the result of a bad query in the modCacheManager::autoPublish() method which was only selecting the MIN() (un)pub_date when that date was greater than the current time when the method was executed. This should select the MIN date where it is > 0.

**Comment by opengeek** [comment]
opengeek submitted:

This fix will be in 2.2.7-pl
