### ISSUE TITLE
Implement OnUserActivate (and add OnUserInactivate?)

### ISSUE THREAD

**Issue by bertoost** [modxbot/migrate#6159]
bertoost created Redmine issue ID 6159

This is very useful for projects where the site-owner activates the user instead of the user does itself

Looks very simple to integrate in my eyes...

**Comment by splittingred** [comment]
splittingred submitted:

Done: https://github.com/modxcms/revolution/commit/79406e9ca989ac26b6e24e65bd2cd7646b377965
