### ISSUE TITLE
"NetworkError: 400 Bad Request" on manager login after "Checking if Directory Exist: Failed!" fix. 

### ISSUE THREAD

**Issue by FickleLife** [modxbot/migrate#6165]
ficklelife created Redmine issue ID 6165

I originally had the "Checking if Directory Exists: Failed!" issue http://forums.modx.com/thread/71140/installation-problem-checking-if-directory-exists-failed which was resolved with this commit https://github.com/modxcms/revolution/commit/defd11063eff7162316d6e3e50f7f73c3469ad91. 

I can install successfully from the nightlies, however on successful log into the manager some CSS and JS doesn't load and am presented with an unstyled, nonfunctional HTML page. All the console errors from firebug: 

"NetworkError: 400 Bad Request - http://46.20.118.12/~racedata/manager/min/?f=/~racedata/manager/assets/ext3/resources/css/ext-all-notheme-min.css,/~racedata/manager/templates/default/css/xtheme-modx.css,/~racedata/manager/templates/default/css/index.css"
?f=/~r...dex.css
"NetworkError: 400 Bad Request - http://46.20.118.12/~racedata/manager/min/?f=/~racedata/manager/assets/modext/core/modx.localization.js,/~racedata/manager/assets/modext/util/utilities.js,/~racedata/manager/assets/modext/core/modx.component.js,/~racedata/manager/assets/modext/widgets/core/modx.panel.js,/~racedata/manager/assets/modext/widgets/core/modx.tabs.js,/~racedata/manager/assets/modext/widgets/core/modx.window.js,/~racedata/manager/assets/modext/widgets/core/modx.tree.js,/~racedata/manager/assets/modext/widgets/core/modx.combo.js,/~racedata/manager/assets/modext/widgets/core/modx.grid.js,/~racedata/manager/assets/modext/widgets/core/modx.console.js,/~racedata/manager/assets/modext/widgets/core/modx.portal.js"
?f=/~r...rtal.js
"NetworkError: 400 Bad Request - http://46.20.118.12/~racedata/manager/min/?f=/~racedata/manager/assets/modext/widgets/modx.treedrop.js,/~racedata/manager/assets/modext/widgets/windows.js,/~racedata/manager/assets/modext/widgets/resource/modx.tree.resource.js,/~racedata/manager/assets/modext/widgets/element/modx.tree.element.js,/~racedata/manager/assets/modext/widgets/system/modx.tree.directory.js,/~racedata/manager/assets/modext/core/modx.view.js,/~racedata/manager/assets/modext/core/modx.layout.js"
?f=/~r...yout.js
"NetworkError: 400 Bad Request - http://46.20.118.12/~racedata/manager/min/?f=/~racedata/manager/assets/modext/widgets/security/modx.grid.user.recent.resource.js,/~racedata/manager/assets/modext/widgets/modx.panel.welcome.js,/~racedata/manager/assets/modext/sections/welcome.js"
?f=/~r...come.js
"NetworkError: 400 Bad Request - http://46.20.118.12/~racedata/manager/min/?f=/~racedata/manager/assets/modext/core/modx.localization.js,/~racedata/manager/assets/modext/util/utilities.js,/~racedata/manager/assets/modext/core/modx.component.js,/~racedata/manager/assets/modext/widgets/core/modx.panel.js,/~racedata/manager/assets/modext/widgets/core/modx.tabs.js,/~racedata/manager/assets/modext/widgets/core/modx.window.js,/~racedata/manager/assets/modext/widgets/core/modx.tree.js,/~racedata/manager/assets/modext/widgets/core/modx.combo.js,/~racedata/manager/assets/modext/widgets/core/modx.grid.js,/~racedata/manager/assets/modext/widgets/core/modx.console.js,/~racedata/manager/assets/modext/widgets/core/modx.portal.js"
?f=/~r...rtal.js
"NetworkError: 400 Bad Request - http://46.20.118.12/~racedata/manager/min/?f=/~racedata/manager/assets/modext/widgets/modx.treedrop.js,/~racedata/manager/assets/modext/widgets/windows.js,/~racedata/manager/assets/modext/widgets/resource/modx.tree.resource.js,/~racedata/manager/assets/modext/widgets/element/modx.tree.element.js,/~racedata/manager/assets/modext/widgets/system/modx.tree.directory.js,/~racedata/manager/assets/modext/core/modx.view.js,/~racedata/manager/assets/modext/core/modx.layout.js"
?f=/~r...yout.js
"NetworkError: 400 Bad Request - http://46.20.118.12/~racedata/manager/min/?f=/~racedata/manager/assets/modext/widgets/security/modx.grid.user.recent.resource.js,/~racedata/manager/assets/modext/widgets/modx.panel.welcome.js,/~racedata/manager/assets/modext/sections/welcome.js"
?f=/~r...come.js
b[d.xtype || e] is not a constructor
[Break On This Error](function%28%29{var h=Ext.util,j=Ext.each,...lclick",this.onNodeDblClick,this)}});
ext-all.js (line 7)
b[d.xtype || e] is not a constructor
[Break On This Error](function%28%29{var h=Ext.util,j=Ext.each,...lclick",this.onNodeDblClick,this)}});
ext-all.js (line 7)
b[d.xtype || e] is not a constructor
[Break On This Error](function%28%29{var h=Ext.util,j=Ext.each,...lclick",this.onNodeDblClick,this)}}); 

I am installing a downloaded (not from git but the modx website) nightly traditional install from the 30th Nov to site5 reseller hosting. I can set up a temporary account if you would like to use it to replicate the error.

**Comment by splittingred** [comment]
splittingred submitted:

Do you have open_basedir in effect? mod_security? Anything else we should know?

It sounds like Google Minify is failing on your server. This is likely due to an environment issue.

**Comment by FickleLife** [comment]
ficklelife submitted:

Here's the entire phpinfo for site 5 reseller: http://dl.dropbox.com/u/419424/phpinfo/phpinfo.html 

open_basedir is set to "no value", mod_security is missing. I have also had a look at phpinfo on a localhost MAMP and open_basedir and mod_security are the same as site5, however 2.2 installs without a hitch on MAMP localhost.

I'm running several 2.1.5 sites on the above php environment and never had a problem - understandably there's big changes from 2.1.5 to 2.2. I'll send an email to site5 and see what they say.

**Comment by FickleLife** [comment]
ficklelife submitted:

I've contacted site 5, they're investigating, I'll report their findings.

**Comment by FickleLife** [comment]
ficklelife submitted:

I've managed to get it 100% working with site5s support. The issue was I was using a staging address with no domain attached - http://46.20.118.12/~racedata/ for some reason doesn't work. As soon as I assigned a domain to it and installed from that address -  www.racedatabase.com - it worked. Weird as I have done this for all versions of revo 2.1.5 and below, only 2.2 presents this issue. 

I don't understand why, site5 are going to clarify and I'll post here.

**Comment by FickleLife** [comment]
ficklelife submitted:

This is their reply:

I assume that this is not working with the temporary URL as the script burns this path to several locations, and requesting that URL for future references, not mentioning about the Rewrite rules also that will be in conflict on how this is pointing. The best solution I think would be - until you point the domain to the IP - to check and work with the domain via the Hosts file - as such, you can configure the script from the start with the domain name.
