### ISSUE TITLE
move resource to new context, cache of original context not refreshed

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#6197]
netprophet created Redmine issue ID 6197

Steps to reproduce:
- edit resource r1 in context c1
- change r1's parent to a resource in context c2
- save

c2's context cache will now include r1 in it's aliasMap
c1's context cache will _still include r1_ in it's aliasMap

**Comment by opengeek** [comment]
opengeek submitted:

Fixed for 2.2.0-rc2 — https://github.com/modxcms/revolution/commit/4e634a67dd50624624ef0ebe454014ca90c6a938
