### ISSUE TITLE
Manager TV Rank Rendering Bug

### ISSUE THREAD

**Issue by neilness** [modxbot/migrate#6209]
neilness created Redmine issue ID 6209

There's a pretty serious bug in the manager on the resource page that populates the wrong TV value into a field. 

In certain instances MODx will incorrectly replace the value stored in the database with the wrong field's default value. Upon saving the document, the correct value will be overwritten by the erroneous value.

I'm having a hard time reproducing it consistently, but I'm pretty sure it has to do with the way TVs are sorted by rank and category. I haven't tested this with form customization rules.

h2. To Reproduce
- TV1 - Empty Default - Rank 20 - Value: "This is TV1" - Category 1
-  TV2 - Default: "TV2 Default" - Rank 10 - Value: Empty Value - Category 0

h2. Will Result In
- TV1 - Value: "TV2 Default"
- TV2 - Value: "TV2 Default"

**Comment by splittingred** [comment]
splittingred submitted:

Does this still happen for you with the latest nightlies? I can't seem to replicate it.

**Comment by jacobkball** [comment]
jacobkball submitted:

I've just had this problem as well, after upgrading from a 2.1.x site to 2.2. I have a bunch of TVs related to a specific template, and when I edit an existing document, it's populating a wrong value into several other TV fields. Some of the fields don't seem to be affected, yet others do, so I'm having a hard time trying to pin down what's causing it.

If I view the document in the front end, those values are correct, so they're correct in the database, it's just in the resource manager that they're screwed up. If I save the document, it gets populated with all the wrong values.

**Comment by jacobkball** [comment]
jacobkball submitted:

I've been able to narrow it down to having a large number of TVs assigned to a Template is causing the problem. I've played around this afternoon, and after moving some TVs out of a Sub Category Folder into a higher level folder, it resolved the issue for those TVs (but not the TVs still in the Sub Category folder). When I moved a few more over, the TV values started displaying incorrectly again, but I wasn't able to fix it by moving them back! Even after clearing the Cache, logging in/out again, it still hasn't fixed it.

I'm trying to pin down exactly how many TVs it takes in a Category before it displays incorrectly.

By the way, I also disabled any Form Customisation rules in effect, to take that out of the equation.

**Comment by pixelchutes** [comment]
pixelchutes submitted:

I wonder if this could be related to #6083 / #6073 ? With these, a value from another TV was overwriting subsequent TVs and upon Save would replace the _correct_ data in the database...this sounds similar.

Do you only see the error upon Save, or are you actually seeing duplicate values for each TV on the front-end prior to saving?

FWIW, I also had quite a few TVs (all but one were in Categories), and no FC rules when I was experiencing #6083 -- however as Shaun stated, latest nightlies seem to have corrected this.

**Comment by splittingred** [comment]
splittingred submitted:

Can you replicate this error in 2.2-rc3?

**Comment by neilness** [comment]
neilness submitted:

I just upgraded to 2.2 rc-3 and I don't appear to be having the issue anymore.
