### ISSUE TITLE
Trapped upon saving after collapsing TV section with a RichText TV

### ISSUE THREAD

**Issue by pixelchutes** [modxbot/migrate#6223]
pixelchutes created Redmine issue ID 6223

When editing a Resource with a RichText TV, if you collapse the Template Variables section (small "up" arrow icon beneath the "Continue editing" button), after expanding the section, the RichText TV values can no longer be seen or edited (see attached). If you try saving after this series of events, you get stuck on the "Saving..." window.

@Error: uncaught exception: [Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIDOMHTMLDocument.implementation]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: assets/components/tinymce/jscripts/tiny_mce/tiny_mce.js?v=220dev :: <TOP_LEVEL> :: line 1"  data: no]

Error: uncaught exception: [object Object]@

I'm not sure if this is specific to TinyMCE (RTE), ExtJS rendering, or both...

**Comment by splittingred** [comment]
splittingred submitted:

This is actually a problem with TinyMCE's core code. Nothing much we can do about it.

**Comment by pixelchutes** [comment]
pixelchutes submitted:

Good to know, thanks Shaun.
