### ISSUE TITLE
Ability to sort users by active status

### ISSUE THREAD

**Issue by kenquad** [modxbot/migrate#6237]
kenquad created Redmine issue ID 6237

Since you can sort users in the manager by other fields, I don't see why you shouldn't be able to sort them by whether or not they are active.  This is useful is quickly determining how many users have not activated their accounts.

**Comment by splittingred** [comment]
splittingred submitted:

Done: https://github.com/modxcms/revolution/commit/deac03521744d43c4ae9368944bd3711a3556fb2
