### ISSUE TITLE
Problems when opening two "Quick update resource" windows in 2.2

### ISSUE THREAD

**Issue by yurkobb** [modxbot/migrate#6238]
yurkobb created Redmine issue ID 6238

If I open a second "Quick update resource" window (on another resource), the "Published" and "Hide from menus" checkboxes jump to the previously opened window so it has double of these checkboxes, and the second opened editing window has none. Also a screenshot attached.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/4ff425dfa61bd18b582d075a6ed0f981ae239334

**Comment by yurkobb** [comment]
yurkobb submitted:

Thank you very much!
