### ISSUE TITLE
Modal Window opens out of reach

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#6246]
onepack created Redmine issue ID 6246

I have had multiple cases that I opened a modal window in MODx but was unable to move it or edit the upper part of the window because it was moved out of reach by the system and I was unable to get it back in position. A page refresh didn't help.
Please change the behaviour so that it always opens in the center of the active browser screen.

See screenshot regarding the modal window being out of reach

**Comment by opengeek** [comment]
opengeek submitted:

See https://github.com/modxcms/revolution/pull/733 for a resolution to this issue
