### ISSUE TITLE
xPDO database fieldname cannot contain the word 'class'

### ISSUE THREAD

**Issue by cyclissmo** [modxbot/migrate#6268]
cyclissmo created Redmine issue ID 6268

xPDO 2.1.3 bonks with the error 'No class specified for loadClass' if I attempt to name a database field with the word 'class' in it:

This example table structure triggers the error with getObject, getObjectGraph, etc.

 `picker_key` varchar(10) NOT NULL ,
 `class_key` varchar(20) NOT NULL , <<< offender
 `name` varchar(255) NOT NULL 

Forgive me if this is a reserved table name as I was not able to find it in docs...

**Comment by opengeek** [comment]
opengeek submitted:

The field name "class_key" is reserved by xPDO for objects using single-table inheritance. As such, it is essentially a reserved column name when using xPDO. I will however enter a ticket in the xPDO project to limit this reserved behavior to objects defined with inherit="single" in future releases of xPDO. Thanks for taking the time to file the issue.
