### ISSUE TITLE
Package manager can only install 1 package at a time

### ISSUE THREAD

**Issue by b03tz** [modxbot/migrate#6269]
b03tz created Redmine issue ID 6269

You can only install 1 package in the package manager, after that when you try to install a second package the browser throws a javascript error.

Steps to reproduce:
- Download 2 packages (in my example used wayFinder and Gallery)
- Install wayFinder, close the console
- Install gallery, when you click install, then the continue buttons gives you:

"b.dom is undefined" in ext-all.js

I'm using firefox and the latest nightly (dec, 8)

**Comment by splittingred** [comment]
splittingred submitted:

Can you check with latest nightly and see if this is fixed? It should have been fixed in a recent update.

**Comment by opengeek** [comment]
opengeek submitted:

Check the nightly tomorrow; it should be resolved after today's commits.
