### ISSUE TITLE
javascript headers cause lang.js.php to fail in some configurations

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#6300]
netprophet created Redmine issue ID 6300

In at least one nginx server configuration, lang.js.php output fails to be output completely to the browser, resulting in blank manager pages. Debugging shows that the complete output is being formulated properly and sent to output.
Removing the javascript mime type header from the script stops this from occurring.

**Comment by splittingred** [comment]
splittingred submitted:

This only seems to happen on one server running php-fpm, nginx and fastcgi. Most likely a server misconfiguration issue.
