### ISSUE TITLE
Package Manager "update" hangs on display of docs

### ISSUE THREAD

**Issue by ghost** [modxbot/migrate#6301]
sottwell created Redmine issue ID 6301

The package manager's Update hangs on the documentation display; the Continue button does nothing. On closing the window, the the updated package has been uploaded and the extra is uninstalled. It can then be installed.

**Comment by splittingred** [comment]
splittingred submitted:

1) Is this on the first installation of an extra (IOW, you hadn't already installed something without reloading the page)
2) What Extra was this?
3) Any errors in core/cache/logs/error.log?

**Comment by ghost** [comment]
sottwell submitted:

This is when updating an existing installed package. Any package. Today I updated archivist, articles, quip, getpage and getresources. 

There are a bunch of errors "MODX could not download the file. You must enable allow_url_fopen, cURL or fsockopen to use remote transport packaging." which make no sense at all as the packages were initially downloaded and installed just fine, and when the update hangs on the documentation page either closing the page or refreshing the Manager page shows the item with a green "install" button, and it installs just fine. So the downloading is accomplished; I don't know why it keeps logging that error. Maybe some kind of timeout due to my flaky Internet connection? Original installations are snappy enough with no problems.

I'll attach my error log for the last two days of work I've been doing in Revo, you will probably be able to make more sense of them than I can.

**Comment by splittingred** [comment]
splittingred submitted:

Thanks Susan. Fixed: https://github.com/modxcms/revolution/commit/189788ccc9b9358ed5d31dbed2761d6fefd7b131
