### ISSUE TITLE
Changing resource's template does not trigger save button

### ISSUE THREAD

**Issue by ghost** [modxbot/migrate#6302]
sottwell created Redmine issue ID 6302

When changing a resource's template, the save button is briefly enabled after the initial refresh, then when the page is finished loading the save button becomes disabled. If you're quick and click the save button in the second before the button is disabled the resource can be saved with its new template setting, other wise you can't save the new template setting.

**Comment by ghost** [comment]
sottwell submitted:

I suspect this is caused by the initial page refresh triggering the "dirty" check, and since nothing was changed since the page was re-loaded it disables the Save button.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/acd76ea9376c5d4f1a23c3ffb13c7b9ffae1ab31

**Comment by ghost** [comment]
sottwell submitted:

Oops... now, when the page finishes its refresh after confirming the template change, it's reverted to the original template. Can't change templates at all.

**Comment by ghost** [comment]
sottwell submitted:

You know, I've been thinking for a long time, why wouldn't it work to simply save the resource at that point, reloading the resource in edit mode?

**Comment by splittingred** [comment]
splittingred submitted:

Susan, the template should change - it does on mine - I'm not sure why it's not on yours. Can you provide more details? Also, is this the latest nightly or rc1?

The reasons we don't want to save it on a template change are these:
1) Form Customization - your rules targeted at "create" would no longer be in effect
2) Behavioral - If I'm creating a resource, I dont want a Template change to actually create the resource. If I decide I dont want to create it, then if i've already changed the template, well, too bad. I'd have to take the extra step of deleting it.
3) Events - basic OnCreate events would not fire as expected, or properly

**Comment by ghost** [comment]
sottwell submitted:

I figured you must have had good reasons for doing it this way all these years.

When I change the template, and click Yes in the warning dialog, the page greys out while the save progress bar shows. When that clears and the screen clears, it shows the change of template in the select as the browser is waiting for the page to refresh (at this point I can click the save button and it'll save OK, but sends me back to the dashboard welcome page instead of leaving the resource open). If I wait until the page refresh is finished, the final new page is back to showing the original template in the select.

**Comment by ghost** [comment]
sottwell submitted:

this is the nightly build from a couple of days ago, patched.
