### ISSUE TITLE
$modx->addExtensionPackage() not setting correct path build

### ISSUE THREAD

**Issue by jgulledge19** [modxbot/migrate#6304]
jgulledge19 created Redmine issue ID 6304

When this file runs: https://github.com/splittingred/Articles/blob/develop/_build/resolvers/extpack.resolver.php:

The $modx->addExtensionPackage() in file core\model\modx\modx.class.php on line 2012 handled the path wrong:

it put: [{"articles":{"path":"E:inetpubwwwrootmodx-2.2.0-rc1/core/components/articles/model/"}}]

rather then:

[{"articles":{"path":"E:/inetpub/wwwroot/modx-2.2.0-rc1/core/components/articles/model/"}}]

in the system_settings table for key= extension_packages

See related bug: http://bugs.modx.com/issues/6263.  Once I changed the path and cleared cached it works good.

**Comment by splittingred** [comment]
splittingred submitted:

I don't get it: I ran this:

<pre>$modx->addExtensionPackage('articles2','E:/inetpub/wwwroot/modx-2.2.0-rc1/core/components/articles/model/');</pre>

Just to test your case, and it added it fine, with all the slashes in there fine. Are you sure your MODX_CORE_PATH is set correctly? Check your config.inc.php file.

Do you have open_basedir, or magic_gpc_quotes or something else on?

**Comment by jgulledge19** [comment]
jgulledge19 submitted:

Yes see: http://bugs.modx.com/issues/6263#note-3.

I uninstalled and reinstalled Articles and then I had to manually install Quip and it work correctly this time.  I did not reinstall Articles the first time I changed the MODX workspace path.  I will do more testing later this week, I don't have any special/old PHP settings.

Thanks for the review.
