### ISSUE TITLE
Resource "Close" button triggers warning

### ISSUE THREAD

**Issue by ghost** [modxbot/migrate#6306]
sottwell created Redmine issue ID 6306

An annoying "You have changes pending; are you sure you want to cancel?" message pops up every time you "Close" a resource editing window. This happens if you've saved, and the Save button is greyed out, or if you only looked at the item and didn't make any changes at all. Just moving to another resource or element doesn't cause this, only using the "Close" button.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/c77eb3e81837a645ebe5d2aa048e6405fd98e0ef
