### ISSUE TITLE
TV of radio option or listbox input type doesn't parse its default value

### ISSUE THREAD

**Issue by WebraumZ** [modxbot/migrate#6308]
WebraumZ created Redmine issue ID 6308

I've installed latest build of Revo 2.2 rc2 from Github and I really don't know what the problem is. I created some template variable of listbox (single-select) type, entered it's possible input values (Yes==1||No==0) and set it's default value to 1 (Yes). Then I assigned it to one of my site templates and saved it. 
Problem is that when i trying to output the default value of TV on the page with this template nothing is happening. Situation changes only when I choose one of possible values by my own hands during the process of editing and saving of this page in manager. I've tried to change TV type on radio option but got the same result.
Is this some bug or strange feature?

**Comment by splittingred** [comment]
splittingred submitted:

I can't replicate this - did the exact steps you described, and the TV outputted fine. You'll have to provide much more information about your Template and how you're rendering the TV to further this ticket.
