### ISSUE TITLE
Save button not disabled after template change.

### ISSUE THREAD

**Issue by ghost** [modxbot/migrate#6340]
sottwell created Redmine issue ID 6340

After saving a change in template the Save button doesn't disable. Once a template change has been saved, any further changes to the resource during that editing session won't disable the Save button.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/1f40d9bb4d4d1cff46a98a7617eda32bdd5632fa
