### ISSUE TITLE
Home look and feel

### ISSUE THREAD

**Issue by maxpiepenbrink** [modxbot/migrate#6363]
mido created Redmine issue ID 6363

The new modx design looks great, but not the preconfigured widgets. The first two ( security and news ) has text with really big titles. 
The other two ( online people and activity ) looks a little bit strange. A table inside a "box". I supose we can't remove the container, but it would look nicer if you only show the table.
In Chrome, scrollbars are hidden unless you scroll over elements, so widgets wich have scroll looks a little bit strange. In Firefox it's OK.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed, mostly: https://github.com/modxcms/revolution/commit/7f13c7e954cb89870fbdba159a80435ffd87f502
