### ISSUE TITLE
missing lexicon entry: package_version_remove

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#6364]
netprophet created Redmine issue ID 6364

On a package's View Details page, on the Uploaded Versions tab, the context menu shows "package_version_remove". This needs to be added to the lexicon.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/c5948ce72fbc265f484e6c83dd18386308e3a5e0
