### ISSUE TITLE
add a duplicate_resource permission

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#6372]
bobray created Redmine issue ID 6372

Didn't this used to exist?  There doesn't appear to be any way to prevent users from duplicating documents without putting the docs in a resource group.

This should be an option in a context access policy, IMO.

**Comment by splittingred** [comment]
splittingred submitted:

Done: https://github.com/modxcms/revolution/commit/fd82a52134a628a430f8e1ba4895870051cb683a
