### ISSUE TITLE
500 (Internal Server Error) with minify

### ISSUE THREAD

**Issue by wanze** [modxbot/migrate#6381]
Wanze created Redmine issue ID 6381

Just installed a fresh version of modx 2.2 from the nightly build (16.12.) on my shared hosting.
After log into the manger, i can't load nothing. There are several errors with the minify.
Firefox is able to load the css, in chrome i get a screen like shown in the screenshot. 
I have several other installations of modx (version 2.1.5) running on the same hosting without problems.

what else informations do you need? will try to disable minify manually in the database...

**Comment by wanze** [comment]
Wanze submitted:

I tried to set the "manager_js_document_root" manually in the DB.
What to set here exactly? The document_root of the website or the whole path to the /manger/min folder?

Also i tried to set "manager_js_cache_max_files" to a lower value -> 5. But there's no such key existing in
my database? 
In the min/index.php on line 55 i made a change like this:
@$min_serveOptions['minApp']['maxFiles'] = (int)$modx->getOption('manager_js_cache_max_files',null,5); //instead of 50@

The problem still exists after all this, and after deleting all folders in the core/cache directory.
max_execution_time is set to 300.

**Comment by opengeek** [comment]
opengeek submitted:

Stefan:

Do you have any server error logs that might be capturing the errors causing the 500 error? I cannot reproduce this in any environment I have, with latest in git (release-2.2 branch) or from the 2.2.0-rc2 downloads that were posted this morning.

**Comment by opengeek** [comment]
opengeek submitted:

Also, do not set/change the manager_js_document_root — leave that blank.

**Comment by wanze** [comment]
Wanze submitted:

I set the field to blank again, thanks Jason. 
By turning off the js- and css compression I can work with modx without problems.
There are some error logs, maybe a problem with FastCGI (whatever this is)?:

@[Fri Dec 16 15:17:25 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2062747", referer: http://isabellefreymond.ch/manager/?a=70
[Fri Dec 16 15:17:25 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2062748", referer: http://isabellefreymond.ch/manager/?a=70
[Fri Dec 16 15:17:30 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2062645", referer: http://isabellefreymond.ch/manager/?a=70
[Fri Dec 16 15:17:49 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2062756", referer: http://isabellefreymond.ch/manager/?a=70
[Fri Dec 16 15:17:50 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2062771", referer: http://isabellefreymond.ch/manager/?a=70
[Fri Dec 16 15:17:56 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2062770", referer: http://isabellefreymond.ch/manager/?a=70
[Fri Dec 16 15:18:11 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2062791", referer: http://isabellefreymond.ch/manager/?a=30&id=1
[Fri Dec 16 15:22:00 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2063001", referer: http://isabellefreymond.ch/manager/?a=53
[Fri Dec 16 15:22:00 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2063003", referer: http://isabellefreymond.ch/manager/?a=53
[Fri Dec 16 15:22:05 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2063000", referer: http://isabellefreymond.ch/manager/?a=53
[Fri Dec 16 15:23:35 2011] [error] [client 84.74.151.111] File does not exist: /home/maloulou/www/isabellefreymond.ch/favicon.ico
[Fri Dec 16 15:23:45 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2063072", referer: http://isabellefreymond.ch/manager/
[Fri Dec 16 15:23:51 2011] [error] [client 84.74.151.111] File does not exist: /home/maloulou/www/isabellefreymond.ch/favicon.ico
[Fri Dec 16 15:24:38 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2063007", referer: http://isabellefreymond.ch/manager/
[Fri Dec 16 15:24:39 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2063104", referer: http://isabellefreymond.ch/manager/
[Fri Dec 16 15:24:44 2011] [error] [client 84.74.151.111] File does not exist: /home/maloulou/www/isabellefreymond.ch/favicon.ico
[Fri Dec 16 15:47:50 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2063965", referer: http://isabellefreymond.ch/manager/
[Fri Dec 16 15:47:57 2011] [error] [client 84.74.151.111] File does not exist: /home/maloulou/www/isabellefreymond.ch/favicon.ico
[Fri Dec 16 15:50:50 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2064105", referer: http://isabellefreymond.ch/manager/
[Fri Dec 16 15:50:50 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2064112", referer: http://isabellefreymond.ch/manager/
[Fri Dec 16 15:50:55 2011] [error] [client 84.74.151.111] File does not exist: /home/maloulou/www/isabellefreymond.ch/favicon.ico
[Fri Dec 16 15:51:59 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2064153", referer: http://isabellefreymond.ch/manager/
[Fri Dec 16 15:52:06 2011] [error] [client 84.74.151.111] File does not exist: /home/maloulou/www/isabellefreymond.ch/favicon.ico
[Fri Dec 16 15:57:53 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2064376", referer: http://isabellefreymond.ch/manager/
[Fri Dec 16 15:57:53 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2064375", referer: http://isabellefreymond.ch/manager/
[Fri Dec 16 15:57:58 2011] [error] [client 84.74.151.111] File does not exist: /home/maloulou/www/isabellefreymond.ch/favicon.ico
[Fri Dec 16 16:13:45 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2065012", referer: http://isabellefreymond.ch/manager/
[Fri Dec 16 16:13:46 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2065013", referer: http://isabellefreymond.ch/manager/
[Fri Dec 16 16:13:52 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2065011", referer: http://isabellefreymond.ch/manager/
[Fri Dec 16 16:14:12 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2065017", referer: http://isabellefreymond.ch/manager/?a=53
[Fri Dec 16 16:14:13 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2065033", referer: http://isabellefreymond.ch/manager/?a=53
[Fri Dec 16 16:14:20 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2065031", referer: http://isabellefreymond.ch/manager/?a=53
[Fri Dec 16 16:14:45 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2065035", referer: http://isabellefreymond.ch/manager/
[Fri Dec 16 16:14:45 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2065053", referer: http://isabellefreymond.ch/manager/
[Fri Dec 16 16:14:51 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2065038", referer: http://isabellefreymond.ch/manager/
[Fri Dec 16 17:23:11 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2066642", referer: http://isabellefreymond.ch/manager/index.php?a=30&id=2
[Fri Dec 16 17:29:24 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2067189", referer: http://isabellefreymond.ch/manager/index.php?a=30&id=2
[Fri Dec 16 17:33:52 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2067190", referer: http://isabellefreymond.ch/manager/index.php?a=30&id=2
[Fri Dec 16 17:34:03 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2067963", referer: http://isabellefreymond.ch/manager/?a=30&id=3
[Fri Dec 16 17:34:04 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2067279", referer: http://isabellefreymond.ch/manager/?a=30&id=3
[Fri Dec 16 17:58:02 2011] [error] [client 84.74.151.111] FastCGI: incomplete headers (0 bytes) received from server "/var/run/hcgi/2068738", referer: http://isabellefreymond.ch/manager/index.php?a=30&@

**Comment by wanze** [comment]
Wanze submitted:

Changing PHP to Version 5.2.17 resolved the problem for me!
But i could not find out why the errors happened, the problem seems to be related to the hosting...
