### ISSUE TITLE
2.2 Translations

### ISSUE THREAD

**Issue by splittingred** [modxbot/migrate#6387]
splittingred created Redmine issue ID 6387

Translations are needed for Revolution 2.2.0. Please attach all translations here, in a single zip file, named "language-2.2.0-pl.zip", where language is the IANA code of your translation.

Alternatively (and preferred!), you can send a pull request on GitHub to the revolution repository to send the files. The core team will review them and then commit them to Git. Please sign a CLA via http://modx.com/cla/ Translations cannot be accepted without a CLA.

We will accept translations until 2PM Central Time (GMT -0600), Jan 2nd, 2011.

**Comment by Pont** [comment]
pont submitted:

Updated swedish language files

**Comment by splittingred** [comment]
splittingred submitted:

Updated, thanks Pontus!

**Comment by Pont** [comment]
pont submitted:

Latest swedish updates in system_events.inc.php

**Comment by pandro** [comment]
pandro submitted:

Italian language files, 
thanks!

**Comment by splittingred** [comment]
splittingred submitted:

Updated: https://github.com/modxcms/revolution/commit/53ceb18b8953408851c5c5946befb5f50ae3ab39

**Comment by Pont** [comment]
pont submitted:

Latest update to element.inc.php in swedish

**Comment by splittingred** [comment]
splittingred submitted:

Updated: https://github.com/modxcms/revolution/commit/3af8fc8e70945191222ab877f135f170ae3e91cc
