### ISSUE TITLE
Static Resources Erased switching Media Source 

### ISSUE THREAD

**Issue by terkkila** [modxbot/migrate#6388]
terkkila created Redmine issue ID 6388

I have a chunk with a static resource site_footer.tpl

It is listed as "assets/templates/main/site_footer.tpl" in the static resource field.
The Media Source for Static File says "none"
The Chunk code is empty.

I then select "File System" from the list and save.
I then refresh my page using this chunk.  Then content is now not displaying.  Why? Because the file is now empty.
This error is fully reproducible.  The file is not deleted, just empty.

Investigating further, it appears that saving the chunk with "File system" selected will replace the contents of the file with the contents of the "chunk code". In this case the field was empty.

Reloading the page (with the tpl having content) will populate the chunk code with the contents of the file.

---

The behavior I would expect is the content on the file system to be independent of the chunk code.
The current functionality is acceptable if it is more clearing explained that the chunk code is the actual file contents and that editing it will also edit the contents of the static resource.

**Comment by terkkila** [comment]
terkkila submitted:

Note: I marked this as major because of the possibility of losing large amount of work when this occurs.

In my instance I was editing the static resource in a text editor. I was using the chunk page to refresh the cache by saving the chunk.

**Comment by splittingred** [comment]
splittingred submitted:

Upgrade to rc2; this was fixed there.
