### ISSUE TITLE
Uncomplete system setting values after upgrade to 2.2 RC2

### ISSUE THREAD

**Issue by gadgetto** [modxbot/migrate#6413]
gadgetto created Redmine issue ID 6413

I have upgraded an existing MODx installation form 2.0.6 to 2.2RC2 and now there are some missing values (missing Name, missing Description) in some system settings:

manager_login_url_alternate
cache_json
cache_json_expires
friendly_alias_urls
custom_resource_classes
date_timezone

Tried to edit settings and fill in missing values from a plain MODx 2.2 RC2 installation but settings editor doesn't save changes. Which values can be deleted? Is there an overview of all actual system settings?

**Comment by onepack** [comment]
onepack submitted:

I can confirm this.

**Comment by opengeek** [comment]
opengeek submitted:

At the moment I can't reproduce this. Some of those are old settings that no longer are used, like cache_json and cache_json_expires. Others are new records that were added for 2.2.0 and should have new setting keys. Is it possible your upgrade failed or did not complete for some other reason?

Also, FYI, you might try the latest nightly as there was a significant issue with timezone handling in 2.2.0-rc2.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed for date_timezone here: https://github.com/modxcms/revolution/commit/c0032bcc424dba5a18e39997224baa9e340bcd9a

The others are fine on my installs; "cache_json", "cache_json_expires" and "custom_resource_classes" are deprecated and can be removed.

**Comment by gadgetto** [comment]
gadgetto submitted:

The manager_login_url_alternate setting has missing values (missing Name, missing Description) in any of my current 3 MODx setups.
Looking at the lexicon files (core/lexicon/..) shows that the $_lang pairs are missing from nearly all languages except "en".

All my sites have the "de" language enabled.

All of my setups finished without errors!
