### ISSUE TITLE
New Document gets class_key of 'modResource' instead of 'modDocument'

### ISSUE THREAD

**Issue by MokoJumbie** [modxbot/migrate#6417]
MokoJumbie created Redmine issue ID 6417

Selecting 'Create Document Here' from Resource tree erroneously results in a resource editing panel with 'modResource' specified as the Resource Type.

The class_key is being sent correctly by the HTTP request, but is being handled incorrectly by line 49 of /manager/controllers/default/resource/resource.class.php as far as I can tell:

<pre>
 $resourceClass = in_array($_REQUEST['class_key'],array('modDocument','modResource')) ? 'modResource' : $_REQUEST['class_key'];
</pre>

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/8431de3cfbb9c8eb28ae493bb5e420e225802dbb
