### ISSUE TITLE
TemplateVar display field blank prevents rendering

### ISSUE THREAD

**Issue by opengeek** [modxbot/migrate#6421]
opengeek created Redmine issue ID 6421

After upgrading a 2.1.3-pl site to 2.2.0-rc2, many of my Template Variables would not render on the front-end. It turns out the field "display" was blank and preventing any renderer from being used.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/07ccc035100a909a40605b77cd24b516f36553bb
