### ISSUE TITLE
Assigning media source to group

### ISSUE THREAD

**Issue by ghost** [modxbot/migrate#6470]
sottwell created Redmine issue ID 6470

Any attempt to assign any media source to any group causes the media source to disappear altogether. It can no longer be seen in the Files tab, nor in the Tools->Media Sources management list of media sources. Its assignment in the Media Sources tab for the group is still visible, and deleting that assignment restores the media source.

This happens whether the group is assigned while creating/updating the media source, or when assigning the media source to the group in the group's Media Sources tab.

**Comment by wanze** [comment]
Wanze submitted:

See also:
http://forums.modx.com/thread/72723/securing-mediasource-to-admin-only-access-denied-afterwards#dis-post-404469

**Comment by splittingred** [comment]
splittingred submitted:

I'm sorry, I just did the exact steps in the docs and was easily able to get it to show for only users in the Administrator group. Can you outline your steps exactly? Also, are you Flushing Sessions and re-logging in after protecting it?

**Comment by wanze** [comment]
Wanze submitted:

Just tried on a fresh install revo 2.2 rc3 and still had the problems. Here my steps, right after the install:
1) Login as default admin
2) Go to Tools -> Media Sources
3) Update Filesystem Media source
4) Access Permissions Tab -> Add User Group -> like in the Docs: Administrator - Member 999 - Media Source Admin
5) Save by pressing first the Save button of the Popup, then the button on the top right
6) Security -> Flush permissions

Now my admin User has no more access to the Filesystem Media source. Not in the File-Tree, nor in TV's assigned this source and
also not over Tools -> Media Sources.
Solved this by manually emptying the table "modx_access_media_source"

**Comment by splittingred** [comment]
splittingred submitted:

Don't "Flush Permissions" - hit "Flush Sessions", or logout completely then log back in. Flush permissions wont refresh your access.

**Comment by ghost** [comment]
sottwell submitted:

Downloaded and installed latest 1229 nightly. Followed exactly the steps for creating a new Media Source and then securing it to the Administrator group. Flushed permissions, flushed sessions. It promptly disappeared  from  the Files tab and Tools -> Media Sources as well as the TV media sources options. The media source access tab for the Administrator group does show it. However, if I open "Update Media Source Access" then attempt to save it I get an "access denied" error. I can delete the assignment, and then it shows again everywhere.

**Comment by wanze** [comment]
Wanze submitted:

Shaun McCormick wrote:

> Don't "Flush Permissions" - hit "Flush Sessions", or logout completely then log back in. Flush permissions wont refresh your access.

Still no access after Flush Sessions, Clear modx-Cache, Clear browser-cache, tried also a different browser..

**Comment by ghost** [comment]
sottwell submitted:

FYI, I installed fresh on a remote Bluehost (linux) server and it's doing the same thing, so it's not something weird going on with MAMP.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: 
https://github.com/modxcms/revolution/commit/26aded7ff6992a4afedf0477e69181dae58e34e8
https://github.com/modxcms/revolution/commit/b300533206a9560562cdc2bb455bed22fff146e0

To fix in your environments, simply add "sources.modAccessMediaSource" to the comma-separated list of the 'principal_targets' System Setting.

**Comment by ghost** [comment]
sottwell submitted:

Just downloaded and installed 2.2pl and this setting has not been implemented.

**Comment by splittingred** [comment]
splittingred submitted:

Bah. Fixed here: https://github.com/modxcms/revolution/commit/bea485f926895a27635b173dd22544a39012d4d9

Occurs only in new installs; upgrades will work fine.

To fix in new installs, just re-run setup or add "sources.modAccessMediaSource" to the principal_targets setting.
