### ISSUE TITLE
getLoginUserID empty with 2.2 RC2

### ISSUE THREAD

**Issue by studiorepublic** [modxbot/migrate#6476]
chris@studiorepublic.com created Redmine issue ID 6476

When logged in, getLoginUserID returns nothing, whereas getLoginUserName works fine

**Comment by opengeek** [comment]
opengeek submitted:

I cannot reproduce this issue. More information required.

**Comment by studiorepublic** [comment]
chris@studiorepublic.com submitted:

Well it looks like the Christmas break and a server reboot has sorted it! Thanks for taking a look Jason.
