### ISSUE TITLE
Quick Edit Modal Window too big/bad positioned

### ISSUE THREAD

**Issue by XoD** [modxbot/migrate#6496]
xod created Redmine issue ID 6496

This was already marked as fixed here:

http://bugs.modx.com/issues/4539

double opened here:

http://bugs.modx.com/issues/4563

but as of Revo v2.2.0rc3 it's still an issue which bothers me day in day out^^.

I love the new 2.2.0 UI, really nice guys! 

But I think this has to be fixed soon. I'm on a macbook air 11" (1366x768px) but I also have this issue on a 4:3 screen with 1280x1024 px, so it affects a lot of people I think...or do the majority of people not use quick update/edit/create? can't imagine that =)...

so here it is again, this time with a screencast to show what I mean.

http://www.exside.ch/client.upload/modx22ui.mov

it seems that this is only a css btw. javascript (which sets the css??) problem, I tracked it with firebug (see attached screenshot) and narrowed it down to two properties...

hope this can be fixed for the final release of 2.2 =)!

The other, unreleated thing with the categories in the new package management module (see end of screencast) I'm not sure if this is a bug, or if I'm just too stupid to see it or if it will come in the final release? So I'm not sure to open another ticket for this?

For the ones who don't like to download and watch the screencast, this was the question:
- where in the new package management are the extra categories?
- is there a way to view all available extras?

**Comment by XoD** [comment]
xod submitted:

the screencast on youtube (not listed...) http://youtu.be/rlt0vq4bCEg

so it is still reachable when I delete the file on my server...I'll do that now...so the link above won't work anymore...I would have corrected it, but I can't edit my initial bug-text (or am I just not seeing the right button?)

**Comment by MarkH** [comment]
markh submitted:

https://github.com/modxcms/revolution/pull/286

That second bug with the package management looks like the repository was offline when you took the screencast. If it still doesn't work for you, open another issue for it to debug.
