### ISSUE TITLE
onMediaSourceGetProperties System-Event

### ISSUE THREAD

**Issue by Bruno17** [modxbot/migrate#6507]
Bruno17 created Redmine issue ID 6507

Still trying to have mediasources a bit more flexible, I found it may be enough to have a new systemevent 'onMediaSourceGetProperties'.

Used this code in modmediasource.class.php function getProperties: 

<pre>
        if ($results = $this->xpdo->invokeEvent('OnMediaSourceGetProperties',array('properties' =>$this->xpdo->toJson($properties)))){
            foreach ($results as $result){
                $properties = array_merge($properties,$this->xpdo->fromJson($result));
            }
        }        
        return $this->prepareProperties($properties);
</pre>

Then we can create plugins to manipulate a mediasource-path this way (very simple example):

<pre>
switch ($modx->event->name) {
    case 'OnMediaSourceGetProperties':
        $params=$modx->fromJson($scriptProperties['properties']);
        $params['basePath']['value']=$params['basePath']['value'].'test/';
        $params['baseUrl']['value']=$params['baseUrl']['value'].'test/';;
        $modx->event->output($modx->toJson($params));
        break; 
}
</pre>

for the manager we can try to use the $_SERVER['HTTP_REFERER'] in our plugin to get a resource-id.
for the frontend we can set placeholders.
This way we could have the same result by using plugins as in this pull: https://github.com/modxcms/revolution/pull/238 without having to add more than this systemevent.

**Comment by splittingred** [comment]
splittingred submitted:

Done: https://github.com/modxcms/revolution/commit/2f13908836ec173b336468defc2001439477c593

Good compromise. :)
