### ISSUE TITLE
Installing update or reinstalling a package doesn't remember page setting in manager. 

### ISSUE THREAD

**Issue by apcherry** [modxbot/migrate#6522]
apcherry created Redmine issue ID 6522

In the package manager if I go to a second page of packages and select a package to update or re-install then once it's gone through the process the package manager returns to the first page.

From a usability point of view it would be nice if it could remember I was on page 2 and return me to that page. If there is only one package to update it's not noticeable but on upgrading to 2.2.-rc3 there was half a dozen packages to upgrade. So it was getting a bit tedious having to switch  back to page 2 after every upgrade.

**Comment by opengeek** [comment]
opengeek submitted:

See https://github.com/modxcms/revolution/commit/2dabd17302b7e3d077c00d67b3e9053c9cf79f56 for resolution.
