### ISSUE TITLE
template ID appears instead of name in "uses template" field when editing a resource

### ISSUE THREAD

**Issue by FickleLife** [modxbot/migrate#6551]
ficklelife created Redmine issue ID 6551

Have had this on 2.2-rc2 and also 2.2-rc3 nightly 3 jan 2012 - screenshot is attached.

The field has "3" in it instead of the template name and it always goes to "empty" when you click on the field. Weird thing is this doesn't happen on every template - I can click on some resources with certain templates and the name of the template shows (2nd screenshot).

It consistently displays or doesn't display the name for a certain template, so it doesn't seem random. 

environment info: http://dl.dropbox.com/u/419424/phpinfo/phpinfo.html

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/fd53ba3c549db4a2360eb19a55f59eba1d5928d6
