### ISSUE TITLE
Save unavailable after changing template

### ISSUE THREAD

**Issue by frogabog** [modxbot/migrate#6581]
frogabog created Redmine issue ID 6581

After changing the template in a resource, the save button is not highlighted.  If a character change is made in a field however, save becomes highlighted and works properly.

**Comment by frogabog** [comment]
frogabog submitted:

I just updated to 2.2.0-pl2.  The save is still not highlighted/available after changing the template.  Rats!

**Comment by BearsFan** [comment]
acaffiero@gmail.com submitted:

similarly, when I try to change templates, the page reloads and then jumps back to the previously selected template.

**Comment by frogabog** [comment]
frogabog submitted:

The template change issue is separate from this "save after changing template" issue. 

This particular issue appeared after I applied the date.timezone solution for the same template change issue you're seeing.    

The simplified solution is below:

> Make sure your date.timezone setting in PHP matches that used by your MySQL Server configuration. If it does not, you are going to have trouble. If you cannot change your php.ini, you can set the date_timezone setting inside MODX to the proper PHP timezone string that matches the timezone being used by MySQL. See http://php.net/manual/en/timezones.php for valid timezones for PHP.

Further solution information can be seen in this current thread at the forum.

http://forums.modx.com/thread/?thread=73018&page=1

**Comment by BobRay** [comment]
bobray submitted:

I'm seeing this in 2.2.0-rc3 (page reloads with original template set) on localhost/XAMPP.

PHP, MySQL, and Windows all have the same timezone setting (America/New_York).

Changing the template with Quick Update does work.

Also, with a new resource, after trying to change the template and seeing the reload (with the original template), the page will not save (infinite progress bar).

**Comment by BobRay** [comment]
bobray submitted:

Never mind my comment. I didn't know about the timezone System Setting. Setting that allows changing templates on the Create/Edit Resource panel in 2.2.0-rc3.

**Comment by MokoJumbie** [comment]
MokoJumbie submitted:

I realize there is a workaround for this issue and have successfully implemented it on a site I'm developing. However, as the solution isn't obvious without referring to the community for support, should there not be a system check for this possible discrepancy in place at setup time?
