### ISSUE TITLE
TV with input type image doesnt show value of media sources 2.2-pl

### ISSUE THREAD

**Issue by multimedia** [modxbot/migrate#6587]
multimedia created Redmine issue ID 6587

I have set up and saved a template variable with Input Type set to image and selected an existing Media Source for web and mgr.
Then when i edit this template variable again it doesnt show a value for the Media Sources web and mgr.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/d73bbb66fe2469340f86c6b915cd860ff743461b
