### ISSUE TITLE
"Image" input type options missing in template variable Input Options tab

### ISSUE THREAD

**Issue by indium** [modxbot/migrate#6594]
indium created Redmine issue ID 6594

When creating a new template variable and choosing "Image" as the type under the "Input Options" tab, no options specific to the "Image" type are shown below the "Default Value" area.

Here are the steps to reproduce:
# Choose the Elements tab in the left column
# Right-click on Template Variables and select "New Template Variable"
# Click on the "Input Options" tab in the main content area of the manager
# Select the "Image" input type from the dropdown box

Nothing appears beneath the "Default Value" text area as it does for other selected input types that have options.

I've been able to reproduce this problem both with an upgraded installation (from 2.1.5-pl to 2.2.0-pl2) and with a clean installation of 2.2.0-pl2.

The attachment illustrates the missing input type options for the "Image" type.

**Comment by splittingred** [comment]
splittingred submitted:

Not an issue; there are no options anymore for image/file TVs, as the basePath and such options are now relegated to Media Sources. See the documentation on Media Sources for more information.
