### ISSUE TITLE
clearing up the search value in Pack Manager, returns "Search results for [object Object]"

### ISSUE THREAD

**Issue by goldsky** [modxbot/migrate#6608]
goldsky created Redmine issue ID 6608

Reproduction:
1. click the search box, type anything > main window returns "No data to display."
2. clear up the content > main window returns some extras > the notification bar returns "Search results for _[object Object]_"

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/135d02088828ccf7fa844f4f1c671fba7766d60f
