### ISSUE TITLE
Package Management - Usability (2)

### ISSUE THREAD

**Issue by ottogal** [modxbot/migrate#6610]
ottogal created Redmine issue ID 6610

h1. Inconsistent naming of packages

Use of uppercase letters in the names of packages is inconsistent - why
_getResources_ but _getfieldresources_?
Since beginners often misspell snippet names (f.i. Ultimateparent instead of UltimateParent), it is irritating anyway to name the packages ultimateparent (or wayfinder instead of Wayfinder). 
Why not, as a rule, give the packages always the name of the snippet?

**Comment by splittingred** [comment]
splittingred submitted:

Because Packages do not necessarily just contain one Snippet. They could contain no Snippets, for that matter. The casing of the name is up to the developer.
