### ISSUE TITLE
MODX Browser: sort order

### ISSUE THREAD

**Issue by ottogal** [modxbot/migrate#6611]
ottogal created Redmine issue ID 6611

Opening the MODX Browser (f.i. to find the file for a static resource) the files will be displayed unordered. You have to choose the _sort by_ option every time anew.

**Comment by mindeffects** [comment]
mindeffects submitted:

Would REALLY love to have a default sort setting for the MODX Browser, too!

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/352ce4da3dd2f2116e6d471286bfbf7d51993151

**Comment by christianseel** [comment]
christianseel submitted:

Seems to be not fixed at all: http://tracker.modx.com/issues/3417#note-4
(Tested on an image tv with different mediasource than filesystem, and on an snippet that uses a static file)
