### ISSUE TITLE
Manager Usability (Remove element)

### ISSUE THREAD

**Issue by ottogal** [modxbot/migrate#6613]
ottogal created Redmine issue ID 6613

If you remove a snippet (same with chunks etc.) which is actually opened for editing, it will be remain in the edit area. Refreshing the page results in the message "Error! snippet not found!".
Although that's quite logical, it is irritating. Removing an open element should flush the edit area.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/2ea1e59dec6feec8ee2c73574038361a6b1b84cb
