### ISSUE TITLE
Checking user New Password box does not enable "Save" button

### ISSUE THREAD

**Issue by ncrossland** [modxbot/migrate#6631]
ncrossland created Redmine issue ID 6631

If you want to assign a user a new password, using the default options of "Show the new password on screen" and0 "Let MODX generate a password", the "Save" button is not activated unless you click/edit another form element.
1. From User list, right click and choose "Update User"
2. Check the "New Password" box

Result: Nothing; "Save" button not clickable
Expected: "Save" button to be clickable in order to generate the new password

Workaround: enter a character and delete it again in any other field

**Comment by ncrossland** [comment]
ncrossland submitted:

This is in Chrome 16

**Comment by splittingred** [comment]
splittingred submitted:

https://github.com/modxcms/revolution/commit/f51943adcb606993a20121c84c14b80c70eb6706
