### ISSUE TITLE
Resource Groups manager page limited to 10 items

### ISSUE THREAD

**Issue by multimedia** [modxbot/migrate#6712]
multimedia created Redmine issue ID 6712

https://github.com/modxcms/revolution/blob/develop/core/model/modx/processors/security/resourcegroup/getnodes.class.php#L21

The Resource Groups manager page under the Security menu shows only max. 10 Resource Group items on the left side.

Its possible to add more then 10 but they dont show up.

I have tested this to modify the 10 to 20 and then it shows max. 20 Resource Group items.

imo this should not be limited at all and show all resource groups there.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/2595baeca05507fa7d09146e29bef54ed2e19ee2
