### ISSUE TITLE
duplicate base with image TVs and phpthumb

### ISSUE THREAD

**Issue by ghost** [modxbot/migrate#6713]
sottwell created Redmine issue ID 6713

Processed image-type TVs returns a path with the base_path added, such as /assets/images/image.jpg or  /subdir/assets/images/image.jpg. The TV itself only stores the filename; the path is added during output processing somewhere.

phpthumb.class.php prepends the server's base_path to this path, which will also include the base. This results in a duplication of the base, whether just a doubled // or in /subdir//subdir/ which causes phpthumb to not be able to find the image.

**Comment by ghost** [comment]
sottwell submitted:

Installed fresh nightly build and installed phpthumbof. Created image-type TV. Used the TV with phpthumbof.

<img src="[[*image:phpthumbof=`w=200&h=200&zc=1`]]" alt="test image">

The phpthumb debug in the error log says:

 [14] => ResolveFilenameToAbsolute() prepending $this->config_document_root (/Applications/MAMP/htdocs/revo-dev/) to $filename (/revo-dev/assets/images/EP0045.jpg) resulting in ($AbsoluteFilename = "/Applications/MAMP/htdocs/revo-dev//revo-dev/assets/images/EP0045.jpg") in file "phpthumb.class.php" on line 1025

Set the phpthumb_document_root - made no difference what it was set to, the above error was not affected.

**Comment by splittingred** [comment]
splittingred submitted:

Can you give more information about:
- What media source is set for this TV?
- What the basePath and baseUrl for that Media Source is?

**Comment by ghost** [comment]
sottwell submitted:

The media source is relative, in this case assets/images/ for a media source called Images (cloned from the default Filesystem media source). Using absolute path and URL don't make any difference. Its properties in the database:

a:2:{s:8:"basePath";a:6:{s:4:"name";s:8:"basePath";s:4:"desc";s:23:"prop_file.basePath_desc";s:4:"type";s:9:"textfield";s:7:"options";a:0:{}s:5:"value";s:14:"assets/images/";s:7:"lexicon";s:11:"core:source";}s:7:"baseUrl";a:6:{s:4:"name";s:7:"baseUrl";s:4:"desc";s:22:"prop_file.baseUrl_desc";s:4:"type";s:9:"textfield";s:7:"options";a:0:{}s:5:"value";s:14:"assets/images/";s:7:"lexicon";s:11:"core:source";}}

The thumbnail for an image TV while editing is fine. Its path in source is http://localhost/revo-dev/connectors/system/phpthumb.php?h=150&w=150&src=EP0045.jpg&source=2. The value of the TV in the database is just the filename, EP0045.jpg.

However, using phpthumbof in the front-end generates the above error. On examining code, I've seen that phpthumb adds the SERVER['DOCUMENT_ROOT'](or at any rate its internal copy of this) to the beginning of the image's path, and will only use a configuration value if the SERVER value isn't available.

$this->config_document_root = (@$_SERVER['DOCUMENT_ROOT'] ? $_SERVER['DOCUMENT_ROOT'] : $this->config_document_root);

MODx will also add the document_root when generating the image TV's raw output: /revo-dev/assets/images/EP0045.jpg but I can't figure out if this is done by the TV processing code or the media source code.

**Comment by splittingred** [comment]
splittingred submitted:

This has been fixed in phpthumbof 1.3.1; it was more a phpthumbof issue than a core one.
