### ISSUE TITLE
Less than 3 char search on Package Management doesnt work

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#6767]
onepack created Redmine issue ID 6767

If I type "get" I get 0 results where I expect to get at least 4 or 5 results like getpage. getresources, getresourcefield.

Please adjust this so that the search gives results when you only type part of the word as well.

**Comment by splittingred** [comment]
splittingred submitted:

It _does_ work with parts of words; however MySQL has a limit with using LIKE with 3 or less characters.

**Comment by onepack** [comment]
4 Years later. Closed!
Please create a new case if someone still thinks this is valid.
