### ISSUE TITLE
Uninstalling TinyMCE stops documents from rendering

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#6782]
onepack created Redmine issue ID 6782

I don't know if this is a TinyMCE issue or a MODx revolution issue but after I uninstalled TinyMCE I could not access any on my documents anymore in the site document tree. All pages would render completely blank.

**Comment by splittingred** [comment]
splittingred submitted:

Change the which_editor setting to "None".

**Comment by onepack** [comment]
onepack submitted:

Cheers Shaun. My bad for forgetting to check this setting.
Can this be set automatically to none if tinymce cannot be loaded... like a default fallback value?
Just a thought ;-)
