### ISSUE TITLE
Permission bug after selecting another tab on "Access Permissions"

### ISSUE THREAD

**Issue by goldsky** [modxbot/migrate#6801]
goldsky created Redmine issue ID 6801

In my case, it happens on all elements, but I'll give the reproduction for Media Sources permission, and logged in as an Admin:
1. Apply a source to a user group
2. Save
3. Click "General Information" tab
4. Save (again)
5. "Access Denied"

eh?....
1. Click "OK" for the pop up
2. The source now is missing from the list.
3. Flush Permissions.
4. If the Media is set for admin, it'll shown up again in the list. If not, then it'll gone completely.

**Comment by goldsky** [comment]
goldsky submitted:

Hacking the SQL by deleting the contents in the _modx_access_media_source_ cleaned up the situation.

**Comment by opengeek** [comment]
opengeek submitted:

As with all access permissions, make sure you give access to a Group the user you are editing the access permissions with is a member of. I ALWAYS provide full permissions to my Administrator (Super User role) members first.

This issue, which applies to any ACL's in MODX, will be addressed by other improvements to ACL management in the future.
