### ISSUE TITLE
Media Sources's File Types are editable?

### ISSUE THREAD

**Issue by goldsky** [modxbot/migrate#6804]
goldsky created Redmine issue ID 6804

Why can we edit the Media Sources's File Types ?

Is it a bug or further feature?

**Comment by splittingred** [comment]
splittingred submitted:

Because they are not editable.

They are based on classes. Read the documentation on Media Sources - specifically creating a type - and that will clear it up.

**Comment by goldsky** [comment]
goldsky submitted:

true, then the grid should be freezed from double clicking.
it should not open the text field.

**Comment by splittingred** [comment]
splittingred submitted:

That has already been fixed in Git. Thanks!
