### ISSUE TITLE
Create one config file to hold ALL 'hard-wired' path information

### ISSUE THREAD

**Issue by tommls** [modxbot/migrate#6836]
tommls created Redmine issue ID 6836

Please, for 2.3 onward, devise a way for one single config file to contain all the path info (constants) MODx needs.
It would be like a lexicon file for the rest of the software.
Even if you keep core_config whatever in all the various folders, if they could all require and reference one single file that must be updated, this would make migrating/moving installations much easier.
Thank you, Tom

**Comment by MarkH** [comment]
markh submitted:

The whole reason there are core.config.php files is to centralize paths and constants in core/config/config.inc.php. The core.config.php files tell the manager/connectors etc where the core is located (as you can easily move that w/ the Advanced install).

**Comment by tommls** [comment]
tommls submitted:

I understand why they're there -- but not why 6+ config files in different places that say mostly the same thing in each one!! :) :)

Zen Cart for example uses only one equivalent file, I forget what it's called but it is the only file that must change when a site is moved, whereas MODx requires many files to change which all have pretty much the same data. It would simplify site moves etc. if there were only one config file to maintain locally and remotely. And if you don't get all the proper config ducks all lined up properly it causes many subtle problems after moving a site, making it often better to do a clean install when moving a MODx site (ugh). I suppose this will always be a philosophical difference of one vs. many. Thank you, Tom

**Comment by splittingred** [comment]
splittingred submitted:

Zen Cart does not allow you to rename or move its manager, core or connectors directories, either. The multiple config.core.php files are there for exactly that reason.

Re-running setup in upgrade mode automatically upgrades your config.core.php files for you. Just do that if you're frustrated. Or, automate upgrades with the CLI installations available in 2.2.
