### ISSUE TITLE
Gallery Add-on. Can't remove album if very large

### ISSUE THREAD

**Issue by nicboyde** [modxbot/migrate#6837]
nicboyde created Redmine issue ID 6837

Album with >3000 images could not be removed. Individual images could be removed, but the whole album could not.

MODx didn't hang: just refreshed the page and re-presented the album list, unchanged.

Couldn't get rid of it. Had to fix by direct edit to mySQL database tables.

Gallery 1.4 MODx Revo 2.12pl

**Comment by splittingred** [comment]
splittingred submitted:

Please file in the Gallery issue tracker. This is for the Core only.

http://github.com/splittingred/Gallery/issues
