### ISSUE TITLE
Please move the Menu index setting back

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#6844]
onepack created Redmine issue ID 6844

All the menu settings for a page are now in the "document" tab but the menu index is moved away from these settings to the "settings" tab.
It would be more logical to have it in the document tab. Maybe on the right side from "hide from menus" and "published"?

**Comment by splittingred** [comment]
splittingred submitted:

No, the team and community all decided it was better to have it in the 2nd tab - the reason being is a menuindex field is a more advanced setting, and it can be done easier by drag/dropping in the left-hand tree.

**Comment by onepack** [comment]
onepack submitted:

Ok, clear :-)
