### ISSUE TITLE
possible SQL Server bug in databasetable getlist processor

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#6936]
netprophet created Redmine issue ID 6936

User has reported:

(ERROR @ E:\inetpub\core\model\modx\modprocessor.class.php : 248) Recoverable error: Argument 1 passed to modProcessor::outputArray() must be an array, null given, called in E:\inetpub\www.masterword.com\core\model\modx\processors\system\databasetable\getlist.class.php on line 18 and defined

**Comment by splittingred** [comment]
splittingred submitted:

Sanity check added: https://github.com/modxcms/revolution/commit/0cc6c3047fbd94c6edee18ac90ca42991ed0b77a
