### ISSUE TITLE
Context Specific Templates in Manager

### ISSUE THREAD

**Issue by jaredloman** [modxbot/migrate#6941]
jaredloman created Redmine issue ID 6941

I have a situation where I have two entirely different sites that are managed within a single MODx install each within their own context.

It would be nice to be able to link elements (specifically templates) to a particular context in the manager. This way when adding/editing a resource in a particular context you would only see the templates specific to that site (context).

As a possible solution, the relationships could be similar to that of the Template variables are linked to a Template, but instead you would be able to link Templates to a specific context.

**Comment by bertoost** [comment]
bertoost submitted:

Yeah that would be a cool wanted feature!

**Comment by splittingred** [comment]
splittingred submitted:

This can already be done through Element Category ACLs.

**Comment by jaredloman** [comment]
jaredloman submitted:

What if a particular user had access to manage both sites (contexts)? Is it still possible to limit only associated templates when adding/editing a resource for a particular context?

**Comment by splittingred** [comment]
splittingred submitted:

Yes and no. Yes, by targeting the Element Category ACL to that Context. However, this will only work (to my knowledge) when editing a Resource in that context. If the user does something non-related to that Context (say, edit a Template, Setting, or any other non-Resource page), then there's no real way to restrict that, since you can't tell me what Context they're in when they're not _in_ a Context.

**Comment by jaredloman** [comment]
jaredloman submitted:

Thank you very much! If I'm understanding you correctly on targeting the Element Category ACL to the context, then unfortunately it doesn't seem to work. Rather it just doesn't show any templates at all. BobRay has also confirmed that it isn't really possible as things stand.

Personally I still think it would make a great feature in regards specifically to add/editing resources. Maybe this is outside of scope of what contexts were designed for though? I've given a bit better explanation of a scenario here http://goo.gl/Ru5VK  so if you feel so inclined to read it, it may better articulate the scenarios that others might run into this type of situation. 

Thanks again!
-Jared
