### ISSUE TITLE
resource_duplicate description

### ISSUE THREAD

**Issue by jaredloman** [modxbot/migrate#6942]
jaredloman created Redmine issue ID 6942

The description for the resource_duplicate permission appears to be showing only the lexicon key as opposed to a description. 

I've confirmed this to be the case on two separate 2.2.0-pl2 installs on two separate servers.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/8debee0653d8ea4ad1fa68253a01201073c207e2
