### ISSUE TITLE
OnMediaSourceDuplicate is under wrong groupname

### ISSUE THREAD

**Issue by goldsky** [modxbot/migrate#6956]
goldsky created Redmine issue ID 6956

OnMediaSourceDuplicate system event is under _resource_ groupname.
Shouldn't it be under _Media Sources_?

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/edf81fe1b4e90dbe906dd8051a02e786bda23549
