### ISSUE TITLE
resource tree changing tree_root_id render bug

### ISSUE THREAD

**Issue by KristianP** [modxbot/migrate#6960]
KristianP created Redmine issue ID 6960

When changing the setting _tree_root_id_ for example to the resource with the _id 7_ the resource tree will end up in an recursion displaying its self when expanding the resource to view its children.

I have created a backend user with the setting tree_root_id = 7 and some other restriction.
(changing the syetem setting tree_root_id (global) results in same output for alle users).

**Comment by gluethegiant** [comment]
paulmerchant submitted:

The following has fixed the tree_root_id problem for me and at least one other on the forums:

in

core/model/modx/processors/resource/getnodes.class.php

line 177 reads

```
   if (empty($node) && !empty($this->defaultRootId)) {
```

but should be

```
   if (empty($this->startNode) && !empty($this->defaultRootId)) {
```

**Comment by KristianP** [comment]
KristianP submitted:

Paul Merchant wrote:

> The following has fixed the tree_root_id problem for me and at least one other on the forums:
> 
> in
> 
> core/model/modx/processors/resource/getnodes.class.php
> 
> line 177 reads
> 
> ```
>    if (empty($node) && !empty($this->defaultRootId)) {
> ```
> 
> but should be
> 
> ```
>    if (empty($this->startNode) && !empty($this->defaultRootId)) {
> ```

Thanks! This fixed the problem.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/79d8697b81ddd88974957b1b117f443ce14974f9
