### ISSUE TITLE
Disabled "Empty Cache" when changing the template

### ISSUE THREAD

**Issue by mindeffects** [modxbot/migrate#6999]
mindeffects created Redmine issue ID 6999

I recently discovered that when changing the template of the resource just being edited, the option "Empty Cache" gets disabled. For a major change like selecting a new template I think "Empty Cache" should definitely be/stay enabled!

**Comment by MarkH** [comment]
markh submitted:

Has been fixed for 2.1.1:
https://github.com/modxcms/revolution/commit/4a5248afa85313815f64b1a43e9071e1481a23f4

**Comment by pixelchutes** [comment]
pixelchutes submitted:

I am on a fresh install of 2.2.1-dev (3/24 nightly: http://modx.s3.amazonaws.com/releases/nightlies/modx-2.2.1-dev-advanced-032412.zip) and I am noticing that every time I change a Template, the "Empty Cache" checkbox is not preserved. I have tested latest versions of Chrome (beta), Firefox (beta) and Safari -- it does not appear to be a browser-related issue.
