### ISSUE TITLE
infinite recursion while static template dir not exists

### ISSUE THREAD

**Issue by Fi1osof** [modxbot/migrate#7011]
fi1osof created Redmine issue ID 7011
1. set files source not existsing dir  (manager/?a=63)
2. Save static template (manager/?a=19&id=1)
   Error: infinite recursion get dir in modElement.class.php line 862  
   public function isStaticSourceMutable(){
   ...
            $sourceDir = dirname($sourceFile);
               while (!empty($sourceDir)) {
                   if (file_exists($sourceDir) && is_dir($sourceDir)) {
                       $isMutable = is_writable($sourceDir);
                       if ($isMutable) break;
                   }
                   $sourceDir = dirname($sourceDir);
               }
   ...
   }

MODIFIED:
print "<br />";
                $count = 0;
                while (!empty($sourceDir)) {
                    $count++;
                    if($count > 20) break;
                    if (file_exists($sourceDir) && is_dir($sourceDir)) {
                        $isMutable = is_writable($sourceDir);
                        if ($isMutable) break;
                    }
                    $sourceDir = dirname($sourceDir);
                    print "<br />". $sourceDir;

```
            }
```

/var/www/.dom/core/components/contexts/web
/var/www/.dom/core/components/contexts
/var/www/.dom/core/components
/var/www/.dom/core
/var/www/.dom
/var/www
/var
/
/
/
/
/
/

_cause:_
/var/www/.dom/core/components/contexts/web - not exists and has not permissions write in /var/www/, /var/, /

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/4583c73b8fd84fbf1f98bd64112ef3d2de9ec0c2
