### ISSUE TITLE
then else output modifiers

### ISSUE THREAD

**Issue by Coroico** [modxbot/migrate#7029]
coroico created Redmine issue ID 7029

With liveSearch=1 when I write: [[+liveSearch:isnot=`1`:then=`Search`]]  I get 'Search'

and with  [[+liveSearch:isnot=`1`:then=`Search`:else=``]]  I get '' (empty string)

is the else statement mandatory with then ?

If the else part is not present, like with first code line, the result is false.
Is it a normal behaviour or a bug ?

**Comment by MarkH** [comment]
markh submitted:

If you don't use "else" you should get the value of the placeholder itself printed on screen. What that is depends on your code ;)

**Comment by MokoJumbie** [comment]
MokoJumbie submitted:

I don't understand why this resolution is set to invalid. As far as I can tell, the 'isnot' output modifier is broken if you don't include an 'else' condition.

Mark stated that failure to use 'else' causes the value of the placeholder to be output, but I have never found that to be the case, and I've tested with values, of 1, 0, true, false, and the value 'string'. Can someone demonstrate a reproducible example of some code which would work as he described?

The 'is' output modifier always gives the expected result without an else condition. Why can the 'isnot' modifier work in the same way?

Pardon me, Jason, if I am being inappropriate by assigning this to you, but as you are the one who closed it and it doesn't seem to have been looked at in a year, I figure you're my best shot at getting an answer. Thanks in advance.
