### ISSUE TITLE
Return-Path (PHP Mailer) not set when sending emails

### ISSUE THREAD

**Issue by ghost** [modxbot/migrate#7031]
paramaniac created Redmine issue ID 7031

I am using Formit for a number of enquiry forms, although I think this is a core issue and will affect any email sending snippets. It seems that the Return-Path header is not being set in the emails received from the form being submitted. Some email providers do not allow emails through that do not have a proper Return-Path set and check whether the Return-Path is a valid email address.

The problem is that because PHP Mailer within the MODx core is not setting it, the Return-Path is defaulting to: _[INSERT ACCOUNT USERNAME HERE]@your-domain.com_
which in most cases is not a proper email address. The Return-Path is used for bounces etc and should in fact be using the email address submitted in the form by the user, also used as the From address.

I think there may be a bug in the way PHP Mailer is integrated with MODx and the From email address is not being set as the Return-Path.

**Comment by ghost** [comment]
paramaniac submitted:

Sorry it should read: "the Return-Path is defaulting to: _your-account-username@your-domain.com_"

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/65c03b0ca15e168e92e1db80733fc3481bdaffae
