### ISSUE TITLE
textboxes used in tbars triggering multiple connector requests

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#7036]
netprophet created Redmine issue ID 7036

On many if not most manager pages which contain a grid and a textbox filter in the grid's tbar, I am seeing the following problems when the user enters/changes text:
- pressing {tab} causes two identical requests to the connector
- pressing {enter} causes four requests, sometimes seeming identical, other times, two with the search payload and two without

An example page is the Manage Users page. I am also seeing this on several Extras.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/c6cc31f4c93c0b5f1c83c142df4155038b80142a
