### ISSUE TITLE
[[++username]] reveals mysql db username

### ISSUE THREAD

**Issue by andrazk** [modxbot/migrate#7052]
andrazk created Redmine issue ID 7052

I have a Revo 2.2.rc3 installation, with Articles 1.4.3 and Quip 2.2.0.
When I tried to put a tag @[[++username]]@ in comment template chunk (tried to output current user, I know, not right way to do it) I got output the actual mysql DB username I'm connecting with.

In my opinion it's a piece of info that shouldn't be available as a placeholder-tag value. Ever. You don't need this info on the "view" side of your site.
Somebody may repeat my mistake.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/399c972bebb2d85347e99075c42a7e8a36efb6b4
