### ISSUE TITLE
Allow default extended fields to be established when user is added to User Group

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#7068]
wshawn created Redmine issue ID 7068

I thought it would be quite cool to allow default extended User Fields to be assigned to a user group.

When a user is added to the group the fields could be either forced on the user upon their next log in, or completed at the time the user is added via a pop up.

Yeah I know I can simply:

<pre>
                <input type="hidden" name="spaces" value="" />
                <input type="hidden" name="spaces2" value="" />
                <input type="hidden" name="spaces3" value="" />
</pre>

With the Login registration Snippet, just thought this would be a nice direction to move the user back end to.

**Comment by MarkH** [comment]
markh submitted:

Isn't that more something for a plugin?

**Comment by splittingred** [comment]
splittingred submitted:

See Mark's response. This is best for a plugin to handle.
