### ISSUE TITLE
Settings for default media source (“Filesystem”) are changed to default values by setup script

### ISSUE THREAD

**Issue by MichaelvanLaar** [modxbot/migrate#7070]
MichaelvanLaar created Redmine issue ID 7070

Usually I set the basePath and baseUrl settings of the standard media source (“Filesystem”) to a special directory, where users can upload their files. I just don’t want a usual website editor to be able to see the whole directory structure.

Each time I use the setup script again (e.g. because I moved the site to a new server), these two settings of the default media source are overwritten with their default vaules – which is empty. So I have to correct this manually after each use of the setup-script.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/c47c0b5090020ae25254a97e9a946af9505227c9
