### ISSUE TITLE
Column width in setting grids

### ISSUE THREAD

**Issue by ottogal** [modxbot/migrate#7088]
ottogal created Redmine issue ID 7088

Since most of the key names of system settings are rather long, the "name" column should be wider by default. It's boring always to have to increase the width by Hand. (Or do I miss a setting for just that?)

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/e34ada6a62b75f7a94fdfcfb6d7485a2cc48a9fc
