### ISSUE TITLE
disallow manipulation of authority of Super User and Member roles

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#7096]
netprophet created Redmine issue ID 7096

Users are able to lock themselves out of their managers by manipulating the authority level of the Super User Role.
Also I do not think that it is necessary for users to manipulate the Member Role either, since they can create and use other Roles if there is a need.

**Comment by splittingred** [comment]
splittingred submitted:

This seems to have already been done in git for 2.2.1. Closing.
