### ISSUE TITLE
Invalid documentation link in system settings

### ISSUE THREAD

**Issue by MathiasD** [modxbot/migrate#7191]
MathiasD created Redmine issue ID 7191

In system settings -> core -> site -> link_tag_scheme 

The description has a dead link to api.modxcms.com/modx/modX.html#makeUrl

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/120e5f9192224a0008277c03c3c5a3dd4f136b70
