### ISSUE TITLE
Unable to save after changing rank

### ISSUE THREAD

**Issue by DiegoBM** [modxbot/migrate#7194]
DiegoBM created Redmine issue ID 7194

If you only change the User-group's rank for an user (when editing an user) by means of drag-and-dro, you won't be offered the option to save that single change (save button will remain gray).

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/f8dcac5d84f00874ece890fd8dc739f646342d0e

**Comment by DiegoBM** [comment]
DiegoBM submitted:

Thank you, and sorry for the wrong priority
