### ISSUE TITLE
two gallery item TVs assigned to one template - only one allows input

### ISSUE THREAD

**Issue by blankcheck** [modxbot/migrate#7198]
blankcheck created Redmine issue ID 7198

Assign two galleryItem TVs to one template.
Assign template to resource.
Choose image for one galleryItem TV.
Now you can not choose image for another galleryItem TV.

If it helps...

Firebug shows: 
this.browser.win is undefined - error this.browser.win.view.store.setBaseParam('album',alb); galtv.js line 536

**Comment by splittingred** [comment]
splittingred submitted:

This is an issue with Gallery, not the MODX core. Please file the issue here: https://github.com/splittingred/Gallery/issues/
