### ISSUE TITLE
tree_root_id user setting leads to tree problems

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#7272]
netprophet created Redmine issue ID 7272

http://twitpic.com/8o70kf/full

Seen in this configuration
- user only has access to one non-web context
- user does not have role 0 in mgr context
- user is supposed to see just a section of the tree via the setting tree_root_id

**Comment by KristianP** [comment]
KristianP submitted:

Mike Schell wrote:

> http://twitpic.com/8o70kf/full
> 
> Seen in this configuration
> - user only has access to one non-web context
> - user does not have role 0 in mgr context
> - user is supposed to see just a section of the tree via the setting tree_root_id

This has been fixed in this request http://tracker.modx.com/issues/6960

**Comment by mkschell** [comment]
netprophet submitted:

Thanks Kristian.
