### ISSUE TITLE
Can't call processor from front end after upgrade to 2.2.0-pl2

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#7274]
bobray created Redmine issue ID 7274

 Fatal error: Cannot redeclare class modResourceCreateProcessor in C:\xampp\htdocs\revo\core\model\modx\processors\resource\create.class.php on line 606

I get this error when NewsPublisher calls the resource/create processor in the front end with this code:

<pre>
    $response = $this->modx->runProcessor('resource/create', $fields);
</pre>

No error in 2.2.0-rc3

**Comment by mschlegel** [comment]
mschlegel submitted:

Is it possible that this behavior only occurs when Articles is installed? Then this bug would be related to this one: http://tracker.modx.com/issues/6593

**Comment by BobRay** [comment]
bobray submitted:

Yes, definitely Articles. If I uninstall it, the bug goes away.

I've filed this for Articles here: http://tracker.modx.com/issues/7279

**Comment by MarkH** [comment]
markh submitted:

See #7279
