### ISSUE TITLE
Security Risk: Plain Text Password

### ISSUE THREAD

**Issue by johnywhy** [modxbot/migrate#7278]
johnywhy created Redmine issue ID 7278

On resetting the User password, ModX displays 

<pre>
You have successfully changed your password to NewPassword
</pre> 

In plain text. You gotta be kidding.

**Comment by MarkH** [comment]
markh submitted:

Doesn't it give you the option to either show the password on screen or to send it via email?

**Comment by splittingred** [comment]
splittingred submitted:

This is not an issue; like Mark said, you can choose to send via email. Most admin interfaces allow you to display the password that you just typed back to you.
