### ISSUE TITLE
Articles breaks both resource/create and resource/update processors

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#7279]
bobray created Redmine issue ID 7279

Any attempt to call these with runProcessor() leads to a PHP error :

Fatal error: Cannot redeclare class modResourceCreateProcessor in C:\xampp\htdocs\revo\core\model\modx\processors\resource\create.class.php on line 606

This happens even with the Articles plugin disabled and regardless of whether the user is logged in to the Manager or not.

Code to reproduce:

Any snippet with this code:

<pre>
 $fields= array();
 $fields['pagetitle'] = 'hello';
 $fields['alias'] = 'hello';
 $fields['content'] = 'This is the content';
 $fields['published'] = '1';  // same result for $fields['published'] = '0';

 $response = $modx->runProcessor('resource/create', $fields);

if ($response->isError()) {
   return 'Error';
} else {
   return 'Resource Created';
}
</pre>

I can't see any reason why this would happen since, with the plugin disabled, no Articles code should be executing.

**Comment by BobRay** [comment]
bobray submitted:

Uninstalling Articles makes the error go away immediately.

Users on other platforms have also reported this.

**Comment by splittingred** [comment]
splittingred submitted:

I think this is actually a core 2.2 issue with the way that processor files are loaded. I'll look into it.

**Comment by BobRay** [comment]
bobray submitted:

The mystery is that it doesn't appear until you install Articles and disappears when you uninstall Articles. I've spent some time looking and can't for the life of me figure out why.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/6da5ec73c7b201cdcfe9ad6a975676f14bbe829e
