### ISSUE TITLE
TV values not saved to DB if same as default

### ISSUE THREAD

**Issue by MokoJumbie** [modxbot/migrate#7305]
MokoJumbie created Redmine issue ID 7305

I've verified this with checkboxes and radio buttons but it's possible all TV types are affected

If a checkbox or radio button tv has a default value defined, setting an instance of that TV to the default value causes the value to be removed from the DB, making the value indeterminable.

Note that the value is saved to the DB if set to something other than the default

**Comment by splittingred** [comment]
splittingred submitted:

It doesn't make the value "indeterminable" - this is the way TV values should work - otherwise changing the default would not change it across all TVs.
