### ISSUE TITLE
PHP error on template change

### ISSUE THREAD

**Issue by Martijn1981** [modxbot/migrate#7306]
Martijn1981 created Redmine issue ID 7306

Hi,

I'm currently using the latest nightly (March 4th 2012) and the following PHP error appears on top of my screen when attempting to change templates:

Warning: Invalid argument supplied for foreach() in /home/fitin3/public_html/manager/controllers/default/resource/create.class.php on line 108

I'm using FC-rules for all templates. Those aren't applied when I'm attemping to change the template, by the way.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/a0500cb31e0920c1ee8a132e3b8db778db2b2e8f

**Comment by Martijn1981** [comment]
Martijn1981 submitted:

Thanks! Any chance it will also solve _this_ issue? http://tracker.modx.com/issues/7254.
