### ISSUE TITLE
User roles are sorted inconsistently on user group update page

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#7315]
gadamiak created Redmine issue ID 7315

Access policies on 'update user group' page are sorted inconsistently:
- on 'users' tab from highest (0) to lowest (9999); additionally they lack the authority number
- on 'context access' tab from lowest (9999) to highest (0)
- on 'resource group access' from highest (0) to lowest (9999)

Can't determine on other tabs. The sorting order should be from lowest (9999) to highest (0) IMO.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/86b0be0a081aebea5138b840421215993c1b909a
