### ISSUE TITLE
debugging minify compresion issues

### ISSUE THREAD

**Issue by titaniumbones** [modxbot/migrate#7319]
titaniumbones created Redmine issue ID 7319

Hi,

I just installed a student's modx site on my laptop to help her with debugging.  I couldn't get the manager to load and after a while I figured out it had todo with minify; by turning off js & css copression in the database, I was able to fix my issue.  In the manual I'm only told that the problem results from "server misconfiguration". Is there a discussion anywhere of what this 'misconfiguration' consists in, and how to fix it? I'd rather turn compression back on if at all possible.  
Thanks!
matt

**Comment by splittingred** [comment]
splittingred submitted:

It is most likely due to overly restrictive suhosin configurations. Try the latest nightly, and read:

http://rtfm.modx.com/display/revolution20/Troubleshooting+Installation
http://rtfm.modx.com/display/revolution20/MODX+and+Suhosin

**Comment by titaniumbones** [comment]
titaniumbones submitted:

thanks shaun! I'll check those out.
