### ISSUE TITLE
changing a TV's Input Option Value from (some value) to (blank) does not work

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#7326]
netprophet created Redmine issue ID 7326

Steps to reproduce:

1) create a TV of any Input Type
2) provide any value for the Input Option Value
3) Save
4) remove/ blank out the Input Option Value field
5) Save
6) click on the TV again from the left tree

Notice that the value for Input Option Value did not go away.

**Comment by splittingred** [comment]
splittingred submitted:

I believe this was fixed here: https://github.com/modxcms/revolution/commit/3b330d976ddcb5542104c0c264831dbcdc25b489

Closing!
