### ISSUE TITLE
Unable to login via "/manager"

### ISSUE THREAD

**Issue by alenmeister** [modxbot/migrate#7336]
alenmeister created Redmine issue ID 7336

Howdy. I'm currently running MODX Revolution 2.2.0-pl2 (traditional) on my Debian server. I recently found out that I was unable to login to the "manager" page with the users I have created. I get no errors at the login screen. It simply refreshes after I've typed in the correct username and password. I've also tried clearing cache and I've repaired the modx_session table numerous of times without any luck. My admin user is not affected in any way, I'm still able to login via that user, however, not the others. Is there some way to troubleshoot this?

**Comment by XoD** [comment]
xod submitted:

Seems to me like a permission issue, have the other users permissions granted on the web/mgr context?

**Comment by alenmeister** [comment]
alenmeister submitted:

For some reason, the permissions I gave to the users while I created them disappeared. I then added them again to their groups and it looks like it's functioning again!

**Comment by MarkH** [comment]
markh submitted:

Sounds like you got it fixed then!
