### ISSUE TITLE
Set default file browser sort by

### ISSUE THREAD

**Issue by ghost** [modxbot/migrate#7364]
paramaniac created Redmine issue ID 7364

It would be great if there was a system setting which would set the default behaviour for the MODx file browser to sort by: Name, Filesize or Last Modified.

By MODx file browser I mean the one that appears when you are editing a resource and click on a file/image TV.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/0a6deefd708c44de5bb682c8ef9061bf939d6e5e

**Comment by ghost** [comment]
paramaniac submitted:

Thanks for the quick response!

I added the updated code from github and the system setting. However it doesn't seem to work. When I load up the file browser, the "sort by" select box does show "last modified" which is what I have set via the new system setting, but the images aren't in "last modified" order (or by name, filesize). It seems to be random.

Manually clicking on the "sort by" select box and selecting "last modified" works, but negates the point of this feature request.

**Comment by splittingred** [comment]
splittingred submitted:

Thanks for the feedback Alex; that's fixed here: https://github.com/modxcms/revolution/commit/2a836abd1c2b6288170686000e0a3de213e9634f
