### ISSUE TITLE
Recent changes to ellipsis output filter cause PHP error

### ISSUE THREAD

**Issue by MokoJumbie** [modxbot/migrate#7389]
MokoJumbie created Redmine issue ID 7389

The change to the ellipsis output filter in https://github.com/modxcms/revolution/commit/310ca8e4ac0c4eb529442052357614b7b1555933 is causing a PHP error.

If the input string is shorter than the character truncation value fed to the 'ellipse' output filter, the following PHP error will be generated:

Warning:  mb_strpos() [function.mb-strpos]: Offset not contained in string in /home/myaccount/mydomain.com/core/model/modx/filters/modoutputfilter.class.php on line <b>303</b><br />

**Comment by splittingred** [comment]
splittingred submitted:

Fixed, thanks! https://github.com/modxcms/revolution/commit/88852ef394a179db0fd9175d9d8ced687b27ea47
