### ISSUE TITLE
Manager UI bug resizing tree panel

### ISSUE THREAD

**Issue by ottogal** [modxbot/migrate#7390]
ottogal created Redmine issue ID 7390

To reproduce:
- Resize the left hand tree panel to zero width and close the browser tab. 
- Reopen the manager in a new tab. Since you remained logged in, you see the same page as before.
- Now resize the tree panel back to its original width: It reappears totally blank. You have to reload the page to see the tree again.

**Comment by splittingred** [comment]
splittingred submitted:

This is already reported here: #6012
