### ISSUE TITLE
Unable to select Resource Group on TV load

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#7391]
onepack created Redmine issue ID 7391

I just created a Resource Group and now want to assign some TVs to that Resource Group.
I noticed that on the initial load of the TV the new Resource Group is listed in the Access Permissions but it's not selectable.
Only after a refresh in the Access Permissions of the TV the checkbox appears.

This behavior applies for all the TVs.
Clearing the site cache doesn't help.

See the screenshots for more info.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/ac24fc0428d9b47f7950a0c6eda16202232c738b
