### ISSUE TITLE
minified return error 400

### ISSUE THREAD

**Issue by jamestan** [modxbot/migrate#7418]
jamestan created Redmine issue ID 7418

Further investigation with firephp, found the problem:

Minify: The file /manager/assets/modext/widgets/modx.treedrop.js
Minify: Array ( [/manager/] => C:/Domains/mydomain.com/mydomain.com/wwwroot/manager/ [/assets/] => C:/Domains/mydomain.com/mydomain.com/wwwroot/assets/ ) 

Somehow, the virtualdirectory passed into lib/controller/minApp.php are:
Array ( [/manager/] => C:/Domains/mydomain.com/mydomain.com/wwwroot/manager/ [/assets/] => C:/Domains/mydomain.com/mydomain.com/wwwroot/assets/ ) 

And the path  /manager/assets/modext/widgets/modx.treedrop.js contain both the manager and assets.
I think this problem persists on windows platform.

I think shall need to add additional virtualdirectory: /manager/assets/ to fix this issue

**Comment by jamestan** [comment]
jamestan submitted:

i think $hasVirtualAssetsURL in index.php should return false,
im still investigating the issue

**Comment by jamestan** [comment]
jamestan submitted:

strpos(MODX_ASSETS_PATH, $min_documentRoot) !== 0 
//will always true as assets path will always contain documentroot

substr(MODX_ASSETS_PATH, 0, strpos(MODX_ASSETS_PATH, MODX_ASSETS_URL)) !== $min_documentRoot
//will true due to windows vs linux directory separator
min_documentRoot version: C:\Domains\mydomain.com\mydomain.com\wwwroot
MODX_ASSETS_PATH version: C:/Domains/mydomain.com/mydomain.com/wwwroot

**Comment by opengeek** [comment]
opengeek submitted:

This has already been resolved for the upcoming 2.2.1-pl release. You can test using the latest nightlies at http://modx.com/download/nightlies/

**Comment by jamestan** [comment]
jamestan submitted:

hi Jason,

nighties has only 2.2.0

**Comment by splittingred** [comment]
splittingred submitted:

James, that has been fixed. Thanks for bringing it to our attention. You should be able to get the latest nightly now.

**Comment by jamestan** [comment]
jamestan submitted:

thank you Shaun :)
