### ISSUE TITLE
Lexicon Topics not editable trough manager

### ISSUE THREAD

**Issue by wanze** [modxbot/migrate#7422]
Wanze created Redmine issue ID 7422

When creating a custom namespace and some lexicon files, only the default topic is listed in the manager.
Trying to show or edit entries from another topic fails.

Steps to reproduce:
1) Create a custom namespace
2) Create the default lexicon file for a language in components/namespace/lexicon/lang/default.inc.php
3) Add some entries...
4) Create another topic in components/namespace/lexicon/lang/mycustomtopic.inc.php
5) Add some entries...
6) Go to System / Lexicon Management
7) Choose your namespace and the desired language

Now the entries from the default topics appear. However, I cannot
change another topic althought other topic-files are existing.

**Comment by MarkH** [comment]
markh submitted:

Lexicons are cached by default, you'll probably just need to clear the cache and they'll show up.

There's two system settings you can use to change this behavior:
- cache_lexicon_topics
- cache_noncore_lexicon_topics

Both of those are disabled on my local development installs, I do recommend turning them on for production.

**Comment by wanze** [comment]
Wanze submitted:

Hi Mark,
Thank you for your quick answer!
Clearing the cache via manger or manually by deleting all folders/files in the core/cache directory
works neither.
Also disable the lexicon-cache via system settings as you provided does not work on my install.

**Comment by splittingred** [comment]
splittingred submitted:

I can do this fine with Quip, which has the same principles. Can you detail:
- The path to your namespace
- Why setting cache_noncore_lexicon_topics to 0 doesn't work for you

**Comment by wanze** [comment]
Wanze submitted:

Path namespace:
{core_path}components/maloulou/

Setting cache_noncore_lexicon_topics to 0:
I still cannot edit another topic of my lexicon files via manager.

I've made two screenshots. The first one shows my folder structure in my component (core/components/maloulou) and the opened
lexicon file "bestellformular.inc.php".
The second one shows the lexicon manager interface. I'm not able to choose the "bestellformular" topic from the dropdown.
Shouldn't this be possible as there is existing this lexicon file?
Please note that I can use all my lexicon files fine in Snippets and Templates.

**Comment by splittingred** [comment]
splittingred submitted:

Hi Stefan,

I replicated your situation specifically, and was not able to replicate it in any way. I was easily able to switch topics and languages within the lexicon.

What happens if you set the Namespace path absolutely? (Don't use {core_path})

If that doesn't work, make sure those lexicon files and directories are readable by PHP.

**Comment by wanze** [comment]
Wanze submitted:

Hi Shaun,
It works!
The problem is: There has to be a folder "en" and the specific topic file inside too.
I only had folders and files for "de" and "fr".
So it seems that for other topics than "default", the topic file is needed in english.
The default topic worked fine before...
Is this now a bug or a feature? :P
Cheers

**Comment by splittingred** [comment]
splittingred submitted:

Well, hard to say. It's not really a bug, because MODX ships by default in English (and falls back to english) so you'll almost always need a en file.
