### ISSUE TITLE
Unable to delete access policy

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#7444]
onepack created Redmine issue ID 7444

I tried to delete an access policy under Access Controls.
But no matter what I do the item stays listed.

I deleted it 3 times and refreshed the page, cleared the cache, flushed all permissions and flushed all sessions with no effect.
The Access Policy is still listed

**Comment by onepack** [comment]
onepack submitted:

Today after login and checking the policy is not present in the list anymore. What cache caused this behaviour?

**Comment by splittingred** [comment]
splittingred submitted:

Not sure, because I can delete, add, and edit Access Policies fine.
