### ISSUE TITLE
TV name fallback when TV caption is empty

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#7455]
onepack created Redmine issue ID 7455

I noticed that when I don't fill in the TV Caption the TV will render in the Resource Page without any name.
It would be better to at least have the tv-name as a fallback.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/117473ce24f94ce9dc8354b676e2c1f7fda4fdb1
