### ISSUE TITLE
Invalid HTTP Header Response for Compressed Manager-JS/CSS-Files in FastCGI-Environments

### ISSUE THREAD

**Issue by eldanilo** [modxbot/migrate#7456]
eldanilo created Redmine issue ID 7456

Hi!

I stumbled upon a problem in the script _manager/min/lib/HTTP/ConditionalGet.php_. 

Basically, creating the inital cache works - it will be delivered to the browser correctly, and during the first valid-period of the cached files everything works fine. But when the browser tries to revalidate the compressed files after the cache expired (files and etag unchanged), the server will respond with a 200 Code and an empty response - because the script sends a wrongly formatted response for fastcgi-environments.

As a result the manager won't load CSS and Javascript Files (resulting in an unusable manager backend). When you clear the cache and reload the page, the files are loaded normally again.

Changing the following line will fix this problem:

<pre>
<  $this->_headers['_responseCode'] = 'HTTP/1.0 304 Not Modified';

---
> $this->_headers['_responseCode'] = 'Status: 304 Not Modified';
</pre>

As reference: http://de.php.net/manual/en/function.header.php

<pre>
For FastCGI you must use the following for a 404 response:
<?php
header("Status: 404 Not Found");
?>
</pre>

As a workaround you could also disable caching of the manager-resources.

**Comment by MarkH** [comment]
markh submitted:

I know the minify has been getting some updates over the past period, can you try to see if using a nightly fixes it already?

**Comment by eldanilo** [comment]
eldanilo submitted:

I just checked the recent minify version (2.1.5), and the script looks exactly the same as in the 2.2.0-pl2 or the modx-git-repository.

I suppose my webserver-php-combination only works when the script returns a correct ("Status: 304 Not Modified"). But i suppose this is more or less a minify-specific bug and i should open a ticket there?

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/d13b49465adbbb0effaf44e61e78e2eda7246082
