### ISSUE TITLE
getObjectGraph() fails with resource/Parent

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#7477]
bobray created Redmine issue ID 7477

This code returns the current resource in $resource->Parent variable rather than the parent. 

The same code works fine with user/Profile. I suspect it has to do with the fact that resource and Parent have the same class type.

<pre>
$output .= '<h2>Me and My Parent</h2>'; 
$id = $modx->resource->get('id');
$resource = $modx->getObjectGraph('modResource',
    '{"Parent":{}}',
    $id);
$output .= '<p>Me: ' . $resource->get('pagetitle') . '</p>';  // displays the current page pagetitle
$output .= 'My Parent: ' . $resource->Parent->get('pagetitle') . '</p>'; // ALSO displays the current page pagetitle
return $output;
</pre>

**Comment by opengeek** [comment]
opengeek submitted:

I believe this may be an issue related to classes that extend modAccessibleObject. I am looking into this so it is resolved for pending next release.

**Comment by opengeek** [comment]
opengeek submitted:

This issue is fixed and merged into release-2.2 branch; it will be in 2.2.1-pl scheduled for release shortly.
