### ISSUE TITLE
Clarify Media Source Access Policy and restrict available Sources

### ISSUE THREAD

**Issue by MokoJumbie** [modxbot/migrate#7491]
MokoJumbie created Redmine issue ID 7491

"Based on a forum discussion":http://forums.modx.com/thread/74385/why-show-media-sources-list-in-file-browser-at-all, the Policy used to determine the Media Sources available to a TV while editing a resource appears to require reconsideration.

My Understanding:
-The source for a TV as rendered to the front end is build from the Media Source Path as defined for that TV and the TV value saved to the TV. In this case, the only valid TV value should be path a relative to the defined Media Source.

The issues with this:
-A user is capable of selecting a different Media Source for a TV when editing a resource. This makes the purpose of defining one Media Source for a TV unclear. Is it merely a default? Is it to restrict a user's access to a given Media Source for a TV?
-If a user selects a different media source, a discrepancy exists between the defined Media Source and the relative path saved in the TV value causing the wrong path to be rendered to the front end.

Although it would resolve this issue, I'm not sure that removing the other Media Sources from the Drop Down is the right solution. It's nice to have the capability to select a different source. I realize we can set an access policy per TV, but it would be good to be able to define all possible Media Sources for a TV in the TV definition.

Furthermore, selecting a different Media Source needs to render the correct path to the front end regardless of the policy used to restrict available Media Sources for a TV.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed; https://github.com/modxcms/revolution/commit/abd0e6bd0b322858869ac3888255cfba9d008738
