### ISSUE TITLE
Disable 'Is Static' for Elements for which the option is not valid

### ISSUE THREAD

**Issue by MokoJumbie** [modxbot/migrate#7493]
MokoJumbie created Redmine issue ID 7493

The option 'Is Static' doesn't seem to apply to TVs. Can it be removed in this case? Or, if it is actually valid, can a use case be explained in the docs?

**Comment by splittingred** [comment]
splittingred submitted:

TVs do have static abilities; the "Default Value" field is the content that is loaded statically.

**Comment by MokoJumbie** [comment]
MokoJumbie submitted:

Ok, I suppose that makes sense now that you've explained it. I couldn't find a reference to it anywhere. It would be nice if the docs could be updated to clarify the use of Static Elements.

Thanks for clearing that up, and for all the quick fixes.
