### ISSUE TITLE
Add Title Bar to Template Variables Section when placed below Content

### ISSUE THREAD

**Issue by MokoJumbie** [modxbot/migrate#7494]
MokoJumbie created Redmine issue ID 7494

When the Template Variables Section is placed below the content it looks as though a title bar should be there, but is missing. Can a bar similar to the bar above the content area be added to the Template Variables section?

**Comment by MarkH** [comment]
markh submitted:

Make sure the show_tv_categories_header setting is set to "yes".

**Comment by MokoJumbie** [comment]
MokoJumbie submitted:

I've got that setting enabled, but the Categories header is nto what I am talking about. I've got two screenshots attached. The one without the TV header is the current behaviour. The other has a mocked up header highlighted in fuchsia. That's what I'd like to see added. Without it, the TV box just looks incomplete.

**Comment by MokoJumbie** [comment]
MokoJumbie submitted:

Can someone take a look at this? I imagine it'd be an easy fix.
