### ISSUE TITLE
missing checkboxes if more than one quick update page is open

### ISSUE THREAD

**Issue by VJPandaAU** [modxbot/migrate#7499]
xxxmicrobexxx created Redmine issue ID 7499

If I right click a resource and then select quick up date it is fine.

If I repeat that without closing the first one the "hide from menus" and "publish" checkboxes and text are missing.

**Comment by VJPandaAU** [comment]
xxxmicrobexxx submitted:

Actually I just discovered that the missing checkboxes are now added to the page that was opened first.  It has 2 sets of checkboxes.

Interestingly, checking (or unchecking) a box that is displaying on the wrong page and then saving the right page actually works.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/e27ae6c4bc37c6d827fd5bcdddb6a8d2e49520f5
