### ISSUE TITLE
Checkboxes inconsistent

### ISSUE THREAD

**Issue by VJPandaAU** [modxbot/migrate#7500]
xxxmicrobexxx created Redmine issue ID 7500

Trivial, but worth fixing:

In edit resource the publish checkbox is below the hide from menus.  However in Quick Update Resource (right click a resource) it is below

Consistency would be good

**Comment by splittingred** [comment]
splittingred submitted:

https://github.com/modxcms/revolution/commit/9a1f7f864094514b3a9bd8c668301519dda199b6
