### ISSUE TITLE
Media Sources settings dissapear when Updating MODX

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#7504]
onepack created Redmine issue ID 7504

I had one Project that I did not update to the latest release of MODx Revo2.2.0-pl2
It was still on MODx 2.2.0-pl

Today I decided to update this project to 2.2.0-pl2 with the final result that the settings in Media Sources got overwritten by the default values.

**Comment by sparkyhd** [comment]
sparkyhd submitted:

I had the same issue.  I copied a Revo2.2.0-pl2 install from a live server to a staging server for testing and ran the upgrade script.

The initial SQL was

<pre>
INSERT INTO `tm_staging_media_sources` VALUES(1, 'Site Assets', '', 'sources.modFileMediaSource', 'a:2:{s:8:"basePath";a:6:{s:4:"name";s:8:"basePath";s:4:"desc";s:23:"prop_file.basePath_desc";s:4:"type";s:9:"textfield";s:7:"options";a:0:{}s:5:"value";s:8:"assets2/";s:7:"lexicon";s:11:"core:source";}s:7:"baseUrl";a:6:{s:4:"name";s:7:"baseUrl";s:4:"desc";s:22:"prop_file.baseUrl_desc";s:4:"type";s:9:"textfield";s:7:"options";a:0:{}s:5:"value";s:8:"assets2/";s:7:"lexicon";s:11:"core:source";}}', 1);
INSERT INTO `tm_staging_media_sources` VALUES(2, 'Assets Admin', '', 'sources.modFileMediaSource', 'a:2:{s:8:"basePath";a:6:{s:4:"name";s:8:"basePath";s:4:"desc";s:23:"prop_file.basePath_desc";s:4:"type";s:9:"textfield";s:7:"options";a:0:{}s:5:"value";s:7:"assets/";s:7:"lexicon";s:11:"core:source";}s:7:"baseUrl";a:6:{s:4:"name";s:7:"baseUrl";s:4:"desc";s:22:"prop_file.baseUrl_desc";s:4:"type";s:9:"textfield";s:7:"options";a:0:{}s:5:"value";s:7:"assets/";s:7:"lexicon";s:11:"core:source";}}', 1);
</pre>

and after running setup it was

<pre>
INSERT INTO `tm_staging_media_sources` VALUES(1, 'Filesystem', '', 'sources.modFileMediaSource', 'a:0:{}', 1);
INSERT INTO `tm_staging_media_sources` VALUES(2, 'Assets Admin', '', 'sources.modFileMediaSource', 'a:2:{s:8:"basePath";a:6:{s:4:"name";s:8:"basePath";s:4:"desc";s:23:"prop_file.basePath_desc";s:4:"type";s:9:"textfield";s:7:"options";a:0:{}s:5:"value";s:7:"assets/";s:7:"lexicon";s:11:"core:source";}s:7:"baseUrl";a:6:{s:4:"name";s:7:"baseUrl";s:4:"desc";s:22:"prop_file.baseUrl_desc";s:4:"type";s:9:"textfield";s:7:"options";a:0:{}s:5:"value";s:7:"assets/";s:7:"lexicon";s:11:"core:source";}}', 1);
</pre>

**Comment by splittingred** [comment]
splittingred submitted:

Not sure how this is happening; the only case of code that I could see this happen on is the 2.2.0-rc1 upgrade.

**Comment by onepack** [comment]
onepack submitted:

I will download a nightly and use that to check if it happens again for this project. If so I will provide you with an environment to test it yourself.

**Comment by onepack** [comment]
onepack submitted:

I just updated version 2.2.0-pl2 to the latest nightly and the settings are still ok after the update.

Maybe it was an issue before in some environments but it is no longer there in the latest modx versions.

Close bug?

**Comment by splittingred** [comment]
splittingred submitted:

I think actually this was fixed here: #7070
