### ISSUE TITLE
Assigning Media Sources to TVs

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#7508]
onepack created Redmine issue ID 7508

When I want to assign a TV to a Media Source it is not clear that there is a dropdown where you can select your choice. The field renders empty.
After Selecting a value from the dropdown the value is not show in the "Source" field but the Source field renders empty again.
After saving and reloading the TV this is still the case so it is never clear if and what Media Source is selected for a TV.
After Saving the Assignment does work because the TV loads on the frontpage.

Maybe this is old news but I was unable to find a similar Bug report. Sorry in case of a double Issue.

**Comment by onepack** [comment]
onepack submitted:

Here are some screenshots

**Comment by MokoJumbie** [comment]
MokoJumbie submitted:

Have you tried using a recent nightly? I had this issue some time ago but it seems to be resolved for me now.

**Comment by splittingred** [comment]
splittingred submitted:

Yes, this has already been fixed for 2.2.1.

**Comment by onepack** [comment]
onepack submitted:

Ok great thanks!

Good remark Nick Boos.
In the future I will download a nightly and test there before submitting an issue.
