### ISSUE TITLE
External urls in file/image TVs not working anymore

### ISSUE THREAD

**Issue by mschlegel** [modxbot/migrate#7518]
mschlegel created Redmine issue ID 7518

In MODx Revo < 2.20 it was possible to specify external urls ('http://www.somedomain/somefile.pdf') for file/image TVs. @[[*filetv]]@ would then output the external url only, without any baseUrl prepended.
Unfortunately, Revo 2.20 breaks this behavior, it always prepends the baseUrl, and the output looks like this:
@baseUrl/http://www.somedomain/somefile.pdf@

Maybe there were reasons to remove this feature in MODx 2.20. But at least for me it had been quite useful. Currently, I have to remove the baseUrl using an output filter.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/b81794b98651b60da5657c02c676b39955885900
