### ISSUE TITLE
Manager: View a usergroup via GET parameter at usermanagement page

### ISSUE THREAD

**Issue by christianseel** [modxbot/migrate#7521]
christianseel created Redmine issue ID 7521

I would like to be able to call the user-management page (/manager/?a=56) with a GET parameter for a usergroup to filter the view (like /manager/?a=56?usergroup=my+usergroup).

...just like it's already possible for system settings: /manager/?a=70&namespace=phpthumbof

**Comment by splittingred** [comment]
splittingred submitted:

Done: https://github.com/modxcms/revolution/commit/58ed1e52057ba71d020ffc4019778860958395e0
