### ISSUE TITLE
system setting for first day of a week for datepicker

### ISSUE THREAD

**Issue by christianseel** [modxbot/migrate#7531]
christianseel created Redmine issue ID 7531

Sunday isn't the first day of a week all over the world...
For TVs there's a setting for the first day of a week, but on resource fields like pub_date it seems like its hard coded to sunday. I would love to see a system setting for this.

**Comment by christianseel** [comment]
christianseel submitted:

Done in this pull request by Romain (rtripault): https://github.com/modxcms/revolution/pull/302

**Comment by splittingred** [comment]
splittingred submitted:

https://github.com/modxcms/revolution/commit/698c87e129654b1195e67ca79bffba22707e266e
