### ISSUE TITLE
editor_css_path Ignored by TinyMCE

### ISSUE THREAD

**Issue by elebrun** [modxbot/migrate#7535]
elebrun@bryant.edu created Redmine issue ID 7535

If a path to a css file is entered in System Settings, TinyMCE does not use it. 

I am also having issues with setting editor_css_selectors and/or tiny.css_selectors. If I set either of these on the context, they are ignored. If I create a context setting for tiny.css_selectors, that value should override the system setting and I should see the context specific drop down unswe Styles in TinyMCE when editing a Resource.

**Comment by elebrun** [comment]
elebrun@bryant.edu submitted:

That should be "under Styles in TinyMCE." I'm attaching a screenshot of what the Style drop down lists, which is the value from the system setting and not the context setting.

**Comment by splittingred** [comment]
splittingred submitted:

This bugtracker is for core MODX issues only. You can file TinyMCE issues here:

http://github.com/splittingred/TinyMCE/issues/

Thanks!
