### ISSUE TITLE
The phpinfo()-link in System Info does not open a new window

### ISSUE THREAD

**Issue by Martijn1981** [modxbot/migrate#7549]
Martijn1981 created Redmine issue ID 7549

Go to Reports > System Info and click on "View" next to "phpinfo():". The link does not open in a new window. Might be a bit frustrating to go back and reload the CMS yet again.

**Comment by splittingred** [comment]
splittingred submitted:

https://github.com/modxcms/revolution/commit/b3e305b56cc903367d641d54bbcbca5e2ca55da2
