### ISSUE TITLE
Modx Update from 2.0.8 breaking tracking pixels on site

### ISSUE THREAD

**Issue by monnie** [modxbot/migrate#7557]
monnie created Redmine issue ID 7557

Hi, my company is trying to update our MODx Revolution 2.0.8 site to the current MODx version. When the update was made the only issue (although major) that we've noticed is that all of our tracking pixels (analytics, etc...) stop working/firing. We have had to roll back to our 2.0.8 version twice.

Any insight as to why this might be happening? Thanks!!

**Comment by MarkH** [comment]
markh submitted:

Not the slightest clue. Lol. Will definitely need more information before being able of saying anything sensible about this issue.

How are those tracking pixels set up, and how does that work with MODX?

(When updating from 2.0.8 I prefer taking the 2.1.5 middle-step as that's seen to prevent some edge case scenarios, though I don't think that's too related to this).
