### ISSUE TITLE
Add JSON to Default ContentTypes

### ISSUE THREAD

**Issue by freelancewebdev** [modxbot/migrate#7568]
freelancewebdev created Redmine issue ID 7568

Just as in the title, I seem to use JSON in all my Revo projects in some way or another and now withe the upcoming REST mechanisms in 2.3 would be good to have JSON added by default to the content types.

**Comment by splittingred** [comment]
splittingred submitted:

Done: https://github.com/modxcms/revolution/commit/08090b3f2ea39f2eab5eaf4d3c710e674a7e7518
