### ISSUE TITLE
Missing option to duplicate user

### ISSUE THREAD

**Issue by DonQuicky** [modxbot/migrate#7613]
donquicky created Redmine issue ID 7613

I do miss an option for cloning users in the usermanager. Especially when you work with mediasources on userlevel, the cloning function can be very handy. Otherwise you have to refill all systemproperties and so per user.

**Comment by splittingred** [comment]
splittingred submitted:

https://github.com/modxcms/revolution/commit/9ddd2065ec215aa2814b8107714930168cf97a1c
