### ISSUE TITLE
modSessionHandler returning empty result set when session.hash_function = 1 in php.ini

### ISSUE THREAD

**Issue by mjansen** [modxbot/migrate#7646]
mjansen created Redmine issue ID 7646

Cannot login after installing beta3 when the php.ini setting session.hash_function = sha256 (Default in OpenSuSE 12.1) because the SELECT query that should return the modSession instance inserted for a particular user session is returning an empty result set. Here is an example debug log from an affected installation: &#91;2009-09-05 16:26:29&#93; (DEBUG @ /2.0/manager/index.php) Fetched empty result set from statement: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `modx_session` AS `modSession` WHERE `modSession`.`id` = ? with bindings: Array
(
 &#91;0&#93; => Array
(
 &#91;value&#93; => 3c65ed5a65680f56d7c8d648292c8a51d918a286
 &#91;type&#93; => 2
 &#91;length&#93; => 0
) ) &#91;2009-09-05 16:26:29&#93; (INFO @ /2.0/manager/index.php) There was an error retrieving or creating session id: 3c65ed5a65680f56d7c8d648292c8a51d918a286

Altering modx_session.id from CHARACTER(40) to CHARACTER(52) fixes the problem.

May i recommend adding a check to make sure the id to inserted does not exceed the columns size? This is one nasty bug that could potentially cost you guys many users less experienced and determined.

Mike

**Comment by mjansen** [comment]
mjansen submitted:

It looks like there is no association to the cloned bug. So see bug #1189 for the previous incarnation.

**Comment by opengeek** [comment]
opengeek submitted:

Size increased to 255 characters to support even longer hash algorithms. Tested with sha512 (87 character id generated).
