### ISSUE TITLE
Error using 'ago' date modifier - undefined element 'seconds' in modoutputfilter.class.phph

### ISSUE THREAD

**Issue by astrodaz** [modxbot/migrate#7649]
astrodaz created Redmine issue ID 7649

Revo 2.2.1-pl
PHP 5.3.0
Apache 2.2.11

Fresh installation on Windows 7.

Error received is:

<pre>
Notice: Undefined index: seconds in D:\Web\home\core\model\modx\filters\modoutputfilter.class.php on line 536
</pre>

Call in the chunk is:

<pre>
[[+pubdate:ago]]
</pre>

Code in the php file at line 536 is:

<pre>
if (empty($ago)) { /* handle <1 min */
  $ago[] = $this->modx->lexicon('ago_seconds',array('time' => $agoTS['seconds']));
}
</pre>

I can see the $agoTS defined at line 504, as:

<pre>
$agoTS = array(
'years' => $years,
'months' => $months,
'weeks' => $weeks,
'days' => $days,
'hours' => $hours,
'minutes' => $minutes,
'seconds' => $diff,
);
</pre>

**Comment by astrodaz** [comment]
astrodaz submitted:

Apologies - this can be closed!!

I missed the fact it was a notice, not an actual error

**Comment by splittingred** [comment]
splittingred submitted:

Fixed notice here: https://github.com/modxcms/revolution/commit/fbd890e39f0e01f99f42b9f963b6ec607e4e98d5
