### ISSUE TITLE
Session-less contexts allows viewing of unpublished resources

### ISSUE THREAD

**Issue by MokoJumbie** [modxbot/migrate#7652]
MokoJumbie created Redmine issue ID 7652

Enabling the "Session-less contexts feature blogged about by Jason Coward on the MODX blog":http://develop.modx.com/blog/2012/04/05/new-for-2.2.1-session-less-contexts/ is causing unpublished resources to be viewable by anonymous web users.

Workaround: Disabling session-less contexts restores the expected behaviour of refusing access of unpublished resources to anonymous users.

**Comment by opengeek** [comment]
opengeek submitted:

Thanks for catching this one; fixed for 2.2.2-pl
