### ISSUE TITLE
Missing config_ttf_directory setting for phpthumb

### ISSUE THREAD

**Issue by christianseel** [modxbot/migrate#7663]
christianseel created Redmine issue ID 7663

I tried to use a water text mark with phpthumb(of) in MODX Revolution 2.2. with a custom ttf font file. But it didn't work. I found out that the font file is not found by the class file at /core/model/phpthumb/phpthumb.class.php

MODX allready has a default folder for custom ttf fonts, but it did not work for me. (core/model/phpthumb/fonts/)

After searching a while I found the setting config_ttf_directory (which defines the path to the fontfolder). But I could not find it anywhere in modx. I added it to the modphpthumb.class.php default settings and then the text mark worked.

My implementation might be not perfekt, so please review it and make changes if necessary:
https://github.com/modxcms/revolution/pull/304

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in 2.2.2: https://github.com/modxcms/revolution/commit/ca34e62464b1ccb30815057df6160beb7b418390
