### ISSUE TITLE
Save button not available in TV

### ISSUE THREAD

**Issue by VJPandaAU** [modxbot/migrate#7665]
xxxmicrobexxx created Redmine issue ID 7665

If I have a TV and decide to just change the default value under input options, the save button doesn't become available until I at least click in the Input Option Values field.  This is similar to other bugs I have reported e.g. #7583

**Comment by VJPandaAU** [comment]
xxxmicrobexxx submitted:

I have just updated to 2.2.1 and behaviour persists

**Comment by splittingred** [comment]
splittingred submitted:

Already fixed. All fields do not enable save button until you move out of focus - this is due to using "blur" rather than "change" due to inconsistencies in various browsers.
