### ISSUE TITLE
CMP Processor Class Overrides 'doesAlreadyExist' missing from modObjectUpdateProcessor

### ISSUE THREAD

**Issue by AESmith** [modxbot/migrate#7677]
aesmith created Redmine issue ID 7677

I seems to me that 'doesAlreadyExist' should be an available method within modObjectUpdateProcessor just as it is within modObjectCreateProcessor.

Currently after a record is added to the the database , through the Update Processor one could then change it to a value which already exists because there is no check as there is with create.

Solution: Roll your own method based on the same method logic in modObjectCreateProcessor.

Add this to your "update.class.php" Class file and all is well. If you try to use without you will get a failed connector.

public function doesAlreadyExist(array $criteria) {
            return $this->modx->getCount($this->classKey,$criteria);
    }

**Comment by splittingred** [comment]
splittingred submitted:

I believe this was added to the 2.3 (develop) branch already in Git.
