### ISSUE TITLE
Quick update is broken in 2.2.2

### ISSUE THREAD

**Issue by goldsky** [modxbot/migrate#7712]
goldsky created Redmine issue ID 7712

The resource's quick update is broken.
It has multiple published checkboxes, and rejects saving.

**Comment by goldsky** [comment]
goldsky submitted:

missed the attachment

**Comment by MarkH** [comment]
markh submitted:

Thanks! Looks like the result of a merge screw up... the problem with it not saving has to do with the resource you're updating being the site_start, and you can't unpublish that. If you'd tick the second published block as well it would properly save.

Fix is awaiting integration: https://github.com/modxcms/revolution/pull/309
