### ISSUE TITLE
CTRL+S Should Save Document when Rich-text editor is focused

### ISSUE THREAD

**Issue by neilness** [modxbot/migrate#7724]
neilness created Redmine issue ID 7724

TinyMCE hijacks keypresses, so it would be nice if a hook was coded to save the document when the user pressed ctrl+s so the interface would be consistent whether or not richtext was enabled.

**Comment by MarkH** [comment]
markh submitted:

As you say, this is a TinyMCE problem, so please report it there and not in the Revo project: https://github.com/splittingred/tinymce/issues
