### ISSUE TITLE
Static chunk empty on second reference

### ISSUE THREAD

**Issue by martinf55** [modxbot/migrate#7763]
martinf55 created Redmine issue ID 7763

The MediaSource of chunk restored from source cache is the superclass rather than FileMediaSource.

The initial symptom of this issue is that if a static chunk stored in a file media source is referenced in resource content twice, the output from the second reference is empty.

In modParser->getElement() around line 420, if the element is found in the sourceCache, it re-creates the element's media source from cache too. The problem is that the class re-created is always the superclass "sources/modMediaSource", presumably because the cache only contains the id of the mediasource and not its class.

Later on when process() is called on the second chunk instance which was re-created from cache, its content is not found because getBasePath() of the superclass modMediaSource always returns empty string, rather than the correct path that would be returned from modFileMediaSource.

Workaround: deselect the file media source on the static chunk and use the full path to the static file instead, if the chunk is needed on the page more than once.

**Comment by opengeek** [comment]
opengeek submitted:

This is partially addressed in #7392 but I am addressing additional issues that occur when modX::getChunk() and modX::runSnippet() are used with Static Elements using a Media Source, and improving the overall efficiency of the code in modParser::getElement() when a Media Source is specified for an Element.

**Comment by opengeek** [comment]
opengeek submitted:

Fixed for 2.2.5-pl
