### ISSUE TITLE
Usability issue with access wizard

### ISSUE THREAD

**Issue by ottogal** [modxbot/migrate#7764]
ottogal created Redmine issue ID 7764

If you open the panel Create Resource Group and unfold the Access Wizard area, the panel will be too high on smaller screens: You can not access the close/save buttons unless you move the panel by dragging its title bar upwards.
But now there's the trap:
Once having moved the panel too far, you loose access to that title bar and cannot move it back anymore.

**Comment by ottogal** [comment]
ottogal submitted:

Logout and Re-Login won't help: The panel keeps its position even after clearing manager and browser caches. So it remains inaccessable - that's why I classified the issue as Major.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/a9acbb234a50aa6abc3ff5fd3f8b741b7bace32f
