### ISSUE TITLE
Help Manager / Custom Help Content

### ISSUE THREAD

**Issue by XoD** [modxbot/migrate#7786]
xod created Redmine issue ID 7786

In Modx Evolution there was a possibility to have custom help content when clicking the help button top right. I did some research (maybe not with the right search terms??) and couldn't find anything about this topic for revolution. I just know the system setting base_help_url which points to the rtfm.modx.com page and autogenerates the right link depending on the page/section you are. This is nice for me as admin but for my less savy users I would like to create a custom help section with explanations, embedded screencasts and so on. Is there already a possibility to do this or would this be a probably neat feature?

**Comment by splittingred** [comment]
splittingred submitted:

Yes, just change the base_help_url to whatever the url of your site is.

**Comment by gadamiak** [comment]
gadamiak submitted:

Is there a guide on how to tie help to manager UI parts? It looks like the @base_help_url@ is appended with a specific URI but what are they for what parts of the UI?

Also, is there a way to open a specific help page based on a template being used or a place of a resource in the document tree?

**Comment by XoD** [comment]
xod submitted:

It seems to be a misunderstanding =)...I know the system Setting and I also tried to set it to another page btw. leave it empty...but the manager seems to add stuff like "Resource" to the url itself and this is also done when I changed the <code>base_help_url</code>, what made it totally useless if not using the standard rtfm url because all you get is a 404 (for example when I add http://www.domain.tld/help/ then http://www.domain.tld/help/Resource would be called on a resource editing page, the URL doesn't exist in this form, so we get an 404). I would like to make a custom help section (for logged in users) out of resources inside the manager (something like a for "normal" visitors hidden help page, like it can be done with documenter http://revaxarts-themes.com/documenter/ ). Is the help overlay maybe not the right place for stuff like that?

**Comment by XoD** [comment]
xod submitted:

I really think this shouldn't be closed as fast as it was, it is either a bug or it would be a really good feature to have in a future version (see comment above for "bug")

**Comment by MarkH** [comment]
markh submitted:

The help functionality offers page-specific help by using the base url, and appending an uri for the specific part of the manager you are looking at. 3PCs can also hook into this, by providing what needs to be appended to be baseurl.

Point being that you can't be 100% sure what the requested url will be, so your implementation needs to properly handle that. It could see if there is documentation for that specific request available, and otherwise route it to the RTFM. Or provide an error message which tells them to give you a call if they need help.

**Comment by XoD** [comment]
xod submitted:

In my opinion, this makes it much more complicated than it needs to be in most cases. It's great to have that functionality for big pages with english speaking editors (because rtfm ist mostly english) or where you have big budgets to develop a complex help system.

But for small sites (with maybe 10-30 pages, limited functionality etc.) developers just don't have the budget/time to implement such a help system.

I'm really open to good ideas how to handle this for a small site, my idea would be something like this:

1) create one/1 resource with alias "help", as content, there would be some sections with ID's like "resource" with screencasts and a little text in them

2) change base_help_url to http://www.domain.tld/help.html#

3) when clicked the page with the screencasts opens in the modal box

this would be more or less simple btw. recyclable and I would like to invest more time into the screencasts and the "real" site developement than programming the code for the help section

**Comment by gadamiak** [comment]
gadamiak submitted:

There's "discussion about this issue":https://github.com/modxcms/revolution/pull/324 on GitHub.
