### ISSUE TITLE
Auto notification when a new version of Revo is launched.

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#7789]
onepack created Redmine issue ID 7789

I think it would be helpful for the Modx revo community when there was a wordpress-like notification when there is a new Revo release available for download in the dashboard.

**Comment by XoD** [comment]
xod submitted:

Why not =), but it should be possible to not show it to every usergroup, ie. there's a need for a permisison setting. On the other side, there's the modx newsfeed on the dashboard where updates are announced regularly... So if something like this was implemented I would rather like it to be styled as an overlay, like the welcome screen or so.

A problem that I see with the download thing is, that it doesn't seem to be possible to update modx from within the manager, so downloading the new version won't be very useful...

**Comment by onepack** [comment]
onepack submitted:

Indeed, the notification should only be visible for Administrators or specific users by default. :-)

**Comment by martinf55** [comment]
martinf55 submitted:

This is currently on the MODX Roadmap as "Add auto-update for MODx - IOW, update from the manager".

http://rtfm.modx.com/display/revolution20/Roadmap

**Comment by XoD** [comment]
xod submitted:

This would definitely be a nice feature but as long as it's not implemented I don't see the purpose of a "message" that there's a new version (beside form the news dashboard widget). And maybe this would be implemented anyway if the auto-update thing is added? =)

**Comment by onepack** [comment]
4 Years later. Closed!
Please create a new case if someone still thinks this is valid.
