### ISSUE TITLE
can't attach media source to usergroup

### ISSUE THREAD

**Issue by manu37** [modxbot/migrate#7793]
manu37 created Redmine issue ID 7793

When I try:
Security->Access Control->modify usergroup->Add Media source permission: Save action hangs.
Errorlogfile shows: [2012-05-08 22:14:29](ERROR @ /connectors/security/access/usergroup/source.php) Could not load class: modAccessMediaSource from source.mysql.modaccessmediasource.
The other way works: tools->media sources->add usergroup.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/ba90a006a7385ab249e63d4c07eec2f13ebc9a6f
