### ISSUE TITLE
Can't add Media Source to Access Policy

### ISSUE THREAD

**Issue by CyntaxDotDev** [modxbot/migrate#7794]
ReSpawN created Redmine issue ID 7794

When trying to add a Media Source to an Access Policy for a customer, the dropdown is empty and returns no errors, with a total of 0 results. I've checked processor and nothing seems out of order. It should function perfectly but it doesn't .

**Comment by CyntaxDotDev** [comment]
ReSpawN submitted:

Oh, and since we're NOT getting an error, is has nothing to do with this one: http://tracker.modx.com/issues/7793

**Comment by splittingred** [comment]
splittingred submitted:

Was this a traditional, advanced or git install? New install or upgrade? If upgrade, from what version?

**Comment by CyntaxDotDev** [comment]
ReSpawN submitted:

Hey Shaun, We noticed this problem after an upgrade from Modx 2.2.1-pl, tough we have several sites running on that version aswell. Who also seem to have that problem

**Comment by splittingred** [comment]
splittingred submitted:

Was this a traditional, advanced or git install?

**Comment by CyntaxDotDev** [comment]
ReSpawN submitted:

Traditional.

**Comment by splittingred** [comment]
splittingred submitted:

Can you try running setup again? I can't seem to reproduce this locally.

**Comment by CyntaxDotDev** [comment]
ReSpawN submitted:

Will try a fresh re-setup tomorrow. Hopefuly that'll do the trick. Never seen this one before. :-(

Thanks for the speedy replies tho!

**Comment by XoD** [comment]
xod submitted:

I had this issue too on several 2.2.x installations, but on the other side, I had working 2.2.x on the same server^^...absolutely strange. Updating seemed to do the trick sometimes.

**Comment by CyntaxDotDev** [comment]
ReSpawN submitted:

We finally got it to work - sort of. The dropdown (combo) works again and shows the two Media Source rights, but now the AJAX is getting a fatal error on the fromArray.

<pre>Tijdstempel: 10-5-2012 10:55:23
Fout: missing ) in parenthetical
Bronbestand: /manager/assets/ext3/ext-all.js
Regel: 8, Kolom: 9
Broncode:
<b>Fatal error</b>:  Call to a member function fromArray() on a non-object in <b>/path/public_html/core/model/modx/processors/security/access/usergroup/source/create.php</b> on line <b>40</b><br /></pre>

From Firebug:

<pre>missing ) in parenthetical
/manager/assets/ext3/ext-all.js
Line 8</pre>

From the Firebug response (XHR):

<pre><br />
<b>Fatal error</b>:  Call to a member function fromArray() on a non-object in <b>/path/core/model/modx/processors/security/access/usergroup/source/create.php</b> on line <b>40</b><br /></pre>

_This is AFTER a 2.2.2-pl re-update WITH original files from a Traditional installation_

**Comment by CyntaxDotDev** [comment]
ReSpawN submitted:

First Shaun-fail I found - ever! :D

Here's the fix.

<pre>
/* @var $acl modAccessMediaSource */
$acl = $modx->newObject('sources.modAccessMediaSource');
$acl->fromArray($scriptProperties);
$acl->set('principal_class','modUserGroup');
if ($acl->save() == false) {
    return $modx->error->failure($modx->lexicon('access_source_err_save'));
}
</pre>

Notice the small "source" changed to "sources". :) Hazaaaaaaa!

**Comment by CyntaxDotDev** [comment]
ReSpawN submitted:

Any update on this? :)

**Comment by 9thwave** [comment]
9thwave submitted:

I'm also getting this problem, so any updates appreciated.

**Comment by splittingred** [comment]
splittingred submitted:

Erm, core/model/modx/processors/security/access/usergroup/source/create.php shouldn't exist, or isn't used anymore. The correct file is:

core/model/modx/processors/security/access/usergroup/source/create.class.php

Do you have the .class.php file? If so, can you delete the create.php (leaving the create.class.php file) and try again?

**Comment by splittingred** [comment]
splittingred submitted:

Oh, wait, this was already fixed in #7793 - closing as duplicate.
