### ISSUE TITLE
Checkbox TVs can not be display in rows

### ISSUE THREAD

**Issue by pepebe** [modxbot/migrate#7866]
pepebe created Redmine issue ID 7866

I noticed in MODX Revolution 2.2.1-pl (traditional) that checkbox TVs cannot be displayed in multiple rows as it is possibe for radio buttons.

If you create or update a checkbox TV the "columns" input field and description is missing. 

I might be wrong, but I remember that it was possible in the past.

A quick look at

manager/templates/default/element/tv/renders/inputproperties/radio.tpl
manager/templates/default/element/tv/renders/inputproperties/checkbox.tpl

shows that this is not a bug, but the necessary code is missing.

I have uploaded a temorary fix to my github fork that adds the missing part: 

https://github.com/pepebe/revolution/commit/68d914b29da62708e2f28e20ce3246b7910ceb01

There is one thing missing to make this complete. "checkbox_columns_desc" should be 

"The number of columns the check boxes are displayed in."

instead of

"The number of columns the radio boxes are displayed in."

I don't know where to change that. Please shed some light on the location of this one. 

Regards,

pepebe

**Comment by pepebe** [comment]
pepebe submitted:

HOW can I edit typos in the original text? Edit just opens a new comment...

**Comment by MarkH** [comment]
markh submitted:

I actually think you can't update the original description without some magic powers that isn't something everyone should have... Just create a comment if something's wrong, we're fine with that. ;)

Thanks for taking the time to report and fix issues, that's really appreciated.

The text is stored in lexicons, which can be found in core/lexicons/. The text string you noticed is wrong is probably in en/tv_widget.inc.php.
