### ISSUE TITLE
Dropdown "wiggle" in manager

### ISSUE THREAD

**Issue by gavinanderegg** [modxbot/migrate#7897]
gavinanderegg created Redmine issue ID 7897

Please forgive me if this issue has been brought up before. I looked through the tracker for something similar, but wasn't able to find it.

Inside the MODX manager, when a user hovers over the options presented by a select input field (a dropdown menu), there's a change in the position of the text. This is because there's a 1px white border being applied to unhighlighted items, but this border is not being applied to highlighted ones. This border is applied in @/manager/assets/ext3/resources/css/ext-all-notheme-min.css@ and isn't being overridden. Because of this, it's possible to hover directly over the border boundary and have the menu items hover between two states.

This could be fixed by overriding the default extJS stylesheet in the @/manager/templates/default/css/xtheme-modx.css@ stylesheet. Currently the relevant section looks like this:

<pre>
.x-combo-list-item {
    border-color:#fff;
}

.x-combo-list .x-combo-selected{
    border:0 none !important;
    background-color:#BACC8D;
}
</pre>

If the @.x-combo-list-item@ also had @border:0 none !important;@ the experience of using dropdown menus inside of the manager would be much more smooth.

**Comment by pdincubus** [comment]
pdincubus submitted:

Is this going to be completed in the next release? It seems an incredibly simple fix for an annoying problem?

**Comment by MarkH** [comment]
markh submitted:

Wasn't this already patched in 2.2.8 or 2.2.9? I seem to recall a pull request for this.

**Comment by MarkH** [comment]
markh submitted:

Yep, here we go: https://github.com/modxcms/revolution/pull/436
Merged in https://github.com/modxcms/revolution/pull/443
