### ISSUE TITLE
Areas no longer function in Property Sets

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#7916]
wshawn created Redmine issue ID 7916

The entire area ui is fubar in Property Sets.

If you add them, they are ignored.  Once you close the Property, if can not be edited.
A new area line appears for each property.

**Comment by JGrant** [comment]
jgrant submitted:

This still affects Revolution-2.2.5-pl.
'Area' isn't ignored; you can create areas. However creating a property followed by updating any property triggers the problem I think wshawn is talking about.

Steps to replicate the problem:

# Click 'Create Property' (for snippet or chunk, in default property set or in another)

# Give it a name and click 'Done'.

# Update any property. The Area field is messed up (see screenshots).

Each subsequent update adds another Area line.

To fix it, optionally save the element then click on it in the Elements tree on the left to reload the page.  The problem will still occur though if the steps above are repeated.

Tested on:
2.2.5-pl Advanced - Chrome 22
2.2.5-pl Traditional (MODX Cloud) - Chrome 22
2.2.4-pl Advanced - Firefox 16
