### ISSUE TITLE
Error when editing documents in multi-context site

### ISSUE THREAD

**Issue by aladage** [modxbot/migrate#7925]
aladage created Redmine issue ID 7925

In a multi-context site, non-sudo users are unable to edit resources, despite proper ACL settings that should allow them to edit a resource in the given context. When the user clicks a resource to edit it, the top MODX logo area and top nav load fine, but everything below it (including the tree and edit area) is replaced with a grey screen that says "Error! Access denied." (see attached screenshot). This bug only seems to affect editing documents, and not creating new documents or editing other types of content in the manager (chunks, snippets, etc.). 

I've attached a few photos to help demonstrate how my ACLs are set up, and what the error looks like. Please see this forum thread for additional info and screenshots (Bob Ray helped me troubleshoot the ACLs and determine it's probably a legit bug): http://forums.modx.com/thread/?thread=75318&page=1

**Comment by BobRay** [comment]
bobray submitted:

I was able to duplicate this in my own install of Revo 2.1.1.

With a new context, a user with access to the context (but no access to the web context) with a policy of Administrator can see but can't edit documents.

Adding a single Context Access ACL entry giving the user group access to the web context solves the problem. They can now see and edit documents in the new context, but that shouldn't be required. 

Steps to reproduce:

Create a new context 'NewContext' with some child documents.
Create a user group with a user who is an admin Super User
Give the user group Context Access ACL entries for the 'mgr' and 'NewContext' contexts with a policy of Administrator.

Log in as the user and try to edit documents in the NewContext context.

Giving the user group a Context Access ACL entry for the web context allows them to edit NewContext documents.

**Comment by JaCraig** [comment]
jacraig submitted:

If you need to limit access to the web context but allow to other contexts and experience this issue, you can set the "web" context to have a "Load Only" access policy.  This works around the bug making you able to edit the other context's content, but the web context doesn't show up to the users that you don't want to have access.

**Comment by IareTedd** [comment]
pash88 submitted:

To fix this bug, I made changes in file "./manager/controllers/default/resource/resource.class.php":

<pre><code class="php">    public function setContext() {
        if(!empty($this->scriptProperties['context_key'])) {
                $this->ctx = $this->scriptProperties['context_key'];
        } else {
                $resource_ctx_key = $this->resource->get('context_key');
                $this->ctx = !empty($resource_ctx_key) ? $resource_ctx_key : 'web';
        }
        $this->setPlaceholder('_ctx',$this->ctx);
        $this->context = $this->modx->getContext($this->ctx);
        
        return $this->context;
    }</code></pre>

**Comment by opengeek** [comment]
opengeek submitted:

Fixed thanks to a pull request from Pavel. Will be in 2.2.3-pl available shortly.
