### ISSUE TITLE
Quick update window contains duplicated "published" checkbox

### ISSUE THREAD

**Issue by bertoost** [modxbot/migrate#7949]
bertoost created Redmine issue ID 7949

Title says enough right?

This causes that resources are unpublished after a quick update save and the "site_start" resource cannot be saved at all.. Returns an error (not in a window by the way) which says "cannot be unpublished because it's linked to the site_start system setting".

**Comment by MarkH** [comment]
markh submitted:

Already fixed for 2.2.3. 

If you can still reproduce in 2.2.3 from git / nightly, let me know and I'll re-open the ticket.
