### ISSUE TITLE
Uploading passed max filesize is not shown as warning

### ISSUE THREAD

**Issue by CyntaxDotDev** [modxbot/migrate#7966]
ReSpawN created Redmine issue ID 7966

When we upload a file more than 1 MB (1MB max in system settings) it cancels and returns true, but no warning. It took some time to figure out we forgot to increase the max filesize upload to 25MB instead of 1MB. The real bug is that there is NO warning.

**Comment by Pendrokar** [comment]
pendrokar submitted:

Dublicate of #7498
