### ISSUE TITLE
Can't Create & Edit File on 2nd Media Source

### ISSUE THREAD

**Issue by lokamaya** [modxbot/migrate#8018]
lokamaya created Redmine issue ID 8018

There are 2 media sources:
- Filesystem (basePath and baseURL empty) - default
- Fileassets (basePath and baseURL: "assets/")

h1. CREATE FILE

From dropdown in _Files_ tab, try to change media source from "Filesystem" to "Fileassets" then click "Create File". Errors are below:
- The dropdown back to default: Filesystem
- When saving the new file (ie. test.txt), test.txt has been saved in the root directory not in /assets directory.

h1. EDIT FILE

From dropdown in _Files_ tab, try to change media source from "Filesystem" to "Fileassets" then try to edit some old file. Errors are below:
- The dropdown back to default: Filesystem
- When saving the old file (ie. old.txt), there is popup alert "File does not exist: old.txt"

---

_Tracking the error:_
- URL: /connectors/browser/file.php
- There is no _source_ variable on HTTP_POST when creating or editing file, that is why it can not recognize the valid media source.

**Comment by wshawn** [comment]
wshawn submitted:

He is correct.  If you go to the Files tab in the Tree and switch the source it is read only.  There is no right click option available - though I would also have to wonder if this is intended functionality.

For File and Image TVs we would not want people to have full access to those areas, but in the file menu?

**Comment by MarkH** [comment]
markh submitted:

https://github.com/modxcms/revolution/pull/375

**Comment by opengeek** [comment]
opengeek submitted:

PR integrated for inclusion in 2.2.5-pl — thanks Mark!
