### ISSUE TITLE
Manager default theme hardcoded theme path

### ISSUE THREAD

**Issue by jonrawlins** [modxbot/migrate#8042]
jonrawlins created Redmine issue ID 8042

_Code below is with /manager/templates/default/header.tpl_

<pre>

_{if $_config.compress_css}
<link rel="stylesheet" type="text/css" href="{$_config.manager_url}assets/ext3/resources/css/ext-all-notheme-min.css" />
<link rel="stylesheet" type="text/css" href="{$_config.manager_url}min/index.php?f={$_config.manager_url}templates/*default*/css/xtheme-modx.css,{$_config.manager_url}templates/default/css/index.css" />
{else}
<link rel="stylesheet" type="text/css" href="{$_config.manager_url}assets/ext3/resources/css/ext-all-notheme-min.css" />
<link rel="stylesheet" type="text/css" href="{$_config.manager_url}templates/*default*/css/xtheme-modx.css" />
<link rel="stylesheet" type="text/css" href="{$_config.manager_url}templates/*default*/css/index.css" />
{/if}_
</pre>

Caused me a 30 minute headache, as assumed this would have been grabbed from the config values.

h2. Fixed with the below code:

<pre>{if $_config.compress_css}
<link rel="stylesheet" type="text/css" href="{$_config.manager_url}assets/ext3/resources/css/ext-all-notheme-min.css" />
<link rel="stylesheet" type="text/css" href="{$_config.manager_url}min/index.php?f={$_config.manager_url}templates/{$_config.manager_theme}/css/xtheme-modx.css,{$_config.manager_url}templates/{$_config.manager_theme}/css/index.css" />
{else}
<link rel="stylesheet" type="text/css" href="{$_config.manager_url}assets/ext3/resources/css/ext-all-notheme-min.css" />
<link rel="stylesheet" type="text/css" href="{$_config.manager_url}templates/*{$_config.manager_theme}*/css/xtheme-modx.css" />
<link rel="stylesheet" type="text/css" href="{$_config.manager_url}templates/*{$_config.manager_theme}*/css/index.css" />
{/if}

</pre>

Thanks

**Comment by jonrawlins** [comment]
jonrawlins submitted:

Just an update, it would seem this is in the login page tpl as well:

<pre>
<link rel="stylesheet" type="text/css" href="{$_config.manager_url}assets/ext3/resources/css/ext-all-notheme-min.css" />
    <link rel="stylesheet" type="text/css" href="{$_config.manager_url}templates/default/css/xtheme-modx.css" />
    <link rel="stylesheet" type="text/css" href="{$_config.manager_url}templates/default/css/index.css" />
    <link rel="stylesheet" type="text/css" href="{$_config.manager_url}templates/default/css/login.css" />
</pre>

**Comment by splittingred** [comment]
splittingred submitted:

Won't fix this, for this reason - We originally had this in place, but found that doing this caused the following issue:

Say you just want to change the template for the "resource/create" page, and that's it. If I change the manager_theme setting here, then to do that I'd have to copy all the base CSS/JS files over to my custom theme directory as well. That creates far more work for me to just copy a single page.

The preferred method is to simply copy the header.tpl file into your own theme, and override it there, if you want to change the CSS/JS for the theme.

**Comment by jonrawlins** [comment]
jonrawlins submitted:

No problem, just thought I would raise it as being new to skinning the backend manager meant I duplicated the entire folder and after about 30 minutes of time wasted realised the paths within the header were wrong. Perhaps something could be added to the RTFM regarding the manager theme and what you MUST update to get the theme working? Thanks for the time you took to reply.
