### ISSUE TITLE
empty($xpdoobject->hydratedfield) is always true in 2.2.2?

### ISSUE THREAD

**Issue by martinf55** [modxbot/migrate#8052]
martinf55 created Redmine issue ID 8052

First seen in 2.2.2-pl, works as expected in 2.2.1-pl.
First seen in a custom class but since observed in standard MODX classes.

Reproduce steps:
Setup two vanilla Traditional installs, one for 2.2.1-pl, another for 2.2.2-pl.

Add a snippet "emptytest" with this code:
<?php
echo($modx->resource->id);
if (empty ($modx->resource) || empty($modx->resource->id)) {
  return 'No resource?';
} else {
  return 'Got a resource';
}

Add the snippet call [[!emptytest]] to the default homepage resource id 1.

Open the homepage for the two installations.

On 2.2.1-pl, the output is:
1Got a resource

On 2.2.2-pl, the output is:
1No resource?

I'm not yet sure what's happening, and whether this change in behaviour is expected. I understand that use of $object->get('hydratedfield') is preferred according to http://rtfm.modx.com/display/xPDO20/Hydrating+Fields, but unfortunately I've probably used the shorthand fields in many places like this, so I'd like to work out if it's expected behaviour before I downgrade or embark on a cleanup of my code.

Switching the xpdoobject.class.php from 2.2.1-pl into the 2.2.1-pl install reverts the behaviour.

**Comment by splittingred** [comment]
splittingred submitted:

This might be due to the magic method refactoring of class vars in xPDO for 2.2.2 that granted the speed improvements found in it. See xPDOObject, and the overridden __get and __set methods. I bet that's what's causing your empty() clause to fail.

I would strongly recommend not calling empty() directly on hydrated fields or class vars. Use ->get() and then run empty on the returned var instead.

**Comment by martinf55** [comment]
martinf55 submitted:

Thanks for the quick response Shaun. That'll be it. 

Having read up on the magic methods, it seems like empty() relies on an __isset() implementation to check if the value exists before checking the actual value via __get(). When I add the following __isset() implementation based on the __get(), the 2.2.1-pl behaviour is restored for empty().

<pre><code class="php">
    public function __isset($name) {
        $set = ($this->getOption(xPDO::OPT_HYDRATE_FIELDS) && array_key_exists($name, $this->_fields))
            || ($this->getOption(xPDO::OPT_HYDRATE_RELATED_OBJECTS)
                && (array_key_exists($name, $this->_composites)
                 || array_key_exists($name, $this->_aggregates) )
               );
        return $set;
    }
</code></pre>

Obviously this also makes isset() calls return true for hydrated fields, which again matches previous behaviour.

If you think this should be implemented in xPDOObject and you want me to make a pull request, let me know.

(Point taken though about using ->get() in preference.)

**Comment by opengeek** [comment]
opengeek submitted:

I have a similar implementation tested that calls isset() on the actual _fields/_relatedObjects so we are not just testing if array_key_exists...

**Comment by opengeek** [comment]
opengeek submitted:

Though your implementation may actually be better in this case...testing...

**Comment by opengeek** [comment]
opengeek submitted:

Fixed in xPDO at https://github.com/modxcms/xpdo/commit/8dcf5c8cded1b4cab21a27c53260eb89ec16eaf8
