### ISSUE TITLE
Media Sources (upload_maxsize)

### ISSUE THREAD

**Issue by SebastienDaniel** [modxbot/migrate#8087]
Askarii created Redmine issue ID 8087

When trying to upload a file that is larger than the system's "upload_maxsize" value, the media source manager displays a "ok" message, thus leading the user to falsely believe that his file was properly uploaded.
However, the file doesn't appear in the directory.

At first this seemed to be a major bug, I was thinking that none of my files were uploading. But after a bit of research I realized it was only a size issue.

MODx Media Source manager should display a warning that the file size is too large. This would avoid misleading the user.

MODx Revo 2.2.2

**Comment by XoD** [comment]
xod submitted:

Also pay attention to the php settings (in the ini), you can set max_upload size in modx, but when php doesn't allow files above a certain size then it won't work...

**Comment by gadamiak** [comment]
gadamiak submitted:

The upload windows should contain notice about maximum allowed file size from either PHP or MODX setting, I think.

**Comment by XoD** [comment]
xod submitted:

that would be nice, yes! This could save some headakes I think =)

**Comment by Pendrokar** [comment]
pendrokar submitted:

Dublicate of #7498
