### ISSUE TITLE
Support providers to validate or checkup the domain or hostname

### ISSUE THREAD

**Issue by bertoost** [modxbot/migrate#8095]
bertoost created Redmine issue ID 8095

Support providers to validate or checkup the domain or hostname to validate the request! Very important information to the REST verifier!

**Comment by bertoost** [comment]
bertoost submitted:

I have made a pull request in github for this

https://github.com/modxcms/revolution/pull/325

**Comment by MarkH** [comment]
markh submitted:

Not a blocker to run Revolution (despite me knowing it's a blocker for you :P)
