### ISSUE TITLE
Invalid source.cache.php file

### ISSUE THREAD

**Issue by pavsyk** [modxbot/migrate#8103]
pavsyk created Redmine issue ID 8103

Sometimes (no direct cause found) the @source.cache.php@ file (@core/cache/media_sources@ directory) is created or updated with an invalid PHP syntax. E.g.:

<pre>
<?php  return array (
);<?php  return array (
);
</pre>

If it happens, all the site frontend is down and returns status 500, but the backend works properly. The only correction I found is to remove the @source.cache.php@ file (or the whole @core/cache/media_sources@ directory) manually.

**Comment by opengeek** [comment]
opengeek submitted:

Can you provide details of how PHP is configured in your environment? In particular, is this using a multi-threaded SAPI interface on an environment where flock cannot be relied upon? See the last warning at http://php.net/manual/en/function.flock.php for more information on this potential issue...

**Comment by opengeek** [comment]
opengeek submitted:

See https://github.com/modxcms/revolution/commit/5f73315081f8b8117cfb4bf9b3d9f52be36b34ea for the fix.
