### ISSUE TITLE
New PHP Warning in 2.2.3pl - easy fix here

### ISSUE THREAD

**Issue by jgulledge19** [modxbot/migrate#8108]
jgulledge19 created Redmine issue ID 8108

Here is the error I get:
_Warning:_ stristr() [function.stristr]: Empty delimiter in E:\inetpub\wwwroot\core\model\modx\modfilehandler.class.php on line 116

_Here is an easy fix wrap in conditional like so:_

<pre>
public function sanitizePath($path) {
        if ( !empty($path) ) {
            $replace = array('../' => '', './' => '', '\\' => '/', '//'  => '/');
            foreach ($replace as $from => $to) {
                while (stristr($from,$path)) {
                    $path = str_replace($from,$to,$path);
                }
            }
        }
        return $path;
    }
</pre>

**Comment by splittingred** [comment]
splittingred submitted:

Duplicate of #8105
