### ISSUE TITLE
Link from modx revo support menu to API documentation broken

### ISSUE THREAD

**Issue by robink** [modxbot/migrate#8130]
robink created Redmine issue ID 8130

support->API Documentation link in MODX revo manager goes to api.modxcms.com, which no longer resolves.
Get a 'Server not found' error

**Comment by opengeek** [comment]
opengeek submitted:

This has long been addressed in releases since 2.0.8 — the current release is 2.2.4.

**Comment by robink** [comment]
robink submitted:

ok, sorry, thought the issue was with a missing server redirect on your end.
My client is stuck on 2.0.8 due to Visioncart not running correctly on latest modx builds.

regards,
Robin
