### ISSUE TITLE
cannot change some system settings

### ISSUE THREAD

**Issue by magicjohnson** [modxbot/migrate#8138]
magicjohnson created Redmine issue ID 8138

I cannot change some system settings in version 2.2.2-pl (same problem in 2.2.4-pl), although the save dialog closes without warning or error message.
It occours with default_template, but also manager_language, fe_editor_lang and modx_charset are affected. Maybe some more (seems to me: all setting fields with dropdown, that are not yes/no).

I also tried to modify the setting of default_template directly in the database, but it has no effect.

The problem exists immediately after installation.

Hope this helps to fix the bug. Thanks!

**Comment by MarkH** [comment]
markh submitted:

I can confirm right click -> update doesn't properly send the value. I think the field needs to explicitely define name: and hiddenName: value for combo boxes.

**Comment by opengeek** [comment]
opengeek submitted:

Fixed for 2.2.7 — https://github.com/modxcms/revolution/pull/483
