### ISSUE TITLE
apc_cache_find: Clearing cache throws bunch of PHP notice: require_once(): apc_cache_find [860408] 

### ISSUE THREAD

**Issue by studiovlijmscherp** [modxbot/migrate#8155]
studiovlijmscherp created Redmine issue ID 8155

We've just moved from php 5.2 to another server with php 5.3.13

Clearing cache via Site/Clear cache throws numerous PHP notices:

<pre>

Console running...
Processing automatic publishing dates
-> 0 documents were published.
-> 0 documents were unpublished.
Regenerating system settings cache: Refresh successful!
Regenerating the context caches
-> mgr: Refresh successful!
-> web: Refresh successful!
Clearing the Snippet/Plugin script cache: Refresh successful!
Clearing the Resource cache: Refresh successful!
Clearing the lexicon topics cache: Refresh successful!

PHP notice: include_once(): 1. h->opened_path=[/home/justmemori/domains/justmemories.nl/public_html/core/model/modx/modconnectorresponse.class.php] h->filename=[/home/justmemori/domains/justmemories.nl/public_html/core/model/modx/modconnectorresponse.class.php]
PHP notice: include_once(): apc_cache_find [860627] 
PHP notice: require_once(): 1. h->opened_path=[/home/justmemori/domains/justmemories.nl/public_html/core/model/modx/modresponse.class.php] h->filename=[/home/justmemori/domains/justmemories.nl/public_html/core/model/modx/modresponse.class.php]
PHP notice: require_once(): apc_cache_find [860408] 
PHP notice: include_once(): 1. h->opened_path=[/home/justmemori/domains/justmemories.nl/public_html/core/model/modx/modprocessor.class.php] h->filename=[/home/justmemori/domains/justmemories.nl/public_html/core/model/modx/modprocessor.class.php]
PHP notice: include_once(): apc_cache_find [860606] 
PHP notice: include(): 1. h->opened_path=[null] h->filename=[/home/justmemori/domains/justmemories.nl/public_html/core/model/modx/processors/system/clearcache.php]
PHP notice: include(): apc_cache_find [1254118] 
</pre>

etc.

Problem apears on 2.2.0-pl2, 2.1.3-pl
Disabling APC (1.3.9) solves the problem.

Frontend and backend apear to function all right.

**Comment by studiovlijmscherp** [comment]
studiovlijmscherp submitted:

update: The APC Debugging is Disabled, but still throwing notices

**Comment by MarkH** [comment]
markh submitted:

You'll probably need to show some APC config
