### ISSUE TITLE
Rich Text Editor

### ISSUE THREAD

**Issue by ghost** [modxbot/migrate#8197]
sottwell created Redmine issue ID 8197

When removing a rich text editor via package management, it does not disable the use of the editor in the Configuration; attempting to load a resource will result in a blank manager page. There should at least be some kind of error message, or at least a redirect to the manager dashboard if the RTE can't be loaded.

The specific RTE that caused this problem at this time was http://modx.com/extras/package/imperavi

**Comment by ghost** [comment]
sottwell submitted:

Even after uninstalling and removing the package, and clearing the cache, the option is still in the which_editor drop-down select.

**Comment by ghost** [comment]
sottwell submitted:

It turns out that while removing the package deleted all the files, it did not remove the plugin, which of course failed without its files. Deleting the plugin from Elements solved the problem.

**Comment by MarkH** [comment]
markh submitted:

From the sounds of your last reply this is solved, so am closing the ticket. Please do post an update if it does need core fixing.
