### ISSUE TITLE
MODx.grid.Grid 'afterAutoSave' not working

### ISSUE THREAD

**Issue by bertoost** [modxbot/migrate#8209]
bertoost created Redmine issue ID 8209

The event isn't fired because the browser gives an error on 'dom' of the object (see modx.js:473).

From the updatefromgrid processor I do;

<pre>
$this->addFieldError('fied', $this->modx->lexicon('mycmp.error.field_ns'));
</pre>

The ajax request is getting nicely the response I expect. From here I want to create a message-box (alert) to show the error and after that I want to do a grid refresh to un-done the change.

Saw the "afterAutoSave" or "save_callback" but both doesn't working. Probably because modx.js:473 is throwing an error.

Unfortunate when I put "forEach" in my field error the javascript error is gone, but the afterAutoSave isn't fired too.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/81568757d7db23d1167b5846ca0e8b932e8644eb (along with some other cleanups)

**Comment by bertoost** [comment]
bertoost submitted:

I have tested the fix to replace this line in my modx.js.

<pre>
Ext.get(f.id).dom.style.border = '1px solid red';
</pre>

with these:

<pre>
var fld = Ext.get(f.id);
if (fld && fld.dom) {
    fld.dom.style.border = '1px solid red';
}
</pre>

And the error is not coming anymore, but the event "afterAutoSave" or the "save_callback" is not being triggered at all

**Comment by bertoost** [comment]
bertoost submitted:

Little note;
the event and callback are triggerd when there is a success response.. when a failure response is send, the events aren't triggerd..
