### ISSUE TITLE
How does $tags ever get populated in modparser.class.php->processElementTags

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#8278]
wshawn created Redmine issue ID 8278

Just reading through the changes in the parser for my book, and was looking at the processElementTags function -  Around line 191.  I see where it is declared, but I seem to be missing when it is actually populated for the foreach...

<pre>
$tags= array ();
        /* invoke OnParseDocument event */
        $this->modx->documentOutput = $content;
        $this->modx->invokeEvent('OnParseDocument', array('content' => &$content));
        $content = $this->modx->documentOutput;
        unset($this->modx->documentOutput);
        if ($collected= $this->collectElementTags($content, $tags, $prefix, $suffix, $tokens)) {
            $tagMap= array ();
            foreach ($tags as $tag) {
               ....
            }
</pre>

**Comment by opengeek** [comment]
opengeek submitted:

It's populated by collectElementTags() — see the &$matches parameter.
