### ISSUE TITLE
Checking if directory is writable: Failed!

### ISSUE THREAD

**Issue by mewolari** [modxbot/migrate#8313]
mewolari created Redmine issue ID 8313

After moving a site from a local server to the webserver and running setup the following message appears:

Checking if directory is writable: Failed!

All other checks during installation are OK.

Unable to find directory that is not writable.

**Comment by opengeek** [comment]
opengeek submitted:

You'll have to provide details on your environment in order for anyone to help diagnose permissions issues. I would suggest creating a forum topic to explore this issue.
