### ISSUE TITLE
Resource data pages can't be extended by Custom Resource Classes

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#8341]
netprophet created Redmine issue ID 8341

Resource data page controller extending modManagerController, while ResourceManagerController is what allows CRCs to provide alternate controllers.

**Comment by mkschell** [comment]
netprophet submitted:

Pull Request created with this commit:
https://github.com/netProphET/revolution/commit/9f12b6cf9cca06a731f1b29bc71066708c9fb2db

**Comment by opengeek** [comment]
opengeek submitted:

Fixed for 2.2.5-pl via https://github.com/modxcms/revolution/pull/343
