### ISSUE TITLE
Respect relative-path media source setting

### ISSUE THREAD

**Issue by bertoost** [modxbot/migrate#8392]
bertoost created Redmine issue ID 8392

When you have MODX installed in a subfolder (example: "projects/myproject/") you can create a media source with all relative settings set to 'true'.

For example; when the paths are set to "uploads/" and relative-settings are 'true' then the output of a imageTV is "/projects/myproject/uploads/...." and this is everything except relative. As I expect the relative should return just "uploads/...".

Now it doesn't and parsing the image-path through phpthumbof (as example) will create an error because the phpthumbof snippet also concats the base_path to the imageTV output path. So that would result in "/projects/myproject//projects/myproject/uploads/....". This is wrong of course.

So; shortly said; the output of imageTV paths should respect the relative setting against the base_path setting.

Hope you understand. I can reproduce this easily!

**Comment by bertoost** [comment]
bertoost submitted:

In core/model/modx/sources/modfilemediasource.class.php

Method prepareOutputUrl() causes this.

The $this->xpdo->context->getOption('base_url',null,MODX_BASE_URL) should not be prefixed... when the URL is relative the "baseUrl" property of the media source is just what should be prefixed.

**Comment by opengeek** [comment]
opengeek submitted:

I believe this is more an issue with phpthumbof, is it not? I don't think it should be prepending anything to what is passed to it. I would expect an image TV, when the value is prepared/processed, to prepend the base_url of the current Context. Am I misunderstanding the issue?

**Comment by bertoost** [comment]
bertoost submitted:

No I do not see this as an phpthumbof issue.
When I setup my media resource like this:

basePath: assets/uploads/
basePathRelative: Yes
baseUrl: assets/uploads/
baseUrlRelative: Yes

I expect the output from the image/file TV's should be "assets/uploads/anything.jpg" and not including my subfolders. I now get the full path absolute from the root of the server instead of relative from the install directory.

For example
- Installed MODX in: /testing/modx-test/
- my TV contains "images/Koala.jpg"
- Media Source path/url: "assets/uploads/" (relative: yes)
- Expected output: "assets/uploads/images/Koala.jpg"
- Output: "/testing/modx-test/assets/uploads/images/Koala.jpg"

phpThumbOf concats the MODX base_path to the input so that would make the path like "/testing/modx-test//testing/modx-test/assets/uploads/images/Koala.jpg" which is not good. I think phpThumbOf should concat the bas_path and the output of the TV should be relative as I set it that way.

What will happen in phpthumbof when you don't have relative settings I don't know, never use that.

**Comment by opengeek** [comment]
opengeek submitted:

After discussion with the team and some other MODX users, we all agree this is an area that needs to be refactored and clarified, but I think we need to find a more robust solution to this problem before we introduce what could end up being a breaking change for many already using 2.2.x releases.

**Comment by opengeek** [comment]
opengeek submitted:

See https://github.com/modxcms/revolution/pull/358
