### ISSUE TITLE
Cache Corruption

### ISSUE THREAD

**Issue by jgulledge19** [modxbot/migrate#8420]
jgulledge19 created Redmine issue ID 8420

On rare occasions after the cache is cleared or something triggers to make a new cache file it becomes corrupted.  How it becomes corrupted is rather then just write one version of the snippet/plugin it writes 2 complete versions starting with the <?php to the end of the file on a single file.

These are the files that can get corrupted:
\core\cache\includes\elements\
                                - modplugin\ 
                                - modsnippet\ 

I am not sure if this is a Windows PHP thing or a problem with the MODX cache engine but when it happens it leaves the site useless until the cache is cleared.  If it is a plugin then you have to manually delete the cache.

See attached file if what I am saying does not make sense.

Thanks for reviewing.

**Comment by RTOSkit** [comment]
RTOSkit submitted:

Josh Gulledge wrote:

> On rare occasions after the cache is cleared or something triggers to make a new cache file it becomes corrupted.  How it becomes corrupted is rather then just write one version of the snippet/plugin it writes 2 complete versions starting with the <?php to the end of the file on a single file.
> 
> These are the files that can get corrupted:
> \core\cache\includes\elements\
>                                 - modplugin\ 
>                                 - modsnippet\ 
> 
> I am not sure if this is a Windows PHP thing or a problem with the MODX cache engine but when it happens it leaves the site useless until the cache is cleared.  If it is a plugin then you have to manually delete the cache.
> 
> See attached file if what I am saying does not make sense.
> 
> Thanks for reviewing.

This is rather a curiosity, the file that you sent: has been modified by you or the file is unchanged?

if the file has not been changed:
you have some kind of accelerator installed in your server (ISA, IAG, etc)?

Regards.

**Comment by opengeek** [comment]
opengeek submitted:

This is an issue on an multi-threaded server that is using CGI and cannot rely on flock(). See #8423 for the underlying issue.

**Comment by opengeek** [comment]
opengeek submitted:

Fixed for 2.2.5-pl. See the related issues and commit details at https://github.com/modxcms/revolution/commit/5f73315081f8b8117cfb4bf9b3d9f52be36b34ea
