### ISSUE TITLE
tv values remain after resource is deleted and purged

### ISSUE THREAD

**Issue by noahlearner** [modxbot/migrate#8435]
noahlearner created Redmine issue ID 8435

When I recently deleted a resource and then purged it in revo2.24 I then clicked save.  When I then when into the modx_site_tmplvar_contentvalues table, the values from the resources remained.  It turns out that when you use taglister snippet it pulls from this table and also shows tags even if the resource that the tv is from has been deleted.

Can a resources tv values also be deleted when the resource is purged?

Many Thanks,

Noah

**Comment by opengeek** [comment]
opengeek submitted:

I am unable to reproduce this in 2.2.4 or the latest from the release-2.2 branch. Any additional information you can provide to help diagnose the issue you are experiencing is welcome.

**Comment by noahlearner** [comment]
noahlearner submitted:

I can't get it to reproduce any more either.

Ugh.

**Comment by noahlearner** [comment]
noahlearner submitted:

Jason,

You can mark this issue as complete.

-N
