### ISSUE TITLE
RTE Output Option for TVs does not render RTE on frontend

### ISSUE THREAD

**Issue by garryn** [modxbot/migrate#8482]
garryn created Redmine issue ID 8482

The RTE output option for TVs does not work properly and no RTE is rendered on the frontend when an RTE is installed and that option is specified for a TV.

It's a two part fix, one minor fix in Revolution and the other fixes in the TinyMCE package. I have the fixes but logging here for completeness, I just need to tidy them up before committing.

**Comment by garryn** [comment]
garryn submitted:

Core fix has been merged into release-2.2 branch, awaiting integration of the TinyMCE component updates.

**Comment by XoD** [comment]
xod submitted:

I'm not sure if this is related to a problem I had with several other RTEs I downloaded from the package manager:

If installed something like elRTE or so I can set it as the default RTE but it only gets loaded in the content editing field and not in Realtext TVs, they appear just as a normal textarea (2 rows) withot RT capabilities, this isn't the case with TinyMCE...if it is the default RTE, all TV's are setup with the TinyMCE interface. But this problem makes all other RTEs more or less useless bc I often use RTE TVs...

**Comment by opengeek** [comment]
opengeek submitted:

This core part of the fix is resolved and in 2.2.5-pl
