### ISSUE TITLE
Duplicated contexts need option to maintain alias

### ISSUE THREAD

**Issue by aladage** [modxbot/migrate#8557]
aladage created Redmine issue ID 8557

Currently, when a context is duplicated, the alias for each duplicated page is regenerated based on page name (approx. lines 974-988 in core/model/modx/modresource.class.php). I would like to see this behavior made optional.

I've discussed this issue and possible solutions with Mark Hamstra. The simple fix would be to add a yes/no system setting that allowed you to toggle this behavior, with the line $newResource->set('alias',$this->get('alias')); preserving the existing aliases.

A better, although more in-depth, solution (per Mark) would be to also add system events for OnContextDuplicate and OnContextDuplicateResource, which would make it easier for developers to write plugins to extend or override default context-duplication behavior.

**Comment by opengeek** [comment]
opengeek submitted:

See PR at https://github.com/modxcms/revolution/pull/374
