### ISSUE TITLE
Duplicated contexts need option to maintain menuindex

### ISSUE THREAD

**Issue by aladage** [modxbot/migrate#8558]
aladage created Redmine issue ID 8558

Please see the feature request at http://tracker.modx.com/issues/8557 for a near-identical issue, only with aliases. It more thoroughly describes the issue and possible resolutions.

When a context is duplicated, the new, duplicated resources have new menuindex numbers generated. I specifically need this to not happen, and would like an option to disable the new-menuindex generation and keep the old menuindex.

This could be fixed on approx. line 992 of core/model/modx/modresource.class.php, using something like $newResource->set('menuindex',$this->get('menuindex'));

**Comment by eprochasson** [comment]
eprochasson submitted:

I needed that as well. Submitted a pull request: https://github.com/modxcms/revolution/pull/374

**Comment by opengeek** [comment]
opengeek submitted:

See PR at https://github.com/modxcms/revolution/pull/374
