### ISSUE TITLE
config.inc.php lacks some single quotes at variables after fresh install

### ISSUE THREAD

**Issue by DonQuicky** [modxbot/migrate#8768]
donquicky created Redmine issue ID 8768

After installing MODX Revolution 2.2.5-dev (traditional) and pointing to the new site I was confronted with several PHP-errors about parsing character "{" in the config.inc.php.
- Parse error: syntax error, unexpected '{' in -

I examined the file and noticed that in line 13,14 and 89 the variables were enclosed without the wrapping single quotes. After adding the single quotes the errors disappeared
and could load the manager page.

**Comment by opengeek** [comment]
opengeek submitted:

I am unable to reproduce this. Any additional information you can provide about the specific steps and/or values used during install might help us further diagnose your issue.

**Comment by DonQuicky** [comment]
Old post. Not actual anymore :)
