### ISSUE TITLE
Update button in Error log

### ISSUE THREAD

**Issue by argnist** [modxbot/migrate#8859]
argnist created Redmine issue ID 8859

It is convenient to update error log while debugging without page reloading.
I use such code in ../modext/widgets/system/modx.panel.error.log.js

<pre>
,buttons: [{
            text: _('clear')
            ,handler: this.clear
            ,scope: this
            ,hidden: MODx.hasEraseErrorLog ? false : true
        },{ // that is new
            text: _('update')
            ,handler: this.update
            ,scope: this
        }]
</pre>

and 

<pre>
,update: function() {
        MODx.Ajax.request({
            url: this.config.url
            ,params: {
                action: 'get'
            }
            ,listeners: {
                'success': {fn:function(r) {
                        this.getForm().setValues(r.object);
                },scope:this}
            }
        });
    }
</pre>

**Comment by XoD** [comment]
xod submitted:

The funny thing about it is that the update button was there till version 2.1.x (if I remember right)...don't know why it was taken out^^

**Comment by gadgetto** [comment]
gadgetto submitted:
- 1

**Comment by exside** [comment]
exside submitted:

could this button may be reenabled in 2.2.7 or were there any deeper reasons to remove it?

**Comment by MarkH** [comment]
markh submitted:

Awaiting integration: https://github.com/modxcms/revolution/pull/475
