### ISSUE TITLE
Can't open Context settings since 2.2.5

### ISSUE THREAD

**Issue by gadgetto** [modxbot/migrate#8866]
gadgetto created Redmine issue ID 8866

Installed the recent Revo update to 2.2.5 - all went fine until I found out that I no longer can open the settings of any context.
If I right click on a context in resource tree and choose "Edit context" - the context settings page loads but stays greyed out and the "load spinner" runs forever.

Also the manager page for contexts (menu System -> Contexts) shows an empty list (the context in resource tree are still available).

Already cleared cache (also manually in core/cache) - flushed permission and session - cleared browser cache - tried another browser.

Seems broken with this release!

**Comment by MarkH** [comment]
markh submitted:

Forum thread: http://forums.modx.com/thread/79717/can-t-open-context-settings-since-2-2-5#dis-post-439036
