### ISSUE TITLE
Using getresourcefield breaks document save

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#8908]
onepack created Redmine issue ID 8908

When I use getresourcefield it will break the save of the documents with templates using getresourcefield.

Example:
[[getResourceField? &id=`1` &field=`copyright` &processTV=`1`]]

See also 8872

**Comment by gluethegiant** [comment]
paulmerchant submitted:

I'll update getResourceField if it's causing the problem. I'm not able to replicate the issue on my sites, even the ones that use getResourceField extensively in templates and chunks. And I'm not seeing anything wrong in the code.

Is anyone other than onepack able to replicate the problem? Does his site have a plugin that's causing the problem?

**Comment by onepack** [comment]
onepack submitted:

I have found out what is causing this save issue in the getresourcefield. 
When one of the TV's that is used in "getresourcefield" has a resource group access restriction assigned it will break the save.

(By the way I don't receive any update e-mails anymore from the redmine system. Anyone else has the same?)

**Comment by onepack** [comment]
onepack submitted:

I decided to test it a bit more and apparently all templates with tv's assigned to them that use resource access restrictions will not save when used in a document. So basically after the upgrade the resource access restriction functionality is broken.
So there is nothing wrong with the getresourcefield functionality it is something in the modx core.

**Comment by opengeek** [comment]
opengeek submitted:

Can you explain where getResourceField is being used and how it affects the Save? I don't understand what this has to do with saving anything...

**Comment by opengeek** [comment]
opengeek submitted:

See resolution for #8928
