### ISSUE TITLE
Cannot save document whit tv that has RA-restrictions

### ISSUE THREAD

**Issue by onepack** [modxbot/migrate#8987]
onepack created Redmine issue ID 8987

Please close case: 8872 and 8908

I decided to test it a bit more and apparently all templates with tv's assigned to them that use resource access restrictions will not save when used in a document. So basically after the upgrade from 2.2.4 to 2.2.5 the resource access restriction functionality is broken.
(So there is nothing wrong with the getresourcefield functionality it is something in the modx core. like I stated in case 8872 and 8908)

**Comment by opengeek** [comment]
opengeek submitted:

See resolution for #8928
