### ISSUE TITLE
phpThumb issue preventing ZC

### ISSUE THREAD

**Issue by splittingred** [modxbot/migrate#9006]
splittingred created Redmine issue ID 9006

https://github.com/splittingred/phpThumbOf/issues/19#issuecomment-9585781

Known issue in Cloud as well. Fix in GH comment has been confirmed to fix the issue in Cloud.

**Comment by opengeek** [comment]
opengeek submitted:

Unfortunately, the proposed fix requires a function that is dependent on PHP 5.3.2+, which is much higher than the MODX core's 5.1.x minimum required version. I am searching for another way to resolve the problem without using stream_resolve_include_path().

**Comment by mindeffects** [comment]
mindeffects submitted:

I would LOVE to see “phpThumbOf“ being aware of the FILEMTIME. When an image gets overwritten (=updated) the image-cache is not refreshed. THAT would be an super sweet awesome thing to have!

best
Oliver

**Comment by opengeek** [comment]
opengeek submitted:

This was addressed for 2.2.6-pl ONLY for users experiencing this issue and running PHP 5.3.2 or later. The issue is not resolved for older PHP versions, but we should enter a new ticket to track a solution to that outstanding issue.

**Comment by MathiasD** [comment]
MathiasD submitted:

The fix made here doesn't work in modx cloud on 2.2.6

In 2.2.6 the far and zc parameters doesn't work unless you remove the fix made here, and revert it to: 
if ($which_convert && ($which_convert{0} == '/') && @file_exists($which_convert)) {
