### ISSUE TITLE
Better error handling in runProcessor()

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#9029]
bobray created Redmine issue ID 9029

Line 1557 of runProcessor: 

if (!isset($this->error)) $this->request->loadErrorHandler();

If $modx->request is not set, MODX dies either silently or with a cryptic message in modParser, so a CLI script that tries to use a processor will fail unless the author knows enough to call $modx->getRequest() after initializing MODX.

Some possible fixes:
- Put getRequest() in $modx->initialize()
- Use getRequest() instead of $modx->request in runProcessor();
- Die with a clear error message if $modx->request is not set in runProcessor()

**Comment by opengeek** [comment]
opengeek submitted:

This should not depend on a modRequest instance existing, so it can be used outside a MODX request cycle. The solution is to use xPDO::getService() to load the modError class.
