### ISSUE TITLE
Resources produces a Fatal Error when saving (different context, user and resource group)

### ISSUE THREAD

**Issue by CyntaxDotDev** [modxbot/migrate#9055]
ReSpawN created Redmine issue ID 9055

We're getting a Fatal Error while saving a Resource with limited rights for the user who is executing the save action.
The error also occurs when trying to save with a SUDO user.

We tracked the error back to a TV assigned to the Resource's template being hidden by a Resource Group. The TV was assigned to all templates and one resource group, which was assigned to different user groups, including anonymous, 3 contexts including web. I should also note that the Resource being saved was in a context other than web.

The result of this problem is that we cannot hide specific TVs for our customers.

<pre>
<br />
<b>Warning</b>:  Illegal offset type in isset or empty in <b>.../public_html/core/model/modx/moduser.class.php</b> on line <b>159</b><br />
<br />
<b>Warning</b>:  Illegal offset type in <b>.../public_html/core/model/modx/moduser.class.php</b> on line <b>160</b><br />
<br />
<b>Warning</b>:  Illegal offset type in <b>.../public_html/core/model/modx/moduser.class.php</b> on line <b>164</b><br />
<br />
<b>Warning</b>:  Illegal offset type in isset or empty in <b>.../public_html/core/model/modx/modx.class.php</b> on line <b>1877</b><br />
<br />
<b>Fatal error</b>:  Call to a member function execute() on a non-object in <b>.../public_html/core/xpdo/om/xpdoobject.class.php</b> on line <b>236</b><br />
</pre>

**Comment by opengeek** [comment]
opengeek submitted:

This has already been fixed for 2.2.6 — see #8928
