### ISSUE TITLE
media sources

### ISSUE THREAD

**Issue by radekzak** [modxbot/migrate#9060]
radekzak created Redmine issue ID 9060

A new media source cannot be created using the standard $modx->newObject('modMediaSource') method.  This is due to the fact that modMediaSource model class is located under /core/model/modx/sources/ instead of /core/model/modx/ directory.  A possible solution is to either eliminate the `sources` subdirectory or modify the xpdo::_loadClass method to support subdirectories.

**Comment by radekzak** [comment]
radekzak submitted:

possible workaround for this is to register a `sources` package:

<pre>
$modx->addPackage('sources', MODX_CORE_PATH . 'model' . DIRECTORY_SEPARATOR . 'modx' . DIRECTORY_SEPARATOR);
</pre>

**Comment by opengeek** [comment]
opengeek submitted:

This is not a bug. First, modMediaSource is an abstract class; you cannot create an instance of this. You must create an instance of a specific type of media source, e.g. modFileMediaSource. Second, it is in an implicit subpackage of MODX, so the correct syntax is:

<pre>
$object = $modx->newObject('sources.modFileMediaSource');
</pre>

**Comment by radekzak** [comment]
radekzak submitted:

Thanks for the replay Jason.  However there still seems to be an issue using `sources.modFileMediaSource`.  Calling this:

<pre>
$object = $modx->newObject('sources.modFileMediaSource');
</pre>

give me the following error:

<pre>
Could not get table name for class: modFileMediaSource
</pre>

But what is interesting is that I can call this without any errors:

<pre>
$object = $modx->newObject('sources.modMediaSource');
</pre>
