### ISSUE TITLE
upload_maxsize = upload_max_filesize !!!

### ISSUE THREAD

**Issue by mindeffects** [modxbot/migrate#9072]
mindeffects created Redmine issue ID 9072

The MODX setting "upload_maxsize" has a default value of about 1MB.
Why not set this value to the server's PHP setting "upload_max_filesize" during the setup?
I just spent 30 minutes of testing and research to find this 1MB setting breaks my customers PDF upload (a 4,1MB pressbook). ;-)

thanks!
Oliver

**Comment by exside** [comment]
exside submitted:

I think this would be a very nice and easy to implement addition,why not incorporating it into the next release =)?

**Comment by theboxer** [comment]
theboxer submitted:

Added pull request https://github.com/modxcms/revolution/pull/507
