### ISSUE TITLE
tab when resources panel is closed is too small

### ISSUE THREAD

**Issue by VJPandaAU** [modxbot/migrate#9093]
xxxmicrobexxx created Redmine issue ID 9093

When the resources/elements/files panel is closed, the tab is just too small to be obvious for people who aren't aware of why their resources panel is missing.

Make it longer, make it wider.  Please go for useability over styling that frustrates.

**Comment by exside** [comment]
exside submitted:

Fix ready on gitHub, could be in 2.2.7 =)

**Comment by opengeek** [comment]
opengeek submitted:

cherry-picked into release-2.2 for inclusion in 2.2.7

see https://github.com/modxcms/revolution/commit/130c2739a12719dcaefbc44c4e872961aef75a66

**Comment by exside** [comment]
exside submitted:

great work! Kudos to you and romain (and the other contributors!)! Really working hard! Will be a great release!!!
