### ISSUE TITLE
Thumbnails for transparent PNGs are incorrect

### ISSUE THREAD

**Issue by MokoJumbie** [modxbot/migrate#9149]
MokoJumbie created Redmine issue ID 9149

This was reported in the forums some time ago and no solution was offered, so I am filing it as a bug here.

Original thread: http://forums.modx.com/thread/73644/transparent-png-thumbnails-in-manager-look-horrendous-what-to-do#dis-post-443739

The thumbnails generated for transparent PNGs are saved as JPGs, causing the appearance of their transparency to be rendered in a very ugly manner. The image format should be maintained when creating thumbnails to maintain the visual integrity of the image. or just assume PNG as the format for quality.

**Comment by onepack** [comment]
onepack submitted:

Hi There. Good that you point it out as well. I have tried on 29-10-2010 as well but the issue is still open: 

http://tracker.modx.com/issues/2662

Good luck.
