### ISSUE TITLE
Can only create new documents via right click context menu when using contexts.

### ISSUE THREAD

**Issue by vrdriver** [modxbot/migrate#9152]
vrdriver created Redmine issue ID 9152

Hi guys,
I was hoping to not post here, but I think I have to, as I think it's a bug. I've tried it in multiple browsers with the same result.

Background: (may be relevant)

At the moment I'm testing this out to get it working, and have a few contexts to test out separate user/client login areas.
I'm planning for each context to have it's own default_media_source, for individual file separation across the contexts. 
This part of it all seems to be working fine. However...

Problem:

When logging in as a "client" (with only access to an assigned context), I go to hit New Document on the toolbar. 
and get sent to a URL: server.com/manager/index.php?a=55

However, I also get:
Error!
context_err_nf

If I right click on the context, or an existing document in the tree list, I get sent to a different URL:
server.com/manager/index.php?id=0&a=55&class_key=modDocument&parent=0&context_key=spaghetti

and it works fine.

I just thought if I've got clients using this, then all toolbar links should work correctly. :)
Nothing shows up in the Modx logs of problems either.

It works fine as an admin who can see all the contexts.

MODX Rev 2.2.5-pl
mysql: 5.0.92-log
PHP Version 5.2.17

**Comment by opengeek** [comment]
opengeek submitted:

Fixed for 2.2.7 — https://github.com/modxcms/revolution/pull/484
