### ISSUE TITLE
Incorrectly comparing PHP time and MySQL NOW() in moddbregistermessage.class.php

### ISSUE THREAD

**Issue by Jacobsen** [modxbot/migrate#9178]
Jacobsen created Redmine issue ID 9178

If PHP and MySQL are running only slightly off-sync, the "valid"-timestamp of a registry message gets incorrectly excluded from output as the timestamp originates from PHP and is compared to MySQL time.

In our specific case a time-difference of only 1,5 minute makes the registry unusable as values need to be read shortly after being created.

Case:

At
PHP time 14.40 and
MySQL time 14.38
a message is input into registry.
1 minute later we attempt to read the message, but get no result as:

Line 20:
"SELECT msg.\* FROM {$msgTable} msg JOIN {$topicTable} topic ON valid _"14.40"_ <= NOW() AND (topic.name = :topic OR (topic.name = :topicbase AND msg.id = :topicmsg)) AND topic.id = msg.topic ORDER BY msg.created ASC {$limitClause}"

Code should be refactored to not depend on tightly synced systems.

**Comment by Jacobsen** [comment]
Jacobsen submitted:

I refactored the mysql implementation. See attached file.

**Comment by opengeek** [comment]
opengeek submitted:

Fixed for 2.2.6-pl
