### ISSUE TITLE
Shared hosting - modx broken (tried flock fix)...

### ISSUE THREAD

**Issue by adskiremote** [modxbot/migrate#9210]
adskiremote created Redmine issue ID 9210

Never had any issues with modx until now.

White screen, will not run any PHP used in any snippet.  I've tried the flock fix.  Setting to false.

Tried installing 2.26 and ran a simple snippet to return a string.  Even this won't run.

The sites are hosted on Rackspace.

At  the moment all modx sites are down.  Rackspace have no idea what it is.

Can anyone help with this?

**Comment by opengeek** [comment]
opengeek submitted:

This is a known issue on Rackspace Cloud Sites accounts and covered by several other tickets. We are working with the engineers from Rackspace to resolve the situation as best we can.

**Comment by CyntaxDotDev** [comment]
ReSpawN submitted:

Did you find a solution Jason?
