### ISSUE TITLE
RSS feeds looks broken in the manager

### ISSUE THREAD

**Issue by bertoost** [modxbot/migrate#9220]
bertoost created Redmine issue ID 9220

Since today I get this errors in de manager dashboard. It's because (as far I can see) the xml feed has an empty space at the first line..

<pre>
Warning: MagpieRSS: Failed to parse RSS file. (Reserved XML Name at line 1, column 38) in /***/core/model/modx/xmlrss/rssfetch.class.php on line 237

Warning: array_keys() [function.array-keys]: The first argument should be an array in /***/public_html/mgr/controllers/default/dashboard/widget.modx-news.php on line 28

Warning: Invalid argument supplied for foreach() in /***/public_html/mgr/controllers/default/dashboard/widget.modx-news.php on line 28

Warning: MagpieRSS: Failed to parse RSS file. (Reserved XML Name at line 1, column 38) in /***/core/model/modx/xmlrss/rssfetch.class.php on line 237

Warning: array_keys() [function.array-keys]: The first argument should be an array in /***/public_html/mgr/controllers/default/dashboard/widget.modx-security.php on line 25

Warning: Invalid argument supplied for foreach() in /***/public_html/mgr/controllers/default/dashboard/widget.modx-security.php on line 25
</pre>

Ps. MODX 2.2.6 is not yet in the "affects" list over here

**Comment by MarkH** [comment]
markh submitted:

Thanks Bert; has been sorted.
