### ISSUE TITLE
Save button is inactive when changing pattern of symbolic links, or simply links.

### ISSUE THREAD

**Issue by newuser** [modxbot/migrate#9287]
newuser created Redmine issue ID 9287

Inactive "Save" button when changing the template or just a symbolic link references. After changes to the template are reloaded the page and returns a page with an inactive "Save" We have to change the other fields of the resource to "Save" button becomes active.

**Comment by MarkH** [comment]
markh submitted:

Seems to have been done by Romain Tripault: https://github.com/modxcms/revolution/pull/470
