### ISSUE TITLE
Undefined context_key in resource/update processor

### ISSUE THREAD

**Issue by argnist** [modxbot/migrate#9339]
argnist created Redmine issue ID 9339

Is that right behaviour that one should add context_key value for every resource/update processor call?
@$modx->runProcessor('resource/update', array('id' => 13, 'pagetitle' => 'test'))->getResponse();@
returns error:

<pre>
Fatal error: Call to a member function getOption() on a non-object in ***/core/model/modx/processors/resource/update.class.php on line 277
</pre>

that is because on line 126:

@$this->workingContext = $this->modx->getContext($this->getProperty('context_key'));@

But in resource/create processor is another behaviour:

@public function getWorkingContext() {
        $contextKey = $this->getProperty('context_key','');
        if (empty($contextKey)) {
            $contextKey = $this->parentResource ? $this->parentResource->get('context_key') : 'web';
            $this->setProperty('context_key',$contextKey);
        }
        $this->workingContext = $this->modx->getContext($contextKey);
        return $this->workingContext;
    }@

**Comment by opengeek** [comment]
opengeek submitted:

I believe this should just use the object's context_key (or web if not set) as the default if the property is not set.

**Comment by opengeek** [comment]
opengeek submitted:

Maybe something like this:

<pre>
$this->workingContext = $this->modx->getContext($this->getProperty('context_key', $this->object->get('context_key') ? $this->object->get('context_key') : 'web'));
</pre>
