### ISSUE TITLE
No feedback when attempting to save an unpublished site_start resource

### ISSUE THREAD

**Issue by eprochasson** [modxbot/migrate#9359]
eprochasson created Redmine issue ID 9359

When attempting to unpublish a resource register as site_start, or attempting to save an unpublished site_start resource, there is no feedback given to the user (saving just fails).

The response of the POST request is : 

<pre>
{"success":false,"message":"","total":1,"data":[{"id":"published",
"msg":"The resource is linked to the site_start variable and cannot be unpublished!"}],"object":[]}
</pre>

But again, no error message displayed to the user (which is quite confusing, since the user believe everything worked fine and moves on). Note: I believed "unpublished site_start resources" should not happen, however I obtained those with two different scenarios:
- duplicating the resource with Babel (which create a linked resource, in a different context, for translation)
- right-click on the resource and select "Unpublish resource"

Maybe at least the latest should be fixed as well.

**Comment by opengeek** [comment]
opengeek submitted:

This appears to be because Ext does not provide validation errors for checkboxes — http://www.marcusschiesser.de/2009/02/151/

**Comment by opengeek** [comment]
opengeek submitted:

Found a way around it by returning the error message immediately from beforeSet().
