### ISSUE TITLE
Unicode characters removed when sanitizeString

### ISSUE THREAD

**Issue by lncknight** [modxbot/migrate#9364]
lncknight created Redmine issue ID 9364

When using the function $modx->sanitizeString(), Unicode characters can be passed.

problem related to:
https://github.com/splittingred/SimpleSearch/issues/63

**Comment by lncknight** [comment]
lncknight submitted:

When using simpleSearch to search in unicode characters, eg. Chinese/Armenian/Afrikaans. It returns garbage characters, unreadable characters in search result.
Similar issue related: https://github.com/splittingred/SimpleSearch/issues/63

It is because sanitizeString() (modx core function) empty the string when  it is unicode-speciifc characters only. Empty string breaks the function of addHighlighting()  in simpleSearch. Therefore, we may allow unciode-specific characters pass from sanitizeString() by adding unicode capacity to the regexp.

**Comment by opengeek** [comment]
opengeek submitted:

Cherry-picked into release-2.2 for inclusion in 2.2.7

https://github.com/modxcms/revolution/commit/94d0291ba4c46ae7e012c551e23d8f50b62961d9
