### ISSUE TITLE
It's not possible to set modx-combo-source as settings type

### ISSUE THREAD

**Issue by exside** [modxbot/migrate#9451]
exside created Redmine issue ID 9451

When trying to create (or edit) a system setting that should enable the user to select a media source from a dropdown there's no possibility to do that from the GUI as far as I can tell. It seems to be named as "modx-combo-source" type (got this from existing system setting "default_media_source"), but it's not selectable when not already set during installation (of extra).

I think this should be added to that type-dropdown/select menu.

**Comment by opengeek** [comment]
opengeek submitted:

https://github.com/modxcms/revolution/pull/447
