### ISSUE TITLE
Posible context wrong assign on $modx->switchContext

### ISSUE THREAD

**Issue by Indomian** [modxbot/migrate#9524]
indomian created Redmine issue ID 9524

Sometimes public array $modx->contexts can be crushed with wrong key=>object data when using $modx->switchContext.
This is caused in methods $modx->getContext and $modx->_initContext. We could get situation like this:

> echo $key.'=>'.$modx->contexts[$key]->get('key');
> 
> 'catalog'=>'web'

This is cause because of & assignment in modx::switchContext and not filling modx::contexts caching array with propriate value.
Some way to fix uploaded here: https://github.com/modxcms/revolution/pull/451

**Comment by Indomian** [comment]
indomian submitted:

Someone plz transfer this one to Revolution tracker.

**Comment by opengeek** [comment]
opengeek submitted:

https://github.com/modxcms/revolution/commit/d74dae639a61c5ab4145ead406f24d53cbe46f4b
