### ISSUE TITLE
Saving existing Template always refreshes entire site cache

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#9571]
bobray created Redmine issue ID 9571

The refresh() call  in the template update.class.php always executes, even if "Clear Cache on Save" is not checked. Maybe that property is not set if the checkbox is not checked.

public function afterSave() {
        if ($this->getProperty('clearCache',true)) {
            $this->modx->cacheManager->refresh();
        }
}

This only happens with Templates. It doesn't happen on create, only update.

**Comment by opengeek** [comment]
opengeek submitted:

Fixed — see https://github.com/modxcms/revolution/pull/482
