### ISSUE TITLE
System Setting update processor E_NOTICE errors 

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#9634]
bobray created Redmine issue ID 9634

The update processor for System Settings throws E_NOTICE errors if run outside of MODX because the 'name' and 'description' fields are not set.

A fix would be to change the updateTranslations() method in core/model/modx/processors/system/settings/update.class.php to this:

<pre>
public function updateTranslations(array $fields) {
        if (isset($fields['name'])) {
            $this->object->updateTranslation('setting_'.$this->object->get('key'),$fields['name'],array(
                'namespace' => $this->object->get('namespace'),
            ));
        }
        if (isset($fields['description'])) {
            $this->object->updateTranslation('setting_'.$this->object->get('key').'_desc',$fields['description'],array(
                'namespace' => $this->object->get('namespace'),
            ));
        }
    }

</pre>

**Comment by theboxer** [comment]
theboxer submitted:

Pull request sent
https://github.com/modxcms/revolution/pull/499

**Comment by exside** [comment]
exside submitted:

Setting target version.
