### ISSUE TITLE
Strange ini_get variable

### ISSUE THREAD

**Issue by Indomian** [modxbot/migrate#9672]
indomian created Redmine issue ID 9672

Seems in file _/core/model/modx/registry/moddbregister.class.php_ there is a bug in method _read_. Look here:

<pre>
$timeLimit = isset($options['time_limit']) ? intval($options['time_limit']) : ini_get('time_limit');
</pre>

Seems there is no 'time_limit' variable in php.ini or php settings. Found only 'max_execution_time'. Got a bug with messages synchronization on configuration where mysql is on another server.
Changed to 'max_execution_time' for my code. Please check if this a bug.

**Comment by opengeek** [comment]
opengeek submitted:

Fixed for 2.2.7-pl — thanks...
