### ISSUE TITLE
incorrect handling of server_offset_time causes auto publishing problems

### ISSUE THREAD

**Issue by mkschell** [modxbot/migrate#9690]
netprophet created Redmine issue ID 9690

In some places throughout the framework, the server_offset setting is treated as seconds, while it is intended to represent hours.
We need to ensure that
- it is always treated and calculated as # hours
- it can contain fraction and negative numbers

**Comment by mkschell** [comment]
netprophet submitted:

For reference, the fix for this also ensured that resource timestamps are stored without the server_offset_time, and that the resource editing view adds the server_offset_time, effectively showing "localized" times to the user.

**Comment by opengeek** [comment]
opengeek submitted:

https://github.com/modxcms/revolution/pull/468 for reference to the pull request
