### ISSUE TITLE
Create New Widget Tab seems empty (ref. Bug #6067)

### ISSUE THREAD

**Issue by wuuti** [modxbot/migrate#9728]
inreti created Redmine issue ID 9728

I was able to reproduce the bug from #6067: when you try to create a new dashboard widget, a screen with only an empty "General Information" tab is shown (see attached screenshot). 
The green coloring of the one and only tab gives a hint to the problem: the javascript generating the UI believes that there is another tab which is active (normally colored white). But there is not other tab if you try to create a new widget. 
Can be solved by the user by a simple click on the green "General Information" tab. The bug behind must be missing "Dashboards" tab, which is shown if you update an existing widget, but not if you try to create a new one! 

Steps to reproduce:  
# update an existing widget (maybe change the description a little bit)
# click on the "Dashboards"-Tab of this widget
# then click on save.
# click on close
# click on "Create new widget button"
# the empty "General Information" tab appears

=> the manager UI seems to remember the last active tab. When you create a new widget, the UI tries to open a tab of that type again - which (somehow) is not created at this point (why not? Choosing the dashboards is necessary on creating, isn't it?)

May this UI bug also affects other parts of modx, where the tabs shown on update are different from the tabs shown on create new?

**Comment by MarkH** [comment]
markh submitted:

Fixed and awaiting integration for 2.2.7: https://github.com/modxcms/revolution/pull/474
