### ISSUE TITLE
modAction create and update processors set lang_topics field to empty string

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#9843]
bobray created Redmine issue ID 9843

The acton/create processor does this:

<pre>
'lang_topics' => '',
</pre>

When you create an action in the Manager, that field is left empty in the modx_actions table. This means that CMPs under development will have blank or undefined language strings unless the CMP is installed via Package Manager (the field is usually set in the _build file).

I suggest two changes:
1. Add a lang_topics field to the Create/Edit Action form and set it in both the create and update processors (and maybe set it to namespace:default if it's empty).
2. In the code that implements the JS lexicon strings: _('lexString'), use the default topic if lang_topics is empty.

**Comment by theboxer** [comment]
theboxer submitted:

PR: https://github.com/modxcms/revolution/pull/574
