### ISSUE TITLE
Near infinite recursion while output modification parsing

### ISSUE THREAD

**Issue by TriAnMan** [modxbot/migrate#9859]
trianman created Redmine issue ID 9859

There is a bug makes the modParser do a near infinite recursion loop while processing TV tag with output modifier.
Also there is inadequate cache behavior for this resource.

Steps to reproduce:
# Create template_variable, assign it to any template
# modify that template like:<pre>

[[_template_variable:is=`0`:then=`noname`]]
[[_template_variable:is=`1`:then=`Natura Siberica`]]
[[_template_variable:is=`2`:then=`Organic Shop`]]
[[_template_variable:is=`3`:then=`Nature's Gate`]]
[[_template_variable:is=`4`:then=`something1`]]
[[_template_variable:is=`5`:then=`something2`]]
[[_template_variable:is=`6`:then=`K Pour Karite`]]
[[_template_variable:is=`7`:then=`DENTALYS`]]
[[_template_variable:is=`8`:then=`Love 2 mix Organic`]]
[[_template_variable:is=`9`:then=`Planeta Organica`]]
[[_template_variable:is=`10`:then=`Organic Therapy`]]
[[_template_variable:is=`11`:then=`Lactimilk`]]
[[_template_variable:is=`12`:then=`something3`]]
[[_template_variable:is=`13`:then=`ECOhysteria`]]
[[_template_variable:is=`14`:then=`Little Siberica`]]
[[_template_variable:is=`15`:then=`Organic People`]]
[[_template_variable:is=`16`:then=`Mama&Baby`]]
[[_template_variable:is=`17`:then=`Mama&Baby`]]
</pre>
# Try to open in frontend any resource with that template
# You will see a near ten times multiplied page generation time. This time will not depend on a resource caching.

It seems that modOutputFilter returns null where it has to return an empty string.

**Comment by TriAnMan** [comment]
trianman submitted:

Have made fix: https://github.com/modxcms/revolution/pull/517

**Comment by exside** [comment]
exside submitted:

What does happen if you add an empty else clause at the end (:is:then should always be used with else) like :else=``? Does the problem persist?

**Comment by TriAnMan** [comment]
trianman submitted:

:else=`` fixes this problem
But on the http://rtfm.modx.com/display/revolution20/Input+and+Output+Filters+%28Output+Modifiers%29 there is no one word about obligatory usage of :else
Eg.:

> [[+numbooks:gt=`0`:then=`Now available!`]] 

But it doesn't matter. The erroneous behavior occurs also with :show, :hide, :userinfo modifiers. The matter is the modParser. Look at this lines:

<pre>
$tagOutput= $this->processTag($tag, $processUncacheable);
if (($tagOutput === null || $tagOutput === false) && $removeUnprocessed) {
        $tagMap[$tag[0]]= '';
        $processed++;
}
elseif ($tagOutput !== null && $tagOutput !== false) {
        $tagMap[$tag[0]]= $tagOutput;
        if ($tag[0] !== $tagOutput) $processed++;
}
</pre>

modParser intends to have $tagOutput===null with $removeUnprocessed==true
or $tagOutput !== null

Our situation produces $tagOutput===null with $removeUnprocessed===false

Maybe we have to fix the modParser not the modOutputFilter? Something like this:

<pre>
$tagOutput= $this->processTag($tag, $processUncacheable);
if ($tag[0] !== $tagOutput) {
    $tagMap[$tag[0]]= (string)$tagOutput;
    $processed++;
}
</pre>

But I'm not shure because I don't understand quite well the meaning of $removeUnprocessed

**Comment by TriAnMan** [comment]
trianman submitted:

I've run unit tests on the proposed modifications of the modParser and have found that this modifications are invalid.

Also I have reviewed MODX code for other places where $tagOutput may become invalid (eg. modElement->process()) and have found that the modOutputFilter is the only place rest for bug. So my patch resolves all problems with such MODX's behavior.

Also profiling reveals that method modTemplateVar->getRenderDirectories() consumes a lot of time for it's invocation. Maybe we have to cache somewhere (eg. in private static field) results of running of the php::SplFileInfo->isReadable() and the php::SplFileInfo->isFile() called a lot by modTemplateVar->getRenderDirectories()

**Comment by TriAnMan** [comment]
trianman submitted:

Solution for modTemplateVar::getRenderDirectories() speedup - http://tracker.modx.com/issues/9896

**Comment by TriAnMan** [comment]
trianman submitted:

Found a bug in proposed "patch":https://github.com/modxcms/revolution/pull/517: getPage with placeholders in pageFirstTpl or pageLastTpl parameters doesn't generate links to first or last page.

Have to found another way to fix such not optimal behavior.

**Comment by TriAnMan** [comment]
trianman submitted:

Made another patch for this bug: https://github.com/modxcms/revolution/pull/527
Now getPage processes placeholders as expected.

So now you can fully enjoy by this speeding-up patch.

**Comment by opengeek** [comment]
opengeek submitted:

Thanks for the research and patch...will be included in 2.2.8
