### ISSUE TITLE
modTemplateVar::getRenderDirectories() speedup

### ISSUE THREAD

**Issue by TriAnMan** [modxbot/migrate#9896]
trianman created Redmine issue ID 9896

Every time modParser finds a TV modTemplateVar parses files and directories on server. Such kind of parsing burdens server a lot if there are hundreds of TVs to parse. Eg. I have a site with about 400 TVs to parse and it takes about 3 seconds to do.

Proposed patch caches directory scan results in a static variable. This reduces parsing time to 1 second.

To reproduce:
# create template variable and assign it to some template
# insert attached code into that template
# create resource for this template (you may disable caching of this resource or clear cache dir by yourself)
# you will see page generation time about 3 seconds

**Comment by TriAnMan** [comment]
trianman submitted:

Proposed patch has been published https://github.com/modxcms/revolution/pull/518
Have to be reviewed and merged.

**Comment by MarkH** [comment]
markh submitted:

Shaving off 66% of the parse time for TVs sounds really awesome!

**Comment by pixelchutes** [comment]
pixelchutes submitted:

On a 2.2.7 site, for a Template w/ approx. 25 TVs, I am seeing a pretty consistent 200ms boost per resource. I've not personally dealt with resources with hundreds of TVs before, but even at smaller numbers there appears to be some improvement.

I'm interested to hear if others experience the same (or better) results for their setups. Nice work!

**Comment by opengeek** [comment]
opengeek submitted:

Thanks for another great patch that will be in 2.2.8
