### ISSUE TITLE
Sessions and subdomains

### ISSUE THREAD

**Issue by NikADA** [modxbot/migrate#9924]
NikADA created Redmine issue ID 9924

I asked a question on the forum, but yet I have not received a response. But I think I got it right on their own.
Or maybe it's a mistake, I do not know.
I read a lot of topics on the forum, well as documentation on configuring subdomains and transfer sessions between them. How to do all the writing and all works. But I did not work until I found an article on the error in PHP more precisely in its module _suhosin_ https://bugs.php.net/bug.php?id=43682&edit=1
After turning off the following parameters it worked

<pre>
suhosin.session.cryptdocroot=Off
suhosin.cookie.cryptdocroot=Off
</pre>

But as I understand it is a manipulation of the system reduces the level of protection from intruders.

Link to post in forum: http://forums.modx.com/thread/84249/sessions-and-subdomains#dis-post-466430

**Comment by opengeek** [comment]
opengeek submitted:

This is simply how PHP sessions work, and in order to allow all subdomains to work in a single session, you have to disable those additional suhosin security features.
