### ISSUE TITLE
Categories that only contain subcategories show up as empty in the Tree

### ISSUE THREAD

**Issue by Flygenring** [modxbot/migrate#9951]
flygenring created Redmine issue ID 9951

If an element is in a subcategory, but none of the same type is in the parent category, the parent category will show up as an empty category (e.g. in my current project, I have 5 TVs I can't reach from the tree)

**Comment by Flygenring** [comment]
flygenring submitted:

I just found out I was a bit wrong. It's actually two levels down, like this:

<pre>
category
   subcategory
      sub-subcategory
         TV1
         TV2
         ...
</pre>

Shows up as if the top category was empty.

**Comment by theboxer** [comment]
theboxer submitted:

PR: https://github.com/modxcms/revolution/pull/685
