### ISSUE TITLE
Duplicate Key on Upgrade 2.2.8 - modTemplateVarResource

### ISSUE THREAD

**Issue by jasonabird** [modxbot/migrate#9965]
jasonabird created Redmine issue ID 9965

When upgrading from 2.2.7 to 2.2.8 getting following warning:
Error updating table for class modTemplateVarResource
Array
(
[0] => 42000
[1] => 1061
[2] => Duplicate key name 'tv_cnt'
)

**Comment by opengeek** [comment]
opengeek submitted:

This is simply a warning from the upgrade telling you that the index it is attempting to add to the table already exists. If it had been an actual error, install would have failed and provided a retry control.
